/** Additional safe example records for the full eight-project demonstration. */
function cbCompletionSeedFullDemoExtras_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSettings');cbAssert_(context.user.owner===true,'Only the owner can load full demo examples.');cbCompletionEnsureParitySchema_(context);var now=cbNow_(),businessId=context.row['Business ID'],projectKey='FLOWER',jobId=cbDemo8Id_('JOB',projectKey),quoteId='H38-DEMO-WEB-FLOWER',itemId=cbDemo8Id_('PRICE',projectKey,'1'),poId=cbDemo8Id_('PO',projectKey),assetId=cbDemo8Id_('ASSET','TRUCK'),documentId=cbDemo8Id_('DOCUMENT',projectKey,'CAD-1');
  cbDemo8Upsert_(context,'core','socialAccounts','Social Account ID',cbDemo8Id_('SOCIAL-ACCOUNT','H38'),{'Platform':'Instagram','Account Name':'Highway 38 Solutions Demo','Provider':'Demo — not connected','Provider Account ID':'','Connection Status':'Not Connected','Status':'Demo'});
  cbDemo8Upsert_(context,'core','featureRequests','Feature Request ID',cbDemo8Id_('FEATURE','CAD'),{'Requested By':context.user.userId,'Page Key':'quotes','User Role':context.user.roleName,'Title':'[DEMO] Review CAD overlays in Quote Builder','Problem':'Example improvement record for CAD and photo-measure workflow.','Current Workaround':'Open the linked DXF from Documents.','Frequency':'Sometimes','Proposed Action':'Add a non-editing CAD preview layer.','Status':'Demo Backlog'});
  cbDemo8Upsert_(context,'core','checklists','Checklist ID',cbDemo8Id_('CHECKLIST','FLOWER'),{'Related Record Type':'Job','Related Record ID':jobId,'Title':'[DEMO] Flower project field verification','Checklist Type':'Pre-quote','Status':'Demo Open','Created By':context.user.userId});
  ['Confirm utilities','Compare CAD to field','Verify AI photo estimate','Review Price Catalog'].forEach(function(text,index){cbDemo8Upsert_(context,'core','checklistItems','Checklist Item ID',cbDemo8Id_('CHECKITEM','FLOWER',String(index+1)),{'Checklist ID':cbDemo8Id_('CHECKLIST','FLOWER'),'Item Text':text,'Required':'Yes','Completed':index<2?'Yes':'No','Completed By':index<2?context.user.userId:'','Completed Time':index<2?now:'','Sort Order':index+1});});
  cbDemo8Upsert_(context,'core','workflows','Workflow ID',cbDemo8Id_('WORKFLOW','QUOTE'),{'Workflow Key':'demo-quote-cad-ai','Workflow Name':'[DEMO] Quote → CAD → AI Measure → Owner Review','Record Type':'Quote','Trigger Type':'Manual Demo','Status':'Active Demo','Owner Approval Required':'Yes'});
  ['Search Price Catalog first','Review linked photos and CAD','Verify AI measurements in field','Owner approves before sending'].forEach(function(label,index){cbDemo8Upsert_(context,'core','workflowSteps','Workflow Step ID',cbDemo8Id_('WORKFLOW-STEP','QUOTE',String(index+1)),{'Workflow ID':cbDemo8Id_('WORKFLOW','QUOTE'),'Step Number':index+1,'Action Key':'DEMO-'+String(index+1),'Label':label,'Configuration JSON':'{}','Owner Approval Required':index===3?'Yes':'No','Status':'Active Demo'});});
  cbDemo8Upsert_(context,'core','priceBookSnapshots','Price Snapshot ID',cbDemo8Id_('PRICE-SNAPSHOT','DEMO8'),{'Snapshot Time':now,'Source Version':'Full Demo 8','Items JSON':JSON.stringify({count:62,source:'Demo starting Price Catalog'}),'Expires Time':'','Created Time':now});
  cbDemo8Upsert_(context,'inventory','reservations','Reservation ID',cbDemo8Id_('RESERVATION','FLOWER'),{'Job ID':jobId,'Item ID':itemId,'Location ID':'LOC-MAIN-SHOP','Quantity':1,'Status':'Demo Reserved — no physical stock','Created By':context.user.userId});
  cbDemo8Upsert_(context,'inventory','purchaseOrderLines','Purchase Order Line ID',cbDemo8Id_('PO-LINE','FLOWER'),{'Purchase Order ID':poId,'Item ID':itemId,'Ordered Quantity':1,'Received Quantity':0,'Unit Cost':130,'Status':'Draft Demo — Not Ordered'});
  cbDemo8Upsert_(context,'inventory','receipts','Receipt ID',cbDemo8Id_('RECEIPT','FLOWER'),{'Vendor ID':cbDemo8Id_('VENDOR','SUPPLY'),'Job ID':jobId,'Document ID':documentId,'Receipt Date':'2026-08-01','Amount':0,'Tax':0,'Status':'Demo Placeholder — No Purchase','Created By':context.user.userId});
  cbDemo8Upsert_(context,'core','documentLinks','Document Link ID',cbDemo8Id_('DOCUMENT-LINK','FLOWER'),{'Document ID':documentId,'Related Record Type':'Quote','Related Record ID':quoteId,'Relationship':'CAD Source','Visibility':'Internal Demo','Created Time':now});
  cbDemo8Upsert_(context,'core','integrationHealth','Integration Health ID',cbDemo8Id_('HEALTH','AI'),{'Provider ID':'PROVIDER-AI','Check Type':'Demo readiness','Result':'Configured state shown in Settings','Details':'AI can fall back to Price Catalog assistance. Photo measurement requires configured AI and a linked photo.','Checked Time':now});
  cbDemo8Upsert_(context,'assets','jobEquipment','Job Equipment ID',cbDemo8Id_('JOB-EQUIPMENT','FLOWER'),{'Job ID':jobId,'Asset ID':assetId,'Requirement Type':'Demo field visit','Quantity':1,'Status':'Returned Demo','Assigned Time':now,'Returned Time':now,'Assigned By':context.user.userId,'Notes':'No real dispatch.'});
  cbDemo8Upsert_(context,'assets','servicePlans','Service Plan ID',cbDemo8Id_('SERVICE-PLAN','TRUCK'),{'Asset ID':assetId,'Plan Name':'Demo 5,000-mile service','Service Type':'Preventive maintenance','Interval Days':180,'Interval Miles':5000,'Interval Hours':0,'Last Completed Date':'2026-06-01','Last Completed Miles':45000,'Last Completed Hours':1100,'Next Due Date':'2026-12-01','Next Due Miles':50000,'Next Due Hours':0,'Status':'Active Demo'});
  cbDemo8Upsert_(context,'assets','fuelLogs','Fuel Log ID',cbDemo8Id_('FUEL','TRUCK'),{'Asset ID':assetId,'Job ID':jobId,'Gallons':0,'Fuel Cost':0,'Odometer':48500,'Engine Hours':1200,'Vendor':'Demo — no fuel purchased','Receipt Document ID':'','User ID':context.user.userId,'Timestamp':now});
  cbDemo8Upsert_(context,'core','socialApprovals','Social Approval ID',cbDemo8Id_('SOCIAL-APPROVAL','FLOWER'),{'Social Post ID':cbDemo8Id_('SOCIAL','FLOWER'),'Decision':'Pending','Requested By':context.user.userId,'Decided By':'','Requested Time':now,'Decided Time':'','Notes':'Nothing published.'});
  cbAudit_(businessId,'SEED FULL DEMO EXTRAS','Business',businessId,'PASS','Remaining safe example modules seeded. No external action performed.');
  return{status:'PASS',phase:'extras',businessId:businessId,records:['socialAccounts','featureRequests','checklists','workflow','priceBookSnapshots','reservations','purchaseOrderLines','receipts','documentLinks','integrationHealth','jobEquipment','servicePlans','fuelLogs','socialApprovals'],approved:false,sent:false,published:false,fundsMoved:false,externalActionsEnabled:false,productionDataMigrated:false};
}
