/** Social Control plus contextual AI teaching, recommendations and feature feedback. */
function cbCompletionSaveCampaign_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),record={'Campaign ID':cbText_(input.campaignId)||cbUuid_('CAMPAIGN'),'Business ID':context.row['Business ID'],'Campaign Name':cbText_(input.campaignName),'Campaign Type':cbText_(input.campaignType)||'Organic','Start Date':cbText_(input.startDate),'End Date':cbText_(input.endDate),'Budget':Number(input.budget||0),'Status':cbText_(input.status)||'Active','Goal':cbText_(input.goal),'Notes':cbText_(input.notes)};cbAssert_(record['Campaign Name'],'Campaign name is required.');var result=cbCompletionUpsert_(context,'core','campaigns','Campaign ID','CAMPAIGN',record,input);if(result.status==='PASS')cbAudit_(context.row['Business ID'],'SAVE SOCIAL CAMPAIGN','Campaign',result.recordId,'PASS','Social campaign saved.');return result;
}
function cbCompletionSaveSocialAccount_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),record={'Social Account ID':cbText_(input.socialAccountId)||cbUuid_('SOCIAL-ACCOUNT'),'Business ID':context.row['Business ID'],'Platform':cbText_(input.platform),'Account Name':cbText_(input.accountName),'Provider':cbText_(input.provider)||'Provider Neutral','Provider Account ID':cbText_(input.providerAccountId),'Connection Status':cbText_(input.connectionStatus)||'Not Connected','Status':cbText_(input.status)||'Active'};cbAssert_(record.Platform&&record['Account Name'],'Platform and account name are required.');return cbCompletionUpsert_(context,'core','socialAccounts','Social Account ID','SOCIAL-ACCOUNT',record,input);
}
function cbCompletionSaveSocialPost_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),body=cbText_(input.body),now=cbNow_();cbAssert_(body,'Social post content is required.');var id=cbText_(input.socialPostId)||cbUuid_('SOCIAL-POST'),existing=cbPlatformFindRow_(context.core,'socialPosts','Social Post ID',id),status=cbText_(input.status)||(existing?existing.Status:'Draft'),record={'Social Post ID':id,'Business ID':context.row['Business ID'],'Campaign ID':cbText_(input.campaignId),'Platform':cbText_(input.platform)||'General','Account ID':cbText_(input.accountId),'Title':cbText_(input.title),'Body':body,'Asset Document IDs JSON':JSON.stringify(input.assetDocumentIds||[]),'Link URL':cbText_(input.linkUrl),'Post Type':cbText_(input.postType)||'Standard','Status':status,'Scheduled Time':cbText_(input.scheduledTime),'Approved By':existing?existing['Approved By']:'','Approved Time':existing?existing['Approved Time']:'','Published Time':existing?existing['Published Time']:'','Provider Post ID':existing?existing['Provider Post ID']:'','Manual Proof Document ID':cbText_(input.manualProofDocumentId)||(existing?existing['Manual Proof Document ID']:''),'Created By':existing?existing['Created By']:context.user.userId,'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'socialPosts',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'socialPosts',record);}cbAudit_(context.row['Business ID'],'SAVE SOCIAL DRAFT','Social Post',id,'PASS','Social content saved internally; nothing published.');return{status:'PASS',socialPostId:id,message:'Social draft saved. Nothing published.'};
}
function cbCompletionRequestSocialReview_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),post=cbPlatformFindRow_(context.core,'socialPosts','Social Post ID',input.socialPostId),now=cbNow_();cbAssert_(post,'Social post was not found.');cbPlatformUpdateRow_(context.core,'socialPosts',post.__row,{'Status':'Pending Review','Updated Time':now,'Record Version':Math.max(1,Number(post['Record Version']||1))+1});var id=cbUuid_('SOCIAL-APPROVAL');cbAppend_(context.core,'socialApprovals',{'Social Approval ID':id,'Business ID':context.row['Business ID'],'Social Post ID':post['Social Post ID'],'Decision':'Pending','Requested By':context.user.userId,'Decided By':'','Requested Time':now,'Decided Time':'','Notes':cbText_(input.notes),'Record Version':1});return{status:'PASS',approvalId:id};
}
function cbCompletionApproveSocialPost_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial');cbAssert_(context.user.owner||cbCompletionCan_(context.user,'manageSettings'),'Owner or administrator approval is required.');var post=cbPlatformFindRow_(context.core,'socialPosts','Social Post ID',input.socialPostId),now=cbNow_();cbAssert_(post,'Social post was not found.');var decision=cbText_(input.decision).toUpperCase()==='REJECT'?'Rejected':'Approved';cbPlatformUpdateRow_(context.core,'socialPosts',post.__row,{'Status':decision==='Approved'?(post['Scheduled Time']?'Scheduled':'Owner Approved'):'Changes Requested','Approved By':decision==='Approved'?context.user.userId:'','Approved Time':decision==='Approved'?now:'','Updated Time':now,'Record Version':Math.max(1,Number(post['Record Version']||1))+1});var pending=cbRows_(context.core,'socialApprovals').filter(function(row){return row['Social Post ID']===post['Social Post ID']&&row.Decision==='Pending';});pending.forEach(function(row){cbPlatformUpdateRow_(context.core,'socialApprovals',row.__row,{'Decision':decision,'Decided By':context.user.userId,'Decided Time':now,'Notes':cbText_(input.notes)||row.Notes,'Record Version':Math.max(1,Number(row['Record Version']||1))+1});});cbAudit_(context.row['Business ID'],'DECIDE SOCIAL POST','Social Post',post['Social Post ID'],'PASS','Social review decision recorded. No publication occurred.');return{status:'PASS',decision:decision,message:'Decision recorded. Nothing published.'};
}
function cbCompletionScheduleSocialPost_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),post=cbPlatformFindRow_(context.core,'socialPosts','Social Post ID',input.socialPostId),scheduled=cbText_(input.scheduledTime),now=cbNow_();cbAssert_(post,'Social post was not found.');cbAssert_(scheduled,'Scheduled time is required.');cbPlatformUpdateRow_(context.core,'socialPosts',post.__row,{'Scheduled Time':scheduled,'Status':post['Approved By']?'Scheduled':'Draft Scheduled — Approval Required','Updated Time':now,'Record Version':Math.max(1,Number(post['Record Version']||1))+1});return{status:'PASS',message:'Schedule recorded internally. Automatic publishing remains disabled.'};
}
