/**
 * Owner-only, idempotent full demonstration seeder for all eight public examples.
 * Creates controlled demo records only. Nothing is approved, transmitted, published,
 * purchased, filed, paid or sent, and no production data is migrated.
 */
var CB_DEMO8_PREFIX='H38-DEMO8';
function cbDemo8Id_(type,key,suffix){return[CB_DEMO8_PREFIX,type,key,suffix||'001'].join('-').replace(/[^A-Za-z0-9-]/g,'-').toUpperCase();}
function cbDemo8Projects_(){return[
 {key:'FLOWER',number:'Q-DEMO-001',title:'Flower Garden Transformation',total:3950,scope:'Install a defined foundation-side flower garden with layout, sod removal, amendment, edging, cold-hardy plants, mulch, cleanup and restoration.',dims:[30,12],lines:[['Layout and bed shaping',1,'LS',200],['Sod removal',240,'sq ft',2],['Soil amendment',4.5,'cu yd',80],['Cold-hardy plants',1,'allowance',1150],['Natural-stone edging',1,'LS',1100],['Mulch and cleanup',1,'LS',660]]},
 {key:'DRIVE',number:'Q-DEMO-002',title:'Class 5 Driveway',total:6425,scope:'Supply, place, crown, grade and compact Class 5 aggregate for a residential driveway.',dims:[80,12],lines:[['Mobilization',1,'LS',650],['Subgrade shaping',960,'sq ft',1.25],['Class 5 aggregate',16,'cu yd',165],['Grading and compaction',1,'LS',1535],['Cleanup',1,'LS',400]]},
 {key:'POND',number:'Q-DEMO-003',title:'Backyard Pond & Water Feature',total:9875,scope:'Construct a small backyard pond with excavation, liner, circulation, stone edge, planting, testing and startup.',dims:[14,10],lines:[['Layout and protection',1,'LS',500],['Excavation',1,'LS',2400],['Liner system',1,'system',1900],['Pump and filtration',1,'system',2200],['Stone and planting',1,'LS',1675],['Startup and cleanup',1,'LS',1200]]},
 {key:'CLEAR',number:'Q-DEMO-004',title:'Lot Clearing & Grading',total:5950,scope:'Clear selected vegetation and rough-grade a defined residential work area.',dims:[100,100],lines:[['Mobilization',1,'LS',900],['Selected tree and brush clearing',1,'LS',2300],['Targeted grubbing',1,'LS',1200],['Rough grading',1,'LS',1150],['Cleanup',1,'LS',400]]},
 {key:'DECK',number:'Q-DEMO-005',title:"8' × 12' Pressure-Treated Deck",total:5842,scope:'Build an attached pressure-treated deck with frost-depth footings, framing, decking, stairs, guard rail, connectors, cleanup and restoration.',dims:[12,8],lines:[['Layout and mobilization',1,'LS',450],['Frost-depth footings',4,'each',285],['Framing',1,'LS',1450],['Pressure-treated decking',96,'sq ft',12],['Stairs and railing',1,'LS',1250],['Cleanup',1,'LS',400]]},
 {key:'IRRIGATION',number:'Q-DEMO-006',title:'Four-Zone Residential Irrigation System',total:3642.5,scope:'Install four irrigation zones with backflow protection, controller, sensor, valves, piping, heads, drip areas, testing, restoration and training.',dims:[100,60],lines:[['Design and layout',1,'LS',350],['Backflow and valves',1,'system',825],['Mainline and lateral piping',1,'LS',925],['Heads and drip components',1,'LS',850],['Controller and sensor',1,'system',492.5],['Testing and restoration',1,'LS',200]]},
 {key:'KITCHEN',number:'Q-DEMO-007',title:'Mid-Range Kitchen Remodel',total:18765,scope:'Complete a mid-range kitchen remodel including demolition, cabinets, quartz countertops, plumbing, backsplash, flooring, electrical, appliances, paint, trim, commissioning and closeout.',dims:[14,12],lines:[['Protection and demolition',1,'LS',2250],['Mid-range cabinets',1,'allowance',6500],['Quartz countertops',1,'allowance',3250],['Plumbing and electrical',1,'LS',2500],['Backsplash and flooring',1,'LS',2150],['Paint, trim and closeout',1,'LS',2115]]},
 {key:'CABIN',number:'Q-DEMO-008',title:'3-Bedroom, 2-Bath Northwoods Cabin',total:572550,direct:520500,scope:'Plan a 1,248-square-foot single-story three-bedroom two-bath northern Minnesota cabin on an uncleared rural lot, excluding land purchase.',dims:[48,26],lines:[['Survey, Soils and Preconstruction',1,'package',18000],['Clearing, Grading and Driveway',1,'package',34000],['Private Well',1,'package',18500],['Septic / SSTS',1,'package',24500],['Utility Service and Exterior Trenching',1,'package',11500],['House Plans, Engineering and Permits',1,'package',22000],['Insulated Slab Foundation',1,'package',32000],['Framing and Structural Shell',1,'package',58000],['Roofing',1,'package',18000],['Windows and Exterior Doors',1,'package',22000],['Siding and Exterior Finish',1,'package',24000],['Insulation and Air Sealing',1,'package',18000],['Electrical',1,'package',24000],['Plumbing',1,'package',28000],['HVAC and Ventilation',1,'package',22000],['Drywall and Painting',1,'package',22000],['Cabinets and Countertops',1,'package',28000],['Flooring, Trim and Interior Doors',1,'package',26000],['Fixtures and Appliances',1,'package',18000],['Covered Entry, Steps and Exterior Completion',1,'package',14000],['General Conditions and Project Management',1,'package',38000],['Planning contingency — 10%',1,'allowance',52050]]}
];}
function cbDemo8CabinPackages_(){return[
 ['01-SURVEY','Survey, Soils and Preconstruction',18000],['02-SITE','Clearing, Grading and Driveway',34000],['03-WELL','Private Well',18500],['04-SEPTIC','Septic / SSTS',24500],['05-UTILITY','Utility Service and Exterior Trenching',11500],['06-PLANS','House Plans, Engineering and Permits',22000],['07-SLAB','Insulated Slab Foundation',32000],['08-FRAME','Framing and Structural Shell',58000],['09-ROOF','Roofing',18000],['10-OPENINGS','Windows and Exterior Doors',22000],['11-SIDING','Siding and Exterior Finish',24000],['12-INSULATION','Insulation and Air Sealing',18000],['13-ELECTRICAL','Electrical',24000],['14-PLUMBING','Plumbing',28000],['15-HVAC','HVAC and Ventilation',22000],['16-DRYWALL','Drywall and Painting',22000],['17-CABINETS','Cabinets and Countertops',28000],['18-FINISH','Flooring, Trim and Interior Doors',26000],['19-FIXTURES','Fixtures and Appliances',18000],['20-EXTERIOR','Covered Entry, Steps and Exterior Completion',14000],['21-MANAGEMENT','General Conditions and Project Management',38000]
];}
function cbDemo8Book_(context,key){return key==='inventory'?context.inventory:key==='assets'?context.assets:context.core;}
function cbDemo8Upsert_(context,bookKey,sheet,idField,id,record){
 var book=cbDemo8Book_(context,bookKey),headers=cbCompletionHeaders_(book,sheet),existing=cbPlatformFindRow_(book,sheet,idField,id),now=cbNow_(),out={};
 headers.forEach(function(header){if(Object.prototype.hasOwnProperty.call(record,header))out[header]=record[header];});out[idField]=id;if(headers.indexOf('Business ID')>=0)out['Business ID']=context.row['Business ID'];if(headers.indexOf('Updated Time')>=0)out['Updated Time']=now;if(headers.indexOf('Record Version')>=0)out['Record Version']=existing?Math.max(1,Number(existing['Record Version']||1))+1:1;
 if(existing)cbPlatformUpdateRow_(book,sheet,existing.__row,out);else{if(headers.indexOf('Created Time')>=0)out['Created Time']=now;if(headers.indexOf('Created By')>=0&&!out['Created By'])out['Created By']=context.user.userId;cbAppend_(book,sheet,out);}return id;
}
function cbDemo8Folder_(context){var root=DriveApp.getFolderById(context.row['Tenant Root Folder ID']),name='07 — Full Demo CAD and Example Files',folders=root.getFoldersByName(name);return folders.hasNext()?folders.next():root.createFolder(name);}
function cbDemo8Dxf_(title,width,height,extras){
 var out=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1009','0','ENDSEC','0','SECTION','2','ENTITIES'];
 function line(x1,y1,x2,y2,layer){out.push('0','LINE','8',layer||'PLAN','10',String(x1),'20',String(y1),'30','0','11',String(x2),'21',String(y2),'31','0');}
 function rect(x,y,w,h,layer){line(x,y,x+w,y,layer);line(x+w,y,x+w,y+h,layer);line(x+w,y+h,x,y+h,layer);line(x,y+h,x,y,layer);}
 function text(x,y,value){out.push('0','TEXT','8','NOTES','10',String(x),'20',String(y),'30','0','40','1','1',String(value));}
 rect(0,0,width,height,'OUTLINE');text(0,height+3,title);text(0,-3,'CONTROLLED DEMO CAD — VERIFY ALL FIELD DIMENSIONS');
 (extras||[]).forEach(function(item){rect(item[0],item[1],item[2],item[3],item[4]||'DETAIL');if(item[5])text(item[0],item[1]+item[3]+1,item[5]);});
 out.push('0','ENDSEC','0','EOF');return out.join('\n');
}
function cbDemo8CadPlans_(project){var w=project.dims[0],h=project.dims[1],plans=[{name:project.key+'-PLAN.dxf',title:project.title+' plan',w:w,h:h,extras:[]}];
 if(project.key==='FLOWER')plans[0].extras=[[3,2,22,7,'BED','Planting bed']];
 if(project.key==='DRIVE')plans[0].extras=[[0,4,80,4,'CENTER','Crowned travel lane']];
 if(project.key==='POND')plans[0].extras=[[2,2,10,6,'WATER','Pond basin']];
 if(project.key==='CLEAR')plans[0].extras=[[20,20,60,60,'CLEAR','Approved clearing zone']];
 if(project.key==='DECK')plans[0].extras=[[1,1,10,6,'FRAMING','Joist field']];
 if(project.key==='IRRIGATION')plans[0].extras=[[5,5,40,22,'ZONE-1','Zone 1'],[55,5,40,22,'ZONE-2','Zone 2'],[5,33,40,22,'ZONE-3','Zone 3'],[55,33,40,22,'ZONE-4','Zone 4']];
 if(project.key==='KITCHEN')plans[0].extras=[[1,1,12,2,'CABINETS','Cabinet run'],[5,5,4,2,'ISLAND','Island']];
 if(project.key==='CABIN')plans=[
  {name:'CABIN-FLOOR-PLAN.dxf',title:'Northwoods Cabin floor plan',w:48,h:26,extras:[[0,0,16,13,'BEDROOM','Bedroom 1'],[0,13,16,13,'BEDROOM','Bedroom 2'],[16,0,14,10,'PRIMARY','Primary suite'],[16,10,14,16,'CORE','Kitchen / living'],[30,0,18,26,'CORE','Living / dining']]},
  {name:'CABIN-SITE-PLAN.dxf',title:'Northwoods Cabin conceptual site plan',w:200,h:150,extras:[[76,62,48,26,'BUILDING','Cabin footprint'],[0,68,76,14,'DRIVE','Class 5 drive'],[130,40,35,25,'SEPTIC','Septic area'],[160,105,4,4,'WELL','Well']]},
  {name:'CABIN-SLAB-PLAN.dxf',title:'Northwoods Cabin slab concept',w:48,h:26,extras:[[2,2,44,22,'SLAB','Insulated slab'],[20,0,8,26,'PLUMBING','Under-slab plumbing zone']]}
 ];return plans;}
function cbDemo8CadFile_(folder,plan){var files=folder.getFilesByName(plan.name);if(files.hasNext())return files.next();return folder.createFile(Utilities.newBlob(cbDemo8Dxf_(plan.title,plan.w,plan.h,plan.extras),'application/dxf',plan.name)).setDescription('Highway 38 controlled demonstration CAD. Verify all field dimensions and engineering requirements.');}
function cbDemo8Document_(context,project,quoteId,file,index){var documentId=cbDemo8Id_('DOCUMENT',project.key,'CAD-'+index),attachmentId=cbDemo8Id_('ATTACHMENT',project.key,'CAD-'+index),now=cbNow_();cbDemo8Upsert_(context,'core','documents','Document ID',documentId,{'Source Type':'CAD','Source ID':quoteId,'File ID':file.getId(),'File Name':file.getName(),'Mime Type':'application/dxf','Access Classification':'Internal Demo','Created By':context.user.userId,'Created Time':now});cbDemo8Upsert_(context,'core','attachments','Attachment ID',attachmentId,{'Document ID':documentId,'Related Record Type':'Quote','Related Record ID':quoteId,'File ID':file.getId(),'File Name':file.getName(),'Mime Type':'application/dxf','File Size':file.getSize(),'Capture Time':now,'Upload Status':'Uploaded','Visibility':'Internal Demo','Created By':context.user.userId,'Created Time':now});return documentId;}
function cbDemo8SeedCore_(context){
 var customerId=cbCompletionEnsureGenericQuoteCustomer_(context),folder=cbDemo8Folder_(context),projects=cbDemo8Projects_(),summary={projects:0,quotes:0,cadFiles:0,measurements:0};
 projects.forEach(function(project,index){var key=project.key,propertyId=cbDemo8Id_('PROPERTY',key),requestId=cbDemo8Id_('REQUEST',key),jobId=cbDemo8Id_('JOB',key),quoteId=cbDemo8Id_('QUOTE',key),now=cbNow_();
  cbDemo8Upsert_(context,'core','properties','Property ID',propertyId,{'Customer ID':customerId,'Property Name':'[DEMO] '+project.title+' Site','Address':(101+index)+' Demo Project Road, Grand Rapids, MN 55744','Status':'Active Demo'});
  cbDemo8Upsert_(context,'core','contacts','Contact ID',cbDemo8Id_('CONTACT',key),{'Customer ID':customerId,'Contact Name':project.title+' Demo Contact','Email':key.toLowerCase()+'.demo@example.invalid','Phone':'218-555-'+String(1100+index),'Role':'Demo Contact','Preferred Channel':'Internal only','Status':'Active Demo'});
  cbDemo8Upsert_(context,'core','requests','Request ID',requestId,{'Customer ID':customerId,'Property ID':propertyId,'Source':'Public Website Example','Subject':'[DEMO] '+project.title,'Details':project.scope,'Priority':'Normal','Assigned User ID':context.user.userId,'Status':'Demo — Complete','Created By':context.user.userId});
  cbDemo8Upsert_(context,'core','jobs','Job ID',jobId,{'Customer ID':customerId,'Property ID':propertyId,'Job Number':'JOB-'+project.number,'Project Title':'[DEMO] '+project.title,'Status':'Demo — Planning','Location ID':'LOC-MAIN-SHOP','Crew ID':''});
  cbCompletionSaveQuote_({businessId:context.row['Business ID'],quoteId:quoteId,quoteNumber:project.number,customerId:customerId,propertyId:propertyId,jobId:jobId,projectTitle:'[DEMO] Website Example — '+project.title,scope:'DEMO RECORD — NO FUNDS MOVED. '+project.scope,measurementNotes:'CAD source dimensions are included in Documents. AI photo estimates remain unverified.',status:'Demo — Owner Review',tax:0,lines:project.lines.map(function(line,lineIndex){return{quoteLineId:cbDemo8Id_('QUOTE-LINE',key,String(lineIndex+1)),description:line[0],quantity:line[1],unit:line[2],unitPrice:line[3],lineType:'Demo Website Example',priceSource:'Demo starting Price Catalog',priceStatus:'Owner review required'};})});summary.quotes+=1;
  cbDemo8Upsert_(context,'core','measurements','Measurement ID',cbDemo8Id_('MEASUREMENT',key,'CAD'),{'Job ID':jobId,'Quote ID':quoteId,'Related Record Type':'Quote','Related Record ID':quoteId,'Measurement Name':'Primary CAD footprint','Measurement Type':'Area / footprint','Value':project.dims[0]*project.dims[1],'Unit':'sq ft','Method':'CAD source','Confidence':'Verified from demo CAD only','Reference Size':project.dims[0],'Reference Unit':'ft','Notes':'Controlled CAD example. Real field conditions and engineering remain subject to verification.','Status':'Demo Verified'});summary.measurements+=1;
  cbDemo8Upsert_(context,'core','measurements','Measurement ID',cbDemo8Id_('MEASUREMENT',key,'AI'),{'Job ID':jobId,'Quote ID':quoteId,'Related Record Type':'Quote','Related Record ID':quoteId,'Measurement Name':'AI-assisted visible dimension example','Measurement Type':'Length','Value':Math.round(project.dims[0]*0.97*10)/10,'Unit':'ft','Method':'AI-assisted photo estimate','Confidence':'Needs verification','Reference Size':12,'Reference Unit':'in','Notes':'AI ESTIMATE — FIELD VERIFICATION REQUIRED. Demonstrates reference-scaled photo measuring.','Status':'Needs Verification'});summary.measurements+=1;
  cbDemo8Upsert_(context,'core','measurementPoints','Measurement Point ID',cbDemo8Id_('POINT',key,'A'),{'Measurement ID':cbDemo8Id_('MEASUREMENT',key,'CAD'),'Point Label':'A','X':0,'Y':0,'Z':0,'Sequence':1,'Notes':'CAD origin'});
  cbDemo8Upsert_(context,'core','measurementPoints','Measurement Point ID',cbDemo8Id_('POINT',key,'B'),{'Measurement ID':cbDemo8Id_('MEASUREMENT',key,'CAD'),'Point Label':'B','X':project.dims[0],'Y':project.dims[1],'Z':0,'Sequence':2,'Notes':'Opposite CAD corner'});
  cbDemo8CadPlans_(project).forEach(function(plan,planIndex){var file=cbDemo8CadFile_(folder,plan);cbDemo8Document_(context,project,quoteId,file,planIndex+1);summary.cadFiles+=1;});
  cbAudit_(context.row['Business ID'],'SEED FULL DEMO CORE','Quote',quoteId,'PASS','Controlled project, quote, CAD and measurement examples seeded.');summary.projects+=1;
 });
 cbDemo8CabinPackages_().forEach(function(pkg,pkgIndex){var quoteId=cbDemo8Id_('CABIN-QUOTE',pkg[0]),jobId=cbDemo8Id_('JOB','CABIN'),customerId=cbCompletionEnsureGenericQuoteCustomer_(context);cbCompletionSaveQuote_({businessId:context.row['Business ID'],quoteId:quoteId,quoteNumber:'Q-DEMO-008-'+pkg[0],customerId:customerId,jobId:jobId,projectTitle:'[DEMO] Cabin Package — '+pkg[1],scope:'Controlled cabin planning sub-quote. No purchase, approval or customer promise.',status:'Demo — Owner Review',tax:0,lines:[{quoteLineId:cbDemo8Id_('CABIN-LINE',pkg[0]),description:pkg[1],quantity:1,unit:'package',unitPrice:pkg[2],lineType:'Cabin sub-quote',priceSource:'Demo starting Price Catalog',priceStatus:'Owner review required'}]});summary.quotes+=1;});return summary;
}
function cbDemo8SeedCatalog_(context){var projects=cbDemo8Projects_(),summary={priceItems:0,transactions:0,materialRequests:0,assets:0};
 projects.forEach(function(project){project.lines.forEach(function(line,index){var id=cbDemo8Id_('PRICE',project.key,String(index+1)),sku='DEMO-'+project.key+'-'+String(index+1).padStart(2,'0');cbDemo8Upsert_(context,'inventory','items','Item ID',id,{'SKU':sku,'Description':line[0],'Category':'Demo Price Catalog — '+project.key,'Unit of Measure':line[2],'Purchase Unit':line[2],'Issue Unit':line[2],'Purchase Cost':Math.round(line[3]*0.65*100)/100,'Average Cost':Math.round(line[3]*0.65*100)/100,'Selling Price':line[3],'Taxable Status':'Review','Minimum Stock':0,'Maximum Stock':0,'Reorder Point':0,'Serial Tracking':'No','Lot Tracking':'No','Expiration Tracking':'No','Status':'Active Demo'});summary.priceItems+=1;});
  var firstItem=cbDemo8Id_('PRICE',project.key,'1'),jobId=cbDemo8Id_('JOB',project.key);cbDemo8Upsert_(context,'inventory','transactions','Transaction ID',cbDemo8Id_('TXN',project.key),{'Location ID':'LOC-MAIN-SHOP','Item ID':firstItem,'Quantity':5,'Direction':'IN','Unit Cost':project.lines[0][3]*0.65,'Total Value':project.lines[0][3]*0.65*5,'Job ID':jobId,'User ID':context.user.userId,'Source Type':'Controlled Demo','Source Record ID':cbDemo8Id_('QUOTE',project.key),'Reason':'DEMO STOCK — NO PHYSICAL INVENTORY MOVED','Timestamp':cbNow_(),'Idempotency Key':cbDemo8Id_('IDEMPOTENCY',project.key),'Sync Status':'DEMO','Audit Metadata JSON':JSON.stringify({demo:true,noPhysicalStockMoved:true})});summary.transactions+=1;
  cbDemo8Upsert_(context,'inventory','materialRequests','Material Request ID',cbDemo8Id_('MATERIAL',project.key),{'Job ID':jobId,'Requested By':context.user.userId,'Assigned To':'','Needed Date':'2026-09-01','Priority':'Normal','Items JSON':JSON.stringify([{itemId:firstItem,quantity:1}]),'Status':'Demo — Owner Review','Notes':'Controlled material request. Nothing purchased or transmitted.'});summary.materialRequests+=1;
 });
 var assetId=cbDemo8Id_('ASSET','TRUCK'),vehicleId=cbDemo8Id_('VEHICLE','TRUCK');cbDemo8Upsert_(context,'assets','assets','Asset ID',assetId,{'Asset Number':'DEMO-TRUCK-01','Manufacturer':'Ford','Model':'F-250','Description':'[DEMO] Field service truck','Category':'Vehicle','Ownership':'Demo','Current Location ID':'LOC-MAIN-SHOP','Status':'Active Demo','Availability':'Available','Mileage':48500,'Inspection Interval':'30 days','Maintenance Interval':'5000 mi'});cbDemo8Upsert_(context,'assets','vehicles','Vehicle ID',vehicleId,{'Asset ID':assetId,'VIN':'DEMO-NOT-A-REAL-VIN','License Plate':'DEMO-38','Year':2024,'Make':'Ford','Model':'F-250','Vehicle Type':'Service Truck','Fuel Type':'Gasoline','GVWR':'','Odometer':48500,'Engine Hours':1200,'Status':'Active Demo'});summary.assets+=1;
 cbDemo8Upsert_(context,'assets','assignments','Asset Assignment ID',cbDemo8Id_('ASSIGNMENT','TRUCK'),{'Asset ID':assetId,'User ID':context.user.userId,'Job ID':cbDemo8Id_('JOB','FLOWER'),'Location ID':'LOC-MAIN-SHOP','Assignment Type':'Demo Job Assignment','Assigned Time':cbNow_(),'Status':'Returned Demo','Condition Out':'Good','Condition In':'Good','Created By':context.user.userId,'Updated By':context.user.userId});
 cbDemo8Upsert_(context,'assets','maintenance','Maintenance ID',cbDemo8Id_('MAINTENANCE','TRUCK'),{'Asset ID':assetId,'Maintenance Type':'Oil and inspection','Status':'Scheduled Demo','Priority':'Normal','Due Date':'2026-09-15','Labor Hours':0,'Parts Cost':0,'Labor Cost':0,'Downtime Hours':0,'Notes':'Demo maintenance record; no service ordered.'});
 cbDemo8Upsert_(context,'assets','inspections','Inspection ID',cbDemo8Id_('INSPECTION','TRUCK'),{'Asset ID':assetId,'Inspection Type':'Pre-trip demo','Result':'Pass Demo','Meter Reading':1200,'Mileage':48500,'Notes':'Controlled example inspection.','Inspected By':context.user.userId,'Inspection Time':cbNow_()});
 cbDemo8Upsert_(context,'assets','usageLogs','Usage Log ID',cbDemo8Id_('USAGE','TRUCK'),{'Asset ID':assetId,'Job ID':cbDemo8Id_('JOB','FLOWER'),'User ID':context.user.userId,'Start Time':'2026-08-01T08:00:00Z','End Time':'2026-08-01T10:00:00Z','Start Mileage':48490,'End Mileage':48500,'Usage Type':'Demo field visit','Notes':'No real vehicle movement recorded.','Offline Operation ID':''});return summary;}
function cbDemo8SeedOperations_(context){var projects=cbDemo8Projects_(),summary={workOrders:0,tasks:0,schedule:0,communications:0,ai:0};
 projects.forEach(function(project,index){var key=project.key,jobId=cbDemo8Id_('JOB',key),quoteId=cbDemo8Id_('QUOTE',key),customerId=cbCompletionEnsureGenericQuoteCustomer_(context),workId=cbDemo8Id_('WORK',key);cbDemo8Upsert_(context,'core','workOrders','Work Order ID',workId,{'Job ID':jobId,'Customer ID':customerId,'Property ID':cbDemo8Id_('PROPERTY',key),'Work Order Number':'WO-'+project.number,'Title':'[DEMO] Verify '+project.title,'Scope':'Field verification, CAD comparison, photo capture and owner review.','Assigned User ID':context.user.userId,'Status':'Demo — Not Scheduled','Priority':'Normal','Closeout Requirements JSON':JSON.stringify(['Verify critical dimensions','Capture proof','Owner review required'])});summary.workOrders+=1;
  ['Verify site and utilities','Review CAD, AI measurement and Price Catalog'].forEach(function(title,taskIndex){cbDemo8Upsert_(context,'core','tasks','Task ID',cbDemo8Id_('TASK',key,String(taskIndex+1)),{'Job ID':jobId,'Task Title':title,'Assigned User ID':context.user.userId,'Status':'Demo — Open','Due Time':'2026-09-'+String(10+index).padStart(2,'0')+'T15:00:00Z'});summary.tasks+=1;});
  cbDemo8Upsert_(context,'core','scheduleEvents','Schedule Event ID',cbDemo8Id_('SCHEDULE',key),{'Event Type':'Demo Site Visit','Title':'[DEMO] '+project.title+' verification','Related Record Type':'Job','Related Record ID':jobId,'Assigned User ID':context.user.userId,'Start Time':'2026-09-'+String(10+index).padStart(2,'0')+'T14:00:00Z','End Time':'2026-09-'+String(10+index).padStart(2,'0')+'T15:00:00Z','Location':'Demo Project Road','Status':'Demo — Not Dispatched','Notes':'Nothing scheduled externally.'});summary.schedule+=1;
  cbDemo8Upsert_(context,'core','timeEntries','Time Entry ID',cbDemo8Id_('TIME',key),{'User ID':context.user.userId,'Job ID':jobId,'Start Time':'2026-08-01T08:00:00Z','End Time':'2026-08-01T09:00:00Z','Break Minutes':0,'Hours':1,'Status':'Demo Recorded','Notes':'Example only; not payroll-authoritative.'});
  cbDemo8Upsert_(context,'core','jobNotes','Job Note ID',cbDemo8Id_('NOTE',key),{'Job ID':jobId,'Note Type':'Demo handoff','Body':'Use CAD dimensions as source data. AI photo measurements remain needs verification. Quote and pricing remain owner-review required.','Visibility':'Internal Demo','Created By':context.user.userId,'Created Time':cbNow_()});
  var conversationId=cbDemo8Id_('CONVERSATION',key);cbDemo8Upsert_(context,'core','conversations','Conversation ID',conversationId,{'Conversation Type':'Internal Demo','Subject':'[DEMO] '+project.title,'Related Record Type':'Quote','Related Record ID':quoteId,'Participant IDs JSON':JSON.stringify([context.user.userId]),'Status':'Active Demo'});cbDemo8Upsert_(context,'core','messages','Message ID',cbDemo8Id_('MESSAGE',key),{'Conversation ID':conversationId,'Sender User ID':context.user.userId,'Message Type':'Internal','Body':'Review scope, CAD files, Price Catalog matches and AI measurement warnings before any customer action.','Attachment IDs JSON':'[]','Status':'Demo Draft','Created Time':cbNow_()});
  cbDemo8Upsert_(context,'core','emailThreads','Email Thread ID',cbDemo8Id_('EMAIL-THREAD',key),{'Provider':'Demo','Provider Thread ID':'','Mailbox':'Drafts','Subject':'[DEMO] '+project.title+' quote review','Customer ID':customerId,'Job ID':jobId,'Quote ID':quoteId,'Assigned User ID':context.user.userId,'Needs Reply':'No','Last Message Time':cbNow_(),'Status':'Draft Demo'});cbDemo8Upsert_(context,'core','emailMessages','Email Message ID',cbDemo8Id_('EMAIL',key),{'Email Thread ID':cbDemo8Id_('EMAIL-THREAD',key),'Direction':'Draft','From Address':'highway38solutions@gmail.com','To Addresses JSON':'["demo@example.invalid"]','Subject':'[DEMO] '+project.title,'Body Preview':'Draft only. Not sent.','Message Time':cbNow_(),'Status':'Draft Demo'});
  cbDemo8Upsert_(context,'core','smsThreads','SMS Thread ID',cbDemo8Id_('SMS-THREAD',key),{'Provider':'Demo','Provider Thread ID':'','Business Number':'DEMO','Customer Number':'DEMO','Customer ID':customerId,'Job ID':jobId,'Quote ID':quoteId,'Assigned User ID':context.user.userId,'Consent Status':'Demo Only','Needs Reply':'No','Last Message Time':cbNow_(),'Status':'Draft Demo'});cbDemo8Upsert_(context,'core','smsMessages','SMS Message ID',cbDemo8Id_('SMS',key),{'SMS Thread ID':cbDemo8Id_('SMS-THREAD',key),'Direction':'Draft','From Number':'DEMO','To Number':'DEMO','Body':'Draft only — not sent.','Media Document IDs JSON':'[]','Delivery Status':'Not Sent','Consent Status':'Demo Only','Message Time':cbNow_(),'Status':'Draft Demo'});
  cbDemo8Upsert_(context,'core','customerPortalThreads','Portal Thread ID',cbDemo8Id_('PORTAL-THREAD',key),{'Customer ID':customerId,'Related Record Type':'Quote','Related Record ID':quoteId,'Subject':'[DEMO] '+project.title,'Status':'Draft Demo'});cbDemo8Upsert_(context,'core','customerPortalMessages','Portal Message ID',cbDemo8Id_('PORTAL',key),{'Portal Thread ID':cbDemo8Id_('PORTAL-THREAD',key),'Sender Type':'Business Draft','Sender ID':context.user.userId,'Body':'Portal draft example. Not released to a customer.','Attachment IDs JSON':'[]','Message Time':cbNow_(),'Status':'Draft Demo'});summary.communications+=1;
  var aiConversationId=cbDemo8Id_('AI-CONVERSATION',key);cbDemo8Upsert_(context,'core','aiConversations','AI Conversation ID',aiConversationId,{'User ID':context.user.userId,'Title':'[DEMO] AI quote assistance — '+project.title,'Context JSON':JSON.stringify({quoteId:quoteId,priceBookSearchedFirst:true,cadDocumentsLinked:true}),'Status':'Active Demo'});cbDemo8Upsert_(context,'core','aiMessages','AI Message ID',cbDemo8Id_('AI-USER',key),{'AI Conversation ID':aiConversationId,'Role':'User','Body':'Build an owner-review quote using the Price Catalog, CAD dimensions and site notes.','Sources JSON':'[]','Action JSON':'{}'});cbDemo8Upsert_(context,'core','aiMessages','AI Message ID',cbDemo8Id_('AI-ASSISTANT',key),{'AI Conversation ID':aiConversationId,'Role':'Assistant','Body':'Price Catalog searched first. CAD dimensions retained as source data. Photo-derived quantities require field verification. Nothing approved or sent.','Sources JSON':JSON.stringify([cbDemo8Id_('DOCUMENT',key,'CAD-1')]),'Action JSON':JSON.stringify({ownerReviewRequired:true,automaticApproval:false,automaticSend:false})});cbDemo8Upsert_(context,'core','actionQueue','Action Queue ID',cbDemo8Id_('ACTION',key),{'User ID':context.user.userId,'Action Type':'REVIEW AI QUOTE DRAFT','Related Record Type':'Quote','Related Record ID':quoteId,'Payload JSON':JSON.stringify({priceBookSearchedFirst:true,cadSource:true,aiMeasurementNeedsVerification:true}),'Risk Level':'Owner Review Required','Review State':'Pending','Status':'Pending Review'});summary.ai+=1;
  cbDemo8Upsert_(context,'core','voiceQueue','Voice Queue ID',cbDemo8Id_('VOICE',key),{'User ID':context.user.userId,'Mode':'Field Demo','Transcript':'Add a field note for '+project.title,'Intent':'Create internal job note','Related Record Type':'Job','Related Record ID':jobId,'Risk Level':'Low','Review Required':'Yes','Status':'Demo Captured'});
  cbDemo8Upsert_(context,'core','notifications','Notification ID',cbDemo8Id_('NOTICE',key),{'User ID':context.user.userId,'Notification Type':'Demo Review','Title':'Review '+project.title,'Body':'CAD, pricing and AI measurement examples are ready for owner review.','Related Record Type':'Quote','Related Record ID':quoteId,'Priority':'Normal','Status':'Unread Demo'});
 });return summary;}
function cbDemo8SeedFinance_(context){var projects=cbDemo8Projects_(),summary={invoices:0,expenses:0,purchaseOrders:0,employees:0,social:0};
 var employeeId=cbDemo8Id_('EMPLOYEE','FIELD');cbDemo8Upsert_(context,'core','employees','Employee ID',employeeId,{'User ID':context.user.userId,'Display Name':'Demo Field Specialist','Email':'employee.demo@example.invalid','Employment Type':'Demo','Pay Type':'Hourly','Hourly Rate':28,'Overtime Multiplier':1.5,'Crew':'Demo Crew','Status':'Active Demo','Start Date':'2026-01-01','Notes':'Example employee; no payroll submitted.'});summary.employees+=1;
 var vendorId=cbDemo8Id_('VENDOR','SUPPLY');cbDemo8Upsert_(context,'inventory','vendors','Vendor ID',vendorId,{'Vendor Name':'Demo Materials Supplier','Contact Name':'Demo Contact','Email':'vendor.demo@example.invalid','Phone':'218-555-0199','Category':'General Materials','Payment Terms':'Net 30 Demo','Status':'Active Demo','Notes':'No orders transmitted.'});
 projects.forEach(function(project,index){var key=project.key,quoteId=cbDemo8Id_('QUOTE',key),jobId=cbDemo8Id_('JOB',key),customerId=cbCompletionEnsureGenericQuoteCustomer_(context),invoiceId=cbDemo8Id_('INVOICE',key),expenseId=cbDemo8Id_('EXPENSE',key),poId=cbDemo8Id_('PO',key);
  cbDemo8Upsert_(context,'core','invoices','Invoice ID',invoiceId,{'Customer ID':customerId,'Job ID':jobId,'Quote ID':quoteId,'Invoice Number':'INV-'+project.number,'Invoice Type':'Demo Draft','Status':'Draft Demo — Not Sent','Issue Date':'2026-08-01','Due Date':'2026-09-01','Subtotal':project.total,'Tax':0,'Total':project.total,'Balance':project.total,'Notes':'Example only. Nothing invoiced or sent.','Created By':context.user.userId});cbDemo8Upsert_(context,'core','invoiceLines','Invoice Line ID',cbDemo8Id_('INVOICE-LINE',key),{'Invoice ID':invoiceId,'Description':project.title+' demo draft','Quantity':1,'Unit':'project','Unit Price':project.total,'Line Total':project.total,'Status':'Demo Draft'});summary.invoices+=1;
  cbDemo8Upsert_(context,'core','payments','Payment ID',cbDemo8Id_('PAYMENT',key),{'Invoice ID':invoiceId,'Customer ID':customerId,'Payment Date':'','Amount':0,'Method':'Demo — no funds moved','Reference':'','Status':'DEMO RECORD — NO FUNDS MOVED','Recorded By':context.user.userId});
  cbDemo8Upsert_(context,'core','expenses','Expense ID',expenseId,{'Job ID':jobId,'Vendor ID':vendorId,'Category':'Demo materials','Description':'Prepared cost example for '+project.title,'Expense Date':'2026-08-01','Amount':Math.round(project.total*0.35*100)/100,'Tax':0,'Payment Method':'Not paid — demo','Status':'Demo — Accounting Review','Created By':context.user.userId});summary.expenses+=1;
  cbDemo8Upsert_(context,'inventory','purchaseOrders','Purchase Order ID',poId,{'Vendor ID':vendorId,'Job ID':jobId,'Location ID':'LOC-MAIN-SHOP','Order Number':'PO-'+project.number,'Order Date':'','Expected Date':'','Description':'Demo material planning for '+project.title,'Subtotal':Math.round(project.total*0.35*100)/100,'Tax':0,'Total':Math.round(project.total*0.35*100)/100,'Status':'Draft Demo — Not Transmitted','Approval Status':'Owner Review Required','Approved By':'','Created By':context.user.userId});summary.purchaseOrders+=1;
  cbDemo8Upsert_(context,'core','approvals','Approval ID',cbDemo8Id_('APPROVAL',key),{'Area':'Quotes','Record Type':'Quote','Record ID':quoteId,'Approval Type':'Owner Quote Review','Request':'Review scope, CAD, AI measurement and pricing.','Requested By':context.user.userId,'Requested Time':cbNow_(),'Decision':'','Status':'Pending Demo','Notes':'Nothing is automatically approved.'});
  var campaignId=cbDemo8Id_('CAMPAIGN',key),postId=cbDemo8Id_('SOCIAL',key);cbDemo8Upsert_(context,'core','campaigns','Campaign ID',campaignId,{'Campaign Name':'[DEMO] '+project.title,'Campaign Type':'Portfolio Example','Start Date':'','End Date':'','Budget':0,'Status':'Draft Demo','Goal':'Demonstrate project workflow','Notes':'Not published.'});cbDemo8Upsert_(context,'core','socialPosts','Social Post ID',postId,{'Campaign ID':campaignId,'Platform':'Instagram','Account ID':'','Title':'[DEMO] '+project.title,'Body':'Draft social example for the controlled demo project.','Asset Document IDs JSON':JSON.stringify([cbDemo8Id_('DOCUMENT',key,'CAD-1')]),'Link URL':'','Post Type':'Draft','Status':'Draft Demo — Not Published','Approved By':'','Created By':context.user.userId});cbDemo8Upsert_(context,'core','socialMetrics','Social Metric ID',cbDemo8Id_('SOCIAL-METRIC',key),{'Social Post ID':postId,'Platform':'Instagram','Metric Date':'2026-08-01','Impressions':0,'Reach':0,'Engagements':0,'Clicks':0,'Leads':0,'Spend':0,'Revenue':0,'Source':'Demo — not published'});summary.social+=1;
 });
 var periodId=cbDemo8Id_('ACCOUNTING','2026-08');cbDemo8Upsert_(context,'core','accountingPeriods','Accounting Period ID',periodId,{'Period Name':'August 2026 Demo','Period Start':'2026-08-01','Period End':'2026-08-31','Status':'Open Demo','Review Status':'Needs Review','Missing Documents':1,'Prepared By':context.user.userId});
 var payrollId=cbDemo8Id_('PAYROLL','2026-08');cbDemo8Upsert_(context,'core','payrollPeriods','Payroll Period ID',payrollId,{'Period Start':'2026-08-01','Period End':'2026-08-15','Pay Date':'2026-08-21','Provider':'Demo only','Status':'Prepared Demo — Not Submitted','Approval Status':'Owner Review Required','Export Allowed':'No','Gross Pay':1120,'Deductions':224,'Prepared Net Amount':896,'Employer Tax Estimate':100,'Employer Cost Estimate':1220,'Created By':context.user.userId});cbDemo8Upsert_(context,'core','payrollLines','Payroll Line ID',cbDemo8Id_('PAYLINE','FIELD'),{'Payroll Period ID':payrollId,'Employee ID':employeeId,'Regular Hours':40,'Overtime Hours':0,'Regular Pay':1120,'Overtime Pay':0,'Salary Pay':0,'Reimbursements':0,'Other Pay':0,'Gross Pay':1120,'Deductions':224,'Prepared Net Amount':896,'Employer Tax Estimate':100,'Employer Cost Estimate':1220,'Approval Status':'Owner Review Required','Notes':'Demo only; not payroll-authoritative.'});cbDemo8Upsert_(context,'core','payrollDeductions','Payroll Deduction ID',cbDemo8Id_('DEDUCTION','FIELD'),{'Employee ID':employeeId,'Payroll Period ID':payrollId,'Description':'Demo withholding estimate','Amount':224,'Status':'Demo — Not Submitted'});
 cbDemo8Upsert_(context,'core','taxPeriods','Tax Period ID',cbDemo8Id_('TAX','2026-Q3'),{'Tax Type':'Sales Tax','Jurisdiction':'Minnesota Demo','Period Start':'2026-07-01','Period End':'2026-09-30','Due Date':'2026-10-20','Status':'Prepared Demo — Not Filed','Approval Status':'Owner Review Required','Finalization Allowed':'No','Taxable Sales':0,'Exempt Sales':0,'Tax Collected':0,'Tax Adjustments':0,'Estimated Liability':0,'Payment Recorded':0,'Missing Documents':1,'Created By':context.user.userId});
 cbDemo8Upsert_(context,'core','missingDocuments','Missing Document ID',cbDemo8Id_('MISSING','RECEIPT'),{'Area':'Tax Prep','Period ID':cbDemo8Id_('TAX','2026-Q3'),'Document Type':'Receipt','Description':'Example missing receipt for tax-prep workflow','Requested From':'Demo Field Specialist','Due Date':'2026-09-10','Status':'Open Demo','Notes':'No filing permitted.'});
 cbDemo8Upsert_(context,'core','reports','Report ID',cbDemo8Id_('REPORT','DEMO8'),{'Report Type':'Full Demo Office Coverage','Period Start':'2026-08-01','Period End':'2026-08-31','Status':'Prepared Demo','Approval Status':'Owner Review Required','File ID':'','Prepared By':context.user.userId,'Prepared Time':cbNow_(),'Notes':'Eight projects, 21 cabin sub-quotes, CAD, AI, catalog, operations and financial examples.'});
 cbDemo8Upsert_(context,'core','backups','Backup ID',cbDemo8Id_('BACKUP','DEMO8'),{'Backup Type':'Demo manifest','Scope':'All eight controlled examples','Status':'Prepared Demo','Requested By':context.user.userId,'Requested Time':cbNow_(),'Completed Time':'','File ID':'','Notes':'No production data included.'});return summary;}
function cbCompletionSeedFullDemoOffice_(request){var input=request||{},context=cbCompletionContext_(input.businessId,'manageSettings');cbAssert_(context.user.owner===true,'Only the owner can load full demo examples.');cbCompletionEnsureParitySchema_(context);var phase=cbText_(input.phase||'all').toLowerCase(),result={status:'PASS',phase:phase,businessId:context.row['Business ID'],projects:8,cabinSubQuotes:21,approved:false,sent:false,published:false,fundsMoved:false,externalActionsEnabled:false,productionDataMigrated:false};if(phase==='all'||phase==='core')result.core=cbDemo8SeedCore_(context);if(phase==='all'||phase==='catalog')result.catalog=cbDemo8SeedCatalog_(context);if(phase==='all'||phase==='operations')result.operations=cbDemo8SeedOperations_(context);if(phase==='all'||phase==='finance')result.finance=cbDemo8SeedFinance_(context);cbAudit_(context.row['Business ID'],'SEED FULL DEMO OFFICE','Business',context.row['Business ID'],'PASS','Phase '+phase+' completed. Controlled demo records only.');return result;}
