/** Additive completion schema for work, communications, money, AI, social and field use. */
var CB_COMPLETION_HEADERS=Object.freeze({
  core:Object.freeze({
    contacts:Object.freeze(['Contact ID','Business ID','Customer ID','Contact Name','Email','Phone','Role','Preferred Channel','Status','Created Time','Updated Time','Record Version']),
    requests:Object.freeze(['Request ID','Business ID','Customer ID','Property ID','Source','Subject','Details','Priority','Assigned User ID','Status','Created By','Created Time','Updated Time','Record Version']),
    workOrders:Object.freeze(['Work Order ID','Business ID','Job ID','Customer ID','Property ID','Work Order Number','Title','Scope','Assigned User ID','Assigned Crew ID','Status','Scheduled Start','Scheduled End','Priority','Closeout Requirements JSON','Created Time','Updated Time','Record Version']),
    scheduleEvents:Object.freeze(['Schedule Event ID','Business ID','Event Type','Title','Related Record Type','Related Record ID','Assigned User ID','Assigned Crew ID','Start Time','End Time','Location','Status','Notes','Created Time','Updated Time','Record Version']),
    timeEntries:Object.freeze(['Time Entry ID','Business ID','User ID','Job ID','Task ID','Start Time','End Time','Break Minutes','Hours','Status','Notes','Offline Operation ID','Created Time','Updated Time','Record Version']),
    jobNotes:Object.freeze(['Job Note ID','Business ID','Job ID','Note Type','Body','Visibility','Created By','Created Time','Record Version']),
    measurements:Object.freeze(['Measurement ID','Business ID','Job ID','Quote ID','Related Record Type','Related Record ID','Measurement Name','Measurement Type','Value','Unit','Method','Confidence','Reference Size','Reference Unit','Photo Document ID','Notes','Status','Created By','Created Time','Updated Time','Record Version']),
    measurementPoints:Object.freeze(['Measurement Point ID','Business ID','Measurement ID','Point Label','X','Y','Z','Latitude','Longitude','Accuracy','Sequence','Notes','Record Version']),
    checklists:Object.freeze(['Checklist ID','Business ID','Related Record Type','Related Record ID','Title','Checklist Type','Status','Created By','Created Time','Updated Time','Record Version']),
    checklistItems:Object.freeze(['Checklist Item ID','Business ID','Checklist ID','Item Text','Required','Completed','Completed By','Completed Time','Sort Order','Record Version']),
    conversationMembers:Object.freeze(['Conversation Member ID','Business ID','Conversation ID','User ID','Role','Notification Level','Joined Time','Left Time','Status','Record Version']),
    messageEvents:Object.freeze(['Message Event ID','Business ID','Message ID','Event Type','User ID','Details JSON','Timestamp','Record Version']),
    emailMessages:Object.freeze(['Email Message ID','Business ID','Email Thread ID','Provider Message ID','Direction','From Address','To Addresses JSON','Cc Addresses JSON','Subject','Body Preview','Document ID','Message Time','Status','Created Time','Record Version']),
    smsMessages:Object.freeze(['SMS Message ID','Business ID','SMS Thread ID','Provider Message ID','Direction','From Number','To Number','Body','Media Document IDs JSON','Delivery Status','Consent Status','Message Time','Status','Created Time','Record Version']),
    notifications:Object.freeze(['Notification ID','Business ID','User ID','Notification Type','Title','Body','Related Record Type','Related Record ID','Priority','Read Time','Status','Created Time','Record Version']),
    userPreferences:Object.freeze(['User Preference ID','Business ID','User ID','Preference Key','Preference Value JSON','Updated Time','Record Version']),
    quickActions:Object.freeze(['Quick Action ID','Business ID','Action Key','Label','Page Key','Role IDs JSON','Configuration JSON','Sort Order','Status','Created Time','Updated Time','Record Version']),
    workflows:Object.freeze(['Workflow ID','Business ID','Workflow Key','Workflow Name','Record Type','Trigger Type','Status','Owner Approval Required','Created Time','Updated Time','Record Version']),
    workflowSteps:Object.freeze(['Workflow Step ID','Business ID','Workflow ID','Step Number','Action Key','Label','Configuration JSON','Owner Approval Required','Status','Record Version']),
    invoices:Object.freeze(['Invoice ID','Business ID','Customer ID','Job ID','Quote ID','Invoice Number','Invoice Type','Status','Issue Date','Due Date','Subtotal','Tax','Total','Balance','Notes','Created By','Created Time','Updated Time','Record Version']),
    invoiceLines:Object.freeze(['Invoice Line ID','Business ID','Invoice ID','Description','Quantity','Unit','Unit Price','Line Total','Status','Record Version']),
    payments:Object.freeze(['Payment ID','Business ID','Invoice ID','Customer ID','Payment Date','Amount','Method','Reference','Status','Recorded By','Created Time','Record Version']),
    expenses:Object.freeze(['Expense ID','Business ID','Job ID','Vendor ID','Category','Description','Expense Date','Amount','Tax','Payment Method','Receipt Document ID','Status','Created By','Created Time','Updated Time','Record Version']),
    documentLinks:Object.freeze(['Document Link ID','Business ID','Document ID','Related Record Type','Related Record ID','Relationship','Visibility','Created Time','Record Version']),
    providers:Object.freeze(['Provider ID','Business ID','Provider Type','Provider Name','Connection Status','Capabilities JSON','Settings JSON','Last Check Time','Last Error','Status','Updated Time','Record Version']),
    integrationHealth:Object.freeze(['Integration Health ID','Business ID','Provider ID','Check Type','Result','Details','Checked Time','Record Version']),
    socialAccounts:Object.freeze(['Social Account ID','Business ID','Platform','Account Name','Provider','Provider Account ID','Connection Status','Status','Created Time','Updated Time','Record Version']),
    socialPosts:Object.freeze(['Social Post ID','Business ID','Campaign ID','Platform','Account ID','Title','Body','Asset Document IDs JSON','Link URL','Post Type','Status','Scheduled Time','Approved By','Approved Time','Published Time','Provider Post ID','Manual Proof Document ID','Created By','Created Time','Updated Time','Record Version']),
    socialApprovals:Object.freeze(['Social Approval ID','Business ID','Social Post ID','Decision','Requested By','Decided By','Requested Time','Decided Time','Notes','Record Version']),
    socialMetrics:Object.freeze(['Social Metric ID','Business ID','Social Post ID','Platform','Metric Date','Impressions','Reach','Engagements','Clicks','Leads','Spend','Revenue','Source','Created Time','Record Version']),
    campaigns:Object.freeze(['Campaign ID','Business ID','Campaign Name','Campaign Type','Start Date','End Date','Budget','Status','Goal','Notes','Created Time','Updated Time','Record Version']),
    aiKnowledge:Object.freeze(['Knowledge ID','Business ID','Topic','Title','Content','Module Key','Role IDs JSON','Source','Version','Status','Updated Time','Record Version']),
    aiConversations:Object.freeze(['AI Conversation ID','Business ID','User ID','Title','Context JSON','Status','Created Time','Updated Time','Record Version']),
    aiMessages:Object.freeze(['AI Message ID','Business ID','AI Conversation ID','Role','Body','Sources JSON','Action JSON','Created Time','Record Version']),
    featureRequests:Object.freeze(['Feature Request ID','Business ID','Requested By','Page Key','User Role','Title','Problem','Current Workaround','Frequency','Proposed Action','Status','Created Time','Updated Time','Record Version']),
    voiceQueue:Object.freeze(['Voice Queue ID','Business ID','User ID','Mode','Transcript','Intent','Related Record Type','Related Record ID','Risk Level','Review Required','Status','Created Time','Updated Time','Record Version']),
    actionQueue:Object.freeze(['Action Queue ID','Business ID','User ID','Action Type','Related Record Type','Related Record ID','Payload JSON','Risk Level','Review State','Approved By','Executed Time','Status','Created Time','Updated Time','Record Version']),
    attachments:Object.freeze(['Attachment ID','Business ID','Document ID','Related Record Type','Related Record ID','File ID','File Name','Mime Type','File Size','Capture Time','Local Operation ID','Upload Status','Visibility','Created By','Created Time','Record Version']),
    customerPortalThreads:Object.freeze(['Portal Thread ID','Business ID','Customer ID','Related Record Type','Related Record ID','Subject','Status','Created Time','Updated Time','Record Version']),
    customerPortalMessages:Object.freeze(['Portal Message ID','Business ID','Portal Thread ID','Sender Type','Sender ID','Body','Attachment IDs JSON','Message Time','Status','Record Version'])
  }),
  inventory:Object.freeze({
    materialRequests:Object.freeze(['Material Request ID','Business ID','Job ID','Requested By','Assigned To','Needed Date','Priority','Items JSON','Status','Notes','Created Time','Updated Time','Record Version']),
    receipts:Object.freeze(['Receipt ID','Business ID','Vendor ID','Job ID','Document ID','Receipt Date','Amount','Tax','Status','Created By','Created Time','Record Version'])
  })
});
