function cbCompletionAssignAsset_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageAssets'),asset=cbPlatformFindRow_(context.assets,'assets','Asset ID',input.assetId),job=cbPlatformFindRow_(context.core,'jobs','Job ID',input.jobId),now=cbNow_();cbAssert_(asset,'Equipment was not found.');cbAssert_(job,'Job was not found.');cbAssert_(!asset.Availability||cbText_(asset.Availability).toUpperCase()==='AVAILABLE','Equipment is not available.');var id=cbUuid_('ASSIGNMENT');cbAppend_(context.assets,'assignments',{'Asset Assignment ID':id,'Business ID':context.row['Business ID'],'Asset ID':asset['Asset ID'],'User ID':cbText_(input.userId),'Crew ID':cbText_(input.crewId),'Truck ID':cbText_(input.truckId),'Job ID':job['Job ID'],'Location ID':cbText_(input.locationId),'Assignment Type':'Job','Assigned Time':now,'Returned Time':'','Status':'Active','Condition Out':cbText_(input.conditionOut),'Condition In':'','Created By':context.user.userId,'Updated By':context.user.userId,'Record Version':1});cbPlatformUpdateRow_(context.assets,'assets',asset.__row,{'Assigned Job ID':job['Job ID'],'Assigned User ID':cbText_(input.userId),'Assigned Crew ID':cbText_(input.crewId),'Availability':'Assigned','Updated Time':now,'Record Version':Math.max(1,Number(asset['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'ASSIGN EQUIPMENT','Asset Assignment',id,'PASS','Equipment assigned to job.');return{status:'PASS',assignmentId:id};
}
function cbCompletionReturnAsset_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageAssets'),asset=cbPlatformFindRow_(context.assets,'assets','Asset ID',input.assetId),now=cbNow_();cbAssert_(asset,'Equipment was not found.');var active=cbRows_(context.assets,'assignments').filter(function(row){return row['Asset ID']===asset['Asset ID']&&cbText_(row.Status).toUpperCase()==='ACTIVE'&&!row['Returned Time'];});cbAssert_(active.length,'No active assignment was found.');active.forEach(function(row){cbPlatformUpdateRow_(context.assets,'assignments',row.__row,{'Returned Time':now,'Status':'Returned','Condition In':cbText_(input.conditionIn),'Updated By':context.user.userId,'Record Version':Math.max(1,Number(row['Record Version']||1))+1});});cbPlatformUpdateRow_(context.assets,'assets',asset.__row,{'Assigned Job ID':'','Assigned User ID':'','Assigned Crew ID':'','Availability':cbText_(input.holdReason)?'Hold':'Available','Status':cbText_(input.holdReason)?'Needs Review':'Active','Updated Time':now,'Record Version':Math.max(1,Number(asset['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'RETURN EQUIPMENT','Asset',asset['Asset ID'],'PASS','Equipment returned.');return{status:'PASS',assetId:asset['Asset ID']};
}
function cbCompletionScheduleMaintenance_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageMaintenance'),asset=cbPlatformFindRow_(context.assets,'assets','Asset ID',input.assetId),now=cbNow_();cbAssert_(asset,'Equipment was not found.');var id=cbUuid_('MAINTENANCE');cbAppend_(context.assets,'maintenance',{'Maintenance ID':id,'Business ID':context.row['Business ID'],'Asset ID':asset['Asset ID'],'Maintenance Type':cbText_(input.maintenanceType)||'Service','Status':cbText_(input.status)||'Scheduled','Priority':cbText_(input.priority)||'Normal','Due Date':cbText_(input.dueDate),'Due Meter':Number(input.dueMeter||0),'Completed Date':'','Vendor ID':cbText_(input.vendorId),'Labor Hours':'','Parts Cost':'','Labor Cost':'','Downtime Hours':'','Notes':cbText_(input.notes),'Created Time':now,'Updated Time':now,'Record Version':1});cbPlatformUpdateRow_(context.assets,'assets',asset.__row,{'Next Service':cbText_(input.dueDate),'Updated Time':now,'Record Version':Math.max(1,Number(asset['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'SCHEDULE MAINTENANCE','Maintenance',id,'PASS','Maintenance scheduled.');return{status:'PASS',maintenanceId:id};
}
function cbCompletionRecordInspection_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageMaintenance'),asset=cbPlatformFindRow_(context.assets,'assets','Asset ID',input.assetId),now=cbNow_(),result=cbText_(input.result).toUpperCase()||'PASS';cbAssert_(asset,'Equipment was not found.');var id=cbUuid_('INSPECTION');cbAppend_(context.assets,'inspections',{'Inspection ID':id,'Business ID':context.row['Business ID'],'Asset ID':asset['Asset ID'],'Inspection Type':cbText_(input.inspectionType)||'Routine','Result':result,'Meter Reading':Number(input.meterReading||0),'Mileage':Number(input.mileage||0),'Notes':cbText_(input.notes),'Document IDs JSON':JSON.stringify(input.documentIds||[]),'Inspected By':context.user.userId,'Inspection Time':now,'Record Version':1});if(result==='FAIL')cbPlatformUpdateRow_(context.assets,'assets',asset.__row,{'Availability':'Inspection Hold','Status':'Needs Service','Updated Time':now,'Record Version':Math.max(1,Number(asset['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'RECORD INSPECTION','Inspection',id,result==='FAIL'?'HOLD':'PASS','Inspection recorded.');return{status:'PASS',inspectionId:id};
}
function cbCompletionRecordAssetUsage_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'useAssets'),asset=cbPlatformFindRow_(context.assets,'assets','Asset ID',input.assetId),now=cbNow_();cbAssert_(asset,'Equipment was not found.');var id=cbUuid_('USAGE');cbAppend_(context.assets,'usageLogs',{'Usage Log ID':id,'Business ID':context.row['Business ID'],'Asset ID':asset['Asset ID'],'Job ID':cbText_(input.jobId),'User ID':cbText_(input.userId)||context.user.userId,'Start Time':cbText_(input.startTime),'End Time':cbText_(input.endTime)||now,'Start Meter':Number(input.startMeter||0),'End Meter':Number(input.endMeter||0),'Start Mileage':Number(input.startMileage||0),'End Mileage':Number(input.endMileage||0),'Usage Type':cbText_(input.usageType)||'Job','Notes':cbText_(input.notes),'Offline Operation ID':cbText_(input.offlineOperationId),'Record Version':1});var updates={'Updated Time':now,'Record Version':Math.max(1,Number(asset['Record Version']||1))+1};if(Number(input.endMeter||0)>0)updates['Meter Hours']=Number(input.endMeter);if(Number(input.endMileage||0)>0)updates.Mileage=Number(input.endMileage);cbPlatformUpdateRow_(context.assets,'assets',asset.__row,updates);return{status:'PASS',usageId:id};
}
