function cbCompletionMarkSocialPosted_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),post=cbPlatformFindRow_(context.core,'socialPosts','Social Post ID',input.socialPostId),now=cbNow_();cbAssert_(post,'Social post was not found.');cbAssert_(post['Approved By'],'Owner approval is required before publication can be recorded.');cbAssert_(cbText_(input.providerPostId)||cbText_(input.manualProofDocumentId)||cbText_(input.publicUrl),'A provider post ID, public URL, or manual proof document is required.');cbPlatformUpdateRow_(context.core,'socialPosts',post.__row,{'Status':'Published — Manually Verified','Published Time':cbText_(input.publishedTime)||now,'Provider Post ID':cbText_(input.providerPostId)||cbText_(input.publicUrl),'Manual Proof Document ID':cbText_(input.manualProofDocumentId),'Updated Time':now,'Record Version':Math.max(1,Number(post['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'RECORD SOCIAL PUBLICATION','Social Post',post['Social Post ID'],'PASS','Manual publication proof recorded. The platform did not publish automatically.');return{status:'PASS'};
}
function cbCompletionRecordSocialMetric_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSocial'),id=cbUuid_('SOCIAL-METRIC');cbAppend_(context.core,'socialMetrics',{'Social Metric ID':id,'Business ID':context.row['Business ID'],'Social Post ID':cbText_(input.socialPostId),'Platform':cbText_(input.platform),'Metric Date':cbText_(input.metricDate)||cbNow_().slice(0,10),'Impressions':Number(input.impressions||0),'Reach':Number(input.reach||0),'Engagements':Number(input.engagements||0),'Clicks':Number(input.clicks||0),'Leads':Number(input.leads||0),'Spend':Number(input.spend||0),'Revenue':Number(input.revenue||0),'Source':cbText_(input.source)||'Manual','Created Time':cbNow_(),'Record Version':1});return{status:'PASS',socialMetricId:id};
}
function cbCompletionSocialPublishHold_(request){var context=cbCompletionContext_(request.businessId,'manageSocial');cbAudit_(context.row['Business ID'],'SOCIAL PUBLISH HOLD','Social Post',cbText_(request.socialPostId),'HOLD','Automatic social publication is disabled until the provider and owner release are explicitly enabled.');return{status:'HOLD',message:'Automatic social publishing is disabled. Use approved manual posting and record proof, or connect and release a provider later.'};}
function cbCompletionAiLocalAnswer_(context,question,pageKey){
  var q=cbText_(question).toLowerCase(),knowledge=cbRows_(context.core,'aiKnowledge').filter(function(row){return cbText_(row.Status).toUpperCase()==='ACTIVE';}),tokens=q.split(/\W+/).filter(function(token){return token.length>2;}),ranked=knowledge.map(function(row){var hay=(row.Topic+' '+row.Title+' '+row.Content+' '+row['Module Key']).toLowerCase(),score=tokens.reduce(function(sum,token){return sum+(hay.indexOf(token)>=0?1:0);},0)+(pageKey&&row['Module Key']===pageKey?2:0);return{row:row,score:score};}).sort(function(a,b){return b.score-a.score;});
  if(ranked.length&&ranked[0].score>0)return{answer:ranked.slice(0,3).map(function(item){return item.row.Title+': '+item.row.Content;}).join('\n\n'),sources:ranked.slice(0,3).map(function(item){return item.row['Knowledge ID'];}),provider:'Local H38 knowledge'};
  return{answer:'I can help with customers, requests, jobs, quotes, scheduling, internal messages, email and text drafts, field capture, inventory, fleet, maintenance, invoices, expenses, documents, Social Control, offline synchronization, settings and workflow recommendations. Ask about the page you are on or the task you are trying to complete.',sources:['KNOWLEDGE-getting-started'],provider:'Local H38 knowledge'};
}
function cbCompletionAiProviderAnswer_(context,question,pageKey,local){
  var props=cbProperties_(),connected=cbText_(props.getProperty('COMMERCIAL_BETA_AI_CONNECTED')).toUpperCase()==='TRUE',key=cbText_(props.getProperty('COMMERCIAL_BETA_AI_API_KEY')),model=cbText_(props.getProperty('COMMERCIAL_BETA_AI_MODEL'));if(!connected||!key||!model)return local;
  try{
    var instructions='You are H38 AI inside a business operating platform. Teach the user how to use the installed product and answer only from the supplied platform context. Respect the user role. Never claim an external action was performed. Never approve, send, publish, purchase, invoice, pay, delete, change permissions, or deploy. Keep answers practical and concise.';
    var contextText='Business: '+context.row['Business Name']+'\nUser role: '+context.user.roleName+'\nCurrent page: '+cbText_(pageKey)+'\nLocal product guidance:\n'+local.answer;
    var response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+key},payload:JSON.stringify({model:model,instructions:instructions,input:contextText+'\n\nUser question: '+question,max_output_tokens:600}),muteHttpExceptions:true});if(response.getResponseCode()<200||response.getResponseCode()>=300)throw new Error('AI provider returned '+response.getResponseCode());var json=JSON.parse(response.getContentText()),text=cbText_(json.output_text);if(!text&&Array.isArray(json.output))json.output.some(function(item){return(item.content||[]).some(function(part){if(part.text){text=part.text;return true;}return false;});});if(text)return{answer:text,sources:local.sources,provider:'Configured AI provider'};
  }catch(error){cbError_(context.row['Business ID'],'AI ANSWER',error);}return local;
}
function cbCompletionAiAsk_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,''),question=cbText_(input.question),now=cbNow_();cbAssert_(question,'Ask a question first.');var local=cbCompletionAiLocalAnswer_(context,question,cbText_(input.pageKey)),result=cbCompletionAiProviderAnswer_(context,question,cbText_(input.pageKey),local),conversationId=cbText_(input.aiConversationId)||cbUuid_('AI-CONVERSATION');if(!cbPlatformFindRow_(context.core,'aiConversations','AI Conversation ID',conversationId))cbAppend_(context.core,'aiConversations',{'AI Conversation ID':conversationId,'Business ID':context.row['Business ID'],'User ID':context.user.userId,'Title':question.slice(0,80),'Context JSON':JSON.stringify({pageKey:input.pageKey,recordType:input.recordType,recordId:input.recordId}),'Status':'Active','Created Time':now,'Updated Time':now,'Record Version':1});cbAppend_(context.core,'aiMessages',{'AI Message ID':cbUuid_('AI-MESSAGE'),'Business ID':context.row['Business ID'],'AI Conversation ID':conversationId,'Role':'User','Body':question,'Sources JSON':'[]','Action JSON':'{}','Created Time':now,'Record Version':1});cbAppend_(context.core,'aiMessages',{'AI Message ID':cbUuid_('AI-MESSAGE'),'Business ID':context.row['Business ID'],'AI Conversation ID':conversationId,'Role':'Assistant','Body':result.answer,'Sources JSON':JSON.stringify(result.sources||[]),'Action JSON':'{}','Created Time':now,'Record Version':1});return{status:'PASS',aiConversationId:conversationId,answer:result.answer,sources:result.sources,provider:result.provider};
}
