function cbCompletionSaveSchedule_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSchedule'),title=cbText_(input.title),start=cbText_(input.startTime),now=cbNow_();cbAssert_(title,'Schedule title is required.');cbAssert_(start,'Start time is required.');var id=cbText_(input.scheduleEventId)||cbUuid_('SCHEDULE'),record={'Schedule Event ID':id,'Business ID':context.row['Business ID'],'Event Type':cbText_(input.eventType)||'Job','Title':title,'Related Record Type':cbText_(input.relatedRecordType)||'Job','Related Record ID':cbText_(input.relatedRecordId),'Assigned User ID':cbText_(input.assignedUserId),'Assigned Crew ID':cbText_(input.assignedCrewId),'Start Time':start,'End Time':cbText_(input.endTime),'Location':cbText_(input.location),'Status':cbText_(input.status)||'Scheduled','Notes':cbText_(input.notes)};var result=cbCompletionUpsert_(context,'core','scheduleEvents','Schedule Event ID','SCHEDULE',record,input);if(result.status==='PASS')cbAudit_(context.row['Business ID'],'SAVE SCHEDULE','Schedule Event',result.recordId,'PASS','Schedule event saved.');return result;
}
function cbCompletionRecordTime_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageField'),start=cbText_(input.startTime),end=cbText_(input.endTime),hours=Number(input.hours||0);if(start&&end&&!hours)hours=Math.max(0,(new Date(end).getTime()-new Date(start).getTime())/3600000-Number(input.breakMinutes||0)/60);var id=cbText_(input.timeEntryId)||cbUuid_('TIME'),record={'Time Entry ID':id,'Business ID':context.row['Business ID'],'User ID':cbText_(input.userId)||context.user.userId,'Job ID':cbText_(input.jobId),'Task ID':cbText_(input.taskId),'Start Time':start,'End Time':end,'Break Minutes':Number(input.breakMinutes||0),'Hours':Math.round(hours*100)/100,'Status':cbText_(input.status)||'Recorded','Notes':cbText_(input.notes),'Offline Operation ID':cbText_(input.offlineOperationId)};var result=cbCompletionUpsert_(context,'core','timeEntries','Time Entry ID','TIME',record,input);if(result.status==='PASS')cbAudit_(context.row['Business ID'],'RECORD TIME','Time Entry',result.recordId,'PASS','Time entry recorded.');return result;
}
function cbCompletionSaveQuote_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageQuotes'),now=cbNow_(),quoteId=cbText_(input.quoteId)||cbUuid_('QUOTE'),existing=cbPlatformFindRow_(context.core,'quotes','Quote ID',quoteId),revision=existing?Math.max(1,Number(existing.Revision||1))+1:1,lines=Array.isArray(input.lines)?input.lines:[],subtotal=lines.reduce(function(sum,line){return sum+Number(line.quantity||0)*Number(line.unitPrice||0);},0),tax=Number(input.tax||0),total=subtotal+tax;
  var record={'Quote ID':quoteId,'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Property ID':cbText_(input.propertyId),'Job ID':cbText_(input.jobId),'Quote Number':existing?existing['Quote Number']:(cbText_(input.quoteNumber)||('Q-'+Utilities.formatDate(new Date(),context.row['Time Zone']||CB_CONFIG.defaultTimeZone,'yyyyMMdd-HHmmss'))),'Project Title':cbText_(input.projectTitle)||'Untitled quote','Scope':cbText_(input.scope),'Measurement Notes':cbText_(input.measurementNotes),'Status':cbText_(input.status)||'Draft','Revision':revision,'Subtotal':subtotal,'Tax':tax,'Total':total,'Price Snapshot Time':cbText_(input.priceSnapshotTime),'Offline Pack ID':cbText_(input.offlinePackId),'Created By':existing?existing['Created By']:context.user.userId,'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};
  if(existing)cbPlatformUpdateRow_(context.core,'quotes',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'quotes',record);}lines.forEach(function(line){var quantity=Number(line.quantity||0),unitPrice=Number(line.unitPrice||0);cbAppend_(context.core,'quoteLines',{'Quote Line ID':cbText_(line.quoteLineId)||cbUuid_('QUOTE-LINE'),'Business ID':context.row['Business ID'],'Quote ID':quoteId,'Quote Revision':revision,'Line Type':cbText_(line.lineType)||'Material','Description':cbText_(line.description),'Quantity':quantity,'Unit':cbText_(line.unit)||'each','Unit Price':unitPrice,'Line Total':quantity*unitPrice,'Price Source':cbText_(line.priceSource)||'Manual or cached','Price Status':cbText_(line.priceStatus)||'Owner review required','Status':'Active','Created Time':now,'Record Version':1});});cbAudit_(context.row['Business ID'],'SAVE QUOTE DRAFT','Quote',quoteId,'PASS','Quote draft saved. Nothing approved or sent.');return{status:'PASS',quoteId:quoteId,revision:revision,total:total};
}
function cbCompletionPostInventory_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageInventory'),itemId=cbText_(input.itemId),direction=cbText_(input.direction).toUpperCase(),quantity=Math.abs(Number(input.quantity||0)),now=cbNow_();cbAssert_(itemId,'Inventory item is required.');cbAssert_(direction==='IN'||direction==='OUT','Direction must be IN or OUT.');cbAssert_(quantity>0,'Quantity must be greater than zero.');var item=cbPlatformFindRow_(context.inventory,'items','Item ID',itemId);cbAssert_(item,'Inventory item was not found.');var transactions=cbRows_(context.inventory,'transactions'),onHand=transactions.filter(function(row){return row['Item ID']===itemId;}).reduce(function(sum,row){return sum+(cbText_(row.Direction).toUpperCase()==='OUT'?-Math.abs(Number(row.Quantity||0)):Math.abs(Number(row.Quantity||0)));},0);if(direction==='OUT')cbAssert_(onHand>=quantity,'Not enough stock is available.');var id=cbUuid_('TXN'),unitCost=Number(input.unitCost||item['Average Cost']||item['Purchase Cost']||0);cbAppend_(context.inventory,'transactions',{'Transaction ID':id,'Business ID':context.row['Business ID'],'Location ID':cbText_(input.locationId)||'LOC-MAIN-SHOP','Item ID':itemId,'Quantity':quantity,'Direction':direction,'Unit Cost':unitCost,'Total Value':quantity*unitCost,'Job ID':cbText_(input.jobId),'User ID':context.user.userId,'Source Type':'Commercial Office','Source Record ID':cbText_(input.sourceRecordId),'Reason':cbText_(input.reason),'Timestamp':now,'Offline Transaction ID':cbText_(input.offlineOperationId),'Idempotency Key':cbText_(input.operationId)||cbUuid_('IDEMPOTENCY'),'Sync Status':'SERVER','Record Version':1,'Audit Metadata JSON':JSON.stringify({email:context.user.email})});cbAudit_(context.row['Business ID'],'POST INVENTORY '+direction,'Inventory Transaction',id,'PASS','Append-only inventory transaction recorded.');return{status:'PASS',transactionId:id,onHand:direction==='IN'?onHand+quantity:onHand-quantity};
}
