function cbCompletionRecommendationExists_(rows,type,title){return rows.some(function(row){return row['Recommendation Type']===type&&row.Title===title&&['Open','Applied','Postponed'].indexOf(row.Status)>=0;});}
function cbCompletionAddRecommendation_(context,type,title,evidence,change,risk){
  var id=cbUuid_('RECOMMENDATION'),now=cbNow_();cbAppend_(context.core,'aiRecommendations',{'Recommendation ID':id,'Business ID':context.row['Business ID'],'Recommendation Type':type,'Title':title,'Evidence JSON':JSON.stringify(evidence||{}),'Proposed Change JSON':JSON.stringify(change||{}),'Risk JSON':JSON.stringify(risk||{}),'Status':'Open','Approved By':'','Applied Time':'','Undo Data JSON':'{}','Created Time':now,'Updated Time':now,'Record Version':1});return id;
}
function cbCompletionRecommendations_(context){
  var rows=cbRows_(context.core,'aiRecommendations'),users=cbRows_(context.core,'users').filter(function(row){return cbText_(row.Status).toUpperCase()==='ACTIVE';}),quotes=cbRows_(context.core,'quotes'),social=cbRows_(context.core,'socialPosts'),assets=cbRows_(context.assets,'assets'),providers=cbRows_(context.core,'providers'),quick=cbRows_(context.core,'quickActions');
  if(users.length<=1&&!cbCompletionRecommendationExists_(rows,'Setup','Add your team'))cbCompletionAddRecommendation_(context,'Setup','Add your team',{activeUsers:users.length},{type:'navigate',pageKey:'settings',action:'add-user'},{level:'Low',note:'Only invited business users gain access.'});
  var draftQuotes=quotes.filter(function(row){return cbText_(row.Status).toUpperCase()==='DRAFT';});if(draftQuotes.length>=3&&!cbCompletionRecommendationExists_(rows,'Workflow','Add a quote review queue'))cbCompletionAddRecommendation_(context,'Workflow','Add a quote review queue',{draftQuotes:draftQuotes.length},{type:'quickAction',actionKey:'review-quotes',label:'Review draft quotes',pageKey:'quotes'},{level:'Low',note:'No quote is approved or sent automatically.'});
  var unscheduled=social.filter(function(row){return cbText_(row.Status).toUpperCase()==='DRAFT'&&!row['Scheduled Time'];});if(unscheduled.length>=3&&!cbCompletionRecommendationExists_(rows,'Social','Plan unscheduled social drafts'))cbCompletionAddRecommendation_(context,'Social','Plan unscheduled social drafts',{unscheduledDrafts:unscheduled.length},{type:'quickAction',actionKey:'plan-social',label:'Plan social drafts',pageKey:'social'},{level:'Low',note:'Scheduling remains internal until provider release.'});
  var due=assets.filter(function(row){return row['Next Service']&&new Date(row['Next Service']).getTime()<=Date.now()+14*86400000;});if(due.length&&!cbCompletionRecommendationExists_(rows,'Maintenance','Review equipment due for service'))cbCompletionAddRecommendation_(context,'Maintenance','Review equipment due for service',{dueAssets:due.map(function(row){return row['Asset ID'];})},{type:'quickAction',actionKey:'service-due',label:'Equipment due for service',pageKey:'fleet'},{level:'Medium',note:'Verify service requirements before taking equipment out of service.'});
  var disconnected=providers.filter(function(row){return row['Connection Status']!=='Connected';});if(disconnected.length&&!cbCompletionRecommendationExists_(rows,'Integration','Review disconnected providers'))cbCompletionAddRecommendation_(context,'Integration','Review disconnected providers',{providers:disconnected.map(function(row){return row['Provider Type'];})},{type:'navigate',pageKey:'settings',action:'providers'},{level:'Low',note:'Connecting providers may require separate credentials and authorization.'});
  if(!quick.some(function(row){return row['Action Key']==='start-quote-from-customer';})&&!cbCompletionRecommendationExists_(rows,'Missing Button','Add Start Quote to customer work'))cbCompletionAddRecommendation_(context,'Missing Button','Add Start Quote to customer work',{reason:'Customer-to-quote is a common workflow.'},{type:'quickAction',actionKey:'start-quote-from-customer',label:'Start quote',pageKey:'customers'},{level:'Low',note:'Creates a draft only.'});
  return cbRows_(context.core,'aiRecommendations').slice().reverse().slice(0,300).map(cbCompletionCleanRow_);
}
function cbCompletionRecommendationDecision_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageSettings'),row=cbPlatformFindRow_(context.core,'aiRecommendations','Recommendation ID',input.recommendationId),decision=cbText_(input.decision).toUpperCase(),now=cbNow_();cbAssert_(row,'Recommendation was not found.');if(decision==='DISMISS'||decision==='POSTPONE'){cbPlatformUpdateRow_(context.core,'aiRecommendations',row.__row,{'Status':decision==='DISMISS'?'Dismissed':'Postponed','Updated Time':now,'Record Version':Math.max(1,Number(row['Record Version']||1))+1});return{status:'PASS'};}cbAssert_(decision==='APPLY','Unsupported recommendation decision.');var change=cbParseJson_(row['Proposed Change JSON'],{}),undo={};if(change.type==='quickAction'){var existing=cbRows_(context.core,'quickActions').find(function(item){return item['Action Key']===change.actionKey;});if(!existing){var id=cbUuid_('QUICK-ACTION');cbAppend_(context.core,'quickActions',{'Quick Action ID':id,'Business ID':context.row['Business ID'],'Action Key':change.actionKey,'Label':change.label,'Page Key':change.pageKey,'Role IDs JSON':'[]','Configuration JSON':'{}','Sort Order':99,'Status':'Active','Created Time':now,'Updated Time':now,'Record Version':1});undo={type:'archiveQuickAction',recordId:id};}}else cbAssert_(change.type==='navigate','Only approved quick actions can be applied automatically. Other recommendations require manual review.');cbPlatformUpdateRow_(context.core,'aiRecommendations',row.__row,{'Status':'Applied','Approved By':context.user.userId,'Applied Time':now,'Undo Data JSON':JSON.stringify(undo),'Updated Time':now,'Record Version':Math.max(1,Number(row['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'APPLY AI RECOMMENDATION','AI Recommendation',row['Recommendation ID'],'PASS','Owner-approved bounded recommendation applied.');return{status:'PASS',change:change};
}
function cbCompletionSaveFeatureRequest_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageCommunications'),record={'Feature Request ID':cbText_(input.featureRequestId)||cbUuid_('FEATURE'),'Business ID':context.row['Business ID'],'Requested By':context.user.userId,'Page Key':cbText_(input.pageKey),'User Role':context.user.roleName,'Title':cbText_(input.title),'Problem':cbText_(input.problem),'Current Workaround':cbText_(input.currentWorkaround),'Frequency':cbText_(input.frequency),'Proposed Action':cbText_(input.proposedAction),'Status':'Open'};cbAssert_(record.Title&&record.Problem,'Feature request title and problem are required.');var result=cbCompletionUpsert_(context,'core','featureRequests','Feature Request ID','FEATURE',record,input);if(result.status==='PASS')cbAudit_(context.row['Business ID'],'CREATE FEATURE REQUEST','Feature Request',result.recordId,'PASS','Product improvement request created.');return result;
}
