function cbCompletionSaveInvoice_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageFinancial'),lines=Array.isArray(input.lines)?input.lines:[],subtotal=lines.reduce(function(sum,line){return sum+Number(line.quantity||0)*Number(line.unitPrice||0);},0),tax=Number(input.tax||0),total=subtotal+tax,id=cbText_(input.invoiceId)||cbUuid_('INVOICE'),existing=cbPlatformFindRow_(context.core,'invoices','Invoice ID',id),now=cbNow_(),record={'Invoice ID':id,'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Job ID':cbText_(input.jobId),'Quote ID':cbText_(input.quoteId),'Invoice Number':existing?existing['Invoice Number']:(cbText_(input.invoiceNumber)||('INV-'+Utilities.formatDate(new Date(),context.row['Time Zone']||CB_CONFIG.defaultTimeZone,'yyyyMMdd-HHmmss'))),'Invoice Type':cbText_(input.invoiceType)||'Standard','Status':cbText_(input.status)||'Draft','Issue Date':cbText_(input.issueDate),'Due Date':cbText_(input.dueDate),'Subtotal':subtotal,'Tax':tax,'Total':total,'Balance':total,'Notes':cbText_(input.notes),'Created By':existing?existing['Created By']:context.user.userId,'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'invoices',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'invoices',record);}lines.forEach(function(line){var quantity=Number(line.quantity||0),unitPrice=Number(line.unitPrice||0);cbAppend_(context.core,'invoiceLines',{'Invoice Line ID':cbUuid_('INVOICE-LINE'),'Business ID':context.row['Business ID'],'Invoice ID':id,'Description':cbText_(line.description),'Quantity':quantity,'Unit':cbText_(line.unit)||'each','Unit Price':unitPrice,'Line Total':quantity*unitPrice,'Status':'Active','Record Version':1});});cbAudit_(context.row['Business ID'],'SAVE INVOICE DRAFT','Invoice',id,'PASS','Invoice draft saved. Nothing sent or posted.');return{status:'PASS',invoiceId:id,total:total};
}
function cbCompletionRecordPayment_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageFinancial'),invoice=cbPlatformFindRow_(context.core,'invoices','Invoice ID',input.invoiceId),amount=Number(input.amount||0),now=cbNow_();cbAssert_(invoice,'Invoice was not found.');cbAssert_(amount>0,'Payment amount must be greater than zero.');cbAssert_(amount<=Number(invoice.Balance||invoice.Total||0),'Payment cannot exceed the recorded balance.');var id=cbUuid_('PAYMENT');cbAppend_(context.core,'payments',{'Payment ID':id,'Business ID':context.row['Business ID'],'Invoice ID':invoice['Invoice ID'],'Customer ID':invoice['Customer ID'],'Payment Date':cbText_(input.paymentDate)||now,'Amount':amount,'Method':cbText_(input.method)||'Manual','Reference':cbText_(input.reference),'Status':'Recorded','Recorded By':context.user.userId,'Created Time':now,'Record Version':1});var balance=Math.max(0,Number(invoice.Balance||invoice.Total||0)-amount);cbPlatformUpdateRow_(context.core,'invoices',invoice.__row,{'Balance':balance,'Status':balance===0?'Paid':invoice.Status,'Updated Time':now,'Record Version':Math.max(1,Number(invoice['Record Version']||1))+1});cbAudit_(context.row['Business ID'],'RECORD PAYMENT','Payment',id,'PASS','Manual payment record saved; no money moved.');return{status:'PASS',paymentId:id,balance:balance};
}
function cbCompletionSaveExpense_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageFinancial'),amount=Number(input.amount||0);cbAssert_(amount>=0,'Expense amount is invalid.');var record={'Expense ID':cbText_(input.expenseId)||cbUuid_('EXPENSE'),'Business ID':context.row['Business ID'],'Job ID':cbText_(input.jobId),'Vendor ID':cbText_(input.vendorId),'Category':cbText_(input.category),'Description':cbText_(input.description),'Expense Date':cbText_(input.expenseDate),'Amount':amount,'Tax':Number(input.tax||0),'Payment Method':cbText_(input.paymentMethod),'Receipt Document ID':cbText_(input.receiptDocumentId),'Status':cbText_(input.status)||'Recorded','Created By':context.user.userId};var result=cbCompletionUpsert_(context,'core','expenses','Expense ID','EXPENSE',record,input);if(result.status==='PASS')cbAudit_(context.row['Business ID'],'SAVE EXPENSE','Expense',result.recordId,'PASS','Expense record saved for accounting review.');return result;
}
function cbCompletionAttachmentFolder_(context){var root=DriveApp.getFolderById(context.row['Tenant Root Folder ID']),folders=root.getFoldersByName('06 — App Attachments');return folders.hasNext()?folders.next():root.createFolder('06 — App Attachments');}
function cbCompletionSaveAttachment_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageField'),name=cbText_(input.fileName),mime=cbText_(input.mimeType)||'application/octet-stream',data=cbText_(input.base64Data),size=Number(input.fileSize||0);cbAssert_(name,'File name is required.');cbAssert_(data,'Attachment data is required.');cbAssert_(size<=3000000,'Offline attachment must be reduced below 3 MB before upload.');cbAssert_(/^(image\/|application\/pdf|audio\/|text\/)/.test(mime),'This attachment type is not allowed.');var bytes=Utilities.base64Decode(data),folder=cbCompletionAttachmentFolder_(context),file=folder.createFile(Utilities.newBlob(bytes,mime,name)),now=cbNow_(),documentId=cbUuid_('DOCUMENT'),attachmentId=cbUuid_('ATTACHMENT');cbAppend_(context.core,'documents',{'Document ID':documentId,'Business ID':context.row['Business ID'],'Source Type':cbText_(input.relatedRecordType)||'App','Source ID':cbText_(input.relatedRecordId),'File ID':file.getId(),'File Name':name,'Mime Type':mime,'Access Classification':cbText_(input.visibility)||'Internal','Created By':context.user.userId,'Created Time':now,'Record Version':1});cbAppend_(context.core,'attachments',{'Attachment ID':attachmentId,'Business ID':context.row['Business ID'],'Document ID':documentId,'Related Record Type':cbText_(input.relatedRecordType),'Related Record ID':cbText_(input.relatedRecordId),'File ID':file.getId(),'File Name':name,'Mime Type':mime,'File Size':size,'Capture Time':cbText_(input.captureTime)||now,'Local Operation ID':cbText_(input.operationId),'Upload Status':'Uploaded','Visibility':cbText_(input.visibility)||'Internal','Created By':context.user.userId,'Created Time':now,'Record Version':1});cbAudit_(context.row['Business ID'],'UPLOAD ATTACHMENT','Document',documentId,'PASS','Private attachment uploaded.');return{status:'PASS',documentId:documentId,attachmentId:attachmentId,fileId:file.getId()};
}
