/** Internal messaging, email/SMS management and portal communication records. */
function cbCompletionUserIds_(context){return cbRows_(context.core,'users').filter(function(row){return cbText_(row.Status).toUpperCase()==='ACTIVE';}).map(function(row){return row['User ID'];}).concat(['USER-OWNER']);}
function cbCompletionCreateConversation_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageCommunications'),type=cbText_(input.conversationType)||'Direct',subject=cbText_(input.subject)||type,participants=Array.isArray(input.participantUserIds)?input.participantUserIds.map(cbText_).filter(Boolean):[],allowed=cbCompletionUserIds_(context);participants.forEach(function(id){cbAssert_(allowed.indexOf(id)>=0,'Conversation participant is not an active business user.');});if(participants.indexOf(context.user.userId)<0)participants.push(context.user.userId);var now=cbNow_(),id=cbUuid_('CONVERSATION');cbAppend_(context.core,'conversations',{'Conversation ID':id,'Business ID':context.row['Business ID'],'Conversation Type':type,'Subject':subject,'Related Record Type':cbText_(input.relatedRecordType),'Related Record ID':cbText_(input.relatedRecordId),'Participant IDs JSON':JSON.stringify(participants),'Status':'Active','Created Time':now,'Updated Time':now,'Record Version':1});participants.forEach(function(userId){cbAppend_(context.core,'conversationMembers',{'Conversation Member ID':cbUuid_('CONVERSATION-MEMBER'),'Business ID':context.row['Business ID'],'Conversation ID':id,'User ID':userId,'Role':'Member','Notification Level':'All','Joined Time':now,'Left Time':'','Status':'Active','Record Version':1});});cbAudit_(context.row['Business ID'],'CREATE CONVERSATION','Conversation',id,'PASS','Internal business conversation created.');return{status:'PASS',conversationId:id};
}
function cbCompletionConversationVisible_(context,conversation){
  if(context.user.owner)return true;var participants=cbParseList_(conversation['Participant IDs JSON']);if(participants.indexOf(context.user.userId)>=0)return true;if(conversation['Conversation Type']==='Channel'&&cbText_(conversation.Status).toUpperCase()==='ACTIVE')return true;return cbRows_(context.core,'conversationMembers').some(function(row){return row['Conversation ID']===conversation['Conversation ID']&&row['User ID']===context.user.userId&&cbText_(row.Status).toUpperCase()==='ACTIVE';});
}
function cbCompletionSendInternalMessage_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageCommunications'),body=cbText_(input.body),conversation=cbPlatformFindRow_(context.core,'conversations','Conversation ID',input.conversationId),now=cbNow_();cbAssert_(body,'Message body is required.');cbAssert_(conversation,'Conversation was not found.');cbAssert_(cbCompletionConversationVisible_(context,conversation),'You cannot access this conversation.');var id=cbUuid_('MESSAGE');cbAppend_(context.core,'messages',{'Message ID':id,'Business ID':context.row['Business ID'],'Conversation ID':conversation['Conversation ID'],'Sender User ID':context.user.userId,'Message Type':cbText_(input.messageType)||'Text','Body':body,'Attachment IDs JSON':JSON.stringify(input.attachmentIds||[]),'Reply To Message ID':cbText_(input.replyToMessageId),'Status':'Sent Internal','Created Time':now,'Edited Time':'','Record Version':1});cbPlatformUpdateRow_(context.core,'conversations',conversation.__row,{'Updated Time':now,'Record Version':Math.max(1,Number(conversation['Record Version']||1))+1});return{status:'PASS',messageId:id,message:'Internal message saved.'};
}
function cbCompletionSaveEmailDraft_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageCommunications'),to=cbText_(input.toAddress),subject=cbText_(input.subject),body=cbText_(input.body),now=cbNow_();cbAssert_(to&&/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(to),'A valid recipient email is required.');cbAssert_(subject||body,'Email subject or body is required.');var threadId=cbText_(input.emailThreadId)||cbUuid_('EMAIL-THREAD'),existing=cbPlatformFindRow_(context.core,'emailThreads','Email Thread ID',threadId);var thread={'Email Thread ID':threadId,'Business ID':context.row['Business ID'],'Provider':'Provider Neutral','Provider Thread ID':cbText_(input.providerThreadId),'Mailbox':cbText_(input.mailbox),'Subject':subject,'Customer ID':cbText_(input.customerId),'Job ID':cbText_(input.jobId),'Quote ID':cbText_(input.quoteId),'Assigned User ID':context.user.userId,'Needs Reply':'No','Last Message Time':now,'Status':'Draft','Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'emailThreads',existing.__row,thread);else cbAppend_(context.core,'emailThreads',thread);var id=cbUuid_('EMAIL-MESSAGE');cbAppend_(context.core,'emailMessages',{'Email Message ID':id,'Business ID':context.row['Business ID'],'Email Thread ID':threadId,'Provider Message ID':'','Direction':'Outbound Draft','From Address':context.user.email,'To Addresses JSON':JSON.stringify([to]),'Cc Addresses JSON':JSON.stringify(cbParseList_(input.ccAddresses)),'Subject':subject,'Body Preview':body,'Document ID':'','Message Time':now,'Status':'Draft — Not Sent','Created Time':now,'Record Version':1});cbAudit_(context.row['Business ID'],'SAVE EMAIL DRAFT','Email Message',id,'PASS','Email draft saved internally; no email sent.');return{status:'PASS',emailThreadId:threadId,emailMessageId:id,message:'Email draft saved. Nothing sent.'};
}
