/** Operational services for customers, work, quotes, schedule, inventory, fleet, money and documents. */
function cbCompletionSaveCustomer_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'viewCustomers'),name=cbText_(input.customerName),now=cbNow_();cbAssert_(name,'Customer name is required.');
  var id=cbText_(input.customerId)||cbUuid_('CUSTOMER'),existing=cbPlatformFindRow_(context.core,'customers','Customer ID',id),record={'Customer ID':id,'Business ID':context.row['Business ID'],'Customer Name':name,'Email':cbText_(input.email),'Phone':cbText_(input.phone),'Status':cbText_(input.status)||'Active','Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};
  if(existing)cbPlatformUpdateRow_(context.core,'customers',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'customers',record);}cbAudit_(context.row['Business ID'],'SAVE CUSTOMER','Customer',id,'PASS','Customer saved through Commercial Office.');return{status:'PASS',customerId:id,message:'Customer saved.'};
}
function cbCompletionSaveProperty_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'viewCustomers'),name=cbText_(input.propertyName)||cbText_(input.address),now=cbNow_();cbAssert_(name,'Property name or address is required.');var id=cbText_(input.propertyId)||cbUuid_('PROPERTY'),existing=cbPlatformFindRow_(context.core,'properties','Property ID',id),record={'Property ID':id,'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Property Name':name,'Address':cbText_(input.address),'Status':cbText_(input.status)||'Active','Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'properties',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'properties',record);}cbAudit_(context.row['Business ID'],'SAVE PROPERTY','Property',id,'PASS','Property saved.');return{status:'PASS',propertyId:id};
}
function cbCompletionSaveRequest_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageWork'),subject=cbText_(input.subject),now=cbNow_();cbAssert_(subject,'Request subject is required.');var id=cbText_(input.requestId)||cbUuid_('REQUEST'),existing=cbPlatformFindRow_(context.core,'requests','Request ID',id),record={'Request ID':id,'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Property ID':cbText_(input.propertyId),'Source':cbText_(input.source)||'Office','Subject':subject,'Details':cbText_(input.details),'Priority':cbText_(input.priority)||'Normal','Assigned User ID':cbText_(input.assignedUserId),'Status':cbText_(input.status)||'New','Created By':existing?existing['Created By']:context.user.userId,'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'requests',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'requests',record);}cbAudit_(context.row['Business ID'],'SAVE REQUEST','Request',id,'PASS','Request saved.');return{status:'PASS',requestId:id};
}
function cbCompletionSaveJob_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageWork'),title=cbText_(input.projectTitle),now=cbNow_();cbAssert_(title,'Project title is required.');var id=cbText_(input.jobId)||cbUuid_('JOB'),existing=cbPlatformFindRow_(context.core,'jobs','Job ID',id),number=existing?existing['Job Number']:(cbText_(input.jobNumber)||('JOB-'+Utilities.formatDate(new Date(),context.row['Time Zone']||CB_CONFIG.defaultTimeZone,'yyyyMMdd-HHmmss'))),record={'Job ID':id,'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Property ID':cbText_(input.propertyId),'Job Number':number,'Project Title':title,'Status':cbText_(input.status)||'Lead','Location ID':cbText_(input.locationId)||'LOC-MAIN-SHOP','Crew ID':cbText_(input.crewId),'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'jobs',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'jobs',record);}cbAudit_(context.row['Business ID'],'SAVE JOB','Job',id,'PASS','Job saved.');return{status:'PASS',jobId:id,jobNumber:number};
}
function cbCompletionSaveTask_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageWork'),title=cbText_(input.taskTitle),now=cbNow_();cbAssert_(title,'Task title is required.');var id=cbText_(input.taskId)||cbUuid_('TASK'),existing=cbPlatformFindRow_(context.core,'tasks','Task ID',id),record={'Task ID':id,'Business ID':context.row['Business ID'],'Job ID':cbText_(input.jobId),'Task Title':title,'Assigned User ID':cbText_(input.assignedUserId),'Assigned Crew ID':cbText_(input.assignedCrewId),'Status':cbText_(input.status)||'Open','Due Time':cbText_(input.dueTime),'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'tasks',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'tasks',record);}cbAudit_(context.row['Business ID'],'SAVE TASK','Task',id,'PASS','Task saved.');return{status:'PASS',taskId:id};
}
function cbCompletionSaveMeasurement_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageField'),name=cbText_(input.measurementName),value=Number(input.value||0),method=cbText_(input.method)||'Direct measurement',now=cbNow_();cbAssert_(name,'Measurement name is required.');cbAssert_(value>=0,'Measurement value is invalid.');
  var id=cbText_(input.measurementId)||cbUuid_('MEASUREMENT'),existing=cbPlatformFindRow_(context.core,'measurements','Measurement ID',id),record={'Measurement ID':id,'Business ID':context.row['Business ID'],'Job ID':cbText_(input.jobId),'Quote ID':cbText_(input.quoteId),'Related Record Type':cbText_(input.relatedRecordType)||'Job','Related Record ID':cbText_(input.relatedRecordId)||cbText_(input.jobId)||cbText_(input.quoteId),'Measurement Name':name,'Measurement Type':cbText_(input.measurementType)||'Length','Value':value,'Unit':cbText_(input.unit)||'ft','Method':method,'Confidence':cbText_(input.confidence)||(method==='Visual estimate'?'Needs verification':'User confirmed'),'Reference Size':Number(input.referenceSize||0),'Reference Unit':cbText_(input.referenceUnit),'Photo Document ID':cbText_(input.photoDocumentId),'Notes':cbText_(input.notes),'Status':cbText_(input.status)||'Active','Created By':context.user.userId,'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};
  if(existing)cbPlatformUpdateRow_(context.core,'measurements',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'measurements',record);}cbAudit_(context.row['Business ID'],'SAVE MEASUREMENT','Measurement',id,'PASS','Measurement saved as '+method+'.');return{status:'PASS',measurementId:id,message:'Measurement saved.',recordVersion:record['Record Version']};
}
