function cbCompletionBootstrap_(businessId){
  var context=cbCompletionContext_(businessId,'');if(context.user.owner||cbCompletionCan_(context.user,'manageSettings'))cbCompletionSeedDefaults_(context);var packs=cbIndustryPacksFromRow_(context.row),modules=cbCompletionEntitlements_(context);
  var data={status:'PASS',serverTime:cbNow_(),version:CB_CONFIG.version,schemaVersion:CB_CONFIG.schemaVersion,user:{email:context.user.email,userId:context.user.userId,displayName:context.user.displayName||context.user.email,roleId:context.user.roleId,roleName:context.user.roleName,owner:context.user.owner,permissions:context.user.permissions},business:{businessId:context.row['Business ID'],businessName:context.row['Business Name'],currency:context.row.Currency,timeZone:context.row['Time Zone'],industryPack:packs[0]||'',industryPacks:packs},modules:modules,productShells:cbCompletionProductShells_(),safeguards:{externalActionsEnabled:false,productionMigrationEnabled:false,automaticSocialPublishing:false,automaticCustomerSending:false,automaticFinancialActions:false}};
  data.users=cbCompletionPublicUsers_(context);data.roles=cbCompletionListRows_(context,'core','roles',100);data.settings=cbCompletionCan_(context.user,'manageSettings')?cbCompletionListRows_(context,'core','settings',500):[];data.quickActions=cbCompletionListRows_(context,'core','quickActions',100);data.providers=cbCompletionCan_(context.user,'manageSettings')?cbCompletionListRows_(context,'core','providers',50):[];
  var workView=cbCompletionAssignedWork_(context),canCustomers=cbCompletionCan_(context.user,'viewCustomers')||cbCompletionCan_(context.user,'manageWork')||cbCompletionCan_(context.user,'manageQuotes');data.customers=canCustomers?cbCompletionListRows_(context,'core','customers',600):[];data.contacts=canCustomers?cbCompletionListRows_(context,'core','contacts',600):[];data.properties=canCustomers?cbCompletionListRows_(context,'core','properties',600):[];data.requests=cbCompletionCan_(context.user,'manageWork')?cbCompletionListRows_(context,'core','requests',500):[];data.jobs=workView.jobs;data.workOrders=cbCompletionCan_(context.user,'manageWork')?cbCompletionListRows_(context,'core','workOrders',600):[];data.tasks=workView.tasks;data.scheduleEvents=workView.scheduleEvents;data.timeEntries=workView.timeEntries;data.jobNotes=workView.jobNotes;
  data.quotes=cbCompletionCan_(context.user,'manageQuotes')||cbCompletionCan_(context.user,'manageWork')?cbCompletionQuoteView_(context):[];data.measurements=cbCompletionListRows_(context,'core','measurements',800);data.measurementPoints=cbCompletionListRows_(context,'core','measurementPoints',1200);data.priceBook=cbCompletionCan_(context.user,'manageQuotes')||cbCompletionCan_(context.user,'manageInventory')||cbCompletionCan_(context.user,'useInventory')?cbCompletionListRows_(context,'inventory','items',1000):[];data.inventoryTransactions=cbCompletionCan_(context.user,'manageInventory')||cbCompletionCan_(context.user,'useInventory')?cbCompletionListRows_(context,'inventory','transactions',500):[];data.materialRequests=cbCompletionCan_(context.user,'manageInventory')||cbCompletionCan_(context.user,'useInventory')?cbCompletionListRows_(context,'inventory','materialRequests',300):[];
  data.assets=cbCompletionListRows_(context,'assets','assets',800);data.assignments=cbCompletionListRows_(context,'assets','assignments',500);data.maintenance=cbCompletionListRows_(context,'assets','maintenance',500);data.inspections=cbCompletionListRows_(context,'assets','inspections',500);data.vehicles=cbCompletionListRows_(context,'assets','vehicles',300);data.usageLogs=cbCompletionListRows_(context,'assets','usageLogs',500);
  var canFinancial=cbCompletionCan_(context.user,'manageFinancial')||cbCompletionCan_(context.user,'viewFinancial');data.invoices=canFinancial?cbCompletionListRows_(context,'core','invoices',500):[];data.invoiceLines=canFinancial?cbCompletionListRows_(context,'core','invoiceLines',1000):[];data.payments=canFinancial?cbCompletionListRows_(context,'core','payments',500):[];data.expenses=canFinancial?cbCompletionListRows_(context,'core','expenses',500):[];data.documents=cbCompletionListRows_(context,'core','documents',800);data.attachments=cbCompletionListRows_(context,'core','attachments',800);
  var communications=cbCompletionCommunicationView_(context);data.conversations=communications.conversations;data.messages=communications.messages;data.emailThreads=communications.emailThreads;data.emailMessages=communications.emailMessages;data.smsThreads=communications.smsThreads;data.smsMessages=communications.smsMessages;data.portalThreads=communications.portalThreads;data.portalMessages=communications.portalMessages;
  var canSocial=cbCompletionCan_(context.user,'manageSocial');data.socialAccounts=canSocial?cbCompletionListRows_(context,'core','socialAccounts',100):[];data.socialPosts=canSocial?cbCompletionListRows_(context,'core','socialPosts',800):[];data.socialMetrics=canSocial?cbCompletionListRows_(context,'core','socialMetrics',1000):[];data.campaigns=canSocial?cbCompletionListRows_(context,'core','campaigns',300):[];
  data.aiKnowledge=cbCompletionListRows_(context,'core','aiKnowledge',300);data.aiRecommendations=(context.user.owner||cbCompletionCan_(context.user,'manageSettings'))&&typeof cbCompletionRecommendations_==='function'?cbCompletionRecommendations_(context):[];data.featureRequests=cbCompletionListRows_(context,'core','featureRequests',300);data.voiceQueue=cbCompletionListRows_(context,'core','voiceQueue',300);data.actionQueue=cbCompletionListRows_(context,'core','actionQueue',300);data.notifications=cbCompletionListRows_(context,'core','notifications',300);data.syncConflicts=cbCompletionListRows_(context,'core','syncConflicts',300);
  if(typeof cbCompletionParityData_==='function')Object.assign(data,cbCompletionParityData_(context));
  return data;
}
function cbCompletionSaveUser_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageUsers'),email=cbText_(input.email).toLowerCase(),displayName=cbText_(input.displayName)||email,roleId=cbText_(input.roleId)||'ROLE-VIEWER',now=cbNow_();cbAssert_(/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email),'A valid user email is required.');cbAssert_(cbRows_(context.core,'roles').some(function(row){return row['Role ID']===roleId;}),'Selected role was not found.');
  var existing=cbRows_(context.core,'users').find(function(row){return cbText_(row.Email).toLowerCase()===email;});var record={'Business ID':context.row['Business ID'],'Email':email,'Display Name':displayName,'Role ID':roleId,'Status':cbText_(input.status)||'Active','Location Restrictions':cbText_(input.locationRestrictions),'Crew Restrictions':cbText_(input.crewRestrictions),'Module Restrictions':cbText_(input.moduleRestrictions),'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};
  var userId=existing?existing['User ID']:cbUuid_('USER');record['User ID']=userId;if(existing)cbPlatformUpdateRow_(context.core,'users',existing.__row,record);else{record['Created Time']=now;cbAppend_(context.core,'users',record);}cbAudit_(context.row['Business ID'],'SAVE USER','User',userId,'PASS','Business user access saved.');return{status:'PASS',userId:userId,message:'User access saved.'};
}
