function cbCompletionSaveSmsDraft_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageCommunications'),phone=cbText_(input.toNumber),body=cbText_(input.body),consent=cbText_(input.consentStatus)||'Unknown',now=cbNow_();cbAssert_(phone,'Customer phone number is required.');cbAssert_(body,'Text message body is required.');var threadId=cbText_(input.smsThreadId)||cbUuid_('SMS-THREAD'),existing=cbPlatformFindRow_(context.core,'smsThreads','SMS Thread ID',threadId),thread={'SMS Thread ID':threadId,'Business ID':context.row['Business ID'],'Provider':'Provider Neutral','Provider Thread ID':'','Business Number':cbText_(input.businessNumber),'Customer Number':phone,'Customer ID':cbText_(input.customerId),'Job ID':cbText_(input.jobId),'Quote ID':cbText_(input.quoteId),'Assigned User ID':context.user.userId,'Consent Status':consent,'Needs Reply':'No','Last Message Time':now,'Status':'Draft','Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};if(existing)cbPlatformUpdateRow_(context.core,'smsThreads',existing.__row,thread);else cbAppend_(context.core,'smsThreads',thread);var id=cbUuid_('SMS-MESSAGE');cbAppend_(context.core,'smsMessages',{'SMS Message ID':id,'Business ID':context.row['Business ID'],'SMS Thread ID':threadId,'Provider Message ID':'','Direction':'Outbound Draft','From Number':cbText_(input.businessNumber),'To Number':phone,'Body':body,'Media Document IDs JSON':JSON.stringify(input.documentIds||[]),'Delivery Status':'Not Sent','Consent Status':consent,'Message Time':now,'Status':'Draft — Not Sent','Created Time':now,'Record Version':1});cbAudit_(context.row['Business ID'],'SAVE SMS DRAFT','SMS Message',id,'PASS','Business text draft saved internally; no SMS sent.');return{status:'PASS',smsThreadId:threadId,smsMessageId:id,message:'Text draft saved. Nothing sent.'};
}
function cbCompletionSavePortalMessage_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageCommunications'),body=cbText_(input.body),now=cbNow_();cbAssert_(body,'Portal message body is required.');var threadId=cbText_(input.portalThreadId),thread=threadId?cbPlatformFindRow_(context.core,'customerPortalThreads','Portal Thread ID',threadId):null;if(!thread){threadId=cbUuid_('PORTAL-THREAD');cbAppend_(context.core,'customerPortalThreads',{'Portal Thread ID':threadId,'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Related Record Type':cbText_(input.relatedRecordType),'Related Record ID':cbText_(input.relatedRecordId),'Subject':cbText_(input.subject)||'Customer portal conversation','Status':'Active','Created Time':now,'Updated Time':now,'Record Version':1});}var id=cbUuid_('PORTAL-MESSAGE');cbAppend_(context.core,'customerPortalMessages',{'Portal Message ID':id,'Business ID':context.row['Business ID'],'Portal Thread ID':threadId,'Sender Type':'Business User','Sender ID':context.user.userId,'Body':body,'Attachment IDs JSON':JSON.stringify(input.attachmentIds||[]),'Message Time':now,'Status':'Draft — Portal Release Required','Record Version':1});cbAudit_(context.row['Business ID'],'SAVE PORTAL MESSAGE','Portal Message',id,'PASS','Portal message prepared; customer release remains required.');return{status:'PASS',portalThreadId:threadId,portalMessageId:id};
}
function cbCompletionConvertMessageToTask_(request){
  var input=request||{},context=cbCompletionContext_(input.businessId,'manageWork'),message=cbPlatformFindRow_(context.core,'messages','Message ID',input.messageId);cbAssert_(message,'Message was not found.');var task=cbCompletionSaveTask_({businessId:context.row['Business ID'],taskTitle:cbText_(input.taskTitle)||message.Body,jobId:cbText_(input.jobId),assignedUserId:cbText_(input.assignedUserId),status:'Open',dueTime:cbText_(input.dueTime)});cbAppend_(context.core,'messageEvents',{'Message Event ID':cbUuid_('MESSAGE-EVENT'),'Business ID':context.row['Business ID'],'Message ID':message['Message ID'],'Event Type':'Converted to Task','User ID':context.user.userId,'Details JSON':JSON.stringify({taskId:task.taskId}),'Timestamp':cbNow_(),'Record Version':1});return{status:'PASS',taskId:task.taskId};
}
function cbCompletionCommunicationSummary_(businessId){
  var context=cbCompletionContext_(businessId,'manageCommunications');return{status:'PASS',conversations:cbCompletionListRows_(context,'core','conversations',500).filter(function(row){return cbCompletionConversationVisible_(context,row);}),messages:cbCompletionListRows_(context,'core','messages',1500),emailThreads:cbCompletionListRows_(context,'core','emailThreads',500),emailMessages:cbCompletionListRows_(context,'core','emailMessages',1000),smsThreads:cbCompletionListRows_(context,'core','smsThreads',500),smsMessages:cbCompletionListRows_(context,'core','smsMessages',1000),portalThreads:cbCompletionListRows_(context,'core','customerPortalThreads',500),portalMessages:cbCompletionListRows_(context,'core','customerPortalMessages',1000),providers:cbCompletionListRows_(context,'core','providers',50)};
}
