/** Offline Quote Builder snapshots, draft revisions and idempotent operation synchronization. */
function cbPlatformQuoteGroups_(lines){var groups={};lines.forEach(function(line){var id=line['Quote ID'],revision=Number(line['Quote Revision']||0);if(!groups[id]||revision>groups[id].revision)groups[id]={revision:revision,lines:[]};if(revision===groups[id].revision)groups[id].lines.push(line);});return groups;}
function cbUpsertQuoteDraft_(request){
  var input=request||{},context=cbPlatformContext_(input.businessId),now=cbNow_(),quoteId=cbText_(input.quoteId)||cbUuid_('QUOTE'),existing=cbPlatformFindRow_(context.core,'quotes','Quote ID',quoteId),revision=existing?Math.max(1,Number(existing.Revision||1))+1:1,lines=Array.isArray(input.lines)?input.lines:[],subtotal=lines.reduce(function(sum,line){return sum+Number(line.quantity||0)*Number(line.unitPrice||0);},0),tax=Number(input.tax||0),total=subtotal+tax;
  var record={'Business ID':context.row['Business ID'],'Customer ID':cbText_(input.customerId),'Property ID':cbText_(input.propertyId),'Job ID':cbText_(input.jobId),'Quote Number':existing?existing['Quote Number']:(cbText_(input.quoteNumber)||('Q-'+Utilities.formatDate(new Date(),context.row['Time Zone']||CB_CONFIG.defaultTimeZone,'yyyyMMdd-HHmmss'))),'Project Title':cbText_(input.projectTitle)||'Untitled quote','Scope':cbText_(input.scope),'Measurement Notes':cbText_(input.measurementNotes),'Status':'Draft','Revision':revision,'Subtotal':subtotal,'Tax':tax,'Total':total,'Price Snapshot Time':cbText_(input.priceSnapshotTime),'Offline Pack ID':cbText_(input.offlinePackId),'Updated Time':now,'Record Version':existing?Math.max(1,Number(existing['Record Version']||1))+1:1};
  if(existing)cbPlatformUpdateRow_(context.core,'quotes',existing.__row,record);else{record['Quote ID']=quoteId;record['Created By']=cbCurrentEmail_();record['Created Time']=now;cbAppend_(context.core,'quotes',record);}
  lines.forEach(function(line){var quantity=Number(line.quantity||0),unitPrice=Number(line.unitPrice||0);cbAppend_(context.core,'quoteLines',{'Quote Line ID':cbText_(line.quoteLineId)||cbUuid_('QUOTE-LINE'),'Business ID':context.row['Business ID'],'Quote ID':quoteId,'Quote Revision':revision,'Line Type':cbText_(line.lineType)||'Material','Description':cbText_(line.description),'Quantity':quantity,'Unit':cbText_(line.unit)||'each','Unit Price':unitPrice,'Line Total':quantity*unitPrice,'Price Source':cbText_(line.priceSource)||'Manual or cached','Price Status':cbText_(line.priceStatus)||'Owner review required','Status':'Active','Created Time':now,'Record Version':1});});cbAudit_(context.row['Business ID'],'SAVE QUOTE DRAFT','Quote',quoteId,'PASS','Draft quote saved. Nothing approved or sent.');return{status:'PASS',message:'Quote draft saved.',quoteId:quoteId,revision:revision,total:total};
}
function cbPwaBootstrap_(businessId){
  var context=cbPlatformContext_(businessId),row=context.row,packs=cbIndustryPacksFromRow_(row),customers=cbRows_(context.core,'customers'),jobs=cbRows_(context.core,'jobs'),quotes=cbRows_(context.core,'quotes'),quoteGroups=cbPlatformQuoteGroups_(cbRows_(context.core,'quoteLines')),items=cbRows_(context.inventory,'items'),assets=cbRows_(context.assets,'assets'),assignments=cbRows_(context.assets,'assignments').filter(function(item){return cbText_(item.Status).toUpperCase()==='ACTIVE'&&!item['Returned Time'];}),maintenance=cbRows_(context.assets,'maintenance'),inspections=cbRows_(context.assets,'inspections'),vehicles=cbRows_(context.assets,'vehicles'),usage=cbRows_(context.assets,'usageLogs');
  return{status:'PASS',serverTime:cbNow_(),version:CB_CONFIG.version,business:{businessId:row['Business ID'],businessName:row['Business Name'],currency:row.Currency,timeZone:row['Time Zone'],industryPack:packs[0],industryPacks:packs},customers:customers.slice().reverse().slice(0,300).map(function(item){return{customerId:item['Customer ID'],name:item['Customer Name'],email:item.Email,phone:item.Phone,status:item.Status};}),jobs:jobs.slice().reverse().slice(0,300).map(function(item){return{jobId:item['Job ID'],jobNumber:item['Job Number'],projectTitle:item['Project Title'],customerId:item['Customer ID'],status:item.Status};}),quotes:quotes.slice().reverse().slice(0,200).map(function(item){return{quoteId:item['Quote ID'],quoteNumber:item['Quote Number'],projectTitle:item['Project Title'],customerId:item['Customer ID'],jobId:item['Job ID'],status:item.Status,revision:item.Revision,total:item.Total,lines:(quoteGroups[item['Quote ID']]||{lines:[]}).lines};}),assets:assets.slice().reverse().slice(0,400).map(function(item){var assignment=assignments.find(function(row){return row['Asset ID']===item['Asset ID'];});return{assetId:item['Asset ID'],assetNumber:item['Asset Number'],assetType:item['Asset Type']||item.Category,description:item.Description,category:item.Category,manufacturer:item.Manufacturer,model:item.Model,vin:item.VIN,licensePlate:item['License Plate'],status:item.Status,availability:item.Availability,assignedJobId:item['Assigned Job ID']||(assignment&&assignment['Job ID'])||'',nextService:item['Next Service'],meterHours:item['Meter Hours'],mileage:item.Mileage};}),assignments:assignments,maintenance:maintenance.slice().reverse().slice(0,300).map(function(item){return{maintenanceId:item['Maintenance ID'],assetId:item['Asset ID'],maintenanceType:item['Maintenance Type'],status:item.Status,priority:item.Priority,dueDate:item['Due Date'],notes:item.Notes};}),inspections:inspections.slice().reverse().slice(0,200),vehicles:vehicles.slice().reverse().slice(0,200),usageLogs:usage.slice().reverse().slice(0,200),priceBook:items.filter(function(item){return cbText_(item.Status).toUpperCase()!=='INACTIVE';}).map(function(item){return{itemId:item['Item ID'],sku:item.SKU,description:item.Description,unit:item['Unit of Measure'],unitPrice:item['Selling Price'],updatedTime:item['Updated Time'],priceStatus:'Cached owner-review price'};}),safeguards:{externalActionsEnabled:false,productionMigrationEnabled:false}};
}
function cbPlatformOperationAlreadyApplied_(context,operationId){return cbRows_(context.core,'offlineSync').find(function(row){return row['Idempotency Key']===operationId;})||null;}
function cbApplyOfflineOperation_(context,operation){
  var operationId=cbText_(operation.operationId);cbAssert_(operationId,'Offline operation ID is required.');var prior=cbPlatformOperationAlreadyApplied_(context,operationId);if(prior)return{operationId:operationId,status:'ALREADY_SYNCED',recordId:prior['Record ID']};var payload=operation.payload||{},action=cbText_(operation.action).toUpperCase(),input=Object.assign({},payload,{businessId:context.row['Business ID']}),result;
  if(action==='UPSERT_QUOTE_DRAFT')result=cbUpsertQuoteDraft_(input);else if(action==='ADD_CUSTOMER')result=cbAddCustomer_(input);else if(action==='ADD_JOB')result=cbAddJob_(input);else if(action==='ASSIGN_ASSET_TO_JOB')result=cbAssignAssetToJob_(input);else if(action==='RETURN_ASSET_FROM_JOB')result=cbReturnAssetFromJob_(input);else if(action==='SCHEDULE_MAINTENANCE')result=cbScheduleMaintenance_(input);else if(action==='RECORD_INSPECTION')result=cbRecordInspection_(input);else if(action==='RECORD_ASSET_USAGE')result=cbRecordAssetUsage_(Object.assign(input,{offlineOperationId:operationId}));else throw new Error('Unsupported offline operation: '+action);
  var recordId=result.quoteId||result.customerId||result.jobId||result.assignmentId||result.maintenanceId||result.inspectionId||result.usageId||cbText_(operation.recordId),now=cbNow_();cbAppend_(context.core,'offlineSync',{'Sync Event ID':cbUuid_('SYNC'),'Business ID':context.row['Business ID'],'User ID':'USER-OWNER','Device ID':cbText_(operation.deviceId),'Action Type':action,'Local Timestamp':cbText_(operation.localTimestamp),'Record Type':cbText_(operation.recordType),'Record ID':recordId,'Record Version':Number(result.revision||1),'Idempotency Key':operationId,'Sync Status':'SYNCED','Retry Count':Number(operation.retryCount||0),'Payload Hash':Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,JSON.stringify(payload))).slice(0,40),'Error Status':'','Server Timestamp':now});return{operationId:operationId,status:'SYNCED',recordId:recordId,result:result};
}
function cbSyncOperations_(request){var input=request||{},context=cbPlatformContext_(input.businessId),operations=Array.isArray(input.operations)?input.operations:[];cbAssert_(operations.length<=100,'Sync is limited to 100 operations per request.');var lock=LockService.getScriptLock();lock.waitLock(30000);try{return{status:'PASS',businessId:context.row['Business ID'],serverTime:cbNow_(),results:operations.map(function(operation){try{return cbApplyOfflineOperation_(context,operation);}catch(error){cbError_(context.row['Business ID'],'SYNC '+cbText_(operation.action),error);return{operationId:cbText_(operation.operationId),status:'FAILED',message:error.message};}})};}finally{lock.releaseLock();}}
