import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const ALLOWED=new Set(["ccf25333-47cd-42ca-a20b-cdbc63a8a695","6dd51b31-5974-4691-b8b8-83e5877528c0"]);
const U=Deno.env.get("SUPABASE_URL")||"",K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const UA="Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Safari/537.36";
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
async function uid(r:Request){const t=String(r.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!t)throw Error("Sign in required.");const x=await fetch(`${U}/auth/v1/user`,{headers:{authorization:`Bearer ${t}`,apikey:K}}),p=await x.json().catch(()=>({}));if(!x.ok||!p?.id)throw Error("Session expired.");return String(p.id)}
function dec(v:any){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&nbsp;|&#160;/gi," ")}
function text(v:any){return dec(v).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function price(v:string){const m=v.match(/\$\s*([0-9]{1,6}(?:,[0-9]{3})*(?:\.[0-9]{1,2})?)/);return m?Number(m[1].replace(/,/g,"")):null}
function uniq(rows:any[]){const m=new Map<string,any>();for(const x of rows){const k=String(x.url||x.source+"|"+x.title).toLowerCase();if(!m.has(k))m.set(k,x)}return[...m.values()]}
async function get(url:string){const c=new AbortController(),to=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:c.signal});const html=await r.text().catch(()=>"");if(!r.ok)throw Error(`HTTP ${r.status}`);return{url:r.url,html}}finally{clearTimeout(to)}}
function matches(title:string,term:string){const a=title.toLowerCase(),parts=term.toLowerCase().split(/\s+/).filter(x=>x.length>2);return a.includes(term.toLowerCase())||parts.some(x=>a.includes(x))}
function craigslist(html:string,base:string,term:string){const out:any[]=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){if(out.length>=30)break;let href=dec(m[1]||""),title=text(m[2]||"");if(!title||title.length<4||!/\/d\//.test(href))continue;try{href=new URL(href,base).toString()}catch{continue}if(!matches(title,term))continue;const around=text(html.slice(Math.max(0,(m.index||0)-700),Math.min(html.length,(m.index||0)+2000)));out.push({source:"Craigslist",title,url:href,price:price(around),term,automatic:true})}return out}
function hibid(html:string,base:string,term:string){const out:any[]=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']*(?:\/lot\/|\/lot-information\/)[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){if(out.length>=30)break;let href=dec(m[1]||""),title=text(m[2]||"");if(!title||title.length<4)continue;try{href=new URL(href,base).toString()}catch{continue}if(!matches(title,term))continue;const around=text(html.slice(Math.max(0,(m.index||0)-700),Math.min(html.length,(m.index||0)+2200)));out.push({source:"HiBid",title,url:href,price:price(around),term,automatic:true})}return out}
function facebook(html:string,base:string,term:string){const out:any[]=[];for(const m of html.matchAll(/href=["']([^"']*\/marketplace\/item\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){if(out.length>=20)break;let href=dec(m[1]||""),title=text(m[2]||"");if(!title||title.length<4)continue;try{href=new URL(href,base).toString()}catch{continue}if(!matches(title,term))continue;out.push({source:"Facebook Marketplace",title,url:href,price:price(text(m[0]||"")),term,automatic:true})}return out}
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response(null,{status:204,headers:cors(r)});if(r.method!=="POST")return json(r,405,{error:"POST required"});try{const id=await uid(r);if(!ALLOWED.has(id))return json(r,403,{error:"Not authorized"});const b=await r.json().catch(()=>({}));let terms=Array.isArray(b.terms)?b.terms.map((x:any)=>String(x||"").trim()).filter((x:string)=>x.length>=2).slice(0,12):[];if(!terms.length)terms=["tools","Milwaukee","DeWalt","Snap-on","generator","welder","toolbox","zero turn","pressure washer"];
const wanted=new Set((Array.isArray(b.sources)?b.sources:[]).map((x:any)=>String(x).toLowerCase()));const use=(n:string)=>!wanted.size||wanted.has(n.toLowerCase());let rows:any[]=[],status:any[]=[];
for(const term of terms.slice(0,5)){const q=encodeURIComponent(term);const jobs:any[]=[];if(use("Craigslist")){jobs.push({source:"Craigslist",url:`https://duluth.craigslist.org/search/sss?query=${q}&sort=date`,parse:craigslist});jobs.push({source:"Craigslist",url:`https://minneapolis.craigslist.org/search/sss?query=${q}&sort=date`,parse:craigslist})}if(use("HiBid")){jobs.push({source:"HiBid",url:`https://hibid.com/lots?q=${q}`,parse:hibid})}if(use("Facebook Marketplace")){jobs.push({source:"Facebook Marketplace",url:`https://www.facebook.com/marketplace/search/?query=${q}`,parse:facebook});jobs.push({source:"Facebook Marketplace",url:`https://m.facebook.com/marketplace/search/?query=${q}`,parse:facebook})}
const settled=await Promise.all(jobs.map(async j=>{try{const p=await get(j.url),found=j.parse(p.html,p.url,term);status.push({source:j.source,term,status:"PASS",matches:found.length});return found}catch(e){status.push({source:j.source,term,status:"BLOCKED_OR_UNAVAILABLE",matches:0,detail:e instanceof Error?e.message:String(e)});return[]} }));for(const x of settled)rows.push(...x)}
rows=uniq(rows).slice(0,80);const by:any={};for(const s of status){const k=s.source;if(!by[k])by[k]={attempts:0,passed:0,matches:0,failed:0};by[k].attempts++;if(s.status==="PASS")by[k].passed++;else by[k].failed++;by[k].matches+=Number(s.matches||0)}return json(r,200,{status:"PASS",sources_checked:status.length,terms_checked:terms.length,opportunities:rows,source_status:status,source_summary:by,automatic:true,scanned_at:new Date().toISOString()})}catch(e){return json(r,200,{status:"PARTIAL",sources_checked:0,opportunities:[],source_status:[],source_summary:{},automatic:true,warning:e instanceof Error?e.message:String(e)})}});
