import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// H38 Deals shared shell login recovery.
// Scope: auth/session bootstrap + entitlement chooser only.
// Penny, Resale and Couponing remain independent hosted products.
const html = String.raw`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b2438"><title>H38 Deals</title><style>
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f3f6f8;color:#102331}.wrap{max-width:560px;margin:auto;padding:calc(18px + env(safe-area-inset-top)) 16px calc(28px + env(safe-area-inset-bottom))}.hero{text-align:center;padding:20px 8px 18px}.logo{width:72px;height:72px;border-radius:22px;background:#0b2438;color:#fff;display:grid;place-items:center;margin:auto;font-size:27px;font-weight:900}.hero h1{margin:12px 0 4px;font-size:30px}.hero p{margin:0;color:#5a6b76}.card{background:white;border:1px solid #dbe3e8;border-radius:22px;padding:18px;margin:12px 0;box-shadow:0 7px 22px rgba(11,36,56,.06)}.card h2{margin:0 0 5px;font-size:22px}.card p{margin:0 0 14px;color:#586a75;line-height:1.35}.row{display:flex;gap:10px;align-items:center}.grow{flex:1}.pill{font-size:12px;padding:5px 8px;border-radius:999px;background:#e8eef2}.pill.on{background:#e3f6e8;color:#17622c}.pill.off{background:#fff0df;color:#8b4a00}button,a.btn{border:0;border-radius:14px;padding:13px 16px;font-weight:750;font-size:15px;text-decoration:none;text-align:center;background:#0b2438;color:#fff;display:inline-block}.secondary{background:#e8eef2!important;color:#102331!important}.auth{background:#fff;border:1px solid #dbe3e8;border-radius:18px;padding:14px;margin-top:8px}input{width:100%;padding:13px;border:1px solid #cbd5dc;border-radius:12px;margin:5px 0 9px;font-size:16px}.small{font-size:12px;color:#667782}.hidden{display:none!important}.status{min-height:18px;margin:8px 0;color:#5d6d77;font-size:13px}.status.error{color:#9c2525}.top{display:flex;justify-content:space-between;align-items:center}.top strong{font-size:14px}.unlock{opacity:.72}.foot{text-align:center;color:#788791;font-size:12px;margin-top:18px}
</style></head><body data-h38-auth="booting" data-h38-login-repair="v312"><main class="wrap"><div class="top"><strong>Highway 38 Solutions</strong><button id="signout" class="secondary hidden" type="button">Sign out</button></div><section class="hero"><div class="logo">H38</div><h1>H38 Deals</h1><p>Choose your shopping tool.</p></section><form id="loginForm" class="auth"><strong>Sign in</strong><p class="small">One account controls which products you can open.</p><input id="email" name="email" type="email" autocomplete="username" inputmode="email" placeholder="Email" required><input id="password" name="password" type="password" autocomplete="current-password" placeholder="Password" required><button id="signin" type="submit">Sign in</button><div id="authstatus" class="status" aria-live="polite"></div></form><section id="products" class="hidden">
<div id="product-penny" class="card" data-product="penny"><div class="row"><div class="grow"><h2>Penny Deals</h2><p>Penny items and deep-clearance retail deals.</p></div><span class="pill">Checking</span></div><a class="btn open" href="/functions/v1/h38-penny-web">Open Penny Deals</a><button class="unlock hidden" type="button">Unlock</button></div>
<div id="product-resale" class="card" data-product="resale"><div class="row"><div class="grow"><h2>Resale</h2><p>Marketplace, auctions and proven buy-to-resell opportunities.</p></div><span class="pill">Checking</span></div><a class="btn open" href="/functions/v1/h38-resale-web">Open Resale</a><button class="unlock hidden" type="button">Unlock</button></div>
<div id="product-coupon" class="card" data-product="coupon"><div class="row"><div class="grow"><h2>Couponing</h2><p>Shopping lists, coupon stacks, real savings and trip optimization.</p></div><span class="pill">Checking</span></div><a class="btn open" href="/functions/v1/h38-coupon-web">Open Couponing</a><button class="unlock hidden" type="button">Unlock</button></div>
</section><div class="foot">Web-backed products update without reinstalling the Android app.</div></main><script>
'use strict';
const URL='https://jqukmwtsgcsaruucnqja.supabase.co';
const KEY='sb_publishable_XrF41kGmTC2SmSTgPvo5OQ_vqcBd0N1';
const SDK_URLS=['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js','https://unpkg.com/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js'];
const $=id=>document.getElementById(id);
let sb=null,clientPromise=null,renderGeneration=0;
function setStatus(text,isError=false){const el=$('authstatus');el.textContent=text||'';el.classList.toggle('error',!!isError);}
function renderSignedOut(){document.body.dataset.h38Auth='signed-out';$('loginForm').classList.remove('hidden');$('products').classList.add('hidden');$('signout').classList.add('hidden');$('signin').disabled=false;}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');let done=false;const finish=(ok,err)=>{if(done)return;done=true;clearTimeout(timer);if(!ok)s.remove();ok?resolve():reject(err||new Error('SDK_LOAD_FAILED'));};s.src=src;s.async=true;s.onload=()=>finish(true);s.onerror=()=>finish(false,new Error('SDK_LOAD_FAILED'));const timer=setTimeout(()=>finish(false,new Error('SDK_LOAD_TIMEOUT')),12000);document.head.appendChild(s);});}
async function ensureClient(){if(sb)return sb;if(clientPromise)return clientPromise;clientPromise=(async()=>{if(!(window.supabase&&typeof window.supabase.createClient==='function')){let last=null;for(const src of SDK_URLS){try{await loadScript(src);if(window.supabase&&typeof window.supabase.createClient==='function')break;}catch(e){last=e;}}if(!(window.supabase&&typeof window.supabase.createClient==='function'))throw last||new Error('SIGNIN_COMPONENT_UNAVAILABLE');}sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return sb;})().catch(e=>{clientPromise=null;throw e;});return clientPromise;}
async function renderSignedIn(session){if(!session){renderSignedOut();return;}const generation=++renderGeneration;document.body.dataset.h38Auth='signed-in';$('loginForm').classList.add('hidden');$('products').classList.remove('hidden');$('signout').classList.remove('hidden');const client=await ensureClient();const {data,error}=await client.from('h38_product_entitlements').select('product_key,active,expires_at').eq('active',true);if(generation!==renderGeneration)return;const allowed=new Set((data||[]).filter(x=>!x.expires_at||new Date(x.expires_at)>new Date()).map(x=>x.product_key));document.querySelectorAll('[data-product]').forEach(card=>{const key=card.dataset.product,on=allowed.has(key),pill=card.querySelector('.pill');pill.textContent=on?'Included':'Locked';pill.className='pill '+(on?'on':'off');card.querySelector('.open').classList.toggle('hidden',!on);card.querySelector('.unlock').classList.toggle('hidden',on);card.classList.toggle('unlock',!on);card.dataset.entitled=on?'true':'false';});if(error){console.error(error);setStatus('Signed in, but product access could not be loaded.',true);}else setStatus('');}
$('signin').addEventListener('pointerdown',()=>{if(!$('signin').disabled)setStatus('Starting secure sign-in…');},{passive:true});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('email').value.trim(),password=$('password').value;if(!email||!password){setStatus('Enter email and password.',true);return;}$('signin').disabled=true;setStatus('Signing in…');try{const client=await ensureClient();const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;if(!data||!data.session)throw new Error('NO_SESSION_RETURNED');await renderSignedIn(data.session);}catch(e){renderSignedOut();const m=String(e&&e.message||e||'Sign-in failed');if(m==='Invalid login credentials')setStatus('Email or password is incorrect.',true);else if(m==='NO_SESSION_RETURNED')setStatus('Sign-in did not return a session. Try again.',true);else if(m.includes('SDK_LOAD')||m.includes('SIGNIN_COMPONENT'))setStatus('Secure sign-in could not start. Check the connection and tap Sign in to retry.',true);else setStatus('Sign-in failed: '+m,true);}finally{$('signin').disabled=false;}});
$('signout').addEventListener('click',async()=>{renderGeneration++;setStatus('');try{const client=await ensureClient();await client.auth.signOut();}catch(e){console.error(e);}finally{renderSignedOut();}});
document.querySelectorAll('.unlock').forEach(b=>b.addEventListener('click',()=>alert('This product is not enabled for this account.')));
(async()=>{try{setStatus('Starting secure sign-in…');const client=await ensureClient();const {data,error}=await client.auth.getSession();if(error)throw error;if(data&&data.session)await renderSignedIn(data.session);else{renderSignedOut();setStatus('');}}catch(e){renderSignedOut();setStatus('Secure sign-in could not start. Tap Sign in to retry.',true);}})();
</script></body></html>`;

Deno.serve(()=>new Response(html,{headers:{
  'content-type':'text/html; charset=utf-8',
  'cache-control':'no-store',
  'content-security-policy':"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; connect-src 'self' https://jqukmwtsgcsaruucnqja.supabase.co wss://jqukmwtsgcsaruucnqja.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; frame-ancestors 'self'"
}}));
