import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const BUILD="20260912-nl-bouncie-fleet-2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const CLIENT_ID=Deno.env.get("BOUNCIE_CLIENT_ID")||"";
const CLIENT_SECRET=Deno.env.get("BOUNCIE_CLIENT_SECRET")||"";
const TOKEN_KEY=Deno.env.get("BOUNCIE_TOKEN_ENCRYPTION_KEY")||"";
const STATE_SECRET=Deno.env.get("BOUNCIE_STATE_SECRET")||"";
const WEBHOOK_KEY=Deno.env.get("BOUNCIE_WEBHOOK_KEY")||"";
const AUTH_URL="https://auth.bouncie.com/dialog/authorize";
const TOKEN_URL="https://auth.bouncie.com/oauth/token";
const API="https://api.bouncie.dev/v1";
const DEFAULT_RETURN="https://highway38solutions.com/businesses/northern-lakes/business-office.html";
const ALLOWED_RETURN_ORIGINS=new Set(["https://highway38solutions.com","https://www.highway38solutions.com","https://rkrueth-maker.github.io"]);
type Json=Record<string,unknown>;
function clean(v:unknown,max=3000){return String(v??"").replace(/Bearer\s+[A-Za-z0-9._-]+/gi,"Bearer [REDACTED]").slice(0,max);}
function db(){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error("Supabase service configuration is unavailable.");return createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
function cors(req:Request){const o=clean(req.headers.get("origin"),300);return{"access-control-allow-origin":o||"*","access-control-allow-headers":"authorization, apikey, content-type, x-client-info","access-control-allow-methods":"GET, POST, OPTIONS","cache-control":"no-store","content-type":"application/json; charset=utf-8","vary":"Origin"};}
function json(req:Request,status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:cors(req)});}
function bearer(req:Request){const m=String(req.headers.get("authorization")||"").match(/^Bearer\s+(.+)$/i);return m?m[1].trim():"";}
function b64url(bytes:Uint8Array){let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,'');}
function fromB64url(v:string){let s=v.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
async function hmac(data:string){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(STATE_SECRET),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(data))));}
async function makeState(payload:Json){if(!STATE_SECRET)throw new Error("BOUNCIE_STATE_SECRET is not configured.");const body=b64url(new TextEncoder().encode(JSON.stringify(payload)));return`${body}.${await hmac(body)}`;}
async function readState(state:string){const [body,sig]=state.split(".");if(!body||!sig||sig!==await hmac(body))throw new Error("Invalid OAuth state.");const p=JSON.parse(new TextDecoder().decode(fromB64url(body))) as Json;if(Number(p.exp||0)<Date.now())throw new Error("OAuth state expired.");return p;}
async function keyMaterial(){if(!TOKEN_KEY)throw new Error("BOUNCIE_TOKEN_ENCRYPTION_KEY is not configured.");const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(TOKEN_KEY));return crypto.subtle.importKey("raw",hash,{name:"AES-GCM"},false,["encrypt","decrypt"]);}
async function encrypt(value:string){const nonce=crypto.getRandomValues(new Uint8Array(12)),key=await keyMaterial();const ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:nonce},key,new TextEncoder().encode(value)));return{cipher:b64url(ct),nonce:b64url(nonce)};}
async function decrypt(cipher:string,nonce:string){const key=await keyMaterial();const pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64url(nonce)},key,fromB64url(cipher));return new TextDecoder().decode(pt);}
function safeReturn(value:unknown){try{const u=new URL(clean(value,1000)||DEFAULT_RETURN);return ALLOWED_RETURN_ORIGINS.has(u.origin)?u.toString():DEFAULT_RETURN;}catch(_){return DEFAULT_RETURN;}}
async function signedUser(req:Request){const token=bearer(req);if(!token)throw new Error("Supabase Auth session is required.");const service=db();const {data,error}=await service.auth.getUser(token);if(error||!data.user)throw new Error("Supabase Auth session is invalid or expired.");return{service,user:data.user};}
async function member(service:ReturnType<typeof db>,userId:string,businessId:string,admin=false){const {data,error}=await service.from("business_memberships").select("role,status").eq("business_id",businessId).eq("auth_user_id",userId).eq("status","active").maybeSingle();if(error)throw error;if(!data)throw new Error("Active business membership is required.");const role=clean(data.role,60).toLowerCase();if(admin&&!["owner","administrator"].includes(role))throw new Error("Owner or Administrator access is required.");return role;}
async function proof(service:ReturnType<typeof db>,businessId:string,userId:string|null,action:string,details:Json){try{await service.from("business_proof_log").insert({business_id:businessId,actor_user_id:userId,action_type:action,entity_type:"Fleet",result:"PASS",details,external_action_occurred:false});}catch(_){} }
function configured(){const missing=[];if(!CLIENT_ID)missing.push("BOUNCIE_CLIENT_ID");if(!CLIENT_SECRET)missing.push("BOUNCIE_CLIENT_SECRET");if(!TOKEN_KEY)missing.push("BOUNCIE_TOKEN_ENCRYPTION_KEY");if(!STATE_SECRET)missing.push("BOUNCIE_STATE_SECRET");if(!WEBHOOK_KEY)missing.push("BOUNCIE_WEBHOOK_KEY");return missing;}
function redirectUri(req:Request){return`${new URL(req.url).origin}/nl-bouncie-fleet?action=oauth-callback`;}
async function tokenExchange(body:Json){const r=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const p=await r.json().catch(()=>({})) as Json;if(!r.ok)throw new Error(clean((p.errors||p.error_description||p.error)||`Bouncie token request failed (${r.status}).`,800));return p;}
async function bouncie(access:string,path:string){const r=await fetch(`${API}${path}`,{headers:{Authorization:access,"Content-Type":"application/json"},signal:AbortSignal.timeout(25000)});const raw=await r.text();let p:unknown={};try{p=raw?JSON.parse(raw):{};}catch(_){p={raw:raw.slice(0,1000)};}if(!r.ok)throw new Error(`Bouncie ${path} failed (${r.status}): ${clean((p as Json).errors||(p as Json).error||raw,800)}`);return p;}
function arr(v:unknown):Json[]{if(Array.isArray(v))return v.filter(x=>x&&typeof x==="object") as Json[];if(v&&typeof v==="object"){for(const k of ["data","vehicles","trips","items"]){const x=(v as Json)[k];if(Array.isArray(x))return x.filter(y=>y&&typeof y==="object") as Json[];}}return[];}
function field(o:Json,...keys:string[]){for(const k of keys){const parts=k.split(".");let v:unknown=o;for(const p of parts)v=v&&typeof v==="object"?(v as Json)[p]:undefined;if(v!==undefined&&v!==null&&v!=="")return v;}return undefined;}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null;}
function time(v:unknown){const d=new Date(String(v||""));return Number.isNaN(d.getTime())?null:d.toISOString();}
async function connection(service:ReturnType<typeof db>,businessId:string){const {data,error}=await service.from("fleet_provider_connections").select("*").eq("business_id",businessId).eq("provider","bouncie").maybeSingle();if(error)throw error;return data as Json|null;}
async function secret(service:ReturnType<typeof db>,connectionId:string){const {data,error}=await service.from("fleet_provider_secrets").select("*").eq("connection_id",connectionId).maybeSingle();if(error)throw error;if(!data)throw new Error("Bouncie token storage is missing.");return data as Json;}
async function saveTokens(service:ReturnType<typeof db>,connectionId:string,tokens:Json){const access=clean(tokens.access_token,8000),refresh=clean(tokens.refresh_token,8000);if(!access||!refresh)throw new Error("Bouncie did not return both access and refresh tokens.");const ea=await encrypt(access),er=await encrypt(refresh);const expires=new Date(Date.now()+Math.max(60,Number(tokens.expires_in||3600))*1000).toISOString();await service.from("fleet_provider_secrets").upsert({connection_id:connectionId,access_token_ciphertext:ea.cipher,refresh_token_ciphertext:er.cipher,token_nonce:JSON.stringify({access:ea.nonce,refresh:er.nonce}),token_expires_at:expires,updated_at:new Date().toISOString()});}
async function accessToken(service:ReturnType<typeof db>,conn:Json){const sec=await secret(service,clean(conn.id,100)),nonces=JSON.parse(clean(sec.token_nonce,500)||"{}") as Json;let access=await decrypt(clean(sec.access_token_ciphertext,12000),clean(nonces.access,200));const exp=new Date(clean(sec.token_expires_at,100)).getTime();if(exp>Date.now()+120000)return access;const refresh=await decrypt(clean(sec.refresh_token_ciphertext,12000),clean(nonces.refresh,200));const tokens=await tokenExchange({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:"refresh_token",refresh_token:refresh});if(!tokens.refresh_token)tokens.refresh_token=refresh;await saveTokens(service,clean(conn.id,100),tokens);access=clean(tokens.access_token,8000);return access;}
function vehicleRow(businessId:string,v:Json){const imei=clean(field(v,"imei","device.imei","deviceImei","device.id"),180);const device=imei||clean(field(v,"id","vehicleId","vin"),180);if(!device)return null;const loc=(field(v,"stats.location","location","gps")||{}) as Json;return{business_id:businessId,provider:"bouncie",provider_device_id:device,provider_imei:imei||null,nickname:clean(field(v,"nickname","name"),240)||null,vin:clean(field(v,"vin"),80)||null,year:num(field(v,"year")),make:clean(field(v,"make"),120)||null,model:clean(field(v,"model"),120)||null,active:true,connection_status:clean(field(v,"stats.deviceConnected","connectionStatus","status"),80)||"connected",last_known_at:time(field(v,"stats.lastUpdated","lastUpdated","timestamp","date"))||new Date().toISOString(),latitude:num(field(loc,"lat","latitude")),longitude:num(field(loc,"lon","lng","longitude")),speed_mph:num(field(v,"stats.speed","speed","stats.speedMph")),odometer_miles:num(field(v,"stats.odometer","odometer")),battery_status:clean(field(v,"stats.battery","battery","batteryStatus"),120)||null,mil_status:clean(field(v,"stats.mil","mil","milStatus"),120)||null,provider_payload:v,updated_at:new Date().toISOString()};}
function routePoints(t:Json){const raw=field(t,"gps","route","locations","geoJson.coordinates","geojson.coordinates");const list=Array.isArray(raw)?raw:[];const out:{lat:number;lon:number;time:string|null}[]=[];for(const p of list.slice(0,2000)){let lat:number|null=null,lon:number|null=null,tm:string|null=null;if(Array.isArray(p)){lon=num(p[0]);lat=num(p[1]);tm=time(p[2]);}else if(p&&typeof p==="object"){const j=p as Json;lat=num(field(j,"lat","latitude"));lon=num(field(j,"lon","lng","longitude"));tm=time(field(j,"time","timestamp","date"));}if(lat!==null&&lon!==null)out.push({lat,lon,time:tm});}if(out.length<=400)return out;const step=Math.ceil(out.length/400);return out.filter((_,i)=>i%step===0).slice(0,400);}
function hav(a:{lat:number;lon:number},b:{lat:number;lon:number}){const R=6371000,dlat=(b.lat-a.lat)*Math.PI/180,dlon=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dlat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function linkTrip(points:{lat:number;lon:number;time:string|null}[],zones:Json[]){let best:Json|null=null,bestSeconds=0;for(const z of zones){const center={lat:Number(z.latitude),lon:Number(z.longitude)},radius=Number(z.radius_meters||120);let seconds=0;for(let i=1;i<points.length;i++){if(hav(points[i],center)<=radius&&hav(points[i-1],center)<=radius&&points[i].time&&points[i-1].time){const d=(new Date(points[i].time!).getTime()-new Date(points[i-1].time!).getTime())/1000;if(d>0&&d<=300)seconds+=d;}}if(seconds>bestSeconds){best=z;bestSeconds=seconds;}}return best?{zone:best,seconds:Math.round(bestSeconds),confidence:bestSeconds>=120?.95:.75}:{zone:null,seconds:0,confidence:null};}
function tripId(t:Json,imei:string){return clean(field(t,"transactionId","transaction_id","tripId","id"),240)||`${imei}-${clean(field(t,"startTime","startedAt","start"),80)}-${clean(field(t,"endTime","endedAt","end"),80)}`;}
async function fetchTrips(access:string,imei:string){const end=new Date(),start=new Date(end.getTime()-7*86400000);const variants=[`/trips?imei=${encodeURIComponent(imei)}&starts_after=${encodeURIComponent(start.toISOString())}&ends_before=${encodeURIComponent(end.toISOString())}&gps_format=geojson`,`/trips?imei=${encodeURIComponent(imei)}&startsAfter=${encodeURIComponent(start.toISOString())}&endsBefore=${encodeURIComponent(end.toISOString())}&gpsFormat=geojson`];let last:Error|null=null;for(const path of variants){try{return arr(await bouncie(access,path));}catch(e){last=e as Error;}}throw last||new Error("Bouncie trip request failed.");}
async function sync(service:ReturnType<typeof db>,businessId:string,userId:string){const conn=await connection(service,businessId);if(!conn||clean(conn.status)!=="connected")throw new Error("Connect the Northern Lakes Bouncie account first.");const access=await accessToken(service,conn);const [userPayload,vehiclePayload]=await Promise.all([bouncie(access,"/user"),bouncie(access,"/vehicles")]);const user=(Array.isArray(userPayload)?userPayload[0]:userPayload) as Json;const vehicles=arr(vehiclePayload),mapped=vehicles.map(v=>vehicleRow(businessId,v)).filter(Boolean) as Json[];if(mapped.length){const {error}=await service.from("fleet_vehicles").upsert(mapped,{onConflict:"business_id,provider,provider_device_id"});if(error)throw error;}
const currentDevices=new Set(mapped.map(v=>clean(v.provider_device_id)));const {data:existing}=await service.from("fleet_vehicles").select("id,provider_device_id").eq("business_id",businessId).eq("provider","bouncie").eq("active",true);for(const old of existing||[]){if(!currentDevices.has(clean(old.provider_device_id)))await service.from("fleet_vehicles").update({active:false,connection_status:"removed",updated_at:new Date().toISOString()}).eq("id",old.id);}
const {data:zones}=await service.from("fleet_job_zones").select("*").eq("business_id",businessId).eq("active",true);const {data:dbVehicles}=await service.from("fleet_vehicles").select("id,provider_device_id,provider_imei").eq("business_id",businessId).eq("provider","bouncie").eq("active",true);let tripCount=0;
for(const v of(dbVehicles||[]).slice(0,25)){const imei=clean(v.provider_imei||v.provider_device_id);if(!imei)continue;let trips:Json[]=[];try{trips=await fetchTrips(access,imei);}catch(_){continue;}const rows=[];for(const t of trips.slice(0,300)){const points=routePoints(t),linked=linkTrip(points,zones||[]),start=time(field(t,"startTime","startedAt","start","started_at")),endAt=time(field(t,"endTime","endedAt","end","ended_at"));rows.push({business_id:businessId,vehicle_id:v.id,provider:"bouncie",provider_trip_id:tripId(t,imei),provider_device_id:imei,started_at:start,ended_at:endAt,distance_miles:num(field(t,"distance","distanceMiles","distance_miles")),duration_seconds:num(field(t,"duration","durationSeconds","duration_seconds")),start_latitude:points[0]?.lat??num(field(t,"startLocation.lat","start.latitude")),start_longitude:points[0]?.lon??num(field(t,"startLocation.lon","start.longitude")),end_latitude:points.at(-1)?.lat??num(field(t,"endLocation.lat","end.latitude")),end_longitude:points.at(-1)?.lon??num(field(t,"endLocation.lon","end.longitude")),route:points.map(p=>[p.lat,p.lon,p.time]),customer_id:linked.zone?clean(linked.zone.customer_id,180)||null:null,job_id:linked.zone?clean(linked.zone.job_id,180)||null:null,on_site_seconds:linked.seconds,linkage_confidence:linked.confidence,linkage_reason:linked.zone?`Route entered ${clean(linked.zone.label||linked.zone.address||"job zone",200)}`:null,provider_payload:t,updated_at:new Date().toISOString()});}
if(rows.length){const {error}=await service.from("fleet_trips").upsert(rows,{onConflict:"business_id,provider,provider_trip_id"});if(error)throw error;tripCount+=rows.length;}}
await service.from("fleet_provider_connections").update({provider_user_id:clean(field(user,"id","userId","email"),300)||null,last_sync_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",clean(conn.id,100));await proof(service,businessId,userId,"FLEET_BOUNCIE_SYNC",{vehicles:mapped.length,trips:tripCount,externalActionOccurred:false});return{vehicles:mapped.length,trips:tripCount};}
async function oauthStart(req:Request,input:Json){const missing=configured();if(missing.length)throw new Error(`Bouncie setup needs these server secrets: ${missing.join(", ")}.`);const {service,user}=await signedUser(req),businessId=clean(input.businessId,80);await member(service,user.id,businessId,true);const state=await makeState({businessId,userId:user.id,returnUrl:safeReturn(input.returnUrl),exp:Date.now()+10*60*1000,nonce:crypto.randomUUID()});const url=new URL(AUTH_URL);url.searchParams.set("client_id",CLIENT_ID);url.searchParams.set("response_type","code");url.searchParams.set("redirect_uri",redirectUri(req));url.searchParams.set("state",state);return{authUrl:url.toString()};}
async function oauthCallback(req:Request){const u=new URL(req.url),code=clean(u.searchParams.get("code"),4000),state=clean(u.searchParams.get("state"),8000);if(!code||!state)throw new Error("Bouncie OAuth callback is missing code or state.");const p=await readState(state),service=db(),businessId=clean(p.businessId,80),userId=clean(p.userId,80);await member(service,userId,businessId,true);const tokens=await tokenExchange({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:"authorization_code",code,redirect_uri:redirectUri(req)});const {data:conn,error}=await service.from("fleet_provider_connections").upsert({business_id:businessId,provider:"bouncie",status:"connected",connected_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"business_id,provider"}).select().single();if(error)throw error;await saveTokens(service,conn.id,tokens);await proof(service,businessId,userId,"FLEET_BOUNCIE_CONNECTED",{externalActionOccurred:false});const ret=new URL(safeReturn(p.returnUrl));ret.searchParams.set("bouncie","connected");return Response.redirect(ret.toString(),302);}
async function duplicate(service:ReturnType<typeof db>,raw:string,event:Json){const hash=b64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw))));const key=clean(field(event,"id","eventId","transactionId","transaction_id"),300)||hash;const {error}=await service.from("fleet_webhook_receipts").insert({provider:"bouncie",receipt_key:key});if(error&&String(error.code)==="23505")return true;if(error)throw error;await service.from("fleet_webhook_receipts").delete().lt("expires_at",new Date().toISOString());return false;}
async function webhook(req:Request){if(!WEBHOOK_KEY)throw new Error("BOUNCIE_WEBHOOK_KEY is not configured.");const supplied=clean(req.headers.get("x-bouncie-authorization")||req.headers.get("authorization"),1000);if(supplied!==WEBHOOK_KEY)throw new Error("Invalid Bouncie webhook authorization.");const raw=await req.text(),event=JSON.parse(raw) as Json,service=db();if(await duplicate(service,raw,event))return{duplicate:true};const imei=clean(field(event,"imei","device.imei","deviceImei"),180),providerUser=clean(field(event,"userId","user.id","user"),300);let businessId="",vehicle:Json|null=null;if(imei){const {data}=await service.from("fleet_vehicles").select("id,business_id,provider_device_id").or(`provider_imei.eq.${imei},provider_device_id.eq.${imei}`).eq("provider","bouncie").limit(1).maybeSingle();if(data){vehicle=data as Json;businessId=clean(data.business_id,80);}}if(!businessId&&providerUser){const {data}=await service.from("fleet_provider_connections").select("business_id").eq("provider","bouncie").eq("provider_user_id",providerUser).limit(1).maybeSingle();if(data)businessId=clean(data.business_id,80);}if(!businessId)throw new Error("Webhook could not be matched to an authorized fleet connection.");const type=clean(field(event,"eventType","type","event"),100).toLowerCase(),eventTime=time(field(event,"timestamp","date","eventTime","createdAt"))||new Date().toISOString(),loc=(field(event,"location","gps","data")||{}) as Json,lat=num(field(loc,"lat","latitude")),lon=num(field(loc,"lon","lng","longitude"));
if(imei&&!vehicle){const row=vehicleRow(businessId,event);if(row){const {data}=await service.from("fleet_vehicles").upsert(row,{onConflict:"business_id,provider,provider_device_id"}).select("id,business_id,provider_device_id").single();vehicle=data as Json;}}
if(vehicle&&(lat!==null||lon!==null||/tripdata|trip data/.test(type))){const update:Json={last_known_at:eventTime,updated_at:new Date().toISOString()};if(lat!==null)update.latitude=lat;if(lon!==null)update.longitude=lon;const speed=num(field(event,"speed","data.speed"));if(speed!==null)update.speed_mph=speed;await service.from("fleet_vehicles").update(update).eq("id",clean(vehicle.id,100));}
if(vehicle&&/disconnect/.test(type))await service.from("fleet_vehicles").update({connection_status:"disconnected",updated_at:new Date().toISOString()}).eq("id",clean(vehicle.id,100));if(vehicle&&/connect/.test(type)&&!/disconnect/.test(type))await service.from("fleet_vehicles").update({connection_status:"connected",updated_at:new Date().toISOString()}).eq("id",clean(vehicle.id,100));if(vehicle&&/vin/.test(type)){const vin=clean(field(event,"vin","data.vin"),80);if(vin)await service.from("fleet_vehicles").update({vin,updated_at:new Date().toISOString()}).eq("id",clean(vehicle.id,100));}if(vehicle&&/battery/.test(type))await service.from("fleet_vehicles").update({battery_status:clean(field(event,"battery","data.battery","value"),120)||"low",updated_at:new Date().toISOString()}).eq("id",clean(vehicle.id,100));if(vehicle&&/\bmil\b|check.?engine/.test(type))await service.from("fleet_vehicles").update({mil_status:clean(field(event,"mil","data.mil","value"),120)||"warning",updated_at:new Date().toISOString()}).eq("id",clean(vehicle.id,100));
const highVolume=/tripdata|trip data/.test(type);if(!highVolume){const receipt=clean(field(event,"id","eventId","transactionId","transaction_id"),300)||b64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw))));await service.from("fleet_events").upsert({business_id:businessId,vehicle_id:vehicle?clean(vehicle.id,100):null,provider:"bouncie",provider_event_key:receipt,event_type:type||"bouncie_event",event_time:eventTime,severity:/battery|mil|disconnect/.test(type)?"warning":"info",latitude:lat,longitude:lon,details:event},{onConflict:"business_id,provider,provider_event_key"});}
await service.from("fleet_provider_connections").update({last_webhook_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("business_id",businessId).eq("provider","bouncie");await service.from("fleet_events").delete().eq("business_id",businessId).lt("event_time",new Date(Date.now()-365*86400000).toISOString());if(/tripend|trip end|geozone|geo-zone/.test(type))await proof(service,businessId,null,"FLEET_BOUNCIE_EVENT",{eventType:type,vehicleId:vehicle?.id||null,eventTime,externalActionOccurred:false});return{businessId,eventType:type,vehicleId:vehicle?.id||null,highVolumeRetainedAsEvent:!highVolume};}
Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});
  const action=new URL(req.url).searchParams.get("action");
  try{
    if(req.method==="GET"&&action==="oauth-callback")return await oauthCallback(req);
    if(req.method!=="POST")return json(req,405,{status:"FAIL",message:"POST required.",build:BUILD});
    if(action==="webhook"||new URL(req.url).pathname.endsWith("/webhook")){const result=await webhook(req);return json(req,200,{status:"PASS",build:BUILD,...result,externalActionOccurred:false});}
    const input=await req.json() as Json,requested=clean(input.action||action,100);
    if(requested==="oauth-start"){const result=await oauthStart(req,input);return json(req,200,{status:"PASS",build:BUILD,...result,externalActionOccurred:false});}
    const {service,user}=await signedUser(req),businessId=clean(input.businessId,80);await member(service,user.id,businessId,true);
    if(requested==="sync"){const result=await sync(service,businessId,user.id);return json(req,200,{status:"PASS",build:BUILD,...result,externalActionOccurred:false});}
    if(requested==="status"){const conn=await connection(service,businessId);return json(req,200,{status:"PASS",build:BUILD,connection:conn?{status:conn.status,lastSyncAt:conn.last_sync_at,lastWebhookAt:conn.last_webhook_at}:null,missingSecrets:configured(),externalActionOccurred:false});}
    throw new Error("Unsupported fleet action.");
  }catch(error){return json(req,400,{status:"FAIL",build:BUILD,message:clean((error as Error)?.message||error,1200),externalActionOccurred:false});}
});
