(function(){
  'use strict';
  const C=window.H38_CATALOG;
  if(!C)return;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
  const byId=id=>C.products.find(p=>p.id===id);
  function contract(p){return `<div class="buying-contract" aria-label="Buying details for ${esc(p.name)}"><div><strong>You send</strong><span>${esc(p.inputs.slice(0,2).join(' · '))}</span></div><div><strong>You receive</strong><span>${esc(p.deliverables.slice(0,2).join(' · '))}</span></div><div><strong>You pay</strong><span>${money(p.price)} · ${esc(p.payment)}</span></div><div><strong>You wait</strong><span>${esc(p.turnaround)}</span></div><div><strong>Revisions</strong><span>${esc(p.revisions)}</span></div><div><strong>Upgrade</strong><span>${esc(p.upgrade)}</span></div></div>`;}
  function enhanceProducts(){
    C.products.forEach(p=>{
      const detail=document.getElementById(p.slug);
      if(detail&&!detail.querySelector('.buying-contract'))detail.querySelector('.detail-top')?.insertAdjacentHTML('afterend',contract(p));
      const sample=document.getElementById(`sample-${p.slug}`);
      if(sample&&!sample.querySelector('.sample-contract'))sample.querySelector('.sample-actions')?.insertAdjacentHTML('beforebegin',`<div class="sample-contract"><strong>Commercial match:</strong> ${money(p.price)} · ${esc(p.turnaround)} · ${esc(p.revisions)} · <a href="products.html#${esc(p.slug)}">full scope</a></div>`);
    });
    $$('.product-card').forEach(card=>{const id=card.querySelector('.meta span')?.textContent.trim(),p=byId(id);if(p&&!card.querySelector('.card-contract'))card.querySelector('.button-row')?.insertAdjacentHTML('beforebegin',`<div class="card-contract"><span><strong>Send:</strong> ${esc(p.inputs[0])}</span><span><strong>Receive:</strong> ${esc(p.deliverables[0])}</span><span><strong>Upgrade:</strong> ${esc(p.upgrade)}</span></div>`);});
  }
  function enhanceBundles(){
    $$('.bundle-card').forEach((card,i)=>{const b=C.bundles[i];if(!b||card.querySelector('.bundle-contract'))return;const products=b.products.map(byId).filter(Boolean),waits=products.map(p=>p.turnaround),revisions=products.map(p=>p.revisions);card.querySelector('.button-row')?.insertAdjacentHTML('beforebegin',`<div class="bundle-contract"><p><strong>You send:</strong> Required inputs for each included product, submitted together where practical.</p><p><strong>You receive:</strong> ${esc(products.map(p=>p.name).join(' + '))}${b.extras?.length?` plus ${esc(b.extras.join(', '))}`:''}.</p><p><strong>Timing:</strong> Confirmed before work begins; component timing ranges are ${esc([...new Set(waits)].join(' / '))}.</p><p><strong>Revisions:</strong> ${esc([...new Set(revisions)].join(' / '))}.</p><p><strong>Boundary:</strong> Bundling does not expand licensed-professional, safety, implementation, or external-action scope.</p></div>`);});
  }
  function decisionAid(){const host=$('[data-decision-aid]');if(!host)return;host.innerHTML=C.outcomes.map(o=>{const ps=o.products.map(byId).filter(Boolean);return `<article class="decision-path"><h3>${esc(o.label||o.name||o.value)}</h3><p>${esc(o.description||'Choose this path when this is the finished outcome you need.')}</p><ul>${ps.map(p=>`<li><a href="products.html#${esc(p.slug)}">${esc(p.name)}</a> — ${money(p.price)}</li>`).join('')}</ul><a class="btn btn-dark" href="start-request.html?outcome=${encodeURIComponent(o.value)}">Start this path</a></article>`;}).join('');}
  function intakeAssurance(){const form=$('#intake-form'),anchor=$('#intake-assurance-anchor');if(!form||!anchor||$('.intake-assurance'))return;anchor.innerHTML=`<details class="intake-assurance intake-assurance--compact"><summary>How scope, price, and next steps are confirmed</summary><div class="assurance-grid"><div><strong>1. Fit review</strong><span>Your request is matched to the smallest useful product or bundle.</span></div><div><strong>2. Scope confirmation</strong><span>Price, inputs, deliverables, turnaround, revisions, exclusions, and payment are confirmed before work begins.</span></div><div><strong>3. Personally reviewed contact</strong><span>No quote, payment request, final delivery, or external action is sent without the configured approval controls.</span></div></div></details>`;}
  function trustStrip(){const main=$('main');if(!main||$('.commercial-trust-strip'))return;main.insertAdjacentHTML('beforeend',`<section class="section commercial-trust-strip"><div class="container"><div class="section-head"><span class="badge">Buying confidence</span><h2>Clear terms before work begins.</h2></div><div class="trust-grid"><article><h3>Experience</h3><p>Practical manufacturing, machining, automation, shop-flow, quoting, project-planning, and small-business workflow experience.</p></article><article><h3>Privacy</h3><p>Only information needed for the agreed scope should be submitted. Sensitive access and unnecessary personal records require separate review.</p></article><article><h3>Payment</h3><p>Planning products are prepaid unless the controlled catalog states otherwise. Larger builds use the stated deposit and delivery rules.</p></article><article><h3>Revisions</h3><p>Each product includes only its bounded revision allowance. New goals, spaces, workflows, or deliverables require a new scope.</p></article></div></div></section>`);}
  function loadStyle(href){if(document.querySelector(`link[href^="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=`${href}?v=20260712-conversion`;document.head.appendChild(link);}
  function loadScript(src){return new Promise((resolve,reject)=>{if(document.querySelector(`script[src^="${src}"]`)){resolve();return;}const script=document.createElement('script');script.src=`${src}?v=20260712-conversion`;script.onload=resolve;script.onerror=reject;document.head.appendChild(script);});}
  async function ecosystem(){loadStyle('ecosystem.css');try{if(!window.H38_ECOSYSTEM)await loadScript('ecosystem-data.js');await loadScript('ecosystem.js');}catch(error){console.error('Ecosystem navigation enhancement failed',error);}}
  function run(){enhanceProducts();enhanceBundles();decisionAid();intakeAssurance();trustStrip();ecosystem();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,0),{once:true});else setTimeout(run,0);
})();