(function(){
  'use strict';
  const E=window.H38_ECOSYSTEM||{};
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const current=(document.body.dataset.page||'').toLowerCase();
  const publicRoutes=[['home','index.html','Home'],['services','services.html','Services'],['tools','free-tools.html','Free Tools'],['proof','proof.html','Proof'],['about','about.html','About'],['start','start-request.html','Start a Project']];
  const footerRoutes=[['products.html','Products & Pricing'],['sample-library-now.html','Samples'],['business-os.html','Business OS'],['business-concept-builder.html','Business Concept Builder'],['resources.html','Resources'],['customer-portal.html','Customer Access Status'],['portal.html','Portal Status']];
  const ownerPortal='https://script.google.com/macros/s/AKfycbzr0hoImRF4iQ1gR90Cr17juP8PODkEWRorXxW6qralEYTGLhOU33E1wYEPU_3duQKpQg/exec';
  function nav(){const host=document.querySelector('.site-nav');if(!host)return;host.className='site-nav eco-nav';host.innerHTML=`<div class="eco-nav__inner"><a class="eco-brand" href="index.html"><img src="brand/highway-38-mark.svg" alt=""><span>Highway 38 Solutions</span></a><button class="eco-menu" type="button" aria-expanded="false" aria-controls="primary-navigation">Menu</button><div class="eco-nav__links" id="primary-navigation">${publicRoutes.map(([id,href,label])=>`<a href="${href}" ${current===id?'aria-current="page"':''} class="${id==='start'?'eco-cta':''}">${label}</a>`).join('')}</div></div>`;const button=host.querySelector('.eco-menu'),links=host.querySelector('.eco-nav__links');button.addEventListener('click',()=>{const open=links.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));});}
  function footer(){const host=document.querySelector('.site-footer');if(!host)return;host.className='site-footer eco-footer';host.innerHTML=`<div class="eco-footer__grid"><div><a class="eco-brand" href="index.html"><img src="brand/highway-38-mark.svg" alt=""><span>Highway 38 Solutions</span></a><p>Big problems. Clear plans, decision packets, and working workflows.</p><p><strong>Every deliverable is personally reviewed before it is sent.</strong></p><p class="eco-download">Owner-reviewed work. No government affiliation. Planning does not replace licensed engineering, architecture, legal, tax, code, electrical, guarding, or safety validation.</p></div><div class="eco-footer__links">${publicRoutes.map(([,href,label])=>`<a href="${href}">${label}</a>`).join('')}${footerRoutes.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}<a href="${ownerPortal}" target="_blank" rel="noopener">Owner Login</a><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a></div></div>`;}
  function analytics(){document.addEventListener('click',event=>{const link=event.target.closest('a,button');if(!link)return;const name=link.dataset.event||link.textContent.trim().slice(0,80);window.h38AnalyticsQueue=window.h38AnalyticsQueue||[];window.h38AnalyticsQueue.push({event:'interaction',name,page:current,timestamp:new Date().toISOString()});});}
  function renderOfferData(){const addons=document.querySelector('[data-ecosystem-addons]');if(addons)addons.innerHTML=(E.addOns||[]).map(x=>`<article class="eco-card"><div class="eco-meta"><span class="eco-chip">${esc(x.id)}</span><span class="eco-chip eco-chip--warn">Owner review</span></div><h3>${esc(x.name)}</h3><div class="eco-price">${x.price?'$'+Number(x.price).toLocaleString():esc(x.priceRule)}</div><p>${esc(x.deliverable)}</p><p><b>Timing:</b> ${esc(x.turnaroundEffect)}</p><p><b>Revision:</b> ${esc(x.revisionRule)}</p></article>`).join('');const contracts=document.querySelector('[data-ecosystem-contracts]');if(contracts)contracts.innerHTML=(E.contracts||[]).map(x=>`<article class="eco-card"><div class="eco-meta"><span class="eco-chip">${esc(x.id)}</span><span class="eco-chip eco-chip--warn">Owner review</span></div><h3>${esc(x.name)}</h3><div class="eco-price">$${Number(x.price).toLocaleString()}/${esc(x.period)}</div><p><b>Included:</b> ${esc(x.included)}</p><p><b>Response:</b> ${esc(x.response)}</p><p><b>Exclusions:</b> ${esc(x.exclusions)}</p><p><b>Cancellation:</b> ${esc(x.cancellation)}</p></article>`).join('');const tiers=document.querySelector('[data-os-tiers]');if(tiers)tiers.innerHTML=(E.osTiers||[]).map(x=>`<article class="eco-card"><div class="eco-meta"><span class="eco-chip">${esc(x.id)}</span><span class="eco-chip eco-chip--warn">Owner review</span></div><h3>${esc(x.name)}</h3><div class="eco-price">$${Number(x.setup).toLocaleString()} setup</div><ul class="eco-list">${x.includes.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></article>`).join('');const providers=document.querySelector('[data-provider-status]');if(providers)providers.innerHTML=(E.providers||[]).map(x=>`<tr><td>${esc(x.feature)}</td><td>${esc(x.mode)}</td><td><span class="eco-chip eco-chip--warn">${esc(x.status)}</span></td><td>${esc(x.blocker)}</td></tr>`).join('');}
  function run(){nav();footer();analytics();renderOfferData();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();