(function(){
  'use strict';
  window.H38_PUBLIC_PROOF = Object.freeze({
    schemaVersion:2,
    release:'proof-evidence-system-2026-07-12-drive-pass-1',
    publicationPolicy:'Only privacy-approved summaries and reconstructions are included. Raw messages, attachments, private paths, addresses, people, customers, vendors, employees, employers, programs, drawings, pricing, production data, screens, plant layouts, photographs, and videos are excluded.',
    items:[
      {
        id:'CASE-MFG-001',title:'Blanking-feed automation planning',classification:'Verified historical work',domain:'Manufacturing and automation',
        summary:'Verified historical planning work for an automated strip-handling and blanking-feed concept, presented without employer, vendor, part, plant, pricing, production, or proprietary details.',
        problem:'Manual strip handling and press feeding required a repeatable sequence with clear setup, sensing, material-flow, exception, and review gates.',
        role:'Participated in project planning and evaluation, including proposal review, operating-sequence definition, integration questions, and facility/integrator evaluation.',
        inputs:['material stack and strip flow','feed and index settings','press-ready states','sensor and conveyor conditions','operator setup'],
        constraints:['existing press and tooling','proprietary process','guarding and safety review','tooling risks','no public production values'],
        workPerformed:['reviewed proposal','connected setup and sequence requirements','evaluated sensing and material flow','identified installation and review gates'],
        decisions:['use a staged feed sequence','require ready-state checks before automatic cycle','retain safety and tooling risks as review items'],
        implementation:'The record reached formal proposal, committee evaluation, concept documentation, and detailed order-of-operations work. Final commissioning is not claimed.',
        outcome:'The planning and evaluation record is corroborated. Quantified labor, capacity, efficiency, safety, and financial outcomes remain held.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:3,approvedAssets:[],relatedFreeTool:'H38-TOOL-005',relatedPaidService:'H38-P011',relatedProducts:['H38-P010','H38-P011'],
        boundary:'No proprietary sequence, drawing, program, production value, identity, raw photo, or safety certification is published.'
      },
      {
        id:'CASE-MFG-002',title:'Robot-tended lathe workflow planning',classification:'Verified historical work',domain:'Manufacturing and automation',
        summary:'Verified historical planning work evaluating a robot-tended turning-center workflow, including part presentation, machine signals, probing, training, runoff, and implementation constraints.',
        problem:'An uneven machining workload created a need to evaluate machine tending without losing control of part handling, quality, recovery, and operator responsibilities.',
        role:'Served as an owner-side planning contact and evaluator for the detailed proposal and related probing, training, workflow, and implementation questions.',
        inputs:['part presentation','gripper and chuck interface','machine signals','queues','probing','runoff criteria','training'],
        constraints:['existing turning center','multiple part families','quality verification','operator recovery','private machine and plant details'],
        workPerformed:['evaluated proposal','reviewed sequence and interface assumptions','connected probing and quality needs','considered runoff, training, utilities, rigging, and part-family fit'],
        decisions:['treat presentation and signal verification as primary gates','include probing and exception handling','separate planning evidence from production claims'],
        implementation:'The record includes a dated proposal, related project grouping, machine-tending media, and probing quotation. Sole design ownership and final commissioning are not claimed.',
        outcome:'The planning role and technical evaluation are corroborated. Exact production rate, savings, implementation responsibility, and realized output remain held.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:3,approvedAssets:[],relatedFreeTool:'H38-TOOL-008',relatedPaidService:'H38-P015',relatedProducts:['H38-P010','H38-P015'],
        boundary:'No machine serial, part identity, program, screen, video, cycle data, vendor control, price, or plant image is published.'
      },
      {
        id:'CASE-MFG-004',title:'CNC programming and CAD/CAM standardization',classification:'Verified historical work',domain:'Machining and digital manufacturing',
        summary:'Historical records document responsibility for CNC programming support, FeatureCAM tool libraries and posts, programming consistency, troubleshooting, training, and fixture/process support.',
        problem:'Programming, tooling, posts, standards, troubleshooting, and knowledge transfer needed coordinated ownership to keep machining work repeatable.',
        role:'Supported and maintained programming workflows, tool libraries, posts, process consistency, junior programmers, machine troubleshooting, quality, fixtures, and tooling research.',
        inputs:['job requirements','programs','tooling','posts','tool libraries','quality feedback','fixture needs'],
        constraints:['machine capability','tool availability','repeatability','quality','training','private programs and parts'],
        workPerformed:['programmed and updated jobs','maintained tool libraries and posts','supported programmers','standardized methods','troubleshot process and quality problems','helped design fixtures'],
        decisions:['use non-quantified public wording','keep programs, tooling inventories, parts, and internal operations private'],
        implementation:'Responsibility records corroborate an established operating role rather than a one-time demonstration.',
        outcome:'The role and work scope are verified. Exact program count, output, scrap, savings, and customer results remain unapproved until independently counted or measured.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:2,approvedAssets:[],relatedFreeTool:'H38-TOOL-001',relatedPaidService:'H38-P010',relatedProducts:['H38-P010','H38-P011'],
        boundary:'No proprietary program, post, inventory, part number, identity, output value, or quantified career count is published.'
      },
      {
        id:'CASE-MFG-005',title:'CAD/CAM workflow modernization',classification:'Historical estimate',domain:'Machining and digital systems',
        summary:'A public-safe historical planning summary covering CAD/CAM utilization, shared licensing, advanced macro training, reusable automation, file handling, and operator adoption without proprietary files or exact savings.',
        problem:'Software capability was not being used consistently, while licensing, repetitive work, training, and errors created cost and throughput concerns.',
        role:'Evaluated workflow gaps and proposed training, shared access, macro development, process review, and more consistent CAD/CAM use.',
        inputs:['software utilization','license access','drawing and programming time','macro opportunities','training needs','error risk'],
        constraints:['proprietary files','license records','operator adoption','exact software chronology','unverified savings'],
        workPerformed:['documented current-state issues','outlined shared-access and training options','identified macro opportunities','estimated cost-of-delay scenarios'],
        decisions:['present savings as historical estimates','hold exact software-version claims','keep macros, posts, licenses, files, and identities private'],
        implementation:'The accessible record supports planning and recommendation work, not a fully verified migration outcome.',
        outcome:'The analysis is supported as a historical estimate. Exact version chronology, output, labor savings, and avoided-error values remain held.',
        evidenceStatus:'SOURCE_LOCATED',privacyStatus:'PUBLIC_SAFE',sourceCount:1,approvedAssets:[],relatedFreeTool:'H38-TOOL-001',relatedPaidService:'H38-P010',relatedProducts:['H38-P007','H38-P008','H38-P010'],
        boundary:'No proprietary file, license, macro, post, price, identity, or quantified result is published.'
      },
      {
        id:'CASE-MFG-006',title:'Manufacturing modernization planning',classification:'Verified historical work',domain:'Manufacturing systems',
        summary:'Historical planning records show experience evaluating modernization across machining, automation, vision, CAD/CAM, monitoring, material flow, storage, and logistics.',
        problem:'Multiple production, handling, quality, information, storage, and staffing constraints needed to be prioritized as an integrated modernization portfolio.',
        role:'Researched, documented, compared, and helped sequence modernization opportunities while continuing machining and automation responsibilities.',
        inputs:['equipment proposals','workflow constraints','quality issues','labor and capacity estimates','training','material flow','storage and logistics'],
        constraints:['capital priorities','training','plant disruption','private production data','confidentiality','estimate uncertainty'],
        workPerformed:['assembled a multi-project opportunity portfolio','recorded status and next steps','compared cost and benefit assumptions','connected automation, machining, vision, storage, and logistics'],
        decisions:['stage projects by readiness and learning value','separate proven work from research concepts','retain exact economics as private estimates'],
        implementation:'The record shows repeated planning and evaluation across multiple initiatives; each final implementation remains subject to its own evidence chain.',
        outcome:'The breadth of modernization planning is corroborated. Exact project ownership and quantified portfolio savings remain restricted or held.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:3,approvedAssets:[],relatedFreeTool:'H38-TOOL-002',relatedPaidService:'H38-P010',relatedProducts:['H38-P010','H38-P011','H38-P015'],
        boundary:'No customer, employee, drawing, price, program, production value, vendor identity, employer identity, or plant detail is published.'
      },
      {
        id:'CASE-MFG-007',title:'Vision, storage, and workflow planning',classification:'Historical estimate',domain:'Automation and shop flow',
        summary:'A public-safe historical planning summary connecting vision inspection, bin-picking research, machine monitoring, material storage, staging, vertical storage, access, and workflow improvements.',
        problem:'Inspection, part orientation, machine utilization, material movement, staging, and storage created connected workflow constraints.',
        role:'Researched and documented vision, bin-picking, monitoring, storage, racking, and material-flow options as part of a broader modernization portfolio.',
        inputs:['inspection needs','part orientation','camera capability','machine utilization','material movement','storage density','access'],
        constraints:['private parts and criteria','plant layout','vendor equipment','safety','unverified financial estimates'],
        workPerformed:['compared vision and bin-picking approaches','identified monitoring and inspection uses','evaluated storage and material-flow concepts','documented implementation and training questions'],
        decisions:['treat camera and storage options as staged evaluations','avoid publishing inspection criteria or layouts','retain projected savings as estimates'],
        implementation:'Accessible evidence supports research and planning. Individual systems and final measured outcomes are not collectively claimed as complete.',
        outcome:'The planning work is supported as a historical estimate; exact performance, labor savings, storage gains, and installation responsibility remain held.',
        evidenceStatus:'SOURCE_LOCATED',privacyStatus:'PUBLIC_SAFE',sourceCount:1,approvedAssets:[],relatedFreeTool:'H38-TOOL-007',relatedPaidService:'H38-P004',relatedProducts:['H38-P004','H38-P010','H38-P014'],
        boundary:'No proprietary image, inspection criterion, plant layout, part, vendor, production value, safety certification, or raw photo is published.'
      },
      {
        id:'CASE-RES-003',title:'Kitchen planning and sequence',classification:'Anonymized reconstruction',domain:'Residential planning',
        summary:'A public-safe reconstruction informed by a historical planning packet containing a floor plan, elevations, material selections, and three-dimensional layout views.',
        problem:'Cabinet, appliance, circulation, work-zone, measurement, material, and sequencing decisions needed to be resolved before purchase or installation.',
        role:'The historical artifact confirms planning activity; exact authorship, customer relationship, and completed installation are not claimed.',
        inputs:['room dimensions','fixed openings','appliance zones','cabinet sizes','circulation','material choices'],
        constraints:['field verification','private design identifiers','pricing and stock numbers','code and trade work','unknown installation outcome'],
        workPerformed:['organized floor-plan and elevation inputs','compared cabinet and material selections','structured decisions before purchase','identified verification boundaries'],
        decisions:['remove all source identifiers and price details','present an anonymized planning reconstruction','avoid permit or construction-authority claims'],
        implementation:'The public case study reconstructs the planning method rather than publishing the private source packet.',
        outcome:'The planning artifact is verified. Authorship, purchase, installation, property, customer, budget, and finished-result claims remain held.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:1,approvedAssets:[],relatedFreeTool:'H38-DL-002',relatedPaidService:'H38-P003',relatedProducts:['H38-P002','H38-P003'],
        boundary:'No vendor, store, design number, item number, price, address, customer, property, source rendering, or field-verified dimension is published.'
      },
      {
        id:'CASE-RES-004',title:'Garage flow and zone planning',classification:'Demonstration sample',domain:'Residential and shop planning',
        summary:'A 28-by-40-foot demonstration showing protected vehicle lanes, workbench and tool zones, fixed-obstacle checks, missing measurements, and phased setup actions.',
        problem:'A mixed-use garage needed clear vehicle, work, storage, utility, access, and future-project zones.',
        role:'Created a public demonstration from purpose-built planning inputs rather than customer evidence.',
        inputs:['overall dimensions','door positions','vehicle lanes','workbench','tool storage','utilities','future equipment'],
        constraints:['unverified field dimensions','code and structural requirements','clearances','budget and phasing'],
        workPerformed:['organized zones','protected movement paths','identified missing measurements','sequenced setup phases'],
        decisions:['keep the example synthetic','separate planning from engineering and permit work'],
        implementation:'Purpose-built demonstration only.',
        outcome:'A reusable planning example and customer-intake structure, not a verified construction outcome.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:1,approvedAssets:[],relatedFreeTool:'H38-TOOL-007',relatedPaidService:'H38-P004',relatedProducts:['H38-P002','H38-P003','H38-P004'],
        boundary:'Not customer work, a permit drawing, engineering, code verification, or field-verified construction plan.'
      },
      {
        id:'CASE-BIZ-001',title:'Small-business lead-to-job control',classification:'Demonstration sample',domain:'Business systems',
        summary:'A seven-status owner-controlled workflow connecting intake, missing information, quote review, scheduling, completion, and follow-up without automatic customer sends.',
        problem:'Work can become fragmented between inquiries, missing information, estimates, approvals, scheduling, delivery, and follow-up.',
        role:'Designed a synthetic public workflow example using no real customer or communication data.',
        inputs:['lead','scope','missing information','quote','approval','schedule','completion','follow-up'],
        constraints:['owner approval','selected-record execution','no automatic customer action','privacy'],
        workPerformed:['defined statuses','connected records','added approval and follow-up gates'],
        decisions:['use synthetic records only','keep customer actions owner-controlled'],
        implementation:'Purpose-built demonstration inside the operating system.',
        outcome:'A reusable workflow model rather than a customer outcome claim.',
        evidenceStatus:'CORROBORATED',privacyStatus:'PUBLIC_SAFE',sourceCount:1,approvedAssets:[],relatedFreeTool:'H38-DL-002',relatedPaidService:'H38-P007',relatedProducts:['H38-P005','H38-P007','H38-P008'],
        boundary:'Synthetic records only; no real customer, message, address, financial, or private business data.'
      }
    ]
  });
})();
