(function(){
  'use strict';
  const byId=id=>document.getElementById(id);
  const all=(selector,root=document)=>Array.from(root.querySelectorAll(selector));
  const form=byId('intake-form');
  if(!form)return;
  const steps=all('[data-request-step]');
  const stepButtons=all('[data-step-indicator]');
  const outcome=byId('outcome');
  const firstContinue=steps.find(step=>Number(step.dataset.requestStep)===1)?.querySelector('[data-request-next]');
  const DRAFT_KEY='public-request-v2';
  let current=1;

  function notice(message,kind='hold'){const node=byId('request-flow-notice');if(!node)return;node.textContent=message||'';node.hidden=!message;node.className='notice '+kind;if(message)node.focus();}
  function updateFirstContinue(){if(!firstContinue)return;const ready=Boolean(outcome&&outcome.value);firstContinue.disabled=!ready;firstContinue.setAttribute('aria-disabled',String(!ready));}
  function showStep(number){current=Math.max(1,Math.min(3,Number(number)||1));steps.forEach(step=>{step.hidden=Number(step.dataset.requestStep)!==current;});stepButtons.forEach(button=>{const n=Number(button.dataset.stepIndicator);button.classList.toggle('is-active',n===current);button.setAttribute('aria-current',n===current?'step':'false');});notice('');if(current===3)updateReview();const heading=steps.find(step=>Number(step.dataset.requestStep)===current)?.querySelector('h2');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}history.replaceState(null,'',location.pathname+location.search+'#step-'+current);window.scrollTo({top:Math.max(0,form.getBoundingClientRect().top+window.scrollY-100),behavior:'smooth'});}
  function selectChoice(value){if(!outcome)return;outcome.value=value;outcome.dispatchEvent(new Event('change',{bubbles:true}));all('[data-outcome-choice]').forEach(card=>{const selected=card.dataset.outcomeChoice===value;card.classList.toggle('is-selected',selected);const input=card.querySelector('input');if(input)input.checked=selected;card.setAttribute('aria-checked',String(selected));});updateFirstContinue();}
  function validateStep(number){if(number===1){if(!outcome||!outcome.value){notice('Choose the result that best matches what you need.');return false;}return true;}if(number===2){const required=[byId('problem'),byId('desired')];const missing=required.find(node=>!String(node&&node.value||'').trim());if(missing){notice('Describe the current problem and the finished result you want.');missing.focus();return false;}return true;}const required=[byId('name'),byId('email')];const missing=required.find(node=>!node||!node.checkValidity());if(missing){notice('Enter your name and a valid email address so Highway 38 can review the request.');missing.reportValidity();return false;}return true;}
  function selectedText(id){const node=byId(id);return node&&node.selectedOptions&&node.selectedOptions[0]?node.selectedOptions[0].textContent:'';}
  function value(id){return String(byId(id)?.value||'').trim();}
  function escapeHtml(text){return String(text).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
  function updateReview(){const host=byId('request-review');if(!host)return;const product=selectedText('product')||'Highway 38 will recommend the smallest useful service';const bundle=byId('bundle')&&byId('bundle').value?selectedText('bundle'):'No bundle selected';const system=byId('business-system-interest')&&byId('business-system-interest').value?selectedText('business-system-interest'):'No larger system selected';const files=value('files')||'No files or links listed yet; Highway 38 will identify anything needed during review.';const summary=[value('problem'),value('desired')].filter(Boolean).join('\n\n');host.innerHTML='<dl><dt>Selected outcome</dt><dd>'+escapeHtml(selectedText('outcome'))+'</dd><dt>Customer summary</dt><dd>'+escapeHtml(summary||'Not entered')+'</dd><dt>Files expected</dt><dd>'+escapeHtml(files)+'</dd><dt>Contact information</dt><dd>'+escapeHtml([value('name'),value('email'),value('phone'),selectedText('contact')].filter(Boolean).join(' · ')||'Not entered')+'</dd><dt>Likely service</dt><dd>'+escapeHtml(product)+'</dd><dt>Bundle</dt><dd>'+escapeHtml(bundle)+'</dd><dt>Business system</dt><dd>'+escapeHtml(system)+'</dd><dt>What happens next</dt><dd>Submit Request creates a secure request record. No charge, quote, order, message, or work begins automatically.</dd></dl>';}
  function formPayload(){const product=value('product'),bundle=value('bundle');return {idempotencyKey:getIdempotencyKey(),source:'website-direct-intake',website:'',name:value('name'),email:value('email'),phone:value('phone'),preferredContact:selectedText('contact'),desiredOutcome:selectedText('outcome'),catalogId:(product||bundle||'').toUpperCase(),problem:value('problem'),finishedResult:value('desired'),filesOrLinks:value('files'),details:[value('details'),value('plan-details'),value('implementation-details'),value('manufacturing-details')].filter(Boolean).join('\n\n'),budget:selectedText('budget'),timing:selectedText('timing')};}
  function getIdempotencyKey(){let key=sessionStorage.getItem('h38RequestIdempotency');if(!key){key='WEB-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);sessionStorage.setItem('h38RequestIdempotency',key);}return key;}
  function endpoint(){return String(form.dataset.intakeEndpoint||window.H38_PUBLIC_INTAKE_ENDPOINT||'').trim();}
  function submitDirect(){return new Promise((resolve,reject)=>{const url=endpoint();if(!url){reject(new Error('Secure intake endpoint is not configured.'));return;}const nonce='INTAKE-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9);const frame=document.createElement('iframe');frame.name='h38-intake-'+nonce;frame.hidden=true;frame.setAttribute('title','Secure request submission');const post=document.createElement('form');post.method='post';post.action=url;post.target=frame.name;post.hidden=true;const payload=document.createElement('input');payload.name='payload';payload.value=JSON.stringify(formPayload());const nonceInput=document.createElement('input');nonceInput.name='nonce';nonceInput.value=nonce;post.append(payload,nonceInput);document.body.append(frame,post);let finished=false;const cleanup=()=>{window.removeEventListener('message',receive);clearTimeout(timer);setTimeout(()=>{frame.remove();post.remove();},0);};const receive=event=>{const message=event.data;if(!message||message.type!=='h38-public-intake'||message.nonce!==nonce)return;finished=true;cleanup();const data=message.payload||{};if(data.ok)resolve(data);else reject(new Error(data.message||'Secure intake placed the request on hold.'));};window.addEventListener('message',receive);const timer=setTimeout(()=>{if(finished)return;cleanup();reject(new Error('Secure intake did not confirm the request.'));},45000);post.submit();});}
  function emailFallback(){const emailLink=byId('email-summary');const href=emailLink&&emailLink.getAttribute('href');if(href&&/^mailto:/i.test(href)){emailLink.hidden=false;emailLink.focus();notice('Secure submission is temporarily unavailable. Use the prepared email fallback; your progress remains saved.','hold');return;}notice('The request could not be submitted. Your progress remains saved on this device.','bad');}
  function showConfirmation(data){const requestId=data.requestId||'Pending confirmation';form.innerHTML='<section class="h38-state" data-h38-state="success" role="status"><div class="h38-state__icon" aria-hidden="true">✓</div><p class="eyebrow">Request received</p><h2>'+escapeHtml(requestId)+'</h2><p>We received your request. No charge or work has been created.</p><p><strong>Next step:</strong> Highway 38 will review the information and respond with questions or a proposed scope.</p><p><a class="btn btn-primary" href="index.html">Return to Highway 38</a></p></section>';if(window.H38Platform)H38Platform.clearDraft(DRAFT_KEY);sessionStorage.removeItem('h38RequestIdempotency');}
  function draftValues(){return Object.fromEntries(new FormData(form).entries());}
  function saveDraft(){if(window.H38Platform)H38Platform.saveDraft(DRAFT_KEY,{step:current,fields:draftValues()});}
  function restoreDraft(){if(!window.H38Platform)return;const draft=H38Platform.loadDraft(DRAFT_KEY);if(!draft||!draft.fields)return;Object.entries(draft.fields).forEach(([name,val])=>{const node=form.elements.namedItem(name);if(node&&typeof node.value!=='undefined')node.value=val;});if(outcome&&outcome.value)selectChoice(outcome.value);current=Number(draft.step)||1;notice('Your saved request progress was restored.','ok');}

  all('[data-outcome-choice]').forEach(card=>{card.addEventListener('click',()=>selectChoice(card.dataset.outcomeChoice));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectChoice(card.dataset.outcomeChoice);}});});
  all('[data-request-next]').forEach(button=>button.addEventListener('click',()=>{if(validateStep(current))showStep(current+1);}));all('[data-request-back]').forEach(button=>button.addEventListener('click',()=>showStep(current-1)));stepButtons.forEach(button=>button.addEventListener('click',()=>{const target=Number(button.dataset.stepIndicator);if(target<current||target===current||validateStep(current))showStep(target);}));
  form.addEventListener('input',()=>{saveDraft();if(current===3)updateReview();});form.addEventListener('change',()=>{saveDraft();updateFirstContinue();if(current===3)updateReview();});
  form.addEventListener('submit',async event=>{event.preventDefault();if(current!==3){if(validateStep(current))showStep(current+1);return;}if(!validateStep(3))return;updateReview();const submit=byId('request-submit');if(submit){submit.disabled=true;submit.setAttribute('aria-busy','true');submit.textContent='Submitting securely…';}notice('Creating a secure request record…','hold');try{const data=await submitDirect();showConfirmation(data);}catch(error){console.error(error);if(submit){submit.disabled=false;submit.removeAttribute('aria-busy');submit.textContent='Submit Request';}emailFallback();}},true);
  if(window.H38Platform)H38Platform.markDirty(form);restoreDraft();const requested=location.hash.match(/step-(\d)/);showStep(requested?Number(requested[1]):current);if(outcome&&outcome.value)selectChoice(outcome.value);else updateFirstContinue();
})();