# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d9b866dd5712dcbccd9b939ef21ece73"
application_url = "https://fictional-space-potato-9669wpq67p49f7jv5-5050.app.github.dev"
embedded = false
name = "Highway 38 Supply Co. App"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_products,write_products,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://fictional-space-potato-9669wpq67p49f7jv5-5050.app.github.dev/callback" ]
