import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

type Any=Record<string,any>;
const BASE=Deno.env.get('SUPABASE_URL')||'';
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const BUCKET='h38-penny-images';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-h38-nightly-key,x-h38-force','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'};
const txt=(v:any)=>String(v??'').trim();
const digits=(v:any)=>txt(v).replace(/\D/g,'');
const json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const admin=()=>createClient(BASE,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
function list(d:any){if(Array.isArray(d))return d;if(Array.isArray(d?.leads))return d.leads;if(Array.isArray(d?.results))return d.results;if(Array.isArray(d?.items))return d.items;return[]}
function retailerKey(v:any){const s=txt(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(s.includes('home depot'))return'home depot';if(s.includes('family dollar'))return'family dollar';if(s.includes('dollar general'))return'dollar general';if(s.includes('dollar tree'))return'dollar tree';return s||'other'}
function junk(v:any){const a=txt(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();return !a||a.length<3||/add the first photo|inventory checker/.test(a)||['penny','penny item','item','product','unknown','search','photo recovery','dollar general'].includes(a)}
function canonical(r:Any){const rr=retailerKey(r.retailer||r.store_name||r.source_name),upc=digits(r.upc||r.gtin||r.barcode).replace(/^0+/,''),sku=digits(r.sku||r.store_sku||r.internet_number).replace(/^0+/,''),title=txt(r.source_identity_title||r.canonical_title||r.title||r.product_name||r.item_name).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().slice(0,180);if(rr==='home depot'&&sku)return`${rr}|s:${sku}`;if(upc)return`${rr}|u:${upc}`;if(sku)return`${rr}|s:${sku}`;return title?`${rr}|t:${title}`:''}
function rawImage(r:Any){const u=txt(r.image_url||r.image||r.thumbnail_url||r.product_image_url||r.primary_image_url||r.source_image_url||r.photo_url);return /^https:\/\//i.test(u)&&!/(placeholder|blank|spacer|logo|favicon|sprite|pixel|loading|no-image)/i.test(u)?u:''}
function parseDate(v:any){const s=txt(v);if(!s)return null;const low=s.toLowerCase();if(low==='today'){const d=new Date();d.setHours(12,0,0,0);return d.toISOString()}if(low==='yesterday'){const d=new Date();d.setDate(d.getDate()-1);d.setHours(12,0,0,0);return d.toISOString()}let d=new Date(s);if(!Number.isFinite(d.getTime()))return null;if(d.getUTCFullYear()===2001&&/^2001-\d{2}-\d{2}$/.test(s)){let y=new Date().getUTCFullYear();let c=new Date(Date.UTC(y,d.getUTCMonth(),d.getUTCDate(),12));if(c.getTime()>Date.now()+36*3600_000)c=new Date(Date.UTC(y-1,d.getUTCMonth(),d.getUTCDate(),12));d=c}if(d.getUTCFullYear()<2024||d.getTime()>Date.now()+36*3600_000)return null;return d.toISOString()}
function rank(k:any){return ['pennied_at','pennied_at_repaired_partial_year'].includes(txt(k))?3:txt(k)==='reported_at'?2:txt(k)==='first_captured'?1:0}
function chooseDate(r:Any,p:any){const raw=txt(r.pennied_at);let at=parseDate(raw),kind=at?(raw.startsWith('2001-')?'pennied_at_repaired_partial_year':'pennied_at'):'';if(!at){at=parseDate(r.posted_date)||parseDate(r.last_seen)||parseDate(r.signal_observed_at);if(!at&&Array.isArray(r.signal_sources)){const z=r.signal_sources.map((s:Any)=>parseDate(s?.observed_at)).filter(Boolean).sort().reverse();at=z[0]||null}if(at)kind='reported_at'}const pa=parseDate(p?.penny_sort_at),pk=txt(p?.penny_date_kind);if(pa&&rank(pk)>rank(kind))return{at:pa,kind:pk};if(pa&&rank(pk)===rank(kind)&&rank(kind)<3)return{at:pa,kind:pk};if(at)return{at,kind};if(pa)return{at:pa,kind:pk||'first_captured'};return{at:new Date().toISOString(),kind:'first_captured'}}
async function validSecret(req:Request,a:any){const got=txt(req.headers.get('x-h38-nightly-key'));if(!got)return false;const {data}=await a.from('h38_internal_job_secrets').select('secret_value').eq('name','penny-nightly').maybeSingle();return !!data?.secret_value&&got===data.secret_value}
async function invoke(slug:string,body:any,timeout=125000){try{const auth=`Bearer ${SERVICE}`;const r=await fetch(`${BASE}/functions/v1/${slug}`,{method:'POST',headers:{Authorization:auth,apikey:SERVICE,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data={raw:text}}return{ok:r.ok,status:r.status,text,data}}catch(e){return{ok:false,status:598,text:e instanceof Error?e.message:String(e),data:{}}}}
async function acquire(a:any,key:string,staleMs:number){for(let i=0;i<2;i++){const token=crypto.randomUUID(),{error}=await a.from('reseller_hunt_scan_locks').insert({cache_key:key,token,acquired_at:new Date().toISOString()});if(!error)return token;if(error.code!=='23505')throw error;const {data}=await a.from('reseller_hunt_scan_locks').select('token,acquired_at').eq('cache_key',key).maybeSingle();const old=data?.acquired_at?Date.parse(data.acquired_at):0;if(!old||Date.now()-old<=staleMs)return null;await a.from('reseller_hunt_scan_locks').delete().eq('cache_key',key).eq('token',data.token)}return null}
async function release(a:any,key:string,token:string){await a.from('reseller_hunt_scan_locks').delete().eq('cache_key',key).eq('token',token)}
async function persist(a:any,rows:Any[]){const n=rows.map(r=>({r,key:canonical(r),title:txt(r.source_identity_title||r.canonical_title||r.title||r.product_name||r.item_name)})).filter(x=>x.key&&!junk(x.title));if(!n.length)return{new_count:0,updated_count:0};const keys=[...new Set(n.map(x=>x.key))],{data:existing}=await a.from('reseller_hunt_cache').select('canonical_key,image_url,image_storage_path,image_cached_at,image_source_url,image_mime,penny_sort_at,penny_date_kind,seen_count').in('canonical_key',keys),old=new Map((existing||[]).map((x:Any)=>[x.canonical_key,x]));let add=0,upd=0;const now=new Date().toISOString();const rowsOut=n.map(({r,key,title})=>{const p:any=old.get(key);p?upd++:add++;const d=chooseDate(r,p),incoming=rawImage(r);return{canonical_key:key,retailer:txt(r.retailer||r.store_name||r.source_name),title,upc:digits(r.upc||r.gtin||r.barcode),sku:txt(r.sku||r.store_sku||r.internet_number),deal_type:txt(r.deal_type||(Number(r.reported_penny_price)===.01?'penny':'candidate')),buy_price:Number.isFinite(Number(r.buy_price??r.price??r.current_price??r.sale_price??r.deal_price))?Number(r.buy_price??r.price??r.current_price??r.sale_price??r.deal_price):null,retail_price:Number.isFinite(Number(r.retail_price??r.regular_price??r.msrp??r.reference_price??r.original_price))?Number(r.retail_price??r.regular_price??r.msrp??r.reference_price??r.original_price):null,image_url:p?.image_url||incoming||'',image_storage_path:p?.image_storage_path||'',image_cached_at:p?.image_cached_at||null,image_source_url:p?.image_source_url||incoming||'',image_mime:p?.image_mime||'',source_url:txt(r.source_item_url||r.source_url||r.url),source_bucket:'nightly-v065',payload:{...r,image_data_url:undefined,image_blob:undefined},penny_sort_at:d.at,penny_date_kind:d.kind,last_seen_at:now,last_changed_at:now,seen_count:Number(p?.seen_count||0)+1,active:true}});const {error}=await a.from('reseller_hunt_cache').upsert(rowsOut,{onConflict:'canonical_key'});if(error)throw error;return{new_count:add,updated_count:upd}}
async function retireUnseenNightly(a:any,scanStarted:string){const changed=new Date().toISOString();const {data,error}=await a.from('reseller_hunt_cache').update({active:false,last_changed_at:changed}).eq('source_bucket','nightly-v065').eq('active',true).lt('last_seen_at',scanStarted).select('canonical_key');if(error)throw error;return Array.isArray(data)?data.length:0}
function decodeData(s:string){const m=/^data:(image\/(?:jpeg|png|webp|gif|avif));base64,([A-Za-z0-9+/=\s]+)$/i.exec(txt(s));if(!m)return null;try{const bin=atob(m[2].replace(/\s/g,''));if(!bin.length||bin.length>3*1024*1024)return null;const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return{mime:m[1].toLowerCase(),bytes}}catch{return null}}
async function pathFor(key:string,mime:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key))),h=Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,40),ext=mime==='image/png'?'png':mime==='image/webp'?'webp':mime==='image/gif'?'gif':mime==='image/avif'?'avif':'jpg';return`${h.slice(0,2)}/${h}.${ext}`}
function refFor(p:Any){return txt(p?.image_reference_url||p?.source_item_url||p?.image_source_url||p?.source_url)||(Array.isArray(p?.signal_sources)?txt(p.signal_sources.find((s:Any)=>txt(s?.item_url||s?.url||s?.source_url))?.item_url||p.signal_sources.find((s:Any)=>txt(s?.item_url||s?.url||s?.source_url))?.url):'')}
async function saveImage(a:any,row:Any,img:Any){const got=decodeData(img?.data_url);if(!got)return false;const path=await pathFor(row.canonical_key,got.mime),{error}=await a.storage.from(BUCKET).upload(path,got.bytes,{contentType:got.mime,cacheControl:'31536000',upsert:true});if(error)return false;const url=a.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;const {error:e}=await a.from('reseller_hunt_cache').update({image_url:url,image_storage_path:path,image_cached_at:new Date().toISOString(),image_source_url:txt(img.source_url),image_mime:got.mime,image_last_error:'',last_changed_at:new Date().toISOString()}).eq('canonical_key',row.canonical_key);return !e}
async function repairStrictImages(a:any,cap=120){const {data}=await a.from('reseller_hunt_cache').select('canonical_key,retailer,title,upc,image_url,payload,image_attempt_count').eq('active',true).eq('image_storage_path','').in('retailer',['Dollar General','Dollar Tree']).order('image_attempt_count',{ascending:true}).order('image_attempted_at',{ascending:true,nullsFirst:true}).limit(cap);const rows=(data||[]).filter((r:Any)=>!junk(r.title)&&digits(r.upc).length>=6);let attempted=0,delivered=0;for(let i=0;i<rows.length;i+=8){const part=rows.slice(i,i+8),items=part.map((r:Any)=>({key:r.canonical_key,retailer:r.retailer,barcode:r.upc,proof:r.payload?.image_match_barcode||r.payload?.image_proof_barcode||'',image_url:r.image_url||'',reference_url:refFor(r.payload||{})})),q=await invoke('reseller-image-delivery-v201',{items},65000),imgs=Array.isArray(q.data?.images)?q.data.images:[],warnings=Array.isArray(q.data?.warnings)?q.data.warnings:[],imap=new Map(imgs.map((x:Any)=>[txt(x.key),x])),wmap=new Map(warnings.map((x:Any)=>[txt(x.key),txt(x.reason)]));for(const r of part){attempted++;const hit=imap.get(r.canonical_key),ok=hit?await saveImage(a,r,hit):false;await a.from('reseller_hunt_cache').update({image_attempted_at:new Date().toISOString(),image_attempt_count:Number(r.image_attempt_count||0)+1,image_last_error:ok?'':(wmap.get(r.canonical_key)||(!q.ok?`resolver ${q.status}`:'no exact UPC image'))}).eq('canonical_key',r.canonical_key);if(ok)delivered++}}return{attempted,delivered}}
const TRUST=['pennycentral.com','thdstatic.com','retailshout.com','pennytree.org','openfoodfacts.org','walmartimages.com','scene7.com'];
function safeRemote(v:any){try{const u=new URL(txt(v)),h=u.hostname.toLowerCase();return u.protocol==='https:'&&TRUST.some(x=>h===x||h.endsWith('.'+x))&&!/(placeholder|blank|logo|favicon|pixel|loading|no-image)/i.test(u.pathname+u.search)}catch{return false}}
async function mirrorImages(a:any,cap=48){const {data}=await a.from('reseller_hunt_cache').select('canonical_key,retailer,image_url,image_source_url').eq('active',true).eq('image_storage_path','').neq('image_url','').limit(cap);let saved=0;for(const r of data||[]){if(['dollar general','dollar tree'].includes(retailerKey(r.retailer)))continue;const src=txt(r.image_source_url||r.image_url);if(!safeRemote(src))continue;try{const f=await fetch(src,{headers:{'user-agent':'Mozilla/5.0 H38Deals/3.1','accept':'image/avif,image/webp,image/*,*/*;q=0.8'},redirect:'follow',signal:AbortSignal.timeout(9000)});if(!f.ok)continue;const mime=(f.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(mime))continue;const bytes=new Uint8Array(await f.arrayBuffer());if(!bytes.length||bytes.length>3*1024*1024)continue;const path=await pathFor(r.canonical_key,mime),{error}=await a.storage.from(BUCKET).upload(path,bytes,{contentType:mime,cacheControl:'31536000',upsert:true});if(error)continue;const url=a.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;await a.from('reseller_hunt_cache').update({image_url:url,image_storage_path:path,image_cached_at:new Date().toISOString(),image_source_url:src,image_mime:mime}).eq('canonical_key',r.canonical_key);saved++}catch{}}return{saved}}
async function runImages(a:any){const lock=await acquire(a,'penny-nightly-images',20*60*1000);if(!lock)return{shared:true,already_running:true};try{const [strict,mirror]=await Promise.all([repairStrictImages(a,120),mirrorImages(a,48)]);return{strict,mirror}}finally{await release(a,'penny-nightly-images',lock).catch(()=>{})}}
function centralNow(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),v:any={};for(const p of parts)v[p.type]=p.value;return{date:`${v.year}-${v.month}-${v.day}`,hour:v.hour}}
async function runNightly(a:any,force=false){const c=centralNow();if(!force&&c.hour!=='00')return{skipped:true,reason:'outside_midnight_central',central:c};const {data:m}=await a.from('reseller_hunt_cache_meta').select('last_nightly_date').eq('cache_key','penny').maybeSingle();if(!force&&txt(m?.last_nightly_date)===c.date)return{skipped:true,reason:'already_ran_today',central:c};const lock=await acquire(a,'penny-nightly',30*60*1000);if(!lock)return{shared:true,already_running:true};try{const scanStarted=new Date().toISOString();const q=await invoke('reseller-auto-leads-v065',{zip:'55744',postal:'55744',radius:50,radius_miles:50},130000);let stats:any={new_count:0,updated_count:0,retired_count:0},err='';const sourceStatus=txt(q.data?.status||'').toUpperCase();if(q.ok){stats=await persist(a,list(q.data));if(sourceStatus==='PASS')stats.retired_count=await retireUnseenNightly(a,scanStarted);else stats.retirement_skipped=`source_status_${sourceStatus||'UNKNOWN'}`}else err=`v065 ${q.status}: ${q.text.slice(0,400)}`;const images=await runImages(a);const {count}=await a.from('reseller_hunt_cache').select('canonical_key',{count:'exact',head:true}).eq('active',true);const patch:any={last_nightly_date:c.date,last_total_count:Number(count||0),last_new_count:stats.new_count,last_updated_count:stats.updated_count,last_error:err,updated_at:new Date().toISOString()};if(q.ok)patch.last_full_scan_at=new Date().toISOString();await a.from('reseller_hunt_cache_meta').update(patch).eq('cache_key','penny');return{ok:q.ok,central:c,source_status:sourceStatus||null,stats,images,total:Number(count||0),error:err,truth:'Unseen nightly-v065 rows are retired only after a PASS refresh. PARTIAL or failed refreshes preserve prior active evidence instead of falsely treating source unavailability as zero results.'}}finally{await release(a,'penny-nightly',lock).catch(()=>{})}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({error:'POST_REQUIRED'},405);const a=admin();if(!await validSecret(req,a))return json({error:'UNAUTHORIZED'},401);const body=await req.json().catch(()=>({})),action=txt(body.action||'nightly');try{if(action==='images')return json({ok:true,data:await runImages(a)});if(action==='nightly')return json({ok:true,data:await runNightly(a,req.headers.get('x-h38-force')==='1')});return json({error:'UNKNOWN_ACTION'},400)}catch(e){return json({error:'PENNY_NIGHTLY_ERROR',detail:e instanceof Error?e.message:String(e)},500)}});
