const txt=v=>String(v??'').trim();
const digits=v=>txt(v).replace(/\D/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const norm=v=>txt(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
function arrays(p){const out=[];for(const x of [p?.products,p?.items,p?.results,p?.data?.products,p?.data?.items,p?.data?.results,p?.search?.products])if(Array.isArray(x))out.push(...x);return out}
function productRoot(p){return p?.product||p?.data?.product||p?.data||p||{}}
function first(...v){return v.find(x=>x!==undefined&&x!==null&&txt(x)!=='')}
function priceOf(x){const p=x?.price||x?.pricing||{};return num(first(p.current,p.value,p.effective,x?.effective_price,x?.current_price,x?.price_current,typeof x?.price==='number'?x.price:null))}
function originalOf(x){const p=x?.price||x?.pricing||{};return num(first(p.original,p.was,p.regular,x?.original_price,x?.regular_price))}
function imageOf(x){const a=x?.images||x?.image_gallery||[];const firstImage=Array.isArray(a)?a[0]:null;return txt(first(x?.image_url,x?.image,firstImage?.url,firstImage?.src,typeof firstImage==='string'?firstImage:null))}
function inventoryOf(x){const p=productRoot(x),raw=p?.ext?.store_inventory||p?.store_inventory||x?.ext?.store_inventory||[];if(!Array.isArray(raw))return[];return raw.map(s=>({store_id:txt(first(s?.store_id,s?.storeId,s?.id)),store_name:txt(first(s?.store_name,s?.storeName,s?.name)),state:txt(first(s?.state,s?.state_code)),quantity:num(first(s?.quantity,s?.qty,s?.available_quantity,s?.on_hand)),in_stock:s?.in_stock===true||s?.inStock===true||num(first(s?.quantity,s?.qty,s?.available_quantity,s?.on_hand))>0})).filter(s=>s.store_id||s.store_name)}
export function normalizeHomeDepotProduct(raw={}){const x=productRoot(raw);return{item_id:txt(first(x?.item_id,x?.itemId,x?.internet_number,x?.id)),sku:txt(first(x?.sku,x?.store_sku,x?.storeSku)),upc:digits(first(x?.upc,x?.gtin,x?.barcode)),model:txt(first(x?.model_number,x?.model,x?.modelNumber)),title:txt(first(x?.title,x?.name,x?.product_name)),price:priceOf(x),original_price:originalOf(x),image_url:imageOf(x),url:txt(first(x?.url,x?.product_url,x?.source_url)),inventory:inventoryOf(x)}}
export function normalizeHomeDepotSearch(payload){return arrays(payload).map(normalizeHomeDepotProduct).filter(x=>x.item_id||x.title)}
export function identityScore(candidate={},product={}){const ids=[candidate?.sku,candidate?.upc,candidate?.item_id].map(digits).filter(x=>x.length>=5),fields=[product?.item_id,product?.sku,product?.upc,product?.model].map(digits).filter(Boolean);if(ids.some(x=>fields.includes(x)))return 100;const a=norm(candidate?.title||candidate?.canonical_title),b=norm(product?.title);if(a&&b){const words=a.split(' ').filter(x=>x.length>2),hit=words.filter(x=>b.includes(x)).length;if(words.length&&hit/words.length>=.7)return 70;if(hit>=2)return 45}return 0}
export function bestHomeDepotMatch(payload,candidate){return normalizeHomeDepotSearch(payload).map(x=>({...x,identity_score:identityScore(candidate,x)})).sort((a,b)=>b.identity_score-a.identity_score)[0]||null}
export function storeReading(detail,storeId='',fallback={}){const p=normalizeHomeDepotProduct(detail),inv=p.inventory.find(x=>txt(x.store_id)===txt(storeId))||p.inventory[0]||{};return{store_id:txt(storeId||inv.store_id||fallback.store_id),store_name:txt(inv.store_name||fallback.store_name),quantity:inv.quantity??null,in_stock:inv.in_stock===true,price:p.price,original_price:p.original_price,price_scope:storeId?'store':'zip',inventory_scope:inv.store_id?'store':'unknown',penny_signal:storeId&&p.price===0.01,evidence_level:storeId?'LIVE VERIFIED':'LIVE PARTIAL'}}
export function communityFallback(candidate){return{...candidate,evidence_level:'COMMUNITY SIGNAL',local_price:null,local_inventory:null,local_verified:false,penny_truth:'Community/crawler evidence is discovery evidence. A web mismatch never erases penny evidence; physical in-store register scan remains final local truth.'}}
