import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {bestHomeDepotMatch,normalizeHomeDepotProduct,storeReading,communityFallback} from './core.mjs';
type Any=Record<string,any>;
const KEY=Deno.env.get('SOCIALCRAWL_API_KEY')||'';
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
const BASE='https://www.socialcrawl.dev/v1/home_depot';
function cors(r:Request){const o=r.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=45','vary':'Origin'}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function txt(v:any){return String(v??'').trim()}
async function api(path:string,params:Record<string,string>,timeout=18000){const u=new URL(`${BASE}/${path}`);for(const [k,v] of Object.entries(params))if(v)u.searchParams.set(k,v);const r=await fetch(u,{headers:{'x-api-key':KEY,accept:'application/json','user-agent':'H38ResellerScout/2.4.0'},signal:AbortSignal.timeout(timeout)}),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(`SocialCrawl ${path} HTTP ${r.status}`);return p}
async function candidateReading(c:Any,zip:string,deep:boolean){const query=txt(c.sku||c.upc||c.title||c.canonical_title);if(!query)return communityFallback(c);const search=await api('search',{query,zipcode:zip,items_per_page:'8'}),match=bestHomeDepotMatch(search,c);if(!match||Number(match.identity_score||0)<45)return{...communityFallback(c),provider_detail:'No sufficiently strong Home Depot identity match from localized search.'};const detail=await api('product',{item_id:match.item_id,zipcode:zip}),product=normalizeHomeDepotProduct(detail),inventory=product.inventory||[],out:Any={...c,provider:'SocialCrawl Home Depot',provider_status:'LIVE',identity_verified:Number(match.identity_score)>=70,item_id:product.item_id||match.item_id,title:product.title||match.title||c.title,image_url:product.image_url||match.image_url||c.image_url,url:product.url||match.url||c.url,zip_price:product.price??match.price??null,zip_original_price:product.original_price??match.original_price??null,price_scope:'zip',store_inventory:inventory,inventory_scope:inventory.length?'store':'unknown',evidence_level:inventory.length?'LIVE PARTIAL':'LIVE PARTIAL',local_verified:false,penny_truth:'Localized web/store signals never erase penny evidence. Physical in-store register scan remains final penny truth.'};if(deep&&out.identity_verified&&product.item_id){const stores=inventory.filter((x:any)=>x.store_id).sort((a:any,b:any)=>(Number(b.quantity)||0)-(Number(a.quantity)||0)).slice(0,3),settled=await Promise.allSettled(stores.map((s:any)=>api('product',{item_id:product.item_id,store_id:String(s.store_id)})));out.store_readings=settled.map((x:any,i:number)=>x.status==='fulfilled'?storeReading(x.value,String(stores[i].store_id),stores[i]):{...stores[i],evidence_level:'UNAVAILABLE',price:null,price_scope:'unknown',inventory_scope:'store',penny_signal:false});out.local_verified=out.store_readings.some((x:any)=>x.evidence_level==='LIVE VERIFIED');if(out.local_verified)out.evidence_level='LIVE VERIFIED'}return out}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,405,{error:'POST required'});if(!req.headers.get('authorization'))return json(req,401,{error:'Sign in required'});const b=await req.json().catch(()=>({})),zip=txt(b.postal||'55744').match(/\d{5}/)?.[0]||'55744',candidates=(Array.isArray(b.candidates)?b.candidates:[]).filter((x:any)=>/home depot/i.test(txt(x.retailer||'Home Depot'))).slice(0,6),deep=!!b.deep_verify;if(!KEY)return json(req,200,{status:'PARTIAL',engine:'H38_HOME_DEPOT_LOCAL_V240',provider_status:'CONFIG_REQUIRED',provider_detail:'SOCIALCRAWL_API_KEY is not configured; community penny candidates are preserved without inventing local price or inventory.',readings:candidates.map(communityFallback),candidate_count:candidates.length,truth:'COMMUNITY SIGNAL only. Physical register scan remains final penny truth.'});const settled=await Promise.allSettled(candidates.map((c:any)=>candidateReading(c,zip,deep))),readings=settled.map((x:any,i:number)=>x.status==='fulfilled'?x.value:{...communityFallback(candidates[i]),provider_status:'UNAVAILABLE',provider_detail:x.reason?.message||String(x.reason)}),verified=readings.filter((x:any)=>x.evidence_level==='LIVE VERIFIED').length,partial=readings.filter((x:any)=>x.evidence_level==='LIVE PARTIAL').length;return json(req,200,{status:verified||partial?'PASS':'PARTIAL',engine:'H38_HOME_DEPOT_LOCAL_V240',provider_status:'LIVE',postal:zip,readings,verified_count:verified,partial_count:partial,candidate_count:candidates.length,truth:'Store-level evidence is labeled separately from ZIP-localized price and community penny evidence. Physical register scan remains final penny truth.'})});
