import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ALLOWED = new Set([
  "ccf25333-47cd-42ca-a20b-cdbc63a8a695",
  "6dd51b31-5974-4691-b8b8-83e5877528c0",
]);
const SUPABASE_URL = Deno.env.get("SUPABASE_URL") || "";
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const ORIGINS = new Set([
  "https://appassets.androidplatform.net",
  "https://highway38solutions.com",
  "https://www.highway38solutions.com",
]);
const RETAILER_PATTERN = "Home Depot|Lowe|Walmart|Target|Menards|Fleet Farm|L&M|L & M|Harbor Freight|Tractor Supply|Dollar General|Dollar Tree|Family Dollar|Northern Tool|Ace Hardware|AutoZone|O.Reilly|NAPA|Advance Auto Parts|Carquest|Auto Value|Parts City|Bumper to Bumper|Best Buy|Walgreens|CVS|Kohl|JCPenney|TJ Maxx|T.J. Maxx|Marshalls|Ross Dress|Burlington|Five Below|Aldi|Costco|Sam.s Club|PetSmart|Petco|Michaels|Hobby Lobby|JOANN|Dunham|Runnings|HomeGoods";
const RETAILER_RE = /Home Depot|Lowe'?s|Walmart|Target|Menards|Fleet Farm|L\s*(?:&|and)\s*M|Harbor Freight|Tractor Supply|Dollar General|Dollar Tree|Family Dollar|Northern Tool|Ace Hardware|AutoZone|O'Reilly|NAPA|Advance Auto Parts|Carquest|Auto Value|Parts City|Bumper to Bumper|Best Buy|Walgreens|CVS|Kohl|JCPenney|TJ Maxx|T\.J\. Maxx|Marshalls|Ross Dress|Burlington|Five Below|Aldi|Costco|Sam'?s Club|PetSmart|Petco|Michaels|Hobby Lobby|JOANN|Dunham|Runnings|HomeGoods/i;
const RELEVANT_SHOPS = new Set(["car_parts","hardware","doityourself","department_store","variety_store","discount","electronics"]);
const OVERPASS = ["https://overpass.private.coffee/api/interpreter","https://overpass-api.de/api/interpreter"];
const DISCOVERY_VERSION = "incremental-durable-store-scan-v1";
const TILE_BATCH = 4;
const HEDGE_DELAY_MS = 300;
const PROVIDER_TIMEOUT_MS = 4200;
const TILE_FRESH_MS = 6 * 60 * 60 * 1000;

type Box={south:number;west:number;north:number;east:number};
type TileRow={tile_index:number;stores:any[];source?:string;updated_at?:string};
function cors(req:Request){const o=req.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","vary":"Origin"};}
function json(req:Request,status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:cors(req)});}
async function userId(req:Request){const token=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)throw Error("Sign in required.");const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:SERVICE_KEY}});const p=await r.json().catch(()=>({}));if(!r.ok||!p?.id)throw Error("Session expired.");return String(p.id);}
function haversine(a:number,b:number,c:number,d:number){const R=3958.7613,rad=(x:number)=>x*Math.PI/180,dLat=rad(c-a),dLon=rad(d-b),q=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
function canonical(name:string){const s=name.toLowerCase();if(s.includes("l&m")||s.includes("l & m")||s.includes("l and m"))return"L&M Fleet Supply";if(s.includes("autozone"))return"AutoZone";if(s.includes("o'reilly"))return"O'Reilly Auto Parts";if(s.includes("napa"))return"NAPA Auto Parts";if(s.includes("advance auto"))return"Advance Auto Parts";if(s.includes("carquest"))return"Carquest";if(s.includes("auto value"))return"Auto Value";if(s.includes("parts city"))return"Parts City";if(s.includes("bumper to bumper"))return"Bumper to Bumper";if(s.includes("home depot"))return"Home Depot";if(s.includes("lowe"))return"Lowe's";if(s.includes("walmart"))return"Walmart";if(s.includes("target"))return"Target";if(s.includes("menards"))return"Menards";if(s.includes("fleet farm"))return"Fleet Farm";if(s.includes("harbor freight"))return"Harbor Freight";if(s.includes("tractor supply"))return"Tractor Supply";if(s.includes("dollar general"))return"Dollar General";if(s.includes("dollar tree"))return"Dollar Tree";if(s.includes("family dollar"))return"Family Dollar";if(s.includes("northern tool"))return"Northern Tool";if(s.includes("ace"))return"Ace Hardware";if(s.includes("best buy"))return"Best Buy";if(s.includes("walgreens"))return"Walgreens";if(s==="cvs"||s.includes("cvs pharmacy"))return"CVS";if(s.includes("kohl"))return"Kohl's";if(s.includes("jcpenney"))return"JCPenney";if(s.includes("tj maxx")||s.includes("t.j. maxx"))return"TJ Maxx";if(s.includes("marshalls"))return"Marshalls";if(s.includes("ross dress"))return"Ross";if(s.includes("burlington"))return"Burlington";if(s.includes("five below"))return"Five Below";if(s.includes("aldi"))return"Aldi";if(s.includes("costco"))return"Costco";if(s.includes("sam's club")||s.includes("sams club"))return"Sam's Club";if(s.includes("petsmart"))return"PetSmart";if(s.includes("petco"))return"Petco";if(s.includes("michaels"))return"Michaels";if(s.includes("hobby lobby"))return"Hobby Lobby";if(s.includes("joann"))return"JOANN";if(s.includes("dunham"))return"Dunham's";if(s.includes("runnings"))return"Runnings";if(s.includes("homegoods"))return"HomeGoods";return name;}
function address(t:any){return[t["addr:housenumber"],t["addr:street"],t["addr:city"],t["addr:state"],t["addr:postcode"]].filter(Boolean).join(" ").replace(/ (\d{5})$/,", $1");}
function areaKey(lat:number,lon:number,radius:number){const q=(v:number)=>Math.round(v*20)/20;return`${q(lat).toFixed(2)}|${q(lon).toFixed(2)}|${radius}`;}
function region(lat:number,lon:number,r:number):Box{const dy=r/69,dx=r/(69.172*Math.max(.15,Math.cos(lat*Math.PI/180)));return{south:lat-dy,west:lon-dx,north:lat+dy,east:lon+dx};}
function splitGrid(b:Box,n:number){const out:Box[]=[];const dy=(b.north-b.south)/n,dx=(b.east-b.west)/n;for(let y=0;y<n;y++)for(let x=0;x<n;x++)out.push({south:b.south+y*dy,west:b.west+x*dx,north:b.south+(y+1)*dy,east:b.west+(x+1)*dx});return out;}
function bbox(b:Box){return`${b.south.toFixed(5)},${b.west.toFixed(5)},${b.north.toFixed(5)},${b.east.toFixed(5)}`;}
function tileQuery(b:Box){const a=bbox(b);return`[out:json][timeout:4];(nwr["name"~"${RETAILER_PATTERN}",i](${a});nwr["brand"~"${RETAILER_PATTERN}",i](${a});nwr["shop"~"^(car_parts|hardware|doityourself|department_store|variety_store|discount|electronics)$"](${a}););out center tags qt;`;}
function validPayload(p:any){if(!p||!Array.isArray(p.elements))return false;const r=String(p.remark||"").toLowerCase();return!r.includes("runtime error")&&!r.includes("timed out")&&!r.includes("timeout")&&!r.includes("out of memory");}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
async function queryTile(query:string,preferred:number){const endpoints=[OVERPASS[preferred%2],OVERPASS[(preferred+1)%2]],controllers=endpoints.map(()=>new AbortController());return await new Promise<any>(resolve=>{let done=0,settled=false;endpoints.forEach((endpoint,i)=>{(async()=>{try{if(i)await sleep(HEDGE_DELAY_MS);if(settled)return;const c=controllers[i],timer=setTimeout(()=>c.abort(),PROVIDER_TIMEOUT_MS);try{const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded","user-agent":"H38-Private-Reseller-Scout/0.1.18"},body:`data=${encodeURIComponent(query)}`,signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);const p=await r.json();if(!validPayload(p))throw Error("invalid partial Overpass response");if(settled)return;settled=true;controllers.forEach((x,j)=>{if(j!==i)x.abort()});resolve({ok:true,payload:p,source:new URL(endpoint).host});}finally{clearTimeout(timer)}}catch{}finally{done++;if(!settled&&done===endpoints.length){settled=true;resolve({ok:false,payload:{elements:[]},source:""})}}})();});});}
function parseStores(elements:any[],lat:number,lon:number,radius:number){const m=new Map<string,any>();for(const e of elements){const t=e.tags||{},name=String(t.name||t.brand||"").trim(),shop=String(t.shop||"").toLowerCase(),slat=Number(e.lat??e.center?.lat),slon=Number(e.lon??e.center?.lon);if(!name||(!RETAILER_RE.test(name)&&!RELEVANT_SHOPS.has(shop))||!Number.isFinite(slat)||!Number.isFinite(slon))continue;const d=Math.round(haversine(lat,lon,slat,slon)*10)/10;if(d>radius)continue;const retailer=canonical(name),addr=address(t),logical=[retailer.toLowerCase(),addr.toLowerCase()||`${slat.toFixed(3)},${slon.toFixed(3)}`].join("|");const x={store_key:`osm:${e.type}:${e.id}`,store_name:name,retailer,store_address:addr,lat:slat,lon:slon,distance_miles:d,store_category:shop||null};if(!m.has(logical)||(!m.get(logical).store_address&&addr))m.set(logical,x);}return[...m.values()];}
function mergeStores(rows:any[][],lat:number,lon:number,radius:number){const m=new Map<string,any>();for(const arr of rows)for(const s of arr||[]){const slat=Number(s.lat),slon=Number(s.lon);if(!Number.isFinite(slat)||!Number.isFinite(slon))continue;const d=Math.round(haversine(lat,lon,slat,slon)*10)/10;if(d>radius)continue;const logical=[String(s.retailer||s.store_name||"").toLowerCase(),String(s.store_address||"").toLowerCase()||`${slat.toFixed(3)},${slon.toFixed(3)}`].join("|");m.set(logical,{...s,distance_miles:d});}return[...m.values()].sort((a,b)=>a.distance_miles-b.distance_miles).slice(0,500);}
const restHeaders={apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json"};
async function loadTiles(key:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/reseller_store_discovery_tiles?area_key=eq.${encodeURIComponent(key)}&select=tile_index,stores,source,updated_at`,{headers:restHeaders});if(!r.ok)return[] as TileRow[];const p=await r.json().catch(()=>[]);return Array.isArray(p)?p:[];}
async function saveTile(key:string,index:number,lat:number,lon:number,radius:number,stores:any[],source:string){await fetch(`${SUPABASE_URL}/rest/v1/reseller_store_discovery_tiles?on_conflict=area_key,tile_index`,{method:"POST",headers:{...restHeaders,prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({area_key:key,tile_index:index,lat,lon,radius_miles:radius,stores,source,updated_at:new Date().toISOString()})}).catch(()=>{});}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required."});const started=Date.now();try{const uid=await userId(req);if(!ALLOWED.has(uid))return json(req,403,{error:"Not authorized."});const body=await req.json().catch(()=>({})),lat=Number(body.lat),lon=Number(body.lon),radius=Math.min(150,Math.max(1,Number(body.radiusMiles||50)));if(!Number.isFinite(lat)||!Number.isFinite(lon))return json(req,400,{error:"Valid phone location required."});const grid=radius<=25?3:radius<=50?4:radius<=100?5:6,tiles=splitGrid(region(lat,lon,radius),grid),key=areaKey(lat,lon,radius);let saved=await loadTiles(key);const byIndex=new Map(saved.map(x=>[Number(x.tile_index),x]));const now=Date.now();const candidates=tiles.map((_,i)=>({i,row:byIndex.get(i)})).sort((a,b)=>{const am=a.row?Date.parse(a.row.updated_at||""):0,bm=b.row?Date.parse(b.row.updated_at||""):0;const af=now-am<TILE_FRESH_MS,bf=now-bm<TILE_FRESH_MS;if(af!==bf)return af?1:-1;return am-bm;}).slice(0,TILE_BATCH);const results=await Promise.all(candidates.map(async(c,j)=>{const q=await queryTile(tileQuery(tiles[c.i]),(c.i+j)%2);if(!q.ok)return{index:c.i,ok:false};const stores=parseStores(q.payload.elements,lat,lon,radius);await saveTile(key,c.i,lat,lon,radius,stores,q.source);return{index:c.i,ok:true,stores,source:q.source};}));saved=await loadTiles(key);const merged=mergeStores(saved.map(x=>Array.isArray(x.stores)?x.stores:[]),lat,lon,radius);const done=new Set(saved.map(x=>Number(x.tile_index))).size,complete=done>=tiles.length,successes=results.filter(x=>x.ok).length;return json(req,200,{status:complete?"PASS":"PARTIAL",radius_miles:radius,stores:merged,store_count:merged.length,coverage_tiles_done:done,coverage_tiles_total:tiles.length,scan_complete:complete,refresh_incomplete:!complete,batch_tiles:candidates.map(x=>x.i),batch_successes:successes,elapsed_ms:Date.now()-started,discovery_version:DISCOVERY_VERSION,warning:complete?null:(successes?"Store coverage is still filling in; successful regions were saved.":"No new map regions completed on this pass; keeping saved store coverage.")});}catch(e){return json(req,200,{status:"PARTIAL",stores:[],store_count:0,refresh_incomplete:true,elapsed_ms:Date.now()-started,discovery_version:DISCOVERY_VERSION,warning:e instanceof Error?e.message:String(e)});}});
