import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const BASE=Deno.env.get("SUPABASE_URL")||"";
const UA="Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 H38ResellerScout/0.1.43 penny-hunt";
const SIGNAL_VERSION="penny-hunt-v043";
const DEDUPE_VERSION="cross-source-identity-v043";
const CACHE_MS=8*60*1000;
let extraCache:any=null;

const EXTRA_SOURCES=[
  {id:"pc-hd",retailer:"Home Depot",name:"PennyCentral",domain:"pennycentral.com",url:"https://www.pennycentral.com/penny-list",kind:"penny",parser:"pennycentral",priority:145},
  {id:"kcl-dg",retailer:"Dollar General",name:"Krazy Coupon Lady",domain:"thekrazycouponlady.com",url:"https://thekrazycouponlady.com/tips/store-hacks/dollar-general-penny-list",kind:"penny",parser:"upc-list",priority:122},
  {id:"freebie-dg",retailer:"Dollar General",name:"The Freebie Guy",domain:"thefreebieguy.com",url:"https://thefreebieguy.com/dollar-general-penny-shopping-master-list/",kind:"penny",parser:"upc-list",priority:121},
  {id:"pt-dg-penny",retailer:"Dollar General",name:"Penny Tree",domain:"pennytree.org",url:"https://pennytree.org/?store=dollargeneral",kind:"penny",parser:"pennytree",priority:118},
  {id:"pt-dg-near",retailer:"Dollar General",name:"Penny Tree",domain:"pennytree.org",url:"https://pennytree.org/?sort=new&store=dollargeneral&view=cheap",kind:"near_penny",parser:"pennytree",priority:112,max_price:.50},
  {id:"pt-dt-penny",retailer:"Dollar Tree",name:"Penny Tree",domain:"pennytree.org",url:"https://pennytree.org/?page=1&sort=new&view=pennies",kind:"penny",parser:"pennytree",priority:118},
  {id:"pt-dt-near",retailer:"Dollar Tree",name:"Penny Tree",domain:"pennytree.org",url:"https://pennytree.org/print-list.php?view=clearance",kind:"near_penny",parser:"pennytree",priority:112,max_price:.75},
  {id:"pt-fd-penny",retailer:"Family Dollar",name:"Penny Tree",domain:"pennytree.org",url:"https://pennytree.org/?store=familydollar",kind:"penny",parser:"pennytree",priority:116},
  {id:"pt-fd-near",retailer:"Family Dollar",name:"Penny Tree",domain:"pennytree.org",url:"https://pennytree.org/?sort=new&store=familydollar&view=cheap",kind:"near_penny",parser:"pennytree",priority:111,max_price:.97}
];

function cors(req:Request){const origin=req.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(origin)?origin:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"GET, POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"private, max-age=120","vary":"Origin"}}
function json(req:Request,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
function clean(v:any){return String(v??"").replace(/\s+/g," ").trim()}
function decode(v:any){return String(v??"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&ndash;|&#8211;/gi,"–").replace(/&mdash;|&#8212;/gi,"—").replace(/&ldquo;|&rdquo;|&#8220;|&#8221;/gi,'"').replace(/&#x2F;/gi,"/").replace(/&#(\d+);/g,(_:string,n:string)=>{try{return String.fromCodePoint(Number(n))}catch{return" "}})}
function lines(html:string){return decode(String(html||"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"\n").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"\n").replace(/<br\s*\/?>/gi,"\n").replace(/<\/(?:p|div|li|h[1-6]|tr|article|section|button|a|span)>/gi,"\n").replace(/<[^>]+>/g," ")).split(/\r?\n/).map(clean).filter(Boolean)}
function retailerKey(v:any){const s=clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();if(s.includes("home depot"))return"home depot";if(s.includes("dollar general"))return"dollar general";if(s.includes("dollar tree"))return"dollar tree";if(s.includes("family dollar"))return"family dollar";if(s.includes("lowe"))return"lowes";return s}
function digits(v:any){return clean(v).replace(/\D/g,"")}
function skuNorm(retailer:any,v:any){const raw=clean(v).toLowerCase(),d=digits(raw);return retailerKey(retailer)==="home depot"&&d.length>=5?d:raw.replace(/[^a-z0-9]+/g,"")}
function titleNorm(v:any){return clean(v).toLowerCase().replace(/\b(?:the|a|an)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim().slice(0,170)}
function genericTitle(v:any){const s=clean(v);return !s||/^(?:home depot|dollar general|dollar tree|family dollar)\s+(?:penny|near-penny)\s+candidate\b/i.test(s)||/^(?:penny|clearance)\s+candidate\b/i.test(s)||/^sku\b/i.test(s)}
function usefulTitle(v:any){const s=clean(v);if(s.length<4||s.length>260)return false;return !/^(?:[→←•·]+|or|today|yesterday|report find|set store|add to|on your list|i found it|just became a penny\b|upc\b|sku\b|penny\b|clearance\b|current weekly list|surprise penny list|health & beauty|food|beverage|medicine|new markdowns?)\b/i.test(s)&&!/\b\d+d ago$/i.test(s)}
function aliases(row:any){const r=retailerKey(row?.retailer),a:string[]=[],u=digits(row?.upc),s=skuNorm(row?.retailer,row?.sku),t=titleNorm(row?.title);if(u.length>=7)a.push(`${r}|u:${u}`);if(s)a.push(`${r}|s:${s}`);if(t&&usefulTitle(row?.title)&&!genericTitle(row?.title)&&t.length>=10)a.push(`${r}|t:${t}`);return a}
function rank(row:any){const type=String(row?.deal_type||"").toLowerCase();return(type==="penny"?200000:type==="near_penny"?100000:0)+(row?.deep_discount?10000:0)+Number(row?.source_priority||0)*10+Number(row?.discount_pct||0)+(genericTitle(row?.title)?-5000:5000)}
function sourceDomain(row:any){if(clean(row?.signal_domain))return clean(row.signal_domain).toLowerCase();try{return new URL(clean(row?.source_url)).hostname.toLowerCase().replace(/^www\./,"")}catch{return clean(row?.source_name).toLowerCase()}}
function signalFrom(row:any){return{name:clean(row?.signal_name||row?.source_name||"Source"),domain:sourceDomain(row),url:clean(row?.signal_url||row?.source_url),kind:clean(row?.deal_type||"candidate"),observed_price:Number.isFinite(Number(row?.reported_penny_price))?Number(row.reported_penny_price):Number.isFinite(Number(row?.buy_price))?Number(row.buy_price):null,observed_at:clean(row?.signal_observed_at||row?.penny_date||row?.last_seen||"")}}
function distinctSignals(list:any[]){const out:any[]=[],seen=new Set<string>();for(const s of list||[]){const domain=clean(s?.domain||(()=>{try{return new URL(clean(s?.url)).hostname.replace(/^www\./,"")}catch{return""}})()).toLowerCase(),key=domain||clean(s?.name).toLowerCase();if(!key||seen.has(key))continue;seen.add(key);out.push({...s,domain})}return out}
function confidence(n:number){return n>=3?"HIGH":n>=2?"MEDIUM":"LOW"}
function mergeRows(a:any,b:any){const winner=rank(b)>rank(a)?b:a,loser=winner===b?a:b,merged={...loser,...winner};if(genericTitle(merged.title)&&usefulTitle(loser.title)&&!genericTitle(loser.title))merged.title=loser.title;merged.signal_sources=distinctSignals([...(Array.isArray(a.signal_sources)?a.signal_sources:[]),signalFrom(a),...(Array.isArray(b.signal_sources)?b.signal_sources:[]),signalFrom(b)]);if(String(a.deal_type)==="penny"||String(b.deal_type)==="penny"){merged.deal_type="penny";merged.near_penny=false;merged.reported_penny_price=.01}else if(String(a.deal_type)==="near_penny"||String(b.deal_type)==="near_penny"){merged.deal_type="near_penny";merged.near_penny=true}merged.penny_date=clean(winner.penny_date||loser.penny_date||winner.last_seen||loser.last_seen||"");merged.last_seen=clean(winner.last_seen||loser.last_seen||winner.penny_date||loser.penny_date||"");merged.image_url=clean(winner.image_url||loser.image_url||"");merged.brand=clean(winner.brand||loser.brand||"");merged.community_reports=Math.max(Number(a.community_reports||0),Number(b.community_reports||0));merged.community_states=Math.max(Number(a.community_states||0),Number(b.community_states||0));merged.state_summary=clean(winner.state_summary||loser.state_summary||"");return merged}
function aggregate(rows:any[]){const clusters:any[]=[],aliasToIndex=new Map<string,number>();for(const row0 of rows){if(!row0||!clean(row0.retailer))continue;const row={...row0};if(!usefulTitle(row.title)&&!row.upc&&!row.sku)continue;const aa=aliases(row);let idx=-1;for(const k of aa){if(aliasToIndex.has(k)){idx=aliasToIndex.get(k)!;break}}if(idx<0){idx=clusters.length;row.signal_sources=distinctSignals([...(Array.isArray(row.signal_sources)?row.signal_sources:[]),signalFrom(row)]);clusters.push(row)}else clusters[idx]=mergeRows(clusters[idx],row);for(const k of aliases(clusters[idx]))aliasToIndex.set(k,idx);for(const k of aa)aliasToIndex.set(k,idx)}const out=clusters.filter(Boolean);for(const row of out){const sigs=distinctSignals(row.signal_sources||[]);row.signal_sources=sigs;row.signal_source_count=sigs.length;row.signal_confidence=confidence(sigs.length);row.signal_version=SIGNAL_VERSION;row.source_domains=sigs.map((s:any)=>s.domain).filter(Boolean);row.posted_date=clean(row.posted_date||row.penny_date||row.last_seen||sigs.find((s:any)=>s.observed_at)?.observed_at||"");const type=String(row.deal_type||"");if(type==="penny")row.availability_label=clean(`${row.signal_confidence} PENNY LEAD · ${sigs.length} independent source${sigs.length===1?"":"s"}. Store/web prices are check history only; the penny lead stays active until physically scanned.`);else if(type==="near_penny")row.availability_label=clean(`NEAR-PENNY LEAD · ${sigs.length} independent source${sigs.length===1?"":"s"}. Verify before buying.`)}return out.sort((a,b)=>rank(b)-rank(a))}
function makeSignal(src:any,title:string,upc:string,sku:string,price:number,kind:string,extra:any={}){const penny=kind==="penny",near=kind==="near_penny";return{id:`${retailerKey(src.retailer).replace(/\s+/g,"-")}:${upc||sku||titleNorm(title).replace(/\s+/g,"-").slice(0,80)}`,retailer:src.retailer,title:clean(title),sku:clean(sku),upc:digits(upc),buy_price:penny?.01:Number(price||0),reported_penny_price:penny?.01:null,original_price:Number(extra.original_price||0),discount_pct:penny?99:Number(extra.discount_pct||0),deep_discount:penny||near,deal_type:kind,near_penny:near,penny_date:clean(extra.date||""),posted_date:clean(extra.date||""),last_seen:clean(extra.last_seen||extra.date||""),brand:clean(extra.brand||""),image_url:clean(extra.image_url||""),community_reports:Number(extra.reports||0),community_states:Number(extra.states||0),state_summary:clean(extra.state_summary||""),source_name:src.name,source_url:src.url,source_priority:src.priority,availability_label:penny?"Penny hunting signal; scan the physical item in store for final truth.":"Cheap clearance signal; verify before buying.",resale_potential:penny?88:72,stock_status:"not_checked",stock_count:null,stock_checked:false,signal_name:src.name,signal_domain:src.domain,signal_url:src.url,signal_observed_at:clean(extra.date||""),signal_sources:[{name:src.name,domain:src.domain,url:src.url,kind,observed_price:penny?.01:Number(price||0),observed_at:clean(extra.date||"")}]} }
function parseUpcList(html:string,src:any){const x=lines(html),out:any[]=[],seen=new Set<string>();let date="";for(const ln of x.slice(0,120)){const m=ln.match(/(?:effective|updated|surprise penny items?|penny items?)\s*(?:wednesday|tuesday)?[,]?\s*([A-Z][a-z]+\s+\d{1,2}(?:,\s*2026)?)/i);if(m){date=m[1];break}}for(let i=0;i<x.length&&out.length<120;i++){const ln=x[i];let m=ln.match(/^(.{4,230}?)(?:\s*[—–-]\s*UPC\s*:?\s*|\s+[—–-]\s*)(\d{7,14})\s*$/i);if(!m)m=ln.match(/^(.{4,230}?)\s+UPC\s*:?\s*(\d{7,14})\s*$/i);if(!m)continue;const title=clean(m[1]).replace(/^[*•·-]+\s*/,""),upc=digits(m[2]);if(!usefulTitle(title)||upc.length<7||seen.has(upc))continue;seen.add(upc);out.push(makeSignal(src,title,upc,"",.01,"penny",{date}))}return out}
function pricesFrom(v:any){return[...String(v||"").matchAll(/\$\s*(\d+(?:\.\d{1,2})?)/g)].map(m=>Number(m[1])).filter(Number.isFinite)}
function stripTitle(v:any){return clean(v).replace(/^(?:🪙\s*Penny|Penny|🏷️\s*Clearance|Clearance)\s*/i,"").replace(/^[^$]{0,55}\$[0-9.]+\s+/,"").replace(/\s+(?:🆕|🔻|🗓|first carried|submitted|updated)[\s\S]*$/i,"").replace(/\s+/g," ").trim()}
function parsePennyTree(html:string,src:any){const x=lines(html),out:any[]=[],seen=new Set<string>();for(let i=0;i<x.length&&out.length<140;i++){let upc="",sku="";const um=x[i].match(/\bUPC\s+(\d{7,14})\b/i),im=x[i].match(/\$\s*(\d+(?:\.\d{1,2})?)\s+#(\d{5,12})\b/);if(um)upc=digits(um[1]);if(im)sku=clean(im[2]);if(!upc&&!sku)continue;const id=upc||sku;if(seen.has(id))continue;let sourceLine=im?x[i]:"";if(!sourceLine)for(let j=i-1;j>=Math.max(0,i-6);j--){if(/\$\s*\d+(?:\.\d{1,2})?/.test(x[j])&&usefulTitle(x[j])){sourceLine=x[j];break}}if(!sourceLine)continue;const ps=pricesFrom(sourceLine),price=im?Number(im[1]):(ps.length?ps[ps.length-1]:0);if(!(price>0))continue;const penny=Math.abs(price-.01)<.0001;if(src.kind==="penny"&&!penny)continue;if(src.kind==="near_penny"&&(penny||price>Number(src.max_price||.97)))continue;let title=stripTitle(sourceLine).replace(/\$\s*\d+(?:\.\d{1,2})?/g," ").replace(/\s+/g," ").trim();if(!usefulTitle(title)){for(let j=i-1;j>=Math.max(0,i-5);j--){const t=stripTitle(x[j]);if(usefulTitle(t)&&!/\b(?:UPC|Add to|On your list)\b/i.test(t)){title=t;break}}}if(!usefulTitle(title))continue;seen.add(id);const was=ps.length>1?Math.max(...ps):0,pct=was>price?Math.round((1-price/was)*100):0,date=x.slice(Math.max(0,i-4),Math.min(x.length,i+8)).map(v=>v.match(/(?:today|yesterday|\d+\s*(?:hours?|days?|weeks?)\s*ago|[A-Z][a-z]+\s+\d{1,2}(?:,\s*\d{4})?)/i)?.[0]||"").find(Boolean)||"";out.push(makeSignal(src,title,upc,sku,price,penny?"penny":"near_penny",{original_price:was,discount_pct:pct,date}))}return out}
function absoluteUrl(v:string,base:string){try{return new URL(decode(v),base).toString()}catch{return""}}
function parsePennyCentral(html:string,src:any){const x=lines(html),out:any[]=[],seen=new Set<string>();for(let i=0;i<x.length&&out.length<140;i++){const m=x[i].match(/\bSKU\s*[:#]?\s*([0-9][0-9-]{4,20})\b/i);if(!m)continue;const sku=clean(m[1]),id=digits(sku);if(id.length<5||seen.has(id))continue;const before=x.slice(Math.max(0,i-8),i),after=x.slice(i+1,Math.min(x.length,i+13)),block=[...before,x[i],...after].join(" ");if(!/\$\s*0\.01\b/i.test(block))continue;let title="";for(let j=before.length-1;j>=0;j--){const t=clean(before[j]).replace(/^Image:\s*/i,"");if(usefulTitle(t)&&!/^(?:fresh signal|hot right now|community|home depot|check amazon|ryobi|milwaukee|dewalt|ridgid|husky|lifeproof|hampton bay|glacier bay|hdx)$/i.test(t)&&!/^\$/.test(t)){title=t;break}}if(!usefulTitle(title))continue;let brand="";const ti=before.findIndex(v=>clean(v).replace(/^Image:\s*/i,"")===title);if(ti>0){const b=clean(before[ti-1]);if(/^[A-Za-z0-9][A-Za-z0-9 &+.'-]{1,40}$/.test(b)&&!/^Image:/i.test(b))brand=b}const prices=[...block.matchAll(/\$\s*([0-9,.]+)/g)].map(z=>Number(z[1].replace(/,/g,""))).filter(n=>Number.isFinite(n)&&n>.01&&n<100000),was=prices.length?Math.max(...prices):0,last=clean(block.match(/Last seen\s*:?\s*([^·|]{1,48}?)(?=Community|\d+\s+reports?|Reported by|$)/i)?.[1]||""),reports=Number(block.match(/(\d{1,5})\s+reports?\b/i)?.[1]||0),states=Number(block.match(/(\d{1,3})\s+states?\b/i)?.[1]||0),summary=clean(block.match(/((?:[A-Z]{2}\s+\d+\s*){1,12}(?:\+\d+ more)?)/)?.[1]||"");const rawAt=html.toLowerCase().indexOf(`sku ${sku}`.toLowerCase()),slice=rawAt>=0?html.slice(Math.max(0,rawAt-6000),Math.min(html.length,rawAt+1200)):"",imgs=[...slice.matchAll(/<img\b[^>]*?(?:src|data-src)=["']([^"']+)["'][^>]*>/gi)],image_url=imgs.length?absoluteUrl(imgs[imgs.length-1][1],src.url):"";seen.add(id);out.push(makeSignal(src,title,"",sku,.01,"penny",{date:last,last_seen:last,brand,image_url,reports,states,state_summary:summary,original_price:was,discount_pct:was>.01?Math.round((1-.01/was)*100):99}))}return out}
async function fetchExtra(src:any){const r=await fetch(src.url,{headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error(`${src.name} ${src.retailer} ${src.kind} returned ${r.status}`);const html=await r.text();let rows:any[]=[];if(src.parser==="upc-list")rows=parseUpcList(html,src);else if(src.parser==="pennycentral")rows=parsePennyCentral(html,src);else rows=parsePennyTree(html,src);if(!rows.length)throw Error(`${src.name} ${src.retailer} ${src.kind} returned no truthful identifiable rows`);return rows}
async function extraSignals(){if(extraCache&&Date.now()-extraCache.at<CACHE_MS)return{...extraCache.payload,cached:true};const settled=await Promise.allSettled(EXTRA_SOURCES.map(fetchExtra)),rows:any[]=[],source_status:any[]=[],warnings:string[]=[];settled.forEach((r,i)=>{const s=EXTRA_SOURCES[i];if(r.status==="fulfilled"){rows.push(...r.value);source_status.push({retailer:s.retailer,source:s.name,domain:s.domain,kind:s.kind,status:"PASS",products:r.value.length,adapter:s.parser})}else{const warning=r.reason instanceof Error?r.reason.message:String(r.reason);warnings.push(warning);source_status.push({retailer:s.retailer,source:s.name,domain:s.domain,kind:s.kind,status:"NO_MATCHING_PRODUCTS",products:0,warning})}});const payload={rows,source_status,warnings};extraCache={at:Date.now(),payload};return payload}
function summaryByRetailer(leads:any[]){const by:any={},penny:any={},near:any={},multi:any={};for(const l of leads){const r=clean(l.retailer)||"Unknown";by[r]=(by[r]||0)+1;if(l.deal_type==="penny")penny[r]=(penny[r]||0)+1;if(l.deal_type==="near_penny")near[r]=(near[r]||0)+1;if(Number(l.signal_source_count)>=2)multi[r]=(multi[r]||0)+1}return{by,penny,near,multi}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="GET"&&req.method!=="POST")return json(req,405,{error:"GET or POST required."});try{const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";if(!auth)return json(req,401,{error:"Sign in required."});const upstream=await fetch(`${BASE}/functions/v1/reseller-auto-leads`,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json"},body:"{}",signal:AbortSignal.timeout(40000)}),payload=await upstream.json().catch(()=>({}));if(!upstream.ok)return json(req,upstream.status,{error:payload?.error||payload?.message||"Candidate source unavailable."});const baseRows=Array.isArray(payload?.leads)?payload.leads:[];let extras:any={rows:[],source_status:[],warnings:[]};try{extras=await extraSignals()}catch(e){extras={rows:[],source_status:[],warnings:[e instanceof Error?e.message:String(e)]}}const leads=aggregate([...baseRows,...extras.rows]),stats=summaryByRetailer(leads),baseStatus=Array.isArray(payload?.source_status)?payload.source_status:[],warnings=[...(Array.isArray(payload?.warnings)?payload.warnings:[]),...extras.warnings];return json(req,200,{...payload,leads,count:leads.length,raw_count:baseRows.length+extras.rows.length,duplicate_count:Math.max(0,baseRows.length+extras.rows.length-leads.length),by_retailer:stats.by,penny_by_retailer:stats.penny,near_penny_by_retailer:stats.near,multi_source_by_retailer:stats.multi,source_status:[...baseStatus,...extras.source_status],warnings,dedupe_version:DEDUPE_VERSION,signal_version:SIGNAL_VERSION,signal_rule:"Sources merge into one product card by retailer + UPC/SKU and strong normalized title aliases. Independent domains count once toward confidence.",local_truth_rule:"A store/web price never deletes a penny lead. LOCAL $0.01 is reserved for exact store-bound $0.01 evidence; otherwise the result is check history and the physical UPC scan remains final hunt authority.",supplemental_source_count:EXTRA_SOURCES.length})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});
