import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const norm=(v:unknown)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();

function eff(p:any){const qty=Math.max(1,Number(p.required_qty||1)),shelf=Math.max(0,Number(p.shelf_price||0))*qty,sav=Math.max(0,Number(p.sale_discount||0))+Math.max(0,Number(p.store_coupon||0))+Math.max(0,Number(p.manufacturer_coupon||0))+Math.max(0,Number(p.rebate||0))+Math.max(0,Number(p.loyalty_value||0));return Math.max(0,shelf-sav)}
function combos<T>(a:T[],max:number){const out:T[][]=[];const rec=(start:number,cur:T[])=>{if(cur.length){out.push([...cur]);if(cur.length>=max)return;}for(let i=start;i<a.length;i++){cur.push(a[i]);rec(i+1,cur);cur.pop()}};rec(0,[]);return out}
function optimize(items:any[],prices:any[],maxStores:number,travelCost:number){const stores=[...new Set(prices.map(x=>String(x.store||'').trim()).filter(Boolean))].slice(0,10);let best:any=null;for(const set of combos(stores,Math.max(1,Math.min(maxStores,4)))){let subtotal=0,missing:any[]=[],chosen:any[]=[];for(const item of items){const key=norm(item.item_name||item.name);const candidates=prices.filter(p=>set.includes(String(p.store||'').trim())&&(norm(p.item_name).includes(key)||key.includes(norm(p.item_name))));if(!candidates.length){if(item.required!==false)missing.push(item);continue;}candidates.sort((a,b)=>eff(a)-eff(b));const p=candidates[0],cost=eff(p)*Math.max(1,Number(item.quantity||1));subtotal+=cost;chosen.push({item:item.item_name||item.name,store:p.store,cost:Number(cost.toFixed(2)),shelf:Number(p.shelf_price||0),savings:Number((Number(p.sale_discount||0)+Number(p.store_coupon||0)+Number(p.manufacturer_coupon||0)+Number(p.rebate||0)+Number(p.loyalty_value||0)).toFixed(2)),confidence:p.confidence||'medium',source_note:p.source_note||''})}if(missing.length)continue;const travel=set.reduce((n,s)=>{const d=prices.filter(p=>String(p.store||'').trim()===s).map(p=>Number(p.distance_miles||0)).filter(Number.isFinite);return n+(d.length?Math.min(...d)*2*travelCost:0)},0);const total=subtotal+travel;const cand={stores:set,items:chosen,subtotal:Number(subtotal.toFixed(2)),travel:Number(travel.toFixed(2)),total:Number(total.toFixed(2)),savings:Number(chosen.reduce((n,x)=>n+x.savings,0).toFixed(2))};if(!best||cand.total<best.total)best=cand;}return best}

function aliases(query:string){const q=norm(query),out=[q];if(q.includes('ice tea'))out.push(q.replace(/\bice tea\b/g,'iced tea'));if(q.includes('iced tea'))out.push(q.replace(/\biced tea\b/g,'ice tea'));return[...new Set(out.filter(Boolean))]}
function badContext(query:string,title:string){const q=norm(query),t=norm(title);if(q==='milk'||q==='whole milk'||q==='2 milk'||q==='1 milk'||q==='skim milk'){if(/\b(?:chocolate|candy|bar|bars|morsel|morsels|cookie|cookies|powder|formula|protein|shake|almond|oat|soy|coconut|condensed|evaporated)\b/.test(t))return true}if(q==='dog food'&&/\b(?:storage|container|bowl|scoop|mat|toy|sign)\b/.test(t))return true;return false}
function matchScore(query:string,title:string){const t=norm(title);if(!t||badContext(query,title))return 0;let best=0;for(const q of aliases(query)){if(!q)continue;if(t===q)best=Math.max(best,100);if(t.includes(q))best=Math.max(best,90);const qt=q.split(' ').filter(Boolean),tt=new Set(t.split(' ').filter(Boolean));if(qt.length===1&&qt[0].length>=3&&tt.has(qt[0]))best=Math.max(best,60);else if(qt.length>=2&&qt.every(x=>tt.has(x)))best=Math.max(best,75)}return best}
function packageOz(title:string){const t=norm(title);if(/\bhalf gallon\b|\b0 5\s*gal\b/.test(t))return 64;if(/\b1\s*gal\b|\b1 gallon\b|\bgallon\b/.test(t))return 128;const m=t.match(/\b([0-9]+(?:\.[0-9]+)?)\s*(?:fl\s*oz|fluid ounces?)\b/);return m?Number(m[1]):null}
function dealMeta(row:any,item:string){const terms=String(row.deal_terms||''),payload=row.payload||{},buy=Number(row.buy_price),retail=Number(row.retail_price),q=norm(item);let qty=Number(payload.deal_quantity||0)||1,effective=Number(payload.effective_each);const multi=terms.match(/(\d+)\s*for\s*\$\s*([0-9]+(?:\.[0-9]{1,2})?)/i);if(multi){qty=Math.max(1,Number(multi[1]));effective=Number(multi[2])/qty}else{const bogo=terms.match(/buy\s*(\d+)\D+get\s*(\d+)\s*free/i);if(bogo){qty=Number(bogo[1])+Number(bogo[2]);const scope=String(payload.deal_price_scope||'').toLowerCase();if(scope==='bundle_total'&&Number.isFinite(buy))effective=buy/qty;else if(!Number.isFinite(effective)&&Number.isFinite(buy))effective=buy;else if(!Number.isFinite(effective)&&Number.isFinite(retail))effective=retail*Number(bogo[1])/qty}}
  if(!Number.isFinite(effective)&&Number.isFinite(buy))effective=buy;const oz=packageOz(String(row.title||''));const perGal=(q==='milk'&&oz&&Number.isFinite(effective))?effective*128/oz:null;return{deal_quantity:qty,effective_each:Number.isFinite(effective)?Number(effective.toFixed(2)):null,package_oz:oz,price_per_gallon:Number.isFinite(perGal)?Number(perGal!.toFixed(2)):null,comparison_price:Number.isFinite(perGal)?perGal:(Number.isFinite(effective)?effective:99999)} }
function confidence(row:any){const v=String(row?.payload?.source_confidence||'').toLowerCase();if(v==='local_store_verified')return{label:'LOCAL STORE VERIFIED',rank:4};if(v==='retailer_current')return{label:'RETAILER CURRENT · VERIFY LOCAL',rank:3};if(v==='public_ad_candidate')return{label:'PUBLIC AD · VERIFY LOCAL',rank:2};if(row.source_kind==='public_offer')return{label:'PUBLIC OFFER · VERIFY LOCAL',rank:2};return{label:'SAVED H38 DEAL · VERIFY LOCAL',rank:1}}
function displayTitle(row:any,meta:any){const title=String(row.title||''),terms=String(row.deal_terms||'').trim(),source=String(row?.payload?.source_confidence||'').toLowerCase();if(source!=='retailer_current'||!terms||/^current\s+(?:retailer|online)/i.test(terms))return title;if(norm(title).includes(norm(terms).slice(0,12)))return title;return `${title} — ${terms}`.slice(0,520)}
async function refreshPublic(url:string,service:string,items:any[]){try{const r=await fetch(`${url}/functions/v1/h38-coupon-public-refresh`,{method:'POST',headers:{Authorization:`Bearer ${service}`,apikey:service,'content-type':'application/json'},body:JSON.stringify({items}),signal:AbortSignal.timeout(26000)});const body=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,...body}}catch(e){return{ok:false,status:0,error:e instanceof Error?e.message:String(e)}}}

async function savedMatches(admin:any,items:any[]){
  const names=items.map(x=>String(x?.item_name||x?.name||x||'').trim()).filter(x=>x.length>=2).slice(0,30);
  if(!names.length)return[];
  const [savedQ,offerQ]=await Promise.all([
    admin.from('reseller_hunt_cache').select('canonical_key,retailer,title,upc,sku,buy_price,retail_price,image_url,source_url,deal_type,penny_sort_at').eq('active',true).gt('buy_price',0).order('penny_sort_at',{ascending:false}).limit(600),
    admin.from('coupon_public_offer_cache').select('canonical_key,retailer,title,item_name,buy_price,retail_price,source_url,deal_terms,evidence_scope,observed_at,expires_at,payload').eq('active',true).limit(300)
  ]);
  if(savedQ.error)throw savedQ.error;if(offerQ.error)throw offerQ.error;
  const now=Date.now();
  const savedRows=(savedQ.data||[]).map((row:any)=>({...row,source_kind:'saved_h38_deal',payload:{}}));
  const offerRows=(offerQ.data||[]).filter((row:any)=>!row.expires_at||Date.parse(row.expires_at)>now).map((row:any)=>({canonical_key:row.canonical_key,retailer:row.retailer,title:row.title,upc:'',sku:'',buy_price:row.buy_price,retail_price:row.retail_price,image_url:'',source_url:row.source_url,deal_type:'public_offer',penny_sort_at:row.observed_at,deal_terms:row.deal_terms,evidence_scope:row.evidence_scope,payload:row.payload||{},source_kind:'public_offer',match_text:`${row.item_name||''} ${row.title||''}`}));
  const rows=[...offerRows,...savedRows],out:any[]=[];
  for(const item of names){
    const found=rows.map((row:any)=>{const score=matchScore(item,row.match_text||row.title),meta=dealMeta(row,item),conf=confidence(row);return{row,score,meta,conf}}).filter((x:any)=>x.score>0).sort((a:any,b:any)=>b.score-a.score||b.conf.rank-a.conf.rank||Number(a.meta.comparison_price)-Number(b.meta.comparison_price)||Number(a.row.buy_price||99999)-Number(b.row.buy_price||99999)).slice(0,10);
    for(const x of found){const effective=Number(x.meta.effective_each),original=Number(x.row.buy_price),shown=Number.isFinite(effective)?effective:original;out.push({...x.row,title:displayTitle(x.row,x.meta),offer_total_price:original,buy_price:Number.isFinite(shown)?Number(shown.toFixed(2)):x.row.buy_price,item_name:item,match_score:x.score,match_label:x.row.source_kind==='public_offer'?(x.score>=90?'CURRENT PUBLIC OFFER':'RELEVANT PUBLIC OFFER'):(x.score>=90?'STRONG SAVED MATCH':'POSSIBLE SAVED MATCH'),verification_status:x.conf.label,source_confidence:x.row?.payload?.source_confidence||'',deal_quantity:x.meta.deal_quantity,effective_each:x.meta.effective_each,package_oz:x.meta.package_oz,price_per_gallon:x.meta.price_per_gallon,comparison_price:Number.isFinite(x.meta.comparison_price)?Number(x.meta.comparison_price.toFixed(2)):null})}
  }
  const seen=new Set<string>();
  return out.filter((x:any)=>{const k=`${norm(x.item_name)}|${x.canonical_key}`;if(seen.has(k))return false;seen.add(k);return true;}).slice(0,100);
}


function amazonAsin(v:unknown){const s=String(v||'').trim();const direct=s.match(/^[A-Z0-9]{10}$/i);if(direct)return direct[0].toUpperCase();const m=s.match(/(?:\/dp\/|\/gp\/product\/|asin=)([A-Z0-9]{10})/i);return m?m[1].toUpperCase():''}
function amazonSearchUrl(name:string){return `https://www.amazon.com/s?k=${encodeURIComponent(name)}`}
function amazonOfferPrice(item:any){const listings=Array.isArray(item?.offersV2?.listings)?item.offersV2.listings:[];for(const l of listings){const n=Number(l?.price?.money?.amount);if(Number.isFinite(n)&&n>0)return{price:n,listing:l}}return null}
async function amazonAccessToken(clientId:string,clientSecret:string){const r=await fetch('https://api.amazon.com/auth/o2/token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({grant_type:'client_credentials',client_id:clientId,client_secret:clientSecret,scope:'creatorsapi::default'}),signal:AbortSignal.timeout(12000)});const b=await r.json().catch(()=>({}));if(!r.ok||!b?.access_token)throw new Error(`Amazon token failed (${r.status})`);return String(b.access_token)}
async function amazonWatchMatches(items:any[]){
  const watches=items.filter(x=>String(x?.source||'all').toLowerCase()==='amazon').slice(0,20);
  const clientId=String(Deno.env.get('AMAZON_CREATORS_CLIENT_ID')||''),clientSecret=String(Deno.env.get('AMAZON_CREATORS_CLIENT_SECRET')||''),partnerTag=String(Deno.env.get('AMAZON_ASSOCIATE_TAG')||''),marketplace=String(Deno.env.get('AMAZON_MARKETPLACE')||'www.amazon.com');
  const configured=!!(clientId&&clientSecret&&partnerTag);
  if(!watches.length)return{configured,matches:[],checked:0};
  if(!configured)return{configured:false,matches:[],checked:0,error:'AMAZON_CREATORS_NOT_CONFIGURED'};
  const token=await amazonAccessToken(clientId,clientSecret),out:any[]=[];
  for(const w of watches){
    const name=String(w?.item_name||w?.name||'').trim(),asin=amazonAsin(w?.source_ref||w?.source_url||'');
    if(!name&&!asin)continue;
    const op=asin?'getItems':'searchItems';
    const payload:any={marketplace,partnerTag,resources:['itemInfo.title','images.primary.medium','offersV2.listings.price']};
    if(asin){payload.itemIds=[asin];payload.itemIdType='ASIN'}else{payload.keywords=name;payload.searchIndex='All';payload.itemCount=3}
    try{
      const r=await fetch(`https://creatorsapi.amazon/catalog/v1/${op}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json','x-marketplace':marketplace},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});
      const b=await r.json().catch(()=>({}));
      if(!r.ok)continue;
      const rows=(b?.itemsResult?.items||b?.searchResult?.items||[]).slice(0,3);
      for(const item of rows){
        const offer=amazonOfferPrice(item);if(!offer)continue;
        const title=String(item?.itemInfo?.title?.displayValue||item?.itemInfo?.title?.displayValue||name||'Amazon item'),itemAsin=String(item?.asin||asin||'').toUpperCase(),price=Number(offer.price),basis=Number(offer.listing?.price?.savingBasis?.money?.amount);
        out.push({canonical_key:`amazon:${itemAsin||norm(title)}`,retailer:'Amazon',title,item_name:name||title,upc:'',sku:itemAsin,buy_price:Number(price.toFixed(2)),retail_price:Number.isFinite(basis)?Number(basis.toFixed(2)):price,image_url:String(item?.images?.primary?.medium?.url||''),source_url:String(item?.detailPageURL||(itemAsin?`https://www.amazon.com/dp/${itemAsin}`:amazonSearchUrl(name))),deal_type:'amazon_watch',penny_sort_at:new Date().toISOString(),source_kind:'amazon',source_confidence:'amazon_creators_api',verification_status:'AMAZON CURRENT',match_label:'AMAZON CURRENT',match_score:asin?100:90,offer_total_price:Number(price.toFixed(2)),effective_each:Number(price.toFixed(2)),comparison_price:Number(price.toFixed(2)),watch_id:String(w?.id||'')});
      }
    }catch{}
  }
  return{configured:true,matches:out,checked:watches.length};
}


function htmlText(v:unknown){return String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim()}
function searchUrl(v:string){try{let s=String(v||'').replace(/&amp;/g,'&');if(s.startsWith('//'))s='https:'+s;const u=new URL(s);if(u.hostname.includes('duckduckgo.com')){const x=u.searchParams.get('uddg');if(x)return decodeURIComponent(x)}return u.toString()}catch{return String(v||'')}}
function priceFromText(v:string){const m=String(v||'').match(/\$\s*([0-9]{1,5}(?:,[0-9]{3})*(?:\.[0-9]{2})?)/);if(!m)return null;const n=Number(m[1].replace(/,/g,''));return Number.isFinite(n)&&n>0?n:null}
function discountFromText(v:string){const m=String(v||'').match(/(?:save\s+)?([0-9]{1,2})\s*%\s*(?:off)?/i);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)&&n>0&&n<100?n:null}
function dealSignal(v:string){const s=String(v||'').toLowerCase();if(/lightning deal/.test(s))return 'Lightning Deal';if(/prime exclusive|prime deal/.test(s))return 'Prime Deal';if(/limited time deal/.test(s))return 'Limited Time Deal';if(/best deal/.test(s))return 'Best Deal';if(/coupon/.test(s))return 'Coupon';if(/promo(?:tion| code)?/.test(s))return 'Promotion';if(/prime day|big deal days|black friday|cyber monday|big spring sale/.test(s))return 'Special Deal Event';return ''}
function discoveryKind(url:string,text:string){const u=String(url||'').toLowerCase(),t=String(text||'').toLowerCase();if(/amazon\.com\/(?:dp\/|gp\/product\/)/.test(u))return 'product';if(/coupon/.test(u+t))return 'coupon';if(/aboutamazon\.com|prime day|big deal days|black friday|cyber monday|big spring sale/.test(u+t))return 'event';return 'search'}
function discoveryScore(x:any,q:string){let s=0;const text=norm(`${x.title||''} ${x.snippet||''}`),qq=norm(q);if(x.result_kind==='product')s+=35;if(x.signal)s+=25;if(Number(x.discount_percent)>=20)s+=Math.min(40,Number(x.discount_percent));if(x.price!=null)s+=10;if(qq&&text.includes(qq))s+=30;if(/amazon\.com/.test(String(x.source_url||'')))s+=10;return s}
async function webGet(url:string,timeout=12000){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (Linux; Android 14; H38Deals/3.1) AppleWebKit/537.36 Chrome/124 Safari/537.36','accept-language':'en-US,en;q=0.9','accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(timeout)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}
async function duckSearch(q:string){try{const html=await webGet('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),10000),out:any[]=[];const re=/<a[^>]*class=["'][^"']*result__a[^"']*["'][^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]{0,1800}?(?:class=["'][^"']*result__snippet[^"']*["'][^>]*>([\s\S]*?)<\/(?:a|div|span)>)/gi;for(const m of html.matchAll(re)){const url=searchUrl(m[1]),title=htmlText(m[2]),snippet=htmlText(m[3]||'');if(!/^https:\/\//.test(url)||!title)continue;out.push({source:'duckduckgo',title,snippet,source_url:url})}return out.slice(0,12)}catch{return[]}}
async function bingSearch(q:string){try{const html=await webGet('https://www.bing.com/search?q='+encodeURIComponent(q),10000),out:any[]=[];const re=/<li[^>]*class=["'][^"']*b_algo[^"']*["'][^>]*>([\s\S]*?)<\/li>/gi;for(const m of html.matchAll(re)){const block=m[1],a=block.match(/<h2[^>]*>\s*<a[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;const url=searchUrl(a[1]),title=htmlText(a[2]),p=block.match(/<p[^>]*>([\s\S]*?)<\/p>/i),snippet=htmlText(p?.[1]||'');if(!/^https:\/\//.test(url)||!title)continue;out.push({source:'bing',title,snippet,source_url:url})}return out.slice(0,12)}catch{return[]}}
function amazonCardRows(html:string,itemName:string){const out:any[]=[];const parts=html.split(/data-asin=["']([A-Z0-9]{10})["']/i);for(let i=1;i<parts.length;i+=2){const asin=parts[i],block=parts[i+1].slice(0,9000),tm=block.match(/<h2[^>]*>[\s\S]*?<span[^>]*>([\s\S]*?)<\/span>/i)||block.match(/class=["'][^"']*a-size-medium[^"']*["'][^>]*>([\s\S]*?)<\/span>/i),title=htmlText(tm?.[1]||'');if(!title)continue;let price:any=null;const pm=block.match(/class=["'][^"']*a-price-whole[^"']*["'][^>]*>([0-9,]+)[\s\S]{0,250}?class=["'][^"']*a-price-fraction[^"']*["'][^>]*>([0-9]{2})/i);if(pm)price=Number(pm[1].replace(/,/g,'')+'.'+pm[2]);const text=htmlText(block).slice(0,1000),discount=discountFromText(text),signal=dealSignal(text);out.push({source:'amazon_web',title,snippet:text.slice(0,420),source_url:`https://www.amazon.com/dp/${asin}`,price:Number.isFinite(price)?price:null,discount_percent:discount,signal,result_kind:'product',item_name:itemName})}return out.slice(0,18)}
async function amazonSearchCards(q:string){try{const url='https://www.amazon.com/s?k='+encodeURIComponent(q||'deals'),html=await webGet(url,12000);if(/captcha|enter the characters you see below/i.test(html))return[];return amazonCardRows(html,q)}catch{return[]}}
async function amazonProductCard(url:string,itemName:string){try{if(!/^https:\/\/(?:www\.)?amazon\.com\/(?:dp\/|gp\/product\/)/i.test(url))return null;const html=await webGet(url,12000);if(/captcha|enter the characters you see below/i.test(html))return null;const title=htmlText((html.match(/id=["']productTitle["'][^>]*>([\s\S]*?)<\/span>/i)||[])[1]||itemName||'Amazon product');const plain=htmlText(html).slice(0,25000);let price=priceFromText(plain);const jsonPrice=html.match(/"priceAmount"\s*:\s*([0-9]+(?:\.[0-9]+)?)/i);if(jsonPrice)price=Number(jsonPrice[1]);return{source:'amazon_web',title,snippet:plain.slice(0,600),source_url:url,price,discount_percent:discountFromText(plain),signal:dealSignal(plain),result_kind:'product',item_name:itemName}}catch{return null}}
function discoveryQueries(w:any){const mode=String(w.watch_mode||'specific'),name=String(w.item_name||'').trim(),year=new Date().getUTCFullYear();if(mode==='discovery')return[`site:amazon.com/dp Amazon "limited time deal" coupon`,`site:amazon.com/gp/goldbox Amazon "Today's Deals"`,`site:aboutamazon.com Amazon Prime deals ${year}`];return[`site:amazon.com/dp ${name} Amazon deal coupon`,`site:amazon.com ${name} "limited time deal"`]}
async function discoverWebWatch(w:any){const name=String(w.item_name||'').trim(),mode=String(w.watch_mode||'specific'),rows:any[]=[];const queries=discoveryQueries(w);const [direct,cards,searchSets]=await Promise.all([amazonProductCard(String(w.source_url||''),name),amazonSearchCards(mode==='discovery'?'deals':name),Promise.all(queries.map(async q=>{const [ddg,bing]=await Promise.all([duckSearch(q),bingSearch(q)]);return[...ddg,...bing]}))]);if(direct)rows.push(direct);rows.push(...cards,...searchSets.flat());if(mode==='discovery'){rows.push({source:'amazon_link',title:"Amazon Today's Deals",snippet:'Browse Amazon deal pages, limited-time offers and current promotions.',source_url:'https://www.amazon.com/gp/goldbox/',price:null,discount_percent:null,signal:'Deals Hub',result_kind:'event',item_name:'Amazon Deal Scan'});rows.push({source:'amazon_link',title:'Amazon deal search',snippet:'Search Amazon for current discounted products.',source_url:'https://www.amazon.com/s?k=deals',price:null,discount_percent:null,signal:'Deal Search',result_kind:'search',item_name:'Amazon Deal Scan'})}else if(name){rows.push({source:'amazon_link',title:`Search Amazon for ${name}`,snippet:'Direct Amazon product search. Verify current price, seller, shipping and coupons before buying.',source_url:amazonSearchUrl(name),price:null,discount_percent:null,signal:'Product Search',result_kind:'search',item_name:name})}
  const allowed=(u:string)=>/https:\/\/(?:[^/]+\.)?(?:amazon\.com|aboutamazon\.com)\//i.test(u);const seen=new Set<string>(),q=mode==='discovery'?'':name;return rows.map((x:any)=>{const text=`${x.title||''} ${x.snippet||''}`,source_url=String(x.source_url||'');return{...x,source_url,price:x.price??priceFromText(text),discount_percent:x.discount_percent??discountFromText(text),signal:x.signal||dealSignal(text),result_kind:x.result_kind||discoveryKind(source_url,text)}}).filter((x:any)=>allowed(x.source_url)&&x.title).sort((a:any,b:any)=>discoveryScore(b,q)-discoveryScore(a,q)).filter((x:any)=>{const k=x.source_url.replace(/[?#].*$/,'');if(seen.has(k))return false;seen.add(k);return true}).slice(0,24)}
function discoveryMatch(row:any,watch:any){const p=Number(row.price),d=Number(row.discount_percent),mode=String(watch.watch_mode||'specific');return{canonical_key:`web:${row.id}`,retailer:'Amazon / Web',title:row.title,item_name:mode==='discovery'?'Amazon Deal Scan':watch.item_name,upc:'',sku:'',buy_price:Number.isFinite(p)?p:null,retail_price:null,image_url:'',source_url:row.source_url,deal_type:'amazon_web_discovery',penny_sort_at:row.observed_at,source_kind:'amazon_web',source_confidence:'web_search',verification_status:'WEB SEARCH · VERIFY ON AMAZON',match_label:row.signal||'WEB DISCOVERY',match_score:Number.isFinite(d)?Math.min(100,60+d):70,offer_total_price:Number.isFinite(p)?p:null,effective_each:Number.isFinite(p)?p:null,comparison_price:Number.isFinite(p)?p:null,discount_percent:Number.isFinite(d)?d:null,deal_terms:row.snippet||'',watch_id:watch.id,result_kind:row.result_kind}}
async function refreshWebDiscoveries(sb:any,admin:any,force:boolean){const {data:watches,error}=await sb.from('coupon_watch_rules').select('*').eq('enabled',true).eq('source','amazon');if(error)throw error;const now=Date.now(),due=(watches||[]).filter((w:any)=>force||!w.last_checked_at||now-Date.parse(w.last_checked_at)>=12*60*60*1000),refreshed:any[]=[];for(const w of due.slice(0,12)){const found=await discoverWebWatch(w);if(found.length){await admin.from('coupon_watch_discovery_cache').delete().eq('watch_id',w.id);const ins=found.map((x:any)=>({watch_id:w.id,user_id:w.user_id,source:x.source||'web',title:String(x.title||'').slice(0,500),snippet:String(x.snippet||'').slice(0,1600),source_url:String(x.source_url||'').slice(0,1600),price:x.price==null?null:(Number.isFinite(Number(x.price))?Number(x.price):null),discount_percent:x.discount_percent==null?null:(Number.isFinite(Number(x.discount_percent))?Number(x.discount_percent):null),signal:String(x.signal||'').slice(0,120),result_kind:String(x.result_kind||'search').slice(0,40),observed_at:new Date().toISOString(),expires_at:new Date(now+36*60*60*1000).toISOString()}));const iq=await admin.from('coupon_watch_discovery_cache').insert(ins);if(iq.error)throw iq.error}const best=found.map((x:any)=>x.price==null?NaN:Number(x.price)).filter(Number.isFinite).sort((a:number,b:number)=>a-b)[0]??null;await admin.from('coupon_watch_rules').update({last_checked_at:new Date().toISOString(),last_price:best,last_status:found.length?`Web scan found ${found.length} candidate${found.length===1?'':'s'}`:'Web scan completed; no new candidates'}).eq('id',w.id);refreshed.push({id:w.id,count:found.length})}
  const ids=(watches||[]).map((w:any)=>w.id);let cache:any[]=[];if(ids.length){const q=await sb.from('coupon_watch_discovery_cache').select('*').in('watch_id',ids).gt('expires_at',new Date().toISOString()).order('observed_at',{ascending:false}).limit(160);if(q.error)throw q.error;cache=q.data||[]}const byId=new Map((watches||[]).map((w:any)=>[w.id,w]));const matches=cache.map((r:any)=>discoveryMatch(r,byId.get(r.watch_id)||{}));return{matches,refreshed,due_count:due.length,total_watches:(watches||[]).length,next_refresh_hours:12}}
async function authenticatedUserId(sb:any,token:string){
  try{
    const claims=await sb.auth.getClaims(token),sub=String(claims?.data?.claims?.sub||'').trim();
    if(!claims?.error&&sub)return sub;
  }catch{}
  for(let attempt=0;attempt<2;attempt++){
    try{const {data:{user},error}=await sb.auth.getUser(token);if(!error&&user?.id)return String(user.id)}catch{}
    if(attempt===0)await new Promise(resolve=>setTimeout(resolve,200));
  }
  return '';
}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');if(!token)return json({error:'AUTH_REQUIRED'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}}),userId=await authenticatedUserId(sb,token);if(!userId)return json({error:'AUTH_REQUIRED'},401);const {data:ent}=await sb.from('h38_product_entitlements').select('active,expires_at').eq('user_id',userId).eq('product_key','coupon').maybeSingle();if(!ent?.active||(ent.expires_at&&Date.parse(ent.expires_at)<=Date.now()))return json({error:'PRODUCT_LOCKED',product:'coupon'},403);const body=await req.json().catch(()=>({}));const action=String(body.action||'optimize');
if(action==='web_discover'){const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),out=await refreshWebDiscoveries(sb,admin,!!body.force);return json({ok:true,...out,source:'h38_amazon_web_discovery_v1',warning:'Web-search results are best-effort. Confirm final Amazon price, seller, shipping, coupon eligibility and deal timing before buying.'});}
if(action==='matches'){const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),items=Array.isArray(body.items)?body.items:[],regularItems=items.filter((x:any)=>String(x?.source||'all').toLowerCase()!=='amazon');const refresh=regularItems.length?await refreshPublic(url,service,regularItems):{ok:true,skipped:true};const [regular,amazon]=await Promise.all([savedMatches(admin,regularItems),amazonWatchMatches(items)]);const matches=[...regular,...amazon.matches];return json({ok:true,matches,count:matches.length,source:'h38_coupon_public_saved_amazon_v1',refresh,amazon:{configured:amazon.configured,checked:amazon.checked,error:(amazon as any).error||''},warning:'Retailer-current public results and Amazon Creators API prices can change. Confirm final price, availability, shipping, seller, and coupon eligibility before buying.'});}
if(action==='optimize'){const items=Array.isArray(body.items)?body.items:[],prices=Array.isArray(body.prices)?body.prices:[];const best=optimize(items,prices,Number(body.max_stores||2),Number(body.travel_cost_per_mile||0.25));return json({ok:true,best,mode:body.mode||'practical'})}
if(action==='stack'){const p=body.price||{};return json({ok:true,stack:{shelf:Number(p.shelf_price||0),sale:Number(p.sale_discount||0),store_coupon:Number(p.store_coupon||0),manufacturer_coupon:Number(p.manufacturer_coupon||0),rebate:Number(p.rebate||0),loyalty:Number(p.loyalty_value||0),effective:Number(eff(p).toFixed(2)),confidence:p.confidence||'medium'}})}
if(action==='assistant'){const text=String(body.text||'');let max=2,mode='practical',budget=null;const m=text.match(/under\s*\$?([0-9]+(?:\.[0-9]+)?)/i);if(m)budget=Number(m[1]);if(/one store|single store/i.test(text)){max=1;mode='single_store'}else if(/two stores|2 stores/i.test(text)){max=2;mode='two_stores'}else if(/maximum|max savings/i.test(text)){max=4;mode='maximum_savings'}return json({ok:true,intent:{max_stores:max,mode,budget,brand_flexible:!/only|must be|brand matters/i.test(text)}})}
return json({error:'UNKNOWN_ACTION'},400)}catch(e){return json({error:'COUPON_API_ERROR',detail:e instanceof Error?e.message:String(e)},500)}});
