import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const norm=(v:unknown)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();

function eff(p:any){const qty=Math.max(1,Number(p.required_qty||1)),shelf=Math.max(0,Number(p.shelf_price||0))*qty,sav=Math.max(0,Number(p.sale_discount||0))+Math.max(0,Number(p.store_coupon||0))+Math.max(0,Number(p.manufacturer_coupon||0))+Math.max(0,Number(p.rebate||0))+Math.max(0,Number(p.loyalty_value||0));return Math.max(0,shelf-sav)}
function combos<T>(a:T[],max:number){const out:T[][]=[];const rec=(start:number,cur:T[])=>{if(cur.length){out.push([...cur]);if(cur.length>=max)return;}for(let i=start;i<a.length;i++){cur.push(a[i]);rec(i+1,cur);cur.pop()}};rec(0,[]);return out}
function optimize(items:any[],prices:any[],maxStores:number,travelCost:number){const stores=[...new Set(prices.map(x=>String(x.store||'').trim()).filter(Boolean))].slice(0,10);let best:any=null;for(const set of combos(stores,Math.max(1,Math.min(maxStores,4)))){let subtotal=0,missing:any[]=[],chosen:any[]=[];for(const item of items){const key=norm(item.item_name||item.name);const candidates=prices.filter(p=>set.includes(String(p.store||'').trim())&&(norm(p.item_name).includes(key)||key.includes(norm(p.item_name))));if(!candidates.length){if(item.required!==false)missing.push(item);continue;}candidates.sort((a,b)=>eff(a)-eff(b));const p=candidates[0],cost=eff(p)*Math.max(1,Number(item.quantity||1));subtotal+=cost;chosen.push({item:item.item_name||item.name,store:p.store,cost:Number(cost.toFixed(2)),shelf:Number(p.shelf_price||0),savings:Number((Number(p.sale_discount||0)+Number(p.store_coupon||0)+Number(p.manufacturer_coupon||0)+Number(p.rebate||0)+Number(p.loyalty_value||0)).toFixed(2)),confidence:p.confidence||'medium',source_note:p.source_note||''})}if(missing.length)continue;const travel=set.reduce((n,s)=>{const d=prices.filter(p=>String(p.store||'').trim()===s).map(p=>Number(p.distance_miles||0)).filter(Number.isFinite);return n+(d.length?Math.min(...d)*2*travelCost:0)},0);const total=subtotal+travel;const cand={stores:set,items:chosen,subtotal:Number(subtotal.toFixed(2)),travel:Number(travel.toFixed(2)),total:Number(total.toFixed(2)),savings:Number(chosen.reduce((n,x)=>n+x.savings,0).toFixed(2))};if(!best||cand.total<best.total)best=cand;}return best}

function aliases(query:string){const q=norm(query),out=[q];if(q.includes('ice tea'))out.push(q.replace(/\bice tea\b/g,'iced tea'));if(q.includes('iced tea'))out.push(q.replace(/\biced tea\b/g,'ice tea'));return[...new Set(out.filter(Boolean))]}
function badContext(query:string,title:string){const q=norm(query),t=norm(title);if(q==='milk'||q==='whole milk'||q==='2 milk'||q==='1 milk'||q==='skim milk'){if(/\b(?:chocolate|candy|bar|bars|morsel|morsels|cookie|cookies|powder|formula|protein|shake|almond|oat|soy|coconut|condensed|evaporated)\b/.test(t))return true}if(q==='dog food'&&/\b(?:storage|container|bowl|scoop|mat|toy|sign)\b/.test(t))return true;return false}
function matchScore(query:string,title:string){const t=norm(title);if(!t||badContext(query,title))return 0;let best=0;for(const q of aliases(query)){if(!q)continue;if(t===q)best=Math.max(best,100);if(t.includes(q))best=Math.max(best,90);const qt=q.split(' ').filter(Boolean),tt=new Set(t.split(' ').filter(Boolean));if(qt.length===1&&qt[0].length>=3&&tt.has(qt[0]))best=Math.max(best,60);else if(qt.length>=2&&qt.every(x=>tt.has(x)))best=Math.max(best,75)}return best}
function packageOz(title:string){const t=norm(title);if(/\bhalf gallon\b|\b0 5\s*gal\b/.test(t))return 64;if(/\b1\s*gal\b|\b1 gallon\b|\bgallon\b/.test(t))return 128;const m=t.match(/\b([0-9]+(?:\.[0-9]+)?)\s*(?:fl\s*oz|fluid ounces?)\b/);return m?Number(m[1]):null}
function dealMeta(row:any,item:string){const terms=String(row.deal_terms||''),payload=row.payload||{},buy=Number(row.buy_price),q=norm(item);let qty=Number(payload.deal_quantity||0)||1,effective=Number(payload.effective_each);const multi=terms.match(/(\d+)\s*for\s*\$\s*([0-9]+(?:\.[0-9]{1,2})?)/i);if(multi){qty=Math.max(1,Number(multi[1]));effective=Number(multi[2])/qty}else{const bogo=terms.match(/buy\s*(\d+)\D+get\s*(\d+)\s*free/i);if(bogo&&Number.isFinite(buy)){qty=Number(bogo[1])+Number(bogo[2]);effective=buy/qty}}
  if(!Number.isFinite(effective)&&Number.isFinite(buy))effective=buy;const oz=packageOz(String(row.title||''));const perGal=(q==='milk'&&oz&&Number.isFinite(effective))?effective*128/oz:null;return{deal_quantity:qty,effective_each:Number.isFinite(effective)?Number(effective.toFixed(2)):null,package_oz:oz,price_per_gallon:Number.isFinite(perGal)?Number(perGal!.toFixed(2)):null,comparison_price:Number.isFinite(perGal)?perGal:(Number.isFinite(effective)?effective:99999)} }
function confidence(row:any){const v=String(row?.payload?.source_confidence||'').toLowerCase();if(v==='local_store_verified')return{label:'LOCAL STORE VERIFIED',rank:4};if(v==='retailer_current')return{label:'RETAILER CURRENT · VERIFY LOCAL',rank:3};if(v==='public_ad_candidate')return{label:'PUBLIC AD · VERIFY LOCAL',rank:2};if(row.source_kind==='public_offer')return{label:'PUBLIC OFFER · VERIFY LOCAL',rank:2};return{label:'SAVED H38 DEAL · VERIFY LOCAL',rank:1}}
async function refreshPublic(url:string,service:string,items:any[]){try{const r=await fetch(`${url}/functions/v1/h38-coupon-public-refresh`,{method:'POST',headers:{Authorization:`Bearer ${service}`,apikey:service,'content-type':'application/json'},body:JSON.stringify({items}),signal:AbortSignal.timeout(26000)});const body=await r.json().catch(()=>({}));return{ok:r.ok,status:r.status,...body}}catch(e){return{ok:false,status:0,error:e instanceof Error?e.message:String(e)}}}

async function savedMatches(admin:any,items:any[]){
  const names=items.map(x=>String(x?.item_name||x?.name||x||'').trim()).filter(x=>x.length>=2).slice(0,30);
  if(!names.length)return[];
  const [savedQ,offerQ]=await Promise.all([
    admin.from('reseller_hunt_cache').select('canonical_key,retailer,title,upc,sku,buy_price,retail_price,image_url,source_url,deal_type,penny_sort_at').eq('active',true).gt('buy_price',0).order('penny_sort_at',{ascending:false}).limit(600),
    admin.from('coupon_public_offer_cache').select('canonical_key,retailer,title,item_name,buy_price,retail_price,source_url,deal_terms,evidence_scope,observed_at,expires_at,payload').eq('active',true).limit(300)
  ]);
  if(savedQ.error)throw savedQ.error;if(offerQ.error)throw offerQ.error;
  const now=Date.now();
  const savedRows=(savedQ.data||[]).map((row:any)=>({...row,source_kind:'saved_h38_deal',payload:{}}));
  const offerRows=(offerQ.data||[]).filter((row:any)=>!row.expires_at||Date.parse(row.expires_at)>now).map((row:any)=>({canonical_key:row.canonical_key,retailer:row.retailer,title:row.title,upc:'',sku:'',buy_price:row.buy_price,retail_price:row.retail_price,image_url:'',source_url:row.source_url,deal_type:'public_offer',penny_sort_at:row.observed_at,deal_terms:row.deal_terms,evidence_scope:row.evidence_scope,payload:row.payload||{},source_kind:'public_offer',match_text:`${row.item_name||''} ${row.title||''}`}));
  const rows=[...offerRows,...savedRows],out:any[]=[];
  for(const item of names){
    const found=rows.map((row:any)=>{const score=matchScore(item,row.match_text||row.title),meta=dealMeta(row,item),conf=confidence(row);return{row,score,meta,conf}}).filter((x:any)=>x.score>0).sort((a:any,b:any)=>b.score-a.score||b.conf.rank-a.conf.rank||Number(a.meta.comparison_price)-Number(b.meta.comparison_price)||Number(a.row.buy_price||99999)-Number(b.row.buy_price||99999)).slice(0,10);
    for(const x of found)out.push({...x.row,item_name:item,match_score:x.score,match_label:x.row.source_kind==='public_offer'?(x.score>=90?'CURRENT PUBLIC OFFER':'RELEVANT PUBLIC OFFER'):(x.score>=90?'STRONG SAVED MATCH':'POSSIBLE SAVED MATCH'),verification_status:x.conf.label,source_confidence:x.row?.payload?.source_confidence||'',deal_quantity:x.meta.deal_quantity,effective_each:x.meta.effective_each,package_oz:x.meta.package_oz,price_per_gallon:x.meta.price_per_gallon,comparison_price:Number.isFinite(x.meta.comparison_price)?Number(x.meta.comparison_price.toFixed(2)):null});
  }
  const seen=new Set<string>();
  return out.filter((x:any)=>{const k=`${norm(x.item_name)}|${x.canonical_key}`;if(seen.has(k))return false;seen.add(k);return true;}).slice(0,100);
}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');if(!token)return json({error:'AUTH_REQUIRED'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:uerr}=await sb.auth.getUser(token);if(uerr||!user)return json({error:'AUTH_REQUIRED'},401);const {data:ent}=await sb.from('h38_product_entitlements').select('active,expires_at').eq('user_id',user.id).eq('product_key','coupon').maybeSingle();if(!ent?.active||(ent.expires_at&&Date.parse(ent.expires_at)<=Date.now()))return json({error:'PRODUCT_LOCKED',product:'coupon'},403);const body=await req.json().catch(()=>({}));const action=String(body.action||'optimize');
if(action==='matches'){const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),items=Array.isArray(body.items)?body.items:[];const refresh=await refreshPublic(url,service,items);const matches=await savedMatches(admin,items);return json({ok:true,matches,count:matches.length,source:'h38_coupon_public_plus_saved_v2',refresh,warning:'Retailer-current public results are refreshed on demand for supported staple categories. Unless explicitly marked local-store verified, price, stock and coupon eligibility still require local verification.'});}
if(action==='optimize'){const items=Array.isArray(body.items)?body.items:[],prices=Array.isArray(body.prices)?body.prices:[];const best=optimize(items,prices,Number(body.max_stores||2),Number(body.travel_cost_per_mile||0.25));return json({ok:true,best,mode:body.mode||'practical'})}
if(action==='stack'){const p=body.price||{};return json({ok:true,stack:{shelf:Number(p.shelf_price||0),sale:Number(p.sale_discount||0),store_coupon:Number(p.store_coupon||0),manufacturer_coupon:Number(p.manufacturer_coupon||0),rebate:Number(p.rebate||0),loyalty:Number(p.loyalty_value||0),effective:Number(eff(p).toFixed(2)),confidence:p.confidence||'medium'}})}
if(action==='assistant'){const text=String(body.text||'');let max=2,mode='practical',budget=null;const m=text.match(/under\s*\$?([0-9]+(?:\.[0-9]+)?)/i);if(m)budget=Number(m[1]);if(/one store|single store/i.test(text)){max=1;mode='single_store'}else if(/two stores|2 stores/i.test(text)){max=2;mode='two_stores'}else if(/maximum|max savings/i.test(text)){max=4;mode='maximum_savings'}return json({ok:true,intent:{max_stores:max,mode,budget,brand_flexible:!/only|must be|brand matters/i.test(text)}})}
return json({error:'UNKNOWN_ACTION'},400)}catch(e){return json({error:'COUPON_API_ERROR',detail:e instanceof Error?e.message:String(e)},500)}});
