import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const norm=(v:unknown)=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const GENERIC_SINGLE=new Set(['milk','bread','eggs','egg','cheese','meat','beef','pork','chicken','water','soda','pop','coffee','rice','flour','sugar','butter','fruit','vegetables','vegetable']);

function eff(p:any){const qty=Math.max(1,Number(p.required_qty||1)),shelf=Math.max(0,Number(p.shelf_price||0))*qty,sav=Math.max(0,Number(p.sale_discount||0))+Math.max(0,Number(p.store_coupon||0))+Math.max(0,Number(p.manufacturer_coupon||0))+Math.max(0,Number(p.rebate||0))+Math.max(0,Number(p.loyalty_value||0));return Math.max(0,shelf-sav)}
function combos<T>(a:T[],max:number){const out:T[][]=[];const rec=(start:number,cur:T[])=>{if(cur.length){out.push([...cur]);if(cur.length>=max)return;}for(let i=start;i<a.length;i++){cur.push(a[i]);rec(i+1,cur);cur.pop()}};rec(0,[]);return out}
function optimize(items:any[],prices:any[],maxStores:number,travelCost:number){const stores=[...new Set(prices.map(x=>String(x.store||'').trim()).filter(Boolean))].slice(0,10);let best:any=null;for(const set of combos(stores,Math.max(1,Math.min(maxStores,4)))){let subtotal=0,missing:any[]=[],chosen:any[]=[];for(const item of items){const key=norm(item.item_name||item.name);const candidates=prices.filter(p=>set.includes(String(p.store||'').trim())&&(norm(p.item_name).includes(key)||key.includes(norm(p.item_name))));if(!candidates.length){if(item.required!==false)missing.push(item);continue;}candidates.sort((a,b)=>eff(a)-eff(b));const p=candidates[0],cost=eff(p)*Math.max(1,Number(item.quantity||1));subtotal+=cost;chosen.push({item:item.item_name||item.name,store:p.store,cost:Number(cost.toFixed(2)),shelf:Number(p.shelf_price||0),savings:Number((Number(p.sale_discount||0)+Number(p.store_coupon||0)+Number(p.manufacturer_coupon||0)+Number(p.rebate||0)+Number(p.loyalty_value||0)).toFixed(2)),confidence:p.confidence||'medium',source_note:p.source_note||''})}if(missing.length)continue;const travel=set.reduce((n,s)=>{const d=prices.filter(p=>String(p.store||'').trim()===s).map(p=>Number(p.distance_miles||0)).filter(Number.isFinite);return n+(d.length?Math.min(...d)*2*travelCost:0)},0);const total=subtotal+travel;const cand={stores:set,items:chosen,subtotal:Number(subtotal.toFixed(2)),travel:Number(travel.toFixed(2)),total:Number(total.toFixed(2)),savings:Number(chosen.reduce((n,x)=>n+x.savings,0).toFixed(2))};if(!best||cand.total<best.total)best=cand;}return best}

function matchScore(query:string,title:string){const q=norm(query),t=norm(title);if(!q||!t)return 0;if(t===q)return 100;const qt=q.split(' ').filter(Boolean),tt=new Set(t.split(' ').filter(Boolean));if(qt.length===1){const token=qt[0];if(GENERIC_SINGLE.has(token))return 0;return token.length>=4&&tt.has(token)?55:0;}if(t.includes(q))return 90;return qt.every(x=>tt.has(x))?70:0;}

async function savedMatches(admin:any,items:any[]){const names=items.map(x=>String(x?.item_name||x?.name||x||'').trim()).filter(x=>x.length>=2).slice(0,30);if(!names.length)return[];const q=await admin.from('reseller_hunt_cache').select('canonical_key,retailer,title,upc,sku,buy_price,retail_price,image_url,source_url,deal_type,penny_sort_at').eq('active',true).gt('buy_price',0).order('penny_sort_at',{ascending:false}).limit(600);if(q.error)throw q.error;const rows=q.data||[],out:any[]=[];for(const item of names){const found=rows.map((row:any)=>({row,score:matchScore(item,row.title)})).filter((x:any)=>x.score>0).sort((a:any,b:any)=>b.score-a.score).slice(0,5);for(const x of found){out.push({...x.row,item_name:item,match_score:x.score,match_label:x.score>=90?'STRONG SAVED MATCH':'POSSIBLE SAVED MATCH',verification_status:'SAVED H38 DEAL · VERIFY LOCAL'});}}const seen=new Set<string>();return out.filter((x:any)=>{const k=`${x.item_name}|${x.canonical_key}`;if(seen.has(k))return false;seen.add(k);return true;}).slice(0,60);}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');if(!token)return json({error:'AUTH_REQUIRED'},401);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}});const {data:{user},error:uerr}=await sb.auth.getUser(token);if(uerr||!user)return json({error:'AUTH_REQUIRED'},401);const {data:ent}=await sb.from('h38_product_entitlements').select('active,expires_at').eq('user_id',user.id).eq('product_key','coupon').maybeSingle();if(!ent?.active||(ent.expires_at&&Date.parse(ent.expires_at)<=Date.now()))return json({error:'PRODUCT_LOCKED',product:'coupon'},403);const body=await req.json().catch(()=>({}));const action=String(body.action||'optimize');
if(action==='matches'){const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const matches=await savedMatches(admin,Array.isArray(body.items)?body.items:[]);return json({ok:true,matches,count:matches.length,source:'h38_saved_deal_cache',warning:'These are saved H38 deal matches, not coupons and not proof of local stock. Verify local price, availability and coupon eligibility before buying.'});}
if(action==='optimize'){const items=Array.isArray(body.items)?body.items:[],prices=Array.isArray(body.prices)?body.prices:[];const best=optimize(items,prices,Number(body.max_stores||2),Number(body.travel_cost_per_mile||0.25));return json({ok:true,best,mode:body.mode||'practical'})}
if(action==='stack'){const p=body.price||{};return json({ok:true,stack:{shelf:Number(p.shelf_price||0),sale:Number(p.sale_discount||0),store_coupon:Number(p.store_coupon||0),manufacturer_coupon:Number(p.manufacturer_coupon||0),rebate:Number(p.rebate||0),loyalty:Number(p.loyalty_value||0),effective:Number(eff(p).toFixed(2)),confidence:p.confidence||'medium'}})}
if(action==='assistant'){const text=String(body.text||'');let max=2,mode='practical',budget=null;const m=text.match(/under\s*\$?([0-9]+(?:\.[0-9]+)?)/i);if(m)budget=Number(m[1]);if(/one store|single store/i.test(text)){max=1;mode='single_store'}else if(/two stores|2 stores/i.test(text)){max=2;mode='two_stores'}else if(/maximum|max savings/i.test(text)){max=4;mode='maximum_savings'}return json({ok:true,intent:{max_stores:max,mode,budget,brand_flexible:!/only|must be|brand matters/i.test(text)}})}
return json({error:'UNKNOWN_ACTION'},400)}catch(e){return json({error:'COUPON_API_ERROR',detail:e instanceof Error?e.message:String(e)},500)}});
