import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const TRANSCRIBE_MODEL=Deno.env.get("OPENAI_WALKTHROUGH_TRANSCRIBE_MODEL")||"gpt-4o-mini-transcribe";
const BUCKET="business-office-files";
const MAX_BYTES=24*1024*1024;
const BUILD="20260824-conversation-transcription-1";
type J=Record<string,unknown>;
type Client=ReturnType<typeof createClient>;
const text=(v:unknown,n=12000)=>String(v??"").replace(/Bearer\s+[A-Za-z0-9._-]+/gi,"Bearer [REDACTED]").trim().slice(0,n);
function cors(req:Request):HeadersInit{return{"access-control-allow-origin":req.headers.get("origin")||"*","access-control-allow-headers":req.headers.get("access-control-request-headers")||"authorization, apikey, content-type, x-client-info","access-control-allow-methods":"POST, OPTIONS","cache-control":"no-store","content-type":"application/json; charset=utf-8","vary":"Origin, Access-Control-Request-Headers"};}
const reply=(req:Request,status:number,payload:unknown)=>new Response(JSON.stringify(payload),{status,headers:cors(req)});
const bearer=(req:Request)=>text(req.headers.get("authorization"),5000).replace(/^Bearer\s+/i,"").trim();
function db(){if(!SUPABASE_URL||!SERVICE_KEY)throw Error("Supabase service configuration is unavailable.");return createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
async function readJson(res:Response):Promise<J>{const raw=await res.text();try{return raw?JSON.parse(raw):{};}catch{return{};}}
async function authorize(req:Request,service:Client,businessId:string){const token=bearer(req);if(!token)throw Error("Supabase Auth session is required.");const res=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:SERVICE_KEY,"x-client-info":BUILD},signal:AbortSignal.timeout(15000)});const user=await readJson(res);if(!res.ok||typeof user.id!=="string"||!user.id)throw Error("Supabase Auth session is invalid or expired.");const membership=await service.from("business_memberships").select("role,status").eq("business_id",businessId).eq("auth_user_id",user.id).eq("status","active").maybeSingle();if(membership.error)throw membership.error;if(!membership.data||!["owner","administrator","staff"].includes(String(membership.data.role)))throw Error("This role cannot transcribe business conversations.");return{id:user.id as string,role:String(membership.data.role)};}
async function meeting(service:Client,businessId:string,meetingId:string){const result=await service.from("business_records").select("record_key,payload").eq("business_id",businessId).eq("collection","meetings").eq("record_key",meetingId).eq("record_status","active").maybeSingle();if(result.error)throw result.error;if(!result.data)throw Error("The meeting record was not found in the active business.");return (result.data.payload&&typeof result.data.payload==="object"?result.data.payload:{}) as J;}
async function evidence(service:Client,businessId:string,meetingId:string,audioAttachmentId:string){const result=await service.from("business_records").select("record_key,payload").eq("business_id",businessId).eq("collection","documents").eq("record_key",audioAttachmentId).eq("record_status","active").maybeSingle();if(result.error)throw result.error;if(!result.data)throw Error("The meeting audio has not reached private storage yet.");const p=(result.data.payload&&typeof result.data.payload==="object"?result.data.payload:{}) as J;const savedMeeting=text(p["Meeting ID"]||p.meetingId,180),sourceType=text(p["Source Type"]||p.sourceType,100).toLowerCase(),evidenceType=text(p["Evidence Type"]||p.evidenceType,120),path=text(p["Storage Path"]||p.storagePath,1200),bucket=text(p["Storage Bucket"]||p.storageBucket||BUCKET,120),fileName=text(p["File Name"]||p.fileName||"conversation-audio.webm",220),mimeType=text(p["Mime Type"]||p.mimeType||"audio/webm",120),fileSize=Number(p["File Size"]||p.fileSize||0),segmentId=text(p["Meeting Segment ID"]||p.meetingSegmentId,180),provenance=text(p["Evidence Provenance"]||p.evidenceProvenance||"RECORDED_AUDIO",80);if(savedMeeting!==meetingId||sourceType!=="meeting")throw Error("The requested audio does not belong to this meeting.");if(!/Conversation Audio|Dictated Recollection Audio/i.test(evidenceType))throw Error("The requested document is not meeting audio evidence.");if(!path||!path.startsWith(`${businessId}/`))throw Error("The private meeting audio storage path is invalid.");if(fileSize>MAX_BYTES)throw Error("This meeting audio is too large for automatic transcription. The original evidence remains saved privately.");return{path,bucket,fileName,mimeType,fileSize,segmentId,provenance,evidenceType};}
async function attempt(blob:Blob,fileName:string,mimeType:string,model:string){const form=new FormData();form.append("file",new File([blob],fileName,{type:mimeType||blob.type||"audio/webm"}));form.append("model",model);form.append("response_format","json");form.append("language","en");const res=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`},body:form,signal:AbortSignal.timeout(120000)});const payload=await readJson(res);return{ok:res.ok,text:text(payload.text,24000),message:text((payload.error as J|undefined)?.message||payload.message||`OpenAI transcription returned ${res.status}.`,3000)};}
async function transcribe(service:Client,e:{path:string,bucket:string,fileName:string,mimeType:string}){const downloaded=await service.storage.from(e.bucket).download(e.path);if(downloaded.error||!downloaded.data)throw Error(downloaded.error?.message||"The private meeting audio could not be downloaded.");if(downloaded.data.size>MAX_BYTES)throw Error("This meeting audio is too large for automatic transcription. The original evidence remains saved privately.");const first=await attempt(downloaded.data,e.fileName,e.mimeType,TRANSCRIBE_MODEL);if(first.ok)return{transcript:first.text,model:TRANSCRIBE_MODEL,recovered:false};const media=/corrupt|unsupported|audio file|decode|format/i.test(first.message);if(media&&TRANSCRIBE_MODEL!=="whisper-1"){const fallback=await attempt(downloaded.data,e.fileName,e.mimeType,"whisper-1");if(fallback.ok)return{transcript:fallback.text,model:"whisper-1",recovered:true};throw Error(fallback.message);}throw Error(first.message);}
function segmentList(payload:J){return Array.isArray(payload.segments)?payload.segments.filter(x=>x&&typeof x==="object") as J[]:[];}
function rebuildTranscript(segments:J[]){return segments.map(segment=>text(segment.transcript||segment.text,12000)).filter(Boolean).join("\n\n").slice(0,48000);}
async function save(service:Client,businessId:string,meetingId:string,userId:string,payload:J,audioAttachmentId:string,segmentId:string,provenance:string,transcript:string,model:string){const segments=segmentList(payload);let found=false;const updatedSegments=segments.map((segment,index)=>{const sid=text(segment.segmentId||segment.id,180);const attachment=text(segment.audioAttachmentId,180);if((segmentId&&sid===segmentId)||(!segmentId&&attachment===audioAttachmentId)){found=true;return{...segment,segmentId:sid||segmentId||`SEG-${index+1}`,sourceType:text(segment.sourceType||provenance,80)||provenance,audioAttachmentId,transcript,transcriptionStatus:"COMPLETE",transcriptionModel:model,transcribedAt:new Date().toISOString()};}return segment;});if(!found)updatedSegments.push({segmentId:segmentId||`SEG-${crypto.randomUUID()}`,kind:"audio",sourceType:provenance,audioAttachmentId,transcript,transcriptionStatus:"COMPLETE",transcriptionModel:model,createdAt:new Date().toISOString()});const next={...payload,segments:updatedSegments,transcript:rebuildTranscript(updatedSegments),sourceTypes:Array.from(new Set(updatedSegments.map(s=>text(s.sourceType,80)).filter(Boolean))),transcriptionStatus:"COMPLETE",updatedAt:new Date().toISOString(),"Updated Time":new Date().toISOString(),ownerReviewStatus:text(payload.ownerReviewStatus,80)||"REQUIRED"};const update=await service.from("business_records").update({payload:next,updated_by:userId,updated_at:new Date().toISOString()}).eq("business_id",businessId).eq("collection","meetings").eq("record_key",meetingId).eq("record_status","active");if(update.error)throw update.error;return next;}
async function proof(service:Client,businessId:string,userId:string,meetingId:string,audioAttachmentId:string,sourceType:string,model:string,recovered:boolean){const result=await service.from("business_proof_log").insert({business_id:businessId,actor_user_id:userId,action_type:"MEETING_TRANSCRIBED",entity_type:"Meeting",entity_id:null,result:"PASS",details:{meetingId,audioAttachmentId,sourceType,transcriptionModel:model,recovered,ownerReviewRequired:true,externalActionOccurred:false,build:BUILD},external_action_occurred:false});if(result.error)console.warn("Meeting transcription proof log:",result.error.message);}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return reply(req,200,{status:"PASS",build:BUILD});if(req.method!=="POST")return reply(req,405,{status:"FAIL",message:"POST is required.",build:BUILD});const service=db();let businessId="",meetingId="",audioAttachmentId="",userId="";try{const body=await req.json() as J;businessId=text(body.businessId,180);meetingId=text(body.meetingId,180);audioAttachmentId=text(body.audioAttachmentId,180);if(!businessId||!meetingId||!audioAttachmentId)throw Error("Business, meeting, and audio attachment are required.");const u=await authorize(req,service,businessId);userId=u.id;const current=await meeting(service,businessId,meetingId);const e=await evidence(service,businessId,meetingId,audioAttachmentId);const result=await transcribe(service,e);if(!result.transcript)throw Error("No spoken conversation was detected in that recording.");const saved=await save(service,businessId,meetingId,userId,current,audioAttachmentId,e.segmentId,e.provenance,result.transcript,result.model);await proof(service,businessId,userId,meetingId,audioAttachmentId,e.provenance,result.model,result.recovered);return reply(req,200,{status:"PASS",meetingId,audioAttachmentId,segmentId:e.segmentId,sourceType:e.provenance,transcript:result.transcript,transcriptionModel:result.model,meeting:saved,ownerReviewRequired:true,automaticApproval:false,automaticCustomerSending:false,automaticFinancialAction:false,build:BUILD});}catch(error){try{if(businessId)await service.from("business_error_log").insert({business_id:businessId,actor_user_id:userId||null,source:"supabase/functions/h38-conversation-transcription",error_code:"MEETING_TRANSCRIPTION_FAILED",message:text(error instanceof Error?error.message:error,4000),severity:"error",status:"open",context:{meetingId,audioAttachmentId,externalActionOccurred:false,build:BUILD}});}catch{}return reply(req,400,{status:"FAIL",message:text(error instanceof Error?error.message:error,4000),build:BUILD});}});
