import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const BUSINESS_ID="10b85a89-5834-436d-95b0-c6ee2eb335ad";
const REPOSITORY="rkrueth-maker/highway-38-solutions";
const WORKFLOW="Owner Maintenance Quote Regression";
const OWNER_ACTOR="rkrueth-maker";
const AUDIENCE="h38-owner-maintenance";
const BUILD="20260824-owner-maintenance-oidc-1";
const ALLOWED_ACTIONS=new Set(["status","seed","run","visual"]);
type J=Record<string,any>;
const txt=(v:any,max=12000)=>String(v??"").trim().slice(0,max);
const db=()=>createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(status:number,body:any)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
function bytes(value:string){const s=value.replace(/-/g,"+").replace(/_/g,"/"),pad=s+"=".repeat((4-s.length%4)%4),raw=atob(pad),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function decode(value:string){return JSON.parse(new TextDecoder().decode(bytes(value)));}
async function verify(token:string){const parts=token.split(".");if(parts.length!==3)throw new Error("GitHub OIDC token is malformed.");const header=decode(parts[0]),claims=decode(parts[1]);if(header.alg!=="RS256"||!header.kid)throw new Error("GitHub OIDC signing algorithm is not accepted.");const r=await fetch("https://token.actions.githubusercontent.com/.well-known/jwks",{signal:AbortSignal.timeout(15000)}),jwks=await r.json(),jwk=(jwks.keys||[]).find((k:J)=>k.kid===header.kid);if(!r.ok||!jwk)throw new Error("GitHub OIDC signing key is unavailable.");const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]),ok=await crypto.subtle.verify("RSASSA-PKCS1-v1_5",key,bytes(parts[2]),new TextEncoder().encode(`${parts[0]}.${parts[1]}`));if(!ok)throw new Error("GitHub OIDC signature is invalid.");const now=Math.floor(Date.now()/1000),aud=Array.isArray(claims.aud)?claims.aud:[claims.aud];if(claims.iss!=="https://token.actions.githubusercontent.com")throw new Error("GitHub OIDC issuer is invalid.");if(!aud.includes(AUDIENCE))throw new Error("GitHub OIDC audience is invalid.");if(Number(claims.exp||0)<=now||Number(claims.nbf||0)>now+30)throw new Error("GitHub OIDC token is expired or not active.");if(txt(claims.repository)!==REPOSITORY)throw new Error("GitHub OIDC repository is not authorized.");if(txt(claims.repository_owner)!=="rkrueth-maker")throw new Error("GitHub OIDC repository owner is not authorized.");if(txt(claims.actor)!==OWNER_ACTOR)throw new Error(`GitHub OIDC actor is not authorized: ${txt(claims.actor)}`);if(txt(claims.workflow)!==WORKFLOW)throw new Error(`GitHub OIDC workflow is not authorized: ${txt(claims.workflow)}`);if(!["push","pull_request","workflow_dispatch"].includes(txt(claims.event_name)))throw new Error("GitHub OIDC event is not authorized.");const ref=txt(claims.ref),head=txt(claims.head_ref);if(txt(claims.event_name)==="push"&&!["refs/heads/main","refs/heads/agent/quote-agent-walkthrough-acceptance-polish-20260823"].includes(ref))throw new Error(`GitHub OIDC branch is not authorized: ${ref}`);if(txt(claims.event_name)==="pull_request"&&head&&head!=="agent/quote-agent-walkthrough-acceptance-polish-20260823")throw new Error(`GitHub OIDC PR head is not authorized: ${head}`);return claims;}
async function shaHex(value:string){const digest=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return Array.from(digest).map(x=>x.toString(16).padStart(2,"0")).join("");}
async function firstOwner(s:any){const r=await s.from("business_memberships").select("auth_user_id").eq("business_id",BUSINESS_ID).eq("status","active").eq("role","owner").limit(1).maybeSingle();if(r.error||!r.data?.auth_user_id)throw r.error||new Error("Active H38 owner membership was not found.");return String(r.data.auth_user_id);}
Deno.serve(async req=>{if(req.method!=="POST")return json(405,{status:"FAIL",message:"POST required",build:BUILD});const oidc=txt(req.headers.get("x-h38-github-oidc"),12000);if(!oidc)return json(401,{status:"FAIL",message:"GitHub OIDC identity is required.",build:BUILD});let body:J={};try{body=await req.json();}catch{return json(400,{status:"FAIL",message:"JSON body required",build:BUILD});}const action=txt(body.action,80);if(!ALLOWED_ACTIONS.has(action))return json(403,{status:"FAIL",message:"Maintenance action is not allowed through GitHub OIDC.",build:BUILD});const s=db(),token=crypto.randomUUID()+crypto.randomUUID(),hash=await shaHex(token);try{const claims=await verify(oidc),owner=await firstOwner(s),expires=new Date(Date.now()+5*60*1000).toISOString(),ins=await s.from("business_records").upsert({business_id:BUSINESS_ID,collection:"ownerMaintenanceTokens",record_key:hash,payload:{"Token Hash":hash,"Scope":"quote regression","Enabled":true,"Expires At":expires,"Created For":"GitHub OIDC Quote Agent regression","GitHub Run ID":txt(claims.run_id,120),"GitHub Ref":txt(claims.ref,300)},record_status:"active",created_by:owner,updated_by:owner,updated_at:new Date().toISOString()},{onConflict:"business_id,collection,record_key"});if(ins.error)throw ins.error;const response=await fetch(`${SUPABASE_URL}/functions/v1/h38-owner-maintenance`,{method:"POST",headers:{"content-type":"application/json","x-h38-maintenance-token":token,Origin:"https://highway38solutions.com"},body:JSON.stringify(body),signal:AbortSignal.timeout(action==="visual"?170000:145000)}),raw=await response.text();let payload:any={};try{payload=JSON.parse(raw);}catch{payload={status:"FAIL",message:raw.slice(0,1200)}};return json(response.ok?200:response.status,{...payload,oidcGatewayBuild:BUILD,githubRunId:txt(claims.run_id,120),githubRef:txt(claims.ref,300)});}catch(e){return json(401,{status:"FAIL",message:txt(e,1600),build:BUILD});}finally{await s.from("business_records").delete().eq("business_id",BUSINESS_ID).eq("collection","ownerMaintenanceTokens").eq("record_key",hash);}});
