export const CANONICAL_IDENTITY_VERSION='retailer-upc-sku-bridge-v063';

export function clean(v){return String(v??'').replace(/\s+/g,' ').trim()}
export function decode(v){return String(v??'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&ndash;|&#8211;/gi,'–').replace(/&mdash;|&#8212;/gi,'—').replace(/&#(\d+);/g,(_,n)=>{try{return String.fromCodePoint(Number(n))}catch{return' '}})}
export function lines(html){return decode(String(html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'\n').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'\n').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(?:p|div|li|h[1-6]|tr|article|section|button|a|span|td|th)>/gi,'\n').replace(/<[^>]+>/g,' ')).split(/\r?\n/).map(clean).filter(Boolean)}
export function digits(v){return clean(v).replace(/\D/g,'')}
export function retailerKey(v){const s=clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(s.includes('home depot'))return'home depot';if(s.includes('dollar general'))return'dollar general';if(s.includes('dollar tree'))return'dollar tree';if(s.includes('family dollar'))return'family dollar';if(s.includes('lowe'))return'lowes';return s||'unknown'}
export function upcNorm(v){const d=digits(v).replace(/^0+/,'');return d.length>=6?d:''}
export function skuNorm(retailer,v){const r=retailerKey(retailer),raw=clean(v).toLowerCase(),d=digits(raw);if((r==='home depot'||r==='dollar general'||r==='dollar tree'||r==='family dollar')&&d.length>=4)return d.replace(/^0+/,'');return raw.replace(/[^a-z0-9]+/g,'')}
export function titleNorm(v){return clean(v).toLowerCase().replace(/\b(?:the|a|an)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim().slice(0,180)}
function usefulTitle(v){const s=clean(v);if(s.length<4||s.length>260)return false;return !/^(?:upc|sku|price|penny|clearance|today|yesterday|home depot deals?|dollar general penny|current weekly list|surprise penny|updated|posted)\b/i.test(s)&&!/^\$\s*\d/.test(s)}
function strongAliases(row){const r=retailerKey(row?.retailer),a=[],u=upcNorm(row?.upc||row?.gtin||row?.barcode),s=skuNorm(row?.retailer,row?.sku||row?.store_sku||row?.internet_number);if(u)a.push(`${r}|u:${u}`);if(s)a.push(`${r}|s:${s}`);return a}
export function aliases(row){const strong=strongAliases(row);if(strong.length)return strong;const r=retailerKey(row?.retailer),t=titleNorm(row?.title||row?.canonical_title);return t&&usefulTitle(row?.title||row?.canonical_title)?[`${r}|t:${t}`]:[]}
function sourceDomain(s){let d=clean(s?.domain).toLowerCase().replace(/^www\./,'');if(d)return d;try{return new URL(clean(s?.url)).hostname.toLowerCase().replace(/^www\./,'')}catch{return clean(s?.name).toLowerCase()}}
function rowSignal(row){return{name:clean(row?.signal_name||row?.source_name||'Source'),domain:sourceDomain({domain:row?.signal_domain,url:row?.signal_url||row?.source_url,name:row?.signal_name||row?.source_name}),url:clean(row?.signal_url||row?.source_url),kind:clean(row?.deal_type||'candidate'),observed_price:Number.isFinite(Number(row?.reported_penny_price))?Number(row.reported_penny_price):Number.isFinite(Number(row?.buy_price))?Number(row.buy_price):null,observed_at:clean(row?.signal_observed_at||row?.last_seen||row?.posted_date||'')}}
export function distinctSignals(list){const out=[],ix=new Map();for(const s0 of list||[]){if(!s0)continue;const s={...s0,domain:sourceDomain(s0)},k=s.domain||clean(s.name).toLowerCase();if(!k)continue;if(!ix.has(k)){ix.set(k,out.length);out.push(s);continue}const i=ix.get(k),old=out[i];out[i]={...old,...s,url:clean(s.url)||clean(old.url),observed_at:clean(s.observed_at)||clean(old.observed_at),observed_price:Number.isFinite(Number(s.observed_price))?Number(s.observed_price):old.observed_price}}return out}
function rank(row){const t=clean(row?.deal_type).toLowerCase();return(t==='penny'?200000:t==='near_penny'?100000:0)+(row?.deep_discount?10000:0)+Number(row?.source_priority||0)*10+(upcNorm(row?.upc)?6000:0)+(skuNorm(row?.retailer,row?.sku)?4000:0)+(clean(row?.image_url)?1000:0)+(usefulTitle(row?.title)?500:0)}
function explicitPennied(row){return clean(row?.pennied_at||row?.penny_start_date||row?.source_pennied_at)}
export function mergeRows(a,b){const winner=rank(b)>rank(a)?b:a,loser=winner===b?a:b,merged={...loser,...winner};merged.retailer=clean(winner.retailer||loser.retailer);merged.upc=clean(winner.upc||loser.upc||winner.gtin||loser.gtin||winner.barcode||loser.barcode);merged.sku=clean(winner.sku||loser.sku||winner.store_sku||loser.store_sku||winner.internet_number||loser.internet_number);merged.title=clean(winner.title||winner.canonical_title||loser.title||loser.canonical_title);merged.brand=clean(winner.brand||loser.brand);merged.image_url=clean(winner.image_url||loser.image_url);merged.pennied_at=explicitPennied(a)||explicitPennied(b)||'';merged.signal_sources=distinctSignals([...(Array.isArray(a?.signal_sources)?a.signal_sources:[]),rowSignal(a),...(Array.isArray(b?.signal_sources)?b.signal_sources:[]),rowSignal(b)]);merged.signal_source_count=merged.signal_sources.length;merged.source_domains=merged.signal_sources.map(s=>s.domain).filter(Boolean);merged.community_reports=Math.max(Number(a?.community_reports||0),Number(b?.community_reports||0));merged.community_states=Math.max(Number(a?.community_states||0),Number(b?.community_states||0));merged.original_price=Math.max(Number(a?.original_price||0),Number(b?.original_price||0));if(clean(a?.deal_type)==='penny'||clean(b?.deal_type)==='penny'||Number(a?.reported_penny_price)===.01||Number(b?.reported_penny_price)===.01){merged.deal_type='penny';merged.near_penny=false;merged.reported_penny_price=.01;merged.buy_price=.01}else if(clean(a?.deal_type)==='near_penny'||clean(b?.deal_type)==='near_penny'){merged.deal_type='near_penny';merged.near_penny=true}merged.posted_date=clean(winner.posted_date||loser.posted_date||winner.last_seen||loser.last_seen);merged.last_seen=clean(winner.last_seen||loser.last_seen||winner.posted_date||loser.posted_date);return merged}
function canonicalId(row){const r=retailerKey(row?.retailer),u=upcNorm(row?.upc),s=skuNorm(row?.retailer,row?.sku),t=titleNorm(row?.title||row?.canonical_title);if(r==='home depot'&&s)return`${r}|s:${s}`;if(u)return`${r}|u:${u}`;if(s)return`${r}|s:${s}`;return`${r}|t:${t}`}
function finalize(row){const x={...row};x.signal_sources=distinctSignals([...(Array.isArray(x.signal_sources)?x.signal_sources:[]),rowSignal(x)]);x.signal_source_count=x.signal_sources.length;x.source_domains=x.signal_sources.map(s=>s.domain).filter(Boolean);x.signal_confidence=x.signal_source_count>=3?'HIGH':x.signal_source_count>=2?'MEDIUM':'LOW';x.canonical_id=canonicalId(x);x.canonical_identity_version=CANONICAL_IDENTITY_VERSION;if(clean(x.deal_type)==='penny'){const start=explicitPennied(x);if(start){x.pennied_at=start;x.pennied_date_status='source_published';x.pennied_date_label=start}else{x.pennied_at='';x.penny_date='';x.pennied_date_status='not_published';x.pennied_date_label='Not published'}x.availability_label=`${x.signal_confidence} PENNY LEAD · ${x.signal_source_count} independent source${x.signal_source_count===1?'':'s'}. Physical UPC/register scan remains final local truth.`}return x}
export function aggregate(rows){const clusters=new Map(),clusterAliases=new Map(),aliasToId=new Map();let nextId=1;for(const raw of rows||[]){if(!raw||!clean(raw.retailer))continue;const row={...raw},aa=aliases(row);if(!aa.length)continue;const matches=[...new Set(aa.map(a=>aliasToId.get(a)).filter(Boolean))];let target;if(!matches.length){target=String(nextId++);clusters.set(target,row);clusterAliases.set(target,new Set(aa))}else{target=matches[0];let merged=clusters.get(target);const allAliases=new Set([...(clusterAliases.get(target)||[]),...aa]);for(const other of matches.slice(1)){merged=mergeRows(merged,clusters.get(other));for(const a of clusterAliases.get(other)||[])allAliases.add(a);clusters.delete(other);clusterAliases.delete(other)}merged=mergeRows(merged,row);for(const a of aliases(merged))allAliases.add(a);clusters.set(target,merged);clusterAliases.set(target,allAliases);for(const a of allAliases)aliasToId.set(a,target)}for(const a of clusterAliases.get(target)||[])aliasToId.set(a,target)}return[...clusters.values()].map(finalize).sort((a,b)=>rank(b)-rank(a))}
function makeSignal({retailer,name,domain,url,priority,title,upc='',sku='',date='',image_url=''}){return{id:`${retailerKey(retailer).replace(/\s+/g,'-')}:${upcNorm(upc)||skuNorm(retailer,sku)||titleNorm(title).replace(/\s+/g,'-').slice(0,80)}`,retailer,title:clean(title),upc:digits(upc),sku:clean(sku),buy_price:.01,reported_penny_price:.01,deep_discount:true,deal_type:'penny',near_penny:false,posted_date:clean(date),last_seen:clean(date),image_url:clean(image_url),source_name:name,source_url:url,source_priority:priority,signal_name:name,signal_domain:domain,signal_url:url,signal_observed_at:clean(date),signal_sources:[{name,domain,url,kind:'penny',observed_price:.01,observed_at:clean(date)}],availability_label:'Community penny signal; physical register scan remains final local truth.'}}
export function parsePennyGeneral(html,src={name:'PennyGeneral',domain:'pennygeneral.net',url:'https://pennygeneral.net/',retailer:'Dollar General',priority:132}){const x=lines(html),out=[],seen=new Set();let currentDate='';for(let i=0;i<x.length;i++){if(/^(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+20\d{2}$/i.test(x[i])){currentDate=x[i];continue}const title=clean(x[i]);if(!usefulTitle(title)||/^(?:UPC|SKU)$/i.test(title))continue;const block=x.slice(i+1,Math.min(x.length,i+12));let upc='',sku='',penny=false;for(let j=0;j<block.length;j++){if(/^UPC\s*:??$/i.test(block[j])&&block[j+1])upc=digits(block[j+1]);else{const m=block[j].match(/^UPC\s*:??\s*(\d{7,14})$/i);if(m)upc=digits(m[1])}if(/^SKU\s*:??$/i.test(block[j])&&block[j+1])sku=clean(block[j+1]);else{const m=block[j].match(/^SKU\s*:??\s*([A-Za-z0-9-]{4,24})$/i);if(m)sku=clean(m[1])}if(/^\$\s*0\.01\b/.test(block[j]))penny=true}const key=upcNorm(upc)||skuNorm(src.retailer,sku);if(!penny||!key||seen.has(key))continue;seen.add(key);out.push(makeSignal({...src,title,upc,sku,date:currentDate}))}return out}
export function parsePennyPinchinMom(html,src={name:"Penny Pinchin' Mom",domain:'pennypinchinmom.com',url:'https://pennypinchinmom.com/home-depot-penny-list/',retailer:'Home Depot',priority:130}){const x=lines(html),out=[],seen=new Set();let currentDate='';for(let i=0;i<x.length;i++){const dh=x[i].match(/Home Depot Deals?\s+for\s+(\d{1,2}\/\d{1,2}\/20\d{2})/i);if(dh){currentDate=dh[1];continue}let line=x[i],m=line.match(/^(.*?)\s*[—–-]\s*SKU\s*:\s*([0-9][0-9-]{4,24})\s*$/i);if(!m)m=line.match(/^(.*?)\s+SKU\s*:\s*([0-9][0-9-]{4,24})\s*$/i);let title='',sku='';if(m){title=clean(m[1]);sku=clean(m[2])}else{const sm=line.match(/^SKU\s*:\s*([0-9][0-9-]{4,24})$/i);if(sm){sku=clean(sm[1]);for(let j=i-1;j>=Math.max(0,i-3);j--){if(usefulTitle(x[j])){title=x[j];break}}}}const key=skuNorm(src.retailer,sku);if(!key||!usefulTitle(title)||seen.has(key))continue;seen.add(key);out.push(makeSignal({...src,title,sku,date:currentDate}))}return out}
