import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const ALLOWED=new Set(["ccf25333-47cd-42ca-a20b-cdbc63a8a695","6dd51b31-5974-4691-b8b8-83e5877528c0"]);
const U=Deno.env.get("SUPABASE_URL")||"",K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const O=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
type S={retailer:string,name:string,url:string,kind:string,priority:number,fallback?:boolean};
const P:S[]=[
 {retailer:"Dollar General",name:"RetailShout Penny List",url:"https://retailshout.com/latest-dollar-general-penny-items-near-you/",kind:"penny",priority:100},
 {retailer:"Dollar Tree",name:"RetailShout Penny List",url:"https://retailshout.com/latest-dollar-tree-penny-items-near-you/",kind:"penny",priority:100}
];
const R:S[]=[
 {retailer:"Home Depot",name:"Home Depot Daily Deals",url:"https://www.homedepot.com/daily-deals/",kind:"deal",priority:99,fallback:true},
 {retailer:"Home Depot",name:"Home Depot Tool Savings",url:"https://www.homedepot.com/b/Tool-Savings/N-5yc1vZ1z1zuqf",kind:"deal",priority:99,fallback:true},
 {retailer:"Menards",name:"Menards Ray's List",url:"https://www.menards.com/main/rayslist.html",kind:"in_store_bargain",priority:98,fallback:true},
 {retailer:"Ace Hardware",name:"Ace Clearance",url:"https://www.acehardware.com/clearance?pageSize=60",kind:"clearance",priority:94,fallback:true},
 {retailer:"Ace Hardware",name:"Ace Tool Deals",url:"https://www.acehardware.com/top-power-tool-deals",kind:"deal",priority:95,fallback:true},
 {retailer:"Walmart",name:"Walmart Rollbacks & Clearance",url:"https://www.walmart.com/shop/savings",kind:"clearance",priority:96,fallback:true},
 {retailer:"Lowe's",name:"Lowe's Tool Deals",url:"https://www.lowes.com/l/savings/tools-savings",kind:"deal",priority:96,fallback:true},
 {retailer:"Lowe's",name:"Lowe's Savings & Clearance",url:"https://www.lowes.com/l/savings",kind:"clearance",priority:94,fallback:true}
];
let C:{at:number,p:any}|null=null,I:Promise<any>|null=null;
function H(q:Request){const o=q.headers.get("origin")||"";return{"access-control-allow-origin":O.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"GET, POST, OPTIONS","content-type":"application/json; charset=utf-8","vary":"Origin"}}
function J(q:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:H(q)})}
async function uid(q:Request){const t=String(q.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!t)throw Error("Sign in required.");const r=await fetch(`${U}/auth/v1/user`,{headers:{authorization:`Bearer ${t}`,apikey:K}}),p=await r.json().catch(()=>({}));if(!r.ok||!p?.id)throw Error("Session expired.");return String(p.id)}
function dec(x:string){return x.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&ndash;/gi,"–").replace(/&mdash;/gi,"—").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)))}
function lines(h:string){return dec(h.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"\n").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"\n").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>|<\/div>|<\/li>|<\/h[1-6]>|<\/tr>|<\/article>|<\/section>/gi,"\n").replace(/<[^>]+>/g," ")).split(/\r?\n/).map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean)}
function slug(x:string){return x.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}
function title(x:string){return x.replace(/^\*\s*/,"").replace(/^Image:\s*/i,"").replace(/\s+/g," ").trim()}
function useful(x:string){x=title(x);return x.length>=10&&x.length<=190&&!/^(add|compare|shop now|view|sort|filter|all filters|price|brand|availability|category|get it fast|showing|load more|clear all|image|sponsored|free shipping|pickup|delivery|shipping|deals by|shop by|top categories)/i.test(x)&&!/^\$?\d+(\.\d{1,2})?$/.test(x)&&!/^was\s*\$?|^save\s*\$?/i.test(x)}
function hot(x:string){return /tool|battery|charger|drill|driver|impact|saw|nailer|grinder|sander|router|vacuum|compressor|generator|mower|blower|trimmer|chainsaw|pressure washer|storage|toolbox|workbench|ladder|grill|smoker|cooler|appliance|electronics|camera|speaker|headphone|tablet|laptop|tv|gaming|console|lego|outdoor power|snow blower|air conditioner|heater|dehumidifier|fan|lighting|faucet|fixture/i.test(x)}
function score(x:string,d=0,k="deal"){let s=72,t=x.toLowerCase();if(/milwaukee|dewalt|ryobi|ridgid|makita|bosch|kobalt|craftsman|metabo|greenworks|ego|weber|traeger|blackstone/.test(t))s+=9;if(/battery|charger|combo kit|tool kit|generator|mower|blower|trimmer|chainsaw|vacuum|compressor|storage|toolbox|workbench|grill|smoker|electronics|gaming|lego/.test(t))s+=8;if(k==="penny")s+=10;if(k==="in_store_bargain")s+=6;s+=Math.min(12,Math.max(0,d)/5);return Math.max(45,Math.min(99,Math.round(s)))}
function money(x:string){const m=x.replace(/,/g,"").match(/\$\s*(\d{1,6}(?:\.\d{1,2})?)/);return m?Number(m[1]):0}
function near(a:string[],i:number){let cur=0,was=0,disc=0,sku="";for(let j=i+1;j<=Math.min(a.length-1,i+10);j++){let x=a[j],m=x.match(/(?:Model#|Model #|Item #|SKU:?)\s*([A-Za-z0-9._-]+)/i);if(m&&!sku)sku=m[1];m=x.match(/(?:Save[^%]{0,40}|off\s*)\(?\s*(\d{1,2})\s*%\)?/i);if(m)disc=Math.max(disc,Number(m[1]));if(/^Was\b/i.test(x)){const p=money(x);if(p)was=p;continue}if(/^Save\b/i.test(x))continue;if(!cur){const p=money(x);if(p)cur=p}}if(!disc&&cur>0&&was>cur)disc=Math.round((1-cur/was)*100);return{cur,was,disc,sku}}
function penny(h:string,s:S){const a=lines(h),out:any[]=[];for(let i=0;i<a.length;i++){const dm=a[i].match(/^(?:Penny Date|Date Pennied):\s*(.+)$/i);if(!dm)continue;let t="";for(let j=i-1;j>=Math.max(0,i-6);j--)if(useful(a[j])){t=title(a[j]).replace(/^\d+[.)]\s*/,"");break}let sku="",upc="";for(let j=i+1;j<=Math.min(a.length-1,i+8);j++){const m=a[j].match(/SKU:\s*([A-Za-z0-9-]+).*?UPC:\s*([0-9]{7,14})/i);if(m){sku=m[1];upc=m[2];break}}if(t&&upc)out.push({id:`${slug(s.retailer)}:${upc}`,retailer:s.retailer,title:t,sku,upc,buy_price:.01,original_price:0,discount_pct:99,deal_type:"penny",penny_date:dm[1].trim(),source_name:s.name,source_url:s.url,availability_label:"Chain penny lead · local shelf availability unknown",resale_potential:score(t,99,"penny"),source_priority:s.priority})}return out}
function retail(h:string,s:S){const a=lines(h),out:any[]=[],seen=new Set<string>();for(let i=0;i<a.length;i++){const t=title(a[i]);if(!useful(t)||!hot(t))continue;const q=near(a,i),k=slug(t);if(seen.has(k))continue;seen.add(k);if(s.retailer==="Home Depot"&&s.kind==="deal"&&!q.cur)continue;if(q.cur&&q.disc>0&&q.disc<8&&s.kind!=="clearance")continue;out.push({id:`${slug(s.retailer)}:${k}:${q.sku||i}`,retailer:s.retailer,title:t,sku:q.sku,upc:"",buy_price:q.cur,original_price:q.was,discount_pct:q.disc,deal_type:s.kind,penny_date:"",source_name:s.name,source_url:s.url,availability_label:s.kind==="in_store_bargain"?"Retailer in-store bargain source · exact store listing varies":"Retailer deal/clearance lead · local price and stock may vary",resale_potential:score(t,q.disc,s.kind),source_priority:s.priority});if(out.length>=45)break}return out}
function fb(s:S){return{id:`${slug(s.retailer)}:source:${slug(s.name)}`,retailer:s.retailer,title:s.retailer==="Menards"?"Ray's List — unclaimed orders, display models, dinged & dented bargains":`${s.name} — browse current retailer deals`,sku:"",upc:"",buy_price:0,original_price:0,discount_pct:0,deal_type:s.kind,penny_date:"",source_name:s.name,source_url:s.url,availability_label:s.kind==="in_store_bargain"?"Store-specific bargain source · open source to view current local listings":"Official retailer savings source · product extraction temporarily unavailable",resale_potential:s.kind==="in_store_bargain"?88:74,source_priority:s.priority,source_only:true}}
async function one(s:S){try{const r=await fetch(s.url,{headers:{"user-agent":"H38ResellerScout/0.1.6","accept":"text/html,application/xhtml+xml"},redirect:"follow",signal:AbortSignal.timeout(14000)});if(!r.ok)throw Error(`${s.name} returned ${r.status}`);const h=await r.text(),l=s.kind==="penny"?penny(h,s):retail(h,s);if(l.length)return{l,w:""};if(s.fallback)return{l:[fb(s)],w:`${s.name} returned no parseable product cards; source link retained.`};throw Error(`${s.name} returned no parseable items`)}catch(e){if(s.fallback)return{l:[fb(s)],w:e instanceof Error?e.message:String(e)};throw e}}
function dedupe(a:any[]){const m=new Map<string,any>();for(const x of a){const k=`${slug(x.retailer)}|${x.upc||slug(x.title)}`,o=m.get(k);if(!o||Number(x.source_priority)>Number(o.source_priority)||Number(x.discount_pct)>Number(o.discount_pct))m.set(k,x)}const g=new Map<string,any[]>();for(const x of m.values()){const z=g.get(x.retailer)||[];z.push(x);g.set(x.retailer,z)}let out:any[]=[];for(const z of g.values()){z.sort((a,b)=>b.resale_potential-a.resale_potential||b.discount_pct-a.discount_pct);out.push(...z.slice(0,70))}return out.sort((a,b)=>b.source_priority-a.source_priority||b.resale_potential-a.resale_potential)}
async function build(){const s=[...P,...R],r=await Promise.allSettled(s.map(one)),raw:any[]=[],warnings:string[]=[],status:any[]=[];for(let i=0;i<r.length;i++){const x=r[i],q=s[i];if(x.status==="fulfilled"){raw.push(...x.value.l);if(x.value.w)warnings.push(x.value.w);status.push({retailer:q.retailer,source:q.name,status:x.value.w?"PARTIAL":"PASS",leads:x.value.l.length})}else{const w=x.reason instanceof Error?x.reason.message:String(x.reason);warnings.push(w);status.push({retailer:q.retailer,source:q.name,status:"FAIL",leads:0})}}const leads=dedupe(raw);if(!leads.length)throw Error(warnings.join("; ")||"Automatic deal sources unavailable.");return{status:"PASS",generated_at:new Date().toISOString(),count:leads.length,retailers:[...new Set(leads.map(x=>x.retailer))],leads,source_status:status,warnings,note:"Automatic hunt leads come from penny-list and retailer-owned savings sources. Local shelf stock and local price are not claimed unless the retailer source itself is store-specific."}}
Deno.serve(async(q:Request)=>{if(q.method==="OPTIONS")return new Response(null,{status:204,headers:H(q)});if(q.method!=="GET"&&q.method!=="POST")return J(q,405,{error:"GET or POST required."});try{const id=await uid(q);if(!ALLOWED.has(id))return J(q,403,{error:"Not authorized."});if(C&&Date.now()-C.at<1200000)return J(q,200,{...C.p,cached:true});if(!I)I=build().then(p=>(C={at:Date.now(),p},p)).finally(()=>I=null);return J(q,200,await I)}catch(e){if(C)return J(q,200,{...C.p,cached:true,stale:true,warning:e instanceof Error?e.message:String(e)});return J(q,503,{error:e instanceof Error?e.message:String(e)})}});
