import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ALLOWED=new Set(["ccf25333-47cd-42ca-a20b-cdbc63a8a695","6dd51b31-5974-4691-b8b8-83e5877528c0"]);
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const CLEARANCE_MIN_DISCOUNT=50,CACHE_TTL_MS=12*60*1000;
const PENNY_STOCK_UNKNOWN_ALLOWED_V1=true,RETAIL_PRODUCT_PAGE_REQUIRED_V1=true,RETAILER_SPECIFIC_ADAPTERS_V1=true;
const PENNY_SOURCES=[
 {retailer:"Dollar General",name:"RetailShout Penny List",url:"https://retailshout.com/latest-dollar-general-penny-items-near-you/",kind:"penny",priority:100},
 {retailer:"Dollar Tree",name:"RetailShout Penny List",url:"https://retailshout.com/latest-dollar-tree-penny-items-near-you/",kind:"penny",priority:100},
];
const RETAIL_SOURCES=[
 {retailer:"Home Depot",name:"Home Depot Deep Tool Savings 1",url:"https://www.homedepot.com/b/Tool-Savings/N-5yc1vZ1z1zuqf?Nao=0&catStyle=ShowProducts",kind:"deep_discount",priority:105,broad:true},
 {retailer:"Home Depot",name:"Home Depot Deep Tool Savings 2",url:"https://www.homedepot.com/b/Tool-Savings/N-5yc1vZ1z1zuqf?Nao=16&catStyle=ShowProducts",kind:"deep_discount",priority:104,broad:true},
 {retailer:"Home Depot",name:"Home Depot Daily Deals",url:"https://www.homedepot.com/daily-deals/",kind:"deal",priority:99},
 {retailer:"Walmart",name:"Walmart Clearance",url:"https://www.walmart.com/shop/deals/clearance",kind:"clearance",priority:103,broad:true},
 {retailer:"Walmart",name:"Walmart Tool Clearance",url:"https://www.walmart.com/browse/home-improvement/clearance-tools/1072864_1031899_6846544",kind:"clearance",priority:102,broad:true},
 {retailer:"Lowe's",name:"Lowe's Savings & Clearance",url:"https://www.lowes.com/l/savings",kind:"clearance",priority:102,broad:true},
 {retailer:"Lowe's",name:"Lowe's Daily Deals",url:"https://www.lowes.com/l/savings/daily-deals",kind:"deal",priority:97},
 {retailer:"Ace Hardware",name:"Ace Clearance",url:"https://www.acehardware.com/clearance?pageSize=180",kind:"clearance",priority:102,broad:true},
 {retailer:"Ace Hardware",name:"Ace Tool Deals",url:"https://www.acehardware.com/top-power-tool-deals",kind:"deal",priority:96},
 {retailer:"Menards",name:"Menards Ray's List",url:"https://www.menards.com/main/b-1957366.htm",kind:"deal",priority:100,broad:true},
 {retailer:"Menards",name:"Menards Tools & Hardware Sale Items",url:"https://www.menards.com/main/sale-items/tools-hardware-sale-items/c-1642874323047994.htm",kind:"deal",priority:96,broad:true},
];
const COLLECTION_TITLES:any={"Home Depot":"Home Depot deep tool savings & daily deals","Walmart":"Walmart clearance & rollbacks","Lowe's":"Lowe's clearance & savings","Ace Hardware":"Ace clearance & tool deals","Menards":"Menards Ray's List & sale items"};
let cache:any=null,inflight:Promise<any>|null=null;
function cors(req:Request){const o=req.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"GET, POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"private, max-age=120","vary":"Origin"}}
function json(req:Request,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
async function userId(req:Request){const t=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!t)throw Error("Sign in required.");const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${t}`,apikey:SERVICE_KEY}}),p=await r.json().catch(()=>({}));if(!r.ok||!p?.id)throw Error("Session expired.");return String(p.id)}
function decodeHtml(v:any){return String(v||"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&ndash;/gi,"–").replace(/&mdash;/gi,"—").replace(/&dollar;/gi,"$").replace(/&#x2F;/gi,"/").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)))}
function clean(v:any){return decodeHtml(v).replace(/^\*\s*/,"").replace(/^Image:\s*/i,"").replace(/\s+/g," ").trim()}
function slug(v:any){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100)}
function usefulTitle(v:any){const s=clean(v);return s.length>=9&&s.length<=220&&!/^(add|compare|shop now|view|sort|filter|price|brand|availability|clearance|sale|savings|special buys?|daily deals?|shop all|featured|sponsored)$/i.test(s)&&!/^\$?\d+(?:\.\d{1,2})?$/.test(s)}
function resaleFriendly(v:any){return /tool|battery|charger|drill|driver|impact|saw|nailer|grinder|sander|router|vacuum|compressor|generator|mower|blower|trimmer|chainsaw|storage|toolbox|workbench|ladder|grill|smoker|cooler|appliance|electronics|camera|speaker|headphone|tablet|laptop|\btv\b|gaming|console|lego|heater|lighting|faucet|pump|welder|socket|wrench|ratchet|hammer|laser|level|patio|fire pit/i.test(String(v||""))}
function resaleScore(t:string,d=0,k="deal"){let s=66,x=t.toLowerCase();if(/milwaukee|dewalt|ryobi|ridgid|makita|bosch|kobalt|craftsman|metabo|greenworks|ego|weber|traeger|blackstone|hart|masterforce/.test(x))s+=11;if(/battery|charger|combo kit|generator|mower|blower|trimmer|chainsaw|vacuum|compressor|storage|toolbox|grill|smoker|electronics|gaming|lego/.test(x))s+=9;if(k==="penny")s+=12;if(d>CLEARANCE_MIN_DISCOUNT)s+=12;return Math.max(45,Math.min(99,Math.round(s+Math.min(14,Math.max(0,d)/4))))}
function money(v:any):number{if(typeof v==="number"&&Number.isFinite(v))return v>0?v:0;if(typeof v==="string"){const m=v.replace(/,/g,"").match(/(?:\$\s*)?(\d{1,7}(?:\.\d{1,2})?)/);return m?Number(m[1]):0}if(v&&typeof v==="object")for(const k of ["price","value","amount","priceValue","currentPrice","minPrice","maxPrice","displayPrice"]){const n=money(v[k]);if(n)return n}return 0}
function at(o:any,p:string){let v=o;for(const k of p.split(".")){if(v==null||typeof v!=="object")return undefined;v=v[k]}return v}
function firstString(o:any,ps:string[]){for(const p of ps){const v=at(o,p);if(typeof v==="string"&&v.trim())return clean(v);if(typeof v==="number"&&Number.isFinite(v))return String(v)}return""}
function firstPrice(o:any,ps:string[]){for(const p of ps){const n=money(at(o,p));if(n)return n}return 0}
function retailerProductUrl(retailer:string,base:string,candidate:string){if(!candidate)return"";try{const u=new URL(decodeHtml(candidate).replace(/\\\//g,"/"),base),h=u.hostname.toLowerCase().replace(/^www\./,""),p=u.pathname;if(u.protocol!=="https:")return"";let ok=false;if(retailer==="Home Depot")ok=h==="homedepot.com"&&/\/p\//i.test(p)&&/\/\d{6,}\/?$/i.test(p);else if(retailer==="Walmart")ok=h==="walmart.com"&&/\/ip\//i.test(p)&&/\/\d{6,}\/?$/i.test(p);else if(retailer==="Lowe's")ok=h==="lowes.com"&&/\/pd\//i.test(p)&&/\/\d{6,}\/?$/i.test(p);else if(retailer==="Ace Hardware")ok=h==="acehardware.com"&&/\/departments\//i.test(p)&&/\d{5,}\/?$/i.test(p);else if(retailer==="Menards")ok=h==="menards.com"&&/\/main\//i.test(p)&&/\/p-\d+/i.test(p);if(!ok)return"";u.search="";u.hash="";return u.toString()}catch{return""}}
function reportedDiscount(o:any,c:number,r:number){for(const p of ["discountPercent","percentOff","savingsPercent","discount.percent","priceInfo.savingsPercent","pricing.savingsPercent"]){const n=Number(String(at(o,p)||"").replace(/[^0-9.]/g,""));if(n>0&&n<=100)return Math.round(n)}return c>0&&r>c?Math.round((1-c/r)*100):0}
function normalizedRetailLead(source:any,f:any){const title=clean(f.title),productUrl=retailerProductUrl(source.retailer,source.url,f.productUrl),current=Number(f.current||0),original=Number(f.original||0);if(!usefulTitle(title)||!productUrl||!(current>0))return null;if(!source.broad&&!resaleFriendly(title))return null;const pairPct=original>current?Math.round((1-current/original)*100):0,discount=pairPct||Math.max(0,Math.min(100,Math.round(Number(f.discount||0)))),deep=original>current&&pairPct>CLEARANCE_MIN_DISCOUNT,strictDeep=source.kind==="clearance"||source.kind==="deep_discount";if(strictDeep&&!deep)return null;return{id:`${slug(source.retailer)}:${clean(f.sku||"")||clean(f.upc||"")||slug(title)}`,retailer:source.retailer,title,sku:clean(f.sku||""),upc:clean(f.upc||"").replace(/\D/g,""),buy_price:current,original_price:original,discount_pct:discount,deep_discount:deep,deal_type:source.kind==="deep_discount"?"clearance":source.kind,penny_date:"",source_name:source.name,source_url:productUrl,availability_label:strictDeep?"Deep discount over 50% from retailer current/was price · local stock not checked by H38":"Priced retailer product page · local stock not checked by H38",resale_potential:resaleScore(title,discount,source.kind),source_priority:source.priority,stock_status:"not_checked",stock_count:null,stock_checked:false}}
const CFG:any={
 "Home Depot":{t:["identifiers.productLabel","productLabel","productName","name","title","displayName","product.name"],u:["canonicalUrl","productUrl","productURL","productPageUrl","url","link","itemUrl","identifiers.canonicalUrl"],c:["pricing.value","pricing.currentPrice","pricing.specialBuyPrice","pricing.price","priceInfo.currentPrice.price","currentPrice","offers.price","price.value","price"],r:["pricing.original","pricing.was","pricing.wasPrice","pricing.regularPrice","pricing.listPrice","priceInfo.wasPrice.price","wasPrice","originalPrice","regularPrice","listPrice"],s:["identifiers.modelNumber","modelNumber","modelNo","sku","identifiers.itemId","itemId","productId"],g:["identifiers.upcGtin13","identifiers.upc","upc","gtin13","gtin12","gtin"]},
 "Walmart":{t:["name","productName","title","displayName","item.name"],u:["canonicalUrl","productUrl","productURL","productPageUrl","url","link","itemUrl","canonicalURL"],c:["priceInfo.currentPrice.price","priceInfo.currentPrice","price.currentPrice","currentPrice.price","currentPrice","salePrice","offerPrice","price.value","price"],r:["priceInfo.wasPrice.price","priceInfo.wasPrice","priceInfo.listPrice.price","wasPrice","originalPrice","regularPrice","listPrice","strikeThroughPrice"],s:["usItemId","itemId","productId","sku","offerId"],g:["upc","gtin13","gtin12","gtin"]},
 "Lowe's":{t:["productInfo.description","productInfo.title","productInfo.name","productName","name","title","displayName"],u:["productInfo.productUrl","productInfo.productPageUrl","canonicalUrl","productUrl","productPageUrl","url","link"],c:["pricing.salePrice","pricing.currentPrice","pricing.price","priceInfo.currentPrice.price","currentPrice","salePrice","offerPrice","price.value","price"],r:["pricing.wasPrice","pricing.regularPrice","pricing.retailPrice","pricing.listPrice","priceInfo.wasPrice.price","wasPrice","originalPrice","regularPrice","listPrice"],s:["productInfo.modelId","productInfo.modelNumber","productInfo.omniItemId","modelNumber","itemNumber","sku","productId"],g:["productInfo.upc","upc","gtin13","gtin12","gtin"]},
 "Ace Hardware":{t:["productName","name","title","displayName","product.name"],u:["canonicalUrl","productUrl","productURL","productPageUrl","url","link","pdpUrl"],c:["salePrice","pricing.salePrice","pricing.currentPrice","price.current","currentPrice","offers.price","price.value","price"],r:["standardPrice","pricing.standardPrice","pricing.regularPrice","pricing.listPrice","wasPrice","originalPrice","regularPrice","listPrice"],s:["productId","productID","sku","itemId","id"],g:["upc","gtin13","gtin12","gtin"]},
 "Menards":{t:["productName","name","title","displayName","product.name"],u:["canonicalUrl","productUrl","productURL","productPageUrl","url","link","pdpUrl"],c:["salePrice","pricing.salePrice","pricing.currentPrice","currentPrice","offerPrice","offers.price","price.value","price"],r:["regularPrice","pricing.regularPrice","pricing.listPrice","wasPrice","originalPrice","listPrice"],s:["sku","productId","productID","itemId","modelNumber"],g:["upc","gtin13","gtin12","gtin"]},
};
function adapt(o:any,s:any){const c=CFG[s.retailer],current=firstPrice(o,c.c),original=firstPrice(o,c.r);return normalizedRetailLead(s,{title:firstString(o,c.t),productUrl:firstString(o,c.u),current,original,sku:firstString(o,c.s),upc:firstString(o,c.g),discount:reportedDiscount(o,current,original)})}
function homeDepotAdapter(o:any,s:any){return adapt(o,s)}
function walmartAdapter(o:any,s:any){return adapt(o,s)}
function lowesAdapter(o:any,s:any){return adapt(o,s)}
function aceAdapter(o:any,s:any){return adapt(o,s)}
function menardsAdapter(o:any,s:any){return adapt(o,s)}
const RETAILER_ADAPTERS:any={"Home Depot":homeDepotAdapter,"Walmart":walmartAdapter,"Lowe's":lowesAdapter,"Ace Hardware":aceAdapter,"Menards":menardsAdapter};
function walk(root:any,s:any,out:any[],seen:WeakSet<object>,count:{n:number}){if(!root||count.n>90000||out.length>180)return;if(Array.isArray(root)){for(const v of root)walk(v,s,out,seen,count);return}if(typeof root!=="object"||seen.has(root))return;seen.add(root);count.n++;const lead=RETAILER_ADAPTERS[s.retailer]?.(root,s);if(lead)out.push(lead);for(const v of Object.values(root)){if(v&&typeof v==="object")walk(v,s,out,seen,count);if(count.n>90000||out.length>180)return}}
function jsonProducts(html:string,s:any){const out:any[]=[];let n=0;for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(n++>100||out.length>160)break;const a=m[1]||"",b=decodeHtml((m[2]||"").trim());if(!b||b.length>9_000_000)continue;if(!/application\/(?:ld\+json|json)/i.test(a)&&!/__NEXT_DATA__|__APOLLO_STATE__|preloaded|initial-state|initialState|__PRELOADED_STATE__/i.test(a)&&!/^[\[{]/.test(b))continue;try{walk(JSON.parse(b),s,out,new WeakSet(),{n:0})}catch{}}return out}
function visibleText(h:string){return clean(decodeHtml(h).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," "))}
function attr(a:string,n:string){const m=a.match(new RegExp(`(?:^|\\s)${n}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`,"i"));return decodeHtml(m?.[1]||m?.[2]||m?.[3]||"")}
function price(t:string,re:RegExp[]){for(const r of re){const m=t.match(r);if(m)return Number(m[1].replace(/,/g,""))}return 0}
function firstDollar(t:string){const m=t.match(/\$\s*([0-9]{1,7}(?:,[0-9]{3})*(?:\.\d{1,2})?)/);return m?Number(m[1].replace(/,/g,"")):0}
function htmlProducts(html:string,s:any){const anchors:any[]=[];for(const m of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){if(m.index==null)continue;const u=retailerProductUrl(s.retailer,s.url,attr(m[1]||"","href"));if(u)anchors.push({u,i:m.index,e:m.index+m[0].length,label:clean(attr(m[1]||"","aria-label")||attr(m[1]||"","title")),inner:visibleText(m[2]||"")})}const out:any[]=[],used=new Set<string>();for(let i=0;i<anchors.length&&out.length<120;i++){const a=anchors[i];if(used.has(a.u))continue;used.add(a.u);let j=i+1;while(j<anchors.length&&anchors[j].u===a.u)j++;const text=visibleText(html.slice(a.i,Math.min(j<anchors.length?anchors[j].i:a.e+9000,a.i+14000))),title=[a.label,a.inner].map((x:string)=>clean(x.replace(/^(?:best seller|clearance|deal|rollback|sponsored|new)\s+/i,"").replace(/\s+\$[\s\S]*$/ ,""))).find(usefulTitle)||"";if(!title)continue;let current=0,original=0,sku="";const now=[/(?:current price|special buy|now|sale price|clearance price|your price|new lower price|after rebate)\s*\$\s*([0-9,.]+)/i],was=[/(?:was|regular price|original price|list price)\s*\$\s*([0-9,.]+)/i];current=price(text,now)||firstDollar(a.label||a.inner||text);original=price(text,was);if(s.retailer==="Home Depot")sku=clean(text.match(/Model#\s*([A-Za-z0-9._\-/]+)/i)?.[1]||"");else if(s.retailer==="Menards")sku=a.u.match(/\/p-(\d+)/i)?.[1]||"";else sku=a.u.match(/\/(\d{5,})\/?$/)?.[1]||"";const lead=normalizedRetailLead(s,{title,productUrl:a.u,current,original,sku});if(lead)out.push(lead)}return out}
function visibleLines(h:string){return decodeHtml(h.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"\n").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"\n").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>|<\/div>|<\/li>|<\/h[1-6]>|<\/tr>|<\/article>|<\/section>|<\/button>/gi,"\n").replace(/<[^>]+>/g," ")).split(/\r?\n/).map(x=>x.replace(/\s+/g," ").trim()).filter(Boolean)}
function pennyLeads(html:string,s:any){const lines=visibleLines(html),out:any[]=[];for(let i=0;i<lines.length;i++){const d=lines[i].match(/^(?:Penny Date|Date Pennied):\s*(.+)$/i);if(!d)continue;let title="",sku="",upc="";for(let j=i-1;j>=Math.max(0,i-7);j--)if(usefulTitle(lines[j])){title=clean(lines[j]).replace(/^\d+[.)]\s*/,"");break}for(let j=i+1;j<=Math.min(lines.length-1,i+10);j++){const m=lines[j].match(/SKU:\s*([A-Za-z0-9-]+).*?UPC:\s*([0-9]{7,14})/i);if(m){sku=m[1];upc=m[2];break}}if(title&&upc)out.push({id:`${slug(s.retailer)}:${upc}`,retailer:s.retailer,title,sku,upc,buy_price:0.01,original_price:0,discount_pct:99,deep_discount:true,deal_type:"penny",penny_date:d[1].trim(),source_name:s.name,source_url:s.url,availability_label:"Chain penny lead · source does not show dependable local stock",resale_potential:resaleScore(title,99,"penny"),source_priority:s.priority,stock_status:"not_shown",stock_count:null,stock_checked:false})}return out}
function dedupe(leads:any[]){const m=new Map<string,any>();for(const l of leads){if(l.deal_type==="penny"){if(!l.upc)continue}else{if(!(Number(l.buy_price)>0)||!retailerProductUrl(l.retailer,l.source_url,l.source_url))continue;if(l.deal_type==="clearance"&&!(Number(l.original_price)>Number(l.buy_price)&&Number(l.discount_pct)>CLEARANCE_MIN_DISCOUNT))continue}const k=`${slug(l.retailer)}|${l.upc||l.sku||slug(l.title)}`,e=m.get(k);if(!e||Number(l.deep_discount)>Number(e.deep_discount)||l.source_priority>e.source_priority||l.discount_pct>e.discount_pct)m.set(k,l)}const g=new Map<string,any[]>();for(const l of m.values()){const a=g.get(l.retailer)||[];a.push(l);g.set(l.retailer,a)}const out:any[]=[];for(const a of g.values()){a.sort((x,y)=>Number(y.deep_discount)-Number(x.deep_discount)||y.discount_pct-x.discount_pct||y.resale_potential-x.resale_potential);out.push(...a.slice(0,70))}return out}
function rollup(retailer:string){const s=RETAIL_SOURCES.filter(x=>x.retailer===retailer).sort((a,b)=>b.priority-a.priority)[0];return{id:`${slug(retailer)}:sale-list`,retailer,title:COLLECTION_TITLES[retailer]||`${retailer} sale list`,sku:"",upc:"",buy_price:0,original_price:0,discount_pct:0,deep_discount:false,deal_type:"sale_list",penny_date:"",source_name:s.name,source_url:s.url,availability_label:"Broad retailer sale list · H38 did not validate individual product rows from this source",resale_potential:0,source_priority:s.priority,source_only:true,stock_status:"not_checked",stock_count:null,stock_checked:false}}
async function fetchSource(s:any){const r=await fetch(s.url,{headers:{"user-agent":"Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 H38ResellerScout/0.1.11","accept":"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error(`${s.name} returned ${r.status}`);const h=await r.text(),leads=s.kind==="penny"?pennyLeads(h,s):dedupe([...jsonProducts(h,s),...htmlProducts(h,s)]);if(!leads.length)throw Error(`${s.name} returned no product rows matching truthful hunt rules`);return leads}
async function buildPayload(){const sources=[...PENNY_SOURCES,...RETAIL_SOURCES],results=await Promise.allSettled(sources.map(fetchSource)),po:any[]=[],ro:any[]=[],warnings:string[]=[],sourceStatus:any[]=[];results.forEach((r,i)=>{const s=sources[i];if(r.status==="fulfilled"){(s.kind==="penny"?po:ro).push(...r.value);sourceStatus.push({retailer:s.retailer,source:s.name,kind:s.kind,status:"PASS",products:r.value.length,adapter:s.kind==="penny"?"penny":s.retailer})}else{const w=r.reason instanceof Error?r.reason.message:String(r.reason);warnings.push(w);sourceStatus.push({retailer:s.retailer,source:s.name,kind:s.kind,status:"NO_MATCHING_PRODUCTS",products:0,adapter:s.kind==="penny"?"penny":s.retailer,warning:w})}});const pennies=dedupe(po),priced=dedupe(ro),retailers=[...new Set(RETAIL_SOURCES.map(x=>x.retailer))],rollups=retailers.filter(r=>!priced.some(l=>l.retailer===r)).map(rollup),leads=[...pennies,...priced,...rollups].sort((a,b)=>Number(a.source_only)-Number(b.source_only)||Number(b.deep_discount)-Number(a.deep_discount)||b.discount_pct-a.discount_pct||b.source_priority-a.source_priority||b.resale_potential-a.resale_potential);if(!leads.length)throw Error(warnings.join("; ")||"Automatic deal sources unavailable.");const byRetailer:any={},deepByRetailer:any={};for(const l of leads){byRetailer[l.retailer]=(byRetailer[l.retailer]||0)+1;if(l.deep_discount)deepByRetailer[l.retailer]=(deepByRetailer[l.retailer]||0)+1}console.log("reseller-auto-leads retailer-adapters-v1",JSON.stringify({by_retailer:byRetailer,deep_by_retailer:deepByRetailer,source_status:sourceStatus,retailer_specific_adapters:RETAILER_SPECIFIC_ADAPTERS_V1}));return{status:"PASS",generated_at:new Date().toISOString(),count:leads.length,retailers:[...new Set(leads.map(x=>x.retailer))],by_retailer:byRetailer,deep_by_retailer:deepByRetailer,leads,source_status:sourceStatus,warnings,adapter_version:"retailer-specific-v1",clearance_rule:`Clearance/deep-discount items require a current price, a higher was/reference price, a retailer product-page URL, and more than ${CLEARANCE_MIN_DISCOUNT}% off.`,stock_rule:"Penny leads remain visible when stock is not shown. Other retailer rows currently say local stock was not checked by H38.",note:"Retailer-specific adapters only emit products when title, legitimate product URL and current price are bound to one product object/card. Missing retailer products fall back to one SALE LIST row."}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="GET"&&req.method!=="POST")return json(req,405,{error:"GET or POST required."});try{const id=await userId(req);if(!ALLOWED.has(id))return json(req,403,{error:"Not authorized."});if(cache&&Date.now()-cache.at<CACHE_TTL_MS)return json(req,200,{...cache.payload,cached:true});if(!inflight)inflight=buildPayload().then(payload=>{cache={at:Date.now(),payload};return payload}).finally(()=>{inflight=null});return json(req,200,await inflight)}catch(e){if(cache)return json(req,200,{...cache.payload,cached:true,stale:true,warning:e instanceof Error?e.message:String(e)});return json(req,503,{error:e instanceof Error?e.message:String(e)})}});
