import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BASE=Deno.env.get("SUPABASE_URL")||"";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const PC="https://www.pennycentral.com/penny-list";
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"GET, POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"private, max-age=120","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function clean(v:any){return String(v??"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function lines(h:string){return String(h||"").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"\n").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"\n").replace(/<br\s*\/?>/gi,"\n").replace(/<\/(?:h[1-6]|p|div|li|span|a|button|section|article)>/gi,"\n").replace(/<[^>]+>/g," ").split(/\r?\n/).map(clean).filter(Boolean)}
function sku(v:any){return clean(v).replace(/\D/g,"")}
function key(x:any){return `home depot|${sku(x.sku)||sku(x.upc)||clean(x.title).toLowerCase()}`}
function sourceList(x:any){const a=Array.isArray(x?.signal_sources)?x.signal_sources:[],out:any[]=[],seen=new Set<string>();for(const s of a){let d=clean(s?.domain).toLowerCase();if(!d){try{d=new URL(clean(s?.url)).hostname.toLowerCase().replace(/^www\./,"")}catch{}}const k=d||clean(s?.name).toLowerCase();if(!k||seen.has(k))continue;seen.add(k);out.push({...s,domain:d})}return out}
function parsePc(h:string){const x=lines(h),out:any[]=[],seen=new Set<string>();for(let i=0;i<x.length;i++){const sm=x[i].match(/^SKU\s+([0-9-]{5,20})$/i);if(!sm)continue;const s=sku(sm[1]);if(!s||seen.has(s))continue;let title="",brand="",last="",reports=0,states=0,state_summary="",ref=0;for(let j=i-1;j>=Math.max(0,i-8);j--){if(/^\$0\.01\s*\$/i.test(x[j])||/^\$0\.01$/i.test(x[j])){const prices=[...x[j].matchAll(/\$\s*([0-9,.]+)/g)].map(m=>Number(m[1].replace(/,/g,""))).filter(n=>n>.01);if(prices.length)ref=Math.max(...prices)}if(!title&&!/^\$|^SKU\b|^Last seen:?$/i.test(x[j])&&x[j].length>5){title=x[j];if(j>0&&x[j-1].length<40&&!/^Image:|Fresh signal|Hot Right Now/i.test(x[j-1]))brand=x[j-1];break}}for(let j=i+1;j<=Math.min(x.length-1,i+14);j++){if(/^Last seen:?$/i.test(x[j])&&x[j+1])last=x[j+1];const r=x[j].match(/^(\d+)\s+reports?$/i);if(r)reports=Number(r[1]);const st=x[j].match(/^(\d+)\s+states?$/i);if(st)states=Number(st[1]);if(states&&j+1<x.length&&/^(?:[A-Z]{2}\s+\d+\s*){1,}/.test(x[j+1]))state_summary=x[j+1]}
if(!title||!/\$0\.01/i.test(x.slice(Math.max(0,i-7),Math.min(x.length,i+3)).join(" ")))continue;seen.add(s);out.push({id:`home-depot:${s}`,retailer:"Home Depot",title:title.replace(/^Image:\s*/i,""),brand,sku:s,upc:"",buy_price:.01,reported_penny_price:.01,original_price:ref,discount_pct:ref>.01?Math.round((1-.01/ref)*100):99,deep_discount:true,deal_type:"penny",near_penny:false,penny_date:last,posted_date:last,last_seen:last,community_penny:true,community_reports:reports,community_states:states,state_summary,source_name:"PennyCentral",source_url:PC,source_priority:160,availability_label:`PENNY LEAD · last seen ${last||"unknown"} · ${reports||1} report${reports===1?"":"s"}${states?` · ${states} states`:""}. Physical UPC/register scan remains final truth.`,resale_potential:90,stock_status:"not_checked",stock_count:null,stock_checked:false,signal_name:"PennyCentral",signal_domain:"pennycentral.com",signal_url:PC,signal_observed_at:last,signal_sources:[{name:"PennyCentral",domain:"pennycentral.com",url:PC,kind:"penny",observed_price:.01,observed_at:last}]})}return out}
function merge(base:any[],pc:any[]){const m=new Map<string,any>();for(const row of [...base,...pc]){const k=row.retailer==="Home Depot"?key(row):`${clean(row.retailer).toLowerCase()}|${clean(row.upc||row.sku||row.id).toLowerCase()}`;const old=m.get(k);if(!old){m.set(k,row);continue}const winner=(row.source_priority||0)>=(old.source_priority||0)?row:old,loser=winner===row?old:row;const z={...loser,...winner};z.title=winner.title||loser.title;z.brand=winner.brand||loser.brand||"";z.posted_date=winner.posted_date||loser.posted_date||winner.penny_date||loser.penny_date||"";z.penny_date=z.posted_date;z.last_seen=winner.last_seen||loser.last_seen||z.posted_date;z.community_reports=Math.max(Number(old.community_reports||0),Number(row.community_reports||0));z.community_states=Math.max(Number(old.community_states||0),Number(row.community_states||0));z.state_summary=winner.state_summary||loser.state_summary||"";z.original_price=Math.max(Number(old.original_price||0),Number(row.original_price||0));z.signal_sources=sourceList({signal_sources:[...sourceList(old),...sourceList(row),...(old.signal_sources||[]),...(row.signal_sources||[])]});z.signal_source_count=z.signal_sources.length;if(old.deal_type==="penny"||row.deal_type==="penny"){z.deal_type="penny";z.reported_penny_price=.01;z.buy_price=.01}m.set(k,z)}return [...m.values()]}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});try{const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";if(!auth)return json(req,401,{error:"Sign in required."});const [up,pcRes]=await Promise.all([fetch(`${BASE}/functions/v1/reseller-auto-leads-v038`,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json"},body:"{}",signal:AbortSignal.timeout(45000)}),fetch(PC,{headers:{"user-agent":"Mozilla/5.0 H38ResellerScout/0.1.44","accept":"text/html"},signal:AbortSignal.timeout(18000)})]);const payload=await up.json().catch(()=>({}));if(!up.ok)return json(req,up.status,{error:payload?.error||"Base lead source failed."});const html=pcRes.ok?await pcRes.text():"",pc=parsePc(html),base=Array.isArray(payload.leads)?payload.leads:[],leads=merge(base,pc);const by:any={};for(const l of leads)by[l.retailer]=(by[l.retailer]||0)+1;return json(req,200,{...payload,status:"PASS",leads,count:leads.length,by_retailer:by,pennycentral_full_count:pc.length,pennycentral_document_complete:pc.length>=60,adapter_version:"full-pennycentral-document-v044",date_rule:"Every PennyCentral lead carries visible last-seen date as posted_date/penny_date/last_seen.",dedupe_rule:"Same retailer + SKU/UPC is one item; sources merge underneath it.",warnings:[...(payload.warnings||[]),...(pc.length<60?[`PennyCentral full-document parser returned only ${pc.length} items.`]:[])]})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});