import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ALLOWED=new Set(["ccf25333-47cd-42ca-a20b-cdbc63a8a695","6dd51b31-5974-4691-b8b8-83e5877528c0"]);
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const SUPPORTED=new Set(["Home Depot","Lowe's","Walmart","Target","Menards","Fleet Farm","Harbor Freight","Tractor Supply","Dollar General","Dollar Tree","Family Dollar","Northern Tool","Ace Hardware"]);
const UA="Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 H38ResellerScoutStock/0.1.13";
const CACHE_TTL=5*60*1000;
const cache=new Map<string,{at:number,p:any}>();
function cors(req:Request){const o=req.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type, x-client-info","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function json(req:Request,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
async function userId(req:Request){const t=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!t)throw Error("Sign in required.");const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${t}`,apikey:SERVICE_KEY}}),p=await r.json().catch(()=>({}));if(!r.ok||!p?.id)throw Error("Session expired.");return String(p.id)}
function clean(v:any){return String(v||"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function norm(v:any){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function tokens(v:any){return norm(v).split(" ").filter(x=>x.length>=3&&!/^(store|road|street|avenue|highway|route|north|south|east|west|suite)$/.test(x))}
function zipOf(v:any){return String(v||"").match(/\b\d{5}(?:-\d{4})?\b/)?.[0]?.slice(0,5)||""}
function stateOf(v:any){const z=zipOf(v),before=z?String(v||"").slice(0,String(v||"").indexOf(z)):String(v||"");return before.match(/\b([A-Z]{2})\b(?!.*\b[A-Z]{2}\b)/)?.[1]||""}
function streetNo(v:any){return String(v||"").match(/^\s*(\d+[A-Za-z-]*)\b/)?.[1]||""}
function addressScore(text:string,s:any){const x=norm(text),z=zipOf(s.store_address),num=streetNo(s.store_address);let score=0;if(z&&x.includes(z))score+=5;if(num&&new RegExp(`\\b${num.toLowerCase()}\\b`).test(x))score+=5;const rt=new Set(tokens(s.retailer));for(const t of [...tokens(s.store_address),...tokens(s.store_name)])if(!rt.has(t)&&x.includes(t))score++;return score}
function storeEvidence(text:string,s:any,storeId=""){const x=norm(text),z=zipOf(s.store_address),num=streetNo(s.store_address);if(storeId&&new RegExp(`\\b${storeId.replace(/\D/g,"")}\\b`).test(text))return `store ${storeId}`;if(z&&num&&x.includes(z)&&new RegExp(`\\b${num.toLowerCase()}\\b`).test(x))return `${num} / ${z}`;const ts=[...tokens(s.store_address),...tokens(s.store_name)].filter(t=>!tokens(s.retailer).includes(t)),hits=[...new Set(ts.filter(t=>x.includes(t)))];return hits.length>=3?hits.slice(0,4).join(", "):""}
function productEvidence(text:string,b:any){const raw=String(text||""),x=norm(raw),upc=String(b.upc||"").replace(/\D/g,""),sku=norm(b.sku||"");if(upc.length>=8&&raw.replace(/\D/g,"").includes(upc))return true;if(sku.length>=3&&x.includes(sku))return true;const tt=tokens(b.title).filter(t=>t.length>=4),hits=tt.filter(t=>x.includes(t));return tt.length?hits.length>=Math.min(3,Math.max(1,Math.ceil(tt.length*.35))):false}
function exactCount(text:string){const rules=[/Quantity\s+Available\s*:?\s*(\d{1,4})/i,/(\d{1,4})\s+In[- ]Stock\b/i,/(\d{1,4})\s+in\s+stock\s+in\s+aisle\b/i,/Only\s+(\d{1,4})\s+(?:left|remaining)\b/i,/"(?:quantityAvailable|availableQuantity|inventoryQuantity|availableQty|onHandQuantity|onHandQty)"\s*:\s*"?(\d{1,4})"?/i,/"quantity"\s*:\s*"?(\d{1,4})"?\s*,\s*"(?:availability|stockStatus|inventoryStatus)"/i];for(const r of rules){const m=text.match(r);if(m){const q=Number(m[1]);if(Number.isInteger(q)&&q>=0&&q<=9999)return q}}return null}
function availability(text:string){if(/out\s+of\s+stock|not\s+available|unavailable|sold\s+out|"availability"\s*:\s*"(?:OUT_OF_STOCK|UNAVAILABLE)"/i.test(text))return"out_of_stock";if(/in[- ]stock|in\s+stock|pickup\s+today|ready\s+in\s+\d+|available\s+for\s+pickup|quantity\s+available|"availability"\s*:\s*"(?:IN_STOCK|AVAILABLE)"/i.test(text))return"in_stock";return"unknown"}
function retailerHost(r:string,h:string){h=h.toLowerCase().replace(/^www\./,"");const m:any={"Home Depot":"homedepot.com","Lowe's":"lowes.com","Walmart":"walmart.com","Target":"target.com","Menards":"menards.com","Fleet Farm":"fleetfarm.com","Harbor Freight":"harborfreight.com","Tractor Supply":"tractorsupply.com","Dollar General":"dollargeneral.com","Dollar Tree":"dollartree.com","Family Dollar":"familydollar.com","Northern Tool":"northerntool.com","Ace Hardware":"acehardware.com"};return h===m[r]||h.endsWith("."+m[r])}
function searchUrl(r:string,q:string){const z=encodeURIComponent(q);const m:any={"Home Depot":`https://www.homedepot.com/s/${z}`,"Lowe's":`https://www.lowes.com/search?searchTerm=${z}`,"Walmart":`https://www.walmart.com/search?q=${z}`,"Target":`https://www.target.com/s?searchTerm=${z}`,"Menards":`https://www.menards.com/main/search.html?search=${z}`,"Fleet Farm":`https://www.fleetfarm.com/search?Ntt=${z}`,"Harbor Freight":`https://www.harborfreight.com/search?q=${z}`,"Tractor Supply":`https://www.tractorsupply.com/tsc/search/${z}`,"Dollar General":`https://www.dollargeneral.com/product-search.html?query=${z}`,"Dollar Tree":`https://www.dollartree.com/searchresults?Ntt=${z}`,"Family Dollar":`https://www.familydollar.com/searchresults?Ntt=${z}`,"Northern Tool":`https://www.northerntool.com/search?s=${z}`,"Ace Hardware":`https://www.acehardware.com/search?query=${z}`};return m[r]||""}
async function fetchPage(url:string){const r=await fetch(url,{headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:AbortSignal.timeout(16000)});if(!r.ok)throw Error(`Retailer page returned ${r.status}.`);return{url:r.url,html:await r.text()}}
function productHref(retailer:string,base:string,html:string){const patterns:any={"Home Depot":/href=["']([^"']*\/p\/[^"']+\/\d{6,}[^"']*)/i,"Lowe's":/href=["']([^"']*\/pd\/[^"']+\/\d{6,}[^"']*)/i,"Walmart":/href=["']([^"']*\/ip\/[^"']+\/\d{6,}[^"']*)/i,"Target":/href=["']([^"']*\/p\/[^"']*\/-\/A-\d+[^"']*)/i,"Menards":/href=["']([^"']*\/main\/[^"']*\/p-\d+[^"']*)/i,"Harbor Freight":/href=["']([^"']*\/[^"']*-\d{5,}\.html[^"']*)/i,"Tractor Supply":/href=["']([^"']*\/tsc\/product\/[^"']+)["']/i,"Dollar General":/href=["']([^"']*\/p\/[^"']+\/\d+[^"']*)/i,"Dollar Tree":/href=["']([^"']*\/[^"']+\/\d+[^"']*)/i,"Family Dollar":/href=["']([^"']*\/[^"']+\/\d+[^"']*)/i,"Northern Tool":/href=["']([^"']*\/products\/[^"']+)["']/i,"Ace Hardware":/href=["']([^"']*\/departments\/[^"']+\/\d+[^"']*)/i,"Fleet Farm":/href=["']([^"']*\/detail\/[^"']+)["']/i};const m=html.match(patterns[retailer]);if(!m)return"";try{return new URL(m[1].replace(/&amp;/g,"&"),base).toString()}catch{return""}}
function locatorUrl(r:string,s:any){const z=zipOf(s.store_address),lat=Number(s.store_lat),lon=Number(s.store_lon);if(!z&&!Number.isFinite(lat))return"";const m:any={"Home Depot":z&&`https://www.homedepot.com/l/search/${z}/full/`,"Lowe's":z&&`https://www.lowes.com/store/?searchTerm=${z}`,"Walmart":z&&`https://www.walmart.com/store/finder?location=${z}`,"Target":z&&`https://www.target.com/store-locator/find-stores/${z}`,"Tractor Supply":z&&`https://www.tractorsupply.com/tsc/store-locator?zipCode=${z}`,"Dollar General":z&&`https://www.dollargeneral.com/store-directory?search=${z}`,"Harbor Freight":z&&`https://www.harborfreight.com/storelocator?zip=${z}`,"Ace Hardware":z&&`https://www.acehardware.com/store-locator?query=${z}`,"Menards":Number.isFinite(lat)&&Number.isFinite(lon)&&`https://www.menards.com/main/storeLocator.html?latitude=${lat}&longitude=${lon}`};return m[r]||""}
function locatorCandidates(r:string,base:string,html:string){const rules:any={"Home Depot":/href=["']([^"']*\/l\/[^"']*\/(\d{3,6})(?:[/?#"']|$)[^"']*)/gi,"Lowe's":/href=["']([^"']*\/store\/[^"']*\/(\d{3,6})(?:[/?#"']|$)[^"']*)/gi,"Walmart":/href=["']([^"']*\/store\/(\d{2,6})-[^"']+)/gi,"Target":/href=["']([^"']*\/sl\/[^"']*\/(\d{2,6})[^"']*)/gi,"Tractor Supply":/href=["']([^"']*\/tsc\/store_[^"']*_(\d{2,6})[^"']*)/gi,"Dollar General":/href=["']([^"']*\/store-directory\/[a-z]{2}\/[^"]*\/(\d{2,8})[^"']*)/gi,"Ace Hardware":/href=["']([^"']*\/store-details\/(\d{2,8})[^"']*)/gi};const re=rules[r],out:any[]=[];if(!re)return out;let m;while((m=re.exec(html))&&out.length<80){let u="";try{u=new URL(m[1].replace(/&amp;/g,"&"),base).toString()}catch{continue}const i=m.index,block=clean(html.slice(Math.max(0,i-1100),Math.min(html.length,i+1800)));out.push({id:String(m[2]),url:u,block})}return out}
async function resolveStore(r:string,s:any){const direct=String(s.store_name||"").match(/#\s*(\d{2,8})\b/)?.[1]||"";if(direct)return{id:direct,url:"",evidence:`store ${direct}`};const lu=locatorUrl(r,s);if(!lu)return{id:"",url:"",evidence:""};try{const p=await fetchPage(lu),c=locatorCandidates(r,p.url,p.html);if(!c.length)return{id:"",url:"",evidence:""};c.sort((a,b)=>addressScore(b.block,s)-addressScore(a.block,s));const best=c[0],score=addressScore(best.block,s);return score>=7?{id:best.id,url:best.url,evidence:storeEvidence(best.block,s,best.id)||`store ${best.id}`}:{id:"",url:"",evidence:""}}catch{return{id:"",url:"",evidence:""}}}
function withParam(raw:string,k:string,v:string){const u=new URL(raw);u.searchParams.set(k,v);return u.toString()}
function contextualize(r:string,url:string,ctx:any,s:any,q:string){if(!ctx?.id)return{url,bound:false};if(r==="Home Depot")return{url:withParam(url,"storeSelection",ctx.id),bound:true};if(r==="Tractor Supply")return{url:withParam(url,"store",ctx.id),bound:true};if(r==="Walmart"&&ctx.url)return{url:ctx.url.replace(/\/$/,"")+`/search?query=${encodeURIComponent(q)}`,bound:true};if(r==="Lowe's")return{url:withParam(url,"store_code",ctx.id),bound:false};if(r==="Target")return{url:withParam(url,"storeId",ctx.id),bound:false};if(r==="Dollar General")return{url:withParam(url,"store",ctx.id),bound:false};if(r==="Ace Hardware")return{url:withParam(url,"store",ctx.id),bound:false};return{url,bound:false}}
function logResult(p:any){try{console.log(JSON.stringify({h38_stock_v:2,retailer:p.retailer,status:p.status,store_id:p.store_id||"",stock_status:p.stock_status,stock_count:p.stock_count,store_bound:!!p.store_bound,cached:!!p.cached}))}catch{}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required."});try{const uid=await userId(req);if(!ALLOWED.has(uid))return json(req,403,{error:"Not authorized."});const b=await req.json().catch(()=>({})),retailer=clean(b.retailer),s={retailer,store_name:clean(b.store_name),store_address:clean(b.store_address),store_lat:b.store_lat,store_lon:b.store_lon},query=clean(b.upc||b.sku||b.title);if(!SUPPORTED.has(retailer))return json(req,200,{status:"unsupported",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,availability_label:"No H38 checker is configured for this retailer yet."});const ck=[retailer,norm(s.store_address),query,clean(b.source_url)].join("|");const prior=cache.get(ck);if(prior&&Date.now()-prior.at<CACHE_TTL)return json(req,200,{...prior.p,cached:true});let url=clean(b.source_url);if(url){try{const u=new URL(url);if(!retailerHost(retailer,u.hostname))url=""}catch{url=""}}if(!url&&query)url=searchUrl(retailer,query);if(!url)return json(req,200,{status:"no_product_reference",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,availability_label:"Need a product URL, UPC, SKU, or title to check this store."});const ctx=await resolveStore(retailer,s);let first=await fetchPage(url),page=first,html=first.html;if(!retailerHost(retailer,new URL(first.url).hostname)||!(/\/p\/|\/pd\/|\/ip\/|\/product\/|p-\d+|\.html/i.test(new URL(first.url).pathname))){const ph=productHref(retailer,first.url,html);if(ph){page=await fetchPage(ph);html=page.html}}
const c=contextualize(retailer,page.url,ctx,s,query);if(c.url!==page.url){try{page=await fetchPage(c.url);html=page.html}catch{}}
const raw=html,text=clean(raw),explicitEvidence=storeEvidence(text,s,ctx.id),storeBound=!!(c.bound&&ctx.id)||!!explicitEvidence,productBound=productEvidence(raw,b),q=productBound?exactCount(raw):null,av=productBound?availability(raw):"unknown";let payload:any;
if(q!==null&&storeBound)payload={status:"exact",retailer,stock_checked:true,stock_status:q>0?"in_stock":"out_of_stock",stock_count:q,store_bound:true,store_id:ctx.id||null,store_evidence:explicitEvidence||ctx.evidence||`store ${ctx.id}`,checked_url:page.url,availability_label:`${q} shown for this store · retailer inventory can change.`};
else if(av!=="unknown"&&storeBound)payload={status:"availability_only",retailer,stock_checked:true,stock_status:av,stock_count:null,store_bound:true,store_id:ctx.id||null,store_evidence:explicitEvidence||ctx.evidence||`store ${ctx.id}`,checked_url:page.url,availability_label:av==="in_stock"?"In stock at this store · retailer does not expose a dependable exact count on this page.":"Out of stock at this store."};
else if(ctx.id)payload={status:"store_resolved_no_quantity",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,store_bound:true,store_id:ctx.id,store_evidence:ctx.evidence||`store ${ctx.id}`,checked_url:page.url,availability_label:`Store ${ctx.id} was selected, but ${retailer} did not expose a dependable quantity for this item.`};
else payload={status:"store_not_resolved",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,store_bound:false,checked_url:page.url,availability_label:`${retailer} page checked, but H38 could not resolve this physical store to the retailer's store ID yet.`};
cache.set(ck,{at:Date.now(),p:payload});logResult(payload);return json(req,200,payload);
}catch(e){const p={status:"check_failed",stock_checked:true,stock_status:"unknown",stock_count:null,availability_label:`Quantity check unavailable: ${e instanceof Error?e.message:String(e)}`};logResult(p);return json(req,200,p)}});
