import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ALLOWED=new Set(["ccf25333-47cd-42ca-a20b-cdbc63a8a695","6dd51b31-5974-4691-b8b8-83e5877528c0"]);
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const SUPPORTED=new Set(["Home Depot","Lowe's","Walmart","Target","Menards","Fleet Farm","Harbor Freight","Tractor Supply","Dollar General","Dollar Tree","Family Dollar","Northern Tool","Ace Hardware"]);
const UA="Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 H38ResellerScoutStock/0.1.12";
function cors(req:Request){const o=req.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type, x-client-info","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function json(req:Request,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
async function userId(req:Request){const t=String(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!t)throw Error("Sign in required.");const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${t}`,apikey:SERVICE_KEY}}),p=await r.json().catch(()=>({}));if(!r.ok||!p?.id)throw Error("Session expired.");return String(p.id)}
function clean(v:any){return String(v||"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function norm(v:any){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function tokens(v:any){return norm(v).split(" ").filter(x=>x.length>=4&&!/^(store|road|street|avenue|highway|route|north|south|east|west)$/.test(x))}
function storeEvidence(text:string,s:any){const x=norm(text),zip=String(s.store_address||"").match(/\b\d{5}(?:-\d{4})?\b/)?.[0]||"";if(zip&&x.includes(zip))return `ZIP ${zip}`;const ts=[...tokens(s.store_address),...tokens(s.store_name)].filter(t=>!tokens(s.retailer).includes(t));const hits=[...new Set(ts.filter(t=>x.includes(t)))];return hits.length>=2?hits.slice(0,3).join(", "):""}
function exactCount(text:string){for(const r of [/Quantity\s+Available\s*:?\s*(\d{1,4})/i,/(\d{1,4})\s+In[- ]Stock\b/i,/(\d{1,4})\s+in\s+stock\s+in\s+aisle\b/i,/Only\s+(\d{1,4})\s+(?:left|remaining)\b/i]){const m=text.match(r);if(m){const q=Number(m[1]);if(Number.isInteger(q)&&q>=0&&q<=9999)return q}}return null}
function availability(text:string){if(/out\s+of\s+stock|not\s+available|unavailable|sold\s+out/i.test(text))return"out_of_stock";if(/in[- ]stock|in\s+stock|pickup\s+today|ready\s+in\s+\d+|available\s+for\s+pickup|quantity\s+available/i.test(text))return"in_stock";return"unknown"}
function retailerHost(r:string,h:string){h=h.toLowerCase().replace(/^www\./,"");const m:any={"Home Depot":"homedepot.com","Lowe's":"lowes.com","Walmart":"walmart.com","Target":"target.com","Menards":"menards.com","Fleet Farm":"fleetfarm.com","Harbor Freight":"harborfreight.com","Tractor Supply":"tractorsupply.com","Dollar General":"dollargeneral.com","Dollar Tree":"dollartree.com","Family Dollar":"familydollar.com","Northern Tool":"northerntool.com","Ace Hardware":"acehardware.com"};return h===m[r]||h.endsWith("."+m[r])}
function searchUrl(r:string,q:string){const z=encodeURIComponent(q);const m:any={"Home Depot":`https://www.homedepot.com/s/${z}`,"Lowe's":`https://www.lowes.com/search?searchTerm=${z}`,"Walmart":`https://www.walmart.com/search?q=${z}`,"Target":`https://www.target.com/s?searchTerm=${z}`,"Menards":`https://www.menards.com/main/search.html?search=${z}`,"Fleet Farm":`https://www.fleetfarm.com/search?Ntt=${z}`,"Harbor Freight":`https://www.harborfreight.com/search?q=${z}`,"Tractor Supply":`https://www.tractorsupply.com/tsc/search/${z}`,"Dollar General":`https://www.dollargeneral.com/product-search.html?query=${z}`,"Dollar Tree":`https://www.dollartree.com/searchresults?Ntt=${z}`,"Family Dollar":`https://www.familydollar.com/searchresults?Ntt=${z}`,"Northern Tool":`https://www.northerntool.com/search?s=${z}`,"Ace Hardware":`https://www.acehardware.com/search?query=${z}`};return m[r]||""}
async function fetchPage(url:string){const r=await fetch(url,{headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:AbortSignal.timeout(16000)});if(!r.ok)throw Error(`Retailer page returned ${r.status}.`);return{url:r.url,html:await r.text()}}
function productHref(retailer:string,base:string,html:string){const patterns:any={"Home Depot":/href=["']([^"']*\/p\/[^"']+\/\d{6,}[^"']*)/i,"Lowe's":/href=["']([^"']*\/pd\/[^"']+\/\d{6,}[^"']*)/i,"Walmart":/href=["']([^"']*\/ip\/[^"']+\/\d{6,}[^"']*)/i,"Target":/href=["']([^"']*\/p\/[^"']*\/-\/A-\d+[^"']*)/i,"Menards":/href=["']([^"']*\/main\/[^"']*\/p-\d+[^"']*)/i,"Harbor Freight":/href=["']([^"']*\/[^"']*-\d{5,}\.html[^"']*)/i,"Tractor Supply":/href=["']([^"']*\/tsc\/product\/[^"']+)["']/i,"Dollar General":/href=["']([^"']*\/p\/[^"']+\/\d+[^"']*)/i,"Dollar Tree":/href=["']([^"']*\/[^"']+\/\d+[^"']*)/i,"Family Dollar":/href=["']([^"']*\/[^"']+\/\d+[^"']*)/i,"Northern Tool":/href=["']([^"']*\/products\/[^"']+)["']/i,"Ace Hardware":/href=["']([^"']*\/departments\/[^"']+\/\d+[^"']*)/i,"Fleet Farm":/href=["']([^"']*\/detail\/[^"']+)["']/i};const m=html.match(patterns[retailer]);if(!m)return"";try{return new URL(m[1].replace(/&amp;/g,"&"),base).toString()}catch{return""}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required."});try{const uid=await userId(req);if(!ALLOWED.has(uid))return json(req,403,{error:"Not authorized."});const b=await req.json().catch(()=>({})),retailer=clean(b.retailer),s={retailer,store_name:clean(b.store_name),store_address:clean(b.store_address)},query=clean(b.upc||b.sku||b.title);if(!SUPPORTED.has(retailer))return json(req,200,{status:"unsupported",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,availability_label:"No H38 checker is configured for this retailer yet."});let url=clean(b.source_url),page:any=null;if(url){try{const u=new URL(url);if(!retailerHost(retailer,u.hostname))url=""}catch{url=""}}if(!url&&query)url=searchUrl(retailer,query);if(!url)return json(req,200,{status:"no_product_reference",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,availability_label:"Need a product URL, UPC, SKU, or title to check this store."});page=await fetchPage(url);let html=page.html;if(!retailerHost(retailer,new URL(page.url).hostname)||!(/\/p\/|\/pd\/|\/ip\/|\/product\/|p-\d+|\.html/i.test(new URL(page.url).pathname))){const p=productHref(retailer,page.url,html);if(p){page=await fetchPage(p);html=page.html}}
const text=clean(html),evidence=storeEvidence(text,s),q=exactCount(text),av=availability(text),storeBound=!!evidence;
if(q!==null&&storeBound)return json(req,200,{status:"exact",retailer,stock_checked:true,stock_status:q>0?"in_stock":"out_of_stock",stock_count:q,store_bound:true,store_evidence:evidence,checked_url:page.url,availability_label:`${q} shown for selected-store context · retailer inventory can change.`});
if(av!=="unknown"&&storeBound)return json(req,200,{status:"availability_only",retailer,stock_checked:true,stock_status:av,stock_count:null,store_bound:true,store_evidence:evidence,checked_url:page.url,availability_label:av==="in_stock"?"In stock shown for selected-store context · exact quantity not exposed.":"Out of stock shown for selected-store context."});
return json(req,200,{status:"not_store_bound",retailer,stock_checked:true,stock_status:"unknown",stock_count:null,store_bound:false,checked_url:page.url,availability_label:"Retailer page checked, but H38 could not tie a dependable quantity or availability result to this exact store."});
}catch(e){return json(req,200,{status:"check_failed",stock_checked:true,stock_status:"unknown",stock_count:null,availability_label:`Quantity check unavailable: ${e instanceof Error?e.message:String(e)}`})}});
