import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const NAME='reseller-auto-leads-v066';
const BASE=Deno.env.get('SUPABASE_URL')||'';
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
const txt=(v:any)=>String(v??'').trim();
function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=60','vary':'Origin'}}
function out(req:Request,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
function decode(v:any){return txt(v).replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;|&#160;/gi,' ').replace(/&cent;|&#0*162;|&#x0*a2;/gi,'¢').replace(/&#(\d+);/g,(_,n)=>{try{return String.fromCodePoint(Number(n))}catch{return' '}})}
function strip(v:any){return decode(String(v??'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function isDG(r:any){return txt(r?.retailer).toLowerCase().includes('dollar general')}
function cleanTitle(v:any){return strip(v).replace(/\b(?:href|src)\s*=\s*["']?https?:\/\/\S+/gi,' ').replace(/https?:\/\/\S+/gi,' ').replace(/\s*[|–-]\s*Dollar General.*$/i,'').replace(/^\$\s*0\.01\s*/,'').replace(/\s+/g,' ').trim().slice(0,220)}
function badTitle(v:any){const raw=txt(v),s=cleanTitle(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(!raw||/<\/?a\b|href=|https?:\/\/(?:www\.)?dollargeneral\.com\/p\//i.test(raw))return true;if(/&(?:cent|#0*162|#x0*a2);/i.test(raw))return true;if(!s||s.length<4)return true;return /^(?:1 cent|one cent|permalink|read more|learn more|shop now|click here|details?|view details?|view product|product page|item page|unknown|n a|penny|penny item|penny list|current weekly list|recently pennied|dollar general|dollar general item|dollar general product|dollar general penny item|first seen at a penny(?: today| yesterday)?|penny date unknown)$/.test(s)}
function directUrl(r:any){for(const v of [r?.source_item_url,r?.product_url,r?.url,r?.source_url]){const s=decode(v);const m=s.match(/https?:\/\/(?:www\.)?dollargeneral\.com\/p\/[A-Za-z0-9_~:/?#\[\]@!$&'()*+,;=%.-]+/i);if(!m)continue;try{const u=new URL(m[0].replace(/["'<>]+$/g,''));if(u.hostname.toLowerCase().endsWith('dollargeneral.com')&&u.pathname.startsWith('/p/')){u.hash='';return u.toString()}}catch{}}return''}
function safeImage(v:any,base:string){let s=decode(v);if(!s)return'';try{s=new URL(s,base).href}catch{return''}if(!/^https:\/\//i.test(s)||/(?:logo|favicon|sprite|pixel|tracking|placeholder|blank|spacer|avatar|badge|banner|loading)/i.test(s))return'';return s}
function titleFromHtml(html:string){for(const re of [/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:title["']/i,/<h1\b[^>]*>([\s\S]*?)<\/h1>/i,/<title\b[^>]*>([\s\S]*?)<\/title>/i]){const m=html.match(re),t=m?cleanTitle(m[1]):'';if(t&&!badTitle(t))return t}return''}
function imageFromHtml(html:string,base:string){for(const re of [/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)["']/i]){const m=html.match(re),u=m?safeImage(m[1],base):'';if(u)return u}return''}
async function pairDirect(r:any){const url=directUrl(r);if(!url)return{...r};try{const res=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Mobile Safari/537.36 H38ResellerScout/3.0.31','accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(9000)});if(!res.ok)return{...r};const type=(res.headers.get('content-type')||'').toLowerCase();if(!type.includes('text/html'))return{...r};const finalUrl=res.url||url,html=(await res.text()).slice(0,1_500_000),title=titleFromHtml(html),image=imageFromHtml(html,finalUrl);if(!title)return{...r,image_url:'',image_data_url:'',image:'',thumbnail:'',thumbnail_url:'',product_image_url:'',primary_image_url:'',source_image_url:'',photo_url:'',name_unresolved:true,title_quality:'UNRESOLVED_DIRECT_PRODUCT'};const x={...r,raw_title:txt(r?.raw_title||r?.title),title,canonical_title:title,source_identity_title:title,source_identity_provider:'Dollar General product page',source_identity_scope:'exact_product_url',source_item_url:finalUrl,source_item_scope:'exact_product',source_item_proof:'direct_dg_product_url_v066',title_quality:'RESOLVED_DIRECT_PRODUCT_V066',name_unresolved:false};if(image){Object.assign(x,{image_url:image,image_data_url:'',image:image,thumbnail:'',thumbnail_url:'',product_image_url:image,primary_image_url:image,source_image_url:'',photo_url:'',image_source_url:finalUrl,image_source_provider:'Dollar General product page',image_source_scope:'exact_product',image_source_proof:'same_direct_dg_product_page_v066',image_title_pair_proof:'same_direct_dg_product_page_v066'})}else{Object.assign(x,{image_url:'',image_data_url:'',image:'',thumbnail:'',thumbnail_url:'',product_image_url:'',primary_image_url:'',source_image_url:'',photo_url:''})}return x}catch{return{...r}}}
async function repair(rows:any[]){const outRows=rows.map(r=>({...r}));const targets:number[]=[];for(let i=0;i<outRows.length&&targets.length<72;i++){const r=outRows[i];if(isDG(r)&&(directUrl(r)||badTitle(r?.title)))targets.push(i)}let cursor=0,paired=0,rejected=0;async function worker(){while(cursor<targets.length){const i=targets[cursor++],before=outRows[i],after=await pairDirect(before);if(after?.image_title_pair_proof==='same_direct_dg_product_page_v066')paired++;if(isDG(after)&&badTitle(after?.title)){rejected++;after.name_unresolved=true;after.title_quality='UNRESOLVED';after.image_url='';after.image_data_url='';after.image='';after.thumbnail='';after.thumbnail_url='';after.product_image_url='';after.primary_image_url='';after.source_image_url='';after.photo_url=''}outRows[i]=after}}await Promise.all(Array.from({length:Math.min(8,targets.length||1)},()=>worker()));return{rows:outRows,paired,rejected}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return out(req,405,{error:'POST required'});const auth=req.headers.get('authorization')||'',apikey=req.headers.get('apikey')||'';if(!auth)return out(req,401,{error:'Sign in required'});try{const body=await req.text(),res=await fetch(`${BASE}/functions/v1/reseller-auto-leads-v065`,{method:'POST',headers:{authorization:auth,apikey,'content-type':'application/json'},body:body||'{}',signal:AbortSignal.timeout(105000)}),p=await res.json().catch(()=>({}));if(!res.ok)return out(req,res.status,{error:p?.error||'Retail Hunt source failed',function_slug:NAME});const fixed=await repair(Array.isArray(p?.leads)?p.leads:[]);return out(req,200,{...p,leads:fixed.rows,count:fixed.rows.length,function_slug:NAME,adapter_version:'v065+same-page-dg-pairing-v066',dg_same_page_pairs:fixed.paired,dg_rejected_junk_titles:fixed.rejected,title_image_rule:'Dollar General title and image may be shown together only when they come from the same exact DollarGeneral.com product page or a separate exact-barcode image proof. HTML penny placeholders such as 1&cent; are never product names.',penny_truth_rule:'Physical Dollar General app/UPC/register scan remains final local penny truth.'})}catch(e){return out(req,503,{error:e instanceof Error?e.message:String(e),function_slug:NAME})}});
