/** Synthetic non-customer fixtures. Requires explicit confirmation and installed candidate sheets. */
function h38PortalLoadSyntheticFixtures(confirmation){
  h38PortalAssertOwner_();
  if(confirmation!=='LOAD SYNTHETIC TEST RECORDS')throw new Error('TEST FIXTURE HOLD — exact confirmation required.');
  if(!H38_PORTAL_NEXT.TEST_MODE)throw new Error('TEST FIXTURE HOLD — test mode must be enabled.');
  if(!h38PortalInstalledStatus_().installed)throw new Error('TEST FIXTURE HOLD — install candidate sheets first.');
  var suffix=Utilities.getUuid().slice(0,6).toUpperCase();
  var customer=h38PortalSave('customers',{'Customer ID':'TEST-CUST-'+suffix,'Name':'Test Customer '+suffix,'Business':'Synthetic Test Shop','Email':'test+'+suffix.toLowerCase()+'@example.invalid','Phone':'000-000-0000','Preferred Contact':'Email','Lead Source':'Synthetic fixture','First Contact Date':h38PortalNow_().slice(0,10),'Customer Status':'Test','Privacy Classification':'Synthetic / No Customer Data','Notes':'Non-customer fixture only.'});
  var lead=h38PortalSave('leads',{'Lead ID':'TEST-LEAD-'+suffix,'Customer ID':customer['Customer ID'],'Name':customer.Name,'Business':customer.Business,'Email':customer.Email,'Phone':customer.Phone,'Preferred Contact':'Email','Lead Source':'Synthetic fixture','First Contact Date':h38PortalNow_().slice(0,10),'Status':'Needs review','Product / Bundle ID':'H38-P001','Next Action':'Review synthetic request','Privacy Classification':'Synthetic / No Customer Data','Notes':'Test fixture.'});
  var job=h38PortalSave('jobs',{'Job ID':'TEST-JOB-'+suffix,'Customer ID':customer['Customer ID'],'Customer Name':customer.Name,'Product / Bundle ID':'H38-P001','Scope':'Synthetic problem snapshot test','Inputs Received':'Synthetic notes','Intake Complete':'Yes','Payment Requirement':'Test only','Payment Status':'Not required','Start Authorization':'HOLD','Job Stage':'Owner review','Revision Allowance':'Test','Revision Status':'Not started','Due Date':h38PortalNow_().slice(0,10),'QA Status':'Needs review','Approval Status':'Rick Review Required / Owner Approval Required','Final Delivery Status':'Do Not Deliver','Revenue':0,'Expense Total':0,'Profit Estimate':0,'Notes':'No customer data and no external action.'});
  var task=h38PortalSave('tasks',{'Task ID':'TEST-TASK-'+suffix,'Task Title':'Review synthetic test job','Task Type':'Job review','Related Customer ID':customer['Customer ID'],'Related Project':'Synthetic Test Shop','Job ID':job['Job ID'],'Product / Bundle ID':'H38-P001','Priority':'Normal','Due Date':h38PortalNow_().slice(0,10),'Status':'Needs review','Approval Requirement':'Rick Review Required / Owner Approval Required','Approval Status':'Rick Review Required / Owner Approval Required','Rick Decision':'HOLD','Assigned Action':'APPROVE_TASK','Source System':'Synthetic fixture','Last Update':h38PortalNow_(),'Next Recommended Action':'Open workspace and test owner decision.','Notes':'No external action.'});
  h38PortalWriteProof_({jobId:job['Job ID'],source:'Portal Test Fixtures',action:'Load synthetic fixtures',decision:confirmation,result:'PASS',evidence:'Customer='+customer['Customer ID']+' Lead='+lead['Lead ID']+' Job='+job['Job ID']+' Task='+task['Task ID'],notes:'No real customer data; no external action.'});
  return {status:'PASS',customer:customer,lead:lead,job:job,task:task};
}
