import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"};
const txt=(v:any)=>String(v??'').trim();
const clean=(v:any)=>txt(v).replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;|&#x27;/gi,"'").replace(/&nbsp;|&#160;/gi,' ').replace(/\s+/g,' ').trim();
const money=(v:any)=>{const n=Number(txt(v).replace(/[$,]/g,''));return Number.isFinite(n)?n:null};
const pct=(now:any,was:any)=>Number.isFinite(now)&&Number.isFinite(was)&&was>now?Math.round((was-now)/was*1000)/10:0;
const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
const nowIso=()=>new Date().toISOString();

async function fetchText(url:string,timeout=18000){
  const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 H38Deals/6.0 clearance-source','accept':'text/html,text/plain,application/xhtml+xml;q=0.9,*/*;q=0.7','accept-language':'en-US,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(timeout)});
  if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);
  return(await r.text()).slice(0,2800000);
}
const mirror=(url:string,timeout=22000)=>fetchText('https://r.jina.ai/'+url,timeout);
function stripMd(v:any){return clean(String(v??'').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/\*\*/g,'').replace(/^#+\s*/,'').replace(/^[-*]\s*/,''))}
function usefulTitle(v:any){const s=stripMd(v);return s.length>=8&&s.length<=260&&!/^(?:home depot|walgreens|walmart|target|harbor freight|fleet farm|clearance|find of the day|more .* finds|track .* like this|page navigation|price and inventory|add to cart|choose options|shop all)/i.test(s)&&!/(?:wag_header_logo|\/store\/c\/productlist\/|https?:\/\/)/i.test(s)}
function keyTitle(v:any){return stripMd(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function dedupe(rows:any[],limit=120){const best=new Map<string,any>();for(const r of rows){const k=`${txt(r.retailer).toLowerCase()}|${keyTitle(r.title)}`;const p=best.get(k);if(!p||Number(r.discount_pct||0)>Number(p.discount_pct||0))best.set(k,r)}return[...best.values()].sort((a,b)=>Number(b.discount_pct||0)-Number(a.discount_pct||0)||txt(a.title).localeCompare(txt(b.title))).slice(0,limit)}
function officialRow(retailer:string,title:any,now:any,was:any,sourceUrl:string,extra:any={}){const t=stripMd(title),d=pct(now,was);if(!usefulTitle(t)||!Number.isFinite(now))return null;return{retailer,title:t,canonical_title:t,buy_price:now,retail_price:Number.isFinite(was)?was:null,discount_pct:d,deep_discount:d>=40,deal_type:'clearance',source_name:`${retailer} official clearance`,source_url:sourceUrl,source_item_url:extra.source_item_url||sourceUrl,image_url:extra.image_url||'',observed_at:nowIso(),deal_scope:extra.deal_scope||'chain_or_online',store_specific:false,source_confidence:'HIGH',source_confidence_score:extra.source_confidence_score??.93,identity_confidence:extra.identity_confidence||'OFFICIAL_CLEARANCE_LIST_TITLE_PRICE',evidence_role:'official_retailer',evidence_group:extra.evidence_group||`${retailer.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-official-clearance`,availability_label:extra.availability_label||`Official ${retailer} clearance. Local price and inventory may vary.`,clearance_verified:true,...extra}}

function hdRow(title:any,brand:any,discount:any,sourceUrl:string,image='',stock:any=null){const d=Number(discount);if(!usefulTitle(title)||!Number.isFinite(d)||d<40||d>99.9)return null;const t=stripMd(title);return{retailer:'Home Depot',title:t,canonical_title:t,buy_price:null,retail_price:null,discount_pct:d,deep_discount:true,deal_type:'clearance',source_name:'Endless public Home Depot clearance preview',source_url:sourceUrl,source_item_url:sourceUrl,image_url:image,observed_at:nowIso(),deal_scope:'chain_observed',store_specific:false,source_confidence:'MEDIUM',source_confidence_score:.78,identity_confidence:image?'TITLE_IMAGE_EXACT_CARD':'TITLE_BRAND',evidence_role:'specialist_clearance_monitor',evidence_group:'endless-home-depot',brand,source_stock_observed:Number.isFinite(stock)?stock:null,availability_label:'Home Depot clearance observed across scanned stores. Exact local price and stock must be verified before travel.',image_source_scope:image?'exact_product_card':'',image_source_proof:image?'public_clearance_preview_exact_product_card':''}}
function parseHdBrand(md:string,sourceUrl:string,brandHint:string){const raw=String(md||''),lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),rows:any[]=[],brand=brandHint||'';for(let i=0;i<lines.length;i++){if(!/^##\s+/.test(lines[i]))continue;const title=stripMd(lines[i]);if(!usefulTitle(title))continue;const before=lines.slice(Math.max(0,i-4),i).join(' '),after=lines.slice(i+1,i+4).join(' '),pm=(before+' '+after).match(/(\d{2,3})%\s*off/i);if(!pm)continue;const im=before.match(/https:\/\/images\.thdstatic\.com\/[^)\s\]]+/i),sm=after.match(/(\d+)\s+(?:in stock|left)/i),r=hdRow(title,brand,Number(pm[1]),sourceUrl,im?im[0]:'',sm?Number(sm[1]):null);if(r)rows.push(r)}const cardRe=/!\[[^\]]*\]\((https:\/\/images\.thdstatic\.com\/[^)]+)\)\s*[^\[]*?(\d{2,3})%\s*off\s+###\s+(.+?)\s+(\d{2,3})%\s*off\s+and\s+(\d+)\s+(?:in stock|left)/gi;let m;while((m=cardRe.exec(raw))){if(Number(m[2])!==Number(m[4]))continue;const r=hdRow(stripMd(m[3]),brand,Number(m[2]),sourceUrl,m[1],Number(m[5]));if(r)rows.push(r)}return dedupe(rows,180)}
const HD_BRANDS=['hampton-bay','everbilt','home-decorators-collection','milwaukee','glacier-bay','vigoro','ryobi','dewalt','commercial-electric','feit-electric','msi','trafficmaster','husky','ridgid','rheem','lincoln-electric','southwire','echo'];
async function homeDepotShared(limitBrands=14){const statuses:any[]=[],all:any[]=[],brands=HD_BRANDS.slice(0,Math.max(1,Math.min(limitBrands,HD_BRANDS.length)));let cursor=0;async function worker(){while(cursor<brands.length){const slug=brands[cursor++],url=`https://endless.page/deals/home-depot/brands/${slug}/`;try{const md=await mirror(url,18000),rows=parseHdBrand(md,url,slug.replace(/-/g,' '));all.push(...rows);statuses.push({source:'Endless Home Depot public brand preview',key:slug,status:rows.length?'AVAILABLE':'DEGRADED',products:rows.length,strategy:'public_text_mirror'})}catch(e){statuses.push({source:'Endless Home Depot public brand preview',key:slug,status:'UNAVAILABLE',products:0,strategy:'public_text_mirror',warning:e instanceof Error?e.message:String(e)})}}}await Promise.all(Array.from({length:Math.min(5,brands.length)},()=>worker()));return{rows:dedupe(all,180),statuses}}

function regulatedWalgreens(v:any){return /\b(?:nicorette|nicotine|tobacco|cigarette|cigar|vape|beer|wine|liquor|spirits)\b/i.test(txt(v))}
function parseCurrentExpression(v:any){const s=txt(v);let m=s.match(/1\s*\/\s*\$([\d,.]+)/i);if(m)return money(m[1]);m=s.match(/\$([\d,.]+)/);if(m)return money(m[1]);m=s.match(/^([\d,.]+)/);return m?money(m[1]):null}
function parseWalgreensText(text:string,clearanceUrl:string,strategy:string){const lines=String(text||'').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").split(/\r?\n/).map(x=>clean(x)).filter(Boolean),out:any[]=[];for(let i=0;i<lines.length;i++){if(!/^Previous price was$/i.test(lines[i]))continue;const title=lines[i-3]||'',brand=lines[i-2]||'',rating=lines[i-1]||'';if(!usefulTitle(title)||regulatedWalgreens(title)||!/^(?:\(\d+[\d,]*\)|No Reviews)$/i.test(rating))continue;const was=money(lines[i+1]);if(!/^Current sale price is$/i.test(lines[i+2]||''))continue;const now=parseCurrentExpression(lines[i+3]);if(!/^Clearance$/i.test(lines[i+4]||''))continue;const r:any=officialRow('Walgreens',title,now,was,clearanceUrl,{acquisition_strategy:strategy,brand,source_confidence_score:.94,availability_label:'Official Walgreens clearance. Walgreens notes that price and inventory may vary by store.'});if(r&&r.discount_pct>=40&&!regulatedWalgreens(r.title))out.push(r)}return dedupe(out,120)}
async function walgreensShared(){const statuses:any[]=[],clearance='https://www.walgreens.com/search/results.jsp?Ntt=Clearance&ban=dl_dlsp_ShopProducts_Clearance';try{const got=parseWalgreensText(await mirror(clearance,18000),clearance,'official_clearance_text_mirror');statuses.push({source:'Walgreens official clearance',status:got.length?'AVAILABLE':'DEGRADED',products:got.length,strategy:'official_clearance_text_mirror'});return{rows:got,statuses}}catch(e){statuses.push({source:'Walgreens official clearance',status:'UNAVAILABLE',products:0,strategy:'official_clearance_text_mirror',warning:e instanceof Error?e.message:String(e)});return{rows:[],statuses}}}

function parseWalmart(text:string,url:string){const lines=String(text||'').split(/\r?\n/).map(x=>clean(x)).filter(Boolean),out:any[]=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/current price(?:\s+Now)?\s*\$([\d,.]+),\s*Was\s*\$([\d,.]+)/i);if(!m)continue;const now=money(m[1]),was=money(m[2]);if(pct(now,was)<40)continue;const window=lines.slice(Math.max(0,i-8),Math.min(lines.length,i+10));if(!window.some(x=>/^Clearance$/i.test(x)||/^Clearance\b/i.test(x)))continue;let title='';for(let j=i+1;j<Math.min(lines.length,i+10);j++){const c=stripMd(lines[j]);if(/^###\s*/.test(lines[j])&&usefulTitle(c)){title=c;break}if(usefulTitle(c)&&!/(you save|options|stars|reviews|shipping|pickup|add|sponsored|best seller|current price|was \$|clearance)/i.test(c)){title=c;break}}if(!title){for(let j=i-1;j>=Math.max(0,i-8);j--){const c=stripMd(lines[j]).replace(/^Clearance\s+/i,'');if(usefulTitle(c)&&!/(you save|options|stars|reviews|shipping|pickup|add|sponsored|best seller|current price)/i.test(c)){title=c;break}}}const r=officialRow('Walmart',title,now,was,url,{evidence_group:'walmart-official-clearance',availability_label:'Official Walmart clearance. Online and local-store pricing/availability can differ.'});if(r)out.push(r)}return dedupe(out,60)}
async function walmartShared(){const statuses:any[]=[],url='https://www.walmart.com/shop/deals/clearance/?povid=EvergreenClearance_Facet_AllClearance';try{const got=parseWalmart(await mirror(url,22000),url);statuses.push({source:'Walmart official clearance',status:got.length?'AVAILABLE':'DEGRADED',products:got.length,strategy:'official_clearance_text_mirror'});return{rows:got,statuses}}catch(e){statuses.push({source:'Walmart official clearance',status:'UNAVAILABLE',products:0,strategy:'official_clearance_text_mirror',warning:e instanceof Error?e.message:String(e)});return{rows:[],statuses}}}

function parseTarget(text:string,url:string){const lines=String(text||'').split(/\r?\n/).map(x=>clean(x)).filter(Boolean),out:any[]=[];for(let i=0;i<lines.length;i++){if(!/^Clearance$/i.test(lines[i]))continue;let now:any=null,was:any=null;for(let j=Math.max(0,i-4);j<i;j++){if(now==null){const m=lines[j].match(/^\$([\d,.]+)$/);if(m)now=money(m[1])}const w=lines[j].match(/^reg\s*\$([\d,.]+)$/i);if(w)was=money(w[1])}if(!Number.isFinite(now)||!Number.isFinite(was)||pct(now,was)<40)continue;let title='';for(let j=i+1;j<Math.min(lines.length,i+6);j++){const c=stripMd(lines[j]);if(usefulTitle(c)&&!/(image:|button:|bought in last month|highly rated|sponsored)/i.test(c)){title=c;break}}const r=officialRow('Target',title,now,was,url,{evidence_group:'target-official-clearance',availability_label:'Official Target clearance. Store pricing and availability may vary.'});if(r)out.push(r)}return dedupe(out,45)}
async function targetShared(){const statuses:any[]=[],url='https://www.target.com/c/clearance/-/N-5q0ga';try{const got=parseTarget(await mirror(url,22000),url);statuses.push({source:'Target official clearance',status:got.length?'AVAILABLE':'DEGRADED',products:got.length,strategy:'official_clearance_text_mirror'});return{rows:got,statuses}}catch(e){statuses.push({source:'Target official clearance',status:'UNAVAILABLE',products:0,strategy:'official_clearance_text_mirror',warning:e instanceof Error?e.message:String(e)});return{rows:[],statuses}}}

function parseHarborFreight(text:string,url:string){const raw=String(text||''),out:any[]=[];const re=/\[([^\]]{8,340})\]\((https:\/\/www\.harborfreight\.com\/[^)]+)\)/gi;let m;while((m=re.exec(raw))){let label=stripMd(m[1]).replace(/^Add to List\s*/i,'').replace(/^Previous Next\s*/i,'').replace(/^\d+\s+Options?\s*/i,'').replace(/^\d+\s+Sizes?\s*/i,'').replace(/\s+Starting at\s+/i,' ');let price:any=null;const d=label.match(/(\d[\d,]*)\s+dollars?\s+and\s+(\d{1,2})\s+cents/i),c=label.match(/(?:^|\s)(\d{1,2})\s+cents\b/i);if(d){price=Number(String(d[1]).replace(/,/g,''))+Number(d[2])/100;label=label.slice(0,d.index).trim()}else if(c){price=Number(c[1])/100;label=label.slice(0,c.index).trim()}if(!Number.isFinite(price)||!usefulTitle(label))continue;const r=officialRow('Harbor Freight',label,price,null,url,{source_item_url:m[2],evidence_group:'harbor-freight-official-clearance',identity_confidence:'OFFICIAL_PRODUCT_URL_TITLE_PRICE',availability_label:'Official Harbor Freight clearance. Limited quantities; many items are in-store only.'});if(r){r.discount_pct=0;r.deep_discount=false;r.clearance_verified=true;out.push(r)}}return dedupe(out,90)}
async function harborFreightShared(){const statuses:any[]=[],url='https://www.harborfreight.com/merchandising-promotions/clearance.html';try{const got=parseHarborFreight(await mirror(url,20000),url);statuses.push({source:'Harbor Freight official clearance',status:got.length?'AVAILABLE':'DEGRADED',products:got.length,strategy:'official_clearance_text_mirror'});return{rows:got,statuses}}catch(e){statuses.push({source:'Harbor Freight official clearance',status:'UNAVAILABLE',products:0,strategy:'official_clearance_text_mirror',warning:e instanceof Error?e.message:String(e)});return{rows:[],statuses}}}

function parseFleetFarm(text:string,url:string){const lines=String(text||'').split(/\r?\n/).map(x=>clean(x)).filter(Boolean),out:any[]=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/^\$([\d,.]+)\s+CLEARANCE$/i);if(!m)continue;const now=money(m[1]);let was:any=null;for(let j=i+1;j<Math.min(lines.length,i+4);j++){const w=lines[j].match(/Reg\.\s*\$([\d,.]+)/i);if(w){was=money(w[1]);break}}if(!Number.isFinite(now)||!Number.isFinite(was)||pct(now,was)<40)continue;let title='';for(let j=i+1;j<Math.min(lines.length,i+8);j++){const c=stripMd(lines[j]);if(usefulTitle(c)&&!/(reg\.\s*\$|clearance|input|view special price|more styles|flat rate shipping)/i.test(c)){title=c;break}}const r=officialRow('Fleet Farm',title,now,was,url,{evidence_group:'fleet-farm-official-clearance',availability_label:'Official Fleet Farm clearance. Clearance stock is limited and not guaranteed.'});if(r)out.push(r)}return dedupe(out,50)}
async function fleetFarmShared(){const statuses:any[]=[],url='https://www.fleetfarm.com/promotion/p540109/home-improvement/_/N-3069115488';try{const got=parseFleetFarm(await mirror(url,22000),url);statuses.push({source:'Fleet Farm official Home Improvement clearance',status:got.length?'AVAILABLE':'DEGRADED',products:got.length,strategy:'official_clearance_text_mirror'});return{rows:got,statuses}}catch(e){statuses.push({source:'Fleet Farm official Home Improvement clearance',status:'UNAVAILABLE',products:0,strategy:'official_clearance_text_mirror',warning:e instanceof Error?e.message:String(e)});return{rows:[],statuses}}}

async function runShared(fast=false){
  const tasks=fast
    ? [homeDepotShared(6),walgreensShared(),walmartShared(),harborFreightShared()]
    : [homeDepotShared(14),walgreensShared(),walmartShared(),targetShared(),harborFreightShared(),fleetFarmShared()];
  const parts=await Promise.all(tasks),rows=parts.flatMap(x=>x.rows),statuses=parts.flatMap(x=>x.statuses);
  const coverage:any={menards:"local Ray's List remains exact-store and is merged in the Store view"};
  for(const r of rows){const k=txt(r.retailer).toLowerCase().replace(/[^a-z0-9]+/g,'_');coverage[k]=(coverage[k]||0)+1}
  return{items:rows,leads:rows,count:rows.length,source_status:statuses,coverage};
}

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});
  if(req.method!=='POST')return json({error:'POST_REQUIRED'},405);
  try{const body=await req.json().catch(()=>({})),action=txt(body.action||'shared');if(action==='shared'||action==='shared_fast')return json({ok:true,data:await runShared(action==='shared_fast')});return json({error:'UNKNOWN_ACTION'},400)}
  catch(e){return json({error:'H38_DEEP_SOURCES_ERROR',detail:e instanceof Error?e.message:String(e)},500)}
});
