import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const html = String.raw`<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#163650"><title>H38 Resale</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#eef3f6;color:#142735}.wrap{max-width:720px;margin:auto;padding:calc(14px + env(safe-area-inset-top)) 14px calc(28px + env(safe-area-inset-bottom))}.top{display:flex;align-items:center;gap:10px}.top a{text-decoration:none;color:#31526a;font-weight:750}.top h1{font-size:25px;margin:0}.card{background:#fff;border:1px solid #d7e1e7;border-radius:18px;padding:14px;margin:11px 0}.grid{display:grid;grid-template-columns:1fr 90px;gap:8px}input,select,button{font:inherit}input,select{width:100%;padding:12px;border:1px solid #c5d3dc;border-radius:12px}button{border:0;border-radius:12px;padding:12px 14px;background:#163650;color:#fff;font-weight:750;min-height:44px}.secondary{background:#dce7ed;color:#173449}.tabs{display:flex;gap:7px;overflow:auto}.tab{white-space:nowrap;background:#dce7ed;color:#173449}.tab.active{background:#163650;color:#fff}.status{font-size:13px;color:#5a6e7b;margin:8px 0}.controls{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:8px}.item{padding:13px 0;border-top:1px solid #e2e9ed}.item:first-child{border-top:0}.item h3{font-size:16px;margin:0 0 4px}.meta{font-size:12px;color:#657987}.money{font-weight:850;font-size:18px}.profit{color:#14642d}.loss{color:#8c2d2d}.badge{display:inline-block;border-radius:999px;background:#e6edf1;padding:4px 7px;font-size:11px;margin-right:4px}.good{background:#dff3e5}.warn{background:#fff1d7}.hidden{display:none}.empty{text-align:center;color:#71828c;padding:24px 8px}.more{width:100%;background:#dce7ed;color:#173449}@media(max-width:480px){.grid{grid-template-columns:1fr 80px}.controls{grid-template-columns:1fr}.top h1{font-size:22px}}</style></head>
<body data-h38-resale-web="saved-leads-v10"><main class="wrap"><div class="top"><a href="/functions/v1/h38-deals-shell">‹ H38 Deals</a><h1>Resale</h1></div><section id="locked" class="card hidden"><h2>Not enabled</h2><p>This account does not include Resale.</p></section><div id="app" class="hidden"><section class="card"><div class="grid"><input id="zip" inputmode="numeric" maxlength="5" placeholder="ZIP code"><select id="radius"><option>25</option><option selected>50</option><option>75</option><option>100</option></select><button id="loc" class="secondary" style="grid-column:1/-1">Use phone location</button></div><div id="status" class="status">Loading saved H38 buy leads…</div></section><div class="tabs"><button class="tab active" data-tab="deals">Profit Deals</button><button class="tab" data-tab="facebook">Facebook</button><button class="tab" data-tab="auctions">Auctions</button><button class="tab" data-tab="stores">Nearby Stores</button><button class="tab" data-tab="garage">Garage/Estate</button></div><section class="card"><div class="controls"><input id="search" type="search" placeholder="Search results"><button id="scan">Scan Profit Deals</button></div><section id="content"><div class="empty">Loading saved H38 buy leads…</div></section></section></div></main>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.95.0/dist/umd/supabase.min.js" onerror="this.onerror=null;this.src='https://unpkg.com/@supabase/supabase-js@2.95.0/dist/umd/supabase.min.js'"></script>
<script>
const SUPABASE_URL='https://jqukmwtsgcsaruucnqja.supabase.co';
const KEY='sb_publishable_XrF41kGmTC2SmSTgPvo5OQ_vqcBd0N1';
const sb=supabase.createClient(SUPABASE_URL,KEY);const $=id=>document.getElementById(id);let tab='deals',cache={},lat=null,lon=null,visible=20;const LOCATION_KEY='h38-resale-location-v1';
const txt=v=>String(v==null?'':v).trim(),num=v=>Number(v);
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function saveLocation(){localStorage.setItem(LOCATION_KEY,JSON.stringify({zip:$('zip').value.trim(),radius:$('radius').value,lat:lat,lon:lon}));}function restoreLocation(){try{const x=JSON.parse(localStorage.getItem(LOCATION_KEY)||'{}');$('zip').value=x.zip||'';$('radius').value=x.radius||'50';lat=Number.isFinite(x.lat)?x.lat:null;lon=Number.isFinite(x.lon)?x.lon:null;}catch(e){}}function payload(){saveLocation();return {postal:$('zip').value.trim(),zip:$('zip').value.trim(),radius_miles:num($('radius').value),radius:num($('radius').value),lat:lat,lon:lon,deep_verify:true,terms:['tools','electronics','appliances','lawn mower','generator','toolbox']};}
function rows(d,source){if(Array.isArray(d))return d;if(!d)return[];if(source==='deals')return[].concat(Array.isArray(d.opportunities)?d.opportunities:[],Array.isArray(d.candidates)?d.candidates.map(function(x){return Object.assign({verification_status:'CANDIDATE · NEEDS SOLD COMPS'},x);}):[],Array.isArray(d.auction_candidates)?d.auction_candidates:[]);if(source==='facebook')return(Array.isArray(d.results)&&d.results.length?d.results:[]).concat(Array.isArray(d.candidates)?d.candidates.map(function(x){return Object.assign({verification_status:'LOCATION NEEDS PROOF'},x);}):[]);if(source==='stores')return Array.isArray(d.stores)?d.stores:(Array.isArray(d.readings)?d.readings:[]);if(Array.isArray(d.results))return d.results;if(Array.isArray(d.deals))return d.deals;if(Array.isArray(d.items))return d.items;if(Array.isArray(d.rows))return d.rows;return [];}
async function api(action){const q=await sb.functions.invoke('h38-resale-api',{body:{action:action,payload:payload()}});if(q.error)throw q.error;if(q.data&&q.data.error)throw new Error(q.data.error);return q.data?q.data.data:null;}
function first(r,keys,min){for(let i=0;i<keys.length;i++){const x=num(r[keys[i]]);if(Number.isFinite(x)&&x>=min)return x;}return NaN;}
function price(r){return first(r,['buy_price','price','current_price','sale_price','asking_price','bid'],0);}
function resale(r){return first(r,['expected_resale','resale_price','market_value','estimated_value','comparable_price'],0.000001);}
function profit(r){const b=price(r),s=resale(r),fees=num(r.estimated_fees||r.fees||0),ship=num(r.estimated_shipping||r.shipping||0),other=num(r.other_costs||0);return Number.isFinite(b)&&Number.isFinite(s)?s-b-fees-ship-other:NaN;}
function title(r){return txt(r.title||r.name||r.store_name||r.item_name||r.event_name||'Opportunity');}
function sourceLink(r){const u=txt(r.url||r.source_url||r.listing_url);return u.startsWith('https://')?'<a href="'+esc(u)+'" target="_blank" rel="noopener" style="font-size:12px">Open source</a>':'';}
function card(r){if(tab==='stores')return '<div class="item"><h3>'+esc(title(r))+'</h3><span class="badge good">NEARBY STORE</span><div class="meta">'+esc(txt(r.store_address||r.address||''))+(Number.isFinite(num(r.distance_miles))?' · '+num(r.distance_miles).toFixed(1)+' miles':'')+'</div><div class="meta">'+esc(txt(r.retailer||r.source||''))+'</div></div>';const p=price(r),s=resale(r),pr=profit(r),roi=Number.isFinite(pr)&&Number.isFinite(p)&&p>0?pr/p*100:NaN,proof=txt(r.verification_status||r.location_status||r.price_scope||r.provider_status),good=Number.isFinite(pr)&&pr>=15&&roi>=25;return '<div class="item"><h3>'+esc(title(r))+'</h3><div>'+(good?'<span class="badge good">BUY CANDIDATE</span>':'<span class="badge">REVIEW</span>')+(proof?'<span class="badge warn">'+esc(proof)+'</span>':'')+'</div><div class="money">'+(Number.isFinite(p)?'Buy $'+p.toFixed(2):'Buy price unknown')+(Number.isFinite(s)?' → resale $'+s.toFixed(2):'')+'</div><div class="meta">'+(Number.isFinite(pr)?'<span class="'+(pr>=0?'profit':'loss')+'">Profit $'+pr.toFixed(2)+(Number.isFinite(roi)?' · '+Math.round(roi)+'% ROI':'')+'</span> · ':'')+esc(txt(r.retailer||r.source||r.marketplace||r.location_label||''))+'</div>'+sourceLink(r)+'</div>';}
function scanSummary(d,r){if(r.length)return r.length+' '+tab+' results returned.';if(d&&d.warning)return tab+' returned no current results: '+d.warning;if(d&&d.provider_status)return tab+' status: '+d.provider_status+'. No current results.';return tab+' completed with no current verified or candidate results.';}
async function load(){visible=20;$('content').innerHTML='<div class="empty">Scanning '+esc(tab)+'…</div>';try{var d=await api(tab);cache[tab]=rows(d,tab);$('status').textContent=scanSummary(d,cache[tab]);render();}catch(e){$('status').textContent=tab+' failed: '+e.message;$('content').innerHTML='<div class="empty">Source unavailable. Your other tabs remain usable.</div>';}}
async function loadSavedDeals(){visible=20;$('content').innerHTML='<div class="empty">Loading saved H38 buy leads…</div>';try{const d=await api('saved');cache.deals=rows(d,'deals');$('status').textContent=cache.deals.length?cache.deals.length+' saved H38 buy leads loaded. These are leads, not verified profit. Sold comps, fees and local availability still need verification. Tap Scan Profit Deals for a live source check.':'No saved H38 resale leads are available yet. Tap Scan Profit Deals for a live source check.';render();}catch(e){$('status').textContent='Saved resale leads could not load: '+e.message;$('content').innerHTML='<div class="empty">Tap Scan Profit Deals for a live source check.</div>';}}
function render(){let q=$('search').value.trim().toLowerCase(),r=(cache[tab]||[]).filter(function(x){return !q||JSON.stringify([title(x),x.retailer,x.source,x.location_label,x.store_name,x.store_address]).toLowerCase().includes(q)});if(tab==='deals')r.sort(function(a,b){const pa=profit(a),pb=profit(b);return (Number.isFinite(pb)?pb:-9999)-(Number.isFinite(pa)?pa:-9999);});$('content').innerHTML=r.length?r.slice(0,visible).map(card).join('')+(r.length>visible?'<button id="more" class="more">Show '+Math.min(20,r.length-visible)+' more</button>':''):'<div class="empty">No current verified or candidate rows returned from this source.</div>';if($('more'))$('more').onclick=function(){visible+=20;render();};}
function selectTab(which){tab=which;visible=20;document.querySelectorAll('.tab').forEach(function(b){b.classList.toggle('active',b.dataset.tab===tab);});$('scan').textContent='Scan '+document.querySelector('.tab.active').textContent;if(cache[tab])render();else $('content').innerHTML='<div class="empty">Tap '+esc($('scan').textContent)+' when you are ready.</div>';}document.querySelectorAll('.tab').forEach(function(b){b.onclick=function(){selectTab(b.dataset.tab);};});$('scan').onclick=load;$('search').oninput=render;$('zip').onchange=function(){lat=null;lon=null;cache={};saveLocation();if(tab==='deals')loadSavedDeals();};$('radius').onchange=function(){cache={};saveLocation();if(tab==='deals')loadSavedDeals();};$('loc').onclick=function(){if(window.AndroidH38Deals&&AndroidH38Deals.requestLocation)AndroidH38Deals.requestLocation();else if(navigator.geolocation)navigator.geolocation.getCurrentPosition(function(p){window.H38NativeLocationResult(p.coords.latitude,p.coords.longitude);},function(){$('status').textContent='Location unavailable. Enter a ZIP instead.';},{timeout:12000});else $('status').textContent='Location unavailable. Enter a ZIP instead.';};window.H38NativeLocationResult=function(a,b){lat=Number(a);lon=Number(b);$('zip').value='';cache={};saveLocation();$('status').textContent='Phone location saved. Loading saved resale leads…';if(tab==='deals')loadSavedDeals();};
async function gate(){const session=(await sb.auth.getSession()).data.session;if(!session){location.href='/functions/v1/h38-deals-shell';return;}const q=await sb.from('h38_product_entitlements').select('active,expires_at').eq('product_key','resale').maybeSingle();const ok=!!(q.data&&q.data.active&&(!q.data.expires_at||new Date(q.data.expires_at)>new Date()));$('app').classList.toggle('hidden',!ok);$('locked').classList.toggle('hidden',ok);if(ok){restoreLocation();selectTab('deals');await loadSavedDeals();}}gate();
</script><style>
.handoff{border-left:4px solid #163650}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.action{display:inline-block;border:1px solid #bdccd5;border-radius:9px;padding:7px 9px;background:#f6f9fa;color:#173449;font-size:12px;font-weight:800;text-decoration:none}
</style><script>
// Connected-app UX v10. Reuse one shopping location and accept a deal for
// evaluation without automatically starting a marketplace scan.
const H38_SHARED_LOCATION='h38-shopping-location-v1';
function sharedSaveLocation(){const x={zip:$('zip').value.trim(),radius:$('radius').value,radiusMiles:num($('radius').value),lat:lat,lon:lon};localStorage.setItem(H38_SHARED_LOCATION,JSON.stringify(x));localStorage.setItem(LOCATION_KEY,JSON.stringify(x));}
saveLocation=sharedSaveLocation;
const h38RestoreLocation=restoreLocation;
restoreLocation=function(){try{const x=JSON.parse(localStorage.getItem(H38_SHARED_LOCATION)||localStorage.getItem(LOCATION_KEY)||'{}');$('zip').value=x.zip||'';$('radius').value=String(x.radius||x.radiusMiles||'50');lat=Number.isFinite(x.lat)?x.lat:null;lon=Number.isFinite(x.lon)?x.lon:null;if(Object.keys(x).length)localStorage.setItem(H38_SHARED_LOCATION,JSON.stringify(x));}catch(e){h38RestoreLocation();}};
function handoffQuery(){const p=new URLSearchParams(location.search);return{item:txt(p.get('item')),store:txt(p.get('store')),upc:txt(p.get('upc')),sku:txt(p.get('sku')),buy:txt(p.get('buy'))}}
function couponLink(r){const q=new URLSearchParams(),name=title(r),p=price(r);if(name)q.set('item',name);if(r.retailer)q.set('store',r.retailer);if(r.upc)q.set('upc',r.upc);if(r.sku)q.set('sku',r.sku);if(Number.isFinite(p))q.set('buy',String(p));return'/functions/v1/h38-coupon-web?'+q.toString()}
const h38ResaleCard=card;
card=function(r){const html=h38ResaleCard(r);if(tab==='stores')return html;const i=html.lastIndexOf('</div>'),actions='<div class="actions"><a class="action" href="'+esc(couponLink(r))+'">Build coupon stack</a></div>';return i<0?html:html.slice(0,i)+actions+html.slice(i)};
const h38SelectTab=selectTab;
selectTab=function(which){h38SelectTab(which);if(cache[which]&&cache[which].length===0)$('content').innerHTML='<div class="empty"><strong>No results returned.</strong><p>This can mean the source is unavailable or has no verified matches. It is not proof that no resale opportunities exist.</p></div>'};
function applyHandoff(attempt){if($('app').classList.contains('hidden')){if(attempt<100)setTimeout(function(){applyHandoff(attempt+1)},100);return}restoreLocation();const h=handoffQuery();if(h.item||h.upc||h.sku){$('search').value=h.item||h.upc||h.sku;const card=document.createElement('section');card.className='card handoff';card.innerHTML='<strong>Deal ready to evaluate</strong><div class="meta">'+esc([h.item,h.store,h.upc?'UPC '+h.upc:'',h.sku?'SKU '+h.sku:'',h.buy?'Buy $'+h.buy:''].filter(Boolean).join(' · '))+'</div><p class="meta">Saved H38 buy leads load automatically. Tap Scan Profit Deals for live source evidence. H38 will not call this a proven flip until sold comps, fees and availability are verified.</p>';$('app').insertBefore(card,$('app').children[1]);}}
applyHandoff(0);
</script></body></html>`;
Deno.serve(()=>new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','content-security-policy':"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; connect-src 'self' https://jqukmwtsgcsaruucnqja.supabase.co wss://jqukmwtsgcsaruucnqja.supabase.co; style-src 'self' 'unsafe-inline'; frame-ancestors 'self'"}}));
