(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.H38_ACCOUNTING_ENGINE=Object.freeze(api);
})(typeof window!=='undefined'?window:null,function(){
  'use strict';
  const VERSION='20260927-wave1-accounting-core-1';
  const TYPES=Object.freeze(['asset','liability','equity','income','cogs','expense','other-income','other-expense']);
  const DEFAULT_ACCOUNTS=Object.freeze([
    ['1000','Operating Checking','asset','Banking'],['1010','Savings','asset','Banking'],['1100','Accounts Receivable','asset','Receivables'],['1200','Undeposited Funds','asset','Receivables'],['1300','Inventory','asset','Inventory'],['1500','Equipment & Fixed Assets','asset','Assets'],
    ['2000','Accounts Payable','liability','Payables'],['2100','Credit Cards Payable','liability','Cards'],['2200','Loans Payable','liability','Loans'],['2300','Customer Deposits','liability','Deposits'],
    ['3000','Owner Equity','equity','Equity'],['4000','Service Revenue','income','Revenue'],['4100','Other Revenue','other-income','Revenue'],
    ['5000','Materials / Cost of Goods Sold','cogs','Job Cost'],['5100','Direct Labor / Cost of Goods Sold','cogs','Job Cost'],['5200','Equipment / Cost of Goods Sold','cogs','Job Cost'],
    ['6000','Operating Expense','expense','Operating'],['6100','Fuel','expense','Operating'],['6200','Insurance','expense','Operating'],['6300','Rent','expense','Operating'],['6400','Software & Subscriptions','expense','Operating'],['6500','Bank & Processor Fees','expense','Operating'],['6600','Mileage & Reimbursements','expense','Operating'],['6700','Repairs & Maintenance','expense','Operating']
  ].map(([code,name,type,group])=>Object.freeze({id:`ACCT-${code}`,code,name,type,group,active:true})));
  function text(v){return String(v==null?'':v).trim();}
  function cents(v){const n=Number(v||0);if(!Number.isFinite(n))throw new Error('Amount must be a finite number.');return Math.round(n*100);}
  function amount(c){return Math.round(Number(c||0))/100;}
  function id(prefix='ACC'){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9).toUpperCase()}`;}
  function requireText(v,msg){const out=text(v);if(!out)throw new Error(msg);return out;}
  function normalizeAccount(account){const type=text(account?.type).toLowerCase();if(!TYPES.includes(type))throw new Error(`Unsupported account type: ${type||'blank'}.`);return {...account,id:requireText(account.id,'Account ID is required.'),name:requireText(account.name,'Account name is required.'),type,code:text(account.code),active:account.active!==false};}
  function chart(custom=[]){const map=new Map(DEFAULT_ACCOUNTS.map(a=>[a.id,{...a}]));(custom||[]).forEach(a=>{const n=normalizeAccount(a);map.set(n.id,n);});return Array.from(map.values());}
  function accountMap(accounts=[]){return new Map(chart(accounts).map(a=>[a.id,a]));}
  function normalizeLine(line,index,accounts){const accountId=requireText(line?.accountId,`Line ${index+1} account is required.`);if(accounts&&!accounts.has(accountId))throw new Error(`Line ${index+1} uses unknown account ${accountId}.`);const debit=cents(line?.debit||0),credit=cents(line?.credit||0);if(debit<0||credit<0)throw new Error(`Line ${index+1} cannot contain a negative debit or credit.`);if((debit>0)===(credit>0))throw new Error(`Line ${index+1} must have exactly one debit or credit amount.`);return {...line,accountId,debit:amount(debit),credit:amount(credit),debitCents:debit,creditCents:credit};}
  function validateTransaction(tx,accounts=[]){if(!tx||typeof tx!=='object')throw new Error('Accounting transaction is required.');const amap=accountMap(accounts);const lines=(tx.lines||[]).map((line,i)=>normalizeLine(line,i,amap));if(lines.length<2)throw new Error('An accounting transaction needs at least two lines.');const debits=lines.reduce((s,l)=>s+l.debitCents,0),credits=lines.reduce((s,l)=>s+l.creditCents,0);if(debits!==credits)throw new Error(`Accounting transaction is out of balance by ${amount(Math.abs(debits-credits)).toFixed(2)}.`);if(debits<=0)throw new Error('Accounting transaction total must be greater than zero.');return {...tx,id:requireText(tx.id||tx.transactionId,'Transaction ID is required.'),businessId:requireText(tx.businessId,'Business ID is required.'),date:requireText(tx.date,'Transaction date is required.'),status:text(tx.status||'Posted'),lines,total:amount(debits),debitTotal:amount(debits),creditTotal:amount(credits),balanced:true};}
  function transaction({transactionId,businessId,date,type,sourceType,sourceId,memo,lines,createdBy,approvalId,reversalOf}){return validateTransaction({id:transactionId||id('GL'),transactionId:transactionId||undefined,businessId,date,type:requireText(type,'Transaction type is required.'),sourceType:text(sourceType),sourceId:text(sourceId),memo:text(memo),status:'Posted',createdBy:text(createdBy),approvalId:text(approvalId),reversalOf:text(reversalOf),createdAt:new Date().toISOString(),lines});}
  function reverse(original,{transactionId,date,businessId,createdBy,memo}={}){const tx=validateTransaction(original);if(text(tx.status).toLowerCase()==='reversed')throw new Error('Transaction is already reversed.');return transaction({transactionId:transactionId||id('REV'),businessId:businessId||tx.businessId,date:date||tx.date,type:'reversal',sourceType:'Accounting Transaction',sourceId:tx.id,reversalOf:tx.id,memo:memo||`Reversal of ${tx.id}`,createdBy,lines:tx.lines.map(l=>({accountId:l.accountId,debit:l.credit,credit:l.debit,customerId:l.customerId,vendorId:l.vendorId,jobId:l.jobId,description:`Reversal: ${l.description||tx.memo||tx.id}`}))});}
  function invoicePosting({businessId,invoiceId,date,total,revenueAccountId='ACCT-4000',arAccountId='ACCT-1100',customerId,jobId,memo}){const a=amount(cents(total));if(a<=0)throw new Error('Invoice total must be greater than zero.');return transaction({businessId,date,type:'customer-invoice',sourceType:'Invoice',sourceId:invoiceId,memo:memo||`Invoice ${invoiceId}`,lines:[{accountId:arAccountId,debit:a,customerId,jobId,description:'Customer balance due'},{accountId:revenueAccountId,credit:a,customerId,jobId,description:'Revenue'}]});}
  function customerPaymentPosting({businessId,paymentId,date,amount:raw,customerId,invoiceId,bankAccountId='ACCT-1200',arAccountId='ACCT-1100',memo}){const a=amount(cents(raw));if(a<=0)throw new Error('Payment amount must be greater than zero.');return transaction({businessId,date,type:'customer-payment',sourceType:'Payment',sourceId:paymentId,memo:memo||`Customer payment ${paymentId}`,lines:[{accountId:bankAccountId,debit:a,customerId,description:'Payment received'},{accountId:arAccountId,credit:a,customerId,description:`Applied to invoice ${invoiceId||''}`}]});}
  function vendorBillPosting({businessId,billId,date,total,vendorId,jobId,expenseAccountId='ACCT-6000',apAccountId='ACCT-2000',memo}){const a=amount(cents(total));if(a<=0)throw new Error('Vendor bill total must be greater than zero.');return transaction({businessId,date,type:'vendor-bill',sourceType:'Vendor Bill',sourceId:billId,memo:memo||`Vendor bill ${billId}`,lines:[{accountId:expenseAccountId,debit:a,vendorId,jobId,description:'Expense / cost recognized'},{accountId:apAccountId,credit:a,vendorId,jobId,description:'Vendor balance due'}]});}
  function vendorPaymentPosting({businessId,paymentId,date,amount:raw,vendorId,billIds=[],bankAccountId='ACCT-1000',apAccountId='ACCT-2000',memo}){const a=amount(cents(raw));if(a<=0)throw new Error('Vendor payment amount must be greater than zero.');return transaction({businessId,date,type:'vendor-payment',sourceType:'Vendor Payment',sourceId:paymentId,memo:memo||`Vendor payment ${paymentId}`,lines:[{accountId:apAccountId,debit:a,vendorId,description:`Bills ${billIds.join(', ')}`},{accountId:bankAccountId,credit:a,vendorId,description:'Cash paid'}]});}
  function expensePosting({businessId,expenseId,date,total,vendorId,jobId,expenseAccountId='ACCT-6000',fundingAccountId='ACCT-1000',memo}){const a=amount(cents(total));if(a<=0)throw new Error('Expense total must be greater than zero.');return transaction({businessId,date,type:'expense-paid',sourceType:'Expense',sourceId:expenseId,memo:memo||`Expense ${expenseId}`,lines:[{accountId:expenseAccountId,debit:a,vendorId,jobId,description:'Expense'},{accountId:fundingAccountId,credit:a,vendorId,jobId,description:'Paid'}]});}
  function groupedBalance(transactions=[],accounts=[]){const amap=accountMap(accounts),out={};chart(accounts).forEach(a=>out[a.id]={account:a,debits:0,credits:0,balance:0});for(const raw of transactions||[]){const tx=validateTransaction(raw,accounts);if(text(tx.status).toLowerCase()==='void')continue;for(const line of tx.lines){if(!out[line.accountId])out[line.accountId]={account:amap.get(line.accountId)||{id:line.accountId,name:line.accountId,type:'asset'},debits:0,credits:0,balance:0};out[line.accountId].debits+=line.debit;out[line.accountId].credits+=line.credit;}}Object.values(out).forEach(row=>{const t=row.account.type;row.balance=['liability','equity','income','other-income'].includes(t)?amount(cents(row.credits-row.debits)):amount(cents(row.debits-row.credits));row.debits=amount(cents(row.debits));row.credits=amount(cents(row.credits));});return out;}
  function trialBalance(transactions=[],accounts=[]){return Object.values(groupedBalance(transactions,accounts)).filter(r=>r.debits||r.credits).sort((a,b)=>String(a.account.code).localeCompare(String(b.account.code)));}
  function profitAndLoss(transactions=[],accounts=[]){const rows=Object.values(groupedBalance(transactions,accounts));let income=0,cogs=0,expense=0,otherIncome=0,otherExpense=0;rows.forEach(r=>{if(r.account.type==='income')income+=r.balance;else if(r.account.type==='cogs')cogs+=r.balance;else if(r.account.type==='expense')expense+=r.balance;else if(r.account.type==='other-income')otherIncome+=r.balance;else if(r.account.type==='other-expense')otherExpense+=r.balance;});const grossProfit=income-cogs,operatingProfit=grossProfit-expense,netIncome=operatingProfit+otherIncome-otherExpense;return {income:amount(cents(income)),cogs:amount(cents(cogs)),grossProfit:amount(cents(grossProfit)),operatingExpenses:amount(cents(expense)),operatingProfit:amount(cents(operatingProfit)),otherIncome:amount(cents(otherIncome)),otherExpense:amount(cents(otherExpense)),netIncome:amount(cents(netIncome))};}
  function balanceSheet(transactions=[],accounts=[]){const rows=Object.values(groupedBalance(transactions,accounts));const sum=t=>amount(cents(rows.filter(r=>r.account.type===t).reduce((s,r)=>s+r.balance,0)));const assets=sum('asset'),liabilities=sum('liability'),equity=sum('equity'),earnings=profitAndLoss(transactions,accounts).netIncome;return{assets,liabilities,equity:amount(cents(equity+earnings)),retainedCurrentEarnings:earnings,difference:amount(cents(assets-liabilities-equity-earnings))};}
  function ageBucket(days){if(days<=0)return'current';if(days<=30)return'1-30';if(days<=60)return'31-60';if(days<=90)return'61-90';return'90+';}
  function daysBetween(asOf,due){const a=new Date(`${asOf}T00:00:00Z`),d=new Date(`${due}T00:00:00Z`);if(Number.isNaN(+a)||Number.isNaN(+d))return 0;return Math.floor((a-d)/86400000);}
  function aging(rows=[],{asOf=new Date().toISOString().slice(0,10),balanceKeys=['Balance','Balance Due','Open Balance','Amount Due'],dueKeys=['Due Date','dueDate']}={}){const buckets={'current':0,'1-30':0,'31-60':0,'61-90':0,'90+':0},items=[];for(const row of rows||[]){let bal=0;for(const k of balanceKeys){if(row?.[k]!=null&&row[k]!==''){bal=Number(row[k])||0;break;}}if(bal<=0)continue;let due='';for(const k of dueKeys){if(row?.[k]){due=String(row[k]).slice(0,10);break;}}const days=daysBetween(asOf,due||asOf),bucket=ageBucket(days);buckets[bucket]=amount(cents(buckets[bucket]+bal));items.push({row,balance:amount(cents(bal)),dueDate:due,daysOverdue:Math.max(0,days),bucket});}return {asOf,buckets,total:amount(cents(Object.values(buckets).reduce((a,b)=>a+b,0))),items:items.sort((a,b)=>b.daysOverdue-a.daysOverdue)};}
  function arAging(invoices,asOf){return aging((invoices||[]).filter(r=>!/void|delet/i.test(text(r.Status||r.status))),{asOf,balanceKeys:['Balance','Balance Due','Open Balance','Amount Due'],dueKeys:['Due Date','dueDate']});}
  function apAging(bills,asOf){return aging((bills||[]).filter(r=>!/void|cancel/i.test(text(r.Status||r.status))),{asOf,balanceKeys:['Open Balance','Balance','Amount Due','Total'],dueKeys:['Due Date','dueDate']});}
  function billsToPay(bills=[],{asOf=new Date().toISOString().slice(0,10),horizonDays=7}={}){const today=new Date(`${asOf}T00:00:00Z`),limit=new Date(today.getTime()+horizonDays*86400000);return (bills||[]).map(row=>{const balance=Number(row['Open Balance']??row.Balance??row['Amount Due']??row.Total??0)||0,due=String(row['Due Date']||row.dueDate||asOf).slice(0,10),d=new Date(`${due}T00:00:00Z`),days=Math.floor((d-today)/86400000),status=days<0?'Overdue':days===0?'Due today':d<=limit?'Due this week':'Later';return{row,balance:amount(cents(balance)),dueDate:due,daysUntilDue:days,status,recommended:balance>0&&days<=horizonDays,reason:days<0?`${Math.abs(days)} day${Math.abs(days)===1?'':'s'} overdue`:days===0?'Due today':days<=horizonDays?`Due in ${days} day${days===1?'':'s'}`:'Outside current payment window'};}).filter(x=>x.balance>0).sort((a,b)=>a.daysUntilDue-b.daysUntilDue||b.balance-a.balance);}
  function prepareCheck({businessId,checkId,bankAccountId,checkNumber,payee,amount:raw,date,memo,billIds=[],approvedBy}){const a=amount(cents(raw));if(a<=0)throw new Error('Check amount must be greater than zero.');return{id:checkId||id('CHECK'),'Check ID':checkId||undefined,'Business ID':requireText(businessId,'Business ID is required.'),'Bank Account ID':requireText(bankAccountId,'Checking account is required.'),'Check Number':requireText(checkNumber,'Check number is required.'),'Payee':requireText(payee,'Payee is required.'),'Amount':a,'Payment Date':requireText(date,'Payment date is required.'),'Memo':text(memo),'Bill IDs':Array.from(new Set(billIds.map(text).filter(Boolean))),'Status':'Prepared — Owner Approval Required','Approved By':text(approvedBy),'Negotiable':false,'Created Time':new Date().toISOString()};}
  function prepareElectronicPayment({businessId,instructionId,vendorId,payee,amount:raw,date,fundingAccountId,billIds=[],memo,method='ACH / provider handoff'}){const a=amount(cents(raw));if(a<=0)throw new Error('Electronic payment amount must be greater than zero.');return{id:instructionId||id('PAYINST'),'Payment Instruction ID':instructionId||undefined,'Business ID':requireText(businessId,'Business ID is required.'),'Vendor ID':text(vendorId),'Payee':requireText(payee,'Payee is required.'),'Amount':a,'Scheduled Date':requireText(date,'Scheduled date is required.'),'Funding Account ID':requireText(fundingAccountId,'Funding account is required.'),'Bill IDs':Array.from(new Set(billIds.map(text).filter(Boolean))),'Memo':text(memo),'Method':method,'Status':'Prepared — Owner Approval Required','External Transfer Occurred':false,'Created Time':new Date().toISOString()};}
  function reconcile({statementEndingBalance,ledgerOpeningBalance=0,cleared=[],bankOnly=[],officeOnly=[]}){const statement=cents(statementEndingBalance),opening=cents(ledgerOpeningBalance);let clearedNet=0;for(const item of cleared||[]){const sign=text(item.direction).toLowerCase()==='out'||Number(item.amount)<0?-1:1;clearedNet+=Math.abs(cents(item.amount))*sign;}const calculated=opening+clearedNet,difference=statement-calculated;return{statementEndingBalance:amount(statement),calculatedClearedBalance:amount(calculated),difference:amount(difference),balanced:difference===0,bankOnly:bankOnly||[],officeOnly:officeOnly||[],explanation:difference===0?'Office cleared activity matches the statement ending balance.':`Office is ${difference>0?'below':'above'} the statement by ${amount(Math.abs(difference)).toFixed(2)}. Review unmatched bank activity, uncleared Office items, bank fees, duplicates, and missing transactions.`};}
  function creditCardReview(charges=[],receipts=[]){const receiptRefs=new Set((receipts||[]).map(r=>text(r['Charge ID']||r.chargeId||r['Card Transaction ID'])));const missing=(charges||[]).filter(c=>!receiptRefs.has(text(c['Charge ID']||c.chargeId||c['Card Transaction ID'])));return{charges:(charges||[]).length,missingReceipts:missing,missingReceiptCount:missing.length,total:amount(cents((charges||[]).reduce((s,c)=>s+Math.abs(Number(c.Amount||c.amount||0)),0)))};}
  function jobProfitability({quotedRevenue=0,invoicedRevenue=0,collectedRevenue=0,labor=0,materials=0,equipment=0,subcontractors=0,mileage=0,expenses=0,purchaseOrders=0,vendorBills=0,overhead=0}={}){const cost=[labor,materials,equipment,subcontractors,mileage,expenses,purchaseOrders,vendorBills,overhead].reduce((s,n)=>s+(Number(n)||0),0),revenue=Number(invoicedRevenue||quotedRevenue||0)||0,grossProfit=revenue-cost,margin=revenue?grossProfit/revenue:0;return{quotedRevenue:amount(cents(quotedRevenue)),invoicedRevenue:amount(cents(invoicedRevenue)),collectedRevenue:amount(cents(collectedRevenue)),cost:amount(cents(cost)),grossProfit:amount(cents(grossProfit)),grossMargin:Number(margin.toFixed(4))};}
  function cashProjection({cashOnHand=0,expectedReceipts=[],approvedBills=[],payrollObligations=[],recurringExpenses=[],otherPayments=[]}={}){const incoming=(expectedReceipts||[]).reduce((s,r)=>s+(Number(r.amount||r.Amount||0)||0),0),outgoing=[approvedBills,payrollObligations,recurringExpenses,otherPayments].flat().reduce((s,r)=>s+(Number(r.amount||r.Amount||r.balance||0)||0),0);return{cashOnHand:amount(cents(cashOnHand)),expectedIncoming:amount(cents(incoming)),knownOutgoing:amount(cents(outgoing)),projectedAvailable:amount(cents(Number(cashOnHand||0)+incoming-outgoing)),assumptions:['Includes only supplied cash, expected receipts, approved/known obligations, recurring expenses, and other supplied payments.','Does not guarantee receipt timing or bank availability.','Does not execute or authorize payments.']};}
  function monthEndChecklist({bankReconciliations=[],cardReconciliations=[],receipts=[],expenses=[],bills=[],payments=[],deposits=[],duplicates=[],inventoryExceptions=[],payrollPeriods=[]}={}){const issues=[];if((bankReconciliations||[]).some(r=>r.balanced===false||/open|in progress/i.test(text(r.Status||r.status))))issues.push({code:'BANK_UNRECONCILED',label:'Unreconciled bank activity'});if((cardReconciliations||[]).some(r=>r.balanced===false||/open|in progress/i.test(text(r.Status||r.status))))issues.push({code:'CARD_UNRECONCILED',label:'Unreconciled credit-card activity'});const missingReceipts=(expenses||[]).filter(e=>String(e['Receipt Required']||e.receiptRequired||'').toLowerCase()==='yes'&&!text(e['Receipt ID']||e.receiptId));if(missingReceipts.length)issues.push({code:'MISSING_RECEIPTS',label:`${missingReceipts.length} expense${missingReceipts.length===1?'':'s'} missing receipts`});const unpaid=(bills||[]).filter(b=>(Number(b['Open Balance']??b.Balance??b.Total??0)||0)>0);if(unpaid.length)issues.push({code:'UNPAID_BILLS',label:`${unpaid.length} unpaid vendor bill${unpaid.length===1?'':'s'}`});const unapplied=(payments||[]).filter(p=>!text(p['Invoice ID']||p.invoiceId)&&!text(p['Applied To']||p.appliedTo));if(unapplied.length)issues.push({code:'UNAPPLIED_PAYMENTS',label:`${unapplied.length} unapplied customer payment${unapplied.length===1?'':'s'}`});const unpostedDeposits=(deposits||[]).filter(d=>!/reconciled|posted/i.test(text(d.Status||d.status)));if(unpostedDeposits.length)issues.push({code:'OUTSTANDING_DEPOSITS',label:`${unpostedDeposits.length} outstanding deposit${unpostedDeposits.length===1?'':'s'}`});if((duplicates||[]).length)issues.push({code:'DUPLICATES',label:`${duplicates.length} duplicate transaction candidate${duplicates.length===1?'':'s'}`});if((inventoryExceptions||[]).length)issues.push({code:'INVENTORY_EXCEPTION',label:`${inventoryExceptions.length} inventory exception${inventoryExceptions.length===1?'':'s'}`});if((payrollPeriods||[]).some(p=>!/approved|exported|complete/i.test(text(p.Status||p.status))))issues.push({code:'PAYROLL_OPEN',label:'Payroll preparation period still open'});return{readyToClose:issues.length===0,issues,issueCount:issues.length};}
  function quickBooksAdapterState({connected=false,lastSync='',pending=0,conflicts=0,error='',companyId='' }={}){return{provider:'QuickBooks Online',mode:connected?'connected':'external-gate',connected:!!connected,companyId:text(companyId),lastSync:text(lastSync),pending:Number(pending||0),conflicts:Number(conflicts||0),error:text(error),sourceOfTruth:'H38 Office remains operational; QuickBooks is optional synchronization/accountant ledger.',liveActivationRequired:!connected};}
  function duplicateKey(record,kind){const norm=s=>text(s).toLowerCase().replace(/[^a-z0-9]/g,'');if(kind==='vendor-bill')return[norm(record.vendorId||record['Vendor ID']),norm(record.billNumber||record['Bill Number']),cents(record.total||record.Total||0),String(record.billDate||record['Bill Date']||'').slice(0,10)].join('|');if(kind==='bank')return[norm(record.accountId||record['Bank Account ID']),String(record.date||record.Date||'').slice(0,10),cents(record.amount||record.Amount||0),norm(record.description||record.Description)].join('|');return JSON.stringify(record);}
  function findDuplicates(rows=[],kind){const seen=new Map(),dupes=[];(rows||[]).forEach((r,i)=>{const key=duplicateKey(r,kind);if(seen.has(key))dupes.push({key,firstIndex:seen.get(key),duplicateIndex:i,row:r});else seen.set(key,i);});return dupes;}
  return {VERSION,TYPES,DEFAULT_ACCOUNTS,chart,validateTransaction,transaction,reverse,invoicePosting,customerPaymentPosting,vendorBillPosting,vendorPaymentPosting,expensePosting,trialBalance,profitAndLoss,balanceSheet,arAging,apAging,billsToPay,prepareCheck,prepareElectronicPayment,reconcile,creditCardReview,jobProfitability,cashProjection,monthEndChecklist,quickBooksAdapterState,duplicateKey,findDuplicates};
});
