function requireValue(value,message){if(!String(value||'').trim())throw new Error(message);return String(value).trim();}
function pendingRows(actions){return all('operations').then(rows=>rows.filter(op=>op.businessId===state.businessId&&actions.includes(op.action)));}

function renderToday(){
  const openJobs=records('jobs').filter(row=>!['COMPLETE','CLOSED','CANCELLED'].includes(String(v(row,'Status')).toUpperCase())).length,draftQuotes=records('quotes').filter(row=>String(v(row,'Status')).toUpperCase().includes('DRAFT')).length,unread=records('messages').filter(row=>String(v(row,'Status')).toUpperCase()!=='READ').length,dueAssets=records('assets').filter(row=>dueSoon(v(row,'Next Service'))).length;
  const schedule=records('scheduleEvents').filter(row=>new Date(v(row,'Start Time')).getTime()>=Date.now()-4*3600000).sort((a,b)=>new Date(v(a,'Start Time'))-new Date(v(b,'Start Time'))).slice(0,8);
  const recommendations=records('aiRecommendations').filter(row=>['Open','Postponed'].includes(v(row,'Status'))).slice(0,5),quick=activeRows(records('quickActions')).slice(0,10);
  $('mainContent').innerHTML=pageHead('Today','What needs attention, what is scheduled and what the business should do next.',`<button class="secondary" id="readDayButton">🔊 Read my day</button>`)+`<div class="grid"><section class="card"><div class="stats"><div class="stat"><strong>${openJobs}</strong><span>Open jobs</span></div><div class="stat"><strong>${draftQuotes}</strong><span>Draft quotes</span></div><div class="stat"><strong>${unread}</strong><span>Recent messages</span></div><div class="stat"><strong>${dueAssets}</strong><span>Service due</span></div></div></section><section class="card span7"><h2>Next work</h2><div class="list">${schedule.length?schedule.map(row=>`<div class="row"><div class="row-top"><strong>${esc(v(row,'Title'))}</strong>${pill(v(row,'Status'))}</div><small>${dateTime(v(row,'Start Time'))} · ${esc(v(row,'Location')||'No location')}</small></div>`).join(''):empty('Nothing scheduled in the cached business pack.')}</div></section><section class="card span5"><h2>Quick actions</h2><div class="quick-grid">${quick.length?quick.map(row=>`<button data-open-page="${esc(v(row,'Page Key'))}">${esc(v(row,'Label'))}</button>`).join(''):empty('Quick actions will appear here.')}</div></section><section class="card span7"><h2>H38 recommendations</h2><div class="list">${recommendations.length?recommendations.map(recommendationRow).join(''):empty('No open recommendations. H38 will continue watching permitted workflow events.')}</div></section><section class="card span5"><h2>Offline readiness</h2>${serverSafeguard()}<p class="muted small">Last business pack: ${dateTime(state.snapshot.cachedAt)}. Use Sync before leaving service to refresh assigned work, prices, messages and equipment.</p><div id="todayPending" class="list"></div></section></div>`;
  $('readDayButton').onclick=readMyDay;document.querySelectorAll('[data-open-page]').forEach(button=>button.onclick=()=>openPage(button.dataset.openPage));bindRecommendationButtons();renderPendingInto('todayPending');
}
function recommendationRow(row){const id=rowId(row,'Recommendation ID');return`<div class="row recommendation"><div class="row-top"><strong>${esc(v(row,'Title'))}</strong>${pill(v(row,'Recommendation Type'))}</div><small>${esc(recommendationEvidence(row))}</small><div class="row-actions"><button data-rec-apply="${esc(id)}">Apply safe change</button><button data-rec-postpone="${esc(id)}">Later</button><button data-rec-dismiss="${esc(id)}">Dismiss</button></div></div>`;}
function recommendationEvidence(row){const evidence=parseJson(v(row,'Evidence JSON'),{});return Object.entries(evidence).map(([key,value])=>`${key}: ${Array.isArray(value)?value.length:value}`).join(' · ')||'Review the proposed workflow improvement.';}
function bindRecommendationButtons(){document.querySelectorAll('[data-rec-apply]').forEach(button=>button.onclick=()=>recommendationDecision(button.dataset.recApply,'APPLY'));document.querySelectorAll('[data-rec-postpone]').forEach(button=>button.onclick=()=>recommendationDecision(button.dataset.recPostpone,'POSTPONE'));document.querySelectorAll('[data-rec-dismiss]').forEach(button=>button.onclick=()=>recommendationDecision(button.dataset.recDismiss,'DISMISS'));}
async function recommendationDecision(id,decision){try{if(!navigator.onLine||!state.bridgeReady)throw new Error('Recommendation decisions need the secure server connection.');await state.bridge.request('aiRecommendationDecision',{businessId:state.businessId,recommendationId:id,decision});toast('Recommendation decision saved.');await loadBusiness(state.businessId,true);}catch(error){toast(error.message,true);}}
async function renderPendingInto(id){const rows=(await all('operations')).filter(op=>op.businessId===state.businessId&&op.syncStatus==='PENDING').slice(0,8);const node=$(id);if(node)node.innerHTML=rows.length?rows.map(op=>`<div class="row"><strong>${esc(op.action.replaceAll('_',' '))}</strong><small>${dateTime(op.localTimestamp)} · waiting to sync</small></div>`).join(''):empty('This device has no pending work.');}

