async function loadBusiness(businessId,quiet=false){if(!businessId)return;state.businessId=businessId;await put('meta',{id:'selectedBusiness',businessId});try{const snapshot=await state.bridge.request('completionBootstrap',{businessId},90000);snapshot.id=`business:${businessId}`;snapshot.cachedAt=now();await put('snapshots',snapshot);state.snapshot=snapshot;$('businessSelect').value=businessId;$('businessStatus').textContent=`${snapshot.business.businessName} · ${snapshot.user.roleName} · cached ${new Date(snapshot.cachedAt).toLocaleTimeString()}`;openPage(state.page,false);if(!quiet)toast('Business refreshed. Important records are now available offline.');}catch(error){await loadCached();if(!quiet)toast(`${error.message} Using the most recent offline business pack.`,true);}}
async function loadCached(){if(!state.businessId)return;const snapshot=await get('snapshots',`business:${state.businessId}`);if(snapshot){state.snapshot=snapshot;$('businessStatus').textContent=`${snapshot.business.businessName} · offline pack ${new Date(snapshot.cachedAt).toLocaleString()}`;$('businessSelect').value=state.businessId;}}
function openPage(page,track=true){const pages=allowedPages();if(!pages.includes(page))page=pages[0]||'today';state.page=page;renderNav();renderPage();$('mainContent').focus({preventScroll:true});if(track)recordUsage(page,'open-page').catch(()=>{});}
function pageHead(title,description,tools=''){return`<header class="page-head"><div><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="page-tools">${tools}</div></header>`;}
function renderPage(){if(!state.snapshot){renderWelcome();return;}const renderers={today:renderToday,customers:renderCustomers,work:renderWork,quotes:renderQuotes,measure:renderMeasure,schedule:renderSchedule,messages:renderMessages,field:renderField,inventory:renderInventory,fleet:renderFleet,money:renderMoney,documents:renderDocuments,social:renderSocial,ai:renderAi,settings:renderSettings};(renderers[state.page]||renderToday)();}
function records(name){return state.snapshot?.[name]||[];}
function customerName(id){const row=records('customers').find(x=>rowId(x,'Customer ID','customerId')===String(id));return v(row,'Customer Name','name')||'No customer';}
function jobName(id){const row=records('jobs').find(x=>rowId(x,'Job ID','jobId')===String(id));return v(row,'Project Title','projectTitle')||'No job';}
function userName(id){if(id==='USER-OWNER')return state.snapshot?.business?.ownerName||'Owner';const row=records('users').find(x=>rowId(x,'User ID','userId')===String(id));return v(row,'Display Name','displayName','Email')||id||'Unassigned';}
function assetName(id){const row=records('assets').find(x=>rowId(x,'Asset ID','assetId')===String(id));return v(row,'Description','description')||id||'Equipment';}
function optionRows(rows,idKeys,labelFn,blank='Select'){return`<option value="">${esc(blank)}</option>`+rows.map(row=>`<option value="${esc(rowId(row,...idKeys))}">${esc(labelFn(row))}</option>`).join('');}
function activeRows(rows){return rows.filter(row=>!['ARCHIVED','INACTIVE','CANCELLED'].includes(String(v(row,'Status','status')).toUpperCase()));}
function dueSoon(value,days=14){if(!value)return false;const time=new Date(value).getTime();return Number.isFinite(time)&&time<=Date.now()+days*86400000;}
function serverSafeguard(){return`<div class="notice warn"><strong>Owner control:</strong> drafts and internal work can be created here. Nothing is automatically sent, published, purchased, paid, deleted or approved.</div>`;}

async function queueOperation(action,recordType,recordId,payload,optimistic,autoSync=true){if(!state.businessId)throw new Error('Open a business first.');const id=newId('OP'),operation={id,operationId:id,businessId:state.businessId,deviceId:await deviceId(),recordType,recordId,action,baseVersion:num(payload?.baseVersion),localTimestamp:now(),payload,syncStatus:'PENDING',retryCount:0};await put('operations',operation);if(optimistic)applyOptimistic(optimistic.collection,optimistic.record,optimistic.idKeys);await updatePending();if(autoSync&&navigator.onLine&&state.bridgeReady)sync(false);return operation;}
function applyOptimistic(collection,record,idKeys=[]){if(!state.snapshot[collection])state.snapshot[collection]=[];const keys=idKeys.length?idKeys:['id'];const id=keys.map(key=>v(record,key)).find(Boolean);const index=state.snapshot[collection].findIndex(row=>keys.some(key=>v(row,key)===id));record.__localPending=true;if(index>=0)state.snapshot[collection][index]=record;else state.snapshot[collection].unshift(record);put('snapshots',{...state.snapshot,id:`business:${state.businessId}`,cachedAt:state.snapshot.cachedAt||now()}).catch(()=>{});}
async function updatePending(){const pending=(await all('operations')).filter(op=>op.businessId===state.businessId&&op.syncStatus==='PENDING');$('syncBadge').textContent=`${pending.length} pending`;$('syncBadge').className=`badge ${pending.length?'warn':'neutral'}`;}
async function sync(show=true){const operations=(await all('operations')).filter(op=>op.businessId===state.businessId&&op.syncStatus==='PENDING');await updatePending();if(!operations.length){if(show)toast('Nothing is waiting to sync.');return;}if(!navigator.onLine||!state.bridgeReady){if(show)toast('Offline or secure bridge unavailable. Work remains safely queued.',true);return;}try{const response=await state.bridge.request('completionSync',{businessId:state.businessId,operations},120000);let done=0,failed=0,conflicts=0;for(const result of response.results||[]){const operation=operations.find(op=>op.operationId===result.operationId);if(!operation)continue;if(['SYNCED','ALREADY_SYNCED'].includes(result.status)){await remove('operations',operation.id);done++;}else if(result.status==='CONFLICT'){operation.syncStatus='CONFLICT';operation.lastError='A newer server version needs review.';await put('operations',operation);conflicts++;}else{operation.retryCount=num(operation.retryCount)+1;operation.lastError=result.message||'Sync failed';await put('operations',operation);failed++;}}await updatePending();toast(`${done} synchronized${conflicts?`, ${conflicts} conflicts`:''}${failed?`, ${failed} failed`:''}.`,failed>0||conflicts>0);if(done)await loadBusiness(state.businessId,true);else renderPage();}catch(error){toast(error.message,true);}}
async function deviceId(){let record=await get('meta','device');if(!record){record={id:'device',deviceId:newId('DEVICE'),createdTime:now(),name:navigator.userAgent.slice(0,90)};await put('meta',record);}return record.deviceId;}
async function recordUsage(pageKey,actionKey,metadata={}){if(!state.businessId)return;await queueOperation('RECORD_USAGE_EVENT','Usage Event',newId('USAGE'),{pageKey,actionKey,deviceId:await deviceId(),metadata},null,false);}
function formObject(form){const data=new FormData(form),out={};for(const [key,value] of data.entries())out[key]=value;return out;}
function bindForm(id,handler){const form=$(id);if(form)form.onsubmit=async event=>{event.preventDefault();try{await handler(formObject(form),form);}catch(error){toast(error.message,true);}};}
