async function handleVoiceTranscript(transcript){const text=String(transcript).trim(),lower=text.toLowerCase();toast(`Heard: ${text}`);const pageMatch=Object.keys(PAGE_DEFS).find(key=>lower.includes(`open ${key}`)||lower.includes(`go to ${key}`));if(pageMatch){openPage(pageMatch);speak(`Opening ${PAGE_DEFS[pageMatch][1]}.`);return;}if(lower.includes('read my day')||lower.includes('what is next')){readMyDay();return;}if(lower.startsWith('message office ')){const body=text.slice(text.toLowerCase().indexOf('message office ')+15),conversation=records('conversations').find(row=>v(row,'Subject')==='General')||records('conversations')[0];if(conversation){const id=newId('MESSAGE'),record={'Message ID':id,'Business ID':state.businessId,'Conversation ID':rowId(conversation,'Conversation ID'),'Sender User ID':state.snapshot.user.userId,'Message Type':'Voice Dictation','Body':body,'Status':'Sent Internal','Created Time':now(),'Record Version':1};await queueOperation('SEND_INTERNAL_MESSAGE','Message',id,{conversationId:rowId(conversation,'Conversation ID'),body,messageType:'Voice Dictation'},{collection:'messages',record,idKeys:['Message ID']});speak('Internal message saved.');return;}}
  if(state.page==='measure'){
    const match=lower.match(/(?:is|equals|at)?\s*(\d+(?:\.\d+)?)\s*(feet|foot|ft|inches|inch|in|meters|meter|m|centimeters|centimeter|cm|square feet|sq ft|degrees)?/);
    if($('measurementNotes'))$('measurementNotes').value=[$('measurementNotes').value,text].filter(Boolean).join('\n');
    if(match&&$('measurementValue')){$('measurementValue').value=match[1];const units={'feet':'ft','foot':'ft','ft':'ft','inches':'in','inch':'in','in':'in','meters':'m','meter':'m','m':'m','centimeters':'cm','centimeter':'cm','cm':'cm','square feet':'sq ft','sq ft':'sq ft','degrees':'degrees'};if(match[2]&&$('measurementUnit'))$('measurementUnit').value=units[match[2]]||$('measurementUnit').value;speak('Measurement captured. Review the method and save it.');return;}
  }
  const highRisk=/(send|approve|publish|pay|purchase|delete|refund|change permission|deploy)/.test(lower);const id=newId('VOICE'),record={'Voice Queue ID':id,'Business ID':state.businessId,'User ID':state.snapshot.user.userId,'Mode':state.drivingMode?'Driving':'Normal','Transcript':text,'Intent':highRisk?'High risk request':'Captured note','Risk Level':highRisk?'High':'Low','Review Required':highRisk?'Yes':'No','Status':highRisk?'Review When Parked':'Captured','Created Time':now(),'Updated Time':now(),'Record Version':1};await queueOperation('SAVE_VOICE_ITEM','Voice Queue',id,{voiceQueueId:id,mode:record.Mode,transcript:text,intent:record.Intent,riskLevel:record['Risk Level'],reviewRequired:record['Review Required']},{collection:'voiceQueue',record,idKeys:['Voice Queue ID']});if(highRisk){showReview(`I captured “${esc(text)}” but did not execute it. Review it when parked.`);speak('That action needs parked review. I saved the request but did not execute it.');}else speak('Voice note saved.');}
function showReview(html){$('reviewBody').innerHTML=`<p>${html}</p>`;$('reviewDialog').showModal();}

init().catch(error=>{console.error(error);toast(error.message,true);renderWelcome();});
