class H38Bridge{
  constructor(frame,url,onStatus){this.frame=frame;this.url=url;this.onStatus=onStatus||(()=>{});this.ready=false;this.pending=new Map();this.popup=null;this.listener=event=>this.receive(event);addEventListener('message',this.listener);}
  setUrl(url){this.url=url;this.ready=false;this.connect();}
  connect(){if(!this.url)return;this.ready=false;this.onStatus('connecting');this.frame.src=this.url+(this.url.includes('?')?'&':'?')+'v='+Date.now();clearTimeout(this.timer);this.timer=setTimeout(()=>{if(!this.ready)this.onStatus('unavailable');},8000);}
  authorize(){if(!this.url)return;const authUrl=this.url+(this.url.includes('?')?'&':'?')+'authorize=1&v='+Date.now();this.onStatus('authorizing');this.popup=window.open(authUrl,'h38-secure-signin','popup=yes,width=520,height=720');if(!this.popup){location.href=authUrl;return;}clearTimeout(this.authTimer);this.authTimer=setTimeout(()=>{if(!this.ready)this.onStatus('unavailable');},30000);}
  receive(event){const fromFrame=event.source===this.frame.contentWindow,fromPopup=this.popup&&event.source===this.popup;if(!fromFrame&&!fromPopup)return;const message=event.data||{};if(message.type==='H38_BRIDGE_READY'){this.ready=true;clearTimeout(this.timer);clearTimeout(this.authTimer);this.onStatus('ready');try{if(this.popup&&!this.popup.closed)this.popup.close();}catch(error){}return;}if(message.type!=='H38_BRIDGE_RESPONSE')return;const pending=this.pending.get(message.requestId);if(!pending)return;this.pending.delete(message.requestId);clearTimeout(pending.timer);message.ok?pending.resolve(message.result):pending.reject(new Error(message.error||'Secure connection request failed.'));}
  request(action,args={},timeout=45000){if(!this.ready)return Promise.reject(new Error('Secure Google connection is not ready. Tap Sign in securely, then try again.'));const requestId=crypto.randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(requestId);reject(new Error(`${action} timed out.`));},timeout);this.pending.set(requestId,{resolve,reject,timer});const target=this.popup&&!this.popup.closed?this.popup:this.frame.contentWindow;target.postMessage({type:'H38_BRIDGE_REQUEST',requestId,action,args},'*');});}
}
window.H38Bridge=H38Bridge;
