class H38Bridge{
  constructor(frame,url,onStatus,onBootstrap,onFullSnapshot,onError){this.frame=frame;this.url=url;this.onStatus=onStatus||(()=>{});this.onBootstrap=onBootstrap||(()=>{});this.onFullSnapshot=onFullSnapshot||(()=>{});this.onError=onError||(()=>{});this.ready=false;this.bootstrapped=false;this.pending=new Map();this.popup=null;this.transport=null;this.listener=event=>this.receive(event);addEventListener('message',this.listener);}
  setUrl(url){this.url=url;this.ready=false;this.bootstrapped=false;this.transport=null;this.connect();}
  connect(){if(!this.url)return;this.ready=false;this.bootstrapped=false;if(!this.popup||this.popup.closed)this.transport=null;this.onStatus('connecting');this.frame.src=this.url+(this.url.includes('?')?'&':'?')+'v='+Date.now();clearTimeout(this.timer);this.timer=setTimeout(()=>{if(!this.bootstrapped)this.onStatus('sign-in-required');},8000);}
  authorize(){if(!this.url)return;if(this.popup&&!this.popup.closed){this.popup.focus();this.onStatus('authorizing');return;}const authUrl=this.url+(this.url.includes('?')?'&':'?')+'authorize=1&v='+Date.now();this.onStatus('authorizing');this.popup=window.open(authUrl,'h38-secure-signin','popup=yes,width=520,height=720');if(!this.popup){this.onStatus('popup-blocked');return;}clearTimeout(this.authTimer);this.authTimer=setTimeout(()=>{if(!this.bootstrapped)this.onStatus('sign-in-timeout');},45000);}
  useTransport(fromFrame,fromPopup){if(fromFrame){this.transport=this.frame.contentWindow;}else if(fromPopup){this.transport=this.popup;}this.ready=true;}
  receive(event){const fromFrame=event.source===this.frame.contentWindow,fromPopup=this.popup&&event.source===this.popup;if(!fromFrame&&!fromPopup)return;const message=event.data||{};
    if(message.type==='H38_BRIDGE_READY'){this.useTransport(fromFrame,fromPopup);this.onStatus('connected');return;}
    if(message.type==='H38_BRIDGE_BOOTSTRAP'){this.useTransport(fromFrame,fromPopup);this.bootstrapped=true;clearTimeout(this.timer);clearTimeout(this.authTimer);this.onBootstrap(message.startup||{});this.onStatus('bootstrapped');return;}
    if(message.type==='H38_BRIDGE_FULL_SNAPSHOT'){this.onFullSnapshot(message.snapshot||{},message.businessId||'');return;}
    if(message.type==='H38_BRIDGE_BOOTSTRAP_ERROR'){clearTimeout(this.timer);clearTimeout(this.authTimer);this.onError('startup',message.error||'Secure startup failed.');this.onStatus('startup-error');return;}
    if(message.type==='H38_BRIDGE_REFRESH_ERROR'){this.onError('refresh',message.error||'Latest-record refresh failed.');return;}
    if(message.type!=='H38_BRIDGE_RESPONSE')return;const pending=this.pending.get(message.requestId);if(!pending)return;this.pending.delete(message.requestId);clearTimeout(pending.timer);message.ok?pending.resolve(message.result):pending.reject(new Error(message.error||'Secure connection request failed.'));
  }
  request(action,args={},timeout=45000){const target=this.transport&&(!(this.transport.closed))?this.transport:(this.popup&&!this.popup.closed?this.popup:this.frame.contentWindow);if(!this.ready||!target)return Promise.reject(new Error('Secure Google connection is not ready. Tap Sign in securely, then try again.'));const requestId=crypto.randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(requestId);reject(new Error(`${action} timed out.`));},timeout);this.pending.set(requestId,{resolve,reject,timer});target.postMessage({type:'H38_BRIDGE_REQUEST',requestId,action,args},'*');});}
}
window.H38Bridge=H38Bridge;
