(function(){
'use strict';
const BUILD='20260808-1848',C=window.H38_FIELD_VISIT_CORE;if(!C)return;const S=C.state,$=C.$;
const native=/H38SiteScannerAndroid/.test(navigator.userAgent),apple=/iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;
if(native)document.documentElement.classList.add('h38-native-shell');
if(apple)document.documentElement.classList.add('h38-apple-device');
const originalBlank=C.blank,originalRestore=C.restore,originalContext=C.context,originalAttach=C.attach;
const now=()=>new Date().toISOString();
const uid=p=>typeof window.newId==='function'?window.newId(p):`${p}-${crypto.randomUUID().toUpperCase()}`;
function optimistic(collection,key,record,keys){if(!window.state?.snapshot)return;if(!Array.isArray(window.state.snapshot[collection]))window.state.snapshot[collection]=[];const rows=window.state.snapshot[collection],index=rows.findIndex(row=>keys.some(k=>C.t(row?.[k])===C.t(key)));if(index>=0)rows[index]=record;else rows.unshift(record)}
async function queueEntity(collection,type,key,record,keys){if(typeof window.queueOperation!=='function')throw Error('Offline save queue is unavailable.');await window.queueOperation('SAVE_ENTITY',type,key,{entity:collection,record},{collection,record,idKeys:keys},false);optimistic(collection,key,record,keys);if(navigator.onLine)C.syncSoon();return record}
function currentQuoteLocked(qid){return !!qid&&C.locked(C.quote(qid))}
C.blank=function(){const visit=originalBlank();if(currentQuoteLocked(visit.quoteId))visit.quoteId='';if(!Array.isArray(visit.videoAttachmentIds))visit.videoAttachmentIds=[];if(!Array.isArray(visit.walkthroughFrameIds))visit.walkthroughFrameIds=[];if(typeof visit.walkthroughSkipped!=='boolean')visit.walkthroughSkipped=false;return visit};
C.restore=async function(){const visit=await originalRestore();if(!visit)return null;const status=C.t(visit.status).toUpperCase();if(status==='ATTACHED_TO_DRAFT_QUOTE'||status==='CLOSED')return null;if(!Array.isArray(visit.videoAttachmentIds))visit.videoAttachmentIds=[];if(!Array.isArray(visit.walkthroughFrameIds))visit.walkthroughFrameIds=[];if(typeof visit.walkthroughSkipped!=='boolean')visit.walkthroughSkipped=false;return visit};
C.context=async function(ev){const form=ev?.currentTarget,selected=C.t(form?.quoteId?.value);if(selected&&currentQuoteLocked(selected)){form.quoteId.value='';C.toast('That quote is already locked. Starting a new editable draft for this Site Visit.');}return originalContext(ev)};
async function relinkRows(collection,type,idKeys,qid){if(!S.visit?.sessionId)return;const sessionId=C.t(S.visit.sessionId),rows=C.rows(collection).filter(row=>C.t(C.val(row,'Capture Session ID','captureSessionId'))===sessionId);for(const row of rows){const key=C.rid(row,...idKeys),updated=Object.assign({},row,{'Quote ID':qid,'Updated Time':now(),'Record Version':C.n(C.val(row,'Record Version','recordVersion')||1)+1});await queueEntity(collection,type,key,updated,idKeys)}}
async function createEditableDraftForVisit(){const oldQid=C.t(S.visit?.quoteId),qid=uid('QUOTE'),record={'Quote ID':qid,'Business ID':C.business(),'Customer ID':C.t(S.visit?.customerId),'Quote Number':`LOCAL-${Date.now()}`,'Project Title':C.t(S.visit?.projectTitle||'Site visit'),'Scope':C.t(S.visit?.scope),'Measurement Notes':'','Status':'Draft','Revision':1,'Subtotal':0,'Tax':0,'Total':0,'Created Time':now(),'Updated Time':now(),'Record Version':1,lines:[]};await queueEntity('quotes','Quote',qid,record,['Quote ID','quoteId']);S.visit.quoteId=qid;if(S.visit.sessionId){const session=C.rows('siteCaptureSessions').find(row=>C.t(C.val(row,'Capture Session ID','captureSessionId'))===C.t(S.visit.sessionId));if(session){const updated=Object.assign({},session,{'Quote ID':qid,'Updated Time':now(),'Record Version':C.n(C.val(session,'Record Version','recordVersion')||1)+1});await queueEntity('siteCaptureSessions','Site Capture Session',S.visit.sessionId,updated,['Capture Session ID','captureSessionId'])}await relinkRows('siteMeasurements','Site Measurement',['Site Measurement ID','measurementId'],qid);await relinkRows('jobNotes','Field Note',['Job Note ID','jobNoteId'],qid)}try{const attachments=await window.H38DB?.all('attachments')||[];for(const row of attachments){if(C.t(row?.relatedRecordId)===C.t(S.visit.visitId)&&(!oldQid||C.t(row?.quoteId)===oldQid)){await window.H38DB.put('attachments',Object.assign({},row,{quoteId:qid}))}}}catch(_){}await C.saveDraft();window.state.quote=Object.assign({},window.state.quote||{},{quoteId:qid,customerId:S.visit.customerId,projectTitle:S.visit.projectTitle,scope:S.visit.scope,lines:[]});C.toast('Created a new editable draft and kept this Site Visit attached.');return qid}
C.attach=async function(){try{if(!S.visit?.quoteId||currentQuoteLocked(S.visit.quoteId))await createEditableDraftForVisit();return await originalAttach()}catch(error){C.toast(error?.message||String(error),true)}};
async function walkthroughSource(){const ids=Array.isArray(S.visit?.videoAttachmentIds)?S.visit.videoAttachmentIds:[];const id=ids[ids.length-1];if(!id)throw Error('No walkthrough recording is attached to this Site Visit yet.');const local=await window.H38DB?.get('attachments',id);if(local?.blobData instanceof Blob)return{url:URL.createObjectURL(local.blobData),revoke:true,status:C.t(local.syncStatus||'Saved on this phone')};let path=C.t(local?.storagePath);if(!path){const doc=C.rows('documents').find(row=>C.rid(row,'Document ID','documentId')===id);path=C.t(C.val(doc,'Storage Path','storagePath'))}if(!path)throw Error('The walkthrough is saved with this visit but is still waiting to sync.');const api=window.H38_SUPABASE_SHARED_CLIENT?.ensure?.();if(!api)throw Error('Secure Business Office connection is not ready.');const signed=await api.storage.from('business-office-files').createSignedUrl(path,300);if(signed.error||!signed.data?.signedUrl)throw Error(signed.error?.message||'Could not open the private walkthrough.');return{url:signed.data.signedUrl,revoke:false,status:'Saved privately'}}
async function viewWalkthrough(){try{const source=await walkthroughSource();const dialog=document.createElement('dialog');dialog.className='field-walkthrough-viewer';dialog.innerHTML=`<div class="field-walkthrough-viewer-shell"><header><strong>Site Walkthrough</strong><button type="button" aria-label="Close walkthrough">×</button></header><video controls playsinline preload="metadata" src="${source.url}"></video><small>${source.status} · Private Site Visit evidence</small></div>`;document.body.appendChild(dialog);const close=()=>{try{dialog.close()}catch(_){}if(source.revoke)URL.revokeObjectURL(source.url);dialog.remove()};dialog.querySelector('button').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});dialog.showModal()}catch(error){C.toast(error?.message||String(error),true)}}
function decorateEvidence(){const stage=document.querySelector('[data-field-walkthrough-stage].complete');if(!stage||S.visit?.walkthroughSkipped)return;let evidence=stage.querySelector('[data-field-walkthrough-evidence]');if(!evidence){evidence=document.createElement('div');evidence.dataset.fieldWalkthroughEvidence='1';evidence.className='field-walkthrough-evidence';evidence.innerHTML='<button id="fieldWalkthroughView" class="field-secondary" type="button">▶ View Saved Walkthrough</button><small>Saved with this Site Visit as private evidence. The extracted frames are used for review.</small>';stage.appendChild(evidence)}evidence.querySelector('#fieldWalkthroughView')?.addEventListener('click',viewWalkthrough,{once:true})}
function installWalkthroughRender(){const ui=window.H38_FIELD_VISIT_UI,video=window.H38_FIELD_VISIT_VIDEO;if(!ui||!video||typeof ui.render!=='function')return false;if(ui.__walkthroughGuaranteed)return true;const base=ui.render;const wrapped=function(){base();video.decorate?.();decorateEvidence()};ui.render=wrapped;ui.__walkthroughGuaranteed=true;ui.__walkthroughWrapped=true;C.setRender(wrapped);return true}
async function open(opts={}){if(!window.state?.snapshot||!C.business()){C.toast('Open the Business Office and active business first.',true);return}installWalkthroughRender();const restored=await C.restore(),requested=C.t(opts.quoteId);S.visit=restored&&(!requested||C.t(restored.quoteId)===requested)?restored:C.blank();if(requested&&!currentQuoteLocked(requested))S.visit.quoteId=requested;if(requested&&currentQuoteLocked(requested)){S.visit.quoteId='';S.visit.customerId=C.t(opts.customerId||C.val(C.quote(requested),'Customer ID','customerId'));S.visit.projectTitle=C.t(C.val(C.quote(requested),'Project Title','projectTitle')||S.visit.projectTitle);S.visit.scope=C.t(C.val(C.quote(requested),'Scope','scope')||S.visit.scope)}if(opts.customerId)S.visit.customerId=opts.customerId;S.open=true;S.tab=S.visit.sessionId?'capture':'job';document.body.classList.add('field-visit-open');await C.load();window.H38_FIELD_VISIT_UI.render()}
function close(){S.open=false;document.body.classList.remove('field-visit-open');$('h38FieldVisitApp')?.remove()}
function title(){return C.t($('mainContent')?.querySelector('.page-head h1')?.textContent)}
function moveQuoteTools(tools,more){if(!tools||!more)return;Array.from(tools.children).forEach(node=>{if(node.id==='h38StartFieldVisit'||node.id==='h38SiteScannerButton'||node.tagName==='INPUT')return;node.classList.add('field-overflow-tool');more.appendChild(node)})}
function focusQuote(){const main=$('mainContent'),tools=main?.querySelector('.page-tools');if(!main||!tools)return;document.body.classList.add('field-quote-focused');let launch=$('h38FieldQuoteLaunch');if(!launch){launch=document.createElement('section');launch.id='h38FieldQuoteLaunch';launch.className='field-quote-launch';launch.innerHTML=`<div><span class="field-kicker">FIELD-FIRST QUOTE</span><h2>Capture the job before building the quote</h2><p>Start with a video walkthrough, then add targeted photos, measurements and notes. Everything stays together online or offline.</p></div><button id="h38StartFieldVisit" class="field-primary">📍 Start Site Visit</button><details class="field-quote-more"><summary>More quote tools</summary><div id="h38QuoteOverflow" class="field-quote-overflow"></div></details>`;const head=main.querySelector('.page-head');(head?.nextSibling?main.insertBefore(launch,head.nextSibling):main.prepend(launch));$('h38StartFieldVisit').onclick=()=>open({quoteId:C.t(window.state?.quote?.quoteId),customerId:C.t(window.state?.quote?.customerId)})}moveQuoteTools(tools,$('h38QuoteOverflow'));tools.classList.add('field-original-tools-hidden')}
function entries(){const main=$('mainContent');if(!main||!window.state?.snapshot||!C.business())return;const page=title(),isQuote=/Quote Builder/i.test(page),isLegacy=/Site Measure|H38 Site Scanner/i.test(page),advanced=Number(window.H38_FIELD_VISIT_ADVANCED_UNTIL||0)>Date.now();if(isQuote)focusQuote();else document.body.classList.remove('field-quote-focused');if(advanced){$('h38SiteScannerButton')?.classList.remove('field-hide-legacy-scanner');$('h38SiteScannerPanel')?.classList.remove('field-hide-legacy-scanner')}else{$('h38SiteScannerButton')?.classList.add('field-hide-legacy-scanner');$('h38SiteScannerPanel')?.classList.add('field-hide-legacy-scanner')}if(isLegacy&&!S.open&&!advanced){open({quoteId:C.t(window.state?.quote?.quoteId),customerId:C.t(window.state?.quote?.customerId)});return}}
function loadGuidance(){if(!document.querySelector('link[data-h38-field-guidance]')){const link=document.createElement('link');link.rel='stylesheet';link.href='./field-visit-guidance.css?build=20260806-2145';link.dataset.h38FieldGuidance='1';document.head.appendChild(link)}if(window.H38_FIELD_VISIT_GUIDANCE||document.querySelector('script[data-h38-field-guidance]'))return;const script=document.createElement('script');script.src='./field-visit-guidance.js?build=20260806-2145';script.dataset.h38FieldGuidance='1';document.head.appendChild(script)}
function loadRecovery(){if(window.H38_FIELD_VISIT_RECOVERY||document.querySelector('script[data-h38-field-recovery]'))return;const script=document.createElement('script');script.src='./field-visit-recovery.js?build=20260806-2100';script.dataset.h38FieldRecovery='1';document.head.appendChild(script)}
function loadPhotoReview(){if(window.H38_FIELD_VISIT_PHOTO_REVIEW||document.querySelector('script[data-h38-field-photo-review]'))return;const script=document.createElement('script');script.src='./field-visit-photo-review.js?build=20260806-2145';script.dataset.h38FieldPhotoReview='1';document.head.appendChild(script)}
function loadVideoWalkthrough(){if(window.H38_FIELD_VISIT_VIDEO)return Promise.resolve();const existing=document.querySelector('script[data-h38-field-video]');if(existing)return new Promise(resolve=>{existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',resolve,{once:true})});return new Promise(resolve=>{const script=document.createElement('script');script.src='./field-visit-video.js?build=20260808-1805';script.dataset.h38FieldVideo='1';script.onload=resolve;script.onerror=resolve;document.head.appendChild(script)})}
async function start(){loadGuidance();loadRecovery();loadPhotoReview();await loadVideoWalkthrough();installWalkthroughRender();const main=$('mainContent');if(main)new MutationObserver(()=>requestAnimationFrame(entries)).observe(main,{childList:true,subtree:true});addEventListener('online',()=>{C.status();C.syncSoon()});addEventListener('offline',C.status);addEventListener('h38:native-scanner-ready',()=>{if(S.open)window.H38_FIELD_VISIT_UI.render()});addEventListener('h38:auth-cleared',close);setInterval(()=>C.pending().catch(()=>{}),5000);entries()}
const style=document.createElement('style');style.textContent=`.field-walkthrough-evidence{display:grid;gap:.45rem}.field-walkthrough-evidence small{color:#52616d}.field-walkthrough-viewer{border:0;padding:0;background:#08131c;color:#fff;width:min(760px,100vw);max-width:100vw}.field-walkthrough-viewer::backdrop{background:rgba(0,0,0,.78)}.field-walkthrough-viewer-shell{display:grid;gap:.7rem;padding:.8rem}.field-walkthrough-viewer header{display:flex;justify-content:space-between;align-items:center}.field-walkthrough-viewer header button{font-size:1.7rem;background:transparent;color:#fff;border:0}.field-walkthrough-viewer video{width:100%;max-height:72dvh;background:#000;border-radius:10px}`;document.head.appendChild(style);
window.H38_FIELD_VISIT={build:BUILD,open,close,ingestNativeResult:C.ingest,refreshPending:C.pending,offlineFirst:true,databaseAuthority:'existing Supabase Business Office',nativeStartupAutoOpen:false,siteVisitRequiresExplicitAction:true,automaticApproval:false,automaticCustomerSending:false,companyCamStyle:true,appleCapture:true,guidedCapture:true,walkthroughFirst:true,targetedPhotosAfterWalkthrough:true,photoReviewBeforeMeasurements:true,queueRecovery:true,videoWalkthrough:true,liveWalkthroughCamera:true,videoFramesForAiReview:true,visibleWalkthroughEvidence:true,lockedQuoteDraftRecovery:true};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else void start();
})();
