(function(){
'use strict';
const BUILD='20260806-0715',C=window.H38_FIELD_VISIT_CORE;if(!C)return;const S=C.state,$=C.$;
async function open(opts={}){if(!window.state?.snapshot||!C.business()){C.toast('Open the Business Office and active business first.',true);return}S.visit=await C.restore()||C.blank();if(opts.quoteId)S.visit.quoteId=opts.quoteId;if(opts.customerId)S.visit.customerId=opts.customerId;S.open=true;S.tab=S.visit.sessionId?'measure':'visit';document.body.classList.add('field-visit-open');await C.load();window.H38_FIELD_VISIT_UI.render()}
function close(){S.open=false;document.body.classList.remove('field-visit-open');$('h38FieldVisitApp')?.remove()}
function entries(){const main=$('mainContent');if(!main||!window.state?.snapshot||!C.business())return;const tools=main.querySelector('.page-tools'),title=C.t(main.querySelector('.page-head h1')?.textContent);if(tools&&/Quote|Measure|Site Scanner/i.test(title)&&!$('h38StartFieldVisit')){const b=document.createElement('button');b.id='h38StartFieldVisit';b.textContent='📍 Start Site Visit';b.onclick=()=>open();tools.prepend(b)}$('h38SiteScannerButton')?.classList.add('field-hide-legacy-scanner');$('h38SiteScannerPanel')?.classList.add('field-hide-legacy-scanner');if(new URLSearchParams(location.search).get('nativeScanner')==='1'&&!S.auto&&!S.open){S.auto=true;setTimeout(()=>open(),100)}}
function start(){const main=$('mainContent');if(main)new MutationObserver(entries).observe(main,{childList:true,subtree:true});addEventListener('online',()=>{C.status();C.syncSoon()});addEventListener('offline',C.status);addEventListener('h38:auth-cleared',close);setInterval(()=>C.pending().catch(()=>{}),5000);entries()}
window.H38_FIELD_VISIT={build:BUILD,open,close,ingestNativeResult:C.ingest,refreshPending:C.pending,offlineFirst:true,databaseAuthority:'existing Supabase Business Office',automaticApproval:false,automaticCustomerSending:false};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
