(function(){
'use strict';
const BUILD='20260923-install-office-tablet-5-idempotent';
const MOBILE='(max-width: 760px)';
const PHONE='(max-width: 540px)';
const SHORTCUTS=new Set(['today','customers','schedule','messages','work','quotes','field']);
let deferredPrompt=null;
let installed=false;
let shortcutHandled=false;
let lastPromptOutcome='';
const mobile=()=>!!window.matchMedia?.(MOBILE).matches;
const phone=()=>!!window.matchMedia?.(PHONE).matches&&!tablet();
const standalone=()=>!!(window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true||document.referrer.startsWith('android-app://'));
const ua=()=>String(navigator.userAgent||'');
const isAndroid=()=>/android/i.test(ua());
const isChromeOS=()=>/cros/i.test(ua());
const isiPadDesktop=()=>String(navigator.platform||'')==='MacIntel'&&Number(navigator.maxTouchPoints||0)>1;
const isiOS=()=>/iphone|ipad|ipod/i.test(ua())&&!window.MSStream||isiPadDesktop();
const isChromium=()=>/chrome|crios|edg|chromium/i.test(ua())&&!/firefox|fxios/i.test(ua());
const viewportWidth=()=>Math.max(0,Number(window.innerWidth||document.documentElement?.clientWidth||screen?.width||0));
const tablet=()=>isiOS()&&viewportWidth()>=600||(isAndroid()&&!/\bmobile\b/i.test(ua()))||(Number(navigator.maxTouchPoints||0)>0&&viewportWidth()>=600&&viewportWidth()<=1400);
const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function platform(){if(isiOS())return tablet()?'iPad':'iPhone';if(isAndroid())return tablet()?'Android tablet':'Android phone';if(isChromeOS())return'Chromebook / ChromeOS';if(isChromium())return'Chrome / Chromium';return'Web browser';}
function diagnostics(){return{installed:installed||standalone(),promptReady:!!deferredPrompt,ios:isiOS(),android:isAndroid(),chromeOS:isChromeOS(),chromium:isChromium(),mobile:mobile(),phone:phone(),tablet:tablet(),platform:platform(),secure:window.isSecureContext===true||location.protocol==='https:'||location.hostname==='localhost',manifestPresent:!!document.querySelector('link[rel="manifest"]'),serviceWorkerSupported:'serviceWorker'in navigator,serviceWorkerControlled:!!navigator.serviceWorker?.controller,lastPromptOutcome};}
function installState(){return diagnostics();}
function ensureStyle(){if(document.getElementById('h38InstallOfficeStyle'))return;const style=document.createElement('style');style.id='h38InstallOfficeStyle';style.textContent=`#h38InstallOfficeButton{min-height:42px;padding:0 12px;border-radius:10px;font-weight:850;white-space:nowrap}.h38-install-dialog{width:min(560px,calc(100vw - 22px));border:0;border-radius:18px;padding:0;max-height:86dvh}.h38-install-dialog::backdrop{background:rgba(0,0,0,.55)}.h38-install-shell{display:grid;gap:14px;padding:18px}.h38-install-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.h38-install-head h2{margin:0}.h38-install-head p{margin:5px 0 0;color:var(--muted,#607285);line-height:1.4}.h38-install-steps{margin:0;padding-left:21px;display:grid;gap:8px}.h38-install-note{padding:11px 12px;border-radius:12px;background:#eef3f7;color:#31495c}.h38-install-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}.h38-install-actions button{min-height:44px}.h38-install-status{font-weight:800;color:#1d6631}.h38-install-diagnostics{display:grid;grid-template-columns:1fr auto;gap:6px 12px;font-size:.8rem}.h38-install-diagnostics strong{font-weight:900}.h38-install-ok{color:#1d6631}.h38-install-warn{color:#895d00}@media(max-width:540px){#h38InstallOfficeButton{display:none!important}.h38-install-dialog{width:calc(100vw - 14px)}}`;(document.head||document.documentElement).appendChild(style);}
function ensureDialog(){let dialog=document.getElementById('h38InstallOfficeDialog');if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='h38InstallOfficeDialog';dialog.className='h38-install-dialog';dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});document.body.appendChild(dialog);return dialog;}
function instructions(){const state=diagnostics();if(state.installed)return{title:'H38 Office is installed',lead:'Open it from your Home Screen, app launcher, Start menu, or shelf.',steps:[],direct:false};if(state.promptReady)return{title:'Install H38 Office',lead:`${state.platform} is ready to install the Business Office as an app.`,steps:['Choose Install H38 Office below.','Confirm the browser installation prompt.','Open H38 Office from the new app icon.'],direct:true};if(state.ios)return{title:`Add H38 Office to ${state.tablet?'iPad':'iPhone'}`,lead:'Apple requires the one-time Home Screen step from Safari.',steps:['Open this page in Safari.','Tap the Share button.','Choose Add to Home Screen.','Keep the H38 Office name and tap Add.'],direct:false};if(state.android)return{title:`Install H38 Office on your ${state.tablet?'tablet':'Android device'}`,lead:'If the direct install prompt is not shown yet, Chrome can still install from its menu.',steps:['Open this page in Chrome.','Tap the three-dot menu.','Choose Install and create shortcut, then Install (wording can vary by Chrome version).','If Install is not offered, reload this page once and open this Install H38 screen again.'],direct:false};if(state.chromeOS)return{title:'Install H38 Office on Chromebook',lead:'ChromeOS can run H38 as a web app from the launcher/shelf.',steps:['Open this page in Chrome.','Open the Chrome menu and choose the Install option if offered.','If only Create shortcut is available, create it and choose Open as window when offered.','Launch H38 Office from the Chromebook launcher or shelf.'],direct:false};if(state.chromium)return{title:'Install H38 Office',lead:'Chrome/Edge can install H38 from the address bar or browser menu.',steps:['Look for the Install icon in the address bar.','Or open the browser menu and choose Install page as app / Apps / Create shortcut.','Confirm H38 Office and open it from the new app icon.'],direct:false};return{title:'Install H38 Office',lead:'Your browser can save H38 Office as an app or Home Screen shortcut.',steps:['Open the browser menu.','Choose Install app, Add to Home Screen, or Create shortcut.','Confirm the H38 Office icon.'],direct:false};}
function diagnosticMarkup(state){const row=(label,ok,detail)=>`<span>${esc(label)}</span><strong class="${ok?'h38-install-ok':'h38-install-warn'}">${esc(detail)}</strong>`;return`<div class="h38-install-diagnostics">${row('Device',true,state.platform)}${row('Secure app page',state.secure,state.secure?'Ready':'HTTPS required')}${row('Web-app manifest',state.manifestPresent,state.manifestPresent?'Found':'Missing')}${row('Service worker support',state.serviceWorkerSupported,state.serviceWorkerSupported?'Supported':'Not supported')}${row('Direct browser prompt',state.promptReady,state.promptReady?'Ready':'Use device steps')}${state.lastPromptOutcome?row('Last install choice',state.lastPromptOutcome==='accepted',state.lastPromptOutcome):''}</div>`;}
function renderDialog(){const dialog=ensureDialog(),state=diagnostics(),info=instructions();dialog.innerHTML=`<div class="h38-install-shell"><div class="h38-install-head"><div><h2>${esc(info.title)}</h2><p>${esc(info.lead)}</p></div><button type="button" class="icon-button" data-install-close aria-label="Close">×</button></div>${info.steps.length?`<ol class="h38-install-steps">${info.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol>`:'<div class="h38-install-note h38-install-status">Installed and ready.</div>'}<div class="h38-install-note">${diagnosticMarkup(state)}</div>${!state.secure?'<div class="h38-install-note">This page is not in a secure HTTPS context, so the browser will not offer normal PWA installation.</div>':''}<div class="h38-install-note">H38 keeps the same secure sign-in and Business Office data. Installing only changes how you launch it.</div><div class="h38-install-actions">${info.direct?'<button type="button" class="primary" data-install-now>Install H38 Office</button>':''}<button type="button" class="secondary" data-install-check>Check again</button><button type="button" class="secondary" data-install-close>Close</button></div></div>`;dialog.querySelectorAll('[data-install-close]').forEach(button=>button.onclick=()=>dialog.close());dialog.querySelector('[data-install-now]')?.addEventListener('click',installNow);dialog.querySelector('[data-install-check]')?.addEventListener('click',()=>{syncButton();syncMoreAction();renderDialog();});return dialog;}
async function installNow(){if(standalone()||installed){renderDialog();return{outcome:'installed'};}if(!deferredPrompt){open();return{outcome:'instructions'};}const prompt=deferredPrompt;deferredPrompt=null;try{await prompt.prompt();const choice=await prompt.userChoice;lastPromptOutcome=String(choice?.outcome||'');installed=choice?.outcome==='accepted';syncButton();syncMoreAction();renderDialog();return choice||{outcome:installed?'accepted':'dismissed'};}catch(error){lastPromptOutcome='error';syncButton();syncMoreAction();renderDialog();return{outcome:'error',error};}}
function open(){ensureStyle();const dialog=renderDialog();if(typeof dialog.showModal==='function'){if(!dialog.open)dialog.showModal();}else dialog.setAttribute('open','');}
function syncButton(){ensureStyle();let button=document.getElementById('h38InstallOfficeButton');const actions=document.querySelector('.topbar .top-actions');if(!actions||phone()||standalone()||installed){button?.remove();return;}if(!button){button=document.createElement('button');button.type='button';button.id='h38InstallOfficeButton';button.className='secondary';button.textContent='Install H38';button.setAttribute('aria-label','Install H38 Office app');button.onclick=open;actions.insertBefore(button,actions.firstChild);}button.title=tablet()?'Install H38 Office on this tablet':'Install H38 Office';}
function syncMoreAction(){if(!mobile())return;const groups=document.querySelector('#h38PrimaryMoreDialog .h38-more-groups');if(!groups)return;let section=groups.querySelector('[data-h38-install-group]');const isInstalled=standalone()||installed;const installMode=isInstalled?'installed':tablet()?'tablet':'install';if(!section){section=document.createElement('section');section.className='h38-more-group';section.dataset.h38InstallGroup='1';groups.appendChild(section);}if(section.dataset.h38InstallState===installMode)return;section.dataset.h38InstallState=installMode;section.innerHTML=`<h3>App</h3><div class="h38-more-grid"><button type="button" data-h38-install-more><span>${isInstalled?'✓':'⬇'}</span><strong>${isInstalled?'H38 Office installed':tablet()?'Install H38 Office on tablet':'Install H38 Office'}</strong></button></div>`;section.querySelector('[data-h38-install-more]').onclick=open;}
function routeShortcut(){if(shortcutHandled)return;const params=new URLSearchParams(location.search),shortcut=String(params.get('shortcut')||'').trim();if(!SHORTCUTS.has(shortcut)){shortcutHandled=true;return;}const ready=()=>typeof window.openPage==='function'&&window.state?.snapshot?.user;let tries=0;const go=()=>{if(ready()){shortcutHandled=true;window.openPage(shortcut);return;}if(++tries<80)setTimeout(go,150);};go();}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;installed=false;lastPromptOutcome='';syncButton();syncMoreAction();if(document.getElementById('h38InstallOfficeDialog')?.open)renderDialog();});
window.addEventListener('appinstalled',()=>{installed=true;deferredPrompt=null;lastPromptOutcome='accepted';syncButton();syncMoreAction();if(document.getElementById('h38InstallOfficeDialog')?.open)renderDialog();});
window.matchMedia?.('(display-mode: standalone)')?.addEventListener?.('change',()=>{syncButton();syncMoreAction();});
window.addEventListener('resize',()=>{syncButton();syncMoreAction();},{passive:true});
document.addEventListener('click',event=>{if(event.target.closest?.('[data-h38-primary="more"]'))setTimeout(syncMoreAction,0);});
const observer=new MutationObserver(()=>{if(document.querySelector('#h38PrimaryMoreDialog[open],#h38PrimaryMoreDialog[open=""]'))syncMoreAction();});if(document.body)observer.observe(document.body,{childList:true,subtree:true});
window.H38_INSTALL_OFFICE={BUILD,open,install:installNow,state:installState,diagnostics,sync:syncButton,syncMoreAction,tablet,phone};
function init(){ensureStyle();syncButton();syncMoreAction();routeShortcut();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();