(function(){
'use strict';
const BUILD='20260924-platform-deepen-1';
let scheduled=false;
const text=v=>String(v==null?'':v).trim();
const num=v=>{const n=Number(String(v==null?'':v).replace(/[$,%]/g,''));return Number.isFinite(n)?n:0;};
const rows=name=>Array.isArray(window.state?.snapshot?.[name])?window.state.snapshot[name]:[];
const value=(r,...keys)=>{for(const k of keys)if(r&&r[k]!==undefined&&r[k]!==null&&r[k]!=='')return r[k];return'';};
const date=v=>{const d=new Date(v);return Number.isFinite(d.getTime())?d:null;};
const money=v=>typeof window.money==='function'?window.money(v):num(v).toLocaleString(undefined,{style:'currency',currency:'USD'});
const esc=v=>typeof window.esc==='function'?window.esc(v):text(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=(r,...keys)=>text(value(r,...keys));
const active=s=>!/(paid|closed|complete|completed|cancel|void|deleted|archived|rejected|expired)/i.test(text(s));
const isExample=r=>/\bDEMO\b|\bEX-/i.test([value(r,'Quote Number','Job Number','Invoice Number'),value(r,'Project Title'),value(r,'Status')].join(' '))||r?.['Example Data']===true;
const operational=name=>rows(name).filter(r=>!isExample(r));
function owner(){const u=window.state?.snapshot?.user||{};return u.owner===true||/\bowner\b/i.test(text(u.roleName||u.role));}
function styles(){if(document.getElementById('h38PlatformDeepenStyle'))return;const s=document.createElement('style');s.id='h38PlatformDeepenStyle';s.textContent='.h38-deepen-card{border:1px solid rgba(70,91,108,.22);border-radius:16px;padding:14px;background:var(--card,#fff);margin:12px 0}.h38-deepen-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.h38-deepen-metric,.h38-deepen-row{border:1px solid rgba(70,91,108,.16);border-radius:12px;padding:10px}.h38-deepen-metric strong{display:block;font-size:1.08rem}.h38-deepen-row small{display:block;opacity:.72;margin-top:3px}.h38-deepen-board{display:grid;grid-template-columns:repeat(7,minmax(130px,1fr));gap:7px;overflow:auto;padding-bottom:4px}.h38-deepen-day{border:1px solid rgba(70,91,108,.16);border-radius:12px;padding:9px;min-height:110px}.h38-deepen-list{display:grid;gap:7px}.h38-deepen-note{font-size:.82rem;line-height:1.4;opacity:.75}.h38-deepen-actions{display:flex;gap:7px;flex-wrap:wrap}.h38-deepen-critical{border-left:4px solid #a32a2a}.h38-deepen-warn{border-left:4px solid #a36a00}.h38-deepen-ok{border-left:4px solid #208451}@media(max-width:760px){.h38-deepen-grid{grid-template-columns:1fr 1fr}.h38-deepen-board{grid-template-columns:repeat(7,minmax(150px,1fr))}}@media(max-width:520px){.h38-deepen-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}
function schedules(){return[...operational('scheduleEvents'),...operational('schedule'),...operational('scheduleItems'),...operational('appointments')];}
function invoiceBalance(r){const total=num(value(r,'Total','total')),paid=num(value(r,'Paid','paid','Amount Paid','amountPaid')),balance=num(value(r,'Balance','Balance Due','balance','balanceDue'));return Math.max(0,balance||total-paid);}
function arAging(){const now=new Date(),buckets={current:0,d30:0,d60:0,d90:0,over90:0,total:0};for(const r of operational('invoices')){if(/paid|closed|void|deleted/i.test(text(value(r,'Status','status'))))continue;const balance=invoiceBalance(r);if(balance<=.005)continue;buckets.total+=balance;const due=date(value(r,'Due Date','dueDate'));if(!due||due>=now){buckets.current+=balance;continue;}const days=Math.floor((now-due)/86400000);if(days<=30)buckets.d30+=balance;else if(days<=60)buckets.d60+=balance;else if(days<=90)buckets.d90+=balance;else buckets.over90+=balance;}return buckets;}
function completedNotInvoiced(){const invoiceJobs=new Set(operational('invoices').map(r=>id(r,'Job ID','jobId')).filter(Boolean));return operational('jobs').filter(r=>/complete|completed|done/i.test(text(value(r,'Status','status')))&&!invoiceJobs.has(id(r,'Job ID','jobId','id')));}
function staleQuotes(){const now=Date.now();return operational('quotes').filter(r=>active(value(r,'Status','status'))).filter(r=>{const d=date(value(r,'Updated Time','updatedTime','Created Time','createdTime'));return d&&now-d.getTime()>14*86400000;});}
function marginModel(){const jobs=new Map();function rowFor(jobId){if(!jobId)return null;if(!jobs.has(jobId))jobs.set(jobId,{jobId,revenue:0,cost:0});return jobs.get(jobId);}for(const r of operational('invoices')){if(/void|deleted/i.test(text(value(r,'Status','status'))))continue;const j=rowFor(id(r,'Job ID','jobId'));if(j)j.revenue+=num(value(r,'Total','total'));}for(const r of operational('expenses')){const j=rowFor(id(r,'Job ID','jobId','Related Job ID','relatedJobId'));if(j)j.cost+=num(value(r,'Amount','amount','Total','total'));}return[...jobs.values()].map(j=>({...j,margin:j.revenue>0?100*(j.revenue-j.cost)/j.revenue:null,profit:j.revenue-j.cost})).sort((a,b)=>a.profit-b.profit);}
function ownerModel(){const ar=arAging(),uninvoiced=completedNotInvoiced(),stale=staleQuotes(),margins=marginModel(),losses=margins.filter(r=>r.revenue>0&&r.profit<0),jobs=operational('jobs').filter(r=>active(value(r,'Status','status'))),quotes=operational('quotes').filter(r=>active(value(r,'Status','status')));const actions=[];if(uninvoiced.length)actions.push({page:'money',title:`Invoice ${uninvoiced.length} completed job${uninvoiced.length===1?'':'s'}`,detail:'Completed work has no linked invoice.'});if(ar.over90>0)actions.push({page:'money',title:`Review ${money(ar.over90)} over 90 days`,detail:'Past-due receivables need collection review.'});if(losses.length)actions.push({page:'money',title:`Review ${losses.length} losing job${losses.length===1?'':'s'}`,detail:'Recorded job costs exceed recorded invoice revenue.'});if(stale.length)actions.push({page:'quotes',title:`Follow up ${stale.length} stale quote${stale.length===1?'':'s'}`,detail:'Open quotes have not been updated in 14+ days.'});return{ar,uninvoiced,stale,margins,losses,wip:jobs.length,openQuotes:quotes.length,actions:actions.slice(0,5)};}
function eventModel(){return schedules().map(r=>({raw:r,jobId:id(r,'Related Record ID','Job ID','jobId'),title:text(value(r,'Title','title','Project Title','projectTitle'))||'Scheduled work',start:date(value(r,'Start Time','startTime','Start','start')),end:date(value(r,'End Time','endTime','End','end')),userId:id(r,'Assigned User ID','assignedUserId'),assetIds:Array.isArray(value(r,'Assigned Asset IDs','assignedAssetIds'))?value(r,'Assigned Asset IDs','assignedAssetIds'):text(value(r,'Assigned Asset IDs','assignedAssetIds','Asset ID','assetId')).split(',').map(text).filter(Boolean),location:text(value(r,'Location','location'))})).filter(e=>e.start&&e.end);}
function dispatchDepth(){const events=eventModel(),scheduledJobs=new Set(events.map(e=>e.jobId).filter(Boolean)),jobs=operational('jobs').filter(r=>active(value(r,'Status','status'))),unscheduled=jobs.filter(r=>!scheduledJobs.has(id(r,'Job ID','jobId','id'))),priority=unscheduled.filter(r=>/emergency|urgent|high/i.test(text(value(r,'Priority','priority','Status','status','Notes','notes')))),missingLocation=jobs.filter(r=>!text(value(r,'Address','address','Service Address','serviceAddress','Location','location'))),start=new Date();start.setHours(0,0,0,0);const days=[];for(let i=0;i<7;i++){const s=new Date(start);s.setDate(s.getDate()+i);const e=new Date(s);e.setDate(e.getDate()+1);days.push({start:s,end:e,events:events.filter(x=>x.start<e&&s<x.end)});}return{events,jobs,unscheduled,priority,missingLocation,days};}
async function pendingOperations(){try{return await window.H38DB?.all?.('operations')||[];}catch(_){return[];}}
async function offlineModel(){const pending=(await pendingOperations()).filter(o=>!/SYNCED|DONE/i.test(text(o.status||o.syncStatus))),collections={assignedWork:operational('jobs').length+operational('tasks').length,customers:operational('customers').length,siteVisits:operational('siteVisits').length,notes:operational('notes').length+operational('fieldNotes').length,time:operational('timeEntries').length,mileage:operational('mileage').length+operational('mileageEntries').length,photos:operational('photos').length+operational('sitePhotos').length,attachments:operational('documents').length+operational('attachments').length,measurements:operational('measurements').length+operational('siteMeasurements').length,signatures:operational('signatures').length,receipts:operational('receipts').length+operational('expenses').filter(r=>text(value(r,'Receipt','receipt','Document ID','documentId'))).length};const queueReady=typeof window.queueOperation==='function'&&typeof window.sync==='function'&&!!window.H38DB;return{pending,collections,queueReady,deviceAccepted:false};}
function ensureCard(idValue,page){const main=document.getElementById('mainContent');if(!main)return null;let card=main.querySelector(`#${idValue}`);if(!card){card=document.createElement('section');card.id=idValue;card.className='h38-deepen-card';(main.querySelector('.grid')||main).prepend(card);}card.dataset.page=page;return card;}
function renderOwner(){if(text(window.state?.page)!=='today'||!owner())return;styles();const card=ensureCard('h38OwnerProfitabilityDeepening','today');if(!card)return;const m=ownerModel();card.innerHTML=`<div><span class="h38-platform-kicker">PROFITABILITY & BILLING CONTROL</span><h2>Owner operating cockpit</h2><p class="h38-deepen-note">Operational intelligence only. Recorded invoice/expense data is used; missing costs remain unknown and are never invented.</p></div><div class="h38-deepen-grid"><div class="h38-deepen-metric"><small>AR total</small><strong>${money(m.ar.total)}</strong><span>${money(m.ar.over90)} over 90 days</span></div><div class="h38-deepen-metric"><small>Completed not invoiced</small><strong>${m.uninvoiced.length}</strong></div><div class="h38-deepen-metric"><small>Open WIP</small><strong>${m.wip}</strong></div><div class="h38-deepen-metric"><small>Stale quotes</small><strong>${m.stale.length}</strong></div></div><div class="h38-deepen-grid" style="margin-top:8px"><div class="h38-deepen-metric"><small>Current</small><strong>${money(m.ar.current)}</strong></div><div class="h38-deepen-metric"><small>1–30 past due</small><strong>${money(m.ar.d30)}</strong></div><div class="h38-deepen-metric"><small>31–90 past due</small><strong>${money(m.ar.d60+m.ar.d90)}</strong></div><div class="h38-deepen-metric"><small>Losing jobs found</small><strong>${m.losses.length}</strong></div></div><div class="h38-deepen-list" style="margin-top:10px">${m.actions.map((a,i)=>`<div class="h38-deepen-row ${i===0?'h38-deepen-warn':''}"><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small><div class="h38-deepen-actions"><button type="button" class="secondary" data-deepen-page="${esc(a.page)}">Open</button></div></div>`).join('')||'<div class="h38-deepen-row h38-deepen-ok"><strong>No deterministic billing or margin exception found.</strong><small>Use the AI owner review for broader context.</small></div>'}</div>`;card.querySelectorAll('[data-deepen-page]').forEach(b=>b.addEventListener('click',()=>window.openPage?.(b.dataset.deepenPage)));}
function jobLabel(r){return text(value(r,'Project Title','projectTitle','Job Number','jobNumber','Job ID','jobId'))||'Job';}
function renderDispatch(){if(text(window.state?.page)!=='schedule')return;styles();const card=ensureCard('h38DispatchWeekDeepening','schedule');if(!card)return;const m=dispatchDepth();card.innerHTML=`<div><span class="h38-platform-kicker">DISPATCH PLANNING</span><h2>7-day work board</h2><p class="h38-deepen-note">This is a planning view over the canonical Schedule. “Plan” only pre-fills the existing deployment form; nothing is silently scheduled.</p></div><div class="h38-deepen-grid"><div class="h38-deepen-metric"><small>Unscheduled jobs</small><strong>${m.unscheduled.length}</strong></div><div class="h38-deepen-metric"><small>Urgent / high priority</small><strong>${m.priority.length}</strong></div><div class="h38-deepen-metric"><small>Jobs missing location</small><strong>${m.missingLocation.length}</strong></div><div class="h38-deepen-metric"><small>Scheduled events</small><strong>${m.events.length}</strong></div></div><div class="h38-deepen-board" style="margin-top:10px">${m.days.map(day=>`<div class="h38-deepen-day"><strong>${day.start.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</strong><div class="h38-deepen-list" style="margin-top:6px">${day.events.slice(0,8).map(e=>`<div class="h38-deepen-row"><strong>${esc(e.title)}</strong><small>${e.start.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}${e.location?' · '+esc(e.location):''}</small></div>`).join('')||'<small class="h38-deepen-note">No work</small>'}</div></div>`).join('')}</div><h3>Unscheduled queue</h3><div class="h38-deepen-list">${m.unscheduled.slice(0,12).map(j=>`<div class="h38-deepen-row ${m.priority.includes(j)?'h38-deepen-critical':''}"><strong>${esc(jobLabel(j))}</strong><small>${esc(text(value(j,'Priority','priority'))||'Normal priority')} · ${esc(text(value(j,'Address','address','Service Address','serviceAddress','Location','location'))||'Location missing')}</small><div class="h38-deepen-actions"><button type="button" class="secondary" data-plan-job="${esc(id(j,'Job ID','jobId','id'))}">Plan</button></div></div>`).join('')||'<div class="h38-deepen-row h38-deepen-ok"><strong>All active jobs have schedule coverage.</strong></div>'}</div><p class="h38-deepen-note">Route/distance values are not fabricated. Jobs with missing locations are called out; travel-time scoring stays unavailable until a verified routing source is connected.</p>`;card.querySelectorAll('[data-plan-job]').forEach(button=>button.addEventListener('click',()=>{const form=document.querySelector('#h38DispatchForm'),select=form?.querySelector('select[name="jobId"]');if(select){select.value=button.dataset.planJob||'';select.dispatchEvent(new Event('change',{bubbles:true}));form.scrollIntoView({behavior:'smooth',block:'center'});select.focus();window.toast?.('Job loaded into the existing deployment form. Review resources and time, then save.');}}));}
async function renderOffline(){if(!['field','work'].includes(text(window.state?.page)))return;styles();const card=ensureCard('h38OfflineWorkflowAcceptance',text(window.state?.page));if(!card)return;const m=await offlineModel(),coverage=[['Assigned work',m.collections.assignedWork],['Customers/sites',m.collections.customers],['Site visits',m.collections.siteVisits],['Notes',m.collections.notes],['Time',m.collections.time],['Mileage',m.collections.mileage],['Photos',m.collections.photos],['Attachments',m.collections.attachments],['Measurements',m.collections.measurements],['Signatures',m.collections.signatures],['Receipts',m.collections.receipts]];card.innerHTML=`<div><span class="h38-platform-kicker">OFFLINE ACCEPTANCE</span><h2>Field workflow readiness</h2><p class="h38-deepen-note">The existing user-scoped IndexedDB and operations queue remain authoritative. This surface checks cached workflow coverage; it does not claim physical-device acceptance.</p></div><div class="h38-deepen-grid"><div class="h38-deepen-metric"><small>Queue ready</small><strong>${m.queueReady?'Yes':'No'}</strong></div><div class="h38-deepen-metric"><small>Pending sync</small><strong>${m.pending.length}</strong></div><div class="h38-deepen-metric"><small>Connectivity</small><strong>${navigator.onLine?'Online':'Offline'}</strong></div><div class="h38-deepen-metric"><small>Physical airplane-mode acceptance</small><strong>Required</strong></div></div><div class="h38-deepen-list" style="margin-top:10px">${coverage.map(([label,count])=>`<div class="h38-deepen-row ${Number(count)>0?'h38-deepen-ok':'h38-deepen-warn'}"><strong>${esc(label)}</strong><small>${Number(count)} cached record${Number(count)===1?'':'s'} visible in the active tenant snapshot</small></div>`).join('')}</div><p class="h38-deepen-note">Final “true offline” acceptance still requires a phone/tablet to lose service, finish the entire job workflow, reconnect, sync, and verify server state.</p>`;}
function ownerBrief(command){const m=ownerModel(),lower=text(command).toLowerCase();if(/losing margin|losing job|margin/.test(lower)){const bad=m.losses.slice(0,8);return bad.length?['Recorded losing-job candidates:',...bad.map(x=>`- ${x.jobId}: revenue ${money(x.revenue)}, cost ${money(x.cost)}, profit ${money(x.profit)}.`),'Missing/unlinked costs are not assumed.'].join('\n'):'No job with both recorded invoice revenue and recorded costs is currently negative.';}if(/needs invoicing|work needs invoicing|completed.*invoice/.test(lower))return m.uninvoiced.length?['Completed jobs without a linked invoice:',...m.uninvoiced.slice(0,12).map(j=>`- ${jobLabel(j)}`)].join('\n'):'No completed job without a linked invoice was found.';if(/unpaid.*30|over 30|aging/.test(lower))return `AR aging: 1–30 ${money(m.ar.d30)}, 31–60 ${money(m.ar.d60)}, 61–90 ${money(m.ar.d90)}, over 90 ${money(m.ar.over90)}. Total open AR ${money(m.ar.total)}.`;if(/equipment conflict|dispatch conflict|plowing.*conflict/.test(lower)){const base=window.H38_PLATFORM_NEXT?.dispatchModel?.();return base?`Current dispatch conflicts: ${base.conflicts.length}. Open Schedule to review person/equipment overlaps; no schedule changes were made.`:'Dispatch model is still loading.';}if(/recurring work/.test(lower)){const base=window.H38_PLATFORM_NEXT?.ownerIntelligence?.();return base?`Recurring work due: ${base.recurringDue}. No work was scheduled automatically.`:'Owner intelligence is still loading.';}if(/changed since yesterday|top .*actions|what.*attention/.test(lower))return ['Owner actions from current deterministic records:',...m.actions.map((a,i)=>`${i+1}. ${a.title} — ${a.detail}`),'No action was executed.'].join('\n');if(/rate increase|price increase/.test(lower)){const pct=(text(command).match(/(\d+(?:\.\d+)?)\s*%/)||[])[1],p=Number(pct||8),baseline=operational('invoices').reduce((s,r)=>s+num(value(r,'Total','total')),0);return `Price-change preview only: ${p.toFixed(1)}% applied to the recorded invoice-revenue baseline of ${money(baseline)} equals ${money(baseline*p/100)} of arithmetic impact. This is not a forecast and no customer rate was changed.`;}return window.H38_PLATFORM_NEXT?.platformBrief?.()||'Platform intelligence is still loading.';}
function assistant(){const base=window.H38_ASSISTANT_COMMAND_BUS;if(!base||base.__h38PlatformDeepen)return;const re=/\b(rate increase|price increase|losing margin|losing jobs?|needs invoicing|work needs invoicing|equipment conflicts?|dispatch conflicts?|recurring work|unpaid invoices?|ar aging|changed since yesterday|top (?:3|4|5)?\s*actions?)\b/i;window.H38_ASSISTANT_COMMAND_BUS=Object.freeze({...base,__h38PlatformDeepen:true,canHandle:c=>re.test(text(c))||base.canHandle?.(c),handle:async(c,o={})=>re.test(text(c))?ownerBrief(c):(base.handle?.(c,o)||'')});}
function render(){renderOwner();renderDispatch();renderOffline();assistant();}
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;render();});}
window.addEventListener('h38:office-page-rendered',schedule);window.addEventListener('h38:business-snapshot-updated',schedule);window.addEventListener('online',schedule);window.addEventListener('offline',schedule);window.addEventListener('pageshow',schedule);
schedule();
window.H38_PLATFORM_DEEPEN=Object.freeze({build:BUILD,ownerModel,dispatchDepth,offlineModel,ownerBrief,safeguards:Object.freeze({taskManagerScheduleAuthority:true,existingOfflineQueueOnly:true,noInventedRouting:true,physicalOfflineAcceptanceRequired:true,aiArbitraryWrites:false,automaticScheduling:false,automaticAccountingWrites:false})});
})();
