package com.highway38.resellerscout;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.net.Uri;
import android.os.Bundle;
import android.os.Looper;
import android.provider.Settings;
import android.util.Base64;
import android.view.ViewGroup;
import android.webkit.JavascriptInterface;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.FrameLayout;
import android.widget.Toast;

import androidx.browser.customtabs.CustomTabsIntent;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import com.google.mlkit.vision.barcode.common.Barcode;
import com.google.mlkit.vision.codescanner.GmsBarcodeScanner;
import com.google.mlkit.vision.codescanner.GmsBarcodeScannerOptions;
import com.google.mlkit.vision.codescanner.GmsBarcodeScanning;
import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public final class MainActivity extends Activity {
    public static final String V200_RUNTIME="H38_SCOUT_V200_CLEAN_RUNTIME";
    public static final String V250_PACKAGED_PROVIDER_LAYER="V250_PACKAGED_PROVIDER_LAYER";
    private static final String APP_BASE_URL="https://highway38solutions.com/commercial-app/reseller-owner-test/";
    private static final int REQUEST_LOCATION=3901,REQUEST_PHOTO=3902;
    private FrameLayout contentRoot; private WebView webView; private String pendingPhotoRole="item";
    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(Color.rgb(13,42,62));getWindow().setNavigationBarColor(Color.WHITE);contentRoot=new FrameLayout(this);contentRoot.setBackgroundColor(Color.rgb(243,246,248));webView=new WebView(this);webView.setBackgroundColor(Color.rgb(243,246,248));contentRoot.addView(webView,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));setContentView(contentRoot);applyInsets();WebSettings settings=webView.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setDatabaseEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMediaPlaybackRequiresUserGesture(true);settings.setUserAgentString(settings.getUserAgentString()+" H38ResellerScoutAndroid/"+BuildConfig.VERSION_NAME);NativeBridge bridge=new NativeBridge();webView.addJavascriptInterface(bridge,"AndroidH38Reseller");webView.addJavascriptInterface(bridge,"AndroidH38Scout");webView.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,String url){if(url==null)return false;if(url.startsWith(APP_BASE_URL))return false;if(url.startsWith("http://")||url.startsWith("https://")){openExternal(url);return true;}return false;}@Override public void onPageFinished(WebView view,String url){deliverSharedText(getIntent());}});webView.loadDataWithBaseURL(APP_BASE_URL,bundledPage(),"text/html","UTF-8",null);}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);deliverSharedText(intent);}
    private void applyInsets(){ViewCompat.setOnApplyWindowInsetsListener(contentRoot,(view,insets)->{Insets bars=insets.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());view.setPadding(bars.left,bars.top,bars.right,bars.bottom);return WindowInsetsCompat.CONSUMED;});ViewCompat.requestApplyInsets(contentRoot);}
    private String bundledPage(){String html=readAsset("reseller/index.html");html=html.replace("<link rel=\"stylesheet\" href=\"v200-ui.css\">","<style>"+readAsset("reseller/v200-ui.css")+"</style>");for(String name:new String[]{"v200-core.js","v200-hunt.js","v200-auctions.js","v200-discover.js","v200-scan.js","v200-more.js","v210-polish.js","v211-wide.js","v212-physical.js","v220-profit.js","v220-track.js","v220-product.js","v200-app.js"})html=html.replace("<script src=\""+name+"\"></script>","<script data-h38-bundled-module=\""+name+"\">"+readAsset("reseller/"+name)+"</script>");String appMarker="<script data-h38-bundled-module=\"v200-app.js\">";html=html.replace(appMarker,"<script data-h38-bundled-module=\"v240-data.js\">"+readAsset("reseller/v240-data.js")+"</script>"+appMarker);String repairs="<script data-h38-bundled-module=\"v264-wide-repair.js\">"+readAsset("reseller/v264-wide-repair.js")+"</script><script data-h38-bundled-module=\"v265-facebook-acquisition-repair.js\">"+readAsset("reseller/v265-facebook-acquisition-repair.js")+"</script><script data-h38-bundled-module=\"v266-actionable-intake.js\">"+readAsset("reseller/v266-actionable-intake.js")+"</script>";return html.replace("</body>",repairs+"</body>");}
    private String readAsset(String path){try(InputStream in=getAssets().open(path);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int count;while((count=in.read(buffer))>0)out.write(buffer,0,count);return new String(out.toByteArray(),StandardCharsets.UTF_8);}catch(Exception e){return"<!doctype html><body><h2>Scout asset failed to load</h2><pre>"+e.getMessage()+"</pre></body>";}}
    private void openExternal(String url){try{if(url==null||!(url.startsWith("https://")||url.startsWith("http://")))return;new CustomTabsIntent.Builder().setShowTitle(true).build().launchUrl(this,Uri.parse(url));}catch(Exception first){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception second){Toast.makeText(this,"Could not open link.",Toast.LENGTH_SHORT).show();}}}
    private void deliverSharedText(Intent intent){if(intent==null||!Intent.ACTION_SEND.equals(intent.getAction()))return;String type=intent.getType();if(type!=null&&!type.startsWith("text/"))return;String text=intent.getStringExtra(Intent.EXTRA_TEXT);if(text==null||text.trim().isEmpty())text=intent.getStringExtra(Intent.EXTRA_SUBJECT);if(text==null||text.trim().isEmpty())return;String js="window.H38SharedOpportunity&&window.H38SharedOpportunity("+JSONObject.quote(text.trim())+");";webView.postDelayed(()->webView.evaluateJavascript(js,null),350);intent.setAction(null);}
    private void requestPhoneLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},REQUEST_LOCATION);return;}deliverLocation();}
    private void deliverLocation(){try{LocationManager manager=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String provider:new String[]{LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER,LocationManager.PASSIVE_PROVIDER})try{Location c=manager.getLastKnownLocation(provider);if(c!=null&&(best==null||c.getAccuracy()<best.getAccuracy()))best=c;}catch(SecurityException ignored){}if(best!=null&&System.currentTimeMillis()-best.getTime()<900000){sendLocation(best.getLatitude(),best.getLongitude());return;}String provider=manager.isProviderEnabled(LocationManager.GPS_PROVIDER)?LocationManager.GPS_PROVIDER:LocationManager.NETWORK_PROVIDER;manager.requestSingleUpdate(provider,new LocationListener(){@Override public void onLocationChanged(Location l){sendLocation(l.getLatitude(),l.getLongitude());}@Override public void onProviderEnabled(String p){}@Override public void onProviderDisabled(String p){}@Override public void onStatusChanged(String p,int s,Bundle e){}},Looper.getMainLooper());}catch(Exception e){sendLocationError(e.getMessage()==null?"Location unavailable":e.getMessage());}}
    private void sendLocation(double lat,double lon){webView.post(()->webView.evaluateJavascript("window.H38NativeLocationResult&&window.H38NativeLocationResult("+lat+","+lon+");",null));}private void sendLocationError(String t){webView.post(()->webView.evaluateJavascript("window.H38NativeLocationError&&window.H38NativeLocationError("+JSONObject.quote(t)+");",null));}private void sendBarcode(String v){String x=v==null?"":v.trim();webView.post(()->webView.evaluateJavascript("window.H38NativeBarcodeResult&&window.H38NativeBarcodeResult("+JSONObject.quote(x)+");",null));}private void sendBarcodeError(String t){String x=t==null||t.isBlank()?"Barcode scan failed.":t;webView.post(()->webView.evaluateJavascript("window.H38NativeBarcodeError&&window.H38NativeBarcodeError("+JSONObject.quote(x)+");",null));}
    private void scanBarcode(){GmsBarcodeScannerOptions o=new GmsBarcodeScannerOptions.Builder().setBarcodeFormats(Barcode.FORMAT_ALL_FORMATS).enableAutoZoom().build();GmsBarcodeScanning.getClient(this,o).startScan().addOnSuccessListener(b->{String v=b.getRawValue();if(v==null)v=b.getDisplayValue();sendBarcode(v);}).addOnCanceledListener(()->sendBarcodeError("Scan canceled")).addOnFailureListener(e->runOnUiThread(this::startFallbackBarcodeScanner));}private void startFallbackBarcodeScanner(){try{IntentIntegrator i=new IntentIntegrator(this);i.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);i.setPrompt("Point the camera at the barcode");i.setBeepEnabled(false);i.setOrientationLocked(true);i.initiateScan();}catch(Exception e){sendBarcodeError("Barcode scanner unavailable. Type the UPC instead.");}}
    private void takePhoto(String role){pendingPhotoRole=role==null||role.trim().isEmpty()?"item":role.trim();try{Intent i=new Intent(this,NativePhotoCaptureActivity.class);i.putExtra(NativePhotoCaptureActivity.EXTRA_ROLE,pendingPhotoRole);startActivityForResult(i,REQUEST_PHOTO);}catch(Exception e){webView.evaluateJavascript("window.H38NativePhotoError&&window.H38NativePhotoError('Scout camera could not open.');",null);}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);IntentResult sr=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(sr!=null){if(sr.getContents()==null||sr.getContents().isBlank())sendBarcodeError("Scan canceled");else sendBarcode(sr.getContents());return;}if(requestCode!=REQUEST_PHOTO)return;if(resultCode!=RESULT_OK){webView.evaluateJavascript("window.H38NativePhotoError&&window.H38NativePhotoError('Photo canceled');",null);return;}String path=data==null?"":data.getStringExtra(NativePhotoCaptureActivity.EXTRA_PATH),role=data==null?pendingPhotoRole:data.getStringExtra(NativePhotoCaptureActivity.EXTRA_ROLE);File file=path==null||path.isBlank()?null:new File(path);Bitmap bitmap=null;try{if(file==null||!file.isFile())throw new IllegalStateException();bitmap=BitmapFactory.decodeFile(file.getAbsolutePath());if(bitmap==null)throw new IllegalStateException();bitmap=scaleForResearch(bitmap,1600);try(ByteArrayOutputStream out=new ByteArrayOutputStream()){bitmap.compress(Bitmap.CompressFormat.JPEG,84,out);String d="data:image/jpeg;base64,"+Base64.encodeToString(out.toByteArray(),Base64.NO_WRAP);webView.evaluateJavascript("window.H38NativePhotoResult&&window.H38NativePhotoResult("+JSONObject.quote(role)+","+JSONObject.quote(d)+");",null);}}catch(Exception e){webView.evaluateJavascript("window.H38NativePhotoError&&window.H38NativePhotoError('Camera returned an unreadable image.');",null);}finally{try{if(file!=null)file.delete();}catch(Exception ignored){}if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();}}
    private static Bitmap scaleForResearch(Bitmap s,int m){int w=s.getWidth(),h=s.getHeight();if(w<=m&&h<=m)return s;double z=Math.min((double)m/Math.max(1,w),(double)m/Math.max(1,h));Bitmap x=Bitmap.createScaledBitmap(s,Math.max(1,(int)Math.round(w*z)),Math.max(1,(int)Math.round(h*z)),true);if(x!=s)s.recycle();return x;}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r!=REQUEST_LOCATION)return;for(int x:g)if(x==PackageManager.PERMISSION_GRANTED){deliverLocation();return;}sendLocationError("Location permission denied");}
    @Override public void onBackPressed(){if(webView==null){super.onBackPressed();return;}webView.evaluateJavascript("(window.H38HandleBack?window.H38HandleBack():false)",v->{if(!"true".equals(String.valueOf(v)))MainActivity.super.onBackPressed();});}
    private String buildIdentity(){String sha=BuildConfig.H38_BUILD_SHA==null?"local":BuildConfig.H38_BUILD_SHA;if(sha.length()>12)sha=sha.substring(0,12);return"v"+BuildConfig.VERSION_NAME+" · code "+BuildConfig.VERSION_CODE+" · "+sha+" · run "+BuildConfig.H38_BUILD_RUN;}
    private final class NativeBridge{@JavascriptInterface public void requestLocation(){runOnUiThread(MainActivity.this::requestPhoneLocation);}@JavascriptInterface public void scanBarcode(){runOnUiThread(MainActivity.this::scanBarcode);}@JavascriptInterface public void takePhoto(String r){runOnUiThread(()->MainActivity.this.takePhoto(r));}@JavascriptInterface public String build(){return buildIdentity();}@JavascriptInterface public void reloadScout(){runOnUiThread(MainActivity.this::recreate);}@JavascriptInterface public boolean notificationAccessEnabled(){try{String e=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");return e!=null&&e.contains(getPackageName());}catch(Exception ignored){return false;}}@JavascriptInterface public void openNotificationAccessSettings(){runOnUiThread(()->{try{startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS));}catch(Exception ignored){}});}@JavascriptInterface public String facebookNotificationCandidates(){return FacebookMarketplaceNotificationListener.rowsJson(MainActivity.this);}@JavascriptInterface public String facebookBrowserCandidates(){return FacebookMarketplaceActivity.rowsJson(MainActivity.this);}@JavascriptInterface public void openFacebookMarketplace(String t,double lat,double lon,int radius,String postal,String url){runOnUiThread(()->{Intent i=new Intent(MainActivity.this,FacebookMarketplaceActivity.class);i.putExtra(FacebookMarketplaceActivity.EXTRA_TERMS,t==null?"[]":t);i.putExtra(FacebookMarketplaceActivity.EXTRA_LAT,lat);i.putExtra(FacebookMarketplaceActivity.EXTRA_LON,lon);i.putExtra(FacebookMarketplaceActivity.EXTRA_RADIUS,radius);i.putExtra(FacebookMarketplaceActivity.EXTRA_POSTAL,postal==null?"":postal);i.putExtra(FacebookMarketplaceActivity.EXTRA_URL,url==null?"":url);startActivity(i);});}@JavascriptInterface public void startDeviceStockCheck(String id,String json){runOnUiThread(()->RetailerVerificationActivity.start(MainActivity.this,id,json));}}
}
