package com.highway38.resellerscout;

import android.app.Activity;
import android.app.Application;
import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Intent;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.JavascriptInterface;
import android.webkit.WebView;

import org.json.JSONObject;

public final class ResellerScoutPatchProvider extends ContentProvider implements Application.ActivityLifecycleCallbacks {
    private static final String ENGINE_MARKER = "H38_RESALE_OPPORTUNITY_ENGINE_V2";
    private static final String FACEBOOK_MARKER = "H38_FACEBOOK_AUTHENTICATED_BROWSER_V1";
    private static final String DEVICE_STOCK_MARKER = "H38_DEVICE_RETAILER_STOCK_V1";
    private static final String LOCATION_MARKER = "H38_PHONE_OR_ZIP_LOCATION_V3";
    private final Handler main = new Handler(Looper.getMainLooper());

    private static final String PATCH_JS = """
            (function(){
              'use strict';
              if(window.__H38ResaleOpportunityEngineV2){if(window.__H38OpportunityRefreshV2)window.__H38OpportunityRefreshV2();return;}
              window.__H38ResaleOpportunityEngineV2=true;
              window.__H38AutomaticOpportunityV4=true;
              window.__H38StrictAutoSourceScanV2=true;

              var ENDPOINT='https://jqukmwtsgcsaruucnqja.supabase.co/functions/v1/reseller-opportunity-scan';
              var STOCK='/functions/v1/reseller-stock-check';
              var SBKEY='sb_publishable_XrF41kGmTC2SmSTgPvo5OQ_vqcBd0N1';
              var DEFAULT_TERMS=['tools','Milwaukee','DeWalt','Snap-on','generator','welder','toolbox','zero turn','pressure washer'];
              var WATCH_KEY='h38_reseller_watch_terms_v2',SHARED_KEY='h38_reseller_shared_opportunities_v1';
              var ZIP_KEY='h38_reseller_zip_search_v1',LOCATION_MODE_KEY='h38_reseller_location_mode_v1';
              var STOCK_KEY='h38_reseller_stock_results_v1',MIGRATION='h38_v027_device_stock_migrated_v1';
              var scanBusy=false,lastScanAt=0,lastRequested='all',lastFacebookCount=-1,lastStockClick='',lastStockClickAt=0;
              var baseFetch=window.fetch.bind(window),deviceWait=new Map(),autoQueued=new Set();
              var FLYERS={
                'home depot':'https://www.homedepot.com/SpecialBuy/SpecialBuyOfTheDay',"lowe's":'https://www.lowes.com/l/savings','lowes':'https://www.lowes.com/l/savings',
                'walmart':'https://www.walmart.com/shop/deals','target':'https://www.target.com/c/weekly-ad/-/N-4ykuc','menards':'https://www.menards.com/main/flyer.html',
                'fleet farm':'https://www.fleetfarm.com/sitewide/weekly-ad','l&m fleet supply':'https://www.landmsupply.com/weekly-ad','harbor freight':'https://www.harborfreight.com/coupons-deals.html',
                'tractor supply':'https://www.tractorsupply.com/tsc/cms/weekly-ad','dollar general':'https://www.dollargeneral.com/weekly-ad','dollar tree':'https://www.dollartree.com/weekly-ads',
                'family dollar':'https://www.familydollar.com/weekly-ads','northern tool':'https://www.northerntool.com/sale','ace hardware':'https://www.acehardware.com/ace-rewards-instant-savings',
                'autozone':'https://www.autozone.com/lp/deals',"o'reilly auto parts":'https://www.oreillyauto.com/specials','napa auto parts':'https://www.napaonline.com/en/deals',
                'advance auto parts':'https://shop.advanceautoparts.com/o/special-offers','best buy':'https://www.bestbuy.com/site/top-deals/pcmcat1563299784494.c','walgreens':'https://www.walgreens.com/topic/promotion/weeklyad.jsp','cvs':'https://www.cvs.com/weeklyad'
              };

              function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'})[c]})}
              function norm(v){return String(v||'').trim().toLowerCase().replace(/\\s+/g,' ')}
              function loadArray(k){try{var x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
              function loadObject(k){try{var x=JSON.parse(localStorage.getItem(k)||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch(e){return{}}}
              function saveObject(k,x){try{localStorage.setItem(k,JSON.stringify(x))}catch(e){}}
              function money(v){var n=Number(v);return Number.isFinite(n)&&n>0?'$'+n.toFixed(2):'—'}
              function pct(v){var n=Number(v);return Number.isFinite(n)?Math.round(n)+'%':'—'}
              function terms(){var x=loadArray(WATCH_KEY);return x.length?x.slice(0,12):DEFAULT_TERMS.slice()}
              function token(){try{var raw=localStorage.getItem('sb-jqukmwtsgcsaruucnqja-auth-token');var p=raw?JSON.parse(raw):null;return p&&p.access_token?String(p.access_token):''}catch(e){return''}}
              function headers(){var t=token(),h={'content-type':'application/json','apikey':SBKEY};if(t)h.authorization='Bearer '+t;return h}
              function zipState(){try{var z=JSON.parse(localStorage.getItem(ZIP_KEY)||'null');return z&&/^\\d{5}$/.test(String(z.zip||''))&&Number.isFinite(Number(z.lat))&&Number.isFinite(Number(z.lon))?z:null}catch(e){return null}}
              function mode(){try{return localStorage.getItem(LOCATION_MODE_KEY)==='zip'?'zip':'phone'}catch(e){return 'phone'}}
              function cachedPoint(){try{var raw=JSON.parse(localStorage.getItem('h38_reseller_last_store_response_v1')||'null');var q=raw&&JSON.parse(String(raw.requestBody||'{}'));var lat=Number(q&&q.lat),lon=Number(q&&q.lon);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat:lat,lon:lon}:null}catch(e){return null}}
              function locationContext(){var z=zipState(),p=(mode()==='zip'&&z)?z:(window.__H38OpportunityLocationV2||cachedPoint()||{}),r=Number((document.getElementById('radius')||{}).value||50);if([25,50,100,150].indexOf(r)<0)r=50;return {lat:Number(p.lat),lon:Number(p.lon),postal:(mode()==='zip'&&z)?String(z.zip):'',radiusMiles:r}}
              function setLocationStatus(text,bad){var s=document.getElementById('status');if(!s)return;s.className='notice '+(bad?'bad':'');s.textContent=text}
              function labelZip(z){var l=document.getElementById('locationLabel');if(!l||!z)return;var place=[z.place,z.state].filter(Boolean).join(', ');l.textContent='ZIP '+z.zip+(place?' · '+place:'')}
              function reloadScout(){try{if(window.AndroidH38Scout&&typeof window.AndroidH38Scout.reloadScout==='function'){window.AndroidH38Scout.reloadScout();return}}catch(e){}location.reload()}

              function migrateOldStock(){try{if(localStorage.getItem(MIGRATION)==='1')return;var x=loadObject(STOCK_KEY),changed=false;Object.keys(x).forEach(function(k){var p=x[k]||{},r=String(p.retailer||'');if((r==='Home Depot'||r==='Dollar General')&&(p.status==='retailer_blocked'||p.source_mode!=='device_browser')){delete x[k];changed=true}});if(changed)saveObject(STOCK_KEY,x);localStorage.setItem(MIGRATION,'1')}catch(e){}}
              migrateOldStock();

              function style(){if(document.getElementById('h38OpportunityStyleV2'))return;var s=document.createElement('style');s.id='h38OpportunityStyleV2';s.textContent='.h38-auto-deck{margin:10px 0;padding:11px;border:1px solid #cbd7df;border-radius:12px;background:#f8fbfd}.h38-auto-deck h3{margin:0 0 5px;font-size:15px}.h38-source-buttons{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.h38-source-buttons button{padding:7px 9px;font-size:12px}.h38-auto-status{font-size:11px;margin-top:5px}.h38-watch-chips{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.h38-watch-chip{font-size:11px;padding:4px 7px;border-radius:999px;background:#e7eef3}.h38-opportunity{display:grid;grid-template-columns:82px 1fr;gap:9px;padding:10px;border:1px solid #d6e0e7;border-radius:10px;margin-top:8px;background:#fff}.h38-opportunity img{width:82px;height:82px;object-fit:cover;border-radius:8px;background:#eef3f7}.h38-opportunity.noimg{grid-template-columns:1fr}.h38-opp-title{font-weight:850}.h38-opp-grade{display:inline-block;padding:3px 7px;border-radius:999px;background:#dff5e8;color:#126132;font-size:10px;font-weight:900}.h38-opp-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;margin:7px 0}.h38-opp-stat{padding:6px;background:#f4f7f9;border-radius:7px}.h38-opp-stat strong{display:block;font-size:13px}.h38-opp-stat span{font-size:9px;color:#607180}.h38-fb-access,.h38-stock-summary{padding:8px;border-radius:9px;background:#eef4f8;margin-top:7px;font-size:12px}.h38-flyer{margin:7px 8px 10px;padding:8px;border:1px dashed #a8bac6;border-radius:9px;background:#f6fafc}.h38-flyer button{font-size:12px;padding:6px 9px}.h38-device-store{margin:7px 10px}.h38-device-store button{padding:6px 9px;font-size:11px}@media(max-width:650px){.h38-opp-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}';document.head.appendChild(s)}
              function renderWatches(){var h=document.getElementById('h38WatchChips');if(!h)return;h.innerHTML=terms().map(function(x){return '<span class="h38-watch-chip">'+esc(x)+'</span>'}).join('')}

              function bridge(){return window.AndroidH38Scout||null}
              function parseBridgeRows(fn){try{var b=bridge(),raw=b&&b[fn]&&b[fn]();var a=JSON.parse(String(raw||'[]'));return Array.isArray(a)?a:[]}catch(e){return[]}}
              function facebookCandidates(){var out=[];parseBridgeRows('facebookBrowserCandidates').forEach(function(x){out.push(x)});parseBridgeRows('facebookNotificationCandidates').forEach(function(x){out.push(x)});loadArray(SHARED_KEY).forEach(function(x){var txt=String(x.text||''),u=String(x.url||''),src=String(x.source||'').toLowerCase();if(src.indexOf('facebook')<0&&u.indexOf('facebook.com/marketplace')<0&&txt.toLowerCase().indexOf('marketplace')<0)return;out.push({id:'shared:'+String(x.at||u||txt).slice(0,100),source:'Facebook Marketplace',title:txt,text:txt,url:u,price:null,posted_at:Number(x.atMs||Date.now()),shared:true})});var seen=new Set();return out.filter(function(x){var k=String(x.id||x.url||x.title||x.text);if(!k||seen.has(k))return false;seen.add(k);return true}).slice(0,180)}
              function openFacebook(url){var c=locationContext();try{bridge().openFacebookMarketplace(JSON.stringify(terms()),Number.isFinite(c.lat)?c.lat:0,Number.isFinite(c.lon)?c.lon:0,c.radiusMiles,c.postal||'',String(url||''))}catch(e){var s=document.getElementById('h38SourceStatus');if(s)s.textContent='Could not open the Scout Facebook browser: '+String(e)}}
              function notificationEnabled(){try{return !!(bridge()&&bridge().notificationAccessEnabled())}catch(e){return false}}
              function renderFacebookAccess(){var h=document.getElementById('h38FacebookAccess');if(!h)return;var browser=parseBridgeRows('facebookBrowserCandidates'),notes=parseBridgeRows('facebookNotificationCandidates');h.innerHTML='<strong>Facebook Marketplace:</strong> '+browser.length+' browser-session listing'+(browser.length===1?'':'s')+' captured · '+notes.length+' notification candidate'+(notes.length===1?'':'s')+'. <button id="h38OpenFacebook" type="button">Search Facebook in Scout</button>'+(notificationEnabled()?'':' <button id="h38FbNotify" type="button" class="secondary">Enable alert capture</button>');var b=document.getElementById('h38OpenFacebook');if(b)b.onclick=function(e){e.preventDefault();openFacebook('')};var n=document.getElementById('h38FbNotify');if(n)n.onclick=function(e){e.preventDefault();try{bridge().openNotificationAccessSettings()}catch(x){}}}

              function stockKeyForBody(b){return [String(b.store_key||''),norm(b.title),String(b.upc||'').replace(/\\D/g,''),norm(b.sku)].join('|')}
              function persistDeviceResult(id,p){var x=loadObject(STOCK_KEY);x[id]=p;saveObject(STOCK_KEY,x)}
              window.H38DeviceStockResult=function(id,json){var waiter=deviceWait.get(String(id));if(!waiter)return;deviceWait.delete(String(id));var p={};try{p=JSON.parse(String(json||'{}'))}catch(e){p={status:'device_unavailable',stock_checked:true,availability_label:'Device result could not be parsed.'}}persistDeviceResult(waiter.stockId||String(id),p);decorateDeviceStock();waiter.resolve(new Response(JSON.stringify(p),{status:200,headers:{'content-type':'application/json'}}))};
              function deviceStockFetch(body){return new Promise(function(resolve){var requestId='ds-'+Date.now()+'-'+Math.random().toString(36).slice(2),sid=(Date.now()-lastStockClickAt<1800&&lastStockClick)?lastStockClick:stockKeyForBody(body);deviceWait.set(requestId,{resolve:resolve,stockId:sid});try{bridge().startDeviceStockCheck(requestId,JSON.stringify(body))}catch(e){deviceWait.delete(requestId);resolve(new Response(JSON.stringify({status:'device_unavailable',retailer:body.retailer,stock_checked:true,stock_status:'unknown',stock_count:null,current_price:null,store_bound:false,source_mode:'device_browser',availability_label:'Could not start device retailer check.'}),{status:200,headers:{'content-type':'application/json'}}));return}setTimeout(function(){var w=deviceWait.get(requestId);if(!w)return;deviceWait.delete(requestId);var p={status:'device_unavailable',retailer:body.retailer,stock_checked:true,stock_status:'unknown',stock_count:null,current_price:null,store_bound:false,source_mode:'device_browser',availability_label:'Device retailer check timed out.'};persistDeviceResult(sid,p);decorateDeviceStock();resolve(new Response(JSON.stringify(p),{status:200,headers:{'content-type':'application/json'}}))},22000)})}
              window.fetch=async function(input,init){var u=typeof input==='string'?input:(input&&input.url)||'';if(u.indexOf(STOCK)>=0){var b={};try{b=JSON.parse(String(init&&init.body||'{}'))}catch(e){}if(b.retailer==='Home Depot'||b.retailer==='Dollar General')return deviceStockFetch(b)}return baseFetch(input,init)};

              document.addEventListener('click',function(e){var n=e.target;if(!(n instanceof Element))return;var b=n.closest('[data-stock],[data-stock-saved]');if(b){lastStockClick=String(b.dataset.stock||b.dataset.stockSaved||'');lastStockClickAt=Date.now()}},true);
              function stockText(p,kind){if(!p)return 'Not checked';if(kind==='price'){var n=Number(p.current_price);if(Number.isFinite(n)&&n>0)return '$'+n.toFixed(2);if(p.status==='device_store_setup_required')return 'Set store';if(p.status==='device_product_not_resolved')return 'No product';return p.store_bound?'Not exposed':'Not verified'}var q=p.stock_count;if(q!==null&&q!==undefined&&q!==''&&Number.isFinite(Number(q)))return String(Number(q));if(p.stock_status==='out_of_stock')return 'OUT';if(p.stock_status==='in_stock')return 'IN';if(p.status==='device_store_setup_required')return 'Set store';if(p.store_bound)return 'Qty not exposed';return 'Not verified'}
              function setupBody(d,lead){var txt=String(lead&&lead.textContent||''),u=txt.match(/UPC\\s+(\\d+)/i),s=txt.match(/Model\\/SKU\\s+([^·\\n]+)/i),title=lead&&lead.querySelector('.lead-title'),storeTitle=d&&d.querySelector('.store-title');return {retailer:String(storeTitle&&storeTitle.textContent||'').trim(),title:String(title&&title.textContent||'').trim(),upc:u?u[1]:'',sku:s?s[1].trim():'',source_url:'',store_key:String(d&&d.dataset.storeKey||''),store_name:String(storeTitle&&storeTitle.textContent||'').trim(),store_address:String((d&&d.querySelector('.muted.small')&&d.querySelector('.muted.small').textContent)||'').trim()}}
              function decorateDeviceStock(){var x=loadObject(STOCK_KEY);document.querySelectorAll('details[data-store-key] .lead').forEach(function(lead){var b=lead.querySelector('[data-stock]');if(!b)return;var id=String(b.dataset.stock||''),p=x[id];if(!p||p.source_mode!=='device_browser')return;var meta=lead.querySelector('.lead-meta');if(meta){var pb=meta.querySelector('[data-h38-store-price]'),qb=meta.querySelector('[data-h38-store-qty]');if(!pb){pb=document.createElement('div');pb.className='stat';pb.setAttribute('data-h38-store-price','1');pb.innerHTML='<strong></strong><span>STORE PRICE</span>';meta.appendChild(pb)}if(!qb){qb=document.createElement('div');qb.className='stat';qb.setAttribute('data-h38-store-qty','1');qb.innerHTML='<strong></strong><span>STORE QTY</span>';meta.appendChild(qb)}pb.querySelector('strong').textContent=stockText(p,'price');qb.querySelector('strong').textContent=stockText(p,'qty')}var st=lead.querySelector('[data-h38-store-status]');if(!st){st=document.createElement('div');st.className='stock-line small';st.setAttribute('data-h38-store-status','1');var a=lead.querySelector('.actions');lead.insertBefore(st,a)}st.textContent=String(p.availability_label||'Device retailer check complete.');});decorateRetailerSetup();renderStockSummary()}
              function decorateRetailerSetup(){document.querySelectorAll('details[data-store-key]').forEach(function(d){if(d.querySelector('.h38-device-store'))return;var name=String((d.querySelector('.store-title')||{}).textContent||'').trim();if(name!=='Home Depot'&&name!=='Dollar General')return;var lead=d.querySelector('.lead'),body=setupBody(d,lead),box=document.createElement('div');box.className='h38-device-store';box.innerHTML='<button type="button" class="secondary">Set / verify '+esc(name)+' store on phone</button>';var btn=box.querySelector('button');btn.onclick=function(e){e.preventDefault();e.stopPropagation();try{bridge().openRetailerSession(JSON.stringify(body))}catch(x){}};var host=d.querySelector('.store-body')||d;host.appendChild(box)})}
              function renderStockSummary(){var h=document.getElementById('h38StockSummary');if(!h)return;var x=loadObject(STOCK_KEY),vals=Object.keys(x).map(function(k){return x[k]||{}});function r(name){var a=vals.filter(function(p){return p.retailer===name&&p.source_mode==='device_browser'}),verified=a.filter(function(p){return p.store_bound&&(Number(p.current_price)>0||p.stock_status==='in_stock'||p.stock_status==='out_of_stock'||p.stock_count!==null&&p.stock_count!==undefined)}).length,price=a.filter(function(p){return Number(p.current_price)>0}).length,qty=a.filter(function(p){return p.stock_count!==null&&p.stock_count!==undefined&&p.stock_count!==''}).length,setup=a.filter(function(p){return p.status==='device_store_setup_required'}).length;return name+': '+a.length+' device checks · '+verified+' verified · '+price+' prices · '+qty+' exact qty'+(setup?' · '+setup+' need store setup':'')}var other=vals.filter(function(p){return p.source_mode!=='device_browser'}),blocked=other.filter(function(p){return p.status==='retailer_blocked'}).length;h.textContent=r('Home Depot')+' | '+r('Dollar General')+(other.length?' | Other retailers: '+other.length+' checks · '+blocked+' blocked':'')}
              function queueDeviceChecks(){var x=loadObject(STOCK_KEY),todo=[];document.querySelectorAll('details[data-store-key]').forEach(function(d){if(todo.length>=8)return;var retailer=String((d.querySelector('.store-title')||{}).textContent||'').trim();if(retailer!=='Home Depot'&&retailer!=='Dollar General')return;var take=d.open?4:1,got=0;d.querySelectorAll('[data-stock]').forEach(function(b){if(todo.length>=8||got>=take)return;var id=String(b.dataset.stock||'');if(!id||x[id]||autoQueued.has(id)||b.disabled)return;autoQueued.add(id);todo.push(b);got++})});todo.forEach(function(b,i){setTimeout(function(){if(document.body.contains(b)&&!b.disabled){lastStockClick=String(b.dataset.stock||'');lastStockClickAt=Date.now();b.click()}},i*2600)})}

              function retailerName(d){var t=String(d&&d.textContent||'').toLowerCase(),keys=Object.keys(FLYERS);for(var i=0;i<keys.length;i++)if(t.indexOf(keys[i])>=0)return keys[i];return ''}
              function fallbackFlyerUrl(d){var name=String(d&&d.querySelector('summary')&&d.querySelector('summary').textContent||d&&d.textContent||'store').trim().replace(/\\s+/g,' ');return 'https://www.google.com/search?q='+encodeURIComponent(name+' weekly ad flyer deals')}
              function decorateStoreFlyers(){var list=document.getElementById('storeList');if(!list)return;Array.from(list.querySelectorAll('details.store,details[data-store-key]')).forEach(function(d){if(d.querySelector('.h38-flyer'))return;var key=retailerName(d),url=key?FLYERS[key]:fallbackFlyerUrl(d),name=String(d.querySelector('summary')&&d.querySelector('summary').textContent||'Store').trim().replace(/\\s+/g,' ');var box=document.createElement('div');box.className='h38-flyer';box.innerHTML='<div class="small"><strong>Ad / flyer source</strong> · sale source for this store.</div><div class="actions"><button data-flyer-open="'+esc(url)+'">Open '+esc(name)+' ad / deals</button></div>';d.appendChild(box);var b=box.querySelector('[data-flyer-open]');if(b)b.onclick=function(e){e.preventDefault();e.stopPropagation();window.location.href=b.dataset.flyerOpen}})}

              function installDeck(){style();var list=document.getElementById('storeList');if(!list||!list.parentNode)return false;var d=document.getElementById('h38AutomaticDeck');if(!d){d=document.createElement('section');d.id='h38AutomaticDeck';d.className='card h38-auto-deck';list.parentNode.insertBefore(d,list)}if(d.dataset.h38Engine!=='2'){d.dataset.h38Engine='2';d.innerHTML='<h3>Resale opportunity analyzer</h3><div class="muted small">Only verified, profit-supported resale opportunities reach this list. Craigslist and auction search hits are opened and checked before scoring. Facebook uses the authenticated Scout browser session on this phone; alerts and shared listings are supplemental.</div><div class="h38-source-buttons"><button data-h38-scan="all">Scan all</button><button data-h38-scan="Facebook Marketplace">Facebook</button><button data-h38-scan="HiBid">Auctions</button><button data-h38-scan="Craigslist">Craigslist</button></div><div id="h38FacebookAccess" class="h38-fb-access"></div><div id="h38WatchChips" class="h38-watch-chips"></div><div id="h38AutoStatus" class="h38-auto-status muted">Opportunity engine ready.</div><div id="h38SourceStatus" class="h38-auto-status muted"></div><div id="h38StockSummary" class="h38-stock-summary"></div><div id="h38AutoFinds"></div>';d.querySelectorAll('[data-h38-scan]').forEach(function(b){b.onclick=function(e){e.preventDefault();e.stopPropagation();var s=b.dataset.h38Scan||'all';if(s==='Facebook Marketplace'&&facebookCandidates().length===0){openFacebook('');return}scan(true,s)}})}renderWatches();renderFacebookAccess();renderStockSummary();decorateStoreFlyers();decorateRetailerSetup();labelCandidateCount();return true}
              function labelCandidateCount(){var stat=document.getElementById('statLeads');if(stat&&stat.parentElement){var sp=stat.parentElement.querySelector('span');if(sp)sp.textContent='Deal / penny candidates'}var fd=document.getElementById('feedDiagnostics');if(fd&&fd.innerHTML.indexOf('Automatic source check:')>=0)fd.innerHTML=fd.innerHTML.replace('Automatic source check:','Candidate source check:')}
              function grade(x){return Number(x.roi_pct)>=60?'STRONG BUY':Number(x.roi_pct)>=35?'GOOD BUY':'PROFITABLE'}
              function renderFinds(rows){var h=document.getElementById('h38AutoFinds');if(!h)return;rows=Array.isArray(rows)?rows:[];if(!rows.length){h.innerHTML='<div class="muted small" style="margin-top:8px">No verified profitable resale opportunities returned. Scout is hiding unverified search hits, missing-comp items, and out-of-area noise.</div>';return}h.innerHTML=rows.slice(0,28).map(function(x){var img=String(x.image_url||''),dist=Number(x.distance_miles),distText=Number.isFinite(dist)?dist.toFixed(1)+' mi':String(x.location_label||'location verified by source'),buy=x.estimated_all_in||x.buy_price,resale=x.resale_estimate,profit=x.net_profit,roi=x.roi_pct,source=String(x.source||'Source'),age=x.age_label||x.closing_label||'',meta=[source,distText,age,x.comp_confidence?('comp '+x.comp_confidence+' · '+Number(x.comp_samples||0)+' sold'):'' ].filter(Boolean).join(' · '),open='';if(source==='Facebook Marketplace')open='<button data-fb-url="'+esc(x.url||'')+'">Open Facebook listing</button>';else if(x.url)open='<button data-auto-open="'+esc(x.url)+'">Open original listing</button>';var auction=source==='HiBid'?'<div class="h38-opp-grid"><div class="h38-opp-stat"><strong>'+money(x.buy_price)+'</strong><span>CURRENT BID</span></div><div class="h38-opp-stat"><strong>'+money(x.max_bid)+'</strong><span>MAX BID FOR TARGET</span></div><div class="h38-opp-stat"><strong>'+pct(x.buyer_premium_pct)+'</strong><span>BUYER PREMIUM</span></div><div class="h38-opp-stat"><strong>'+money(x.travel_cost)+'</strong><span>TRAVEL EST.</span></div></div>':'';return '<div class="h38-opportunity '+(img?'':'noimg')+'">'+(img?'<img src="'+esc(img)+'" alt="">':'')+'<div><span class="h38-opp-grade">'+grade(x)+'</span><div class="h38-opp-title">'+esc(x.title||'Listing')+'</div><div class="small muted">'+esc(meta)+'</div><div class="h38-opp-grid"><div class="h38-opp-stat"><strong>'+money(buy)+'</strong><span>EST. ALL-IN</span></div><div class="h38-opp-stat"><strong>'+money(resale)+'</strong><span>SOLD COMP MEDIAN</span></div><div class="h38-opp-stat"><strong>'+money(profit)+'</strong><span>EST. NET</span></div><div class="h38-opp-stat"><strong>'+pct(roi)+'</strong><span>ROI</span></div></div>'+auction+'<div class="small muted">Verified listing detail · resale fee allowance '+pct(x.selling_friction_pct)+' · travel included when distance is available.</div>'+(open?'<div class="actions">'+open+'</div>':'')+'</div></div>'}).join('');h.querySelectorAll('[data-auto-open]').forEach(function(b){b.onclick=function(e){e.preventDefault();window.location.href=b.dataset.autoOpen}});h.querySelectorAll('[data-fb-url]').forEach(function(b){b.onclick=function(e){e.preventDefault();openFacebook(String(b.dataset.fbUrl||''))}})}
              function sourceStatus(p){var h=document.getElementById('h38SourceStatus');if(!h)return;var s=p&&p.source_summary||{},parts=[];Object.keys(s).forEach(function(k){var x=s[k]||{};parts.push(k+': '+Number(x.search_hits||x.matches||0)+' hits · '+Number(x.detail_verified||0)+' detail verified · '+Number(x.comp_verified||0)+' comp verified · '+Number(x.qualified||0)+' profitable'+(Number(x.failed||0)?' · '+Number(x.failed)+' unavailable':''))});h.textContent=parts.join(' | ')||'No source status returned.'}
              async function scan(force,requested){if(!installDeck()||scanBusy)return;var now=Date.now();if(!force&&now-lastScanAt<120000)return;scanBusy=true;lastScanAt=now;lastRequested=requested||'all';var st=document.getElementById('h38AutoStatus'),ctx=locationContext(),fb=facebookCandidates();if(st)st.textContent='Verifying resale listings and profit near '+(mode()==='zip'&&zipState()?('ZIP '+zipState().zip):'phone location')+'…';try{var body={terms:terms(),lat:Number.isFinite(ctx.lat)?ctx.lat:null,lon:Number.isFinite(ctx.lon)?ctx.lon:null,radiusMiles:ctx.radiusMiles,postal:ctx.postal,facebookCandidates:fb};body.sources=lastRequested==='all'?['Craigslist','HiBid','Facebook Marketplace']:[lastRequested];var r=await baseFetch(ENDPOINT,{method:'POST',headers:headers(),body:JSON.stringify(body)}),p=await r.json().catch(function(){return{}});if(!r.ok)throw new Error((p&&p.error)||('HTTP '+r.status));renderFinds(p&&p.opportunities);sourceStatus(p);if(st)st.textContent='Verified opportunity scan complete · '+Number(p&&p.search_hits||0)+' search hits · '+Number(p&&p.detail_verified||0)+' detail verified · '+Number(p&&p.opportunities&&p.opportunities.length||0)+' profitable.'}catch(e){renderFinds([]);if(st)st.textContent='Opportunity scan unavailable.';var ss=document.getElementById('h38SourceStatus');if(ss)ss.textContent=String(e&&e.message||e)}finally{scanBusy=false;renderFacebookAccess();decorateDeviceStock();decorateStoreFlyers()}}

              function wrapNativeLocation(){if(window.__H38LocationWrappedV3)return true;var original=window.H38NativeLocationResult;if(typeof original!=='function')return false;var originalError=window.H38NativeLocationError;window.__H38LocationWrappedV3=true;window.H38NativeLocationResult=function(lat,lon){var z=zipState();if(mode()==='zip'&&z){window.__H38OpportunityLocationV2={lat:Number(z.lat),lon:Number(z.lon)};original(Number(z.lat),Number(z.lon));setTimeout(function(){labelZip(z)},60);return}window.__H38OpportunityLocationV2={lat:Number(lat),lon:Number(lon)};original(lat,lon)};if(typeof originalError==='function')window.H38NativeLocationError=function(text){var z=zipState();if(mode()==='zip'&&z){window.H38NativeLocationResult(Number(z.lat),Number(z.lon));return}originalError(text)};return true}
              async function searchZip(input,button){var zip=String(input&&input.value||'').replace(/\\D/g,'').slice(0,5);if(input)input.value=zip;if(!/^\\d{5}$/.test(zip)){setLocationStatus('Enter a 5-digit ZIP code.',true);return}if(button)button.disabled=true;setLocationStatus('Finding ZIP '+zip+'…',false);try{var r=await baseFetch('https://api.zippopotam.us/us/'+encodeURIComponent(zip),{method:'GET'});if(!r.ok)throw new Error('ZIP not found');var p=await r.json(),place=Array.isArray(p.places)&&p.places.length?p.places[0]:null,lat=Number(place&&place.latitude),lon=Number(place&&place.longitude);if(!place||!Number.isFinite(lat)||!Number.isFinite(lon))throw new Error('ZIP location unavailable');var z={zip:zip,lat:lat,lon:lon,place:String(place['place name']||''),state:String(place['state abbreviation']||place.state||'')};localStorage.setItem(ZIP_KEY,JSON.stringify(z));localStorage.setItem(LOCATION_MODE_KEY,'zip');setLocationStatus('Switching Scout to ZIP '+zip+'…',false);reloadScout()}catch(e){setLocationStatus('ZIP search failed: '+String(e&&e.message||e),true);if(button)button.disabled=false}}
              function installLocationControls(){var line=document.querySelector('.location-line'),locate=document.getElementById('locateBtn');if(!line||!locate)return false;locate.textContent='Use phone location';if(!locate.dataset.h38PhoneModeV3){locate.dataset.h38PhoneModeV3='1';locate.addEventListener('click',function(e){if(mode()==='zip'){e.preventDefault();e.stopImmediatePropagation();localStorage.setItem(LOCATION_MODE_KEY,'phone');localStorage.removeItem(ZIP_KEY);setLocationStatus('Switching Scout back to phone location…',false);reloadScout();return}localStorage.setItem(LOCATION_MODE_KEY,'phone');localStorage.removeItem(ZIP_KEY)},true)}if(!document.getElementById('h38ZipInput')){var input=document.createElement('input');input.id='h38ZipInput';input.type='text';input.inputMode='numeric';input.autocomplete='postal-code';input.maxLength=5;input.placeholder='ZIP code';input.style.width='104px';input.style.padding='10px';input.style.border='1px solid #cbd7df';input.style.borderRadius='9px';var z=zipState();if(z)input.value=String(z.zip||'');var button=document.createElement('button');button.id='h38ZipBtn';button.type='button';button.textContent='Search ZIP';button.addEventListener('click',function(e){e.preventDefault();searchZip(input,button)});input.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();searchZip(input,button)}});line.appendChild(input);line.appendChild(button)}var z=zipState();if(mode()==='zip'&&z)labelZip(z);return true}
              function startLocationPatch(){wrapNativeLocation();installLocationControls();var z=zipState(),app=document.getElementById('app');if(mode()==='zip'&&z&&app&&!app.classList.contains('hidden')&&!window.__H38ZipBootstrappedV3&&wrapNativeLocation()){window.__H38ZipBootstrappedV3=true;window.H38NativeLocationResult(Number(z.lat),Number(z.lon));labelZip(z)}if(!window.__H38LocationPatchTimerV3)window.__H38LocationPatchTimerV3=setInterval(function(){wrapNativeLocation();installLocationControls()},600)}

              function sharedOpportunity(text){text=String(text||'').trim();if(!text)return;var rows=loadArray(SHARED_KEY),now=Date.now(),u=(text.match(/https?:\\/\\/\\S+/)||[])[0]||'',src=/facebook.com\\/marketplace/i.test(text)?'Facebook Marketplace':/hibid/i.test(text)?'HiBid':/craigslist/i.test(text)?'Craigslist':'Shared listing';if(!rows.some(function(x){return x.text===text&&now-Number(x.atMs||0)<600000})){rows.unshift({id:now,source:src,text:text,url:u,atMs:now,at:new Date(now).toISOString()});try{localStorage.setItem(SHARED_KEY,JSON.stringify(rows.slice(0,60)))}catch(e){}}scan(true,src==='Shared listing'?'all':src)}
              window.H38SharedOpportunity=sharedOpportunity;
              window.__H38OpportunityRefreshV2=function(){installDeck();startLocationPatch();renderFacebookAccess();decorateDeviceStock();decorateStoreFlyers();queueDeviceChecks();labelCandidateCount();var c=facebookCandidates().length;if(lastFacebookCount>=0&&c>lastFacebookCount)scan(true,'Facebook Marketplace');lastFacebookCount=c};
              window.H38AutomaticRefresh=window.__H38OpportunityRefreshV2;
              startLocationPatch();
              function boot(){if(!installDeck()){setTimeout(boot,500);return}lastFacebookCount=facebookCandidates().length;decorateDeviceStock();queueDeviceChecks();scan(false,'all');var list=document.getElementById('storeList');if(list&&!window.__H38StoreObserverV2){window.__H38StoreObserverV2=new MutationObserver(function(){decorateDeviceStock();decorateStoreFlyers();queueDeviceChecks();labelCandidateCount()});window.__H38StoreObserverV2.observe(list,{childList:true})}if(!window.__H38OpportunityTimerV2)window.__H38OpportunityTimerV2=setInterval(function(){scan(false,'all');renderFacebookAccess();decorateDeviceStock();decorateStoreFlyers();queueDeviceChecks();labelCandidateCount()},120000);if(!window.__H38StockUiTimerV2)window.__H38StockUiTimerV2=setInterval(function(){decorateDeviceStock();renderFacebookAccess()},3500)}
              boot();
              var engineMarker='H38_RESALE_OPPORTUNITY_ENGINE_V2',facebookMarker='H38_FACEBOOK_AUTHENTICATED_BROWSER_V1',deviceStockMarker='H38_DEVICE_RETAILER_STOCK_V1',locationMarker='H38_PHONE_OR_ZIP_LOCATION_V3';
            })();
            """;

    private static final class Bridge {
        private final Activity activity;
        private final WebView scout;
        Bridge(Activity activity, WebView scout) { this.activity = activity; this.scout = scout; }

        @JavascriptInterface public void reloadScout() { activity.runOnUiThread(activity::recreate); }
        @JavascriptInterface public boolean notificationAccessEnabled() {
            try { String enabled = Settings.Secure.getString(activity.getContentResolver(), "enabled_notification_listeners"); return enabled != null && enabled.contains(activity.getPackageName()); }
            catch (Exception ignored) { return false; }
        }
        @JavascriptInterface public void openNotificationAccessSettings() { activity.runOnUiThread(() -> { try { activity.startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)); } catch (Exception ignored) {} }); }
        @JavascriptInterface public String facebookNotificationCandidates() { return FacebookMarketplaceNotificationListener.rowsJson(activity); }
        @JavascriptInterface public String facebookBrowserCandidates() { return FacebookMarketplaceActivity.rowsJson(activity); }
        @JavascriptInterface public void openFacebookMarketplace(String termsJson, double lat, double lon, int radius, String postal, String url) {
            activity.runOnUiThread(() -> {
                Intent i = new Intent(activity, FacebookMarketplaceActivity.class);
                i.putExtra(FacebookMarketplaceActivity.EXTRA_TERMS, termsJson == null ? "[]" : termsJson);
                if (Double.isFinite(lat) && Double.isFinite(lon) && !(lat == 0 && lon == 0)) { i.putExtra(FacebookMarketplaceActivity.EXTRA_LAT, lat); i.putExtra(FacebookMarketplaceActivity.EXTRA_LON, lon); }
                i.putExtra(FacebookMarketplaceActivity.EXTRA_RADIUS, radius); i.putExtra(FacebookMarketplaceActivity.EXTRA_POSTAL, postal == null ? "" : postal);
                if (url != null && url.startsWith("https://www.facebook.com/marketplace/")) i.putExtra(FacebookMarketplaceActivity.EXTRA_URL, url);
                activity.startActivity(i);
            });
        }
        @JavascriptInterface public void startDeviceStockCheck(String requestId, String bodyJson) { RetailerDeviceCheckManager.check(activity, scout, requestId, bodyJson); }
        @JavascriptInterface public void openRetailerSession(String bodyJson) {
            activity.runOnUiThread(() -> {
                try {
                    JSONObject b = new JSONObject(bodyJson == null ? "{}" : bodyJson);
                    String retailer = b.optString("retailer", ""), query = first(b.optString("upc", ""), b.optString("sku", ""), b.optString("title", ""), "tools");
                    Intent i = new Intent(activity, RetailerVerificationActivity.class);
                    i.putExtra(RetailerVerificationActivity.EXTRA_RETAILER, retailer); i.putExtra(RetailerVerificationActivity.EXTRA_QUERY, query);
                    i.putExtra(RetailerVerificationActivity.EXTRA_SOURCE_URL, b.optString("source_url", "")); i.putExtra(RetailerVerificationActivity.EXTRA_STORE, b.optString("store_address", b.optString("store_name", "")));
                    activity.startActivity(i);
                } catch (Exception ignored) {}
            });
        }
        private static String first(String... v) { for (String x : v) if (x != null && !x.trim().isEmpty()) return x.trim(); return ""; }
    }

    @Override public boolean onCreate() { Application app = (Application) getContext().getApplicationContext(); app.registerActivityLifecycleCallbacks(this); return true; }
    private static WebView findWebView(View view) { if (view instanceof WebView) return (WebView) view; if (view instanceof ViewGroup) { ViewGroup g=(ViewGroup)view; for(int i=0;i<g.getChildCount();i++){WebView w=findWebView(g.getChildAt(i));if(w!=null)return w;}} return null; }
    private static String sharedText(Intent intent) { if (intent==null||!Intent.ACTION_SEND.equals(intent.getAction()))return null;String type=intent.getType();if(type!=null&&!type.startsWith("text/"))return null;String t=intent.getStringExtra(Intent.EXTRA_TEXT);if(t==null||t.trim().isEmpty())t=intent.getStringExtra(Intent.EXTRA_SUBJECT);return t==null||t.trim().isEmpty()?null:t.trim(); }
    private void inject(Activity activity) {
        if (!(activity instanceof MainActivity)) return;
        WebView webView = findWebView(activity.getWindow().getDecorView()); if (webView == null) return;
        webView.addJavascriptInterface(new Bridge(activity, webView), "AndroidH38Scout");
        String shared = sharedText(activity.getIntent());
        String js = PATCH_JS + (shared == null ? "" : "\nwindow.H38SharedOpportunity&&window.H38SharedOpportunity(" + JSONObject.quote(shared) + ");");
        webView.evaluateJavascript(js, null); if (shared != null) activity.getIntent().setAction(null);
    }
    @Override public void onActivityResumed(Activity activity) { inject(activity); main.postDelayed(() -> inject(activity), 450); main.postDelayed(() -> inject(activity), 1400); main.postDelayed(() -> inject(activity), 3000); }
    @Override public void onActivityCreated(Activity activity, Bundle state) {}
    @Override public void onActivityStarted(Activity activity) {}
    @Override public void onActivityPaused(Activity activity) {}
    @Override public void onActivityStopped(Activity activity) {}
    @Override public void onActivitySaveInstanceState(Activity activity, Bundle state) {}
    @Override public void onActivityDestroyed(Activity activity) {}
    @Override public Cursor query(Uri uri, String[] projection, String selection, String[] selectionArgs, String sortOrder) { return null; }
    @Override public String getType(Uri uri) { return null; }
    @Override public Uri insert(Uri uri, ContentValues values) { return null; }
    @Override public int delete(Uri uri, String selection, String[] selectionArgs) { return 0; }
    @Override public int update(Uri uri, ContentValues values, String[] selectionArgs, ContentValues values2) { return 0; }
    @Override public int update(Uri uri, ContentValues values, String selection, String[] selectionArgs) { return 0; }
}
