import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const OPENAI_API_KEY=Deno.env.get('OPENAI_API_KEY')||'';
const MODEL=Deno.env.get('OPENAI_WALKTHROUGH_TRANSCRIBE_MODEL')||'gpt-4o-mini-transcribe';
const BUCKET='business-office-files';
const MAX_BYTES=24*1024*1024;
type J=Record<string,unknown>;
const clean=(v:unknown,n=12000)=>String(v??'').replace(/Bearer\s+[A-Za-z0-9._-]+/gi,'Bearer [REDACTED]').slice(0,n);
function cors(req:Request){return{'access-control-allow-origin':req.headers.get('origin')||'*','access-control-allow-headers':req.headers.get('access-control-request-headers')||'authorization, apikey, content-type, x-client-info','access-control-allow-methods':'POST, OPTIONS','cache-control':'no-store','content-type':'application/json; charset=utf-8','vary':'Origin, Access-Control-Request-Headers'};}
const reply=(req:Request,status:number,payload:unknown)=>new Response(JSON.stringify(payload),{status,headers:cors(req)});
const bearer=(req:Request)=>(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();
function db(){if(!SUPABASE_URL||!SERVICE_KEY)throw Error('Supabase service configuration is unavailable.');return createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
async function json(res:Response):Promise<J>{try{return await res.json() as J;}catch{return{};}}
async function user(req:Request){const token=bearer(req);if(!token)throw Error('Supabase Auth session is required.');const res=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:SERVICE_KEY},signal:AbortSignal.timeout(15000)});const p=await json(res);if(!res.ok||typeof p.id!=='string'||!p.id)throw Error('Supabase Auth session is invalid or expired.');return{id:p.id as string};}
async function membership(service:ReturnType<typeof createClient>,userId:string,businessId:string){const{data,error}=await service.from('business_memberships').select('role,status').eq('business_id',businessId).eq('auth_user_id',userId).eq('status','active').maybeSingle();if(error)throw error;if(!data)throw Error('The signed-in account is not an active member of this business.');if(!['owner','administrator','staff'].includes(String(data.role)))throw Error('This role cannot dictate Site Visit notes.');}
async function session(service:ReturnType<typeof createClient>,businessId:string,captureSessionId:string,quoteId:string){const{data,error}=await service.from('business_records').select('payload').eq('business_id',businessId).eq('collection','siteCaptureSessions').eq('record_key',captureSessionId).eq('record_status','active').maybeSingle();if(error)throw error;if(!data)throw Error('The Site Visit capture session was not found.');const p=(data.payload&&typeof data.payload==='object'?data.payload:{}) as J;if(clean(p['Quote ID']||p.quoteId,180)!==quoteId)throw Error('The dictated note does not match this Site Visit quote.');}
async function evidence(service:ReturnType<typeof createClient>,businessId:string,captureSessionId:string,quoteId:string,id:string){const{data,error}=await service.from('business_records').select('record_key,payload').eq('business_id',businessId).eq('collection','documents').eq('record_key',id).eq('record_status','active').maybeSingle();if(error)throw error;if(!data)throw Error('The dictated note audio has not reached private storage yet.');const p=(data.payload&&typeof data.payload==='object'?data.payload:{}) as J;const type=clean(p['Evidence Type']||p.evidenceType,100),source=clean(p['Source Type']||p.sourceType,100).toLowerCase(),savedSession=clean(p['Capture Session ID']||p.captureSessionId,180),savedQuote=clean(p['Quote ID']||p.quoteId,180),path=clean(p['Storage Path']||p.storagePath,1200),bucket=clean(p['Storage Bucket']||p.storageBucket||BUCKET,120),name=clean(p['File Name']||p.fileName||'dictated-field-note.webm',220),mime=clean(p['Mime Type']||p.mimeType||'audio/webm',120),size=Number(p['File Size']||p.fileSize||0);if(type!=='Dictated Field Note Audio'||source!=='site visit')throw Error('The requested document is not a dictated Site Visit note.');if(savedSession!==captureSessionId||savedQuote!==quoteId)throw Error('The dictated note audio does not match this Site Visit.');if(!path||!path.startsWith(`${businessId}/`))throw Error('The private dictated note storage path is invalid.');if(size>MAX_BYTES)throw Error('This dictated note is too large to transcribe automatically.');return{path,bucket,name,mime};}
async function transcribe(service:ReturnType<typeof createClient>,e:{path:string,bucket:string,name:string,mime:string}){const d=await service.storage.from(e.bucket).download(e.path);if(d.error||!d.data)throw Error(d.error?.message||'The private dictated note could not be downloaded.');if(d.data.size>MAX_BYTES)throw Error('This dictated note is too large to transcribe automatically.');async function attempt(model:string){const form=new FormData();form.append('file',new File([d.data],e.name,{type:e.mime||d.data.type||'audio/webm'}));form.append('model',model);form.append('response_format','json');form.append('language','en');const res=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{authorization:`Bearer ${OPENAI_API_KEY}`},body:form,signal:AbortSignal.timeout(120000)});const p=await json(res);return{ok:res.ok,text:clean(p.text,12000).trim(),message:clean((p.error as J|undefined)?.message||p.message||`OpenAI transcription returned ${res.status}.`,2000)};}
const first=await attempt(MODEL);if(first.ok)return{transcript:first.text,model:MODEL};if(MODEL!=='whisper-1'&&/corrupt|unsupported|audio file|decode|format/i.test(first.message)){const fallback=await attempt('whisper-1');if(fallback.ok)return{transcript:fallback.text,model:'whisper-1'};throw Error(fallback.message);}throw Error(first.message);}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return reply(req,200,{status:'PASS'});if(req.method!=='POST')return reply(req,405,{status:'FAIL',message:'POST is required.'});const service=db();let businessId='',captureSessionId='',quoteId='',audioAttachmentId='',userId='';try{const body=await req.json() as J;businessId=clean(body.businessId,180);captureSessionId=clean(body.captureSessionId,180);quoteId=clean(body.quoteId,180);audioAttachmentId=clean(body.audioAttachmentId,180);if(!businessId||!captureSessionId||!quoteId||!audioAttachmentId)throw Error('Business, Site Visit, quote, and dictated note audio are required.');const u=await user(req);userId=u.id;await membership(service,userId,businessId);await session(service,businessId,captureSessionId,quoteId);const e=await evidence(service,businessId,captureSessionId,quoteId,audioAttachmentId);const result=await transcribe(service,e);if(!result.transcript)throw Error('No spoken note was detected in that recording.');await service.from('business_proof_log').insert({business_id:businessId,actor_user_id:userId,action_type:'SITE_DICTATED_FIELD_NOTE_TRANSCRIBED',entity_type:'Site Capture Session',entity_id:null,result:'PASS',details:{captureSessionId,quoteId,audioAttachmentId,transcriptionModel:result.model,ownerReviewRequired:true,automaticApproval:false,automaticCustomerSending:false,automaticFinancialAction:false},external_action_occurred:false});return reply(req,200,{status:'PASS',transcript:result.transcript,cleanNote:result.transcript,transcriptionModel:result.model,ownerReviewRequired:true,automaticApproval:false,automaticCustomerSending:false});}catch(error){try{if(businessId)await service.from('business_error_log').insert({business_id:businessId,actor_user_id:userId||null,source:'supabase/functions/h38-field-note-transcription',error_code:'SITE_DICTATED_FIELD_NOTE_TRANSCRIPTION_FAILED',message:clean(error instanceof Error?error.message:error,4000),severity:'error',status:'open',context:{captureSessionId,quoteId,audioAttachmentId,externalActionOccurred:false}});}catch{}return reply(req,400,{status:'FAIL',message:clean(error instanceof Error?error.message:error,4000)});}});
