import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const UA="Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36 H38ResellerScout/3.0.8";
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store",vary:"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function dec(v:any){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&nbsp;|&#160;/gi," ").replace(/&ndash;/gi,"–").replace(/&mdash;/gi,"—")}
function strip(v:any){return dec(v).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function abs(h:string,b:string){try{return new URL(dec(h),b).toString()}catch{return""}}
function hav(a:number,b:number,c:number,d:number){const R=3958.7613,q=Math.PI/180,x=(c-a)*q,y=(d-b)*q,z=Math.sin(x/2)**2+Math.cos(a*q)*Math.cos(c*q)*Math.sin(y/2)**2;return 2*R*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function meta(html:string,key:string){const e=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),a=html.match(new RegExp(`<meta\\b[^>]*(?:property|name|itemprop)=["']${e}["'][^>]*content=["']([^"']+)["']`,"i"))||html.match(new RegExp(`<meta\\b[^>]*content=["']([^"']+)["'][^>]*(?:property|name|itemprop)=["']${e}["']`,"i"));return a?dec(a[1]):""}
async function get(url:string,timeout=9000){const c=new AbortController(),to=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{"user-agent":UA,accept:"text/html,application/xhtml+xml,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:c.signal}),html=await r.text().catch(()=>"");if(!r.ok)throw Error(`HTTP ${r.status}`);return{url:r.url,html}}finally{clearTimeout(to)}}
function saleType(v:string){const s=v.toLowerCase();if(/estate/.test(s))return"ESTATE SALE";if(/moving/.test(s))return"MOVING SALE";if(/rummage/.test(s))return"RUMMAGE SALE";if(/yard/.test(s))return"YARD SALE";return"GARAGE SALE"}
function cleanTitle(v:any){return strip(v).replace(/\s*[|–-]\s*craigslist.*$/i,"").trim().slice(0,220)}
function craigslistSeeds(html:string,base:string){const out:any[]=[],seen=new Set<string>();for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){if(out.length>=24)break;const url=abs(m[1]||"",base),title=cleanTitle(m[2]||"");if(!url||seen.has(url)||title.length<4||(!/\.html(?:$|\?)/i.test(url)&&!/\/d\//i.test(url)))continue;seen.add(url);out.push({source:"Craigslist",source_type:"public_garage_moving_category",title,event_type:saleType(title),url,location_verified:false,freshness_unproven:true,source_search_bound:true})}return out}
async function craigslistDetail(seed:any,lat:number,lon:number,radius:number){try{const p=await get(seed.url,7000),h=p.html,plain=strip(h),title=cleanTitle(meta(h,"og:title")||h.match(/id=["']titletextonly["'][^>]*>([\s\S]*?)<\/span>/i)?.[1]||seed.title),image=meta(h,"og:image"),la=Number(meta(h,"geo.position").split(/[;,]/)[0]||h.match(/latitude[^0-9-]*(-?\d+(?:\.\d+)?)/i)?.[1]),lo=Number(meta(h,"geo.position").split(/[;,]/)[1]||h.match(/longitude[^0-9-]*(-?\d+(?:\.\d+)?)/i)?.[1]),location=strip(h.match(/class=["'][^"']*(?:mapaddress|postingtitletext)[^"']*["'][^>]*>([\s\S]{0,700}?)<\//i)?.[1]||"").replace(/^\(|\)$/g,""),time=h.match(/<time\b[^>]*datetime=["']([^"']+)["'][^>]*>/i)?.[1]||"",d=Number.isFinite(la)&&Number.isFinite(lo)&&Number.isFinite(lat)&&Number.isFinite(lon)?hav(lat,lon,la,lo):null;if(d!=null&&d>radius)return null;return{...seed,title,event_type:saleType(`${title} ${plain.slice(0,500)}`),url:p.url,image_url:image,location_label:location,event_time:time,distance_miles:d==null?null:Number(d.toFixed(1)),location_verified:d!=null,freshness_unproven:!time,detail_verified:true}}catch{return seed}}
const STATE:any={alabama:"AL",alaska:"AK",arizona:"AZ",arkansas:"AR",california:"CA",colorado:"CO",connecticut:"CT",delaware:"DE",florida:"FL",georgia:"GA",hawaii:"HI",idaho:"ID",illinois:"IL",indiana:"IN",iowa:"IA",kansas:"KS",kentucky:"KY",louisiana:"LA",maine:"ME",maryland:"MD",massachusetts:"MA",michigan:"MI",minnesota:"MN",mississippi:"MS",missouri:"MO",montana:"MT",nebraska:"NE",nevada:"NV","new hampshire":"NH","new jersey":"NJ","new mexico":"NM","new york":"NY","north carolina":"NC","north dakota":"ND",ohio:"OH",oklahoma:"OK",oregon:"OR",pennsylvania:"PA","rhode island":"RI","south carolina":"SC","south dakota":"SD",tennessee:"TN",texas:"TX",utah:"UT",vermont:"VT",virginia:"VA",washington:"WA","west virginia":"WV",wisconsin:"WI",wyoming:"WY"};
function area(label:string,postal:string){const raw=strip(label).replace(new RegExp(`,?\\s*${postal}.*$`),"").trim(),parts=raw.split(',').map(x=>x.trim()).filter(Boolean),city=parts[0]||"",region=parts[1]||"",st=/^[A-Z]{2}$/i.test(region)?region.toUpperCase():STATE[region.toLowerCase()]||"";return{city,st}}
function estateSeeds(html:string,base:string,st:string,postal:string){const out:any[]=[],seen=new Set<string>();const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;for(const m of html.matchAll(re)){if(out.length>=20)break;const url=abs(m[1]||"",base),title=cleanTitle(m[2]||"");if(!url||seen.has(url)||title.length<5||!url.includes("estatesales.net")||!/\/\d{5}(?:\/|$)/.test(url))continue;if(!/sale|estate|moving|liquidat|vintage|antique|collect|tool|garage|house|contents|downsizing/i.test(title))continue;seen.add(url);out.push({source:"EstateSales.NET",source_type:"public_estate_sale_index",title,event_type:saleType(title),url,location_label:`${st} ${postal}`.trim(),location_verified:false,freshness_unproven:false,source_search_bound:true})}return out}
function dedupe(rows:any[]){const m=new Map<string,any>();for(const r of rows){const k=String(r.url||`${r.source}|${r.title}`).replace(/[?#].*$/,'');if(k&&!m.has(k))m.set(k,r)}return[...m.values()]}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required"});try{const b=await req.json().catch(()=>({})),lat=Number(b.lat),lon=Number(b.lon),radius=[25,50,100,150].includes(Number(b.radiusMiles))?Number(b.radiusMiles):50,postal=String(b.postal||"").match(/\d{5}/)?.[0]||"",label=String(b.location_label||b.locationLabel||""),rows:any[]=[],health:any={Craigslist:{status:"unavailable",count:0},"EstateSales.NET":{status:"unavailable",count:0}};
    if(Number.isFinite(lat)&&Number.isFinite(lon)){try{const u=`https://www.craigslist.org/search/gms?sort=date&lat=${lat}&lon=${lon}&search_distance=${radius}`,p=await get(u),seeds=craigslistSeeds(p.html,p.url),details=await Promise.all(seeds.slice(0,14).map(x=>craigslistDetail(x,lat,lon,radius)));const got=details.filter(Boolean);rows.push(...got);health.Craigslist={status:got.length?"live":"empty",count:got.length,route:p.url}}catch(e){health.Craigslist={status:"unavailable",count:0,warning:String(e)}}}
    const a=area(label,postal);if(a.city&&a.st&&postal){try{const slug=a.city.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,''),u=`https://www.estatesales.net/${a.st}/${slug}/${postal}`,p=await get(u),got=estateSeeds(p.html,p.url,a.st,postal);rows.push(...got);health["EstateSales.NET"]={status:got.length?"live":"empty",count:got.length,route:p.url}}catch(e){health["EstateSales.NET"]={status:"unavailable",count:0,warning:String(e)}}}
    const out=dedupe(rows).sort((x,y)=>{const av=x.location_verified===true?0:1,bv=y.location_verified===true?0:1;if(av!==bv)return av-bv;const ad=Number(x.distance_miles),bd=Number(y.distance_miles);if(Number.isFinite(ad)&&Number.isFinite(bd))return ad-bd;return 0}).slice(0,40);return json(req,200,{status:out.length?"PASS":"PARTIAL",engine:"garage_sales_v308",results:out,source_health:health,truth:"Sale-level discovery only. Scout does not assign resale value or profit until actual items are identified and comped."})}catch(e){return json(req,500,{error:e instanceof Error?e.message:String(e)})}});