import assert from 'node:assert/strict';
import fs from 'node:fs';
const physical=fs.readFileSync(new URL('./src/main/assets/reseller/v212-physical.js',import.meta.url),'utf8');
const wide=fs.readFileSync(new URL('./src/main/assets/reseller/v211-wide.js',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('./src/main/assets/reseller/index.html',import.meta.url),'utf8');
const main=fs.readFileSync(new URL('./src/main/java/com/highway38/resellerscout/MainActivity.java',import.meta.url),'utf8');
const acceptance=fs.readFileSync(new URL('./SCOUT_BUILD_ACCEPTANCE.md',import.meta.url),'utf8');
assert.match(physical,/H38_SCOUT_V215_NATIVE_HUNT=true/);
assert.match(physical,/H38_SCOUT_V216_HUNT_RUNTIME=true/);
assert.match(physical,/function strictImageRetailer\(v\)/);
assert.match(wide,/strictImageRetailer\(r\.retailer\)/,'wide image-recovery layer must exercise the dependency caught by the phone recording');
assert.ok(index.indexOf('v211-wide.js')<index.indexOf('v212-physical.js')&&index.indexOf('v212-physical.js')<index.indexOf('v200-app.js'),'runtime helper must be defined after wide declarations but before app bootstrap can render Hunt');
assert.match(physical,/<details class="retailer-group" data-hunt-details=/);
assert.match(physical,/<summary class="retailer-group-head">/);
assert.match(physical,/summary\.click\(\)/);
assert.match(physical,/Native Penny Hunt expansion/);
assert.doesNotMatch(physical,/h38BindStableHuntTouch/);
const disclosureMarkup=physical.match(/return `<details class="retailer-group"[\s\S]*?<\/details>`;/)?.[0]||'';
assert.ok(disclosureMarkup,'native disclosure template must be present');
assert.doesNotMatch(disclosureMarkup,/data-hunt-group/,'native retailer markup must not expose the legacy JS-toggle selector');
assert.match(disclosureMarkup,/data-hunt-details=/,'native retailer markup must use the native disclosure identity');
assert.match(main,/"v212-physical\.js"/);
assert.match(acceptance,/TAP EACH visible retailer header/);
assert.match(acceptance,/actual Android phone behavior is final acceptance authority/i);
console.log('PASS v2.1.6 Penny Hunt runtime + native disclosure contract');
