import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const here=path.dirname(fileURLToPath(import.meta.url));
const p=path.join(here,'src/main/assets/reseller');
const java=path.join(here,'src/main/java/com/highway38/resellerscout');
const v240=fs.readFileSync(path.join(p,'v240-data.js'),'utf8');
const v264=fs.readFileSync(path.join(p,'v264-wide-repair.js'),'utf8');
const v265=fs.readFileSync(path.join(p,'v265-facebook-acquisition-repair.js'),'utf8');
const v300=fs.readFileSync(path.join(p,'v266-actionable-intake.js'),'utf8');
const main=fs.readFileSync(path.join(java,'MainActivity.java'),'utf8');
const sourceInbox=fs.readFileSync(path.join(java,'FacebookMarketplaceSourceInbox.java'),'utf8');
const manifest=fs.readFileSync(path.join(here,'src/main/AndroidManifest.xml'),'utf8');
const gradle=fs.readFileSync(path.join(here,'build.gradle'),'utf8');
const rules=fs.readFileSync(path.join(here,'V3-RUNTIME-RULES.md'),'utf8');

assert.match(v264,/H38_SCOUT_LEGACY_V264_DISABLED=true/);
assert.match(v265,/H38_SCOUT_LEGACY_V265_DISABLED=true/);
assert.doesNotMatch(v264,/renderDiscover\s*=|loadHunt\s*=|facebookSnapshot\s*=/);
assert.match(v265,/H38_SCOUT_V312_PHYSICAL_REPAIR=true/);
assert.match(v265,/window\.runDiscover=repairedRunDiscover/);
assert.match(v265,/window\.loadHunt=repairedLoadHunt/);
assert.match(v265,/reseller-auto-leads-v065/);
assert.doesNotMatch(v265,/facebookSnapshot\s*=/);
assert.match(v300,/H38_SCOUT_V300_SINGLE_OWNER_RUNTIME=true/);
assert.match(v300,/H38_SCOUT_V305_PUBLIC_BACKEND_RECOVERY=true/);
assert.match(v300,/facebookSnapshot=function/);
assert.match(v300,/facebookPublicCandidates/);
assert.match(v300,/reseller-facebook-public-v240/);
assert.match(v300,/facebookRequestSeq/);
assert.match(v300,/currentKey=txt\(state\.v300\.facebookQueryKey\)/);
assert.match(v300,/if\(state\.facebookPassPending\)\{if\(!\(requested\.length&&queryKey&&queryKey!==currentKey\)\)return true;state\.facebookPassPending=false;state\.facebookRanking=false\}/);
assert.match(v300,/mergeFacebookRows\(\[\.\.\.priorCaptured,\.\.\.nextCaptured,\.\.\.state\.v240\.facebookRows\]\)/);
assert.match(v300,/request!==facebookRequestSeq/);
assert.match(v300,/normalizeFacebookTerms\(explicitTerms\)/);
assert.match(v300,/replaceActive=!!requested\.length&&queryKey!==currentKey/);
assert.match(v300,/priorVerified=replaceActive\?\[\]:/);
assert.match(v300,/priorCaptured=replaceActive\?\[\]:/);
assert.match(v300,/state\.v300\.facebookQueryKey=queryKey/);
assert.match(v300,/if\(replaceActive\)\{state\.v240=state\.v240\|\|\{\};state\.v240\.facebookRows=\[\];state\.v300\.facebookPublicCandidates=\[\]\}/);
assert.match(v300,/const typed=txt\(\$\('discoverSearch'\)\?\.value\?\?state\.discover\.query\);state\.discover\.query=typed;write\(H38_KEYS\.discover,typed\);const publicPass=startFacebook\(false,typed\?\[typed\]:null\);const basePass=runDiscoverBase\(\)/);
const discoverSync=v300.indexOf("const typed=txt($('discoverSearch')?.value??state.discover.query)");
const facebookStart=v300.indexOf('const publicPass=startFacebook(false,typed?[typed]:null)');
assert.ok(discoverSync>=0&&facebookStart>discoverSync,'Discover must copy the typed item into state before Facebook acquisition begins');
assert.match(v300,/Searching public Facebook Marketplace\$\{termText\}/);
assert.match(v300,/activeTerm\?`\$\{esc\(activeTerm\)\} · `/);
assert.match(v300,/No Facebook sign-in is used/i);
assert.match(v300,/does not open Facebook automatically/i);
assert.match(v300,/legacySec\.remove\(\)/);
assert.doesNotMatch(v300,/n\.openFacebookMarketplace\(/);
assert.doesNotMatch(v300,/Repair Facebook session|Sign in once|Complete checkpoint/);
assert.match(v300,/LOCATION NEEDS PROOF/);
assert.match(v300,/FRESHNESS UNPROVEN/);
assert.match(v300,/H38V300ImageFallback/);
assert.match(v300,/weirdHuntRow/);
assert.match(v300,/1cent/);
assert.match(v300,/Promise\.allSettled\(\[fn\('reseller-auto-leads-v064'/);
assert.match(v300,/fn\('reseller-auto-leads-v058'/);
assert.match(v300,/physical UPC\/register scan remains final local penny truth/i);

assert.match(v240,/H38_SCOUT_V306_SINGLE_FACEBOOK_OWNER=true/);
assert.match(v240,/PUBLIC_EVIDENCE/);
assert.match(v240,/public remodel indicator/);
assert.match(v240,/selected-store price\/stock not yet proven/);
assert.match(v240,/\['PUBLIC_EVIDENCE','CONFIG_REQUIRED','UNAVAILABLE','LIVE_PARTIAL','PARTIAL'\]/);
assert.match(v240,/provider_status:bound\?'DEVICE_LIVE':'PUBLIC_EVIDENCE'/);
assert.doesNotMatch(v240,/publicPromise=loadFacebookPublicV240/);
assert.doesNotMatch(v240,/Run signed-in Facebook pass|signed-in device pass|cookies are now explicitly persisted/i);
assert.match(v240,/runDiscover=async function\(\)\{if\(state\.discover\.running\)return;if\(!requireLocation\(\)\)return;await baseRunDiscoverV240\(\);await H38V240LoadRetailIntel\(false\);renderDiscover\(\)\}/);

assert.match(manifest,/android\.intent\.action\.SEND/);
assert.match(manifest,/android:mimeType="text\/\*"/);
assert.match(main,/FacebookMarketplaceSourceInbox\.captureSharedText/);
assert.match(main,/FacebookMarketplaceSourceInbox\.mergedRowsJson/);
assert.match(main,/facebookNotificationCandidates/);
assert.match(main,/openNotificationAccessSettings/);
assert.ok(sourceInbox.includes('facebook\\\\.com/marketplace/item/(\\\\d{6,})'), 'direct Facebook Marketplace item URL matcher must require numeric listing id');
assert.match(sourceInbox,/facebook\\\\\.com\/share/);
assert.match(sourceInbox,/marketplace_url_proven/);
assert.match(sourceInbox,/Facebook shared lead/);
assert.match(sourceInbox,/capture_method", "ANDROID_SHARE"/);
assert.match(sourceInbox,/capture_method", "FACEBOOK_NOTIFICATION"/);
assert.match(sourceInbox,/location_verified", false/);
assert.match(sourceInbox,/location_status", "LOCATION_UNPROVEN"/);
assert.match(sourceInbox,/freshness_unproven", true/);
assert.doesNotMatch(sourceInbox,/c_user|\bxs\b|checkpoint|CookieManager/);

assert.match(gradle,/versionCode 312/);
assert.match(gradle,/versionName '3\.0\.12'/);
assert.match(rules,/Single-owner runtime rule/);
assert.match(rules,/Physical Android phone behavior remains final acceptance/);
console.log('PASS v3.0.12 explicit physical repair ownership + typed Discover query + source isolation contracts');
