import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const here=path.dirname(fileURLToPath(import.meta.url));
const p=path.join(here,'src/main/assets/reseller');
const java=path.join(here,'src/main/java/com/highway38/resellerscout');
const v264=fs.readFileSync(path.join(p,'v264-wide-repair.js'),'utf8');
const v265=fs.readFileSync(path.join(p,'v265-facebook-acquisition-repair.js'),'utf8');
const v300=fs.readFileSync(path.join(p,'v266-actionable-intake.js'),'utf8');
const main=fs.readFileSync(path.join(java,'MainActivity.java'),'utf8');
const sourceInbox=fs.readFileSync(path.join(java,'FacebookMarketplaceSourceInbox.java'),'utf8');
const manifest=fs.readFileSync(path.join(here,'src/main/AndroidManifest.xml'),'utf8');
const gradle=fs.readFileSync(path.join(here,'build.gradle'),'utf8');
const rules=fs.readFileSync(path.join(here,'V3-RUNTIME-RULES.md'),'utf8');

assert.match(v264,/H38_SCOUT_LEGACY_V264_DISABLED=true/);
assert.match(v265,/H38_SCOUT_LEGACY_V265_DISABLED=true/);
assert.doesNotMatch(v264,/renderDiscover\s*=|loadHunt\s*=|facebookSnapshot\s*=/);
assert.doesNotMatch(v265,/renderDiscover\s*=|loadHunt\s*=|facebookSnapshot\s*=/);
assert.match(v300,/H38_SCOUT_V300_SINGLE_OWNER_RUNTIME=true/);
assert.match(v300,/H38_SCOUT_V305_PUBLIC_BACKEND_RECOVERY=true/);
assert.match(v300,/facebookSnapshot=function/);
assert.match(v300,/facebookPublicCandidates/);
assert.match(v300,/reseller-facebook-public-v240/);
assert.match(v300,/No Facebook sign-in is used/i);
assert.match(v300,/no longer opens Facebook automatically/i);
assert.doesNotMatch(v300,/n\.openFacebookMarketplace\(/);
assert.doesNotMatch(v300,/Repair Facebook session|Sign in once|Complete checkpoint/);
assert.match(v300,/LOCATION NEEDS PROOF/);
assert.match(v300,/FRESHNESS UNPROVEN/);
assert.match(v300,/H38V300ImageFallback/);
assert.match(v300,/weirdHuntRow/);
assert.match(v300,/1cent/);
assert.match(v300,/Promise\.allSettled\(\[fn\('reseller-auto-leads-v064'/);
assert.match(v300,/fn\('reseller-auto-leads-v058'/);
assert.match(v300,/physical UPC\/register scan remains final local penny truth/i);

assert.match(manifest,/android\.intent\.action\.SEND/);
assert.match(manifest,/android:mimeType="text\/\*"/);
assert.match(main,/FacebookMarketplaceSourceInbox\.captureSharedText/);
assert.match(main,/FacebookMarketplaceSourceInbox\.mergedRowsJson/);
assert.match(main,/facebookNotificationCandidates/);
assert.match(main,/openNotificationAccessSettings/);
assert.ok(sourceInbox.includes('facebook\\\\.com/marketplace/item/(\\\\d{6,})'), 'direct Facebook Marketplace item URL matcher must require numeric listing id');
assert.match(sourceInbox,/facebook\\\\\.com\/share/);
assert.match(sourceInbox,/marketplace_url_proven/);
assert.match(sourceInbox,/Facebook shared lead/);
assert.match(sourceInbox,/capture_method", "ANDROID_SHARE"/);
assert.match(sourceInbox,/capture_method", "FACEBOOK_NOTIFICATION"/);
assert.match(sourceInbox,/location_verified", false/);
assert.match(sourceInbox,/location_status", "LOCATION_UNPROVEN"/);
assert.match(sourceInbox,/freshness_unproven", true/);
assert.doesNotMatch(sourceInbox,/c_user|\bxs\b|checkpoint|CookieManager/);

assert.match(gradle,/versionCode 306/);
assert.match(gradle,/versionName '3\.0\.6'/);
assert.match(rules,/Single-owner runtime rule/);
assert.match(rules,/Physical Android phone behavior remains final acceptance/);
console.log('PASS v3.0.6 source-specific Facebook share + notification intake contracts');
