import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const here=path.dirname(fileURLToPath(import.meta.url));
const p=path.join(here,'src/main/assets/reseller');
const app=fs.readFileSync(path.join(p,'v264-wide-repair.js'),'utf8');
const backend=fs.readFileSync(path.join(here,'../../../../supabase/functions/reseller-garage-sales-v308/index.ts'),'utf8');
const gradle=fs.readFileSync(path.join(here,'build.gradle'),'utf8');

assert.match(app,/H38_SCOUT_LEGACY_V264_DISABLED=true/);
assert.match(app,/H38_SCOUT_V308_GARAGE_POLISH=true/);
assert.doesNotMatch(app,/renderDiscover\s*=|loadHunt\s*=|facebookSnapshot\s*=/);
for(const term of ['garage sale','yard sale','rummage sale','moving sale','estate sale'])assert.ok(app.includes(`'${term}'`),`missing ${term}`);
assert.match(app,/reseller-facebook-public-v240/);
assert.match(app,/reseller-garage-sales-v308/);
assert.match(app,/Garage & estate sales/);
assert.match(app,/LOCATION NEEDS PROOF/);
assert.match(app,/FRESHNESS UNPROVEN/);
assert.match(app,/Nearby \/ location-proven/);
assert.match(app,/Needs location or freshness proof/);
assert.match(app,/Sale-level lead only/);
assert.match(app,/profit is not rated until actual items are identified and sold comps support a value/i);
assert.match(app,/Profit not rated — sold-comp evidence is still needed before this is a buy/);
assert.match(app,/Open sale/);
assert.match(app,/Scout items/);
assert.match(app,/window\['render'\+'Discover'\]/);
assert.match(app,/window\['run'\+'Discover'\]/);

assert.match(backend,/\/search\/gms/);
assert.match(backend,/estatesales\.net/i);
assert.match(backend,/Craigslist/);
assert.match(backend,/EstateSales\.NET/);
assert.match(backend,/location_verified:false/);
assert.match(backend,/Sale-level discovery only/);
assert.match(backend,/does not assign resale value or profit until actual items are identified and comped/i);
assert.doesNotMatch(backend,/\bnet_profit\b|\bresale_estimate\b|\broi_pct\b/);
assert.match(gradle,/versionCode 308/);
assert.match(gradle,/versionName '3\.0\.8'/);
console.log('PASS v3.0.8 garage-sale source isolation, truth labels, and mobile polish contracts');