plugins {
    id 'com.android.application'
}

android {
    namespace 'com.highway38.sitescanner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.highway38.sitescanner'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.test'
            versionNameSuffix '-test'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'com.google.ar:core:1.54.0'
}
