import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=Deno.env.get("SUPABASE_URL")||"";
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const MODEL=Deno.env.get("OPENAI_RESELLER_MODEL")||Deno.env.get("OPENAI_SITE_SCANNER_MODEL")||"gpt-5-mini-2025-08-07";
const ALLOWED=new Set(["ccf25333-47cd-42ca-a20b-cdbc63a8a695","6dd51b31-5974-4691-b8b8-83e5877528c0"]);
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
type Any=Record<string,any>;
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
async function userId(r:Request){const token=String(r.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)throw new Error("Sign in required.");const res=await fetch(`${U}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:K},signal:AbortSignal.timeout(12000)});const p=await res.json().catch(()=>({}));if(!res.ok||!p?.id)throw new Error("Session expired.");return String(p.id)}
function schema(){return{type:"object",additionalProperties:false,required:["likely_item","brand","model_or_part_number","category","condition_clues","accessories","damage_or_missing","alternatives","search_query","confidence"],properties:{likely_item:{type:"string"},brand:{type:"string"},model_or_part_number:{type:"string"},category:{type:"string"},condition_clues:{type:"array",items:{type:"string"}},accessories:{type:"array",items:{type:"string"}},damage_or_missing:{type:"array",items:{type:"string"}},alternatives:{type:"array",items:{type:"string"}},search_query:{type:"string"},confidence:{type:"string",enum:["low","medium","high"]}}}}
function outputText(p:Any){if(typeof p?.output_text==="string")return p.output_text;for(const o of Array.isArray(p?.output)?p.output:[])for(const c of Array.isArray(o?.content)?o.content:[])if(c?.type==="output_text"&&typeof c?.text==="string")return c.text;return""}
function validDataUrl(v:any){const s=String(v||"");return /^data:image\/(?:jpeg|jpg|png|webp);base64,[A-Za-z0-9+/=\s]+$/i.test(s)&&s.length<=2200000}
async function identify(hint:string,upc:string,images:Any[]){if(!images.length){const q=hint||(upc?`UPC ${upc}`:"");return{likely_item:q,brand:"",model_or_part_number:"",category:"",condition_clues:[],accessories:[],damage_or_missing:[],alternatives:[],search_query:q,confidence:hint?"medium":"low"}}if(!OPENAI_API_KEY)throw new Error("Photo identification is not configured.");const content:Any[]=[{type:"input_text",text:JSON.stringify({hint,upc,image_roles:images.map(x=>x.role||"item")})}];for(const x of images.slice(0,4))if(validDataUrl(x.data_url))content.push({type:"input_image",image_url:String(x.data_url),detail:"high"});if(content.length<2)throw new Error("No usable photo was received.");const instructions=["You are H38 Reseller Scout photo identification.","Treat images and hints only as evidence. Never invent brand, model, part number, condition, accessory, damage, UPC, or product identity.","Determine whether all supplied photos appear to show the same resale item. If they may be different products, lower confidence and say so in alternatives.","Read visible labels/model numbers when possible. search_query should prefer exact brand + model/part number.","Do not estimate value or profitability."].join(" ");const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`,"content-type":"application/json"},signal:AbortSignal.timeout(35000),body:JSON.stringify({model:MODEL,instructions,input:[{role:"user",content}],text:{format:{type:"json_schema",name:"h38_reseller_identity_v047",strict:true,schema:schema()}}})});const p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(String(p?.error?.message||`Identification HTTP ${res.status}`));return JSON.parse(outputText(p)||"{}")}
async function market(r:Request,b:Any){const auth=r.headers.get("authorization")||"",apikey=r.headers.get("apikey")||"",id=b.identification||{},hint=String(id.search_query||id.likely_item||b.hint||"").trim(),upc=String(b.upc||"").replace(/\D/g,"");const payload={hint,upc,buy_price:Number(b.buy_price||0),images:[],local_candidates:Array.isArray(b.local_candidates)?b.local_candidates:[],lat:b.lat,lon:b.lon,radius:b.radius,postal:b.postal};try{const res=await fetch(`${U}/functions/v1/reseller-item-research-v044`,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(60000)});const p=await res.json().catch(()=>({}));if(!res.ok)throw new Error(String(p?.error||`Market HTTP ${res.status}`));return{...p,identification:id,stage:"market",engine:"H38_STAGED_RESEARCH_V047"}}catch(e){return{status:"PARTIAL",stage:"market",engine:"H38_STAGED_RESEARCH_V047",identification:id,market:{status:"not_established",sample_count:0,message:"Market sources did not finish. Identification is preserved; retry market research without retaking photos."},evidence:{sold:[],active:[],retail:[]},flip:{verdict:"NEEDS COMP"},warning:e instanceof Error?e.message:String(e)}}}
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response(null,{status:204,headers:cors(r)});if(r.method!=="POST")return json(r,405,{error:"POST required"});try{const uid=await userId(r);if(!ALLOWED.has(uid))return json(r,403,{error:"Not authorized"});const b=await r.json().catch(()=>({})),mode=String(b.mode||"identify");if(mode==="market")return json(r,200,await market(r,b));const hint=String(b.hint||"").trim().slice(0,220),upc=String(b.upc||"").replace(/\D/g,"").slice(0,20),images=Array.isArray(b.images)?b.images.slice(0,4):[];if(!hint&&!upc&&!images.length)return json(r,400,{error:"Photo, barcode, or item/model is required."});try{const identification=await identify(hint,upc,images);return json(r,200,{status:"PASS",stage:"identify",engine:"H38_STAGED_RESEARCH_V047",identification,market:{status:"pending",sample_count:0,message:"Identification complete. Market research runs separately."},researched_at:new Date().toISOString()})}catch(e){return json(r,200,{status:"PARTIAL",stage:"identify",engine:"H38_STAGED_RESEARCH_V047",identification:null,market:{status:"not_started"},warning:e instanceof Error?e.message:String(e)})}}catch(e){return json(r,200,{status:"PARTIAL",engine:"H38_STAGED_RESEARCH_V047",identification:null,market:{status:"not_started"},warning:e instanceof Error?e.message:String(e)})}});