(()=>{
'use strict';
const config=window.NL_CUSTOMER_PORTAL_CONFIG||{};
const state={client:null,session:null,account:null,jobs:[],quotes:[],invoices:[],payments:[],files:[],activeQuote:null,epoch:0};
const $=id=>document.getElementById(id);
const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0));
const date=value=>value?new Intl.DateTimeFormat('en-US',{dateStyle:'medium'}).format(new Date(value+'T00:00:00')):'Not posted';
const dateTime=value=>value?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Not posted';
const withTimeout=(promise,ms,message)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(message)),ms))]);
function validConfig(){return config.enabled===true&&/^[0-9a-f-]{36}$/i.test(String(config.businessId||''))&&config.businessKey==='northern-lakes'&&/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(String(config.supabaseUrl||''))&&/^sb_publishable_/.test(String(config.publishableKey||''))&&!/service_role/i.test(String(config.publishableKey||''));}
function notice(message,kind=''){const node=$('portalNotice');node.className='portal-notice '+kind;node.innerHTML=message;}
function view(name){$('portalHold').hidden=name!=='hold';$('portalLogin').hidden=name!=='login';$('portalApp').hidden=name!=='app';$('signOutButton').hidden=name!=='app';}
function friendlyError(error){return String(error&&error.message?error.message:error||'Something went wrong.').replace(/\bSupabase\b/gi,'secure service').replace(/row level security/gi,'account access controls').replace(/\btenant\b/gi,'business');}
function safeError(error){console.error(error);notice('<strong>Secure portal notice:</strong> '+esc(friendlyError(error)),'bad');}
function redirectUrl(){const current=location.origin+location.pathname;return (config.allowedRedirectOrigins||[]).includes(location.origin)?current:config.canonicalRedirectUrl;}
function initClient(){if(!validConfig()){view('hold');notice('<strong>Portal held closed.</strong> Secure configuration validation failed. No customer data is exposed.','bad');return null;}if(!window.supabase||typeof window.supabase.createClient!=='function')throw new Error('Secure sign-in service did not load.');state.client=window.supabase.createClient(config.supabaseUrl,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'},global:{headers:{'x-client-info':'northern-lakes-customer-portal'}}});return state.client;}
async function signIn(event){event.preventDefault();const email=String($('portalEmail').value||'').trim().toLowerCase();const password=String($('portalPassword').value||'');if(!email)throw new Error('Enter the email connected to your customer account.');if(!password)throw new Error('Enter your password or request a secure email link.');notice('Signing in securely…');const {data,error}=await withTimeout(state.client.auth.signInWithPassword({email,password}),15000,'Secure sign-in took too long. Please try again.');if(error)throw error;$('portalPassword').value='';await applySession(data.session);}
async function magicLink(){const email=String($('portalEmail').value||'').trim().toLowerCase();if(!email)throw new Error('Enter the email connected to your customer account.');const {error}=await withTimeout(state.client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectUrl(),shouldCreateUser:false}}),15000,'The secure email request took too long. Please try again.');if(error)throw error;notice('<strong>Check your email.</strong> A secure sign-in link was requested. For privacy, this page does not confirm whether an address is registered.','good');}
function clearCustomer(){state.epoch++;Object.assign(state,{session:null,account:null,jobs:[],quotes:[],invoices:[],payments:[],files:[],activeQuote:null});$('quoteDialog').close();view('login');}
async function signOut(){clearCustomer();const {error}=await withTimeout(state.client.auth.signOut(),10000,'Sign-out took too long. Refresh this page before signing in again.');if(error)throw error;notice('Signed out.','good');}
async function loadAccount(epoch){const userId=state.session?.user?.id;if(!userId)throw new Error('A signed-in user is required.');const request=state.client.from('customer_accounts').select('id,business_id,tenant_key,customer_code,display_name,email,status,portal_enabled').eq('auth_user_id',userId).eq('business_id',config.businessId).eq('tenant_key',config.businessKey).eq('status','active').eq('portal_enabled',true).maybeSingle();const {data,error}=await withTimeout(request,15000,'Customer account access took too long. Please refresh and try again.');if(epoch!==state.epoch)return false;if(error)throw error;if(!data)throw new Error('This sign-in is not connected to an active Northern Lakes customer account.');state.account=data;$('customerName').textContent=data.display_name||data.customer_code||'Customer';$('customerCode').textContent=data.customer_code?'Customer '+data.customer_code:'';return true;}
async function own(table,columns,order='updated_at'){let request=state.client.from(table).select(columns).eq('business_id',config.businessId).eq('customer_id',state.account.id);if(order)request=request.order(order,{ascending:false});const {data,error}=await withTimeout(request,15000,'Customer records took too long to load. Please refresh and try again.');if(error)throw error;return Array.isArray(data)?data:[];}
function renderJobs(){const node=$('jobsList');node.innerHTML=state.jobs.length?state.jobs.map(row=>`<article class="portal-item"><div class="portal-item__head"><div><strong>${esc(row.job_number||row.title||'Property work')}</strong><small>${esc(row.title||'')}</small></div><span class="pill">${esc(row.status||'Open')}</span></div><p>${esc(row.next_action||'No next action has been posted.')}</p><small>Due or next update: ${esc(row.expected_update_date||row.due_date||'Not posted')}</small></article>`).join(''):'<p class="empty">No property work is currently shared with this account.</p>';const select=$('messageJob');select.innerHTML='<option value="">General account question</option>'+state.jobs.map(row=>`<option value="${esc(row.id)}">${esc(row.job_number||row.title)}</option>`).join('');}
function terms(row){return [['Deliverables',row.deliverables],['Timing',row.timing],['Revision allowance',row.revision_allowance],['Exclusions',row.exclusions],['What approval means',row.approval_consequence]].map(([label,value])=>`<div class="quote-term"><strong>${label}</strong><span>${esc(value||'Not posted')}</span></div>`).join('');}
function renderQuotes(){const node=$('quotesList');node.innerHTML=state.quotes.length?state.quotes.map(row=>`<article class="portal-item"><div class="portal-item__head"><div><strong>${esc(row.quote_number||'Estimate')}</strong><small>${esc(row.title||'')}</small></div><div><strong>${money(row.amount)}</strong><br><span class="pill">${esc(row.status||'Draft')}</span></div></div>${row.customer_decision?`<p>Customer decision: <strong>${esc(row.customer_decision.replaceAll('_',' '))}</strong> ${row.decision_at?'on '+esc(dateTime(row.decision_at)):''}</p>`:''}<div class="item-actions"><button class="btn secondary" type="button" data-review-quote="${esc(row.id)}">View Complete Estimate</button>${row.pdf_storage_path?`<button class="btn secondary" type="button" data-download-path="${esc(row.pdf_storage_path)}">Download PDF</button>`:''}</div></article>`).join(''):'<p class="empty">No estimates are available.</p>';node.querySelectorAll('[data-review-quote]').forEach(button=>button.addEventListener('click',()=>openQuote(button.dataset.reviewQuote)));bindDownloads(node);}
function safeHostedUrl(value){try{const url=new URL(String(value||''));return url.protocol==='https:'?url.toString():'';}catch{return'';}}
function paymentAction(row){const url=safeHostedUrl(row.hosted_payment_url);if(!url)return'<span class="pill">Online payment not configured</span>';if(config.payment?.liveChargingEnabled===true)return`<a class="btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer" data-hosted-payment="live">Pay Invoice</a>`;if(config.payment?.testMode===true&&/test|sandbox/i.test(url))return`<a class="btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer" data-hosted-payment="test">Open Test Checkout</a>`;return'<span class="pill">Payment link held until activation</span>';}
function renderInvoices(){const node=$('invoicesList');node.innerHTML=state.invoices.length?state.invoices.map(row=>`<article class="portal-item"><div class="portal-item__head"><div><strong>${esc(row.invoice_number||'Invoice')}</strong><small>Due ${esc(date(row.due_date))}</small></div><div><strong>${money(row.balance_due)}</strong><br><span class="pill">${esc(row.status||'Open')}</span></div></div><p>Total ${money(row.total)} · Paid ${money(Number(row.total||0)-Number(row.balance_due||0))}</p><div class="item-actions">${row.pdf_storage_path?`<button class="btn secondary" type="button" data-download-path="${esc(row.pdf_storage_path)}">Download Invoice PDF</button>`:''}${paymentAction(row)}</div></article>`).join(''):'<p class="empty">No invoices are available.</p>';bindDownloads(node);}
function renderPayments(){const node=$('paymentsList');node.innerHTML=state.payments.length?state.payments.map(row=>`<article class="portal-item"><div class="portal-item__head"><div><strong>${money(row.amount)} payment</strong><small>${esc(dateTime(row.paid_at||row.created_at))}</small></div><span class="pill">${esc(row.status||'Recorded')}</span></div><p>${esc(row.provider||'Payment provider')} ${row.test_mode?'<strong>TEST MODE</strong>':''}</p><div class="item-actions">${row.receipt_storage_path?`<button class="btn secondary" type="button" data-download-path="${esc(row.receipt_storage_path)}">Download Receipt</button>`:'<span class="pill">Receipt not posted</span>'}</div></article>`).join(''):'<p class="empty">No payment history has been posted.</p>';bindDownloads(node);}
function renderFiles(){const node=$('filesList');node.innerHTML=state.files.length?state.files.map(row=>`<article class="portal-item"><div class="portal-item__head"><div><strong>${esc(row.file_name||'Shared file')}</strong><small>${esc(row.status||'Available')}</small></div><span class="pill">Private</span></div><div class="item-actions"><button class="btn secondary" type="button" data-download-path="${esc(row.storage_path)}">Secure Download</button></div></article>`).join(''):'<p class="empty">No files or photos are currently shared.</p>';bindDownloads(node);}
function bindDownloads(root){root.querySelectorAll('[data-download-path]').forEach(button=>button.addEventListener('click',()=>download(button.dataset.downloadPath).catch(safeError)));}
async function download(path){if(!path)throw new Error('No secure file path was posted.');const {data,error}=await withTimeout(state.client.storage.from(config.storageBucket).createSignedUrl(path,120,{download:true}),15000,'Secure download took too long. Please try again.');if(error)throw error;if(!data?.signedUrl)throw new Error('Secure download could not be created.');window.open(data.signedUrl,'_blank','noopener,noreferrer');}
function openQuote(id){const row=state.quotes.find(item=>item.id===id);if(!row)return;state.activeQuote=row;$('quoteDialogTitle').textContent=row.quote_number||row.title||'Estimate Review';$('quoteDialogBody').innerHTML=`<p><strong>${esc(row.title||'Northern Lakes estimate')}</strong></p><p>Amount: <strong>${money(row.amount)}</strong> · Version ${Number(row.version||1)}</p><div class="quote-terms">${terms(row)}</div>${row.customer_decision?`<p class="payment-status"><strong>Decision already recorded:</strong> ${esc(row.customer_decision.replaceAll('_',' '))}</p>`:''}`;const available=row.status==='presented'&&!row.customer_decision;$('quoteApprove').disabled=!available;$('quoteRevision').disabled=!available;$('quoteDecline').disabled=!available;$('quoteDialog').showModal();}
async function decide(decision){const row=state.activeQuote;if(!row)throw new Error('Choose an estimate first.');let notes='';if(decision==='revision_requested'){notes=prompt('Describe the requested change:')||'';if(notes.trim().length<3)return;}if(decision==='declined')notes=prompt('Optional reason for declining:')||'';const confirmation=decision==='approved'?'Approve this fully reviewed estimate? This does not charge a card or start work automatically.':`Record ${decision.replaceAll('_',' ')}?`;if(!confirm(confirmation))return;const {error}=await withTimeout(state.client.rpc('customer_portal_decide_quote',{p_quote_id:row.id,p_expected_version:Number(row.version||1),p_decision:decision,p_notes:notes||null}),15000,'Estimate update took too long. Please try again.');if(error)throw error;$('quoteDialog').close();notice('<strong>Customer decision recorded.</strong> Northern Lakes must review the next action.','good');await refresh();}
async function submitMessage(event){event.preventDefault();const body=String($('messageBody').value||'').trim();if(!body)throw new Error('Enter a message first.');if(body.length>2000)throw new Error('Messages are limited to 2,000 characters.');const jobId=String($('messageJob').value||'')||null;const request=state.client.from('customer_messages').insert({business_id:config.businessId,customer_id:state.account.id,job_id:jobId,body,direction:'customer_to_business',status:'pending_owner_review',created_by:state.session.user.id});const {error}=await withTimeout(request,15000,'Message save took too long. Please try again.');if(error)throw error;$('messageBody').value='';notice('<strong>Message recorded for owner review.</strong> No automatic text or email was sent.','good');}
function renderPaymentMode(){const node=$('paymentModeNotice');const payment=config.payment||{};if(payment.liveChargingEnabled===true){node.innerHTML='<strong>Hosted online payments enabled</strong><span>Card information is entered only on the approved payment provider’s hosted page.</span>';return;}node.innerHTML='<strong>Live online charging is not active</strong><span>'+esc(payment.notice||'Payment-provider setup is pending. Invoices and balances remain viewable.')+'</span>';}
async function refresh(){if(!state.account||!state.session)return;const epoch=state.epoch,accountId=state.account.id;notice('Loading your Northern Lakes records…');const [jobs,quotes,invoices,payments,files]=await Promise.all([
 own('customer_jobs','id,business_id,customer_id,job_number,title,status,next_action,due_date,expected_update_date,progress_percent'),
 own('customer_quotes','id,business_id,customer_id,job_id,quote_number,title,amount,status,version,customer_decision,decision_at,deliverables,timing,revision_allowance,exclusions,approval_consequence,pdf_storage_path'),
 own('customer_invoices','id,business_id,customer_id,invoice_number,total,balance_due,status,due_date,hosted_payment_url,pdf_storage_path'),
 own('customer_payments','id,business_id,customer_id,invoice_id,provider,amount,status,paid_at,receipt_storage_path,test_mode','paid_at'),
 own('customer_files','id,business_id,customer_id,job_id,file_name,storage_path,status,available_to_customer')
 ]);if(epoch!==state.epoch||!state.session||state.account?.id!==accountId)return;state.jobs=jobs;state.quotes=quotes;state.invoices=invoices;state.payments=payments;state.files=files.filter(row=>row.available_to_customer===true);renderJobs();renderQuotes();renderInvoices();renderPayments();renderFiles();$('metricBalance').textContent=money(invoices.reduce((sum,row)=>sum+Number(row.balance_due||0),0));$('metricInvoices').textContent=invoices.filter(row=>Number(row.balance_due||0)>0).length;$('metricQuotes').textContent=quotes.filter(row=>row.status==='presented'&&!row.customer_decision).length;$('metricJobs').textContent=jobs.filter(row=>!/complete|cancel/i.test(row.status||'')).length;notice('<strong>Secure portal loaded.</strong> This session is limited to your Northern Lakes customer account.','good');}
async function applySession(session){if(!session){clearCustomer();notice('Ready for secure sign-in.');return;}if(state.session?.access_token===session.access_token&&state.account)return;clearCustomer();state.session=session;const epoch=state.epoch;if(!await loadAccount(epoch))return;view('app');renderPaymentMode();await refresh();}
async function boot(){try{if(!initClient())return;$('loginForm').addEventListener('submit',event=>signIn(event).catch(safeError));$('magicLinkButton').addEventListener('click',()=>magicLink().catch(safeError));$('signOutButton').addEventListener('click',()=>signOut().catch(safeError));document.querySelectorAll('[data-sign-out]').forEach(button=>button.addEventListener('click',()=>signOut().catch(safeError)));$('refreshPortal').addEventListener('click',()=>refresh().catch(safeError));$('messageForm').addEventListener('submit',event=>submitMessage(event).catch(safeError));$('closeQuoteDialog').addEventListener('click',()=>$('quoteDialog').close());$('quoteApprove').addEventListener('click',()=>decide('approved').catch(safeError));$('quoteRevision').addEventListener('click',()=>decide('revision_requested').catch(safeError));$('quoteDecline').addEventListener('click',()=>decide('declined').catch(safeError));view('login');notice('Ready for secure sign-in.');let session=null;try{const result=await withTimeout(state.client.auth.getSession(),8000,'Saved sign-in check took too long. You can still sign in below.');if(result.error)throw result.error;session=result.data?.session||null;}catch(error){console.warn(error);notice('Ready for secure sign-in. Saved sign-in could not be checked automatically.','');}if(session)await applySession(session);state.client.auth.onAuthStateChange((_event,nextSession)=>setTimeout(()=>applySession(nextSession).catch(safeError),0));}catch(error){safeError(error);view(validConfig()?'login':'hold');}}
window.NL_CUSTOMER_PORTAL={getState:()=>({...state}),refresh:()=>refresh(),build:'20261001-portal-timeout-copy-1'};
document.addEventListener('DOMContentLoaded',boot);
})();
