(()=>{
'use strict';
const A='assets/';
const CATALOG=[
{id:'cabin-care',name:'Cabin & Lake-Home Care',category:'Property Care Plans',short:'Scheduled property checks, seasonal opening and closing, photo reports and emergency property visits.',description:'Year-round support for cabins and lake homes, especially when owners are away. Every visit is documented and any additional work remains owner-reviewed before scheduling.',available:true,featured:true,image:A+'service-source/cabin-care.jpg',page:'cabin-care.html',seasonal:'Year-round',pricing:'estimate',disclaimer:'Property maintenance only. Conditions outside the visible inspection scope are not guaranteed.',services:['Scheduled property visits','Exterior property inspections','Storm and freeze checks','Door, window and visible-damage checks','Photo reports','Spring property opening','Fall property closing','Yard and driveway preparation','Outdoor furniture setup and storage','Vendor and delivery access','Emergency property visits','Lawn, snow and gravel-driveway coordination']},
{id:'driveway-drainage',name:'Driveway & Drainage Care',category:'Grounds & Site Work',short:'Grading, pothole repair, gravel refresh, culvert cleaning and storm-damage response.',description:'Seasonal and project-based care for gravel driveways, culverts, ditches and drainage trouble spots.',available:true,featured:true,image:A+'excavation.svg',page:'driveway-drainage.html',seasonal:'Spring through freeze-up; emergency response subject to availability',pricing:'estimate',disclaimer:'Final scope depends on site conditions, access, drainage path and any required permits.',services:['Spring driveway inspection','Grading and pothole repair','Gravel refresh and placement','Culvert inlet cleaning','Washout repair','Ditch and drainage correction','Fall touch-up before freeze','Emergency storm repair']},
{id:'commercial-property-care',name:'Commercial Property Care',category:'Property Care Plans',short:'One owner-reviewed agreement for snow, lawn, lot cleanup and seasonal exterior care.',description:'Recurring exterior property maintenance for small offices, retail sites, storage properties, churches, associations and other local facilities.',available:true,featured:true,image:A+'about.svg',page:'commercial-property-care.html',seasonal:'Year-round agreements',pricing:'estimate',disclaimer:'Services and response levels are defined in the approved agreement before work begins.',services:['Snowplowing','Salting and sanding','Ice management','Lawn care','Parking-lot cleanup and sweeping','Trash and exterior cleanup','Seasonal inspections','Minor exterior property maintenance']},
{id:'rental-resort-support',name:'Rental & Resort Property Support',category:'Property Care Plans',short:'Exterior turnover checks, cleanup, lawn, snow, firewood, storm response and owner photo reports.',description:'Behind-the-scenes property support for vacation rentals, cabins and resort properties with documented exterior service.',available:true,featured:true,image:A+'service-source/rental-resort-support.jpg',page:'rental-resort-support.html',seasonal:'Year-round',pricing:'estimate',disclaimer:'Guest-facing commitments and emergency response are confirmed in writing before activation.',services:['Pre-arrival exterior inspections','Exterior turnover cleanup','Garbage and firepit cleanup','Lawn and snow service','Firewood delivery','Gravel and parking-area maintenance','Storm response','Photo reports to owners','Emergency property calls']},
{id:'senior-property-maintenance',name:'Senior Property Maintenance Plans',category:'Property Care Plans',short:'Non-medical exterior property checks and seasonal assistance for older homeowners and their families.',description:'Practical exterior property maintenance with clear photo updates and owner-reviewed service.',available:true,featured:false,image:A+'service-source/senior-property-maintenance.jpg',page:'quote-request.html?service=senior-property-maintenance',seasonal:'Year-round',pricing:'estimate',disclaimer:'Property maintenance only—not personal care, medical care or home-health service.',services:['Exterior home checks','Lawn and snow service','Gutter cleaning','Storm preparation','Minor exterior property tasks','Photo updates for family','Seasonal property assistance']},
{id:'brush-trail-lot-clearing',name:'Brush, Trail & Lot Clearing',category:'Grounds & Site Work',short:'Brush mowing, trail opening, overgrowth removal and hunting-property maintenance.',description:'Equipment-based clearing and cleanup for access routes, trails, lots and overgrown property.',available:true,featured:true,image:A+'service-source/brush-clearing.jpg',page:'quote-request.html?service=brush-trail-lot-clearing',seasonal:'Ground and access conditions permitting',pricing:'estimate',disclaimer:'Tree risk, buried hazards, disposal and site access are reviewed before approval.',services:['Brush mowing','Trail opening','Fallen-tree cleanup','Overgrowth removal','Hunting-property trail maintenance','Lot cleanup','Storm-debris cleanup']},
{id:'storm-tree-cleanup',name:'Storm & Fallen-Tree Cleanup',category:'Grounds & Site Work',short:'Storm debris, fallen-tree and access cleanup subject to safe site conditions.',description:'Responsive exterior cleanup after wind, snow and storm events.',available:true,featured:false,image:A+'service-source/storm-cleanup.jpg',page:'quote-request.html?service=storm-tree-cleanup',seasonal:'As conditions allow',pricing:'estimate',disclaimer:'Utility hazards, unsafe trees and emergency conditions may require specialized providers.',services:['Storm-debris cleanup','Fallen-tree cleanup','Access clearing','Hauling coordination']},
{id:'lawn-landscaping',name:'Lawn & Landscaping',category:'Grounds & Site Work',short:'Mowing, trimming, seasonal cleanup, mulch and landscape maintenance.',description:'Reliable lawn and landscape care for residential, commercial and seasonal properties.',available:true,featured:false,image:A+'lawn.svg',page:'lawn.html',seasonal:'Growing season',pricing:'estimate',disclaimer:'Plant, irrigation and soil conditions are reviewed before recommendations are finalized.',services:['Mowing and trimming','Spring and fall cleanup','Mulch and soil placement','Landscape maintenance']},
{id:'snow-ice',name:'Snow & Ice Management',category:'Grounds & Site Work',short:'Plowing, salting, sanding, ice control and owner-approved seasonal service.',description:'Winter access and ice-management service for homes and commercial properties.',available:true,featured:true,image:A+'snow.svg',page:'snow.html',seasonal:'Winter',pricing:'estimate',disclaimer:'Service triggers, areas and response priorities are defined before activation.',services:['Snowplowing','Salting','Sanding','Ice control','Snowbank relocation','Ice-management inspections']},
{id:'cleanouts-hauling',name:'Cleanouts, Dump Trailers & Hauling',category:'Cleanouts & Hauling',short:'Property and estate cleanouts, customer-loaded dump trailers, cleanup hauling and delivery.',description:'Flexible cleanup and hauling support using Northern Lakes trucks and trailers.',available:true,featured:true,image:A+'service-source/cleanouts-hauling.jpg',page:'cleanouts-hauling.html',seasonal:'Year-round, access permitting',pricing:'estimate',disclaimer:'No prohibited, hazardous or unapproved materials. Disposal rules and fees are confirmed before approval.',services:['Property cleanouts','Estate cleanouts','Construction-debris hauling','Customer-loaded dump-trailer rental','Cleanup hauling','Equipment delivery','Trailer delivery']},
{id:'small-property-improvements',name:'Small Property Improvements',category:'Small Property Improvements',short:'Steps, handrails, pads, walkways, fence repair and minor exterior accessibility work.',description:'Clearly scoped exterior improvements sized for property-maintenance crews and equipment.',available:true,featured:false,image:A+'landscaping.svg',page:'quote-request.html?service=small-property-improvements',seasonal:'Conditions permitting',pricing:'estimate',disclaimer:'Permit, licensing, engineering and code requirements are reviewed before regulated work is accepted.',services:['Steps and handrails','Small decks and landings','Shed pads','Gravel patios','Walkways','Fence repair','Minor accessibility ramps','Mailbox and sign installation']},
{id:'gutter-cleaning',name:'Gutter Cleaning',category:'Seasonal Add-Ons',short:'Seasonal gutter and downspout cleaning subject to safe access.',description:'Exterior gutter cleanup coordinated with other property service.',available:true,featured:false,image:A+'service-source/gutter-cleaning.jpg',page:'quote-request.html?service=gutter-cleaning',seasonal:'Spring and fall',pricing:'estimate',disclaimer:'Roof access, height and condition must be safely serviceable.',services:['Gutter cleaning','Visible downspout check']},
{id:'pressure-washing',name:'Pressure Washing',category:'Seasonal Add-Ons',short:'Exterior surface cleaning after material and site review.',description:'Pressure washing for suitable exterior surfaces and property features.',available:true,featured:false,image:A+'service-source/pressure-washing.jpg',page:'quote-request.html?service=pressure-washing',seasonal:'Warm weather',pricing:'estimate',disclaimer:'Surface condition and water access are confirmed before scheduling.',services:['Exterior surface cleaning','Site cleanup']},
{id:'firewood-delivery',name:'Firewood Delivery & Stacking',category:'Seasonal Add-Ons',short:'Owner-reviewed firewood delivery and stacking.',description:'Seasonal delivery support for cabins, rentals and local properties.',available:true,featured:false,image:A+'service-source/firewood-delivery.jpg',page:'quote-request.html?service=firewood-delivery',seasonal:'Subject to supply',pricing:'estimate',disclaimer:'Wood type, quantity, access and stacking location are confirmed before approval.',services:['Firewood delivery','Firewood stacking']},
{id:'seasonal-yard-cleanup',name:'Spring & Fall Yard Cleanup',category:'Seasonal Add-Ons',short:'Leaves, branches, beds and general exterior seasonal cleanup.',description:'Scheduled cleanup to prepare properties for spring use or winter shutdown.',available:true,featured:false,image:A+'service-source/seasonal-yard-cleanup.jpg',page:'quote-request.html?service=seasonal-yard-cleanup',seasonal:'Spring and fall',pricing:'estimate',disclaimer:'Debris type and disposal are reviewed before approval.',services:['Spring cleanup','Fall cleanup','Branch and leaf collection']},
{id:'holiday-lights',name:'Holiday-Light Installation & Removal',category:'Seasonal Add-Ons',short:'Exterior holiday-light setup and takedown on approved accessible areas.',description:'Seasonal exterior light installation and removal with scope confirmed before scheduling.',available:true,featured:false,image:A+'service-source/holiday-lights.jpg',page:'quote-request.html?service=holiday-lights',seasonal:'Late fall and winter',pricing:'estimate',disclaimer:'Electrical condition, fixture ownership, height and safe access are reviewed first.',services:['Exterior installation','Seasonal removal','Owner-provided light setup']},
{id:'outdoor-furniture',name:'Outdoor Furniture Setup & Storage',category:'Seasonal Add-Ons',short:'Assembly, seasonal setup, relocation and storage coordination.',description:'Property setup support for cabins, rentals and seasonal homes.',available:true,featured:false,image:A+'service-source/outdoor-furniture.jpg',page:'quote-request.html?service=outdoor-furniture',seasonal:'Spring and fall',pricing:'estimate',disclaimer:'Storage space and item condition must be approved before service.',services:['Assembly','Seasonal setup','Relocation','Storage coordination']},
{id:'equipment-rental',name:'Equipment Rental',category:'Equipment & Materials',short:'Skid steers, mini excavators, loaders, trailers and attachments subject to availability.',description:'Owner-reviewed equipment and trailer rental with delivery options.',available:true,featured:false,image:A+'equipment.svg',page:'equipment-rental.html',seasonal:'Subject to availability',pricing:'estimate',disclaimer:'Rental terms, operator requirements, delivery, damage and availability are confirmed before approval.',services:['Equipment rental','Trailer rental','Attachment rental','Equipment delivery']},
{id:'materials-delivery',name:'Materials & Delivery',category:'Equipment & Materials',short:'Sand, road salt, sand/salt mix, gravel, topsoil, mulch and decorative rock.',description:'Bulk materials for property maintenance and improvement, available for pickup or delivery when stocked.',available:true,featured:true,image:A+'materials-source/material-delivery.jpg',page:'materials.html',seasonal:'Availability varies',pricing:'estimate',disclaimer:'Material type, quantity, pickup or delivery, and delivery charge are confirmed before scheduling.',services:['Sand','Road salt','Sand/salt mix','Gravel','Topsoil','Mulch','Decorative rock','Pickup or delivery']}
];
const CATEGORIES=['Property Care Plans','Grounds & Site Work','Cleanouts & Hauling','Small Property Improvements','Seasonal Add-Ons','Equipment & Materials'];
const byId=id=>CATALOG.find(item=>item.id===id);
const requestUrl=item=>item.page.startsWith('quote-request')?item.page:`quote-request.html?service=${encodeURIComponent(item.id)}`;
window.NL_SERVICE_CATALOG=Object.freeze({items:CATALOG,categories:CATEGORIES,byId,requestUrl});
})();
