(()=>{
'use strict';
const V='nl-site-portal-20260805';
const asset=name=>`assets/${name}?v=${V}`;
const LOGO=asset('diamond-logo.svg');
const A={hero:asset('hero.svg'),snow:asset('snow.svg'),lawn:asset('lawn.svg'),landscape:asset('landscaping.svg'),excavation:asset('excavation.svg'),equipment:asset('equipment.svg'),materials:asset('materials.svg'),lake:asset('lake.svg'),about:asset('about.svg')};
const H=`<div class="utility"><div class="wrap"><a href="tel:+12182592506">☎ &nbsp;(218) 259-2506</a><span>● &nbsp;3131 Horseshoe Lake Rd, Grand Rapids, MN 55744</span><span>● &nbsp;Northern Minnesota</span></div></div><header class="site-header"><div class="wrap header-row"><a class="brand" href="index.html"><img class="brand-badge" src="${LOGO}" alt="Northern Lakes Property Maintenance LLC approved logo"><span class="brand-text"><strong>NORTHERN LAKES</strong><span>Property Maintenance LLC</span><em>Reliable. Honest. Hardworking.</em></span></a><button class="nav-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="site-nav" aria-label="Primary navigation"><a data-nav="home" href="index.html">Home</a><a data-nav="services" href="services.html">Services</a><a data-nav="equipment" href="equipment-rental.html">Equipment Rental</a><a data-nav="materials" href="materials.html">Materials &amp; Delivery</a><a data-nav="about" href="about.html">About</a><a data-nav="contact" href="contact.html">Contact</a><a class="customer-link" href="customer-portal.html">Customer Sign In</a><a class="owner-link" href="owner-login.html">Owner Login</a><a class="btn" href="quote-request.html">Request Estimate</a></nav></div></header>`;
const F=`<footer class="site-footer"><div class="wrap footer-grid"><div><img class="footer-logo" src="${LOGO}" alt="Northern Lakes Property Maintenance LLC approved logo"><p>Year-round property maintenance serving Grand Rapids and surrounding Northern Minnesota communities.</p></div><div class="footer-col"><strong>Property Services</strong><a href="cabin-care.html">Cabin &amp; Lake-Home Care</a><a href="driveway-drainage.html">Driveway &amp; Drainage</a><a href="commercial-property-care.html">Commercial Property Care</a><a href="cleanouts-hauling.html">Cleanouts &amp; Hauling</a><a href="services.html">Complete Service Catalog</a></div><div class="footer-col"><strong>Company</strong><a href="about.html">About</a><a href="gallery.html">Our Work</a><a href="reviews.html">Reviews</a><a href="service-areas.html">Service Areas</a><a href="faq.html">FAQ</a></div><div class="footer-col"><strong>Account &amp; Contact</strong><a href="customer-portal.html">Customer Sign In</a><a href="quote-request.html">Request an Estimate</a><a href="contact.html">Contact Northern Lakes</a><a href="tel:+12182592506">(218) 259-2506</a><a class="owner-link" href="owner-login.html">Owner Login</a></div></div><div class="wrap footer-bottom">© 2026 Northern Lakes Property Maintenance LLC · <a href="privacy.html">Privacy</a> · <a href="terms.html">Terms</a></div></footer>`;
const servicePages=['services.html','snow.html','lawn.html','landscaping.html','excavation.html','cabin-care.html','driveway-drainage.html','commercial-property-care.html','rental-resort-support.html','cleanouts-hauling.html'];
function pageKey(){const p=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(p==='index.html'||!p)return'home';if(servicePages.includes(p))return'services';if(p==='equipment-rental.html')return'equipment';if(p==='materials.html')return'materials';if(['about.html','gallery.html','reviews.html','service-areas.html','faq.html'].includes(p))return'about';if(['contact.html','quote-request.html'].includes(p))return'contact';return'';}
function normalizeLogoReferences(){document.querySelectorAll('img').forEach(img=>{const src=String(img.getAttribute('src')||'');if(/diamond-logo|approved.logo.northern|northern.*logo/i.test(src)){img.src=LOGO;img.alt='Northern Lakes Property Maintenance LLC approved logo';}});}
document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('link[href*="approved-hotfix.css"]').forEach(node=>node.remove());
 if(!document.querySelector('link[href*="nl-v3.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href=`nl-v3.css?v=${V}`;document.head.appendChild(link);}
 if(!document.querySelector('.site-header'))document.body.insertAdjacentHTML('afterbegin',H);
 if(!document.querySelector('.site-footer'))document.body.insertAdjacentHTML('beforeend',F);
 normalizeLogoReferences();
 document.querySelectorAll('[data-nav]').forEach(link=>link.classList.toggle('active',link.dataset.nav===pageKey()));
 const toggle=document.querySelector('.nav-toggle');if(toggle)toggle.addEventListener('click',()=>{document.body.classList.toggle('nav-open');toggle.setAttribute('aria-expanded',String(document.body.classList.contains('nav-open')));});
 document.querySelectorAll('.site-nav a').forEach(link=>link.addEventListener('click',()=>document.body.classList.remove('nav-open')));
 const style=document.createElement('style');style.textContent=`.site-nav .customer-link{font-weight:900;color:var(--forest);border:1px solid var(--forest);padding:8px 10px}.site-nav .owner-link{font-size:.72rem;opacity:.72}.hero{background-image:url('${A.hero}')!important;background-size:cover!important;background-position:center!important}.hero:before{background-image:url('${A.hero}')!important}.page-hero img{object-position:center center!important}@media(max-width:1050px){.site-nav .customer-link,.site-nav .owner-link{display:block!important}}`;document.head.appendChild(style);
});
})();
