(()=>{
 const V='ux3';
 const H=`<div class="utility"><div class="wrap"><a href="tel:+12182592506">☎ &nbsp;(218) 259-2506</a><span>● &nbsp;3131 Horseshoe Lake Rd, Grand Rapids, MN 55744</span><span>● &nbsp;Northern Minnesota</span></div></div><header class="site-header"><div class="wrap header-row"><a class="brand" href="index.html"><img class="brand-badge" src="assets/diamond-logo.svg?v=${V}" alt="Northern Lakes Property Maintenance LLC diamond logo"><span class="brand-text"><strong>NORTHERN LAKES</strong><span>Property Maintenance LLC</span><em>Reliable. Honest. Hardworking.</em></span></a><button class="nav-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="site-nav" aria-label="Primary navigation"><a data-nav="home" href="index.html">Home</a><a data-nav="services" href="services.html">Services</a><a data-nav="equipment" href="equipment-rental.html">Equipment Rental</a><a data-nav="materials" href="materials.html">Salt &amp; Materials</a><a data-nav="about" href="about.html">About Us</a><a data-nav="contact" href="contact.html">Contact</a><a class="owner-link" href="owner-login.html">Owner Login</a><a class="btn" href="quote-request.html">Request an Estimate</a></nav></div></header>`;
 const F=`<footer class="site-footer"><div class="wrap footer-grid"><div><img class="footer-logo" src="assets/diamond-logo.svg?v=${V}" alt="Northern Lakes diamond logo"><p>Year-round property maintenance serving Grand Rapids and surrounding Northern Minnesota communities.</p></div><div class="footer-col"><strong>Services</strong><a href="snow.html">Snow &amp; Ice</a><a href="lawn.html">Lawn &amp; Landscaping</a><a href="excavation.html">Property &amp; Outdoor Work</a><a href="equipment-rental.html">Equipment Rental</a><a href="materials.html">Salt &amp; Materials</a></div><div class="footer-col"><strong>Company</strong><a href="about.html">About Us</a><a href="gallery.html">Our Work</a><a href="reviews.html">Reviews</a><a href="service-areas.html">Service Areas</a><a href="faq.html">FAQ</a></div><div class="footer-col"><strong>Contact</strong><a href="tel:+12182592506">(218) 259-2506</a><a href="contact.html">3131 Horseshoe Lake Rd<br>Grand Rapids, MN 55744</a><a href="customer-portal.html">Customer Portal</a><a href="owner-login.html">Owner Login</a></div></div><div class="wrap footer-bottom">© 2026 Northern Lakes Property Maintenance LLC · <a href="privacy.html">Privacy</a> · <a href="terms.html">Terms</a></div></footer>`;
 const key=()=>{const p=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(p==='index.html'||!p)return'home';if(['services.html','snow.html','lawn.html','landscaping.html','excavation.html'].includes(p))return'services';if(p==='equipment-rental.html')return'equipment';if(p==='materials.html')return'materials';if(['about.html','gallery.html','reviews.html','service-areas.html','faq.html'].includes(p))return'about';if(['contact.html','quote-request.html'].includes(p))return'contact';return''};
 document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('link[href*="approved-hotfix.css"]').forEach(n=>n.remove());
  if(!document.querySelector('link[href*="nl-v3.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href=`nl-v3.css?v=${V}`;document.head.appendChild(l)}
  if(!document.querySelector('.site-header'))document.body.insertAdjacentHTML('afterbegin',H);
  if(!document.querySelector('.site-footer'))document.body.insertAdjacentHTML('beforeend',F);
  document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===key()));
  const b=document.querySelector('.nav-toggle');if(b)b.addEventListener('click',()=>{document.body.classList.toggle('nav-open');b.setAttribute('aria-expanded',String(document.body.classList.contains('nav-open')))});
  document.querySelectorAll('.site-nav a').forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('nav-open')));
  document.querySelectorAll('img[src^="assets/"]').forEach(img=>{const s=img.getAttribute('src').split('?')[0];img.setAttribute('src',`${s}?v=${V}`)});
 });
})();