(()=>{
 const V='visual-final-20260719';
 const A={
  hero:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:9d9509a5-3956-4c01-8d6d-0dbd566d174c',
  snow:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:9d9509a5-3956-4c01-8d6d-0dbd566d174c',
  lawn:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:65f7e03e-e7e0-4108-b8f5-36e959bbded6',
  landscape:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:701b1ca9-ea9e-4277-a8c2-44f2058c50e1',
  excavation:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:38de198d-c5f3-4795-8d25-de5022c3d024',
  equipment:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:503b1d08-2c44-423f-a83f-e1cdad87abb9',
  materials:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:fd5097e0-fb8e-426f-83b7-bf1b7c0154d6',
  lake:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:4091c6b6-3e2d-493d-b346-aee2b4bf0a2e',
  about:'https://photoshop-api.adobe.io/v2/short-url/urn:aaid:ps:US:b1171653-48af-409c-8395-2b8809f68cdb'
 };
 const H=`<div class="utility"><div class="wrap"><a href="tel:+12182592506">☎ &nbsp;(218) 259-2506</a><span>● &nbsp;3131 Horseshoe Lake Rd, Grand Rapids, MN 55744</span><span>● &nbsp;Northern Minnesota</span></div></div><header class="site-header"><div class="wrap header-row"><a class="brand" href="index.html"><img class="brand-badge" src="assets/diamond-logo.svg?v=${V}" alt="Northern Lakes Property Maintenance LLC diamond logo"><span class="brand-text"><strong>NORTHERN LAKES</strong><span>Property Maintenance LLC</span><em>Reliable. Honest. Hardworking.</em></span></a><button class="nav-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="site-nav" aria-label="Primary navigation"><a data-nav="home" href="index.html">Home</a><a data-nav="services" href="services.html">Services</a><a data-nav="equipment" href="equipment-rental.html">Equipment Rental</a><a data-nav="materials" href="materials.html">Salt &amp; Materials</a><a data-nav="about" href="about.html">About Us</a><a data-nav="contact" href="contact.html">Contact</a><a class="owner-link" href="owner-login.html">Owner Login</a><a class="btn" href="quote-request.html">Request an Estimate</a></nav></div></header>`;
 const F=`<footer class="site-footer"><div class="wrap footer-grid"><div><img class="footer-logo" src="assets/diamond-logo.svg?v=${V}" alt="Northern Lakes diamond logo"><p>Year-round property maintenance serving Grand Rapids and surrounding Northern Minnesota communities.</p></div><div class="footer-col"><strong>Services</strong><a href="snow.html">Snow &amp; Ice</a><a href="lawn.html">Lawn &amp; Landscaping</a><a href="excavation.html">Property &amp; Outdoor Work</a><a href="equipment-rental.html">Equipment Rental</a><a href="materials.html">Salt &amp; Materials</a></div><div class="footer-col"><strong>Company</strong><a href="about.html">About Us</a><a href="gallery.html">Our Work</a><a href="reviews.html">Reviews</a><a href="service-areas.html">Service Areas</a><a href="faq.html">FAQ</a></div><div class="footer-col"><strong>Contact</strong><a href="tel:+12182592506">(218) 259-2506</a><a href="contact.html">3131 Horseshoe Lake Rd<br>Grand Rapids, MN 55744</a><a href="customer-portal.html">Customer Portal</a><a href="owner-login.html">Owner Login</a></div></div><div class="wrap footer-bottom">© 2026 Northern Lakes Property Maintenance LLC · <a href="privacy.html">Privacy</a> · <a href="terms.html">Terms</a></div></footer>`;
 const EXPECT=`<div class="wrap"><div class="section-title"><div class="eyebrow">What You Can Expect</div><h2>Clear Service From Request to Completion.</h2></div><div class="quote-grid"><article class="quote"><h3>Clear Estimates</h3><p>Scope, pricing, assumptions and next steps are reviewed before work is authorized.</p></article><article class="quote"><h3>Prepared Equipment</h3><p>Equipment and materials are selected for the work and checked before service begins.</p></article><article class="quote"><h3>Controlled Approvals</h3><p>During beta testing, customer sends, scheduling and charges remain owner-approved actions.</p></article></div></div>`;
 const key=()=>{const p=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(p==='index.html'||!p)return'home';if(['services.html','snow.html','lawn.html','landscaping.html','excavation.html'].includes(p))return'services';if(p==='equipment-rental.html')return'equipment';if(p==='materials.html')return'materials';if(['about.html','gallery.html','reviews.html','service-areas.html','faq.html'].includes(p))return'about';if(['contact.html','quote-request.html'].includes(p))return'contact';return''};
 const pick=src=>{const s=(src||'').split('?')[0].toLowerCase();if(s.includes('diamond-logo')||s.includes('/logo'))return `assets/diamond-logo.svg?v=${V}`;if(s.includes('hero'))return A.hero;if(s.includes('snow'))return A.snow;if(s.includes('equipment')||s.includes('skid'))return A.equipment;if(s.includes('material')||s.includes('salt'))return A.materials;if(s.includes('excavat')||s.includes('driveway'))return A.excavation;if(s.includes('landscape')||s.includes('patio'))return A.landscape;if(s.includes('lawn'))return A.lawn;if(s.includes('lake')||s.includes('community'))return A.lake;if(s.includes('about')||s.includes('commercial')||s.includes('truck'))return A.about;return src};
 document.addEventListener('DOMContentLoaded',()=>{
  document.querySelectorAll('link[href*="approved-hotfix.css"]').forEach(n=>n.remove());
  if(!document.querySelector('link[href*="nl-v3.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href=`nl-v3.css?v=${V}`;document.head.appendChild(l)}
  if(!document.querySelector('.site-header'))document.body.insertAdjacentHTML('afterbegin',H);
  if(!document.querySelector('.site-footer'))document.body.insertAdjacentHTML('beforeend',F);
  const confidence=document.querySelector('.testimonials');if(confidence)confidence.innerHTML=EXPECT;
  document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===key()));
  const b=document.querySelector('.nav-toggle');if(b)b.addEventListener('click',()=>{document.body.classList.toggle('nav-open');b.setAttribute('aria-expanded',String(document.body.classList.contains('nav-open')))});
  document.querySelectorAll('.site-nav a').forEach(a=>a.addEventListener('click',()=>document.body.classList.remove('nav-open')));
  document.querySelectorAll('img').forEach(img=>{const next=pick(img.getAttribute('src'));if(next&&next!==img.getAttribute('src'))img.setAttribute('src',next);img.addEventListener('error',()=>{if(!img.dataset.nlFallback){img.dataset.nlFallback='1';img.src=A.hero}})});
  const st=document.createElement('style');st.textContent=`.hero{background-image:url('${A.hero}')!important;background-size:cover!important;background-position:center!important}.hero:before{background-image:url('${A.hero}')!important}.hero-media{object-position:center center!important}.page-hero img{object-position:center center!important}`;document.head.appendChild(st);
 });
})();