import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const BUSINESS_ID="10b85a89-5834-436d-95b0-c6ee2eb335ad";
const REPOSITORY="rkrueth-maker/highway-38-solutions";
const WORKFLOW="Scout Owner Maintenance v2.4";
const OWNER_ACTOR="rkrueth-maker";
const AUDIENCE="h38-scout-owner-maintenance";
const ALLOWED_REF="refs/heads/agent/private-reseller-scout-maintenance-v240";
const BUILD="20260826-scout-owner-maintenance-v240-1";
type J=Record<string,any>;
const txt=(v:any,max=12000)=>String(v??"").trim().slice(0,max);
const db=()=>createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(status:number,body:any)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
function bytes(value:string){const s=value.replace(/-/g,"+").replace(/_/g,"/"),pad=s+"=".repeat((4-s.length%4)%4),raw=atob(pad),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function decode(value:string){return JSON.parse(new TextDecoder().decode(bytes(value)));}
async function verifyOidc(token:string){const parts=token.split(".");if(parts.length!==3)throw new Error("GitHub OIDC token is malformed.");const header=decode(parts[0]),claims=decode(parts[1]);if(header.alg!=="RS256"||!header.kid)throw new Error("GitHub OIDC signing algorithm is not accepted.");const r=await fetch("https://token.actions.githubusercontent.com/.well-known/jwks",{signal:AbortSignal.timeout(15000)}),jwks=await r.json(),jwk=(jwks.keys||[]).find((k:J)=>k.kid===header.kid);if(!r.ok||!jwk)throw new Error("GitHub OIDC signing key is unavailable.");const key=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]),ok=await crypto.subtle.verify("RSASSA-PKCS1-v1_5",key,bytes(parts[2]),new TextEncoder().encode(`${parts[0]}.${parts[1]}`));if(!ok)throw new Error("GitHub OIDC signature is invalid.");const now=Math.floor(Date.now()/1000),aud=Array.isArray(claims.aud)?claims.aud:[claims.aud];if(claims.iss!=="https://token.actions.githubusercontent.com"||!aud.includes(AUDIENCE))throw new Error("GitHub OIDC issuer or audience is invalid.");if(Number(claims.exp||0)<=now||Number(claims.nbf||0)>now+30)throw new Error("GitHub OIDC token is expired or not active.");if(txt(claims.repository)!==REPOSITORY||txt(claims.repository_owner)!=="rkrueth-maker"||txt(claims.actor)!==OWNER_ACTOR)throw new Error("GitHub OIDC repository/actor is not authorized.");if(txt(claims.workflow)!==WORKFLOW)throw new Error(`GitHub OIDC workflow is not authorized: ${txt(claims.workflow)}`);if(txt(claims.event_name)!=="push"||txt(claims.ref)!==ALLOWED_REF)throw new Error(`GitHub OIDC ref is not authorized: ${txt(claims.ref)}`);return claims;}
async function ownerIdentity(s:any){const m=await s.from("business_memberships").select("auth_user_id").eq("business_id",BUSINESS_ID).eq("status","active").eq("role","owner").limit(1).maybeSingle();if(m.error||!m.data?.auth_user_id)throw m.error||new Error("Active H38 owner membership was not found.");const u=await s.auth.admin.getUserById(String(m.data.auth_user_id)),email=txt(u.data?.user?.email).toLowerCase();if(u.error||!email)throw u.error||new Error("Owner email is unavailable.");return{userId:String(m.data.auth_user_id),email};}
async function ownerSession(s:any,email:string){const g=await s.auth.admin.generateLink({type:"magiclink",email});if(g.error||!g.data?.properties?.hashed_token)throw g.error||new Error("Could not create owner maintenance session.");const r=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:"POST",headers:{apikey:SERVICE_KEY,"content-type":"application/json"},body:JSON.stringify({type:"magiclink",token_hash:g.data.properties.hashed_token}),signal:AbortSignal.timeout(30000)}),p=await r.json();if(!r.ok||!p.access_token)throw new Error(p?.message||p?.msg||"Could not verify owner maintenance session.");return String(p.access_token);}
async function callFn(slug:string,token:string,body:J,timeout=120000){const started=Date.now();try{const r=await fetch(`${SUPABASE_URL}/functions/v1/${slug}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,apikey:SERVICE_KEY,"content-type":"application/json",Origin:"https://appassets.androidplatform.net","x-client-info":BUILD},body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)}),raw=await r.text();let p:any={};try{p=JSON.parse(raw);}catch{p={status:"FAIL",message:raw.slice(0,1200)}}return{http:r.status,ok:r.ok,payload:p,elapsedMs:Date.now()-started};}catch(e){return{http:0,ok:false,payload:{status:"FAIL",message:txt(e,1200)},elapsedMs:Date.now()-started};}}
function hdCheck(r:any){const p=r.payload||{},readings=Array.isArray(p.readings)?p.readings:[],allowed=["LIVE","LIVE_PARTIAL","CONFIG_REQUIRED","UNAVAILABLE"].includes(txt(p.provider_status)),fabricated=p.provider_status==="CONFIG_REQUIRED"&&readings.some((x:any)=>x.local_verified===true||x.evidence_level==="LIVE VERIFIED"||x.price_scope==="store");return{status:r.ok&&r.http===200&&p.engine==="H38_HOME_DEPOT_LOCAL_V240"&&allowed&&!fabricated?"PASS":"FAIL",http:r.http,elapsedMs:r.elapsedMs,providerStatus:txt(p.provider_status),candidateCount:Number(p.candidate_count||0),verifiedCount:Number(p.verified_count||0),partialCount:Number(p.partial_count||0),readingCount:readings.length,fabricatedLocalEvidence:fabricated,detail:txt(p.provider_detail||p.truth,1000)};}
function dgCheck(r:any){const p=r.payload||{},stores=Array.isArray(p.stores)?p.stores:[],allowed=["LIVE","LIVE_PARTIAL","CONFIG_REQUIRED","UNAVAILABLE"].includes(txt(p.provider_status)),fabricated=p.provider_status==="CONFIG_REQUIRED"&&stores.length>0;return{status:r.ok&&r.http===200&&p.engine==="H38_DG_REMODEL_RADAR_V240"&&allowed&&!fabricated?"PASS":"FAIL",http:r.http,elapsedMs:r.elapsedMs,providerStatus:txt(p.provider_status),indicatorCount:Number(p.indicator_count||0),communityCandidateCount:Array.isArray(p.community_candidates)?p.community_candidates.length:0,storeCount:stores.length,fabricatedStoreEvidence:fabricated,warnings:Array.isArray(p.warnings)?p.warnings.slice(0,8):[],detail:txt(p.provider_detail||p.truth,1000)};}
function fbCheck(r:any){const p=r.payload||{},results=Array.isArray(p.results)?p.results:[],allowed=["LIVE","LIVE_PARTIAL","AUTH_GATED","CONFIG_REQUIRED","UNAVAILABLE"].includes(txt(p.provider_status)),countMatches=Number(p.count||0)===results.length;return{status:r.ok&&r.http===200&&p.engine==="H38_FACEBOOK_PUBLIC_V240"&&p.authentication==="NO_FACEBOOK_LOGIN"&&allowed&&countMatches?"PASS":"FAIL",http:r.http,elapsedMs:r.elapsedMs,providerStatus:txt(p.provider_status),provider:txt(p.provider),authentication:txt(p.authentication),count:Number(p.count||0),countMatches,warnings:Array.isArray(p.warnings)?p.warnings.slice(0,8):[],detail:txt(p.config_hint||p.truth,1000)};}
async function run(token:string){const hdBody={postal:"55744",deep_verify:true,candidates:[{retailer:"Home Depot",title:"Milwaukee M18 FUEL 1/2 in. Hammer Drill/Driver",source:"owner-maintenance-v240"}]},dgBody={postal:"55744",location_label:"Grand Rapids, MN",nearby_stores:[]},fbBody={postal:"55744",location_label:"Grand Rapids, MN",lat:47.2372,lon:-93.5302,radiusMiles:50,terms:["Milwaukee","generator","tool box","lawn mower"]};const [hdRaw,dgRaw,fbRaw]=await Promise.all([callFn("reseller-home-depot-local-v240",token,hdBody,80000),callFn("reseller-dg-remodel-radar-v240",token,dgBody,125000),callFn("reseller-facebook-public-v240",token,fbBody,125000)]),homeDepot=hdCheck(hdRaw),dollarGeneral=dgCheck(dgRaw),facebook=fbCheck(fbRaw),checks=[homeDepot,dollarGeneral,facebook],pass=checks.every(x=>x.status==="PASS");return{status:pass?"PASS":"FAIL",build:BUILD,release:"2.4.0",releaseSha:"93d241e9aefd8755f25791445f4962d374c610b0",authMode:"github-oidc -> temporary H38 owner Supabase session",readOnly:true,location:{postal:"55744",label:"Grand Rapids, MN",radiusMiles:50},homeDepot,dollarGeneral,facebook,providerReadiness:{homeDepot:homeDepot.providerStatus,dollarGeneral:dollarGeneral.providerStatus,facebook:facebook.providerStatus},truthBoundary:"PASS means authenticated runtime and evidence labeling behaved correctly. LIVE provider readiness is reported separately; CONFIG_REQUIRED or AUTH_GATED is not mislabeled as live inventory."};}
Deno.serve(async req=>{if(req.method!=="POST")return json(405,{status:"FAIL",message:"POST required",build:BUILD});const oidc=txt(req.headers.get("x-h38-github-oidc"),12000);if(!oidc)return json(401,{status:"FAIL",message:"GitHub OIDC identity is required.",build:BUILD});try{const claims=await verifyOidc(oidc),s=db(),owner=await ownerIdentity(s),token=await ownerSession(s,owner.email),result=await run(token);return json(result.status==="PASS"?200:422,{...result,githubRunId:txt(claims.run_id,120),githubRef:txt(claims.ref,300)});}catch(e){return json(401,{status:"FAIL",message:txt(e,1600),build:BUILD});}});
