import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";
const BASE=Deno.env.get('SUPABASE_URL')||'',ANON=Deno.env.get('SUPABASE_ANON_KEY')||'',SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',BUCKET='h38-penny-images',MAX_BYTES=3*1024*1024,BATCH=24;
const HEAD={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-h38-nightly-key','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'};
const txt=v=>String(v??'').trim(),json=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:HEAD}),admin=()=>createClient(BASE,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const STOP=new Set(['the','and','with','for','from','this','that','only','pack','set','size','oz','fl','ea','inch','inches','clearance','sale','new','each']);
function norm(v){return txt(v).toLowerCase().replace(/&amp;/g,'&').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function tokens(v){return [...new Set(norm(v).split(' ').filter(x=>x.length>2&&!STOP.has(x)&&!/^\d+$/.test(x)))]}
function overlap(a,b){const A=tokens(a),B=new Set(tokens(b));let hits=0;for(const x of A)if(B.has(x))hits++;return{hits,score:A.length?hits/A.length:0,count:A.length}}
function lowInfo(v){const n=norm(v),t=tokens(v);return n.length<12||t.length<3||/^\$?\d+(?:\.\d+)?(?: ea)?$/.test(n)||/clearance rollbacks?$/.test(n)}
function decode(v){return txt(v).replace(/&quot;|&#34;/gi,'"').replace(/&amp;/gi,'&').replace(/&#x27;|&#39;/gi,"'")}
function coreTitle(v){return txt(v).replace(/\([^)]*\)/g,' ').replace(/\b\d+(?:\.\d+)?\s*(?:fl\s*)?(?:oz|ounce|ounces|ea|ct|count|ml|l|lb|lbs|inch|inches)\b/gi,' ').replace(/\s+-\s+\d+(?:\.\d+)?\s*(?:fl\s*)?(?:oz|ea|ct|ml|l|lb|lbs)\b/gi,' ').replace(/\s+/g,' ').trim()}
function retailerHost(r){return /walmart/i.test(txt(r))?'walmart.com':/walgreen/i.test(txt(r))?'walgreens.com':''}
function exactRetailerPage(v,host){try{const u=new URL(decode(v)),h=u.hostname.toLowerCase();return u.protocol==='https:'&&(h===host||h.endsWith('.'+host))?u.toString():''}catch{return''}}
function exactProductPage(v,host){const page=exactRetailerPage(v,host);if(!page)return'';try{const u=new URL(page);if(host==='walmart.com'&&!/\/ip\/(?:[^/?#]+\/)?\d+/i.test(u.pathname))return'';if(host==='walgreens.com'&&!/\/store\/c\//i.test(u.pathname))return'';return page}catch{return''}}
function safeImage(v){try{const u=new URL(decode(v)),h=u.hostname.toLowerCase(),p=(u.pathname+u.search).toLowerCase();if(u.protocol!=='https:'||!h||h==='localhost'||h.endsWith('.local')||/^\d+\.\d+\.\d+\.\d+$/.test(h)||/(logo|favicon|sprite|pixel|tracking|blank|placeholder|no-image)/.test(p))return'';return u.toString()}catch{return''}}
async function internalOk(req){const got=txt(req.headers.get('x-h38-nightly-key'));if(!got)return false;const {data}=await admin().from('h38_internal_job_secrets').select('secret_value').eq('name','penny-nightly').maybeSingle();return !!data?.secret_value&&got===data.secret_value}
async function userOk(req){const auth=txt(req.headers.get('authorization')),token=auth.replace(/^Bearer\s+/i,'');if(!token)return false;const sb=createClient(BASE,ANON,{global:{headers:{Authorization:'Bearer '+token}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error}=await sb.auth.getUser(token);if(error||!user)return false;const {data}=await sb.from('h38_product_entitlements').select('active,expires_at').eq('user_id',user.id).eq('product_key','penny').maybeSingle();return !!data?.active&&(!data.expires_at||Date.parse(data.expires_at)>Date.now())}
async function allowed(req){return await internalOk(req)||await userOk(req)}
function bingCandidates(html){const out=[];for(const hit of html.matchAll(/<a\b[^>]*>/gi)){const tag=hit[0];if(!/\bclass=["'][^"']*\biusc\b[^"']*["']/i.test(tag))continue;const mm=tag.match(/\bm=(["'])([\s\S]*?)\1/i);if(!mm)continue;try{const o=JSON.parse(decode(mm[2])),purl=txt(o.purl),murl=txt(o.murl);if(purl&&murl)out.push({purl,murl,label:[o.t,o.desc].filter(Boolean).join(' ')})}catch{}if(out.length>=40)break}return out}
async function bing(query){try{const r=await fetch('https://www.bing.com/images/search?q='+encodeURIComponent(query)+'&form=HDRSC3',{headers:{'user-agent':'Mozilla/5.0 H38Deals/9.1 retailer-image','accept':'text/html,*/*'},signal:AbortSignal.timeout(12000)});if(!r.ok)return[];return bingCandidates(await r.text())}catch{return[]}}
async function retailerPageImage(page){try{const r=await fetch(page,{headers:{'user-agent':'Mozilla/5.0 H38Deals/9.1 retailer-image','accept':'text/html,application/xhtml+xml,*/*'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!r.ok)return'';const html=await r.text();const pats=[/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i,/<meta[^>]+name=["']twitter:image(?::src)?["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image(?::src)?["']/i];for(const p of pats){const m=html.match(p),u=m?safeImage(decode(m[1])):'';if(u)return u}return''}catch{return''}}
async function fetchImage(url,ref){try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 H38Deals/9.1 retailer-image','accept':'image/avif,image/webp,image/*,*/*;q=0.8','referer':ref},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!r.ok)return null;const mime=(r.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(mime))return null;const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length<1500||bytes.length>MAX_BYTES)return null;return{bytes,mime,source:r.url}}catch{return null}}
async function pathFor(key,mime){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key))),h=Array.from(b).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,40),ext=mime==='image/png'?'png':mime==='image/webp'?'webp':mime==='image/gif'?'gif':mime==='image/avif'?'avif':'jpg';return`${h.slice(0,2)}/${h}.${ext}`}
async function save(a,row,img,page,score,proof){const path=await pathFor(row.canonical_key,img.mime),up=await a.storage.from(BUCKET).upload(path,img.bytes,{contentType:img.mime,cacheControl:'31536000',upsert:true});if(up.error)throw up.error;const publicUrl=a.storage.from(BUCKET).getPublicUrl(path).data.publicUrl,p=row.payload&&typeof row.payload==='object'?row.payload:{},now=new Date().toISOString();const payload={...p,image_source_scope:'product_identification',image_source_proof:proof,retailer_image_verified_page:page,retailer_image_title_score:score,retailer_image_attempted_at:now,retailer_image_attempt_count:Number(p.retailer_image_attempt_count||0)+1};const {error}=await a.from('reseller_hunt_cache').update({image_url:publicUrl,image_storage_path:path,image_cached_at:now,image_source_url:img.source,image_mime:img.mime,image_last_error:'',payload,last_changed_at:now}).eq('canonical_key',row.canonical_key);if(error)throw error;return true}
function candidateOk(title,label,retailerPage){const m=overlap(title,label),brand=tokens(title)[0]||'',brandOk=!brand||tokens(label).includes(brand);if(!brandOk)return{ok:false,m};if(retailerPage)return{ok:m.hits>=Math.min(2,m.count)&&m.score>=.35,m};return{ok:m.hits>=Math.min(3,m.count)&&m.score>=.55,m}}
async function one(a,row){const p=row.payload&&typeof row.payload==='object'?row.payload:{},title=txt(row.title||p.title),host=retailerHost(row.retailer),attempt=Number(p.retailer_image_attempt_count||0)+1,now=new Date().toISOString();if(!host||lowInfo(title))return false;const sku=txt(row.sku||p.sku).replace(/\D/g,''),core=coreTitle(title),short=core.split(/\s+/).slice(0,12).join(' '),knownPage=exactProductPage(row.source_url||p.source_url,host);if(knownPage){const direct=await retailerPageImage(knownPage);if(direct){const img=await fetchImage(direct,knownPage);if(img)return await save(a,row,img,knownPage,1,'exact_retailer_product_page_metadata')}}const queries=[];if(host==='walmart.com'&&sku)queries.push(`site:walmart.com/ip/${sku} "${short}"`);queries.push(`site:${host} "${short}"`);queries.push(`"${short}" ${host==='walmart.com'?'Walmart':'Walgreens'} product`);queries.push(`"${short}" product`);let best=null,candidateCount=0;for(const q of queries){const found=await bing(q);candidateCount+=found.length;for(const c of found){const retailerPage=exactRetailerPage(c.purl,host),page=retailerPage||safeImage(c.purl),image=safeImage(c.murl);if(!page||!image)continue;const chk=candidateOk(core,c.label,!!retailerPage);if(!chk.ok)continue;const proof=retailerPage?'retailer_domain_brand_title_match':'strong_brand_title_image_match_external_reference';if(!best||chk.m.score>best.score||(chk.m.score===best.score&&retailerPage&&!best.retailerPage))best={...c,page,image,score:chk.m.score,hits:chk.m.hits,proof,retailerPage:!!retailerPage}}if(best)break}if(!best){await a.from('reseller_hunt_cache').update({image_last_error:candidateCount?'No defensible brand/title image match':'Image search returned no parseable candidates',payload:{...p,retailer_image_attempted_at:now,retailer_image_attempt_count:attempt,retailer_image_candidate_count:candidateCount}}).eq('canonical_key',row.canonical_key);return false}const img=await fetchImage(best.image,best.page);if(!img){await a.from('reseller_hunt_cache').update({image_last_error:'Matched product image could not be cached',payload:{...p,retailer_image_attempted_at:now,retailer_image_attempt_count:attempt}}).eq('canonical_key',row.canonical_key);return false}return await save(a,row,img,best.page,best.score,best.proof)}
async function run(){const a=admin(),{data,error}=await a.from('reseller_hunt_cache').select('canonical_key,retailer,title,sku,source_url,image_storage_path,payload').eq('active',true).eq('image_storage_path','').in('retailer',['Walmart','Walgreens']).limit(120);if(error)throw error;const rows=(data||[]).filter(r=>!lowInfo(r.title)).sort((x,y)=>Number(x.payload?.retailer_image_attempt_count||0)-Number(y.payload?.retailer_image_attempt_count||0)).slice(0,BATCH);let cursor=0,attempted=0,saved=0;const byRetailer={};async function worker(){while(cursor<rows.length){const r=rows[cursor++];attempted++;try{if(await one(a,r)){saved++;byRetailer[r.retailer]=(byRetailer[r.retailer]||0)+1}}catch(e){console.error('retailer image',r.canonical_key,e)}}}await Promise.all([worker(),worker(),worker(),worker()]);return{attempted,saved,by_retailer:byRetailer,remaining:Math.max(0,(data||[]).length-saved)}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:HEAD});if(req.method!=='POST')return json({error:'POST_REQUIRED'},405);if(!await allowed(req))return json({error:'AUTH_OR_PRODUCT_REQUIRED'},401);try{EdgeRuntime.waitUntil(run());return json({ok:true,data:{started:true,background:true,scope:['Walmart','Walgreens'],matcher:'retailer-page-first-v3'}})}catch(e){return json({error:'RETAILER_IMAGE_ERROR',detail:e instanceof Error?e.message:String(e)},500)}});
