import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Any=Record<string,any>;
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
const HOSTS=['k-bid.com','govdeals.com','allsurplus.com','proxibid.com','auctiontime.com','hibid.com','publicsurplus.com','craigslist.org','craigslistcdn.com','fbcdn.net','facebook.com','retailshout.com','pennytree.org','openfoodfacts.org','openbeautyfacts.org','openproductsfacts.org','openpetfoodfacts.org'];
const MAX=8,MAX_BYTES=650_000;
function cors(r:Request){const o=r.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=300','vary':'Origin'}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function allowed(raw:any){try{const u=new URL(String(raw||''));if(u.protocol!=='https:')return false;const h=u.hostname.toLowerCase();return HOSTS.some(x=>h===x||h.endsWith('.'+x))&&!/(?:logo|icon|avatar|spinner|placeholder|pixel|favicon|tracking|blank|loading)/i.test(u.pathname+u.search)}catch{return false}}
function referer(raw:any){try{const u=new URL(String(raw||''));return u.protocol==='https:'?u.toString():''}catch{return''}}
function b64(bytes:Uint8Array){let out='';for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+0x8000)));return btoa(out)}
async function one(x:Any){const key=String(x?.key||'').trim(),url=String(x?.image_url||'').trim(),ref=referer(x?.source_url);if(!key)return{key,status:'rejected',reason:'missing key'};if(!allowed(url))return{key,status:'rejected',reason:'unapproved image host'};const headers:Record<string,string>={'user-agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36 H38ResellerScout/2.3.0',accept:'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','accept-language':'en-US,en;q=0.9'};if(ref)headers.referer=ref;try{const r=await fetch(url,{headers,redirect:'follow',signal:AbortSignal.timeout(10000)});if(!r.ok)return{key,status:'unavailable',reason:`HTTP ${r.status}`};const type=(r.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!type.startsWith('image/'))return{key,status:'rejected',reason:`not image (${type||'unknown'})`};const len=Number(r.headers.get('content-length')||0);if(len>MAX_BYTES)return{key,status:'rejected',reason:'image too large for local cache'};const bytes=new Uint8Array(await r.arrayBuffer());if(!bytes.length||bytes.length>MAX_BYTES)return{key,status:'rejected',reason:'image size invalid for local cache'};return{key,status:'ok',data_url:`data:${type};base64,${b64(bytes)}`,bytes:bytes.length,source_url:r.url,image_source:String(x?.source||'source listing')}}catch(e){return{key,status:'unavailable',reason:e instanceof Error?e.message:String(e)}}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,405,{error:'POST required'});if(!req.headers.get('authorization'))return json(req,401,{error:'Sign in required'});try{const body=await req.json().catch(()=>({})),items=(Array.isArray(body?.items)?body.items:[]).slice(0,MAX),settled=await Promise.all(items.map(one)),images=settled.filter(x=>x.status==='ok'),warnings=settled.filter(x=>x.status!=='ok');console.log(JSON.stringify({event:'reseller-image-cache-v230',requested:items.length,delivered:images.length,warnings:warnings.length,sources:[...new Set(items.map((x:any)=>String(x?.source||'')))].filter(Boolean)}));return json(req,200,{status:'PASS',images,warnings,rule:'Source listing image cache only. A failed, blocked, stale, or unavailable image never changes product identity, penny truth, location truth, resale evidence, or profitability.'})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});
