import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Any=Record<string,any>;
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const MAX_ITEMS=8,MAX_BYTES=2_500_000,PAGE_TTL=10*60*1000;
const EXACT_HOSTS=["retailshout.com","crazy4couponing.com","pennytree.org","kattydeals.com","openfoodfacts.org","openbeautyfacts.org","openproductsfacts.org","openpetfoodfacts.org","wsuuxqiyujxksfqubpxj.supabase.co"];
const RETAILSHOUT_DG="https://retailshout.com/latest-dollar-general-penny-items-near-you/";
const RETAILSHOUT_DT="https://retailshout.com/latest-dollar-tree-penny-items-near-you/";
const PENNYTREE_ITEM="https://pennytree.org/item.php?sku=";
let dgCache={html:"",at:0},dtCache={html:"",at:0};
const itemPageCache=new Map<string,{html:string,at:number}>();
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"private, max-age=300","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function clean(v:any){return String(v??"").trim()}
function rawDigits(v:any){return clean(v).replace(/\D/g,"")}
function digits(v:any){return rawDigits(v).replace(/^0+/,"")}
function same(a:any,b:any){const x=digits(a),y=digits(b);return !!x&&x===y}
function decode(v:string){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/\\u0026/gi,"&").replace(/\\\//g,"/")}
function abs(v:string,base:string){try{return new URL(decode(v),base).toString()}catch{return""}}
function allowed(url:string){try{const u=new URL(url);if(u.protocol!=="https:")return false;const h=u.hostname.toLowerCase();return EXACT_HOSTS.some(x=>h===x||h.endsWith("."+x))&&!/(?:logo|icon|avatar|spinner|placeholder|pixel|favicon|tracking|blank|loading)/i.test(u.pathname+u.search)}catch{return false}}
function referer(v:any){try{const u=new URL(clean(v));return u.protocol==="https:"?u.toString():""}catch{return""}}
function b64(bytes:Uint8Array){let out="";for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+0x8000)));return btoa(out)}
function imageFromTag(tag:string,base:string){const raws:string[]=[];for(const m of tag.matchAll(/(?:data-src|data-lazy-src|data-original|src)=["']([^"']+)["']/gi))raws.push(m[1]);const set=tag.match(/(?:data-srcset|srcset)=["']([^"']+)["']/i)?.[1]||"";for(const part of set.split(",")){const x=part.trim().split(/\s+/)[0];if(x)raws.push(x)}for(const x of raws){const u=abs(x,base);if(u&&allowed(u))return u}return""}
function firstAllowedImage(html:string,base:string){for(const m of html.matchAll(/<img\b[^>]*>/gi)){const u=imageFromTag(m[0],base);if(u)return u}for(const m of html.matchAll(/(?:og:image|twitter:image)[^>]*content=["']([^"']+)["']/gi)){const u=abs(m[1],base);if(u&&allowed(u))return u}return""}
async function fetchHtml(url:string,ttl=PAGE_TTL){const hit=itemPageCache.get(url);if(hit?.html&&Date.now()-hit.at<ttl)return hit.html;try{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36 H38ResellerScout/2.1.2","accept":"text/html,application/xhtml+xml","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const html=await r.text();itemPageCache.set(url,{html,at:Date.now()});if(itemPageCache.size>80){const first=itemPageCache.keys().next().value;if(first)itemPageCache.delete(first)}return html}catch{return""}}
async function sourcePage(kind:"dg"|"dt"){let cache=kind==="dg"?dgCache:dtCache;if(cache.html&&Date.now()-cache.at<PAGE_TTL)return cache.html;const url=kind==="dg"?RETAILSHOUT_DG:RETAILSHOUT_DT;const html=await fetchHtml(url);if(html){cache={html,at:Date.now()};if(kind==="dg")dgCache=cache;else dtCache=cache}return html}
function exactRetailShout(html:string,barcode:string,base:string){if(!html||!barcode)return"";const variants=[...new Set([rawDigits(barcode),digits(barcode)].filter(x=>x.length>=7))];for(const code of variants){let at=html.indexOf(code);while(at>=0){const next=html.indexOf("UPC",at+code.length),limit=next>at?Math.min(next,at+5000):Math.min(html.length,at+5000),segment=html.slice(at+code.length,limit),tag=segment.match(/<img\b[^>]*>/i)?.[0]||"",u=imageFromTag(tag,base);if(u)return u;at=html.indexOf(code,at+code.length)}}return""}
async function exactPennyTree(retailer:string,barcode:string){const code=digits(barcode);if(!code||code.length<6)return null;const prefix=retailer.includes("dollar general")?"dg":retailer.includes("dollar tree")?"dt":"";if(!prefix)return null;const reference=PENNYTREE_ITEM+encodeURIComponent(`${prefix}:${code}`),html=await fetchHtml(reference,5*60*1000);if(!html)return null;const raw=rawDigits(barcode),normalized=digits(barcode),textDigits=html.replace(/\D/g,"");if(!textDigits.includes(normalized)&&!html.includes(raw))return null;const u=firstAllowedImage(html,reference);if(!u)return null;return{url:u,reference,proof:barcode,source:"PennyTree exact retailer + UPC"}}
async function resolveExact(item:Any){const retailer=clean(item?.retailer).toLowerCase(),barcode=rawDigits(item?.barcode);if(!barcode)return null;const penny=await exactPennyTree(retailer,barcode);if(penny)return penny;if(retailer.includes("dollar general")){const html=await sourcePage("dg"),u=exactRetailShout(html,barcode,RETAILSHOUT_DG);if(u)return{url:u,reference:RETAILSHOUT_DG,proof:barcode,source:"RetailShout exact UPC"}}if(retailer.includes("dollar tree")){const html=await sourcePage("dt"),u=exactRetailShout(html,barcode,RETAILSHOUT_DT);if(u)return{url:u,reference:RETAILSHOUT_DT,proof:barcode,source:"RetailShout exact UPC"}}return null}
async function fetchBytes(key:string,url:string,reference:string,source:string){if(!allowed(url))return{key,status:"rejected",reason:"unapproved image host"};const headers:any={"user-agent":"Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36 H38ResellerScout/2.1.2","accept":"image/avif,image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},ref=referer(reference);if(ref)headers.referer=ref;try{const r=await fetch(url,{headers,redirect:"follow",signal:AbortSignal.timeout(10000)});if(!r.ok)return{key,status:"unavailable",reason:`HTTP ${r.status}`};const type=(r.headers.get("content-type")||"").split(";")[0].trim().toLowerCase();if(!type.startsWith("image/"))return{key,status:"rejected",reason:`not image (${type||"unknown"})`};const len=Number(r.headers.get("content-length")||0);if(len>MAX_BYTES)return{key,status:"rejected",reason:"image too large"};const bytes=new Uint8Array(await r.arrayBuffer());if(!bytes.length||bytes.length>MAX_BYTES)return{key,status:"rejected",reason:"image size invalid"};return{key,status:"ok",data_url:`data:${type};base64,${b64(bytes)}`,bytes:bytes.length,source_url:r.url,image_source:source}}catch(e){return{key,status:"unavailable",reason:e instanceof Error?e.message:String(e)}}}
async function fetchImage(item:Any){const key=clean(item?.key),retailer=clean(item?.retailer).toLowerCase(),barcode=rawDigits(item?.barcode),proof=rawDigits(item?.proof);if(!key)return{key,status:"rejected",reason:"missing key"};let url=clean(item?.image_url),reference=clean(item?.reference_url),source="Verified source image";const strict=retailer.includes("dollar general")||retailer.includes("dollar tree");if(strict&&url&&(!barcode||!proof||!same(barcode,proof)))url="";if(!url||!allowed(url)){const resolved=await resolveExact(item);if(resolved){url=resolved.url;reference=resolved.reference;source=resolved.source}else return{key,status:"unavailable",reason:strict?"no exact UPC image resolved":"no approved image"}}return fetchBytes(key,url,reference,source)}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required"});if(!req.headers.get("authorization"))return json(req,401,{error:"Sign in required"});try{const body=await req.json().catch(()=>({})),items=(Array.isArray(body?.items)?body.items:[]).slice(0,MAX_ITEMS),settled=await Promise.all(items.map(fetchImage)),images=settled.filter(x=>x.status==="ok"),warnings=settled.filter(x=>x.status!=="ok");console.log(JSON.stringify({event:"reseller-image-delivery-v201",requested:items.length,delivered:images.length,warnings:warnings.length,resolver:"exact-upc-pennytree+retailshout+verified-url"}));return json(req,200,{status:"PASS",images,warnings,rule:"Dollar General and Dollar Tree images require exact barcode identity. Scout first resolves the exact retailer + UPC item on PennyTree, then RetailShout exact UPC, or uses a supplied image URL only when its barcode proof matches. Image failure never changes penny/store/resale truth."})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});
