import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Any=Record<string,any>;
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const MAX_ITEMS=8,MAX_BYTES=2_500_000;
const EXACT_HOSTS=["retailshout.com","crazy4couponing.com","pennytree.org","kattydeals.com","openfoodfacts.org","openbeautyfacts.org","openproductsfacts.org","openpetfoodfacts.org","wsuuxqiyujxksfqubpxj.supabase.co"];
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"private, max-age=300","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function clean(v:any){return String(v??"").trim()}
function digits(v:any){return clean(v).replace(/\D/g,"").replace(/^0+/,"")}
function same(a:any,b:any){const x=digits(a),y=digits(b);return !!x&&x===y}
function allowed(url:string){try{const u=new URL(url);if(u.protocol!=="https:")return false;const h=u.hostname.toLowerCase();return EXACT_HOSTS.some(x=>h===x||h.endsWith("."+x))}catch{return false}}
function referer(v:any){try{const u=new URL(clean(v));return u.protocol==="https:"?u.toString():""}catch{return""}}
function b64(bytes:Uint8Array){let out="";for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,Math.min(bytes.length,i+0x8000)));return btoa(out)}
async function fetchImage(item:Any){const key=clean(item?.key),url=clean(item?.image_url),retailer=clean(item?.retailer).toLowerCase(),barcode=digits(item?.barcode),proof=digits(item?.proof);if(!key||!url||!allowed(url))return{key,status:"rejected",reason:"unapproved image host"};if((retailer.includes("dollar general")||retailer.includes("dollar tree"))&&(!barcode||!proof||!same(barcode,proof)))return{key,status:"rejected",reason:"exact barcode proof required"};const headers:any={"user-agent":"Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36 H38ResellerScout/2.0.1","accept":"image/avif,image/webp,image/apng,image/*,*/*;q=0.8","accept-language":"en-US,en;q=0.9"},ref=referer(item?.reference_url);if(ref)headers.referer=ref;try{const r=await fetch(url,{headers,redirect:"follow",signal:AbortSignal.timeout(10000)});if(!r.ok)return{key,status:"unavailable",reason:`HTTP ${r.status}`};const type=(r.headers.get("content-type")||"").split(";")[0].trim().toLowerCase();if(!type.startsWith("image/"))return{key,status:"rejected",reason:`not image (${type||"unknown"})`};const len=Number(r.headers.get("content-length")||0);if(len>MAX_BYTES)return{key,status:"rejected",reason:"image too large"};const bytes=new Uint8Array(await r.arrayBuffer());if(!bytes.length||bytes.length>MAX_BYTES)return{key,status:"rejected",reason:"image size invalid"};return{key,status:"ok",data_url:`data:${type};base64,${b64(bytes)}`,bytes:bytes.length,source_url:r.url}}catch(e){return{key,status:"unavailable",reason:e instanceof Error?e.message:String(e)}}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required"});if(!req.headers.get("authorization"))return json(req,401,{error:"Sign in required"});try{const body=await req.json().catch(()=>({})),items=(Array.isArray(body?.items)?body.items:[]).slice(0,MAX_ITEMS),settled=await Promise.all(items.map(fetchImage)),images=settled.filter(x=>x.status==="ok"),warnings=settled.filter(x=>x.status!=="ok");console.log(JSON.stringify({event:"reseller-image-delivery-v201",requested:items.length,delivered:images.length,warnings:warnings.length}));return json(req,200,{status:"PASS",images,warnings,rule:"Only already-verified exact image URLs from approved Scout sources are fetched. Dollar General and Dollar Tree require matching barcode proof. Image failure never changes penny/store/resale truth."})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});
