const txt=v=>String(v??'').trim();
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clean=s=>txt(s).replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();
const stop=new Set('the a an and or with for of to in on at by from item product products dollar general dg penny remodel upc sku'.split(' '));
const words=s=>new Set(clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!stop.has(x)));
export function identityAgreement(a='',b=''){const A=words(a),B=words(b);if(!A.size||!B.size)return{status:'UNPROVEN',score:0};let hit=0;for(const x of A)if(B.has(x))hit++;const score=hit/Math.min(A.size,B.size);return{status:score>=.5?'MATCH':hit?'WEAK':'MISMATCH',score:Number(score.toFixed(2))}}
export function parseIndicators(html=''){const out=[],seen=new Set(),re=/(\d{11,14})/g;let m;while((m=re.exec(String(html)))){const upc=m[1];if(seen.has(upc))continue;const a=Math.max(0,m.index-180),b=Math.min(String(html).length,m.index+180),ctx=clean(String(html).slice(a,b));if(!/upc|remodel|product|item|beauty|gift|food|frozen|refriger|pot pie/i.test(ctx))continue;seen.add(upc);let name=ctx.replace(upc,' ').replace(/\bUPC\b\s*:?/ig,' ').replace(/\s+/g,' ').trim();if(name.length>150)name=name.slice(-150);out.push({upc,name:name||`Indicator ${upc}`,source:'Penny Puss indicator list'})}return out.slice(0,80)}
export function parseMinnesotaCandidates(html=''){const text=clean(html),out=[],seen=new Set(),re=/([A-Za-z0-9 .#'&-]{3,80}),?\s+(Grand Rapids|Bemidji|Hibbing|Duluth|Virginia|Bovey|Coleraine|Deer River|Cohasset|Eveleth|Chisholm|International Falls|Brainerd|Baxter)[, ]+MN(?:\s+(\d{5}))?/gi;let m;while((m=re.exec(text))){const key=`${m[2].toLowerCase()}|${m[3]||''}`;if(seen.has(key))continue;seen.add(key);out.push({label:`${m[1].trim()} ${m[2]}, MN${m[3]?` ${m[3]}`:''}`.replace(/\s+/g,' '),city:m[2],state:'MN',postal:m[3]||'',source:'Penny Puss Minnesota remodel list',evidence_level:'COMMUNITY SIGNAL'})}return out.slice(0,60)}
export function normalizeProbe(row={},indicator={}){const regular=num(row?.price??row?.regular_price??row?.list_price),effective=num(row?.effective_price??row?.discount_price??row?.sale_price??row?.price),ratio=regular&&effective!=null&&regular>0?effective/regular:null;const upc=txt(row?.upc||row?.barcode||indicator?.upc),sourceName=txt(indicator?.name),liveName=txt(row?.name||row?.title),id=identityAgreement(sourceName,liveName);return{upc,name:liveName||sourceName,source_name:sourceName,live_name:liveName,identity_status:id.status,identity_score:id.score,identity_warning:id.status==='MISMATCH'?'UPC matched but source description conflicts with the live item. Do not use this row as product/photo evidence until independently verified.':'',regular_price:regular,effective_price:effective,markdown_ratio:ratio,in_stock:row?.in_stock===true,available_quantity:num(row?.available_quantity),store_id:txt(row?.store_id),source_url:txt(row?.source_url)}}
export function scoreStore(store={},probes=[],community=false){const usable=probes.filter(p=>p.identity_status!=='MISMATCH');let score=community?30:0,deep=0,moderate=0,cold=false;for(const p of usable){const r=num(p.markdown_ratio);if(r!=null&&r<=.55){score+=18;deep++}else if(r!=null&&r<=.75){score+=8;moderate++}if(/pot pie|frozen|freezer|refriger/i.test(txt(p.name))&&r!=null&&r<=.6){score+=18;cold=true}}if(deep>=3)score+=18;else if(deep>=2)score+=10;if(usable.length>=4)score+=5;score=Math.min(100,score);let label='NO REMODEL SIGNAL';if(score>=80)label='PENNY WINDOW CANDIDATE';else if(score>=60)label='REMODEL LIKELY';else if(score>=35)label='REMODEL POSSIBLE';else if(community)label='COMMUNITY SIGNAL';return{...store,score,label,indicator_hits:deep,moderate_hits:moderate,cold_case_signal:cold,community_signal:community,identity_conflicts:probes.length-usable.length,evidence_level:deep>=2?'LIVE PARTIAL':community?'COMMUNITY SIGNAL':'LIVE PARTIAL',truth:'Remodel score excludes UPC rows whose live description conflicts with the source item. A remodel score is still only a probability signal; physical register scan remains final penny truth.'}}
