import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {parseIndicators,parseMinnesotaCandidates,normalizeProbe,scoreStore} from './core.mjs';
type Any=Record<string,any>;
const TOKEN=Deno.env.get('APIFY_API_TOKEN')||'';
const ACTOR='dromb~dollar-general-scraper-clean';
const INDICATORS='https://pennypuss.com/products-with-upcs-that-i-use-to-search-for-dollar-general-remodels/';
const MN='https://pennypuss.com/dollar-general-free-store-remodel-location-list-for-minnesota/';
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
function cors(r:Request){const o=r.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=180','vary':'Origin'}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function txt(v:any){return String(v??'').trim()}
async function getText(url:string){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 H38ResellerScout/2.4.0','accept-language':'en-US,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()}
async function actor(input:Any,timeout=35000){const u=`https://api.apify.com/v2/acts/${ACTOR}/run-sync-get-dataset-items?token=${encodeURIComponent(TOKEN)}`;const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(timeout)}),p=await r.json().catch(()=>[]);if(!r.ok)throw Error(`Apify DG HTTP ${r.status}`);return Array.isArray(p)?p:[]}
function queryFrom(body:Any){const label=txt(body.location_label);if(/grand rapids/i.test(label))return'Grand Rapids, MN';const stores=Array.isArray(body.nearby_stores)?body.nearby_stores:[];for(const s of stores){const a=txt(s.store_address);const m=a.match(/([A-Za-z .'-]{3,40}),?\s+(MN|Minnesota)\b/i);if(m)return`${m[1].trim()}, MN`}return txt(body.postal||'55744')==='55744'?'Grand Rapids, MN':label||txt(body.postal)}
function communityNear(candidates:Any[],store:Any){const city=txt(store.city).toLowerCase(),postal=txt(store.postal_code);return candidates.some(x=>(postal&&txt(x.postal)===postal)||(city&&txt(x.city).toLowerCase()===city))}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,405,{error:'POST required'});if(!req.headers.get('authorization'))return json(req,401,{error:'Sign in required'});const body=await req.json().catch(()=>({}));let indicators:Any[]=[],community:Any[]=[],warnings:string[]=[];const source=await Promise.allSettled([getText(INDICATORS),getText(MN)]);if(source[0].status==='fulfilled')indicators=parseIndicators(source[0].value);else warnings.push(`Indicator list unavailable: ${source[0].reason}`);if(source[1].status==='fulfilled')community=parseMinnesotaCandidates(source[1].value);else warnings.push(`Minnesota remodel list unavailable: ${source[1].reason}`);if(!TOKEN)return json(req,200,{status:'PARTIAL',engine:'H38_DG_REMODEL_RADAR_V240',provider_status:'CONFIG_REQUIRED',provider_detail:'APIFY_API_TOKEN is not configured; current indicator UPCs and community remodel signals are still available, but store-specific DG prices are not fabricated.',indicator_count:indicators.length,indicators:indicators.slice(0,30),community_candidates:community,stores:[],warnings,truth:'COMMUNITY SIGNAL / indicator intelligence only. A remodel is not official until independently verified; physical register scan remains final penny truth.'});let directory:Any[]=[];try{directory=await actor({operation:'stores',query:queryFrom(body),limit:8},30000)}catch(e){warnings.push(e instanceof Error?e.message:String(e))}directory=directory.filter(x=>x?.record_type==='store'||x?.operation==='stores'||x?.store_id).slice(0,3);const probeSet=indicators.slice(0,4),stores:Any[]=[];for(const s of directory.slice(0,2)){const settled=await Promise.allSettled(probeSet.map(i=>actor({operation:'item',upc:i.upc,store_id:s.store_id},30000))),probes:Any[]=[];settled.forEach((x:any,i)=>{if(x.status==='fulfilled'){const row=x.value.find((r:any)=>r?.record_type==='product'||r?.upc||r?.effective_price!=null);if(row)probes.push(normalizeProbe(row,probeSet[i]))}else warnings.push(`DG ${s.store_id} ${probeSet[i].upc}: ${x.reason?.message||x.reason}`)});const communitySignal=communityNear(community,s);stores.push({...scoreStore(s,probes,communitySignal),probes})}stores.sort((a,b)=>Number(b.score||0)-Number(a.score||0));return json(req,200,{status:stores.length?'PASS':'PARTIAL',engine:'H38_DG_REMODEL_RADAR_V240',provider_status:stores.length?'LIVE':'LIVE_PARTIAL',indicator_count:indicators.length,indicators:indicators.slice(0,30),community_candidates:community,stores,warnings,truth:'Store-specific indicator markdown clusters are probabilistic remodel evidence, not an official Dollar General remodel schedule. Physical register scan remains final penny truth.'})});
