import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const FUNCTION_SLUG='reseller-auto-leads-v065';
const BASE=Deno.env.get('SUPABASE_URL')||'';
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
const FETCH_CAP=96;
const CONCURRENCY=8;
function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=60','vary':'Origin'}}
function json(req:Request,status:number,body:any){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
const txt=(v:any)=>String(v??'').trim();
const digits=(v:any)=>txt(v).replace(/\D/g,'');
const decode=(v:any)=>txt(v).replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;|&#160;/gi,' ').replace(/&#x2F;/gi,'/').replace(/&#(\d+);/g,(_,n)=>{try{return String.fromCodePoint(Number(n))}catch{return' '}});
const strip=(v:any)=>decode(String(v??'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();
function isDg(row:any){return txt(row?.retailer).toLowerCase().includes('dollar general')}
function malformedTitle(v:any){const s=txt(v);return /<\/?a\b|href=|&(?:#\d+|[a-z]+);|https?:\/\/(?:www\.)?dollargeneral\.com\/p\//i.test(s)}
function cleanTitle(v:any){return strip(v).replace(/\b(?:href|src)\s*=\s*["']?https?:\/\/\S+/gi,' ').replace(/https?:\/\/\S+/gi,' ').replace(/\s*[|–-]\s*Dollar General.*$/i,'').replace(/^\$\s*0\.01\s*/,'').replace(/\s+/g,' ').trim().slice(0,220)}
function genericTitle(v:any){const s=cleanTitle(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(!s||s.length<4)return true;return /^(?:permalink|read more|learn more|shop now|click here|details?|view details?|view product|product page|item page|unknown|n a|penny|penny item|penny list|current weekly list|recently pennied|dollar general|dollar general item|dollar general product|dollar general penny item)$/.test(s)}
function usableTitle(v:any){return !malformedTitle(v)&&!genericTitle(v)}
function bestExistingTitle(row:any){for(const v of [row?.source_identity_title,row?.product_name,row?.item_name,row?.name,row?.canonical_title,row?.title,row?.raw_title]){const t=cleanTitle(v);if(usableTitle(t))return t}return''}
function directDgUrls(row:any){const values=[row?.source_item_url,row?.product_url,row?.url,row?.source_url,row?.title,row?.raw_title,row?.canonical_title,row?.description];for(const s of Array.isArray(row?.signal_sources)?row.signal_sources:[]){values.push(s?.item_url,s?.url,s?.source_url)}const joined=decode(values.map(txt).filter(Boolean).join(' ')),out:string[]=[];for(const m of joined.matchAll(/https?:\/\/(?:www\.)?dollargeneral\.com\/p\/[A-Za-z0-9_~:/?#\[\]@!$&'()*+,;=%.-]+/gi)){let u=m[0].replace(/["'<>]+$/g,'').replace(/&(?:quot|amp);.*$/i,'');try{const x=new URL(u);if(x.hostname.toLowerCase().endsWith('dollargeneral.com')&&x.pathname.startsWith('/p/')){x.hash='';u=x.toString();if(!out.includes(u))out.push(u)}}catch{}}return out.slice(0,4)}
function safeImage(v:any,base:string){let raw=decode(v);if(!raw)return'';try{raw=new URL(raw,base).href}catch{return''}if(!/^https:\/\//i.test(raw))return'';if(/(?:logo|favicon|sprite|pixel|tracking|placeholder|blank|spacer|avatar|badge|banner|loading)/i.test(raw))return'';return raw}
function titleFromHtml(html:string){for(const re of [/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:title["']/i,/<h1\b[^>]*>([\s\S]*?)<\/h1>/i,/<title\b[^>]*>([\s\S]*?)<\/title>/i]){const m=html.match(re),t=m?cleanTitle(m[1]):'';if(usableTitle(t))return t}return''}
function imageFromHtml(html:string,base:string){for(const re of [/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)["']/i]){const m=html.match(re),u=m?safeImage(m[1],base):'';if(u)return u}for(const m of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/ig)){try{const data=JSON.parse(decode(m[1])),stack=[data];while(stack.length){const x=stack.pop();if(Array.isArray(x)){stack.push(...x);continue}if(!x||typeof x!=='object')continue;for(const k of ['image','imageUrl','thumbnailUrl']){const v=(x as any)[k];if(typeof v==='string'){const u=safeImage(v,base);if(u)return u}else if(Array.isArray(v))for(const q of v){const raw=typeof q==='string'?q:q?.url||q?.contentUrl;const u=safeImage(raw,base);if(u)return u}else if(v&&typeof v==='object'){const u=safeImage(v.url||v.contentUrl,base);if(u)return u}}for(const v of Object.values(x))if(v&&typeof v==='object')stack.push(v)}}catch{}}return''}
async function fetchPage(url:string){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Mobile Safari/537.36 H38ResellerScout/3.0.13','accept':'text/html,application/xhtml+xml','accept-language':'en-US,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(9000)});if(!r.ok)return null;const type=(r.headers.get('content-type')||'').toLowerCase();if(!type.includes('text/html'))return null;return{url:r.url||url,html:(await r.text()).slice(0,1_500_000)}}
async function recover(row:any){let out={...row};const existing=bestExistingTitle(out);if(existing&&existing!==txt(out.title)){out.raw_title=txt(out.raw_title||out.title);out.title=existing;out.canonical_title=existing;out.title_quality='RESOLVED_EXISTING_EVIDENCE'}const urls=directDgUrls(out);for(const url of urls){try{const p=await fetchPage(url);if(!p)continue;const title=titleFromHtml(p.html),image=imageFromHtml(p.html,p.url);if(title&&(!txt(out.title)||!usableTitle(out.title))){out.raw_title=txt(out.raw_title||out.title);out.title=title;out.canonical_title=title;out.source_identity_title=title;out.source_identity_provider='Dollar General product page';out.source_identity_scope='exact_product_url';out.description_conflict=true;out.title_quality='RESOLVED_DIRECT_PRODUCT'}if(image&&!txt(out.image_url)){out.image_url=image;out.image_source_url=p.url;out.image_source_provider='Dollar General product page';out.image_source_scope='exact_product';out.image_source_proof='direct_dg_product_page_v065'}out.source_item_url=p.url;out.source_item_scope='exact_product';out.source_item_proof='direct_dg_product_url_v065';if(txt(out.image_url)&&usableTitle(out.title))break}catch{}}if(malformedTitle(out.title)){const cleaned=cleanTitle(out.title);if(cleaned&&cleaned!==out.title){out.raw_title=txt(out.raw_title||out.title);out.title=cleaned;out.canonical_title=cleaned}}if(genericTitle(out.title)){out.title_quality='UNRESOLVED';out.name_unresolved=true}else if(!txt(out.title_quality))out.title_quality='RESOLVED';return out}
async function recoverRows(rows:any[]){const out=rows.map(x=>({...x})),targets:number[]=[];for(let i=0;i<out.length&&targets.length<FETCH_CAP;i++)if(isDg(out[i])&&(malformedTitle(out[i]?.title)||genericTitle(out[i]?.title)||!txt(out[i]?.image_url)||!!bestExistingTitle(out[i])&&bestExistingTitle(out[i])!==txt(out[i]?.title)))targets.push(i);let cursor=0,recoveredImages=0,recoveredTitles=0,unresolvedTitles=0;async function worker(){while(cursor<targets.length){const i=targets[cursor++],before=out[i],after=await recover(before);if(!txt(before.image_url)&&txt(after.image_url))recoveredImages++;if(txt(before.title)!==txt(after.title))recoveredTitles++;if(after?.name_unresolved===true)unresolvedTitles++;out[i]=after}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,targets.length||1)},()=>worker()));for(let i=0;i<out.length;i++)if(isDg(out[i])&&genericTitle(out[i]?.title)&&out[i]?.name_unresolved!==true){out[i]={...out[i],title_quality:'UNRESOLVED',name_unresolved:true};unresolvedTitles++}return{rows:out,attempted:targets.length,recoveredImages,recoveredTitles,unresolvedTitles}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,405,{error:'POST required'});const auth=req.headers.get('authorization')||'',apikey=req.headers.get('apikey')||'';if(!auth)return json(req,401,{error:'Sign in required'});try{const body=await req.text(),r=await fetch(`${BASE}/functions/v1/reseller-auto-leads-v064`,{method:'POST',headers:{authorization:auth,apikey,'content-type':'application/json'},body:body||'{}',signal:AbortSignal.timeout(90000)}),p=await r.json().catch(()=>({}));if(!r.ok)return json(req,r.status,{error:p?.error||'Retail Hunt source failed',function_slug:FUNCTION_SLUG});const recovered=await recoverRows(Array.isArray(p?.leads)?p.leads:[]);const dgRows=recovered.rows.filter(isDg),dgImages=dgRows.filter(x=>txt(x.image_url)).length;return json(req,200,{...p,status:p?.status||'PASS',leads:recovered.rows,count:recovered.rows.length,function_slug:FUNCTION_SLUG,adapter_version:'v064+direct-dg-product-recovery-v065-title-quality-v071',dg_direct_product_attempted:recovered.attempted,dg_direct_product_images_recovered:recovered.recoveredImages,dg_direct_product_titles_recovered:recovered.recoveredTitles,dg_unresolved_title_count:recovered.unresolvedTitles,dg_image_count:dgImages,image_rule:'When an upstream Dollar General row contains an exact public DollarGeneral.com product URL, Scout may use that exact page to recover its published title and image. It never guesses an image or treats the product page as proof of local stock or penny price.',title_rule:'Generic navigation labels such as Permalink are never treated as product names. Scout prefers exact identity evidence, then direct Dollar General product-page titles; unresolved names remain explicitly marked unresolved instead of being presented as product identity.',penny_truth_rule:'Physical Dollar General app/UPC/register scan remains final local penny truth.'})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e),function_slug:FUNCTION_SLUG})}});
