from pathlib import Path
p=Path('scripts/verify-field-visit-offline-autofill.js')
s=p.read_text()
s=s.replace("const main=read('native/h38-site-scanner/android-app/app/src/main/java/com/highway38/sitescanner/MainActivity.java');\nconst bridge=", "const main=read('native/h38-site-scanner/android-app/app/src/main/java/com/highway38/sitescanner/MainActivity.java');\nconst nativeCapture=read('native/h38-site-scanner/android-app/app/src/main/java/com/highway38/sitescanner/WalkthroughCaptureActivity.java');\nconst bridge=")
old="for(const s of ['setImportantForAutofill','AutofillManager','requestAutofill(webView)','H38SiteScannerAndroid/0.5.6','MediaStore.ACTION_VIDEO_CAPTURE','MediaStore.EXTRA_DURATION_LIMIT','MediaStore.EXTRA_OUTPUT','pendingFileCapture','pendingCaptureUri','createWalkthroughVideoUri','REQUEST_WALKTHROUGH_CAMERA_PERMISSION','pendingWalkthroughPermissionResume','requestPermissions(','launchWalkthroughVideoCapture','onRequestPermissionsResult','CAPTURE_RECOVERY_URL','persistCaptureTracking','restoreCaptureTracking','recoveredCaptureUri','openRecoveredWalkthroughResponse','confirmRecoveredWalkthroughConsumed'])must(main,s,'Android shell');"
new="for(const s of ['setImportantForAutofill','AutofillManager','requestAutofill(webView)','H38SiteScannerAndroid/0.5.7','pendingFileCapture','WalkthroughCaptureActivity.class','Manifest.permission.CAMERA','Manifest.permission.RECORD_AUDIO','REQUEST_WALKTHROUGH_CAMERA_PERMISSION','pendingWalkthroughPermissionResume','requestPermissions(','launchWalkthroughVideoCapture','onRequestPermissionsResult','CAPTURE_RECOVERY_URL','persistCaptureTracking','restoreCaptureTracking','recoveredCaptureUri','openRecoveredWalkthroughResponse','confirmRecoveredWalkthroughConsumed'])must(main,s,'Android shell');\nfor(const s of ['PreviewView','CameraSelector.DEFAULT_BACK_CAMERA','VideoCapture.withOutput','withAudioEnabled()','FileOutputOptions','getFilesDir()','FileProvider.getUriForFile','Light On','Light Off','enableTorch','Stop & Use Video'])must(nativeCapture,s,'Android in-app walkthrough recorder');\nfor(const s of ['MediaStore.ACTION_VIDEO_CAPTURE','MediaStore.EXTRA_OUTPUT','createWalkthroughVideoUri'])absent(main,s,'retired external camera handoff');"
if old not in s: raise SystemExit('old Android verifier block not found')
s=s.replace(old,new)
s=s.replace("for(const s of [\"versionCode 11\",\"versionName '0.5.6'\",\"androidx.credentials:credentials:1.6.0-beta02\",\"androidx.webkit:webkit:1.14.0\"])must(gradle,s,'Android Gradle');", "for(const s of [\"versionCode 12\",\"versionName '0.5.7'\",\"androidx.credentials:credentials:1.6.0-beta02\",\"androidx.webkit:webkit:1.14.0\",\"androidx.camera:camera-video:1.5.3\",\"androidx.camera:camera-view:1.5.3\"])must(gradle,s,'Android Gradle');")
s=s.replace("'android.permission.RECORD_AUDIO','smallestScreenSize|uiMode']", "'android.permission.RECORD_AUDIO','.WalkthroughCaptureActivity','androidx.core.content.FileProvider','smallestScreenSize|uiMode']")
s=s.replace("androidNativeVideoCapture:true,androidGuaranteedReturnUri:true,androidCameraPermissionResume:true", "androidInAppVideoCapture:true,androidInAppMicrophone:true,androidTorchControl:true,androidPrivateWalkthroughStorage:true,externalCameraHandoff:false,androidCameraPermissionResume:true")
p.write_text(s)
print('PASS — field verifier updated for v0.5.7 in-app camera mic torch')
