import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const BUSINESS_ID="10b85a89-5834-436d-95b0-c6ee2eb335ad";
const BUILD="20260824-quote-agent-canonical-1";
const STORAGE_BUCKET="business-office-files";
const H38_ORIGIN="https://highway38solutions.com";
const ALLOWED_ORIGINS=new Set([H38_ORIGIN,"https://www.highway38solutions.com","https://rkrueth-maker.github.io","http://localhost:8000","http://127.0.0.1:8000"]);
type J=Record<string,any>;
const txt=(v:any,max=12000)=>String(v??"").trim().slice(0,max);
const num=(v:any)=>{const n=Number(v??0);return Number.isFinite(n)?n:0;};
const norm=(v:any)=>txt(v,2000).toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();
const unit=(v:any)=>{const x=norm(v),m:J={ea:"each",each:"each",lf:"linear foot","linear ft":"linear foot","linear foot":"linear foot","linear feet":"linear foot",ft:"foot",foot:"foot",feet:"foot",sf:"square foot","sq ft":"square foot","square foot":"square foot","square feet":"square foot",cy:"cubic yard","cu yd":"cubic yard","cubic yard":"cubic yard",step:"step",steps:"step",ls:"lump sum","lump sum":"lump sum",hr:"hour",hour:"hour",hours:"hour"};return m[x]||x||"each";};
function cors(req:Request):HeadersInit{const o=txt(req.headers.get("origin"),300);return{"access-control-allow-origin":o||"*","access-control-allow-headers":txt(req.headers.get("access-control-request-headers"),500)||"authorization, apikey, content-type, x-client-info, x-h38-request-id","access-control-allow-methods":"GET, POST, OPTIONS","cache-control":"no-store","content-type":"application/json; charset=utf-8","vary":"Origin, Access-Control-Request-Headers"};}
const json=(req:Request,status:number,body:any)=>new Response(JSON.stringify(body),{status,headers:cors(req)});
const bearer=(req:Request)=>{const m=txt(req.headers.get("authorization"),5000).match(/^Bearer\s+(.+)$/i);return m?m[1].trim():"";};
const db=()=>createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
async function readJson(r:Response){const raw=await r.text();try{return raw?JSON.parse(raw):{};}catch{return{status:"FAIL",message:raw.slice(0,1000)};}}
async function authorize(req:Request,businessId:string){const token=bearer(req);if(!token)throw new Error("Supabase Auth session is required.");const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:SERVICE_KEY,"x-client-info":BUILD},signal:AbortSignal.timeout(15000)});const p=await readJson(r);if(!r.ok||!p?.id)throw new Error("Supabase Auth session is invalid or expired.");const s=db(),m=await s.from("business_memberships").select("id,role,status").eq("business_id",businessId).eq("auth_user_id",p.id).eq("status","active").maybeSingle();if(m.error)throw m.error;if(!m.data||!["owner","administrator","staff"].includes(String(m.data.role)))throw new Error("This account cannot build or review quotes for this business.");return{token,userId:String(p.id),role:String(m.data.role),client:s};}
function normalizeLines(value:any){return(Array.isArray(value)?value:[]).filter(x=>txt(x?.description||x?.Description,600)).slice(0,100).map((x:any,i:number)=>{const q=Math.max(0,num(x.quantity??x.Quantity)),rate=Math.max(0,num(x.unitPrice??x.rate??x["Unit Price"]??x.Rate)),extended=num(x.extendedPrice??x.Amount??x.Total)||q*rate;return{quoteLineId:txt(x.quoteLineId||x["Quote Line ID"]||`LINE-${i+1}`,180),description:txt(x.description||x.Description,800),costType:txt(x.costType||x["Cost Type"]||"other",80)||"other",quantity:q,unit:txt(x.unit||x.Unit||"each",80)||"each",unitPrice:rate,rate,extendedPrice:extended,catalogId:txt(x.catalogId||x["Catalog ID"],180),priceSource:txt(x.priceSource||x["Price Source"]||"owner_saved_quote",300),priceStatus:txt(x.priceStatus||x["Price Status"]||"Owner review required",200)};});}
function quoteLines(payload:J){for(const k of ["lines","Quote Lines","quoteLines","Estimate","estimate"])if(Array.isArray(payload?.[k]))return normalizeLines(payload[k]);return[];}
function canonicalLine(line:J){return{id:txt(line.quoteLineId,180),description:txt(line.description,800),quantity:num(line.quantity),unit:unit(line.unit),rate:num(line.unitPrice??line.rate),extended:num(line.extendedPrice)||num(line.quantity)*num(line.unitPrice??line.rate),costType:txt(line.costType,80)};}
async function sha(value:any){const bytes=new TextEncoder().encode(JSON.stringify(value)),digest=new Uint8Array(await crypto.subtle.digest("SHA-256",bytes));return Array.from(digest).map(x=>x.toString(16).padStart(2,"0")).join("");}
async function quoteRecord(s:any,businessId:string,quoteId:string){const r=await s.from("business_records").select("record_key,payload,updated_at").eq("business_id",businessId).eq("collection","quotes").eq("record_key",quoteId).eq("record_status","active").maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error("The saved quote could not be found.");return r.data;}
function requestedLines(body:J,payload:J){const explicit=normalizeLines(body.currentEstimate);return explicit.length?explicit:quoteLines(payload);}
function baselineRequested(body:J,payload:J,lines:J[]){if(body.preserveSavedBaseline===false)return false;if(!lines.length)return false;if(body.forceAiReinterpretation===true)return false;const saved=quoteLines(payload);if(!saved.length)return false;return body.acceptanceMode==="regression"||body.reproductionMode===true||body.preserveSavedBaseline===true||Boolean(payload["Regression Fixture"]||payload["Historical Demo"])||norm(body.currentEstimateSource).includes("saved");}
function sourceAuthority(payload:J){return{actionPictureId:txt(payload["Action Picture ID"]||payload.actionPictureId,220),actionPhotoPath:txt(payload["Action Photo Path"]||payload.actionPhotoPath,1200),renderSourcePath:txt(payload["Prepared Render Source Path"]||payload.preparedRenderSourcePath||payload["Render Source Path"]||payload.renderSourcePath,1200),renderInstructions:txt(payload["Render Instructions"]||payload.renderInstructions,5000)};}
function visualMode(title:string,scope:string,lines:J[]){const x=norm(`${title} ${scope} ${lines.map(l=>l.description).join(" ")}`);if(/\b(electrical|circuit|panel|receptacle|switch|plumbing|piping|hvac|ventilation|duct|framing|structural|insulation|air sealing|engineering|permit|project management|general conditions|survey|soils)\b/.test(x))return"plan_detail";if(/\b(master quote|whole house|complete cabin|house plan)\b/.test(x))return"mixed";return"photo_edit";}
function visibleFacts(lines:J[],scope:string){const facts:string[]=[];for(const l of lines){const q=num(l.quantity);if(q<=0)continue;const desc=txt(l.description,500),u=txt(l.unit,80);facts.push(`${q} ${u} — ${desc}`);}const s=txt(scope,1200);if(/4\s*[- ]?foot\s+(?:wide\s+)?stairs?/i.test(s))facts.push("HARD CONSTRAINT: stairs are 4 feet WIDE; this does not mean four steps.");return Array.from(new Set(facts)).slice(0,60);}
async function fingerprint(quoteId:string,payload:J,title:string,scope:string,lines:J[],directionId:string,source:J){const revision=num(payload.Revision||payload.revision);const canonical={quoteId,revision,title:txt(title,500),scope:txt(scope,8000),measurementNotes:txt(payload["Measurement Notes"]||payload.measurementNotes,8000),selectedDirectionId:txt(directionId,160),source,lines:lines.map(canonicalLine)};return{revision,canonical,fingerprint:await sha(canonical)};}
function manifest(quoteId:string,fp:any,title:string,scope:string,lines:J[],directionId:string,source:J){return{sourceQuoteId:quoteId,quoteRevision:fp.revision,quoteFingerprint:fp.fingerprint,selectedDirectionId:txt(directionId,160),projectTitle:title,scope,actionPictureId:source.actionPictureId,renderSourcePath:source.renderSourcePath||source.actionPhotoPath,exactQuoteLines:lines.map(canonicalLine),visibleWorkFacts:visibleFacts(lines,scope),renderInstructions:source.renderInstructions,visualMode:visualMode(title,scope,lines),generatedBy:BUILD,generatedAt:new Date().toISOString()};}
async function docsForQuote(s:any,businessId:string,quoteId:string,payload:J){const r=await s.from("business_records").select("record_key,payload,updated_at").eq("business_id",businessId).eq("collection","documents").eq("record_status","active").order("updated_at",{ascending:false}).limit(500);if(r.error)throw r.error;const action=txt(payload["Action Picture ID"]||payload.actionPictureId,220),paths=new Set([txt(payload["Prepared Render Source Path"]||payload.preparedRenderSourcePath,1200),txt(payload["Render Source Path"]||payload.renderSourcePath,1200),txt(payload["Action Photo Path"]||payload.actionPhotoPath,1200)].filter(Boolean));const out=(r.data||[]).filter((row:J)=>{const p=row.payload||{};return txt(row.record_key)===action||txt(p["Document ID"]||p.documentId)===action||paths.has(txt(p["Storage Path"]||p.storagePath,1200))||(txt(p["Source ID"]||p.sourceId,220)===quoteId&&["quote","quote reference","quote render"].includes(norm(p["Source Type"]||p.sourceType)));}).map((row:J)=>{const p=row.payload||{};return{documentId:txt(p["Document ID"]||p.documentId||row.record_key,220),role:txt(p["Historical Asset Role"]||p.historicalAssetRole||p["Evidence Type"]||p.evidenceType||p["Source Type"]||p.sourceType,240),mimeType:txt(p["Mime Type"]||p.mimeType,120),bucket:txt(p["Storage Bucket"]||p.storageBucket||STORAGE_BUCKET,120),path:txt(p["Storage Path"]||p.storagePath,1200),actionPicture:Boolean(p["Action Picture"]||p.actionPicture),sourceType:txt(p["Source Type"]||p.sourceType,120),updatedAt:row.updated_at};});return out;}
async function signedRefs(s:any,refs:J[]){const out=[];for(const ref of refs.slice(0,12)){let url="";if(ref.path){const r=await s.storage.from(ref.bucket||STORAGE_BUCKET).createSignedUrl(ref.path,1800);if(!r.error)url=txt(r.data?.signedUrl,4000);}out.push({...ref,url});}return out;}
function chooseVisualRefs(mode:string,refs:J[]){const action=refs.find(r=>r.actionPicture)||refs.find(r=>norm(r.role).includes("before"));if(mode==="photo_edit")return action?[action]:refs.filter(r=>String(r.mimeType).startsWith("image/")).slice(0,3);const scored=[...refs].sort((a,b)=>{const score=(r:J)=>{const x=norm(`${r.role} ${r.path}`);return(x.includes("plan")?5:0)+(x.includes("floor")?4:0)+(x.includes("elevation")?3:0)+(x.includes("diagram")?4:0)+(x.includes("exterior")?2:0)+(r.actionPicture?1:0);};return score(b)-score(a);});return scored.slice(0,5);}
async function delegateLegacy(req:Request,slug:string,body:J,timeoutMs:number){const token=bearer(req),r=await fetch(`${SUPABASE_URL}/functions/v1/${slug}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,apikey:SERVICE_KEY,"content-type":"application/json",Origin:H38_ORIGIN,"x-client-info":BUILD,"x-h38-request-id":txt(body.requestId||crypto.randomUUID(),180)},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)});const p=await readJson(r);if(!r.ok||p?.status!=="PASS")throw new Error(txt(p?.message||`${slug} failed (${r.status}).`,1400));return p;}
function asDraft(title:string,scope:string,lines:J[],note:string){return{projectTitle:title,scope,confidence:"high",photoObservations:[],measurementBasis:[],assumptions:[],missingInformation:[],suggestedLines:lines.map(l=>({quoteLineId:l.quoteLineId,description:l.description,costType:["material","labor","equipment","other"].includes(norm(l.costType))?norm(l.costType):"other",quantity:l.quantity,unit:l.unit,rate:l.unitPrice,unitPrice:l.unitPrice,extendedPrice:l.extendedPrice,catalogId:l.catalogId,priceSource:l.priceSource,priceStatus:l.priceStatus,confidence:"high",rationale:`${note} Owner review still controls Save/Send.`})),pricingSummary:note};}
function compareLines(base:J[],candidate:J[]){const key=(l:J)=>txt(l.quoteLineId,180)||`${norm(l.description)}|${unit(l.unit)}`;const map=new Map(candidate.map(l=>[key(l),l])),missing:any[]=[],drift:any[]=[];for(const b of base){const c=map.get(key(b));if(!c){missing.push({quoteLineId:b.quoteLineId,description:b.description});continue;}if(norm(b.description)!==norm(c.description)||num(b.quantity)!==num(c.quantity)||unit(b.unit)!==unit(c.unit)||num(b.unitPrice)!==num(c.unitPrice))drift.push({quoteLineId:b.quoteLineId,baseline:canonicalLine(b),candidate:canonicalLine(c)});map.delete(key(b));}return{baselineCount:base.length,candidateCount:candidate.length,coverage:base.length?((base.length-missing.length)/base.length):1,missing,unexpected:Array.from(map.values()).map(canonicalLine),drift};}
function deterministicOptions(title:string,scope:string,lines:J[],fp:any,manifestBase:J){const base={id:"base",name:"Current owner-reviewed scope",tier:"base",summary:"Exact canonical quote baseline.",quantityLabel:"Canonical quote",quantity:1,quantityUnit:"project",quantityRequired:false,differences:[],visualPrompt:"Render exactly the canonical quote and Visual Quantity Manifest.",suggestedLines:lines.map(l=>({...l,quantityMode:"fixed",rate:l.unitPrice,ownerReviewRequired:true})),pricingSummary:"Saved owner-reviewed baseline; Save/Send remains owner controlled.",quoteFingerprint:fp.fingerprint,visualQuantityManifest:{...manifestBase,selectedDirectionId:"base"}};const x=norm(`${title} ${scope} ${lines.map(l=>l.description).join(" ")}`),alts:any[]=[];const add=(id:string,name:string,replace:RegExp,replacement:string)=>{const changed=lines.map(l=>replace.test(l.description)?{...l,description:l.description.replace(replace,replacement),unitPrice:0,rate:0,catalogId:"",priceSource:"manual_required",priceStatus:"Owner review required",quantityMode:"fixed"}:{...l,quantityMode:"fixed",rate:l.unitPrice});if(changed.some((l,i)=>l.description!==lines[i].description))alts.push({id,name,tier:alts.length?"premium":"upgrade",summary:`Same requested project with ${name.toLowerCase()}.`,quantityLabel:"Canonical quote",quantity:1,quantityUnit:"project",quantityRequired:false,differences:[`Visible material/finish choice: ${name}`],visualPrompt:`Preserve every canonical quantity and geometry. Show only the visible material/finish change for ${name}.`,suggestedLines:changed,pricingSummary:"Changed material pricing intentionally left for owner review.",ownerReviewRequired:true});};
 if(/pressure treated|pressure-treated/.test(x))add("upgrade-composite","Composite decking upgrade",/pressure[- ]treated/ig,"composite");
 if(/flexible edging|plastic edging/.test(x))add("upgrade-metal-edging","Metal edging upgrade",/(flexible|plastic) edging/ig,"metal edging");
 if(/metal edging/.test(x))add("upgrade-stone-border","Stone/paver border upgrade",/metal edging/ig,"stone/paver border");
 if(/laminate countertop/.test(x))add("upgrade-quartz","Quartz countertop upgrade",/laminate countertop/ig,"quartz countertop");
 return{decisionTitle:alts.length?"Project choices":"Canonical project direction",decisionReason:alts.length?"Only visibly meaningful alternatives that accomplish the same requested project are shown.":"No unrelated upgrade is being invented for this scope.",defaultDirectionId:"base",directions:[base,...alts].slice(0,4),optionsGenerated:alts.length>0,optionsSuppressed:alts.length===0,suppressionReason:alts.length?"":"No safe, visibly meaningful deterministic alternative was justified by the canonical quote."};}
async function build(req:Request,body:J,auth:any,row:J){const p=row.payload||{},quoteId=txt(body.quoteId||row.record_key,220),title=txt(body.projectTitle||p["Project Title"]||p.projectTitle,400),scope=txt(body.scope||p.Scope||p.scope,9000),lines=requestedLines(body,p),source=sourceAuthority(p),direction=txt(body.selectedDirectionId||p["Selected Direction ID"]||p.selectedDirectionId,160),fp=await fingerprint(quoteId,p,title,scope,lines,direction,source),vqm=manifest(quoteId,fp,title,scope,lines,direction,source);if(baselineRequested(body,p,lines)){const saved=quoteLines(p),cmp=compareLines(saved,lines);return{status:"PASS",classification:cmp.missing.length||cmp.unexpected.length||cmp.drift.length?"FAIL":"CLEAN",provider:"owner-reviewed-baseline",model:"deterministic",serverBuild:BUILD,quoteId,revision:fp.revision,quoteFingerprint:fp.fingerprint,visualQuantityManifest:vqm,draft:asDraft(title,scope,lines,"Reproduced deterministically from the saved owner-reviewed estimate."),baselineComparison:cmp,preservedSavedBaseline:true,providerCallSkipped:true,ownerReviewRequired:true,externalActionOccurred:false,automaticApproval:false,automaticCustomerSending:false,automaticPurchase:false,automaticPayment:false,automaticScheduling:false};}
 const legacy=await delegateLegacy(req,"h38-quote-ai",{action:"buildQuote",...body,businessId:body.businessId,quoteId,projectTitle:title,scope,currentEstimate:lines,preserveSavedBaseline:false,clientRuntimeBuild:BUILD},70000),draftLines=normalizeLines((legacy.draft?.suggestedLines||[]).map((l:J,i:number)=>({...l,quoteLineId:l.quoteLineId||`AI-${i+1}`,unitPrice:l.rate}))),outLines=draftLines.length?draftLines:lines,outFp=await fingerprint(quoteId,p,title,scope,outLines,direction,source),outManifest=manifest(quoteId,outFp,title,scope,outLines,direction,source);return{...legacy,status:"PASS",classification:"CLEAN",serverBuild:BUILD,legacyServerBuild:legacy.serverBuild,quoteFingerprint:outFp.fingerprint,visualQuantityManifest:outManifest,preservedSavedBaseline:false,providerCallSkipped:false,ownerReviewRequired:true,externalActionOccurred:false};}
async function prepareVisual(body:J,row:J,auth:any){const p=row.payload||{},quoteId=txt(body.quoteId||row.record_key,220),title=txt(body.projectTitle||p["Project Title"]||p.projectTitle,400),scope=txt(body.scope||p.Scope||p.scope,9000),lines=requestedLines(body,p),source=sourceAuthority(p),direction=txt(body.selectedDirectionId||p["Selected Direction ID"]||p.selectedDirectionId,160),fp=await fingerprint(quoteId,p,title,scope,lines,direction,source),vqm=manifest(quoteId,fp,title,scope,lines,direction,source),refs=chooseVisualRefs(vqm.visualMode,await docsForQuote(auth.client,body.businessId,quoteId,p)),signed=await signedRefs(auth.client,refs);return{status:"PASS",classification:"CLEAN",serverBuild:BUILD,quoteId,quoteFingerprint:fp.fingerprint,visualQuantityManifest:vqm,visualMode:vqm.visualMode,sourceAuthority:source,sourceReferences:signed,renderEligible:vqm.visualMode==="photo_edit"&&signed.some((r:J)=>r.actionPicture||norm(r.role).includes("before")),planDetailRequired:vqm.visualMode!=="photo_edit",ownerReviewRequired:true,externalActionOccurred:false,automaticApproval:false,automaticCustomerSending:false,automaticPurchase:false,automaticPayment:false,automaticScheduling:false};}
async function render(req:Request,body:J,row:J,auth:any){const plan=await prepareVisual(body,row,auth);if(plan.visualMode!=="photo_edit")return{...plan,renderStatus:"PLAN_DETAIL_AUTHORITY",renderedConcepts:[],message:"A plan/detail/reference visual is authoritative for this trade; no fake photorealistic completion image was generated."};if(!plan.renderEligible)return{...plan,renderStatus:"NO_ACTION_PICTURE",renderedConcepts:[],message:"A real Action Picture/before image is required before photorealistic editing."};const p=row.payload||{},lines=requestedLines(body,p),legacy=await delegateLegacy(req,"h38-quote-ai",{action:"renderConcept",...body,businessId:body.businessId,quoteId:body.quoteId,projectTitle:body.projectTitle||p["Project Title"],scope:body.scope||p.Scope,currentEstimate:lines,suggestedLines:lines,notes:[txt(p["Render Instructions"]||p.renderInstructions,5000),`VISUAL QUANTITY MANIFEST (hard constraints): ${JSON.stringify(plan.visualQuantityManifest)}`].filter(Boolean).join("\n\n"),clientRuntimeBuild:BUILD},145000);const concepts=Array.isArray(legacy.renderedConcepts)?legacy.renderedConcepts.map((c:J)=>({...c,quoteFingerprint:plan.quoteFingerprint,visualQuantityManifest:plan.visualQuantityManifest,selectedDirectionId:txt(body.selectedDirectionId,160)})):[];if(concepts.length){const latest=await auth.client.from("business_records").select("record_key,payload,updated_at").eq("business_id",body.businessId).eq("collection","documents").eq("record_status","active").order("updated_at",{ascending:false}).limit(40);if(!latest.error){const doc=(latest.data||[]).find((r:J)=>norm(r.payload?.["Source Type"]||r.payload?.sourceType)==="quote render"&&txt(r.payload?.["Source ID"]||r.payload?.sourceId,220)===txt(body.quoteId,220));if(doc){const patched={...(doc.payload||{}),"Quote Fingerprint":plan.quoteFingerprint,"Quote Revision":plan.visualQuantityManifest.quoteRevision,"Selected Direction ID":txt(body.selectedDirectionId||"base",160),"Visual Quantity Manifest":plan.visualQuantityManifest,"Exact Quote Lines":plan.visualQuantityManifest.exactQuoteLines,"Render Instructions":plan.visualQuantityManifest.renderInstructions,"Quote Agent Build":BUILD,"Generation Timestamp":new Date().toISOString()};await auth.client.from("business_records").update({payload:patched,updated_by:auth.userId,updated_at:new Date().toISOString()}).eq("business_id",body.businessId).eq("collection","documents").eq("record_key",doc.record_key).eq("record_status","active");}}}return{status:"PASS",classification:"CLEAN",serverBuild:BUILD,legacyServerBuild:legacy.serverBuild,quoteFingerprint:plan.quoteFingerprint,visualQuantityManifest:plan.visualQuantityManifest,visualMode:plan.visualMode,renderStatus:concepts.length?"PASS":"FAIL",renderedConcepts:concepts,ownerReviewRequired:true,externalActionOccurred:false,automaticApproval:false,automaticCustomerSending:false,automaticPurchase:false,automaticPayment:false,automaticScheduling:false};}
async function options(body:J,row:J,auth:any){const p=row.payload||{},quoteId=txt(body.quoteId||row.record_key,220),title=txt(body.projectTitle||p["Project Title"]||p.projectTitle,400),scope=txt(body.scope||p.Scope||p.scope,9000),lines=requestedLines(body,p),source=sourceAuthority(p),fp=await fingerprint(quoteId,p,title,scope,lines,"base",source),vqm=manifest(quoteId,fp,title,scope,lines,"base",source);return{status:"PASS",classification:"CLEAN",serverBuild:BUILD,quoteId,quoteFingerprint:fp.fingerprint,...deterministicOptions(title,scope,lines,fp,vqm),ownerReviewRequired:true,externalActionOccurred:false,automaticApproval:false,automaticCustomerSending:false,automaticPurchase:false,automaticPayment:false,automaticScheduling:false};}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return json(req,200,{status:"PASS",preflight:true,serverBuild:BUILD});if(req.method==="GET")return json(req,200,{status:"PASS",service:"h38-quote-agent",serverBuild:BUILD,canonicalQuoteAuthority:true,savedBaselineDeterministic:true,visualQuantityManifest:true,quoteFingerprint:true,tradeAppropriateVisualMode:true,deterministicBaseDirection:true,ownerReviewRequired:true,automaticApproval:false,automaticCustomerSending:false});if(req.method!=="POST")return json(req,405,{status:"FAIL",message:"POST required",serverBuild:BUILD});let body:J={};try{body=await req.json();}catch{return json(req,400,{status:"FAIL",message:"JSON body required",serverBuild:BUILD});}const businessId=txt(body.businessId||BUSINESS_ID,120),quoteId=txt(body.quoteId,220);try{const origin=txt(req.headers.get("origin"),300);if(origin&&!ALLOWED_ORIGINS.has(origin))return json(req,403,{status:"FAIL",message:`Quote Agent origin is not approved: ${origin}`,serverBuild:BUILD});if(!businessId||!quoteId)throw new Error("Business and saved quote are required.");const auth=await authorize(req,businessId),row=await quoteRecord(auth.client,businessId,quoteId),action=txt(body.action||"buildQuote",80);let result:any;if(action==="buildQuote")result=await build(req,{...body,businessId,quoteId},auth,row);else if(action==="options")result=await options({...body,businessId,quoteId},row,auth);else if(action==="prepareVisual")result=await prepareVisual({...body,businessId,quoteId},row,auth);else if(action==="renderQuote")result=await render(req,{...body,businessId,quoteId},row,auth);else throw new Error(`Unsupported Quote Agent action: ${action}`);return json(req,200,result);}catch(error){const message=txt(error instanceof Error?error.message:error,1600)||"Quote Agent failed.";return json(req,/auth|member|role/i.test(message)?401:500,{status:"FAIL",classification:"FAIL",message,serverBuild:BUILD,ownerReviewRequired:true,externalActionOccurred:false,automaticApproval:false,automaticCustomerSending:false,automaticPurchase:false,automaticPayment:false,automaticScheduling:false});}});
