import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const ALLOWED_ORIGINS=new Set([
  "https://highway38solutions.com",
  "https://www.highway38solutions.com",
  "https://rkrueth-maker.github.io",
  "http://localhost:8000",
  "http://127.0.0.1:8000",
]);
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SUPABASE_SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const OPENAI_MODEL=Deno.env.get("OPENAI_QUOTE_MODEL")||"gpt-5-mini-2025-08-07";
const BUILD="20260821-quote-options-directions-1";
const MAX_PRICE_ROWS=140;
type JsonObject=Record<string,unknown>;
function clean(value:unknown,max=4000){return String(value??"").replace(/Bearer\s+[A-Za-z0-9._-]+/gi,"Bearer [REDACTED]").slice(0,max);}
function number(value:unknown){const n=Number(value??0);return Number.isFinite(n)?n:0;}
function normalize(value:unknown){return clean(value,1200).toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function normalizeUnit(value:unknown){const x=normalize(value);const map:Record<string,string>={ea:"each",each:"each",lf:"linear foot","linear ft":"linear foot","linear foot":"linear foot","linear feet":"linear foot",ft:"foot",foot:"foot",feet:"foot",sf:"square foot","square foot":"square foot","square feet":"square foot",cy:"cubic yard","cubic yard":"cubic yard","cubic yards":"cubic yard",hr:"hour",hour:"hour",hours:"hour",ls:"lump sum","lump sum":"lump sum"};return map[x]||x;}
function origin(request:Request){return String(request.headers.get("origin")||"").trim().replace(/\/+$/,'');}
function cors(request:Request):HeadersInit{const requested=String(request.headers.get("access-control-request-headers")||"").trim();return{"access-control-allow-origin":origin(request)||"*","access-control-allow-headers":requested||"authorization, apikey, content-type, x-client-info, x-h38-request-id","access-control-allow-methods":"GET, POST, OPTIONS","cache-control":"no-store","content-type":"application/json; charset=utf-8","vary":"Origin, Access-Control-Request-Headers"};}
function json(request:Request,status:number,payload:unknown){return new Response(JSON.stringify(payload),{status,headers:cors(request)});}
function bearer(request:Request){const match=String(request.headers.get("authorization")||"").match(/^Bearer\s+(.+)$/i);return match?match[1].trim():"";}
async function readJson(response:Response):Promise<JsonObject>{const raw=await response.text();if(!raw)return{};try{const parsed=JSON.parse(raw);return parsed&&typeof parsed==="object"?parsed:{};}catch(_){return{};}}
function service(){if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)throw new Error("Supabase service configuration is unavailable.");return createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
async function user(request:Request){const token=bearer(request);if(!token)throw new Error("Supabase Auth session is required.");const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:SUPABASE_SERVICE_ROLE_KEY,"x-client-info":BUILD},signal:AbortSignal.timeout(15000)});const payload=await readJson(response);if(!response.ok||typeof payload.id!=="string"||!payload.id)throw new Error("Supabase Auth session is invalid or expired.");return{id:String(payload.id)};}
async function membership(client:ReturnType<typeof service>,userId:string,businessId:string){const{data,error}=await client.from("business_memberships").select("id,role,status").eq("business_id",businessId).eq("auth_user_id",userId).eq("status","active").maybeSingle();if(error)throw error;if(!data)throw new Error("The signed-in account is not an active member of this business.");if(!["owner","administrator","staff"].includes(String(data.role)))throw new Error("This role cannot build quote options.");return data;}
function behaviorClass(title:string,scope:string){const x=normalize(`${title} ${scope}`);if(/\b(retaining wall|retainer wall|segmental wall|block wall)\b/.test(x))return"retaining-wall";if(/\bgarage|shop\b/.test(x))return"garage";if(/\b(border|edging|landscape edge|flower garden|garden bed)\b/.test(x))return"landscape-border";return"general";}
function words(value:string){return new Set(normalize(value).split(" ").filter(word=>word.length>2&&!new Set(["the","and","for","with","from","into","work","install","installation","labor","material","materials","allowance","project"]).has(word)));}
function scoreRow(row:JsonObject,needle:Set<string>){const hay=words(`${clean(row.category,200)} ${clean(row.description,600)} ${clean(row.item_code,160)} ${clean(row.source_note,600)}`);let score=0;needle.forEach(word=>{if(hay.has(word))score+=1;});if(/^OPTIONAL/i.test(clean(row.description,600)))score+=1;return score;}
async function priceBook(client:ReturnType<typeof service>,businessId:string,title:string,scope:string,baseDraft:JsonObject){const{data,error}=await client.from("price_book_items").select("id,item_code,category,description,unit,unit_cost,source_type,source_note,approval_status,updated_at").eq("business_id",businessId).eq("active",true).order("updated_at",{ascending:false}).limit(250);if(error)throw error;const baseLines=Array.isArray(baseDraft?.suggestedLines)?baseDraft.suggestedLines:[];const needle=words(`${title} ${scope} ${baseLines.map((line:any)=>clean(line?.description,400)).join(" ")}`);return(data||[]).map((row:JsonObject)=>({...row,_score:scoreRow(row,needle)})).sort((a:any,b:any)=>number(b._score)-number(a._score)).slice(0,MAX_PRICE_ROWS).map((row:any)=>({catalogId:row.id,itemCode:row.item_code,category:row.category,description:row.description,unit:row.unit,rate:row.unit_cost,sourceType:row.source_type,sourceNote:row.source_note,approvalStatus:row.approval_status,updatedAt:row.updated_at}));}
function schema(){return{type:"object",additionalProperties:false,required:["decisionTitle","decisionReason","defaultDirectionId","directions"],properties:{decisionTitle:{type:"string"},decisionReason:{type:"string"},defaultDirectionId:{type:"string"},directions:{type:"array",minItems:1,maxItems:4,items:{type:"object",additionalProperties:false,required:["id","name","tier","summary","quantityLabel","quantity","quantityUnit","quantityRequired","differences","visualPrompt","suggestedLines","pricingSummary"],properties:{id:{type:"string"},name:{type:"string"},tier:{type:"string",enum:["base","upgrade","premium","alternate"]},summary:{type:"string"},quantityLabel:{type:"string"},quantity:{type:"number"},quantityUnit:{type:"string"},quantityRequired:{type:"boolean"},differences:{type:"array",items:{type:"string"}},visualPrompt:{type:"string"},suggestedLines:{type:"array",items:{type:"object",additionalProperties:false,required:["description","costType","quantityMode","quantity","unit","rate","catalogId","priceSource","confidence","rationale"],properties:{description:{type:"string"},costType:{type:"string",enum:["material","labor","equipment","other"]},quantityMode:{type:"string",enum:["decision","fixed"]},quantity:{type:"number"},unit:{type:"string"},rate:{type:"number"},catalogId:{type:"string"},priceSource:{type:"string",enum:["price_book","web_research","manual_required"]},confidence:{type:"string",enum:["low","medium","high"]},rationale:{type:"string"}}}},pricingSummary:{type:"string"}}}}}};}
function outputText(payload:JsonObject){if(typeof payload.output_text==="string")return payload.output_text;for(const item of Array.isArray(payload.output)?payload.output:[]){if(!item||typeof item!=="object")continue;for(const part of Array.isArray((item as JsonObject).content)?(item as JsonObject).content as unknown[]:[]){if(part&&typeof part==="object"&&(part as JsonObject).type==="output_text"&&typeof(part as JsonObject).text==="string")return String((part as JsonObject).text);}}return"";}
function instructions(klass:string){return[
  "Create an owner-review quote decision set for Highway 38 Solutions from one real project scope.",
  "Return 2 to 4 viable execution directions when the project genuinely has a material, finish, system, quality, or feature choice. If the scope is already fully fixed, return one locked/base direction rather than inventing alternatives.",
  "A direction is an ALTERNATIVE way to accomplish the SAME requested project, not unrelated extra work.",
  "Keep project scope authority limited to projectTitle, scope, ownerWorkRequest, baseDraft, currentEstimate, structured measurements, and the supplied price book.",
  "Never invent site dimensions. If a project quantity is missing, set quantityRequired=true, quantity=0, choose the correct quantityUnit, and give positive owner-review unit rates when defensible. The owner can enter that quantity later.",
  "For lines driven by the owner-entered decision quantity, set quantityMode=decision. For mobilization, fixed disposal, permits, or other fixed lines that truly belong to that direction, set quantityMode=fixed.",
  "Use owner-approved Price Book rows first. For a price_book line, return its exact catalogId and compatible unit. If no safe relevant Price Book row exists, use web_search to research a defensible current regional planning rate for Grand Rapids / Itasca County, Minnesota and mark it web_research with low or medium confidence. If a defensible rate is unavailable, return 0 and manual_required.",
  "Keep material and labor separate when they are meaningfully separate costs. Do not hide all costs in a single vague line when a real choice depends on material/system differences.",
  "Every visualPrompt must describe ONLY the visible change for that direction and preserve the existing property geometry, permanent structures and camera viewpoint.",
  "Do not claim engineering approval, permit approval, code compliance, exact structural capacity, or completed work.",
  "All directions are internal planning tools until the owner selects and reviews one. Never approve, send, purchase, pay, schedule or authorize work automatically.",
  klass==="landscape-border"?"LANDSCAPE BORDER behavior: vary viable edging/border material or finish systems supported by the scope (for example flexible edging, metal edging, paver/stone edging) only when those alternatives are actually suitable; keep soil, weed/tree cleanup and other requested work common unless a direction genuinely changes it.":"",
  klass==="garage"?"GARAGE behavior: preserve the actual garage scope. Alternatives may vary finish/material/system grade or optional scope explicitly supported by the project; never inject drywall, insulation, doors, electrical, storage or other garage work unless the project scope/evidence supports it.":"",
  klass==="retaining-wall"?"RETAINING WALL behavior: alternatives may vary viable wall material/system/finish while preserving the requested wall purpose and known geometry. Drainage, base preparation and structural/engineering unknowns must remain visible; never invent wall height, loading or reinforcement.":"",
].filter(Boolean).join(" ");}
function catalogMatch(line:JsonObject,prices:JsonObject[]){const id=clean(line.catalogId,160);if(!id)return null;return prices.find(row=>clean(row.catalogId,160)===id)||null;}
function sanitizeDirections(result:JsonObject,prices:JsonObject[]){const raw=Array.isArray(result.directions)?result.directions:[];const directions=raw.slice(0,4).map((item,index)=>{const direction=item&&typeof item==="object"?item as JsonObject:{};const quantity=Math.max(0,number(direction.quantity));const quantityUnit=clean(direction.quantityUnit,80)||"each";const lines=(Array.isArray(direction.suggestedLines)?direction.suggestedLines:[]).slice(0,30).map((entry,lineIndex)=>{const line=entry&&typeof entry==="object"?entry as JsonObject:{};let rate=Math.max(0,number(line.rate));let source=clean(line.priceSource,40);let catalogId=clean(line.catalogId,160);const matched=catalogMatch(line,prices);if(source==="price_book"){if(matched&&number(matched.rate)>0&&normalizeUnit(matched.unit)===normalizeUnit(line.unit)){rate=number(matched.rate);catalogId=clean(matched.catalogId,160);}else{source="manual_required";catalogId="";}}
      const quantityMode=clean(line.quantityMode,40)==="fixed"?"fixed":"decision";let lineQty=Math.max(0,number(line.quantity));if(quantityMode==="decision"&&quantity>0)lineQty=quantity;if(quantityMode==="fixed"&&lineQty<=0)lineQty=1;return{description:clean(line.description,500)||`Direction line ${lineIndex+1}`,costType:["material","labor","equipment","other"].includes(clean(line.costType,40))?clean(line.costType,40):"other",quantityMode,quantity:lineQty,unit:clean(line.unit,80)||quantityUnit,rate,catalogId,priceSource:["price_book","web_research","manual_required"].includes(source)?source:"manual_required",confidence:["low","medium","high"].includes(clean(line.confidence,40))?clean(line.confidence,40):"low",rationale:clean(line.rationale,1000),ownerReviewRequired:true};});return{id:clean(direction.id,100)||`direction-${index+1}`,name:clean(direction.name,180)||`Direction ${index+1}`,tier:["base","upgrade","premium","alternate"].includes(clean(direction.tier,40))?clean(direction.tier,40):index===0?"base":"alternate",summary:clean(direction.summary,1000),quantityLabel:clean(direction.quantityLabel,240)||"Project quantity",quantity,quantityUnit,quantityRequired:Boolean(direction.quantityRequired)||quantity<=0,differences:(Array.isArray(direction.differences)?direction.differences:[]).map(x=>clean(x,500)).filter(Boolean).slice(0,8),visualPrompt:clean(direction.visualPrompt,1800),suggestedLines:lines,pricingSummary:clean(direction.pricingSummary,1200),ownerReviewRequired:true};}).filter(direction=>direction.suggestedLines.length||direction.visualPrompt||direction.summary);const defaultId=directions.some(d=>d.id===clean(result.defaultDirectionId,100))?clean(result.defaultDirectionId,100):(directions[0]?.id||"");return{decisionTitle:clean(result.decisionTitle,240)||"Choose a project direction",decisionReason:clean(result.decisionReason,1000)||"Choose the material, finish or system direction that best matches the intended result, then confirm any missing project quantity.",defaultDirectionId:defaultId,directions};}
async function callModel(context:JsonObject,klass:string){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:OPENAI_MODEL,store:false,tools:[{type:"web_search"}],input:[{role:"developer",content:[{type:"input_text",text:instructions(klass)}]},{role:"user",content:[{type:"input_text",text:JSON.stringify(context)}]}],text:{format:{type:"json_schema",name:"h38_quote_directions",strict:true,schema:schema()},verbosity:"low"}}),signal:AbortSignal.timeout(135000)});const payload=await readJson(response);if(!response.ok){const err=payload.error&&typeof payload.error==="object"?payload.error as JsonObject:{};throw new Error(clean(err.message||`OpenAI option request failed (${response.status}).`,1200));}const raw=outputText(payload);if(!raw)throw new Error("OpenAI returned no quote directions.");try{const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=="object")throw new Error("invalid");return parsed as JsonObject;}catch(_){throw new Error("OpenAI returned unreadable quote directions.");}}
async function writeProof(client:ReturnType<typeof service>,businessId:string,userId:string,quoteId:string,klass:string,count:number,requestId:string){try{await client.from("business_proof_log").insert({business_id:businessId,actor_user_id:userId,action_type:"BUILD_QUOTE_DIRECTIONS",entity_type:"Quote",entity_id:quoteId,result:"PASS",details:{quoteId,behaviorClass:klass,directionCount:count,requestId,serverBuild:BUILD,ownerReviewRequired:true,automaticApproval:false,automaticCustomerSending:false,automaticFinancialAction:false},external_action_occurred:false});}catch(_){} }
Deno.serve(async(request:Request)=>{
  if(request.method==="OPTIONS")return json(request,200,{status:"PASS",preflight:true,serverBuild:BUILD});
  if(request.method==="GET")return json(request,200,{status:"PASS",service:"h38-quote-options",serverBuild:BUILD,projectDirections:true,quantityDecisionSupport:true,landscapeBorderBehavior:true,garageBehavior:true,retainingWallBehavior:true,visualDirectionPrompts:true,ownerReviewRequired:true,automaticApproval:false,automaticSending:false});
  if(request.method!=="POST")return json(request,405,{status:"FAIL",message:"Method not allowed.",serverBuild:BUILD});
  let body:JsonObject={};try{body=await request.json();}catch(_){return json(request,400,{status:"FAIL",message:"Request body must be JSON.",serverBuild:BUILD});}
  const requestId=clean(body.requestId||request.headers.get("x-h38-request-id")||crypto.randomUUID(),180),businessId=clean(body.businessId,100),quoteId=clean(body.quoteId,160);
  try{
    const requestOrigin=origin(request);if(!ALLOWED_ORIGINS.has(requestOrigin))return json(request,403,{status:"FAIL",message:`Quote options origin is not approved: ${requestOrigin||"missing origin"}.`,serverBuild:BUILD,requestId});
    const signed=await user(request),client=service();if(!businessId||!quoteId)throw new Error("Business and saved quote are required before building options.");await membership(client,signed.id,businessId);if(!OPENAI_API_KEY)throw new Error("The OpenAI API key is not configured.");
    const{data:quoteRow,error:quoteError}=await client.from("business_records").select("record_key,payload").eq("business_id",businessId).eq("collection","quotes").eq("record_key",quoteId).eq("record_status","active").maybeSingle();if(quoteError)throw quoteError;if(!quoteRow)throw new Error("The saved quote could not be found.");const quote=quoteRow.payload&&typeof quoteRow.payload==="object"?quoteRow.payload as JsonObject:{};
    const projectTitle=clean(body.projectTitle||quote["Project Title"],300),scope=clean(body.scope||quote.Scope,8000),ownerWorkRequest=clean(body.ownerWorkRequest,10000),baseDraft=body.baseDraft&&typeof body.baseDraft==="object"?body.baseDraft as JsonObject:{},klass=behaviorClass(projectTitle,scope),prices=await priceBook(client,businessId,projectTitle,scope,baseDraft);
    const context={businessId,quoteId,behaviorClass:klass,projectTitle,scope,ownerWorkRequest,measurementEvidence:Array.isArray(body.measurementEvidence)?body.measurementEvidence.slice(0,80):[],baseDraft,currentEstimate:Array.isArray(body.currentEstimate)?body.currentEstimate.slice(0,80):[],priceBookEntries:prices,pricingLocation:"Grand Rapids / Itasca County, Minnesota",ownerReviewRequired:true};
    const raw=await callModel(context,klass),sanitized=sanitizeDirections(raw,prices);if(!sanitized.directions.length)throw new Error("No viable quote direction could be produced from the current scope.");await writeProof(client,businessId,signed.id,quoteId,klass,sanitized.directions.length,requestId);
    return json(request,200,{status:"PASS",serverBuild:BUILD,requestId,behaviorClass:klass,...sanitized,ownerReviewRequired:true,externalActionOccurred:false});
  }catch(error){const message=clean(error instanceof Error?error.message:error,1400)||"Quote options failed.";return json(request,/auth|member|role/i.test(message)?401:500,{status:"FAIL",message,serverBuild:BUILD,requestId,ownerReviewRequired:true,externalActionOccurred:false});}
});