const txt=v=>String(v??'').trim();
const num=v=>{if(v==null)return null;if(typeof v==='object')v=v.amount??v.value??v.price??v.formatted_amount;const s=txt(v).replace(/[^0-9.-]/g,'');const n=Number(s);return Number.isFinite(n)?n:null};
const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&txt(x)!=='');
function imageOf(r){const p=first(r?.image_url,r?.image,r?.thumbnailUrl,r?.thumbnail_url,r?.primary_listing_photo?.image?.uri,r?.listingPhotoUrl,r?.photo);if(typeof p==='string')return p;return txt(p?.url||p?.uri)}
function urlOf(r,id){const u=txt(first(r?.url,r?.listingUrl,r?.listing_url,r?.source_url));if(/^https:\/\//i.test(u))return u;return id?`https://www.facebook.com/marketplace/item/${id}/`:''}
function locationOf(r){return txt(first(r?.location_label,r?.location,r?.locationName,r?.city_state,r?.marketplace_listing_location?.reverse_geocode?.city,r?.city))}
export function normalizeMarketplaceRow(r={},ctx={}){const id=txt(first(r?.id,r?.listingId,r?.listing_id,r?.marketplace_listing_id,r?.node?.id)),title=txt(first(r?.title,r?.listingTitle,r?.listing_title,r?.name,r?.marketplace_listing_title,r?.node?.marketplace_listing_title)),price=num(first(r?.price,r?.listingPrice,r?.listing_price,r?.formatted_price,r?.node?.listing_price)),km=num(first(r?.distanceKm,r?.distance_km)),miles=num(first(r?.distance_miles,km!=null?km*.621371:null)),city=txt(first(r?.city,r?.location?.city)),state=txt(first(r?.state,r?.location?.state)),label=locationOf(r)||[city,state].filter(Boolean).join(', '),radius=Number(ctx.radiusMiles||50),localByDistance=miles!=null&&miles<=radius+.15,localByText=/grand rapids/i.test(label)&&/(\bmn\b|minnesota)/i.test(label),verified=localByDistance||localByText;return{id:id||urlOf(r,id),source:'Facebook Marketplace',title:title||'Marketplace listing',price:price!=null?price:null,buy_price:price!=null?price:null,url:urlOf(r,id),image_url:imageOf(r),location_label:label,distance_miles:miles!=null?Number(miles.toFixed(1)):null,location_verified:verified,source_search_bound:true,captured_at:new Date().toISOString(),provider:txt(ctx.provider||'public_guest'),public_listing:true}}
export function normalizeMarketplaceRows(rows=[],ctx={}){const out=[],seen=new Set();for(const r of Array.isArray(rows)?rows:[]){if(r?.record_type==='diagnostic'||r?.type==='diagnostic')continue;const x=normalizeMarketplaceRow(r,ctx),k=x.url||x.id;if(!k||seen.has(k)||!x.title)continue;if(x.distance_miles!=null&&x.distance_miles>Number(ctx.radiusMiles||50)+.15)continue;seen.add(k);out.push(x)}return out}
export function parseGuestHtml(html='',ctx={}){const s=String(html),out=[],seen=new Set(),re=/\/marketplace\/item\/(\d{6,})/g;let m;while((m=re.exec(s))){const id=m[1];if(seen.has(id))continue;seen.add(id);const a=Math.max(0,m.index-900),b=Math.min(s.length,m.index+1600),snip=s.slice(a,b),title=(snip.match(/"marketplace_listing_title"\s*:\s*"([^"]{3,180})"/)||snip.match(/"title"\s*:\s*"([^"]{3,180})"/)||[])[1]||'',price=(snip.match(/"formatted_amount"\s*:\s*"?\$?([0-9,.]+)"?/)||snip.match(/"amount"\s*:\s*"?([0-9.]+)"?/)||[])[1],image=(snip.match(/"uri"\s*:\s*"(https:[^"\\]+(?:\\u0026[^"\\]+)*)"/)||[])[1]||'';out.push(normalizeMarketplaceRow({id,title:title.replace(/\\u0026/g,'&'),price,image_url:image.replace(/\\u0026/g,'&')},{...ctx,provider:'facebook_public_ssr'}))}return out.slice(0,120)}
