import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {normalizeMarketplaceRows,parseGuestHtml} from './core.mjs';
type Any=Record<string,any>;
const TOKEN=Deno.env.get('APIFY_API_TOKEN')||'';
const ACTOR='crowdpull~facebook-marketplace-scraper';
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
function cors(r:Request){const o=r.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=60','vary':'Origin'}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function txt(v:any){return String(v??'').trim()}
function location(body:Any){const label=txt(body.location_label);if(txt(body.postal)==='55744'||/grand rapids/i.test(label))return'Grand Rapids, MN';return label||txt(body.postal)}
async function apify(term:string,body:Any){const u=`https://api.apify.com/v2/acts/${ACTOR}/run-sync-get-dataset-items?token=${encodeURIComponent(TOKEN)}`,km=Math.max(1,Math.round(Number(body.radiusMiles||50)*1.60934)),input={location:location(body),searchQuery:term,maxListings:30,radiusKm:km,includeDetails:false};const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(50000)}),p=await r.json().catch(()=>[]);if(!r.ok)throw Error(`Apify Facebook HTTP ${r.status}`);return normalizeMarketplaceRows(Array.isArray(p)?p:[],{radiusMiles:body.radiusMiles,provider:'CrowdPull public guest'})}
async function direct(term:string,body:Any){const u=new URL('https://www.facebook.com/marketplace/search/');u.searchParams.set('query',term);u.searchParams.set('sortBy','creation_time_descend');u.searchParams.set('daysSinceListed','7');u.searchParams.set('deliveryMethod','local_pick_up');u.searchParams.set('radius',String(Math.max(25,Number(body.radiusMiles||50))));if(Number.isFinite(Number(body.lat))&&Number.isFinite(Number(body.lon))){u.searchParams.set('latitude',String(body.lat));u.searchParams.set('longitude',String(body.lon))}const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept-language':'en-US,en;q=0.9',accept:'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(16000)}),html=await r.text().catch(()=> '');if(!r.ok)throw Error(`Facebook public HTTP ${r.status}`);const gated=/log in to facebook|login\/\?next=|checkpoint|confirm your identity/i.test(html),rows=parseGuestHtml(html,{radiusMiles:body.radiusMiles,provider:'facebook_public_ssr'});return{rows,gated}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,405,{error:'POST required'});if(!req.headers.get('authorization'))return json(req,401,{error:'Sign in required'});const body=await req.json().catch(()=>({})),terms=[...new Set((Array.isArray(body.terms)?body.terms:[]).map((x:any)=>txt(x)).filter((x:string)=>x.length>=2))].slice(0,4),warnings:string[]=[];if(!terms.length)terms.push('tools','lawn mower','electronics','appliances');let rows:Any[]=[];if(TOKEN){const settled=await Promise.allSettled(terms.map(t=>apify(t,body)));let failed=0;settled.forEach((x:any,i)=>{if(x.status==='fulfilled')rows.push(...x.value.map((r:any)=>({...r,term:terms[i]})));else{failed++;warnings.push(`${terms[i]}: ${x.reason?.message||x.reason}`)}});rows=normalizeMarketplaceRows(rows,{radiusMiles:body.radiusMiles,provider:'CrowdPull public guest'});return json(req,200,{status:rows.length?'PASS':'PARTIAL',engine:'H38_FACEBOOK_PUBLIC_V240',provider_status:rows.length?'LIVE':failed===terms.length?'PROVIDER_UNAVAILABLE':'LIVE_PARTIAL',provider:'CrowdPull public guest via Apify',authentication:'NO_FACEBOOK_LOGIN',results:rows.slice(0,120),count:rows.length,terms,warnings,truth:'Only public logged-out Marketplace data is collected. Missing, blocked or auth-gated listings are not treated as zero local inventory. Scout never reads Facebook credentials or imports personal cookies.'})}const settled=await Promise.allSettled(terms.map(t=>direct(t,body)));let gated=false,failed=0;settled.forEach((x:any,i)=>{if(x.status==='fulfilled'){gated=gated||x.value.gated;rows.push(...x.value.rows.map((r:any)=>({...r,term:terms[i]})))}else{failed++;warnings.push(`${terms[i]}: ${x.reason?.message||x.reason}`)}});rows=normalizeMarketplaceRows(rows,{radiusMiles:body.radiusMiles,provider:'facebook_public_ssr'});const blocked=!rows.length&&(gated||failed>0);return json(req,200,{status:rows.length?'PASS':'PARTIAL',engine:'H38_FACEBOOK_PUBLIC_V240',provider_status:rows.length?'LIVE':blocked?'AUTH_GATED':'LIVE_PARTIAL',provider:'Direct public guest SSR',authentication:'NO_FACEBOOK_LOGIN',device_fallback_required:blocked,config_hint:rows.length?'':'Signed-in device Marketplace is the no-key fallback; an optional APIFY_API_TOKEN can add proxy-backed public collection without using Facebook credentials.',results:rows.slice(0,120),count:rows.length,terms,warnings,truth:'Public guest collection only. If anonymous Facebook is blocked, Scout reports AUTH_GATED and uses the persisted signed-in phone browser as fallback; it does not bypass login or CAPTCHA.'})});
