import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {normalizeMarketplaceRows,parseGuestHtml} from './core.mjs';
type Any=Record<string,any>;
const TOKEN=Deno.env.get('APIFY_API_TOKEN')||'';
const ACTOR='crowdpull~facebook-marketplace-scraper';
const ORIGINS=new Set(['https://appassets.androidplatform.net','https://highway38solutions.com','https://www.highway38solutions.com']);
function cors(r:Request){const o=r.headers.get('origin')||'';return{'access-control-allow-origin':ORIGINS.has(o)?o:'https://appassets.androidplatform.net','access-control-allow-headers':'authorization, apikey, content-type','access-control-allow-methods':'POST, OPTIONS','content-type':'application/json; charset=utf-8','cache-control':'private, max-age=60','vary':'Origin'}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function txt(v:any){return String(v??'').trim()}
function where(body:Any){const label=txt(body.location_label).replace(/^ZIP\s+/i,'').trim();return label||[txt(body.city),txt(body.state)].filter(Boolean).join(', ')||txt(body.postal)}
function ctx(body:Any,provider:string,onlyVerified=true){return{radiusMiles:Number(body.radiusMiles||body.radius_miles||50),provider,locationLabel:where(body),lat:Number(body.lat),lon:Number(body.lon),onlyVerified}}
async function apify(term:string,body:Any){const u=`https://api.apify.com/v2/acts/${ACTOR}/run-sync-get-dataset-items?token=${encodeURIComponent(TOKEN)}`,km=Math.max(1,Math.round(Number(body.radiusMiles||50)*1.60934)),input={location:where(body),searchQuery:term,maxListings:30,radiusKm:km,includeDetails:false};const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(50000)}),p=await r.json().catch(()=>[]);if(!r.ok)throw Error(`Apify Facebook HTTP ${r.status}`);return normalizeMarketplaceRows(Array.isArray(p)?p:[],ctx(body,'CrowdPull public guest'))}
async function direct(term:string,body:Any){const u=new URL('https://www.facebook.com/marketplace/search/');u.searchParams.set('query',term);u.searchParams.set('sortBy','creation_time_descend');u.searchParams.set('daysSinceListed','7');u.searchParams.set('deliveryMethod','local_pick_up');u.searchParams.set('radius',String(Math.max(25,Number(body.radiusMiles||50))));if(Number.isFinite(Number(body.lat))&&Number.isFinite(Number(body.lon))){u.searchParams.set('latitude',String(body.lat));u.searchParams.set('longitude',String(body.lon))}const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept-language':'en-US,en;q=0.9',accept:'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(16000)}),html=await r.text().catch(()=> '');if(!r.ok)throw Error(`Facebook public HTTP ${r.status}`);const gated=/log in to facebook|login\/\?next=|checkpoint|confirm your identity/i.test(html),raw=parseGuestHtml(html,ctx(body,'facebook_public_ssr',false)),rows=normalizeMarketplaceRows(raw,ctx(body,'facebook_public_ssr'));return{rows,gated}}

/*
Public search-index parsing adapted from Better Fetch tools/facebook-marketplace-scraper.
Copyright (c) 2026 Better Fetch. MIT License.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files to deal in the Software without restriction, subject to inclusion of this notice. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
*/
function decodeEntities(value:string){return value.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#0?39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)))}
function stripTags(value:string){return decodeEntities(value.replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function marketplaceTarget(value:string){const normalized=/^https?:\/\//i.test(value)?value:`https://${value}`,m=normalized.match(/^https?:\/\/(?:www\.|m\.)?facebook\.com\/marketplace\/item\/(\d+)/i);return m?{id:m[1],url:`https://www.facebook.com/marketplace/item/${m[1]}/`}:null}
function indexedResults(html:string,limit:number){const out:Any[]=[],seen=new Set<string>(),links=/<a[^>]+href="(https?:\/\/[^\"]+)"[^>]*>(?:(?!<\/a>).)*?<h3[^>]*>((?:(?!<\/h3>).)*)<\/h3>/gs;let m:RegExpExecArray|null;while((m=links.exec(html))&&out.length<limit){let url=decodeEntities(m[1]),redir=url.match(/[?&]q=(https?[^&]+)/);if(redir){try{url=decodeURIComponent(redir[1])}catch{url=redir[1]}}const target=marketplaceTarget(url);if(!target||seen.has(target.id))continue;seen.add(target.id);const tail=html.slice(m.index+m[0].length,m.index+m[0].length+3500),sm=tail.match(/<(?:div|span)[^>]*(?:data-sncf|class="[^"]*(?:VwiC3b|IsZvec)[^"]*")[^>]*>((?:(?!<\/(?:div|span)>).)*)/s);out.push({title:stripTags(m[2]),url:target.url,id:target.id,snippet:sm?stripTags(sm[1]).slice(0,1200):''})}return out}
function listingFrom(r:Any){const snippet=txt(r.snippet),price=(snippet.match(/\b(?:[A-Z]{1,3}\$|\$)[\d,.]+(?:\.\d{2})?\b|\bFREE\b/i)||[])[0]||'',location=(snippet.match(/\bin\s+([A-Z][A-Za-z .'-]+,\s*(?:[A-Z]{2}|[A-Za-z ]+))(?=[.·,]|$)/)||[])[1]?.trim()||'',listed=(snippet.match(/Listed\s+(?:\d+\s+\w+\s+ago|on\s+[^.·,]+|over\s+a\s+week\s+ago|about\s+[^.·,]+)(?:\s+in\s+[A-Z][A-Za-z .'-]+,\s*[A-Z]{2})?/i)||[])[0]||'';return{id:r.id,url:r.url,title:r.title,description:snippet,price_label:price,location_label:location,listed_at_label:listed}}
async function indexed(term:string,body:Any){const loc=where(body),sourceQuery=`site:facebook.com/marketplace/item ${loc?`"${loc}" `:''}${term}`,u=`https://www.google.com/search?q=${encodeURIComponent(sourceQuery)}&num=25&hl=en&filter=0`,r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/151 Safari/537.36','accept-language':'en-US,en;q=0.9',accept:'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(18000)}),html=await r.text().catch(()=> '');if(!r.ok)throw Error(`Public index HTTP ${r.status}`);const listings=indexedResults(html,20).map(listingFrom);return normalizeMarketplaceRows(listings,ctx(body,'public_search_index'))}
function dedupe(rows:Any[],body:Any){return normalizeMarketplaceRows(rows,ctx(body,'public_multi_source')).slice(0,Math.max(1,Math.min(120,Number(body.max_results||120))))}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,405,{error:'POST required'});if(!req.headers.get('authorization'))return json(req,401,{error:'Sign in required'});const body=await req.json().catch(()=>({})),terms=[...new Set((Array.isArray(body.terms)?body.terms:[]).map((x:any)=>txt(x)).filter((x:string)=>x.length>=2))].slice(0,4),warnings:string[]=[];if(!terms.length)terms.push('tools','lawn mower','electronics','appliances');let rows:Any[]=[],directGated=false,attempts=0,successes=0;const jobs:Promise<{provider:string,term:string,rows:Any[],gated?:boolean}>[]=[];for(const term of terms){if(TOKEN)jobs.push(apify(term,body).then(x=>({provider:'apify',term,rows:x})));jobs.push(direct(term,body).then(x=>({provider:'facebook_guest',term,rows:x.rows,gated:x.gated})));jobs.push(indexed(term,body).then(x=>({provider:'public_index',term,rows:x})))}attempts=jobs.length;const settled=await Promise.allSettled(jobs);for(const x of settled){if(x.status==='fulfilled'){successes++;directGated=directGated||x.value.gated===true;rows.push(...x.value.rows.map(r=>({...r,term:x.value.term})));}else warnings.push(txt(x.reason?.message||x.reason))}rows=dedupe(rows,body);const status=rows.length?'PASS':'PARTIAL',providerStatus=rows.length?'LIVE':successes?'PUBLIC_LIMITED':'PROVIDER_UNAVAILABLE';return json(req,200,{status,engine:'H38_FACEBOOK_PUBLIC_V260',provider_status:providerStatus,provider:TOKEN?'Public multi-source: Apify guest + Facebook guest SSR + search index':'Public multi-source: Facebook guest SSR + search index',authentication:'NO_FACEBOOK_LOGIN',device_fallback_required:false,results:rows,count:rows.length,terms,location_query:where(body),attempts,successful_attempts:successes,direct_facebook_gated:directGated,warnings:[...new Set(warnings)].slice(0,12),config_hint:rows.length?'':'Public coverage is best-effort. No result is not zero local inventory. An optional APIFY_API_TOKEN can broaden public collection without Facebook credentials.',truth:'Public-only Facebook discovery. Scout never needs a Facebook login, never reads Facebook cookies, and never treats search targeting alone as local proof. A listing is returned only when its distance or city/state evidence matches the selected Scout area; missing or blocked results remain unknown.'})});