with h38 as (
  select id as business_id from public.businesses where business_key='highway38' limit 1
)
insert into public.contractor_pricing_rules
(business_id,rule_code,category,description,numeric_value,unit,source_type,source_note,approval_status,active,updated_at)
select h38.business_id,v.* from h38 cross join (values
('MATERIAL_WASTE_FLOOR','Waste','Minimum material scrap/waste factor applied to purchased material quantities. Does not inflate measured installed quantity.',0.10,'ratio','business','Owner direction 2026-08-12: at least 10% scrap on materials.','owner_review_required',true,now()),
('DRYWALL_WASTE','Waste','Drywall board and related sheet-good waste factor.',0.10,'ratio','business','Minimum 10% scrap floor.','owner_review_required',true,now()),
('INSULATION_WASTE','Waste','Batt/roll insulation waste factor.',0.10,'ratio','business','Minimum 10% scrap floor.','owner_review_required',true,now()),
('FRAMING_WASTE','Waste','Framing lumber waste factor.',0.10,'ratio','business','Minimum 10% scrap floor.','owner_review_required',true,now()),
('SHEATHING_WASTE','Waste','OSB/plywood sheet-good waste factor.',0.10,'ratio','business','Minimum 10% scrap floor.','owner_review_required',true,now()),
('CONCRETE_WASTE','Waste','Concrete material overage factor for estimating/order quantities.',0.10,'ratio','business','Minimum 10% scrap/overage floor.','owner_review_required',true,now()),
('BLOCK_WASTE','Waste','Retaining wall/block waste and breakage factor.',0.10,'ratio','business','Minimum 10% scrap floor.','owner_review_required',true,now()),
('AGGREGATE_WASTE','Waste','Base, drainage stone, gravel and soil material overage factor.',0.10,'ratio','business','Minimum 10% overage floor.','owner_review_required',true,now()),
('FILTER_FABRIC_WASTE','Waste','Landscape/filter fabric cut, lap and overlap factor.',0.15,'ratio','business','15% due to overlaps/cuts; exceeds 10% floor.','owner_review_required',true,now()),
('PAINT_WASTE','Waste','Primer/paint material overage factor.',0.10,'ratio','business','Minimum 10% material overage floor.','owner_review_required',true,now()),
('PRICE_REFRESH_DAYS','Freshness','Maximum age for stored local-research prices before current research is required.',30,'days','business','Matches H38 Quote AI stale local-research refresh policy.','owner_review_required',true,now()),
('NE_MN_CONSTRUCTION_MEDIAN_WAGE','Labor benchmark','Northeast Minnesota Construction & Extraction median hourly wage benchmark.',34.75,'USD/hour','local_research','Minnesota DEED OEWS Q1 2026: Northeast Minnesota Construction & Extraction median hourly wage $34.75.','owner_review_required',true,now()),
('CARPENTER_MARKET_SELL_BENCHMARK','Labor benchmark','General carpenter customer-facing hourly market benchmark; owner review required.',100,'USD/hour','local_research','2026 HomeAdvisor general carpenter range $75-$125/hour; midpoint $100.','owner_review_required',true,now()),
('DELIVERY_TRIP_BENCHMARK','Job cost benchmark','Material/topsoil delivery trip planning allowance; owner review required.',100,'USD/trip','local_research','2026 market benchmark commonly $50-$150 per trip; midpoint used.','owner_review_required',true,now())
) as v(rule_code,category,description,numeric_value,unit,source_type,source_note,approval_status,active,updated_at)
on conflict (business_id,rule_code) do update set category=excluded.category,description=excluded.description,numeric_value=excluded.numeric_value,unit=excluded.unit,source_type=excluded.source_type,source_note=excluded.source_note,approval_status='owner_review_required',active=true,approved_by=null,approved_at=null,updated_at=now();

with h38 as (
  select id as business_id from public.businesses where business_key='highway38' limit 1
)
insert into public.price_book_items
(business_id,item_code,category,description,unit,unit_cost,source_type,source_note,approval_status,active,updated_at)
select h38.business_id,v.* from h38 cross join (values
('MAT-DRYWALL-STD-1_2-4X8','RAW MATERIAL | Drywall','RAW MATERIAL ONLY — 1/2 in. x 4 ft. x 8 ft. standard drywall panel','each',16.68,'local_research','Home Depot Aug 2026 benchmark: $16.68 each; bulk benchmark $14.18.','owner_review_required',true,now()),
('MAT-DRYWALL-MOLD-1_2-4X8','RAW MATERIAL | Drywall','RAW MATERIAL ONLY — 1/2 in. x 4 ft. x 8 ft. mold-resistant drywall panel','each',23.58,'local_research','Home Depot Aug 2026 benchmark: $23.58 each; bulk benchmark $20.04.','owner_review_required',true,now()),
('MAT-DRYWALL-TAPE-250','RAW MATERIAL | Drywall','RAW MATERIAL ONLY — Paper drywall joint tape 2-1/16 in. x 250 ft.','roll',4.57,'local_research','Home Depot Aug 2026 benchmark.','owner_review_required',true,now()),
('MAT-DRYWALL-SCREWS-1_5_8-5LB','RAW MATERIAL | Drywall','RAW MATERIAL ONLY — Coarse-thread drywall screws #6 x 1-5/8 in., 5 lb box','box',24.98,'local_research','Home Depot Aug 2026 benchmark.','owner_review_required',true,now()),
('MAT-FRAMING-2X4X8','RAW MATERIAL | Framing','RAW MATERIAL ONLY — 2 in. x 4 in. x 96 in. #2 KD-HT framing stud','each',4.15,'local_research','Home Depot Aug 2026 benchmark: $4.15; bulk benchmark $3.74.','owner_review_required',true,now()),
('MAT-FRAMING-2X6X8','RAW MATERIAL | Framing','RAW MATERIAL ONLY — 2 in. x 6 in. x 96 in. framing stud benchmark','each',6.00,'local_research','2026 Midwest planning benchmark; verify local supplier before order.','owner_review_required',true,now()),
('MAT-OSB-7_16-4X8','RAW MATERIAL | Sheathing','RAW MATERIAL ONLY — 7/16 in. OSB sheathing panel 4 ft. x 8 ft.','each',12.34,'local_research','Home Depot Aug 2026 benchmark: $12.34; bulk benchmark $11.72.','owner_review_required',true,now()),
('MAT-OSB-23_32-TG-4X8','RAW MATERIAL | Sheathing','RAW MATERIAL ONLY — 23/32 in. tongue-and-groove OSB subfloor 4 ft. x 8 ft.','each',24.98,'local_research','Home Depot Aug 2026 benchmark: $24.98; bulk benchmark $22.48.','owner_review_required',true,now()),
('MAT-PLYWOOD-3_4-SANDE-4X8','RAW MATERIAL | Sheathing','RAW MATERIAL ONLY — 3/4 in. category sanded plywood 4 ft. x 8 ft.','each',69.85,'local_research','Home Depot Aug 2026 benchmark.','owner_review_required',true,now()),
('MAT-INSULATION-R19-KRAFT-SF','RAW MATERIAL | Insulation','RAW MATERIAL ONLY — R-19 kraft-faced fiberglass batt material benchmark per square foot','SF',0.80,'local_research','Home Depot Aug 2026 pallet benchmark: about $0.80/SF.','owner_review_required',true,now()),
('MAT-INSULATION-R19-UNFACED-SF','RAW MATERIAL | Insulation','RAW MATERIAL ONLY — R-19 unfaced fiberglass batt material benchmark per square foot','SF',1.06,'local_research','Home Depot Aug 2026 single-bag benchmark: about $1.06/SF.','owner_review_required',true,now()),
('MAT-CONCRETE-MIX-80LB','RAW MATERIAL | Concrete','RAW MATERIAL ONLY — 80 lb all-purpose concrete mix','bag',6.47,'local_research','Home Depot Aug 2026 Quikrete benchmark.','owner_review_required',true,now()),
('MAT-PAVER-BASE-0_5CF','RAW MATERIAL | Hardscape','RAW MATERIAL ONLY — 0.5 cu. ft. paver base','bag',6.47,'local_research','Home Depot Aug 2026 benchmark; bulk benchmark $5.82.','owner_review_required',true,now()),
('MAT-PEA-GRAVEL-0_5CF','RAW MATERIAL | Hardscape','RAW MATERIAL ONLY — 0.5 cu. ft. pea gravel / drainage pebble','bag',5.74,'local_research','Home Depot Aug 2026 benchmark; bulk benchmark $5.17.','owner_review_required',true,now()),
('MAT-DRAIN-PIPE-4-PERF','RAW MATERIAL | Drainage','RAW MATERIAL ONLY — 4 in. perforated corrugated drain pipe material cost per linear foot','LF',1.36,'local_research','Home Depot Aug 2026 100-ft benchmark.','owner_review_required',true,now()),
('MAT-DRAIN-PIPE-4-PERF-SOCK','RAW MATERIAL | Drainage','RAW MATERIAL ONLY — 4 in. perforated corrugated drain pipe with filter sock material cost per linear foot','LF',2.07,'local_research','Home Depot Aug 2026 conservative 100-ft benchmark.','owner_review_required',true,now()),
('MAT-LANDSCAPE-FABRIC-SF','RAW MATERIAL | Drainage','RAW MATERIAL ONLY — Medium-duty landscape/filter fabric material cost per square foot','SF',0.10,'local_research','Home Depot Aug 2026 4x100-ft benchmark; assembly uses 15% overlap/cut waste.','owner_review_required',true,now()),
('MAT-RETAINING-BLOCK-LADARA','RAW MATERIAL | Retaining Wall','RAW MATERIAL ONLY — Pavestone Ladara/Ladera retaining wall block benchmark','each',4.47,'local_research','Home Depot Aug 2026 benchmark; bulk benchmark $4.02.','owner_review_required',true,now()),
('MAT-RETAINING-BLOCK-PRO-1SF','RAW MATERIAL | Retaining Wall','RAW MATERIAL ONLY — Segmental retaining wall pro block, approximately 1 face SF per block','each',9.47,'local_research','Home Depot Aug 2026 benchmark; bulk benchmark $8.52.','owner_review_required',true,now()),
('MAT-CONSTRUCTION-ADHESIVE-28OZ','RAW MATERIAL | Consumables','RAW MATERIAL ONLY — Heavy-duty construction adhesive, 28 oz tube','tube',6.48,'local_research','Home Depot Aug 2026 Loctite PL 375 benchmark.','owner_review_required',true,now()),
('MAT-CONSTRUCTION-ADHESIVE-PREMIUM-28OZ','RAW MATERIAL | Consumables','RAW MATERIAL ONLY — Premium polyurethane construction adhesive, 28 oz tube','tube',12.34,'local_research','Home Depot Aug 2026 PL Premium two-pack benchmark divided per tube.','owner_review_required',true,now()),
('MAT-TOPSOIL-SCREENED-CY','RAW MATERIAL | Landscape','RAW MATERIAL ONLY — Screened topsoil planning material allowance per cubic yard','CY',40.00,'local_research','2026 screened topsoil benchmark range $25-$55/CY; midpoint before delivery/labor.','owner_review_required',true,now()),
('LAB-CONSTRUCTION-MARKET-WAGE','LABOR BENCHMARK','Northeast Minnesota Construction & Extraction median wage benchmark; not a customer sell rate','hour',34.75,'local_research','Minnesota DEED Q1 2026 benchmark.','owner_review_required',true,now()),
('LAB-CARPENTER-MARKET-SELL','LABOR BENCHMARK','General carpenter customer-facing hourly market benchmark; planning only','hour',100.00,'local_research','2026 HomeAdvisor range $75-$125/hour; midpoint.','owner_review_required',true,now()),
('LAB-CARPENTER-LOW','LABOR BENCHMARK','General carpenter lower-market planning rate','hour',75.00,'local_research','2026 HomeAdvisor lower benchmark.','owner_review_required',true,now()),
('LAB-CARPENTER-HIGH','LABOR BENCHMARK','General carpenter upper-market planning rate','hour',125.00,'local_research','2026 HomeAdvisor upper benchmark.','owner_review_required',true,now()),
('LAB-GENERAL-CONSTRUCTION-ALLOW','LABOR BENCHMARK','General construction labor planning sell allowance; owner review required','hour',65.00,'local_research','Planning allowance derived from local wage benchmark; not an approved H38 labor rate.','owner_review_required',true,now()),
('LAB-EQUIPMENT-OPERATOR-ALLOW','LABOR BENCHMARK','Equipment operator planning sell allowance; owner review required','hour',75.00,'local_research','Planning allowance; verify operator/equipment split.','owner_review_required',true,now()),
('JOB-DELIVERY-TRIP','JOB COST BENCHMARK','Material/topsoil delivery trip planning allowance','trip',100.00,'local_research','2026 planning midpoint from $50-$150 trip benchmark.','owner_review_required',true,now()),
('JOB-MOBILIZATION-SMALL','JOB COST BENCHMARK','Small-job mobilization planning allowance; owner review required','LS',150.00,'local_research','Planning allowance; owner sets final H38 policy.','owner_review_required',true,now()),
('JOB-CLEANUP-STANDARD','JOB COST BENCHMARK','Standard jobsite cleanup/consumables allowance; owner review required','LS',150.00,'local_research','Planning allowance; scale by project size.','owner_review_required',true,now()),
('JOB-DISPOSAL-TRIP','JOB COST BENCHMARK','Single disposal/haul trip allowance; owner review required','trip',175.00,'local_research','Planning allowance; actual dump fees/distance/trailer time vary.','owner_review_required',true,now())
) as v(item_code,category,description,unit,unit_cost,source_type,source_note,approval_status,active,updated_at)
on conflict (business_id,item_code) do update set category=excluded.category,description=excluded.description,unit=excluded.unit,unit_cost=excluded.unit_cost,source_type=excluded.source_type,source_note=excluded.source_note,approval_status='owner_review_required',active=true,approved_by=null,approved_at=null,updated_at=now();

with h38 as (
  select id as business_id from public.businesses where business_key='highway38' limit 1
)
insert into public.price_book_assemblies
(business_id,assembly_code,category,description,output_unit,material_waste_pct,sell_rate,pricing_method,source_type,source_note,approval_status,active,updated_at)
select h38.business_id,v.* from h38 cross join (values
('ASM-DRYWALL-WALL-L4','Drywall','Hang and finish standard 1/2 in. drywall to Level 4 on walls; installed quantity remains net SF; internal board purchase includes 10% waste.','SF',0.10,2.25,'recipe','local_research','2026 H38 researched installed benchmark; owner review required.','owner_review_required',true,now()),
('ASM-DRYWALL-CEILING-L4','Drywall','Hang and finish standard 1/2 in. drywall to Level 4 on ceiling; includes 10% board waste and higher handling labor.','SF',0.10,2.75,'recipe','local_research','Ceiling handling/access premium; owner review required.','owner_review_required',true,now()),
('ASM-DRYWALL-MOLD-WALL-L4','Drywall','Hang and finish mold-resistant 1/2 in. drywall to Level 4 on walls; internal board purchase includes 10% waste.','SF',0.10,2.75,'recipe','local_research','Current mold-resistant material plus finishing labor; owner review required.','owner_review_required',true,now()),
('ASM-DRYWALL-DEMO-DISPOSE','Drywall','Remove existing drywall/OSB wall finish and stage/dispose debris; verify hazardous materials and dump conditions.','SF',0.10,1.50,'researched_allowance','local_research','Planning allowance; demolition conditions vary.','owner_review_required',true,now()),
('ASM-INSULATION-R19-WALL','Insulation','Install R-19 fiberglass batt in wall cavities; internal material quantity includes minimum 10% waste.','SF',0.10,2.00,'recipe','local_research','Current R-19 material and installed market benchmark; owner review required.','owner_review_required',true,now()),
('ASM-INSULATION-R24-CEILING','Insulation','Install high-R batt insulation at ceiling/overhead cavities; verify R-value, cavity depth and product width.','SF',0.10,2.75,'researched_allowance','local_research','Higher material/access allowance than wall batt.','owner_review_required',true,now()),
('ASM-INSULATION-AIR-VAPOR','Insulation','Air sealing, vapor retarder, tape, sealants, supports and minor blocking allowance.','SF',0.10,0.60,'researched_allowance','local_research','Accessories allowance; field conditions/code assembly control.','owner_review_required',true,now()),
('ASM-FRAME-2X4-WALL-8FT','Framing','Frame straight non-load-bearing 2x4 wall at about 16 in. O.C., standard 8 ft height; 10% lumber waste included internally.','LF',0.10,10.00,'recipe','local_research','2026 framing benchmark roughly $6-$12/LF installed.','owner_review_required',true,now()),
('ASM-FRAME-2X6-WALL-8FT','Framing','Frame straight non-load-bearing 2x6 wall at about 16 in. O.C., standard 8 ft height; 10% lumber waste included internally.','LF',0.10,13.00,'recipe','local_research','2026 2x6 installed planning allowance.','owner_review_required',true,now()),
('ASM-FRAME-DOOR-OPENING','Framing','Frame standard non-load-bearing door opening with king/jack studs and header; excludes door unit.','each',0.10,175.00,'researched_allowance','local_research','Verify opening width, load path and header requirement.','owner_review_required',true,now()),
('ASM-OSB-WALL-7_16','Sheathing','Install 7/16 in. OSB wall sheathing; internal panel purchase includes minimum 10% waste.','SF',0.10,1.50,'recipe','local_research','Current OSB material plus installed allowance.','owner_review_required',true,now()),
('ASM-OSB-FLOOR-23_32-TG','Sheathing','Install 23/32 in. T&G OSB subfloor; internal panel purchase includes minimum 10% waste.','SF',0.10,2.25,'recipe','local_research','Current T&G OSB material plus installed allowance.','owner_review_required',true,now()),
('ASM-CONCRETE-SLAB-4IN','Concrete','4 in. residential concrete slab installed allowance including placement/finish; concrete order quantity uses minimum 10% overage.','SF',0.10,9.00,'researched_allowance','local_research','2026 residential slab benchmark $6-$12/SF installed; midpoint.','owner_review_required',true,now()),
('ASM-CONCRETE-SLAB-6IN','Concrete','6 in. residential/heavy slab installed allowance; verify reinforcement, base and load requirement; 10% concrete overage internally.','SF',0.10,12.00,'researched_allowance','local_research','Scaled 2026 planning allowance.','owner_review_required',true,now()),
('ASM-CONCRETE-FORM-EDGE','Concrete','Form and strip straight slab edge allowance.','LF',0.10,5.00,'researched_allowance','local_research','Curves/steps/height increase cost.','owner_review_required',true,now()),
('ASM-EXCAVATION-STANDARD','Earthwork','Standard accessible residential excavation; excludes rock, dewatering, shoring and export disposal.','CY',0.10,40.00,'researched_allowance','local_research','2026 Minnesota excavation benchmark $16-$63/CY; planning midpoint.','owner_review_required',true,now()),
('ASM-BASE-GRAVEL-INSTALL','Earthwork','Supply, place and compact aggregate/paver base; internal aggregate quantity includes minimum 10% overage.','CY',0.10,110.00,'researched_allowance','local_research','Replace with local bulk vendor price when available.','owner_review_required',true,now()),
('ASM-TOPSOIL-SPREAD','Landscape','Supply and spread screened topsoil; material quantity includes minimum 10% overage.','CY',0.10,95.00,'recipe','local_research','2026 screened topsoil plus delivery/labor planning allowance.','owner_review_required',true,now()),
('ASM-HYDROSEED','Landscape','Hydroseed disturbed area; installed area stays net SF; material allowance includes minimum 10% overage.','SF',0.10,0.18,'researched_allowance','local_research','2026 hydroseed benchmark roughly $0.10-$0.22/SF.','owner_review_required',true,now()),
('ASM-SOD-INSTALL','Landscape','Install sod on prepared disturbed area; internal sod order includes minimum 10% waste.','SF',0.10,2.50,'researched_allowance','local_research','H38 planning allowance with explicit waste.','owner_review_required',true,now()),
('ASM-RETAINING-WALL-BLOCK','Retaining Wall','Segmental concrete retaining wall installed per wall-face SF; includes minimum 10% block waste internally but excludes engineering when required.','SF',0.10,50.00,'researched_allowance','local_research','2026 block retaining wall benchmark roughly $35-$85/SF installed.','owner_review_required',true,now()),
('ASM-RETAINING-DRAIN-PIPE','Retaining Wall','Install 4 in. perforated drain pipe behind retaining wall; internal pipe purchase includes minimum 10% length overage.','LF',0.10,5.50,'recipe','local_research','Current pipe material plus installed allowance.','owner_review_required',true,now()),
('ASM-RETAINING-FABRIC','Retaining Wall','Install filter/landscape fabric at drainage/backfill interface; 15% overlap/cut waste internally.','SF',0.15,0.55,'recipe','local_research','15% overlap/cut waste.','owner_review_required',true,now()),
('ASM-RETAINING-DRAIN-STONE','Retaining Wall','Supply/place drainage stone behind retaining wall; internal quantity includes minimum 10% overage.','CY',0.10,105.00,'researched_allowance','local_research','Replace with local bulk vendor quote when available.','owner_review_required',true,now()),
('ASM-RETAINING-GEOGRID','Retaining Wall','Geogrid reinforcement where required by wall height/soil/design; material quantity includes minimum 10% waste.','SF',0.10,1.75,'researched_allowance','local_research','Planning allowance pending vendor/design confirmation.','owner_review_required',true,now()),
('ASM-RETAINING-CAP','Retaining Wall','Standard retaining wall cap installed; internal cap quantity includes minimum 10% waste/breakage.','LF',0.10,12.00,'researched_allowance','local_research','Existing H38 planning benchmark.','owner_review_required',true,now()),
('ASM-RETAINING-PREMIUM-CAP-UPGRADE','Retaining Wall','Incremental premium/high-profile cap upgrade above standard cap.','LF',0.10,6.00,'researched_allowance','local_research','Existing H38 incremental planning allowance.','owner_review_required',true,now()),
('ASM-LANDSCAPE-STAIR-4FT','Retaining Wall','4-ft-wide block landscape stair riser/tread installed allowance; field-verify rise, tread count and geometry.','step',0.10,562.50,'researched_allowance','local_research','Existing H38 2026 Minnesota planning benchmark.','owner_review_required',true,now()),
('ASM-PRIME-PAINT-NEW-DRYWALL','Finish','Prime and paint new drywall; material quantity includes minimum 10% overage.','SF',0.10,1.75,'researched_allowance','local_research','2026 planning allowance; owner review required.','owner_review_required',true,now()),
('ASM-TRIM-PENETRATION-REWORK','Finish','Minor trim reinstall, box extension and penetration patching allowance.','LS',0.10,300.00,'researched_allowance','local_research','Planning allowance to avoid underpricing small rework.','owner_review_required',true,now()),
('ASM-DRYWALL-WASTE-DISPOSAL','Job Support','Drywall cutoff/package waste handling and disposal allowance when no separate demolition/haul line exists.','SF',0.10,0.12,'researched_allowance','local_research','Planning allowance.','owner_review_required',true,now()),
('ASM-MOBILIZATION-SMALL','Job Support','Small-job mobilization allowance. Use only when not already represented; owner review required.','LS',0.10,150.00,'researched_allowance','local_research','Do not auto-add if duplicate.','owner_review_required',true,now()),
('ASM-CLEANUP-STANDARD','Job Support','Standard jobsite cleanup allowance. Disposal fees and demolition haul-off remain separate when material.','LS',0.10,150.00,'researched_allowance','local_research','Scale to scope.','owner_review_required',true,now())
) as v(assembly_code,category,description,output_unit,material_waste_pct,sell_rate,pricing_method,source_type,source_note,approval_status,active,updated_at)
on conflict (business_id,assembly_code) do update set category=excluded.category,description=excluded.description,output_unit=excluded.output_unit,material_waste_pct=greatest(excluded.material_waste_pct,0.10),sell_rate=excluded.sell_rate,pricing_method=excluded.pricing_method,source_type=excluded.source_type,source_note=excluded.source_note,approval_status='owner_review_required',active=true,approved_by=null,approved_at=null,updated_at=now();
