import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const BASE=Deno.env.get("SUPABASE_URL")||"";
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const MODEL=Deno.env.get("OPENAI_RESELLER_MODEL")||Deno.env.get("OPENAI_SITE_SCANNER_MODEL")||"gpt-5-mini-2025-08-07";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function outputText(p:any){if(typeof p?.output_text==="string")return p.output_text;for(const o of Array.isArray(p?.output)?p.output:[])for(const c of Array.isArray(o?.content)?o.content:[])if(c?.type==="output_text"&&typeof c?.text==="string")return c.text;return""}
function stats(vals:any[]){const a=vals.map(Number).filter(n=>Number.isFinite(n)&&n>=3&&n<=50000).sort((a,b)=>a-b);if(!a.length)return null;const pick=(q:number)=>a[Math.min(a.length-1,Math.max(0,Math.round((a.length-1)*q)))];return{low:pick(.2),typical:pick(.5),high:pick(.8),sample_count:a.length,confidence:a.length>=8?"medium":a.length>=3?"low":"thin"}}
async function webEvidence(q:string,upc:string){if(!OPENAI_API_KEY)return null;const prompt=`Research resale market evidence for this exact item: ${q}${upc?` UPC ${upc}`:""}. Use web search. Return ONLY compact JSON with keys: exact_item, confidence, sold_prices (array of numeric completed/sold transaction prices only), active_prices (array of numeric current asking prices), retail_prices (array of numeric new retail prices), sold_sources (array of {name,url}), active_sources, retail_sources, notes. Do not mix active asking or retail prices into sold_prices. If completed-sale evidence cannot be verified, sold_prices must be empty.`;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`,"content-type":"application/json"},signal:AbortSignal.timeout(45000),body:JSON.stringify({model:MODEL,tools:[{type:"web_search_preview",search_context_size:"medium"}],tool_choice:"auto",include:["web_search_call.action.sources"],input:prompt})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(p?.error?.message||`Web research HTTP ${r.status}`));let t=outputText(p).trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();const a=t.indexOf("{"),b=t.lastIndexOf("}");if(a>=0&&b>a)t=t.slice(a,b+1);const data=JSON.parse(t||"{}");return{...data,raw_sources:(Array.isArray(p.output)?p.output:[]).filter((x:any)=>x?.type==="web_search_call").flatMap((x:any)=>x?.action?.sources||[])} }
function band(source:string,type:string,vals:any[],sources:any[],msg:string){const s=stats(vals||[]);return s?{source,evidence_type:type,status:"verified",...s,rows:(sources||[]).slice(0,8),message:msg}:{source,evidence_type:type,status:"not_established",sample_count:0,confidence:"none",rows:(sources||[]).slice(0,8),message:msg}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required"});try{const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";const body=await req.json().catch(()=>({}));const up=await fetch(`${BASE}/functions/v1/reseller-item-research-v041`,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(55000)}),base=await up.json().catch(()=>({}));if(!up.ok)return json(req,up.status,{error:base?.error||"Base research failed."});const id=base.identification||{},q=String(id.search_query||id.likely_item||body.hint||body.upc||"").trim(),upc=String(body.upc||"").replace(/\D/g,"");let web:any=null;try{web=await webEvidence(q,upc)}catch(e){web={error:e instanceof Error?e.message:String(e)}}const soldWeb=band("Web completed-sale evidence","sold",web?.sold_prices||[],web?.sold_sources||[],"Completed/sold prices only. Active asking and retail prices are excluded."),activeWeb=band("Web active market","asking",web?.active_prices||[],web?.active_sources||[],"Current asking prices are market context only."),retailWeb=band("Web retail market","retail",web?.retail_prices||[],web?.retail_sources||[],"Current new-retail prices are context only.");const baseSold=(base.evidence?.sold||[])[0]||base.market||{},market=baseSold.status==="verified"?baseSold:soldWeb.status==="verified"?soldWeb:baseSold;const buy=Math.max(0,Number(body.buy_price||0));let flip=base.flip||{verdict:"NEEDS COMP"};if(buy>0&&market.status==="verified"){const resale=Number(market.typical||0),net=Number((resale*.87-buy).toFixed(2)),roi=buy?Number((net/buy*100).toFixed(1)):0;flip={verdict:net>=25&&roi>=30?"BUY":net>0?"MAYBE":"PASS",estimated_resale:resale,estimated_net:net,roi_pct:roi,selling_friction_pct:13,assumption:"Uses verified completed-sale typical value when available; active and retail prices are context only."}}return json(req,200,{...base,status:"PASS",engine:"H38_RESALE_RESEARCH_V044",market,evidence:{...(base.evidence||{}),sold:[baseSold,soldWeb],active:[...(base.evidence?.active||[]),activeWeb],retail:[retailWeb],web_summary:{exact_item:web?.exact_item||q,confidence:web?.confidence||"",notes:web?.notes||"",error:web?.error||""}},flip,source_health:{...(base.source_health||{}),web_sold:soldWeb.status,web_active:activeWeb.status,web_retail:retailWeb.status},researched_at:new Date().toISOString()})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});