import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const OPENAI_API_KEY=Deno.env.get("OPENAI_API_KEY")||"";
const TRANSCRIBE_MODEL=Deno.env.get("OPENAI_WALKTHROUGH_TRANSCRIBE_MODEL")||"gpt-4o-mini-transcribe";
const NOTES_MODEL=Deno.env.get("OPENAI_SITE_SCANNER_MODEL")||Deno.env.get("OPENAI_QUOTE_MODEL")||"gpt-5-mini-2025-08-07";
const MAX_AUDIO_BYTES=24*1024*1024;
const BUILD="20260915-quick-meeting-notes-1";
type J=Record<string,unknown>;
type Client=ReturnType<typeof createClient>;
const text=(v:unknown,n=12000)=>String(v??"").replace(/Bearer\s+[A-Za-z0-9._-]+/gi,"Bearer [REDACTED]").trim().slice(0,n);
function cors(req:Request):HeadersInit{return{"access-control-allow-origin":req.headers.get("origin")||"*","access-control-allow-headers":req.headers.get("access-control-request-headers")||"authorization, apikey, content-type, x-client-info","access-control-allow-methods":"POST, OPTIONS","cache-control":"no-store","content-type":"application/json; charset=utf-8","vary":"Origin, Access-Control-Request-Headers"};}
const reply=(req:Request,status:number,payload:unknown)=>new Response(JSON.stringify(payload),{status,headers:cors(req)});
const bearer=(req:Request)=>text(req.headers.get("authorization"),5000).replace(/^Bearer\s+/i,"").trim();
function db(){if(!SUPABASE_URL||!SERVICE_KEY)throw Error("Supabase service configuration is unavailable.");return createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});}
async function readJson(res:Response):Promise<J>{const raw=await res.text();try{return raw?JSON.parse(raw):{};}catch{return{};}}
async function authorize(req:Request,service:Client,businessId:string){const token=bearer(req);if(!token)throw Error("Supabase Auth session is required.");const res=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{authorization:`Bearer ${token}`,apikey:SERVICE_KEY,"x-client-info":BUILD},signal:AbortSignal.timeout(15000)});const user=await readJson(res);if(!res.ok||typeof user.id!=="string"||!user.id)throw Error("Supabase Auth session is invalid or expired.");const membership=await service.from("business_memberships").select("role,status").eq("business_id",businessId).eq("auth_user_id",user.id).eq("status","active").maybeSingle();if(membership.error)throw membership.error;if(!membership.data||!["owner","administrator","staff"].includes(String(membership.data.role)))throw Error("This role cannot create meeting notes for this business.");return{id:user.id as string,role:String(membership.data.role)};}
async function transcribe(file:File){if(!OPENAI_API_KEY)throw Error("Meeting-note AI is not configured.");if(file.size>MAX_AUDIO_BYTES)throw Error("This recording is too large for Quick Meeting. Use a shorter recording or type the notes.");const form=new FormData();form.append("file",file,file.name||"meeting.webm");form.append("model",TRANSCRIBE_MODEL);form.append("response_format","json");form.append("language","en");const response=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`},body:form,signal:AbortSignal.timeout(120000)});const payload=await readJson(response);if(!response.ok)throw Error(text((payload.error as J|undefined)?.message||payload.message||`Meeting transcription returned ${response.status}.`,3000));const spoken=text(payload.text,48000);if(!spoken)throw Error("No spoken meeting content was detected in that recording.");return spoken;}
function outputText(payload:J):string{if(typeof payload.output_text==="string")return payload.output_text;for(const output of Array.isArray(payload.output)?payload.output:[]){if(!output||typeof output!=="object")continue;for(const part of Array.isArray((output as J).content)?(output as J).content as unknown[]:[]){if(part&&typeof part==="object"&&(part as J).type==="output_text"&&typeof (part as J).text==="string")return (part as J).text as string;}}return"";}
function schema(){const list={type:"array",items:{type:"string"}};return{type:"object",additionalProperties:false,required:["discussed","decisions","actionItems","followUp"],properties:{discussed:list,decisions:list,actionItems:list,followUp:list}};}
function cleanList(v:unknown){return(Array.isArray(v)?v:[]).map(item=>text(item,800)).filter(Boolean).slice(0,20);}
async function makeNotes(source:string,context:J){if(!OPENAI_API_KEY)throw Error("Meeting-note AI is not configured.");const instructions=["Turn the supplied meeting content into concise internal bullet notes.","Return only useful meeting notes, not a transcript.","Do not invent names, decisions, promises, dates, prices, due dates, measurements, approvals, commitments, or action owners that were not explicitly stated.","Keep ordinary discussion separate from actual decisions and action items.","Use short plain-English bullets. Remove greetings, filler, repetition, and transcription noise.","If a section has no supported content, return an empty array.","A customer is optional; do not infer one.","The raw audio and transcript are temporary processing inputs and must not be treated as records to retain."].join(" ");const input={title:text(context.title,300),customerId:text(context.customerId,180),content:text(source,48000)};const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:NOTES_MODEL,instructions,input:[{role:"user",content:[{type:"input_text",text:JSON.stringify(input)}]}],text:{format:{type:"json_schema",name:"h38_quick_meeting_notes",strict:true,schema:schema()}}}),signal:AbortSignal.timeout(120000)});const payload=await readJson(response);if(!response.ok)throw Error(text((payload.error as J|undefined)?.message||payload.message||`Meeting notes returned ${response.status}.`,3000));const raw=outputText(payload);if(!raw)throw Error("Meeting-note AI returned no notes.");const parsed=JSON.parse(raw) as J;return{discussed:cleanList(parsed.discussed),decisions:cleanList(parsed.decisions),actionItems:cleanList(parsed.actionItems),followUp:cleanList(parsed.followUp)};}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return reply(req,200,{status:"PASS",build:BUILD});if(req.method!=="POST")return reply(req,405,{status:"FAIL",message:"POST is required.",build:BUILD});try{const service=db(),form=await req.formData(),businessId=text(form.get("businessId"),180),customerId=text(form.get("customerId"),180),title=text(form.get("title"),300),typedNotes=text(form.get("typedNotes"),12000),candidate=form.get("audio"),audio=candidate instanceof File&&candidate.size?candidate:null;if(!businessId)throw Error("Business is required.");await authorize(req,service,businessId);if(!typedNotes&&!audio)throw Error("Record the meeting or type notes first.");let spoken="";if(audio)spoken=await transcribe(audio);const source=[typedNotes?`Typed context:\n${typedNotes}`:"",spoken?`Recorded meeting:\n${spoken}`:""].filter(Boolean).join("\n\n");const notes=await makeNotes(source,{title,customerId});return reply(req,200,{status:"PASS",notes,retention:{audioSaved:false,transcriptSaved:false,notesOnly:true},build:BUILD});}catch(error){console.warn("Quick meeting notes failed",text(error instanceof Error?error.message:error,500));return reply(req,400,{status:"FAIL",message:text(error instanceof Error?error.message:error,3000),build:BUILD});}});
