import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Any=Record<string,any>;
const BASE=Deno.env.get("SUPABASE_URL")||"";
const ORIGINS=new Set(["https://appassets.androidplatform.net","https://highway38solutions.com","https://www.highway38solutions.com"]);
const SOURCES=[
 {name:"RetailShout DG",retailer:"dollar general",url:"https://retailshout.com/latest-dollar-general-penny-items-near-you/"},
 {name:"RetailShout Dollar Tree",retailer:"dollar tree",url:"https://retailshout.com/latest-dollar-tree-penny-items-near-you/"}
];
const TTL=10*60*1000;type Cache={html:string,at:number,error?:string};const cache=new Map<string,Cache>();
function cors(r:Request){const o=r.headers.get("origin")||"";return{"access-control-allow-origin":ORIGINS.has(o)?o:"https://appassets.androidplatform.net","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"private, max-age=90","vary":"Origin"}}
function json(r:Request,s:number,b:any){return new Response(JSON.stringify(b),{status:s,headers:cors(r)})}
function clean(v:any){return String(v??"").trim()}
function rawDigits(v:any){return clean(v).replace(/\D/g,"")}
function key(v:any){return rawDigits(v).replace(/^0+/,"")}
function retailer(v:any){return clean(v?.retailer??v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function code(row:Any){for(const v of [row?.upc,row?.gtin,row?.barcode]){const x=rawDigits(v);if(x.length>=7)return x}const s=rawDigits(row?.sku);return s.length>=10?s:""}
function decode(v:string){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#0*39;|&apos;/gi,"'").replace(/&nbsp;/gi," ").replace(/\\u0026/gi,"&").replace(/\\\//g,"/")}
function abs(v:string,base:string){try{return new URL(decode(v),base).toString()}catch{return""}}
function safe(url:string){try{const u=new URL(url);return u.protocol==="https:"&&!/(?:logo|icon|avatar|spinner|placeholder|pixel|favicon|tracking|blank|loading)/i.test(u.pathname+u.search)}catch{return false}}
function imageTag(tag:string,base:string){const raws:string[]=[];for(const m of tag.matchAll(/(?:data-src|data-lazy-src|data-original|src)=["']([^"']+)["']/gi))raws.push(m[1]);const set=tag.match(/(?:data-srcset|srcset)=["']([^"']+)["']/i)?.[1]||"";for(const p of set.split(",")){const x=p.trim().split(/\s+/)[0];if(x)raws.push(x)}for(const x of raws){const u=abs(x,base);if(u&&safe(u))return u}return""}
function text(v:string){return decode(v).replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function pennyDate(segment:string){const m=text(segment).match(/\bPenny\s+Date\s*:\s*((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)[a-z]*\s+\d{1,2},\s+20\d{2})\b/i);return m?.[1]||""}
async function page(src:typeof SOURCES[number]){const c=cache.get(src.url);if(c&&Date.now()-c.at<TTL)return c;try{const r=await fetch(src.url,{headers:{"user-agent":"Mozilla/5.0 H38ResellerScout/2.0.1","accept":"text/html,application/xhtml+xml","accept-language":"en-US,en;q=0.9"},redirect:"follow",signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(`HTTP ${r.status}`);const x={html:await r.text(),at:Date.now()};cache.set(src.url,x);return x}catch(e){const x={html:"",at:Date.now(),error:e instanceof Error?e.message:String(e)};cache.set(src.url,x);return x}}
function buildIndex(html:string,base:string){const out=new Map<string,Any>(),occ=[...html.matchAll(/\bUPC(?:\s*(?:Code|#))?\s*[:\-]?\s*([0-9][0-9\s-]{5,20}[0-9])/gi)].map(m=>({at:m.index||0,end:(m.index||0)+m[0].length,code:rawDigits(m[1])})).filter(x=>x.code.length>=7&&x.code.length<=14);for(let i=0;i<occ.length;i++){const cur=occ[i],end=i+1<occ.length?occ[i+1].at:Math.min(html.length,cur.at+6000),segment=html.slice(cur.at,end),tag=segment.match(/<img\b[^>]*>/i)?.[0]||"",image=imageTag(tag,base);if(!image)continue;const k=key(cur.code);if(!k||out.has(k))continue;out.set(k,{image_url:image,image_reference_url:base,image_match_barcode:cur.code,pennied_at:pennyDate(segment),image_source:"RetailShout exact UPC"})}return out}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,405,{error:"POST required"});try{const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";if(!auth)return json(req,401,{error:"Sign in required"});const raw=await req.text(),up=await fetch(`${BASE}/functions/v1/reseller-auto-leads-v051`,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json"},body:raw||"{}",signal:AbortSignal.timeout(55000)}),payload=await up.json().catch(()=>({}));if(!up.ok)return json(req,up.status,{error:payload?.error||"Lead source failed"});const sourceRows=await Promise.all(SOURCES.map(async s=>{const p=await page(s);return{s,p,index:p.html?buildIndex(p.html,s.url):new Map<string,Any>()}})),health:Any={};for(const x of sourceRows)health[x.s.name]={status:x.p.html?"available":"unavailable",indexed:x.index.size,error:x.p.error||""};let added=0,dates=0;const leads=(Array.isArray(payload.leads)?payload.leads:[]).map((row:Any)=>{const c=code(row),k=key(c);if(!c||!k)return row;const src=sourceRows.find(x=>x.s.retailer===retailer(row)),hit=src?.index.get(k);if(!hit)return row;let next={...row};if(!clean(next.image_url)){next={...next,image_url:hit.image_url,image_source:hit.image_source,image_reference_url:hit.image_reference_url,image_match_barcode:c};added++}if(hit.pennied_at&&!clean(next.pennied_at)&&String(next.deal_type||"").toLowerCase()==="penny"){next.pennied_at=hit.pennied_at;next.penny_start_source=hit.image_source;dates++}return next});const warnings=[...(Array.isArray(payload.warnings)?payload.warnings:[])];for(const [n,h] of Object.entries(health) as any)if(h.status!=="available")warnings.push(`${n} visual source unavailable; lead evidence remains unchanged.`);console.log(JSON.stringify({event:"reseller-v058-exact-boundary-v201",photo_added:added,penny_dates_added:dates,health}));return json(req,200,{...payload,status:payload.status||"PASS",leads,count:leads.length,adapter_version:"v058-exact-upc-boundary-v201",dg_exact_visual_enriched_count:added,dg_exact_penny_date_enriched_count:dates,visual_source_health:health,warnings,visual_rule:"For DG/DT, exact UPC is located first and only the image before the next UPC boundary may be attached. Existing images/dates are never overwritten."})}catch(e){return json(req,503,{error:e instanceof Error?e.message:String(e)})}});
