/** Highway 38 Business Office — owner-configured internal task assignment rules. */
var H38_TASK_RULES_SHEET = 'BO Task Assignment Rules';
var H38_TASK_RULE_HEADERS = [
  'Rule ID','Business ID','Rule Name','Trigger','Assigned User ID','Assigned Role',
  'Task Title Template','Task Type','Priority','Due Offset Days','Instructions Template',
  'Match Field','Match Value','Status','Created By User ID','Created Time','Updated Time',
  'Last Run Time','Is Voided'
];
var H38_TASK_RULE_TRIGGERS = Object.freeze([
  {value:'request.created',label:'New request created',module:'requests',recordType:'Request'},
  {value:'quote.approved',label:'Quote approved or accepted',module:'quotes',recordType:'Quote'},
  {value:'job.created',label:'New job created',module:'jobs',recordType:'Job'},
  {value:'job.completed',label:'Job completed',module:'jobs',recordType:'Job'},
  {value:'invoice.created',label:'New invoice created',module:'invoices',recordType:'Invoice'},
  {value:'invoice.overdue',label:'Invoice becomes overdue',module:'invoices',recordType:'Invoice'},
  {value:'payment.review',label:'Payment needs owner review',module:'payments',recordType:'Payment'}
]);

function h38TaskRuleNow_(){return typeof h38TmNow_ === 'function' ? h38TmNow_() : Utilities.formatDate(new Date(),boPackValue_('business.timeZone','America/Chicago'),'yyyy-MM-dd HH:mm:ss');}
function h38TaskRuleId_(){return typeof h38TmId_ === 'function' ? h38TmId_('TASK-RULE') : 'TASK-RULE-'+Utilities.getUuid().slice(0,8).toUpperCase();}
function h38TaskRuleManageAll_(){var user=boGetCurrentUser_();return {user:user,manage:typeof h38TmManageAll_==='function'&&h38TmManageAll_(user)};}
function h38TaskRuleRequireManager_(){var access=h38TaskRuleManageAll_();boAssert_(access.manage,'Owner or Administrator access is required to manage task assignment rules.');return access.user;}
function h38TaskRuleSheet_(create){var ss=boGetSpreadsheet_(),sheet=ss.getSheetByName(H38_TASK_RULES_SHEET);if(!sheet&&create){h38TaskRuleRequireManager_();sheet=ss.insertSheet(H38_TASK_RULES_SHEET);sheet.getRange(1,1,1,H38_TASK_RULE_HEADERS.length).setValues([H38_TASK_RULE_HEADERS]);sheet.setFrozenRows(1);boProof_('INITIALIZE_TASK_ASSIGNMENT_RULES','System',boGetBusinessId_(),'PASS','Created private task assignment rule storage.',boGetActiveEmail_());}return sheet;}
function h38TaskRuleRows_(includeVoided){var sheet=h38TaskRuleSheet_(false);if(!sheet)return [];var values=sheet.getDataRange().getDisplayValues();if(values.length<2)return [];var headers=values[0].map(boNormalizeText_);return values.slice(1).filter(function(row){return row.some(function(value){return value!=='';});}).map(function(row,index){var record={__rowNumber:index+2};headers.forEach(function(header,column){if(header)record[header]=row[column];});return record;}).filter(function(row){return (!row['Business ID']||row['Business ID']===boGetBusinessId_())&&(includeVoided||row['Is Voided']!=='Yes');});}
function h38TaskRuleWrite_(record,rowNumber){var sheet=h38TaskRuleSheet_(true),headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0].map(boNormalizeText_),row=headers.map(function(header){return Object.prototype.hasOwnProperty.call(record,header)?record[header]:'';});if(rowNumber)sheet.getRange(rowNumber,1,1,headers.length).setValues([row]);else sheet.appendRow(row);return record;}
function h38TaskRuleTrigger_(value){var found=H38_TASK_RULE_TRIGGERS.find(function(item){return item.value===boNormalizeText_(value);});boAssert_(found,'Choose a supported task assignment trigger.');return found;}
function h38TaskRuleValidateAssignee_(userId,role){userId=boNormalizeText_(userId);role=boNormalizeText_(role);boAssert_(userId||role,'Assign the rule to a user or role.');if(userId)boAssert_(h38TmUserById_(userId),'The selected assigned user is not active in this business.');if(role)boAssert_(h38TmRoleExists_(role),'The selected assigned role is not active.');return {userId:userId,role:role};}
function h38TaskRuleSave_(ruleId,values){var user=h38TaskRuleRequireManager_(),input=Object.assign({},values||{}),before=ruleId?h38TaskRuleRows_(true).find(function(row){return row['Rule ID']===ruleId;})||null:null;boAssert_(!ruleId||before,'The selected assignment rule was not found.');var trigger=h38TaskRuleTrigger_(input.Trigger||(before&&before.Trigger)),assignee=h38TaskRuleValidateAssignee_(input['Assigned User ID']||(before&&before['Assigned User ID']),input['Assigned Role']||(before&&before['Assigned Role'])),record=Object.assign({},before||{},input),now=h38TaskRuleNow_();delete record.__rowNumber;record['Rule ID']=ruleId||(before&&before['Rule ID'])||h38TaskRuleId_();record['Business ID']=boGetBusinessId_();record['Rule Name']=boNormalizeText_(record['Rule Name']);boAssert_(record['Rule Name'],'Rule name is required.');record.Trigger=trigger.value;record['Assigned User ID']=assignee.userId;record['Assigned Role']=assignee.role;record['Task Title Template']=boNormalizeText_(record['Task Title Template']);boAssert_(record['Task Title Template'],'Task title template is required.');record['Task Type']=boNormalizeText_(record['Task Type'])||'Workflow';record.Priority=['Urgent','High','Normal','Low'].indexOf(record.Priority)>=0?record.Priority:'Normal';record['Due Offset Days']=String(Math.max(0,Math.min(Number(record['Due Offset Days'])||0,365)));record.Status=boNormalizeText_(record.Status)==='Inactive'?'Inactive':'Active';record['Created By User ID']=before?before['Created By User ID']:user['User ID'];record['Created Time']=before?before['Created Time']:now;record['Updated Time']=now;record['Is Voided']='No';h38TaskRuleWrite_(record,before&&before.__rowNumber);boAudit_(before?'UPDATE':'CREATE',H38_TASK_RULES_SHEET,record['Rule ID'],before||{},record,'Task assignment rules');boProof_('TASK_RULE_'+(before?'UPDATE':'CREATE'),'Task Assignment Rule',record['Rule ID'],'PASS','Internal assignment configuration only; no external action.',user.Email);return record;}
function h38TaskRuleToggle_(ruleId,enabled){var user=h38TaskRuleRequireManager_(),before=h38TaskRuleRows_(true).find(function(row){return row['Rule ID']===ruleId;});boAssert_(before,'The selected assignment rule was not found.');var record=Object.assign({},before,{Status:enabled?'Active':'Inactive','Updated Time':h38TaskRuleNow_()});delete record.__rowNumber;h38TaskRuleWrite_(record,before.__rowNumber);boAudit_('UPDATE',H38_TASK_RULES_SHEET,ruleId,before,record,'Task assignment rule status');boProof_('TASK_RULE_TOGGLE','Task Assignment Rule',ruleId,'PASS',(enabled?'Enabled':'Disabled')+' internal assignment rule.',user.Email);return record;}
function h38TaskRuleRecordId_(module,row){var map={requests:'Request ID',quotes:'Quote ID',jobs:'Job ID',invoices:'Invoice ID',payments:'Payment ID'};return boNormalizeText_(row[map[module]]||'');}
function h38TaskRuleRecordType_(module){var map={requests:'Request',quotes:'Quote',jobs:'Job',invoices:'Invoice',payments:'Payment'};return map[module]||'';}
function h38TaskRuleRecordLabel_(module,row){return boNormalizeText_(row.Name||row['Project Title']||row['Quote Number']||row['Job Number']||row['Invoice Number']||row['Payment ID']||h38TaskRuleRecordId_(module,row));}
function h38TaskRuleTemplate_(template,module,row){var id=h38TaskRuleRecordId_(module,row),values={record:h38TaskRuleRecordType_(module),id:id,name:h38TaskRuleRecordLabel_(module,row),customer:boNormalizeText_(row['Customer ID']),status:boNormalizeText_(row.Status||row.Stage||row['Approval Status']),number:boNormalizeText_(row['Quote Number']||row['Job Number']||row['Invoice Number']||id)};return String(template||'').replace(/\{(record|id|name|customer|status|number)\}/g,function(_,key){return values[key]||'';}).trim();}
function h38TaskRuleDate_(offset){var date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()+Math.max(0,Number(offset)||0));return Utilities.formatDate(date,boPackValue_('business.timeZone','America/Chicago'),'yyyy-MM-dd');}
function h38TaskRuleMatches_(rule,row){var field=boNormalizeText_(rule['Match Field']),expected=boNormalizeText_(rule['Match Value']).toLowerCase();if(!field||!expected)return true;return boNormalizeText_(row[field]).toLowerCase().indexOf(expected)>=0;}
function h38TaskRuleDuplicateKey_(ruleId,module,recordId){return h38TmHash_(['AUTO-RULE',ruleId,module,recordId].join('|'));}
function h38TaskRuleCreateTask_(rule,module,row){if(!h38TaskRuleMatches_(rule,row))return {skipped:true,reason:'match'};var recordId=h38TaskRuleRecordId_(module,row);if(!recordId)return {skipped:true,reason:'missing-id'};var duplicateKey=h38TaskRuleDuplicateKey_(rule['Rule ID'],module,recordId),existing=h38TmRead_('TASKS',{includeVoided:true}).find(function(task){return task['Duplicate Key']===duplicateKey&&task['Is Voided']!=='Yes';});if(existing)return {duplicatePrevented:true,task:existing};var user=boGetCurrentUser_(),recordType=h38TaskRuleRecordType_(module),task={
  'Task Title':h38TaskRuleTemplate_(rule['Task Title Template'],module,row),
  'Task Type':rule['Task Type']||'Workflow',
  'Assigned User ID':rule['Assigned User ID']||'',
  'Assigned Role':rule['Assigned Role']||'',
  'Assigned By User ID':user['User ID']||'SYSTEM',
  Priority:rule.Priority||'Normal',
  'Due Date':h38TaskRuleDate_(rule['Due Offset Days']),
  Status:'Open',
  Instructions:h38TaskRuleTemplate_(rule['Instructions Template'],module,row),
  Notes:'Auto-assigned by rule '+rule['Rule Name']+'.',
  'Linked Record Type':recordType,
  'Linked Record ID':recordId,
  'Customer ID':row['Customer ID']||'',
  'Request ID':row['Request ID']||'',
  'Quote ID':row['Quote ID']||'',
  'Work Order ID':row['Work Order ID']||'',
  'Job ID':row['Job ID']||'',
  'Invoice ID':row['Invoice ID']||'',
  'Payment ID':row['Payment ID']||'',
  'Document ID':row['Document ID']||'',
  'Duplicate Key':duplicateKey,
  'Is Voided':'No'
};boAssert_(task['Task Title'],'The assignment rule produced an empty task title.');h38TaskRuleValidateAssignee_(task['Assigned User ID'],task['Assigned Role']);var saved=h38TmAppend_('TASKS',task);h38TmTaskHistory_(saved,null,'AUTO_ASSIGNED','Rule '+rule['Rule ID'],user);boProof_('TASK_AUTO_ASSIGN','Task',saved['Task ID'],'PASS','Rule '+rule['Rule ID']+' assigned internal work for '+recordType+' '+recordId+'. No external action.',user.Email);return {created:true,task:saved};}
function h38TaskRuleStatusText_(row){return [row.Status,row.Stage,row['Approval Status'],row['Customer Action'],row['Delivery Status']].join(' ').toLowerCase();}
function h38TaskRuleBalance_(row){var direct=Number(String(row['Balance Due']||'').replace(/[$,]/g,''));if(Number.isFinite(direct))return direct;var total=Number(String(row.Total||0).replace(/[$,]/g,''))||0,paid=Number(String(row['Amount Paid']||row.Paid||0).replace(/[$,]/g,''))||0;return Math.max(0,total-paid);}
function h38TaskRulePast_(value){var parsed=Date.parse(boNormalizeText_(value));if(!Number.isFinite(parsed))return false;var today=new Date();today.setHours(0,0,0,0);return parsed<today.getTime();}
function h38TaskRuleCandidates_(trigger){var spec=h38TaskRuleTrigger_(trigger),rows=boListRecords(spec.module,{limit:1000,includeVoided:false});if(trigger==='quote.approved')return rows.filter(function(row){return /approved|accepted/.test(h38TaskRuleStatusText_(row));});if(trigger==='job.completed')return rows.filter(function(row){return /complete|completed|closed/.test(h38TaskRuleStatusText_(row));});if(trigger==='invoice.overdue')return rows.filter(function(row){return h38TaskRuleBalance_(row)>0&&(h38TaskRulePast_(row['Due Date'])||/overdue/.test(h38TaskRuleStatusText_(row)));});if(trigger==='payment.review')return rows.filter(function(row){return /required|review/.test(boNormalizeText_(row['Approval Status']).toLowerCase());});return rows;}
function h38TaskRuleEventsForSave_(module,before,saved){var events=[],afterText=h38TaskRuleStatusText_(saved||{}),beforeText=h38TaskRuleStatusText_(before||{});if(!before){if(module==='requests')events.push('request.created');if(module==='jobs')events.push('job.created');if(module==='invoices')events.push('invoice.created');}if(module==='quotes'&&/approved|accepted/.test(afterText)&&!/approved|accepted/.test(beforeText))events.push('quote.approved');if(module==='jobs'&&/complete|completed|closed/.test(afterText)&&!/complete|completed|closed/.test(beforeText))events.push('job.completed');if(module==='payments'&&/required|review/.test(boNormalizeText_((saved||{})['Approval Status']).toLowerCase())&&!/required|review/.test(boNormalizeText_((before||{})['Approval Status']).toLowerCase()))events.push('payment.review');return events;}
function h38TmApplyAssignmentRulesForSave_(module,before,saved){var rules=h38TaskRuleRows_(false).filter(function(rule){return rule.Status==='Active';}),events=h38TaskRuleEventsForSave_(module,before,saved),result={created:0,duplicates:0,errors:[],events:events};events.forEach(function(eventKey){rules.filter(function(rule){return rule.Trigger===eventKey;}).forEach(function(rule){try{var outcome=h38TaskRuleCreateTask_(rule,module,saved);if(outcome.created)result.created++;if(outcome.duplicatePrevented)result.duplicates++;}catch(error){result.errors.push({ruleId:rule['Rule ID'],message:String(error&&error.message||error)});}});});return result;}
function h38TaskRuleRun_(options){h38TaskRuleRequireManager_();var opts=options||{},rules=h38TaskRuleRows_(false).filter(function(rule){return rule.Status==='Active'&&(!opts.ruleId||rule['Rule ID']===opts.ruleId);}),summary={rules:rules.length,records:0,created:0,duplicates:0,skipped:0,errors:[],externalActionsOccurred:false};rules.forEach(function(rule){var spec=h38TaskRuleTrigger_(rule.Trigger),rows=[];try{rows=h38TaskRuleCandidates_(rule.Trigger).slice(0,Math.max(1,Math.min(Number(opts.limit)||500,1000)));summary.records+=rows.length;rows.forEach(function(row){try{var result=h38TaskRuleCreateTask_(rule,spec.module,row);if(result.created)summary.created++;else if(result.duplicatePrevented)summary.duplicates++;else summary.skipped++;}catch(error){summary.errors.push({ruleId:rule['Rule ID'],recordId:h38TaskRuleRecordId_(spec.module,row),message:String(error&&error.message||error)});}});var before=Object.assign({},rule),updated=Object.assign({},rule,{'Last Run Time':h38TaskRuleNow_(),'Updated Time':h38TaskRuleNow_()});delete updated.__rowNumber;h38TaskRuleWrite_(updated,rule.__rowNumber);boAudit_('UPDATE',H38_TASK_RULES_SHEET,rule['Rule ID'],before,updated,'Task assignment rule run');}catch(error2){summary.errors.push({ruleId:rule['Rule ID'],message:String(error2&&error2.message||error2)});}});boProof_('TASK_ASSIGNMENT_RULE_RUN','System',boGetBusinessId_(),summary.errors.length?'HOLD':'PASS','Rules='+summary.rules+'; records='+summary.records+'; tasks created='+summary.created+'; duplicates='+summary.duplicates+'; external actions=0.',boGetActiveEmail_());return summary;}
function h38TaskRuleWorkload_(){var rows=h38TmListTasks_({limit:1000}),open=rows.filter(function(row){return !/^(Completed|Cancelled)$/i.test(row.Status);}),users=h38PortalTaskMessagingAssignees(),items=[];(users.users||[]).forEach(function(user){var assigned=open.filter(function(row){return row['Assigned User ID']===user.id;});items.push({key:user.id,label:user.name,type:'User',open:assigned.length,urgent:assigned.filter(function(row){return row.Priority==='Urgent'||row.Priority==='High';}).length,overdue:assigned.filter(function(row){return row['Display Status']==='Overdue';}).length});});(users.roles||[]).forEach(function(role){var assigned=open.filter(function(row){return !row['Assigned User ID']&&row['Assigned Role']===role.name;});items.push({key:role.name,label:role.name,type:'Role',open:assigned.length,urgent:assigned.filter(function(row){return row.Priority==='Urgent'||row.Priority==='High';}).length,overdue:assigned.filter(function(row){return row['Display Status']==='Overdue';}).length});});return {open:open.length,completed:rows.length-open.length,items:items};}
function h38TaskRuleSeedStarters_(){var user=h38TaskRuleRequireManager_(),existing=h38TaskRuleRows_(false);boAssert_(!existing.length,'Starter rules can only be installed when no assignment rules exist.');var userId=user['User ID'],starters=[
  {name:'Review new request',trigger:'request.created',title:'Review new request: {name}',type:'Intake',priority:'High',due:0,instructions:'Verify the request, customer details, scope, and next action.'},
  {name:'Prepare approved quote',trigger:'quote.approved',title:'Prepare approved quote for work: {number}',type:'Quote follow-through',priority:'High',due:0,instructions:'Confirm the approved scope and prepare the job/work-order handoff.'},
  {name:'Plan new job',trigger:'job.created',title:'Plan and assign job: {name}',type:'Job planning',priority:'High',due:1,instructions:'Confirm field assignment, schedule, materials, and customer commitments before release.'},
  {name:'Close completed job',trigger:'job.completed',title:'Review completed job: {name}',type:'Job closeout',priority:'Normal',due:0,instructions:'Verify completion evidence, remaining issues, and invoice readiness.'},
  {name:'Review new invoice',trigger:'invoice.created',title:'Review invoice: {number}',type:'Billing review',priority:'Normal',due:0,instructions:'Review the draft invoice and preserve the owner approval gate before customer delivery.'},
  {name:'Follow up overdue invoice',trigger:'invoice.overdue',title:'Review overdue invoice: {number}',type:'Payment follow-up',priority:'High',due:0,instructions:'Review the account and prepare a customer follow-up for owner approval. Do not send automatically.'}
];return starters.map(function(item){return h38TaskRuleSave_('',{'Rule Name':item.name,Trigger:item.trigger,'Assigned User ID':userId,'Assigned Role':'','Task Title Template':item.title,'Task Type':item.type,Priority:item.priority,'Due Offset Days':item.due,'Instructions Template':item.instructions,Status:'Active'});});}
function h38PortalTaskAssignmentCenter(){var access=h38TaskRuleManageAll_();boAssert_(access.manage,'Owner or Administrator access is required to view team assignment controls.');var assignees=h38PortalTaskMessagingAssignees();return {status:'PASS',rules:h38TaskRuleRows_(false),triggers:H38_TASK_RULE_TRIGGERS,users:assignees.users||[],roles:assignees.roles||[],workload:h38TaskRuleWorkload_(),externalActionsEnabled:false};}
function h38PortalTaskAssignmentRuleSave(ruleId,values){return h38TaskRuleSave_(ruleId||'',values||{});}
function h38PortalTaskAssignmentRuleToggle(ruleId,enabled){return h38TaskRuleToggle_(ruleId,enabled===true);}
function h38PortalTaskAssignmentRun(options){return h38TaskRuleRun_(options||{});}
function h38PortalTaskAssignmentSeedStarters(){return {status:'PASS',rules:h38TaskRuleSeedStarters_(),externalActionsOccurred:false};}
